### PR TITLE
server: fix incorrectly reported token probabilities

### LINKED ISSUE #7093: Completion probabilities exceed 100% with top_p < 1
When using the server, I've observed that with a `top_p` value less than 1 (like the default of 0.95), the sum of the completion probabilities in the returned distributions is exceeding 1. In some cases, significantly (e.g. reaching 1.2).

llama.cpp version: [b2779](https://github.com/ggerganov/llama.cpp/releases/tag/b2779)

### Steps to reproduce

Start server:
```bash
./server -m models/qwen1_5-1_8b-chat-q4_0.gguf`
```

Request:
```bash
curl --request POST \
     --url http://localhost:8080/completion \
     --header "Content-Type: application/json" \
     --data '{"prompt": "It is amazing how much our world", "n_predict": 3, "n_probs": 10, "top_p": 0.95}'
```

Response:
```json
{
  "content": " has changed over",
  "id_slot": 0,
  "stop": true,
  "model": "models/qwen1_5-1_8b-chat-q4_0.gguf",
  "tokens_predicted": 3,
  "tokens_evaluated": 7,
  "generation_settings": {
    "n_ctx": 512,
    "n_predict": -1,
    "model": "models/qwen1_5-1_8b-chat-q4_0.gguf",
    "seed": 4294967295,
    "temperature": 0.800000011920929,
    "dynatemp_range": 0.0,
    "dynatemp_exponent": 1.0,
    "top_k": 40,
    "top_p": 0.949999988079071,
    "min_p": 0.05000000074505806,
    "tfs_z": 1.0,
    "typical_p": 1.0,
    "repeat_last_n": 64,
    "repeat_penalty": 1.0,
    "presence_penalty": 0.0,
    "frequency_penalty": 0.0,
    "penalty_prompt_tokens": [],
    "use_penalty_prompt_tokens": false,
    "mirostat": 0,
    "mirostat_tau": 5.0,
    "mirostat_eta": 0.10000000149011612,
    "penalize_nl": false,
    "stop": [],
    "n_keep": 0,
    "n_discard": 0,
    "ignore_eos": false,
    "stream": false,
    "logit_bias": [],
    "n_probs": 10,
    "min_keep": 0,
    "grammar": "",
    "samplers": ["top_k", "tfs_z", "typical_p", "top_p", "min_p", "temperature"]
  },
  "prompt": "It is amazing how much our world",
  "truncated": false,
  "stopped_eos": false,
  "stopped_word": false,
  "stopped_limit": true,
  "stopping_word": "",
  "tokens_cached": 9,
  "timings": {
    "prompt_n": 7,
    "prompt_ms": 372.6,
    "prompt_per_token_ms": 53.228571428571435,
    "prompt_per_second": 18.786902844873858,
    "predicted_n": 3,
    "predicted_ms": 190.64,
    "predicted_per_token_ms": 63.54666666666666,
    "predicted_per_second": 15.736466638690727
  },
  "completion_probabilities": [
    {
      "content": " has",
      "probs": [
        { "tok_str": " has", "prob": 0.9287585020065308 },
        { "tok_str": " changes", "prob": 0.036657482385635376 },
        { "tok_str": " is", "prob": 0.034583963453769684 },
        { "tok_str": " can", "prob": 0.017485665157437325 },
        { "tok_str": " ______", "prob": 0.007350301370024681 },
        { "tok_str": " and", "prob": 0.006574820727109909 },
        { "tok_str": " revolves", "prob": 0.0038582286797463894 },
        { "tok_str": " __", "prob": 0.0033750736620277166 },
        { "tok_str": " changed", "prob": 0.0031072746496647596 },
        { "tok_str": " depends", "prob": 0.002843035152181983 }
      ]
    },
    {
      "content": " changed",
      "probs": [
        { "tok_str": " changed", "prob": 1.0 },
        { "tok_str": " evolved", "prob": 0.015449372120201588 },
        { "tok_str": " advanced", "prob": 0.005510618910193443 },
        { "tok_str": " been", "prob": 0.004084543325006962 },
        { "tok_str": " transformed", "prob": 0.0026381351053714752 },
        { "tok_str": " grown", "prob": 0.002358403755351901 },
        { "tok_str": " improved", "prob": 0.002303898800164461 },
        { "tok_str": " developed", "prob": 0.0017443477408960462 },
        { "tok_str": " ______", "prob": 0.0011860313825309277 },
        { "tok_str": " __", "prob": 0.000809003715403378 }
      ]
    },
    {
      "content": " over",
      "probs": [
        { "tok_str": " in", "prob": 0.62572181224823 },
        { "tok_str": " over", "prob": 0.198844775557518 },
        { "tok_str": " since", "prob": 0.17543338239192963 },
        { "tok_str": ".", "prob": 0.022418279200792313 },
        { "tok_str": " just", "prob": 0.011968874372541904 },
        { "tok_str": ",", "prob": 0.010632796213030815 },
        { "tok_str": " and", "prob": 0.004682034719735384 },
        { "tok_str": " with", "prob": 0.004631646443158388 },
        { "tok_str": " during", "prob": 0.004250160418450832 },
        { "tok_str": " within", "prob": 0.0036900020204484463 }
      ]
    }
  ]
}
```

### Expected Behavior

The sum of the probabilities should ideally equal 100% (or very close due to potential floating-point rounding errors).

### Actual Behavior

The sum of probabilities is exceeding 100%.

### PR DESCRIPTION
**Pull request by JohannesGaessler**
Fixes https://github.com/ggerganov/llama.cpp/issues/7093 .

The problem on master is that the server unconditionally reports the token probabilities stored for the top tokens even if they were *not actually considered for sampling*. This then, among other things, causes the sum of token probabilities to exceed 100%. In total this PR fixes the following issues:

* Tokens failing top_p/min_p check being reported to have nonzero probability.
* Setting a temperature <= 0 not actually resulting in the top token having a reported probability of 1 with all others being reported as 0.
* When setting n_probs > top_k the returned "top tokens" are essentially undefined.

To make this work I am extending `ctx_sampling` with a property `n_considered` that stores how many of the top tokens were actually used for sampling. This can then be used to determine if and how many top tokens need to be fetched and starting at what index all token probabilities should be zero.

### CODE REVIEW

File: examples/server/server.cpp [hunk 1]
```diff
@@ -2266,17 +2266,31 @@ struct server_context {
...
-                    result.probs.push_back({
-                        cur_p.data[i].id,
-                        cur_p.data[i].p
-                    });
+                    // Make sure at least n_probs top tokens are at the front of the vector:
+                    if (n_probs > n_considered) {
+                        llama_sample_top_k(ctx, &cur_p, n_probs, 0);
+                    }
+
+                    if (slot.sparams.temp <= 0.0f) {
```
Comment (ggerganov) [inline examples/server/server.cpp:2278]: Should this check just equality?

```suggestion
                    if (slot.sparams.temp == 0.0f) {
```

For sub-zero temperatures, we calculate the probabilities, though they are never used:

https://github.com/ggerganov/llama.cpp/blob/3af34c1d1b0da47f85b95f60922abeded1cb5d33/common/sampling.cpp#L196-L202

I guess either way makes sense

**Review by ggerganov — APPROVED** [review]

File: examples/server/server.cpp (hunk 1 above)
Comment (JohannesGaessler) [reply examples/server/server.cpp]: No, I think that it's better to be consistent if at all possible. I changed it to an equality and added a note to the documentation. (I also noticed and fixed a bug where for temperature 0.0f the "top tokens" were wrong.)
