### PR TITLE
server : refactor middleware and /health endpoint

### LINKED ISSUE #7787: Refactor: investigate cleaner exception handling for server/server.cpp
### Background Description

In https://github.com/ggerganov/llama.cpp/pull/7642 @0wwafa observed unhanded exceptions on windows, but didn't provide a concrete example of a failure to load replications steps, so the root cause is unknown. He assert that every exception should be catched globally.

However @ngxson mentioned that we should do a more local try catch focused on `ctx_server.init()` as it makes no sense to cover `ctx_server.load_model(params)` which will always return false. 0wwafa opted afterwards to close the PR.

Considering that he did observe an exception around this area, we should at least give this spot a lookover to ensure all error cases are handled.

If done so, make sure to at least credit @0wwafa in the commit for the general observation.

### Possible Refactor Approaches

* See if we can restrict the error handling to ctx_server.init() or closer to the error source.

### PR DESCRIPTION
**Pull request by ngxson**
## `/health` endpoint

In the beginning, `/health` endpoint was used to retrieve slots state. That was because at the time, `/completions` endpoint returns an error if there is no slot available. Therefore, `/health` was used to allow the application to wait until one slot is available.

Nowadays, the server now can queue (defer) the request if no slots is available. `/health` is used by docker for health checking. This is now become a problem when the server is busy doing a long task, `/health` can timeout. On HF inference endpoint, this causes the container to be in unhealthy state, which triggers a force restart.

Therefore, I propose a cleaner usage:
- `GET /health` is now purely used to report actual health
- `GET /slots` can be used as a replacement to get slot state

As a consequence, `/health?fail_on_no_slot=1` is also moved to `/slots?fail_on_no_slot=1` (for compatibility, we keep this option)

## Refactor middleware

Some repeated code blocks, for example setting `Access-Control-Allow-Origin`, is now moved to middleware.

Middleware now also responsible to return error if the server is not yet ready:

When the server starts, if the model is being loaded, accessing to **any endpoint** will result in 503 error code:

image

## Behavior on loading model failed

If model fails to load (for example, file does not exist), the server will simply **exit with status code 1**. This resolves #7787 where user reports that loading invalid model causes the server to crash.

image

---

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

File: examples/server/server.cpp [hunk 1]
```diff
@@ -689,12 +690,11 @@ struct server_context {
         if (model == nullptr) {
             LOG_ERROR("unable to load model", {{"model", params.model}});
             return false;
+        } else {
+            n_ctx = llama_n_ctx(ctx);
+            add_bos_token = llama_add_bos_token(model);
+            has_eos_token = !llama_add_eos_token(model);
         }
```
Comment (ggerganov) [inline examples/server/server.cpp:697]: No need for the `else` because of the `return`:

```suggestion
        }

        n_ctx = llama_n_ctx(ctx);

        add_bos_token = llama_add_bos_token(model);
        has_eos_token = !llama_add_eos_token(model);

```

**Review by ggerganov — APPROVED** [review]
