### PR TITLE
main : add -sysf / --system-prompt-file (#12249)

### LINKED ISSUE #12249: Misc. bug:
### Name and Version

version: 4837 (e721c05c)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-cli

### Command line

```shell

```

### Problem description & steps to reproduce

Following commit 45a8e76 (release b4797), `--system-prompt`/`-sys` has now been introduced to use a system prompt. This is something I appreciate as it clarifies the command line somewhat.

However I have my system prompt in a file that I load with `--file`. This previously allowed me to update the prompt without having to retest the whole code.

There does not seem to be an equivalent for `--system-prompt`/`-sys` according to the `--help` information.

For additional context, `--file` used to load the contents of the file as a prompt, the first of which would be treated as a system prompt.

### First Bad Commit

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by CISC**
Fixes #12249

### CODE REVIEW

File: common/common.h [hunk 1]
```diff
@@ -276,6 +276,7 @@ struct common_params {
     std::string prompt               = "";                                                                  // NOLINT
     std::string system_prompt        = "";                                                                  // NOLINT
     std::string prompt_file          = ""; // store the external prompt file name                           // NOLINT
+    std::string system_prompt_file   = ""; // store the external system prompt file name                    // NOLINT
```
Comment (ngxson) [inline common/common.h:279]: Since no examples are using this, we can delete it for now.

Comment (CISC) [reply common/common.h]: I figured it might come in use later, but sure.

File: common/arg.cpp [hunk 2]
```diff
@@ -849,6 +849,20 @@ common_params_context common_params_parser_init(common_params & params, llama_ex
...
+        "a file containing the system prompt (default: none)",
+        [](common_params & params, const std::string & value) {
+            std::ifstream file(value);
+            if (!file) {
+                throw std::runtime_error(string_format("error: failed to open file '%s'\n", value.c_str()));
+            }
+            std::copy(std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>(), back_inserter(params.system_prompt));
+            if (!params.system_prompt.empty() && params.system_prompt.back() == '\n') {
+                params.system_prompt.pop_back();
+            }
```
Comment (ngxson) [inline common/arg.cpp:863]: This won't work if the file ends with double `\n\n` right?

Btw there is also `string_strip` in `common.h`

Comment (CISC) [reply common/arg.cpp:863]: True, copied from --file handling right above though...

Comment (CISC) [reply common/arg.cpp:863]: `string_strip` will remove all whitespace, I don't think that's the intention of this (and probably not what you'd want), but rather just remove the last "cosmetic" newline in a file.

Comment (CISC) [reply common/arg.cpp:863]: I don't think it makes sense to address this here, so marking as resolved as it behaves the same as --file. If it is desirable to improve this behavior (add \r and \r\n handling?) I suggest a new PR.

Comment (ngxson) [reply common/arg.cpp:863]: Ok to me, but anw I think either doing string_strip or just removing this code altogether.

Also if you're force to add a new line at the end of the file due to editorconfig, there is an ignore file in the project's root

**Review by ngxson — APPROVED** [review]

**Comment by CISC** [comment]
@ngxson Did you forget to merge?

**Comment by ngxson** [comment]
Ok sorry I thought you have the right to merge it
