### PR TITLE
mtmd : fix memory leak in mtmd_helper_eval_chunk_single

### LINKED ISSUE #13620: Misc. bug: batch in the mtmd-cli.cpp not freed
### Name and Version

latest version

### Operating systems

_No response_

### Which llama.cpp modules do you know to be affected?

_No response_

### Command line

```shell

```

### Problem description & steps to reproduce

I just found that the batch in the mtmd_cli_context of mtmd-cli.cpp is not freed with llama_batch_free .It is just some finding by code review , I am not very sure about it. 

### First Bad Commit

_No response_

### Relevant log output

```shell

```

### LINKED ISSUE #13958: Misc. bug: memory leak in mtmd ? (mtmd_helper_eval_chunk_single)
### Name and Version

llama.cpp integrated in a personal project, using CMake's FetchContent_Declare / FetchContent_Declare.

Version: 
int LLAMA_BUILD_NUMBER = 5544;
char const *LLAMA_COMMIT = "b49a8ff9";
char const *LLAMA_COMPILER = "Apple clang version 17.0.0 (clang-1700.0.13.5)";
char const *LLAMA_BUILD_TARGET = "arm64-apple-darwin24.5.0";

### Operating systems

Mac

### Which llama.cpp modules do you know to be affected?

Other (Please specify in the next section)

### Command line

```shell

```

### Problem description & steps to reproduce

I am reusing code similar to mdmd-cli, inside my application. For now, I am including code from tools/mtmd, in particular mdmd-helper.

I am seeing memory leaks stemming from mtmd_helper_eval_chunk_single. I think this is because text_batch seems to be left hanging on success and no reference is kept in the mtmd context so it can be freed once it's not needed any more. 

I'm still in the process of analysing this section of the code and I'm not sure how a fix should look. 
I'm only mentioning because it might be useful to someone else.

### First Bad Commit

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by ngxson**
Fix https://github.com/ggml-org/llama.cpp/issues/13958

Maybe we should have a C++ wrapper in `llama-cpp.h` for  `llama_batch` ?

### CODE REVIEW

**Review by DangNhutNguyen — APPROVED** [review]

File: tools/mtmd/mtmd-helper.cpp [hunk 1]
```diff
@@ -311,6 +311,7 @@ int32_t mtmd_helper_eval_chunk_single(mtmd_context * ctx,
         GGML_ABORT("chunk type not supported");
     }
 
+    llama_batch_free(text_batch);
```
Comment (evverx) [inline tools/mtmd/mtmd-helper.cpp:314]: FWIW It seems to fix the following direct leaks
```sh
Direct leak of 49176 byte(s) in 3 object(s) allocated from:                                                                                                   
    #0 0x0000004abdc8 in malloc (/llama.cpp/build/bin/llama-mtmd-cli+0x4abdc8) (BuildId: d0529438afdc212f2f3e006e74cba8cc230cfcc6)                            
    #1 0x7fcb42e3a64b in llama_batch_init /llama.cpp/src/llama-batch.cpp:358:40                                                                               
    #2 0x7fcb4337b518 in mtmd_helper_eval_chunk_single /llama.cpp/tools/mtmd/mtmd-helper.cpp:255:30                                                           
    #3 0x7fcb4337bcab in mtmd_helper_eval_chunks /llama.cpp/tools/mtmd/mtmd-helper.cpp:335:23                                                                 
    #4 0x0000004f3aa6 in eval_message(mtmd_cli_context&, common_chat_msg&, bool) /llama.cpp/tools/mtmd/mtmd-cli.cpp:222:9                                     
    #5 0x0000004f22fc in main /llama.cpp/tools/mtmd/mtmd-cli.cpp:300:13                                                                                       
    #6 0x7fcb425a95f4 in __libc_start_call_main (/lib64/libc.so.6+0x35f4) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)                                 
    #7 0x7fcb425a96a7 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x36a7) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)                          
    #8 0x0000004082b4 in _start (/llama.cpp/build/bin/llama-mtmd-cli+0x4082b4) (BuildId: d0529438afdc212f2f3e006e74cba8cc230cfcc6)     
...
```
but with this PR applied ASan still reports memory leaks in `llama-mtmd-cli`:
<details>
  <summary>SUMMARY: AddressSanitizer: 654872 byte(s) leaked in 2096 allocation(s).</summary>
  
  ```sh
Direct leak of 16392 byte(s) in 1 object(s) allocated from:                                                                                                   
    #0 0x0000004abdc8 in malloc (/llama.cpp/build/bin/llama-mtmd-cli+0x4abdc8) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)                            
    #1 0x7f748b1d464b in llama_batch_init /llama.cpp/src/llama-batch.cpp:358:40                                                                               
    #2 0x0000004f8d9e in mtmd_cli_context::mtmd_cli_context(common_params&) /llama.cpp/tools/mtmd/mtmd-cli.cpp:93:17                                          
    #3 0x0000004f1ea1 in main /llama.cpp/tools/mtmd/mtmd-cli.cpp:259:22                                                                                       
    #4 0x7f748a9435f4 in __libc_start_call_main (/lib64/libc.so.6+0x35f4) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)                                 
    #5 0x7f748a9436a7 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x36a7) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)                          
    #6 0x0000004082b4 in _start (/llama.cpp/build/bin/llama-mtmd-cli+0x4082b4) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)                            
                                                                                                                                                              
Direct leak of 8192 byte(s) in 1 object(s) allocated from:                                                                                                    
    #0 0x0000004abdc8 in malloc (/llama.cpp/build/bin/llama-mtmd-cli+0x4abdc8) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)                            
    #1 0x7f748b1d461e in llama_batch_init /llama.cpp/src/llama-batch.cpp:357:40                                                                               
    #2 0x0000004f8d9e in mtmd_cli_context::mtmd_cli_context(common_params&) /llama.cpp/tools/mtmd/mtmd-cli.cpp:93:17                                          
    #3 0x0000004f1ea1 in main /llama.cpp/tools/mtmd/mtmd-cli.cpp:259:22                                                                                       
    #4 0x7f748a9435f4 in __libc_start_call_main (/lib64/libc.so.6+0x35f4) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)                                 
    #5 0x7f748a9436a7 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x36a7) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)                          
    #6 0x0000004082b4 in _start (/llama.cpp/build/bin/llama-mtmd-cli+0x4082b4) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)                            
                                                                                                                                                              
Direct leak of 8192 byte(s) in 1 object(s) allocated from:                                                                                                    
    #0 0x0000004abdc8 in malloc (/llama.cpp/build/bin/llama-mtmd-cli+0x4abdc8) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)                            
    #1 0x7f748b1d45fa in llama_batch_init /llama.cpp/src/llama-batch.cpp:356:40                                                                               
    #2 0x0000004f8d9e in mtmd_cli_context::mtmd_cli_context(common_params&) /llama.cpp/tools/mtmd/mtmd-cli.cpp:93:17                                          
    #3 0x0000004f1ea1 in main /llama.cpp/tools/mtmd/mtmd-cli.cpp:259:22                                                                                       
    #4 0x7f748a9435f4 in __libc_start_call_main (/lib64/libc.so.6+0x35f4) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)                                 
    #5 0x7f748a9436a7 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x36a7) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)                          
    #6 0x0000004082b4 in _start (/llama.cpp/build/bin/llama-mtmd-cli+0x4082b4) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)                            
                                                                                                                                                              
Direct leak of 8192 byte(s) in 1 object(s) allocated from:                                                                                                    
    #0 0x0000004abdc8 in malloc (/llama.cpp/build/bin/llama-mtmd-cli+0x4abdc8) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)                            
    #1 0x7f748b1d45cb in llama_batch_init /llama.cpp/src/llama-batch.cpp                                                                                      
    #2 0x0000004f8d9e in mtmd_cli_context::mtmd_cli_context(common_params&) /llama.cpp/tools/mtmd/mtmd-cli.cpp:93:17                                          
    #3 0x0000004f1ea1 in main /llama.cpp/tools/mtmd/mtmd-cli.cpp:259:22                                                                                       
    #4 0x7f748a9435f4 in __libc_start_call_main (/lib64/libc.so.6+0x35f4) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)
    #5 0x7f748a9436a7 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x36a7) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)
    #6 0x0000004082b4 in _start (/llama.cpp/build/bin/llama-mtmd-cli+0x4082b4) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)

Direct leak of 2048 byte(s) in 1 object(s) allocated from:
    #0 0x0000004abdc8 in malloc (/llama.cpp/build/bin/llama-mtmd-cli+0x4abdc8) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)
    #1 0x7f748b1d46e0 in llama_batch_init /llama.cpp/src/llama-batch.cpp:364:40 
    #2 0x0000004f8d9e in mtmd_cli_context::mtmd_cli_context(common_params&) /llama.cpp/tools/mtmd/mtmd-cli.cpp:93:17
    #3 0x0000004f1ea1 in main /llama.cpp/tools/mtmd/mtmd-cli.cpp:259:22
    #4 0x7f748a9435f4 in __libc_start_call_main (/lib64/libc.so.6+0x35f4) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)
    #5 0x7f748a9436a7 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x36a7) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)
    #6 0x0000004082b4 in _start (/llama.cpp/build/bin/llama-mtmd-cli+0x4082b4) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)

Direct leak of 416 byte(s) in 1 object(s) allocated from:
    #0 0x0000004f07c1 in operator new(unsigned long) (/llama.cpp/build/bin/llama-mtmd-cli+0x4f07c1) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)
    #1 0x0000007f6a4f in common_sampler_init(llama_model const*, common_params_sampling const&) /llama.cpp/common/sampling.cpp:216:21
    #2 0x0000004f1fba in main /llama.cpp/tools/mtmd/mtmd-cli.cpp:264:36
    #3 0x7f748a9435f4 in __libc_start_call_main (/lib64/libc.so.6+0x35f4) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)
    #4 0x7f748a9436a7 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x36a7) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)
    #5 0x0000004082b4 in _start (/llama.cpp/build/bin/llama-mtmd-cli+0x4082b4) (BuildId: 693cd788cb564003831ab992f5b80d129be780e8)
```
</details>

**Comment by jmuffat** [comment]
FWIW, adding this line does fix the leak in my project without any noticeable side effects.

File: tools/mtmd/mtmd-helper.cpp (hunk 1 above)
Comment (ngxson) [reply tools/mtmd/mtmd-helper.cpp:314]: It should be fixed in https://github.com/ggml-org/llama.cpp/pull/13961/commits/6aaefb7c8683fcc73421756cfc91f92879378f35

Could you give it a try?

File: tools/mtmd/mtmd-cli.cpp [hunk 2]
```diff
@@ -70,6 +70,7 @@ struct mtmd_cli_context {
     llama_model       * model;
     llama_context     * lctx;
     const llama_vocab * vocab;
+    common_sampler    * smpl = nullptr;
```
Comment (ggerganov) [inline tools/mtmd/mtmd-cli.cpp]:
```suggestion
    common_sampler    * smpl;
```

**Review by ggerganov — APPROVED** [review]

File: tools/mtmd/mtmd-helper.cpp (hunk 1 above)
Comment (evverx) [reply tools/mtmd/mtmd-helper.cpp:314]: Looks like ASan no longer complains. Thanks!
