### PR TITLE
server: wrap headers for mcp proxy

### LINKED ISSUE #21012: Misc. bug: webui-mcp-proxy http header Authorization conflict
### Name and Version

./llama-cli --version
ggml_cuda_init: found 1 CUDA devices (Total VRAM: 124615 MiB):
  Device 0: NVIDIA GB10, compute capability 12.1, VMM: yes, VRAM: 124615 MiB
version: 8479 (cc18f965b)
built with GNU 13.3.0 for Linux aarch64

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
--api-key xxx --webui-mcp-proxy
```

### Problem description & steps to reproduce

start llama-server use --api-key xxx --webui-mcp-proxy, mcp remote server need Authorization header, webui-mcp-proxy also need this, cause error 401

### First Bad Commit

_No response_

### Relevant log output

<details>
<summary>Logs</summary>

```console

```
</details>

### PR DESCRIPTION
**Pull request by ngxson**
## Overview

Fix https://github.com/ggml-org/llama.cpp/issues/21012

Wrap the target header with `X-Proxy-Header-` prefix to avoid conflict with llama.cpp-specific headers

# Requirements

- I have read and agree with the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md)
- AI usage disclosure: NO

### CODE REVIEW

File: tools/server/server-cors-proxy.h [hunk 1]
```diff
@@ -32,13 +32,24 @@ static server_http_res_ptr proxy_request(const server_http_req & req, std::strin
...
+    std::map<std::string, std::string> headers;
+    for (auto [key, value] : req.headers) {
+        if (string_starts_with(key, "X-Proxy-Header-")) {
+            auto new_key = key;
+            string_replace_all(new_key, "X-Proxy-Header-", "");
+            headers[new_key] = value;
+        } else {
+            headers[key] = value;
+        }
+    }
```
Comment (ggerganov) [inline tools/server/server-cors-proxy.h:42]: Isn't this the same with less copies?

```suggestion
    for (auto [key, value] : req.headers) {
        if (string_starts_with(key, "X-Proxy-Header-")) {
            string_replace_all(key, "X-Proxy-Header-", "");
        }
        headers[key] = std::move(value);
    }
```

**Review by ggerganov — APPROVED** [review]

File: tools/server/server-cors-proxy.h (hunk 1 above)
Comment (ngxson) [reply tools/server/server-cors-proxy.h:42]: hmm, the `req.headers` is const so we cannot modify it, I fixed by copy the string: https://github.com/ggml-org/llama.cpp/pull/21072/commits/367752990dcf28c593605ba3353932a3b8a3f17d

**Review by allozaur — APPROVED** [review]

**Review by ServeurpersoCom — APPROVED** [review]

File: tools/server/server-cors-proxy.h (hunk 1 above)
Comment (ggerganov) [reply tools/server/server-cors-proxy.h:42]: The structured bindings `key` and `value` are already copies. So it's ok to modify them and move the `value` in the end. Either way is fine.

**Review by ggerganov — APPROVED** [review]
