### PR TITLE
TP: fix Qwen 3 Next data split

### LINKED ISSUE #21703: Misc. bug: Tensor parallelism causes loops
### Name and Version

❯ llama-cli --version
ggml_cuda_init: found 2 CUDA devices (Total VRAM: 64215 MiB):
  Device 0: NVIDIA GeForce RTX 5090, compute capability 12.0, VMM: yes, VRAM: 32106 MiB
  Device 1: NVIDIA GeForce RTX 5090, compute capability 12.0, VMM: yes, VRAM: 32109 MiB
version: 8740 (e34f04215)
built with GNU 13.3.0 for Linux x86_64

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-cli

### Command line

```shell
llama-cli -hf unsloth/Qwen3-Coder-Next-GGUF:MXFP4_MOE --split-mode tensor --temp 1.0 --top-p 0.95 --top-k 40 --min-p 0.01 --repeat-penalty 1.0
```

### Problem description & steps to reproduce

Testing the new tensor parallelism with my two 5090's.

>llama-cli -hf unsloth/Qwen3-Coder-Next-GGUF:MXFP4_MOE --split-mode tensor --temp 1.0 --top-p 0.95 --top-k 40 --min-p 0.01 --repeat-penalty 1.0

Simple prompt:  `Write me a python snake game`

Causes looping.  Without --split-mode tensor, task completes easily.

Example:
```
food.penup()  # to prevent showing lines when turtle not using tracers
food.shapesize(0.5)  # size of the snake (0.5 is big) and by the snake (0.5 is big) and by the snake (0.5 is big) and by the snake (0.5 is big) and by the snake (0.5 is big) and by the snake (0.5 is big) and by the snake (0.5 is big) and by the snake (0.5 is big) and by the snake (0.5 is big) and by the snake (0.5 is big!0.5 is big) and by the snake (0.5 is big!0.5 is big?0.5 is big?0.5 is big?0.5 is big?0.5 is big?0.5 is big?0.5 is big?0.5 is big?0.5 is big?0.5 is big?0.5 is big?0.5 is big?0.5 is big?0.5 is big?0
```

Running CUDA 13.2 and I compiled it myself

```
#!/bin/sh

rm -rf build
git pull

cmake -B build -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -DGGML_CUDA=ON -DGGML_CUDA_FA=ON -DLLAMA_CURL=ON -DGGML_RPC=ON -DLLAMA_BUILD_BORINGSSL=ON -DLLAMA_BUILD_LIBRESSL=ON #-DGGML_VULKAN=1
cmake --build build --config Release -j $(nproc)
```

### First Bad Commit

One of these? https://github.com/ggml-org/llama.cpp/pull/19378

### Relevant log output

No logs.

### PR DESCRIPTION
**Pull request by JohannesGaessler**
Fixes https://github.com/ggml-org/llama.cpp/issues/21703 .

The problem is that I had incorrectly assumed that Qwen 3 Next and Qwen 3.5 use the same broadcasting pattern for K across V. So for Qwen 3 Next 50% of the time the wrong K and V heads are being combined. This is not immediately obvious as the generated text can still look reasonable at first glance. However, it can be clearly detected by looking at PPL. The Q3_K_M quantization goes from a PPL of 7.48 to 4.32 on the first 512tokens of Wikitext-2.

# Requirements

- I have read and agree with the [contributing guidelines](https://github.com/ggml-org/llama.cpp/blob/master/CONTRIBUTING.md)
- AI usage disclosure: No

### CODE REVIEW

File: src/llama-model.cpp [hunk 1]
```diff
@@ -202,24 +202,37 @@ struct ggml_backend_meta_split_state llama_meta_device_get_split_state(const str
...
-            }
-            if (std::regex_match(tensor_name, pattern_r_cache)) {
-                return std::vector<int64_t>(2 + head_ratio, key_dim * (hparams.ssm_d_conv - 1));
-            }
-            if (std::regex_match(tensor_name, pattern_s_cache)) {
-                return std::vector<int64_t>(head_ratio, n_k_heads * head_v_dim * head_v_dim);
+
+            // both Qwen 3 Next and Qwen 3.5 support n_v_heads > n_k_heads but the broadcasting pattern is different:
+            //   - Qwen 3 Next: [k0_v0, k0_v1, k1_v2, k1_v3] (this is the default split pattern)
+            //   - Qwen 3.5:    [k0_v0, k1_v1, k0_v2, k1_v3] (needs segmenting of V on the scale of K to get teh correct pattern)
```
Comment (CISC) [inline src/llama-model.cpp]:
```suggestion
            //   - Qwen 3.5:    [k0_v0, k1_v1, k0_v2, k1_v3] (needs segmenting of V on the scale of K to get the correct pattern)
```

**Review by CISC — APPROVED** [review]

**Review by am17an — APPROVED** [review]

**Comment by JohannesGaessler** [comment]
@am17an @CISC sorry, it seems that fixing the typo has invalidated the approvals, can you re-approve?

**Review by am17an — APPROVED** [review]
