### PR TITLE
fix(perf/UX): Use num physical cores by default, warn about E/P cores

### LINKED ISSUE #932: perf: Investigate performance discrepancy with llama-rs - 1.5x-2x slower
Preliminary results show that `llama.cpp` is 1.5x-2x _slower_ than `llama-rs`. They were both checked to compile with the same arch flags and use the same gnu toolchain.

Summary (on `Vicuna 13B, 2048 ctx size, 256 predict tokens`):
- `llama.cpp`: **430.44 ms** per run
- `llama-rs`: per_token_duration: **272.793ms**

[Detailed results](https://github.com/rustformers/llama-rs/issues/131#issuecomment-1506246836)

An interesting observation is that CPU util is _lower_ on llama-rs.

System Info:

llama.cpp
```
> make
I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wno-unused-function -pthread -march=native -mtune=native
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native
I LDFLAGS:  
I CC:       cc (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0
I CXX:      g++ (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0

./main
system_info: n_threads = 16 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
```

llama-rs
```
warning: Using gnu
warning: Using MAVX
warning: Using AVX2
warning: Using FMA
warning: Using F16C
warning: Using SSE3
```
No BLAS.

Notes: llama-rs bench runs on [my branch](https://github.com/rustformers/llama-rs/pull/129).

### PR DESCRIPTION
**Pull request by jon-chuang**
Fixes: https://github.com/ggerganov/llama.cpp/issues/932

Hyperthreading is bad, probably because we are compute bound (not memory bound).

See also: https://github.com/ggerganov/llama.cpp/issues/34

Notes: I consulted GPT4 in the making of this PR.

### CODE REVIEW

File: examples/common.cpp [hunk 1]
```diff
@@ -34,9 +38,25 @@ bool gpt_params_parse(int argc, char ** argv, gpt_params & params) {
...
 #ifdef __linux__
     std::ifstream cpuinfo("/proc/cpuinfo");
-    params.n_threads = std::count(std::istream_iterator<std::string>(cpuinfo),
-                                  std::istream_iterator<std::string>(),
-                                  std::string("processor"));
+    std::string line;
+    while (std::getline(cpuinfo, line)) {
+        if (line.find("cpu cores") != std::string::npos) {
+            line.erase(0, line.find(": ") + 2);
+            params.n_threads = std::stoul(line);
```
Comment (jon-chuang) [inline examples/common.cpp:45]: Perhaps add a try-catch block here in case stoul does not parse an integer.

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoul
Aborted (core dumped)
```

**Comment by jon-chuang** [comment]
> without having access to a wide variety of machines.

This hasn't been tested on darwin or windows. I would appreciate CI or someone being able to test.

> How do the various methods compare to simply using std::thread::hardware_concurrency?

For Linux, I get the number of physical cores, rather than the logical cores provided by `std::thread::hardware_concurrency`. Perf is 1.5-2x better, which is a much better default.

> There's some more logic in the header file for n_threads, it would be nice to have this in one place.

I guess you mean here. I saw that too. Should we change all the logic to be in the header?
https://github.com/ggerganov/llama.cpp/blob/e7f6997f897a18b6372a6460e25c5f89e1469f1d/examples/common.h#L18

**Comment by jon-chuang** [comment]
> This is better kept in common.cpp. 

These pertain to the struct default, so, I suggest adding a function in the header, with impl in .cpp that contains this logic.

Function name is `get_default_physical_cpu_cores()`

**Comment by prusnak** [comment]
Btw, `sysctl hw.physicalcpu` returns 8 on M1 but it contains 4 hi-perf cores and 8 lo-perf cores. So you want to use only 4 threads on M1.

**Comment by KASR** [comment]
just as an fyi: i did some benchmark test for another issue ( see https://github.com/ggerganov/llama.cpp/issues/603#issuecomment-1490136086 )

this was done on a [Xeon W 2295](https://ark.intel.com/content/www/us/en/ark/products/198011/intel-xeon-w2295-processor-24-75m-cache-3-00-ghz.html) having 18 physical cores. However, at those benchmarks the performance was best either a bit below the number of physical cores or a bit above it. Also performance did increase when using more threads then the number of physical cores. So the settings will probably be system depended.

Perhaps it's an idea to include a benchmark script so that users can test the on their own system and determine the performance as function of system settings?

**Comment by jon-chuang** [comment]
> the performance was best either a bit below the number of physical cores or a bit above it.

The best performance is not the aim. 

It's to provide a _reasonable default_. 2X slower than optimal is not reasonable, but 10% slower is still reasonable IMO.

A bench script to loop through different n_threads and report results would definitely be a nice orthogonal improvement, and we could include it in the main Readme so some users actually get to using it.

**Comment by jon-chuang** [comment]
> Btw, sysctl hw.physicalcpu returns 8 on M1, but you want to use only 4 threads, because M1 contains 4 high-performance cores and 4 low-performance cores.

Hmm I see. There was a separate discussion about this type of Arch. Let me replicate the conclusions here. (I don't think there is a super nice solution in this case). 

I also wonder if the same thing applies to the new Intel CPUs with E and P cored.

**Comment by prusnak** [comment]
> Are you able to report some rough results of running 8 v.s. 4 cores in terms of the ms per token for inference mode?

7B 4 threads => 80ms/token
7B 8 threads => 167ms/token

13B 4 threads => 167ms/token
13B 8 threads => 320ms/token

So it's roughly 2x slower when using 8 cores (lo+hi) instead of 4 cores (hi only).

**Comment by prusnak** [comment]
Btw, this is the output of `sysctl -a | grep hw.perflevel` on my M1:

```
hw.perflevel0.physicalcpu: 4
hw.perflevel0.physicalcpu_max: 4
hw.perflevel0.logicalcpu: 4
hw.perflevel0.logicalcpu_max: 4
hw.perflevel0.l1icachesize: 196608
hw.perflevel0.l1dcachesize: 131072
hw.perflevel0.l2cachesize: 12582912
hw.perflevel0.cpusperl2: 4
hw.perflevel0.name: Performance
hw.perflevel1.physicalcpu: 4
hw.perflevel1.physicalcpu_max: 4
hw.perflevel1.logicalcpu: 4
hw.perflevel1.logicalcpu_max: 4
hw.perflevel1.l1icachesize: 131072
hw.perflevel1.l1dcachesize: 65536
hw.perflevel1.l2cachesize: 4194304
hw.perflevel1.cpusperl2: 4
hw.perflevel1.name: Efficiency
```

So we can detect the number of performance cores via `hw.perflevel0.physicalcpu`.

**Comment by prusnak** [comment]
> Anyone have a non-M1 mac? What is the result of grepping perflevel?

I confirmed that `hw.perflevel0.physicalcpu` exists on Intel iMac and Intel Macbook too. So we can use that first. If the value is not available we can fallback to `hw.physicalcpu`.

Suggestion for the code:

``` c++
    int result = sysctlbyname("hw.perflevel0.physicalcpu", &num_physical_cores, &len, NULL, 0);
    if (result == 0) {
        params.n_threads = num_physical_cores;
    } else {
        result = sysctlbyname("hw.physicalcpu", &num_physical_cores, &len, NULL, 0);
        if (result == 0) {
            params.n_threads = num_physical_cores;
        }
    }
```

**Comment by jon-chuang** [comment]
> I've uploaded the python script that i use as a gist

We should start with the default and then go up by a quarter step. There should also be a short warm up step of -n 16 or something.

I think we want to modify this by assuming a single global optimum and doing halving so we only need log n_cpu steps rather than n_cpu steps.

File: examples/common.cpp [hunk 2]
```diff
@@ -13,6 +13,10 @@
 #include <alloca.h>
 #endif
 
+#if defined(_WIN32) || defined(_WIN64)
+#include <windows.h>
```
Comment (prusnak) [inline examples/common.cpp:17]: Just move this include below into the `_WIN32` block.

`_WIN32` is always defined on Windows (even for on 64-bits), so there is no need to check for `_WIN64`

**Review by prusnak — CHANGES_REQUESTED** [review]

File: examples/common.cpp [hunk 3]
```diff
@@ -34,9 +38,27 @@ bool gpt_params_parse(int argc, char ** argv, gpt_params & params) {
...
+        }
+    }
+#elif defined(__APPLE__) && defined(__MACH__)
+    int num_physical_cores;
+    size_t len = sizeof(num_physical_cores);
+    int result = sysctlbyname("hw.physicalcpu", &num_physical_cores, &len, NULL, 0);
+    if (result == 0) {
+        params.n_threads = num_physical_cores;
+    }
+#elif defined(_WIN32) || defined(_WIN64)
```
Comment (prusnak) [inline examples/common.cpp:58]: Same here, don't use _WIN64

**Comment by jon-chuang** [comment]
> we clamp the default number of threads to maximum of 8

Not for @KASR 's case though https://github.com/ggerganov/llama.cpp/issues/603#issuecomment-1490136086

I think we should let the benchmark script speak for itself.

File: examples/common.cpp [hunk 4]
```diff
@@ -23,17 +24,41 @@ extern "C" __declspec(dllimport) int __stdcall WideCharToMultiByte(unsigned int
...
+    while (std::getline(cpuinfo, line)) {
+        if (line.find("cpu cores") != std::string::npos) {
+            line.erase(0, line.find(": ") + 2);
+            try {
+                return (int32_t) std::stoul(line);
+            } catch (std::invalid_argument& e) {} // Ignore if we could not parse
+        }
+    }
+#elif defined(__APPLE__) && defined(__MACH__)
+    int num_physical_cores;
```
Comment (prusnak) [inline examples/common.cpp:40]: Just use `int32` here and you don't need to cast it two times below. 
```suggestion
    int32 num_physical_cores;
```

**Review by prusnak — CHANGES_REQUESTED** [review]

**Comment by jon-chuang** [comment]
@MillionthOdin16 would you be able to check it this works on windows for you? (does it show num_physical_cores as the default when running lamma.cpp)

**Comment by jon-chuang** [comment]
> I confirmed that hw.perflevel0.physicalcpu exists on Intel iMac and Intel Macbook too. So we can use that first. If the value is not available we can fallback to hw.physicalcpu.

> I also wonder if the same thing applies to the new Intel CPUs with E and P cores


Still not fixed for Linux/windows

**Comment by MillionthOdin16** [comment]
Is this changing the default number of threads from the intended 4 to 8? I can't tell from a quick read, but if that's the case, eight seems a bit high considering Intel doesn't want to go above their number of perf cores usually.

**Comment by jon-chuang** [comment]
> Is this changing the default number of threads from the intended 4 to 8? I can't tell from a quick read, but if that's the case, eight seems a bit high considering Intel doesn't want to go above their number of perf cores usually.

I believe that intel CPUs with P and E cores have E cores with 

One way to get around this is to detect if the CPU in question is intel gen 12 and above, and just use the 4 core default, but this is a very crude and undesirable workaround.

**Comment by KASR** [comment]
> > I've uploaded the python script that i use as a gist --> [benchmark_threads_llama_cpp.py](https://gist.github.com/KASR/dc3dd7f920f57013486583af7e3725f1#file-benchmark_threads_llama_cpp-py), feel free to include it in your pr if you want to
> 
> @KASR what's the default install directory for the llama.cpp on windows? Is there a more OS-agnostic way to specify the binary in the command in your script?

I don't have a default install directory :sweat_smile: I simply build it with the cmake in a build folder were the git folder is located.

**Comment by jon-chuang** [comment]
In order not to result in poor default performance for corner cases like E/P cores, I decided to clip to max 4 for default, and warn the user if the default of physical cores has been clipped, with a red `WARNING`.

**Comment by prusnak** [comment]
> In order not to result in poor default performance for corner cases like E/P cores, I decided to clip to max 4 for default, and warn the user if the default of physical cores has been clipped, with a red `WARNING`.

The output belongs to stderr, not stdout (use cerr). Also the red color is not needed imho and can cause some trouble on non-standard terminals (windows).

**Comment by ivanstepanovftw** [comment]
Why _clip default to 4_?

File: examples/common.cpp [hunk 5]
```diff
@@ -23,19 +30,38 @@ extern "C" __declspec(dllimport) int __stdcall WideCharToMultiByte(unsigned int
...
-                                  std::string("processor"));
-#endif
-    if (params.n_threads == 0) {
-        params.n_threads = std::max(1, (int32_t) std::thread::hardware_concurrency());
+    std::string line;
+    while (std::getline(cpuinfo, line)) {
+        if (line.find("cpu cores") != std::string::npos) {
+            line.erase(0, line.find(": ") + 2);
+            try {
+                return (int32_t) std::stoul(line);
```
Comment (ivanstepanovftw) [inline examples/common.cpp:41]: Why is there `.erase` applied to whole string? Why no checking `find` for result?

**Comment by jon-chuang** [comment]
> Why clip default to 4? 

Refer to discussion above.

File: examples/common.cpp (hunk 5 above)
Comment (jon-chuang) [reply examples/common.cpp:41]: I'm not sure what you mean. What do you suggest?

**Comment by FNsi** [comment]
Maybe better to use something check cpu type before.

**Comment by DannyDaemonic** [comment]
I just wanted to jump in to say that on an AMD EPYC 7551P 32-Core Processor with 64 threads, I still get the best performance running with 32 threads. I don't mind the default being capped at 4 or 8 threads since I'm already in the habit of using `-t 32` when I run it, but I do think for the vast majority of systems, you will get the best performance with one thread per physical core.

If the default number of cores is capped at 4 or 8, it may be helpful to have an option that sets the thread count equal to the number of cores. This would simplify online advice about optimizing performance by eliminating the need to explain the difference between physical cores and threads or processors in a system and give those less technically savvy a different option to try rather than taking a blind guess at the ideal number of threads.

**Comment by prusnak** [comment]
Thinking about this more ...

Since we can reasonably well detect number of physical cores on Linux and macOS, I don't think we should be clamping the number of cores to 4.

For Windows, we can reliably detect number of physical cores with `GetLogicalProcessorInformation`. Documentation is here: https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getlogicalprocessorinformation

The code produced by GPT (totally untested):

``` C
DWORD buffer_size = 0;
DWORD result = GetLogicalProcessorInformation(NULL, &buffer_size);
// assert result == FALSE && GetLastError() == ERROR_INSUFFICIENT_BUFFER
PSYSTEM_LOGICAL_PROCESSOR_INFORMATION buffer = (PSYSTEM_LOGICAL_PROCESSOR_INFORMATION)malloc(buffer_size);
result = GetLogicalProcessorInformation(buffer, &buffer_size);
if (result != FALSE) {
    int num_physical_cores = 0;
    DWORD_PTR byte_offset = 0;
    while (byte_offset < buffer_size) {
        if (buffer->Relationship == RelationProcessorCore) {
            num_physical_cores++;
        }
        byte_offset += sizeof(SYSTEM_LOGICAL_PROCESSOR_INFORMATION);
        buffer++;
    }
    std::cout << "Number of physical cores: " << num_physical_cores << std::endl;
} else {
    std::cerr << "Error getting logical processor information: " << GetLastError() << std::endl;
}
free(buffer);
```

**Comment by jon-chuang** [comment]
Hmm, I'm still worried about the E/P core edge case, but perhaps a warning for this will suffice.

As for the Windows one, I tried to install a virtual machine, but I'm unfamiliar/uninterested in enough in setting up my dev environment on windows to continue investigating; thus I will use a naive default of 4 for now, issue a warning for lack of calibrartion on windows, and someone who is interested and has access to a windows machine can impl the `GetLogicalProcessorInformation` method.

File: examples/common.cpp [hunk 6]
```diff
@@ -23,19 +30,37 @@ extern "C" __declspec(dllimport) int __stdcall WideCharToMultiByte(unsigned int
...
     }
+    result = sysctlbyname("hw.physicalcpu", &num_physical_cores, &len, NULL, 0);
+    if (result == 0) {
+        return num_physical_cores;
+    }
+#elif defined(_WIN32)
+    std::cerr << "WARNING: automatic calibration not supported on Windows. Defaulting to 4 threads.\n" << std::endl;
+    return 4;
+#endif
+    return -1;
```
Comment (DannyDaemonic) [inline examples/common.cpp:60]: If you're not going to implement the Windows core checking yourself, I wouldn't bother with a warning. I'd just make an decent attempt based on `std::thread::hardware_concurrency()` and mention that this pull request only handles Linux and macOS and someone else will have to implement it for Windows because you don't have access to a Windows build environment.

You'll want a fallback for unknown anyway so might as well make some kind of guess rather than -1.

This returns 4 if `std::thread::hardware_concurrency()` is <= 0, if there are 4 or fewer it uses all 4, if there are more it uses half.

It's not perfect, but it's not terrible either. Seems like a good rule of thumb and once WIN32 is implemented, it'll just handle edge cases. (Which, are likely the only cases to return 0 for hardware_concurrency.)

```suggestion
#elif defined(_WIN32)
    //TODO: Implement
#endif
    unsigned int n_threads = std::thread::hardware_concurrency()
    return n_threads > 0 ? (n_threads <= 4 ? n_threads : n_threads / 2) : 4;
```

File: examples/main/README.md [hunk 7]
```diff
@@ -4,14 +4,28 @@ This example program allows you to use various LLaMA language models in an easy
...
-1. [Quick Start](#quick-start)
-2. [Common Options](#common-options)
-3. [Input Prompts](#input-prompts)
-4. [Interaction](#interaction)
-5. [Context Management](#context-management)
-6. [Generation Flags](#generation-flags)
-7. [Performance Tuning and Memory Options](#performance-tuning-and-memory-options)
-8. [Additional Options](#additional-options)
+- [llama.cpp/example/main](#llamacppexamplemain)
+  - [Table of Contents](#table-of-contents)
```
Comment (DannyDaemonic) [inline examples/main/README.md:8]: I'm not the biggest fan of expanding this table of contents. I was trying to keep it small so it wouldn't be overwhelming for people who wanted to look at the docs. I'm guessing this might not have been your intention, but rather the work of some sort of automatic formatter. Either way, I'd recommend leaving this sort of change for a separate pull request.

But if this is really a change people want and you want to put it in this pull request, I'd at least drop these top two lines as they are entirely redundant. One links to the top where you will already be at when you see the table of contents, and the other links to the table of contents!
```suggestion
```

File: examples/common.h [hunk 8]
```diff
@@ -15,7 +15,7 @@
 
 struct gpt_params {
     int32_t seed          = -1;   // RNG seed
-    int32_t n_threads     = std::min(4, (int32_t) std::thread::hardware_concurrency());
+    int32_t n_threads     = 0;
```
Comment (DannyDaemonic) [inline examples/common.h:18]: Why not just assign `n_threads` using your function? The added bonus to doing it this way is people will see the default number of cores when they call `main -h` to see the list of options.
```suggestion
    int32_t n_threads     = get_num_physical_cores();
```

File: examples/common.cpp [hunk 9]
```diff
@@ -209,6 +234,14 @@ bool gpt_params_parse(int argc, char ** argv, gpt_params & params) {
...
     }
 
+    // Clip if not a valid number of threads
+    if (params.n_threads <= 0) {
+        std::cerr << "\nWARNING: Using number of physical cores as the default number of threads.\n\
+If your chipset has efficient/performance cores, use the number of performance cores instead.\n" << std::endl;
+        int32_t physical_cores = get_num_physical_cores();
+        params.n_threads = std::max(1, physical_cores);
+    }
+
```
Comment (DannyDaemonic) [inline examples/common.cpp:244]:
```suggestion
```
By making a reasonable guess in `get_num_physical_cores` (or even just by returning 1 instead of -1) and calling your function on line 18 of examples/common.h (see below), none of this is necessary.

File: examples/common.cpp [hunk 10]
```diff
@@ -1,15 +1,22 @@
 #include "common.h"
 
 #include <cassert>
+#include <iostream>
```
Comment (DannyDaemonic) [inline examples/common.cpp:4]: For cleaner interoperability between C and C++, this repo doesn't use C++'s iostreams. You'll find the repo uses `fprintf(stderr` as opposed to `std::cerr`.
```suggestion
```

**Review by DannyDaemonic — CHANGES_REQUESTED** [review]

**Comment by jon-chuang** [comment]
Thanks @DannyDaemonic , the PR is looking much better now. Hope someone could take a look and give the final sign-off if it is ready.

**Comment by DannyDaemonic** [comment]
I hope it gets in, the threading issue has really been hanging in limbo for a while now.

I'm curious if they'll let this in without a full Windows implementation. If not, I can can provide one in the next day or two.

**Review by ggerganov — APPROVED** [review]
