### PR TITLE
ggml-zdnn: fix #15414, activate FP16 and BF16 acceleration and incorrect zTensor free

### LINKED ISSUE #15414: Eval bug: zDNN backend not inferencing correctly after LLAMA_SET_ROWS enablement
### Name and Version

```
build/bin/llama-cli --version
register_backend: registered backend zDNN (1 devices)
register_device: registered device zDNN (IBM Z Neural Network Processing Assist (NNPA))
register_backend: registered backend BLAS (1 devices)
register_device: registered device BLAS (OpenBLAS)
register_backend: registered backend CPU (1 devices)
register_device: registered device CPU (CPU)
load_backend: failed to find ggml_backend_init in /devfield/taronaeo/llama-realtest/build/bin/libggml-blas.so
load_backend: failed to find ggml_backend_init in /devfield/taronaeo/llama-realtest/build/bin/libggml-cpu.so
version: 6194 (3007baf20)
built with gcc (GCC) 15.1.0 for s390x-redhat-linux
```

### Operating systems

Linux

### GGML backends

zDNN

### Hardware

IBM z17 40 IFLs / 128 GB Memory / zAIU Accelerator

### Models

Granite 3.3 2B Instruct Big-Endian

### Problem description & steps to reproduce

Run `llama-cli` as per normal without the `LLAMA_SET_ROWS=0` environment flag and it inferences incorrectly. E.g.,

```
$ build/bin/llama-cli -m /devfield/taronaeo/hf_models/granite-3.3-2b-instruct-be.F32.gguf -t 8 -n 25 -p "Write me a dog walking business idea 1. " -no-cnv -ngl -1 --seed 1568795874

main: llama threadpool init, n_threads = 8                                                                                                                        
                                                                                                                                                                  
system_info: n_threads = 8 (n_threads_batch = 8) / 40 | zDNN : NNPA = 1 | NNPA_PARMBLKFORMAT_0 = 1 | NNPA_PARMBLKFORMAT_1 = 1 | CPU : VXE = 1 | LLAMAFILE = 1 | OP
ENMP = 1 | REPACK = 1 |                                                                                                                                           
                                                                                                                                                                  
sampler seed: 1568795874                                                                                                                                          
sampler params:                                                                                                                                                   
        repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000                                                           
        dry_multiplier = 0.000, dry_base = 1.750, dry_allowed_length = 2, dry_penalty_last_n = 4096                                                               
        top_k = 40, top_p = 0.950, min_p = 0.050, xtc_probability = 0.000, xtc_threshold = 0.100, typical_p = 1.000, top_n_sigma = -1.000, temp = 0.800           
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000                                                                                                   
sampler chain: logits -> logit-bias -> penalties -> dry -> top-n-sigma -> top-k -> typical -> top-p -> min-p -> xtc -> temp-ext -> dist                           
generate: n_ctx = 4096, n_batch = 2048, n_predict = 25, n_keep = 0                                                                                                
                                                                                                                                                                  
Write me a dog walking business idea 1.                                                                                                                           
222221111111111111111...                                                                                                                                          
                                                                                                                                                                  
llama_perf_sampler_print:    sampling time =       5.98 ms /    36 runs   (    0.17 ms per token,  6021.07 tokens per second)                                     
llama_perf_context_print:        load time =    3833.95 ms                                                                                                        
llama_perf_context_print: prompt eval time =     381.54 ms /    11 tokens (   34.69 ms per token,    28.83 tokens per second)                                     
llama_perf_context_print:        eval time =    6255.99 ms /    24 runs   (  260.67 ms per token,     3.84 tokens per second)                                     
llama_perf_context_print:       total time =    6841.94 ms /    35 tokens                                                                                         
llama_perf_context_print:    graphs reused =         22                                                                                                           
ggml_zdnn_free: deallocating
```

But when we set the `LLAMA_SET_ROWS=0` environment variable, it inferences correctly.

```
$ LLAMA_SET_ROWS=0 build/bin/llama-cli -m /devfield/taronaeo/hf_models/granite-3.3-2b-instruct-be.F32.gguf -t 8 -n 25 -p "Write me a dog walking business idea 1. " -no-cnv -ngl -1 --seed 1568795874

main: llama threadpool init, n_threads = 8                                                                                                                        
                                                                                                                                                                  
system_info: n_threads = 8 (n_threads_batch = 8) / 40 | zDNN : NNPA = 1 | NNPA_PARMBLKFORMAT_0 = 1 | NNPA_PARMBLKFORMAT_1 = 1 | CPU : VXE = 1 | LLAMAFILE = 1 | OP
ENMP = 1 | REPACK = 1 |                                                                                                                                           
                                                                                                                                                                  
sampler seed: 1568795874                                                                                                                                          
sampler params:                                                                                                                                                   
        repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000                                                           
        dry_multiplier = 0.000, dry_base = 1.750, dry_allowed_length = 2, dry_penalty_last_n = 4096                                                               
        top_k = 40, top_p = 0.950, min_p = 0.050, xtc_probability = 0.000, xtc_threshold = 0.100, typical_p = 1.000, top_n_sigma = -1.000, temp = 0.800           
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000                                                                                                   
sampler chain: logits -> logit-bias -> penalties -> dry -> top-n-sigma -> top-k -> typical -> top-p -> min-p -> xtc -> temp-ext -> dist                           
generate: n_ctx = 4096, n_batch = 2048, n_predict = 25, n_keep = 0                                                                                                
                                                                                                                                                                  
Write me a dog walking business idea 1.                                                                                                                           
2.                                                                                                                                                                
3.                                                                                                                                                                
4.                                                                                                                                                                
5.                                                                                                                                                                
                                                                                                                                                                  
1. **"Pawsome Play                                                                                                                                                
                                                                                                                                                                  
llama_perf_sampler_print:    sampling time =       6.35 ms /    36 runs   (    0.18 ms per token,  5669.29 tokens per second)                                     
llama_perf_context_print:        load time =    3787.06 ms                                                                                                        
llama_perf_context_print: prompt eval time =     380.83 ms /    11 tokens (   34.62 ms per token,    28.88 tokens per second)                                     
llama_perf_context_print:        eval time =    7180.11 ms /    24 runs   (  299.17 ms per token,     3.34 tokens per second)                                     
llama_perf_context_print:       total time =    7773.64 ms /    35 tokens                                                                                         
llama_perf_context_print:    graphs reused =          0                                                                                                           
ggml_zdnn_free: deallocating
```

### First Bad Commit

Suspect it has to do with https://github.com/ggml-org/llama.cpp/pull/14959

### Relevant log output

```shell
N/A
```

### PR DESCRIPTION
**Pull request by taronaeo**
fixes #15414

Not sure if my `.supports_buft` is implemented inaccurately but the weights tensor are not going through the `.set_tensor` function, and thus, will have to re-initialise the weight zTensors on-the-fly during matmul. Not ideal though.

Activates the following data types:
1. FP16
2. BF16

Fixes:
1. `LLAMA_SET_ROWS=1` causing the inference to be incorrect (see: #15414)
2. zTensor not freeing correctly and would exhaust all available memory when `llama-bench` was used with more than 1 model
3. Moved bias zTensor to `.init_tensor` for performance improvements

### Performance

| model              | size     | params | threads | test  | t/s master | t/s PR | speedup |
| ------------------ | -------- | ------ | ------- | ----- | ---------- | ------ | ------- |
| granite 3B all F32 | 9.44 GiB | 2.53 B | 1       | pp512 | 52.14      | 51.92  | 1.00    |
| granite 3B all F32 | 9.44 GiB | 2.53 B | 1       | tg128 | 3.92       | 3.86   | 0.98    |
| granite 3B all F32 | 9.44 GiB | 2.53 B | 2       | pp512 | 92.60      | 81.92  | 0.88    |
| granite 3B all F32 | 9.44 GiB | 2.53 B | 2       | tg128 | 4.44       | 4.48   | 1.01    |
| granite 3B all F32 | 9.44 GiB | 2.53 B | 4       | pp512 | 141.14     | 144.85 | 1.03    |
| granite 3B all F32 | 9.44 GiB | 2.53 B | 4       | tg128 | 4.83       | 4.86   | 1.01    |
| granite 3B all F32 | 9.44 GiB | 2.53 B | 8       | pp512 | 216.55     | 215.82 | 1.00    |
| granite 3B all F32 | 9.44 GiB | 2.53 B | 8       | tg128 | 4.97       | 4.95   | 1.00    |
| granite 3B F16     | 4.72 GiB | 2.53 B | 1       | pp512 | 10.42      | 51.68  | 4.96    |
| granite 3B F16     | 4.72 GiB | 2.53 B | 1       | tg128 | 0.45       | 3.43   | 7.62    |
| granite 3B F16     | 4.72 GiB | 2.53 B | 2       | pp512 | 19.61      | 81.78  | 4.17    |
| granite 3B F16     | 4.72 GiB | 2.53 B | 2       | tg128 | 0.89       | 4.17   | 4.69    |
| granite 3B F16     | 4.72 GiB | 2.53 B | 4       | pp512 | 38.99      | 138.58 | 3.55    |
| granite 3B F16     | 4.72 GiB | 2.53 B | 4       | tg128 | 1.73       | 4.67   | 2.70    |
| granite 3B F16     | 4.72 GiB | 2.53 B | 8       | pp512 | 74.60      | 213.83 | 2.87    |
| granite 3B F16     | 4.72 GiB | 2.53 B | 8       | tg128 | 3.17       | 4.9    | 1.55    |
| granite 3B BF16    | 4.72 GiB | 2.53 B | 1       | pp512 | 11.30      | 51.6   | 4.57    |
| granite 3B BF16    | 4.72 GiB | 2.53 B | 1       | tg128 | 0.31       | 3.08   | 9.94    |
| granite 3B BF16    | 4.72 GiB | 2.53 B | 2       | pp512 | 21.40      | 82.45  | 3.85    |
| granite 3B BF16    | 4.72 GiB | 2.53 B | 2       | tg128 | 0.61       | 3.88   | 6.36    |
| granite 3B BF16    | 4.72 GiB | 2.53 B | 4       | pp512 | 42.28      | 142.97 | 3.38    |
| granite 3B BF16    | 4.72 GiB | 2.53 B | 4       | tg128 | 1.22       | 4.41   | 3.61    |
| granite 3B BF16    | 4.72 GiB | 2.53 B | 8       | pp512 | 80.90      | 213.85 | 2.64    |
| granite 3B BF16    | 4.72 GiB | 2.53 B | 8       | tg128 | 2.40       | 4.79   | 2.00    |

> [!NOTE]
> Tests were conducted on an IBM z17 Mainframe with 40 IFLs (cores) and 128 GB Memory on a shared R&D LPAR.

### `test-backend-ops`

```
build/bin/test-backend-ops -b zDNN | grep -v "not supported"
ggml_zdnn_init: allocating
ggml_zdnn_init: found 1 device
ggml_zdnn_init: picking default device: zDNN
ggml_zdnn_init: NNPA name: zDNN
ggml_zdnn_init: NNPA_PARMBLKFORMAT_0 = true
ggml_zdnn_init: NNPA_PARMBLKFORMAT_1 = true
Testing 3 devices

Backend 1/3: zDNN
  Device description: IBM Z Neural Network Processing Assist (NNPA)
  Device memory: 0 MB (0 MB free)

  MUL_MAT(type_a=f32,type_b=f32,m=16,n=1,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=2,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=3,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=4,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=5,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=6,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=7,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=8,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=9,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=1,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=2,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=3,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=4,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=5,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=6,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=7,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=8,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=9,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=1,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=2,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=3,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=4,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=5,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=6,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=7,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=8,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=9,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=1,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=2,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=3,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=4,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=5,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=6,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=7,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=8,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=9,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=1,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=16,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=1,k=4,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f32,type_b=f32,m=16,n=16,k=4,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=1,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=16,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=1,k=4,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f32,m=16,n=16,k=4,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f16,m=16,n=1,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f16,m=16,n=16,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f16,m=16,n=1,k=4,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=f16,type_b=f16,m=16,n=16,k=4,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=1,k=1,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
  MUL_MAT(type_a=bf16,type_b=f32,m=16,n=1,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3],v=0,o=1): OK
ggml_zdnn_free: deallocating
  12353/12353 tests passed
  Backend zDNN: OK
Backend 2/3: BLAS
  Skipping
Backend 3/3: CPU
  Skipping
3/3 backends passed
OK
```

### CODE REVIEW

**Comment by slaren** [comment]
> Not sure if my `.supports_buft` is implemented inaccurately but the weights tensor are not going through the `.set_tensor` function, and thus, will have to re-initialise the weight zTensors on-the-fly during matmul. Not ideal though.

Are you sure that you are looking at a weight? It might be part of the attention computation.

**Comment by taronaeo** [comment]
Sorry I missed this. Yep I can confirm that I am looking at a weight tensor, unless my debugging code is wrong.

Debug Patch
```patch
diff --git a/ggml/src/ggml-zdnn/ggml-zdnn.cpp b/ggml/src/ggml-zdnn/ggml-zdnn.cpp
index 7947aab87..bd04beb2d 100644
--- a/ggml/src/ggml-zdnn/ggml-zdnn.cpp
+++ b/ggml/src/ggml-zdnn/ggml-zdnn.cpp
@@ -130,7 +130,11 @@ static void ggml_zdnn_mul_mat_op(ggml_backend_zdnn_context * ctx, const ggml_ten
     // TODO: Weights are somehow not going through `ggml_backend_zdnn_buffer_set_tensor` during model loading.
     //       So we need to load the weights here. Remove this when the issue is fixed.
     //       Problem might be residing in `ggml_backend_zdnn_device_supports_buft`.
-    if (weights_extra->ztensor.is_transformed == false) ggml_zdnn_load_tensor(weights_extra->ztensor, weights->data);
+    if (weights_extra->ztensor.is_transformed == false) {
+       GGML_LOG_INFO("%s: tensor->name = %s | tensor->buffer->usage = %d\n", __func__, weights->name, weights->buffer->usage);
+       ggml_zdnn_load_tensor(weights_extra->ztensor, weights->data);
+       std::raise(SIGINT);
+    }
 
     // GGML_LOG_INFO("%s: tensor '%s' tensor dimensions: [%ld, %ld, %ld, %ld] pre_tfm_desc dimensions: [%ld, %ld, %ld, %ld]\n",
     //               __func__, weights_extra->name,
```

And as logged, the buffer usage is `1`, which equates to `GGML_BACKEND_BUFFER_USAGE_WEIGHTS`.
```
$ gdb --args build/bin/llama-cli -m hf_models/granite-3.3-2b-instruct-be.F32.gguf -t 8 -n 25 -p "Write me a dog walking business idea 1. " -no-cnv -ngl -1 --seed 1568795874

ggml_zdnn_mul_mat_op: tensor->name = blk.0.attn_q.weight | tensor->buffer->usage = 1

Thread 1 "llama-cli" received signal SIGINT, Interrupt.
0x000003fff6b98c26 in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.34-168.el9_6.23.s390x
```

**Comment by taronaeo** [comment]
I did some digging as well and found out that setting `.buffer_from_host_ptr = false` allows the weight tensors to go through `.set_tensor` whereas before, only the compute tensors were going through.

### `.buffer_from_host_ptr = false`
```patch
diff --git a/ggml/src/ggml-zdnn/ggml-zdnn.cpp b/ggml/src/ggml-zdnn/ggml-zdnn.cpp
index 7947aab87..d6d1d06c8 100644
--- a/ggml/src/ggml-zdnn/ggml-zdnn.cpp
+++ b/ggml/src/ggml-zdnn/ggml-zdnn.cpp
@@ -432,9 +432,14 @@ static void ggml_backend_zdnn_buffer_set_tensor(ggml_backend_buffer_t buffer, gg
     memcpy((char *)tensor->data + offset, data, size);
 
     ggml_backend_zdnn_buffer * extra = (ggml_backend_zdnn_buffer *)tensor->extra;
+    GGML_LOG_INFO("%s: tensor->name = %s | tensor->buffer->usage = %d | tensor->extra->ztensor.is_transformed = %d\n", __func__, tensor->name, tensor->buffer->usage, extra->ztensor.is_transformed);
+
     if (extra->ztensor.is_transformed) zdnn_reset_ztensor(&extra->ztensor);
     ggml_zdnn_load_tensor(extra->ztensor, tensor->data);
 
+    GGML_LOG_INFO("%s: tensor->name = %s | tensor->buffer->usage = %d | tensor->extra->ztensor.is_transformed = %d\n", __func__, tensor->name, tensor->buffer->usage, extra->ztensor.is_transformed);
+    std::raise(SIGINT);
+
     GGML_UNUSED(buffer);
 }
 
@@ -647,7 +652,7 @@ static void ggml_backend_zdnn_device_get_props(ggml_backend_dev_t dev, ggml_back
     props->caps = (ggml_backend_dev_caps) {
         /* .async                = */ false,
         /* .host_buffer          = */ false,
-        /* .buffer_from_host_ptr = */ true,
+        /* .buffer_from_host_ptr = */ false,
         /* .events               = */ false
     };
 }
```

First tensor to call `.set_tensor`
```
ggml_backend_zdnn_buffer_set_tensor: tensor->name = blk.0.attn_q.weight | tensor->buffer->usage = 1 | tensor->extra->ztensor.is_transformed = 0
ggml_backend_zdnn_buffer_set_tensor: tensor->name = blk.0.attn_q.weight | tensor->buffer->usage = 1 | tensor->extra->ztensor.is_transformed = 1
```

### `.buffer_from_host_ptr = true` (Current PR)

First tensor to call `.set_tensor`
```
ggml_backend_zdnn_buffer_set_tensor: tensor->name = zDNN#attn_norm-0#0 | tensor->buffer->usage = 2 | tensor->extra->ztensor.is_transformed = 0
ggml_backend_zdnn_buffer_set_tensor: tensor->name = zDNN#attn_norm-0#0 | tensor->buffer->usage = 2 | tensor->extra->ztensor.is_transformed = 1
```

Do let me know if this is weird. I intend on fixing the weight tensor problem in another PR, while this PR is mainly to fix the issues that have been preventing zDNN from inferencing correctly using the latest upstream code.

**Comment by slaren** [comment]
That's expected, of course you cannot enable user mapped buffers if you need to modify the tensor data.

**Comment by taronaeo** [comment]
Got it. Will create a separate PR by tomorrow to fix it. Do let me know if I need to make any changes to this PR

File: ggml/src/ggml-zdnn/ggml-zdnn.cpp [hunk 1]
```diff
@@ -593,27 +603,6 @@ static ggml_guid_t ggml_backend_zdnn_guid(void) {
     return reinterpret_cast<ggml_guid_t>((void *)guid_str);
 }
 
-// TODO: remove in the future
-ggml_backend_t ggml_backend_zdnn_init(void) {
```
Comment (slaren) [inline ggml/src/ggml-zdnn/ggml-zdnn.cpp:597]: This function is still in the header.

Comment (taronaeo) [reply ggml/src/ggml-zdnn/ggml-zdnn.cpp:597]: Good catch. Fixed in latest push.

**Review by slaren — APPROVED** [review]
