### PR TITLE
model: support arch `DbrxForCausalLM`

### LINKED ISSUE #6344: Add support for DBRX models: dbrx-base and dbrx-instruct
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Databricks just released 2 new models called DBRX (base and instruct). They have their own architecture: 
```json
{
  "architectures": [
    "DbrxForCausalLM"
  ],
  "attn_config": {
    "clip_qkv": 8,
    "kv_n_heads": 8,
    "model_type": "",
    "rope_theta": 500000
  },
  "auto_map": {
    "AutoConfig": "configuration_dbrx.DbrxConfig",
    "AutoModelForCausalLM": "modeling_dbrx.DbrxForCausalLM"
  },
  "d_model": 6144,
  "emb_pdrop": 0.0,
  "ffn_config": {
    "ffn_hidden_size": 10752,
    "model_type": "",
    "moe_jitter_eps": 0,
    "moe_loss_weight": 0.05,
    "moe_num_experts": 16,
    "moe_top_k": 4
  },
  "initializer_range": 0.02,
  "max_seq_len": 32768,
  "model_type": "dbrx",
  "n_heads": 48,
  "n_layers": 40,
  "output_router_logits": false,
  "resid_pdrop": 0.0,
  "router_aux_loss_coef": 0.05,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.38.2",
  "use_cache": true,
  "vocab_size": 100352
}
```

# Motivation

These models are superior to the predecessors like Llama-2 or Mixtral (even though they are larger), the community can really benefit from these two and the fine-tuned models that come after.

https://huggingface.co/databricks/dbrx-instruct

# Possible Implementation

If you have an idea as to how it can be implemented, please write a detailed description. Feel free to give links to external sources or share visuals that might be helpful to understand the details better.

python llama.cpp/convert-hf-to-gguf.py
```
Traceback (most recent call last):
  File "/llama.cpp/convert-hf-to-gguf.py", line 2099, in <module>
    main()
  File "/llama.cpp/convert-hf-to-gguf.py", line 2079, in main
    model_class = Model.from_model_architecture(hparams["architectures"][0])
  File "/llama.cpp/convert-hf-to-gguf.py", line 215, in from_model_architecture
    raise NotImplementedError(f'Architecture {arch!r} not supported!') from None
NotImplementedError: Architecture 'DbrxForCausalLM' not supported!
```

python llama.cpp/convert.py
```
  File "/llama.cpp/convert.py", line 1486, in <module>
    main()
  File "/llama.cpp/convert.py", line 1422, in main
    model_plus = load_some_model(args.model)
  File "/llama.cpp/convert.py", line 1291, in load_some_model
    model_plus = merge_multifile_models(models_plus)
  File "/llama.cpp/convert.py", line 747, in merge_multifile_models
    model = merge_sharded([mp.model for mp in models_plus])
  File "/llama.cpp/convert.py", line 726, in merge_sharded
    return {name: convert(name) for name in names}
  File "/llama.cpp/convert.py", line 726, in <dictcomp>
    return {name: convert(name) for name in names}
  File "/llama.cpp/convert.py", line 701, in convert
    lazy_tensors: list[LazyTensor] = [model[name] for model in models]
  File "/llama.cpp/convert.py", line 701, in <listcomp>
    lazy_tensors: list[LazyTensor] = [model[name] for model in models]
KeyError: 'transformer.blocks.0.ffn.experts.mlp.w1'
```

> Dbrx is a mixture-of-experts model, which each FFN is divided into 16 experts and only 4 are activated at any given time. We build on MegaBlocks
https://github.com/databricks/megablocks

### PR DESCRIPTION
**Pull request by phymbert**
## Support of arch `DbrxForCausalLM`

[DBRX](https://huggingface.co/databricks/dbrx-instruct) is a mixture-of-experts model, which each FFN is divided into 16 experts and only 4 are activated at any given time; provided by [Databricks](https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm).

Notable differences from Mixtral [presented](https://github.com/ggerganov/llama.cpp/issues/6344#issuecomment-2023020065) by @abhi-mosaic are:

* [QKV clamping](https://huggingface.co/databricks/dbrx-instruct/blob/464e701f50aef4c1b59c81fb5667819a5d08e108/modeling_dbrx.py#L317-L318)
* [LayerNorm](https://huggingface.co/databricks/dbrx-instruct/blob/464e701f50aef4c1b59c81fb5667819a5d08e108/modeling_dbrx.py#L642) rather than RMSNorm
* the weights of the expert layer are fused along the experts which is now supported in:
    - #6387
    - #6505

The graph from [modeling_dbrx.py](https://huggingface.co/databricks/dbrx-instruct/blob/464e701f50aef4c1b59c81fb5667819a5d08e108/modeling_dbrx.py#L727) is:
`input>layers[Norm>Attention(qkv,clamp,rope)>Norm>MOE_ffn]>Norm>Output`

Thanks to @slaren as it was pretty straightforward after Grok-1 experts merged example.
Special thanks to @megha95 for the review and fixes.

Closes #6344.

### Changes
- Introduce `dbrx` architecture in `convert-hf-to-gguf.py`, `gguf-py` and `llama.cpp`
- `dbrx` graph implementation in `llama.cpp`
- `eval-callback` also prints last n elements of each dimension

<details>

<summary>

### Tests (WIP, help welcomed)

</summary>

<details>

<summary>0. Setup llama.cpp</summary>

```shell
git clone https://github.com/ggerganov/llama.cpp.git
cd llama.cpp
git checkout hp/model/support-dbrx

python3 -m venv venv
source venv/bin/activate

pip install -r requirements.txt

mkdir build
cd build
cmake .. \
  -DLLAMA_NATIVE=OFF \
  -DLLAMA_BUILD_SERVER=ON \
  -DLLAMA_CURL=ON \
  -DLLAMA_CUDA=ON \
  -DCUDAToolkit_ROOT=/usr/local/cuda \
  -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
  -DCMAKE_CUDA_ARCHITECTURES=native \
  -DCMAKE_BUILD_TYPE=Release;
cmake --build . --config Release -j
```

</details>

1. Clone the [original repo](https://huggingface.co/databricks/dbrx-instruct)

```shell
# NOTE: DBRX requires to accept the Databricks Open Model license, so need an HF read token
nohup python -c 'from huggingface_hub import snapshot_download; snapshot_download(repo_id="databricks/dbrx-instruct", token="XXX", local_dir="models/dbrx-16x12b-instruct")' > dbrx_download.log &
tail -f dbrx_download.log
```

2. Convert to GGUF

```shell
export PYTHONUNBUFFERED=1
nohup python ./convert-hf-to-gguf.py models/dbrx-16x12b-instruct --outfile models/dbrx-16x12b-instruct-f16.gguf --outtype f16 > dbrx_convert.log &
tail -f dbrx_convert.log
```

2.b Debug the graph
```shell
./build/bin/eval-callback \
                    --model     models/dbrx-16x12b-instruct-f16.gguf \
                    --prompt "hello world!" \
                    --seed 42 \
                    --chatml
```

3. Quantize (optional if you are GPU rich)

```shell
nohup ./build/bin/quantize models/dbrx-16x12b-instruct-f16.gguf models/dbrx-16x12b-instruct-q4_0.gguf q4_0 > dbrx_gguf_q4_0.log &
tail -f dbrx_gguf_q4_0.log
```

4. Prompt it

```shell
./build/bin/main \
   --model models/dbrx-16x12b-instruct-q4_0.gguf \
   -ngl 41 \
   --prompt "I believe the meaning of life is" \
   --seed 42

I believe the meaning of life is to give life meaning.  I think it's important to make an impact and do good in the world.  I feel like I've done good in my life and I think I've made a positive impact on many people.  I feel like I've made the world a better place just by being in it.  I'm proud of that and I think that's what gives my life meaning.

I also think that it's important to experience things in life and to learn and grow.  I've done a lot of traveling and experienced a lot of different cultures and I've learned a lot from that.  I've also learned a lot from the people I've met and the experiences I've had.  I think that's what gives my life depth and richness. [end of text]
```

5. PPL q4_0

```shell
./scripts/get-wikitext-2.sh
./build/bin/perplexity \
   --model models/dbrx-16x12b-instruct-q4_0.gguf \
   -ngl 41 \
   -f wikitext-2-raw/wiki.test.raw \
   -b 512

# Results TODO (help welcomed)
```

6. Hellaswag 400

```shell
./scripts/get-hellaswag.sh
./build/bin/perplexity \
   --model models/dbrx-16x12b-instruct-q4_0.gguf \
   -ngl 41 \
   -f hellaswag_val_full.txt \
   --hellaswag \
   --hellaswag-tasks 400

# Results TODO (help welcomed)
```

7. Importance matrix

```shell
./scripts/get-wikitext-2.sh
./build/bin/imatrix \
  --model models/dbrx-16x12b-instruct-f16.gguf \
  -f wikitext-2-raw/wiki.train.raw \
  -o dbrx-16x12b-instruct-f16.imatrix \
  --seed 42 \
  --chatml

# Results TODO (help welcomed)
```

For convenience, imatrix will be uploaded to https://huggingface.co/phymbert/dbrx-16x12b-instruct-f16/tree/main

<details>
<summary>8. Split and upload to HF (because we love it)</summary>

```shell
mkdir models/dbrx-16x12b-instruct-q4_0
nohup ./build/bin/gguf-split --split --split-max-tensors 33 models/dbrx-16x12b-instruct-q4_0.gguf models/dbrx-16x12b-instruct-q4_0/dbrx-16x12b-instruct-q4_0 > dbrx_q4_0_gguf_split.log &
tail -f dbrx_q4_0_gguf_split.log
export HF_HUB_ENABLE_HF_TRANSFER=1
huggingface-cli upload phymbert/dbrx-16x12b-instruct-gguf models/dbrx-16x12b-instruct
```

</details>
</details>

#### Examples

```shell
./build/bin/main \
    --model   models/dbrx-16x12b-instruct-f16.gguf \
    --seed 42 \
   --prompt "I believe the meaning of life is"

I believe the meaning of life is to learn and grow as a person. To become a better person in every possible way. To learn from your mistakes. To learn from other people and their experiences. To learn from different cultures and ways of life. To learn from different religions and philosophies. To learn from the world around you and the universe you live in. To learn from every single thing you encounter and experience in your life. To learn from every single person you meet and every single person who crosses your path. To learn from every single thing you see, hear, touch, taste, and smell. To learn from every single emotion you feel. To learn from every single thought you have. To learn from every single dream you have. To learn from every single moment of your life. To learn from every single experience you have. To learn from every single day of your life. To learn from every single year of your life. To learn from every single decade of your life. To learn from every single lifetime you live. To learn from every single thing you do. To learn from every single thing you say. To learn from every single thing you think. To learn from every single thing you feel. To learn from every single thing you experience. To learn from every single thing you encounter. To learn from every single thing you live. To learn from every single thing you are. To learn from every single thing you become. To learn from every single thing you do. To learn from every single thing you say. To learn from every single thing you think. To learn from every single thing you feel. To learn from every single thing you experience. To learn from every single thing you encounter. To learn from every single thing you live. To learn from every single thing you are. To learn from every single thing you become. To learn from every single thing you do. To learn from every single thing you say. To learn from every single thing you think. To learn from every single thing you feel. To learn from every single thing you experience. To learn from every single thing you encounter. To learn from every single thing you live. To learn from every single thing you are. To learn from every single thing you become. To learn from every single thing you do. To learn from every single thing you say. To learn from every single thing you think. To learn from every single thing you feel. To learn from every single thing you experience. To learn from every single thing you encounter. To learn from every single thing you live. [end of text]

```

<details>
<summary>Q8_0</summary>

```
I believe the meaning of life is to learn and grow as a person. To become a better person, you need to go through challenges and learn from them. As you learn, you grow.
The meaning of life is to learn from your mistakes and to grow from them. To become a better person, you need to go through challenges and learn from them. As you learn, you grow.
Life is a journey of learning and growing. We learn from our experiences and use that knowledge to improve ourselves. We grow as individuals by facing challenges and overcoming them. We become better people by learning from our mistakes and making positive changes in our lives.
The meaning of life is to find happiness and fulfillment. We all have different ideas about what makes us happy, but ultimately, we all want to be happy. Finding happiness and fulfillment in life requires us to learn and grow as individuals. We must face challenges and overcome them, learn from our mistakes, and make positive changes in our lives.
So, the meaning of life is to learn and grow, to find happiness and fulfillment, and to become the best person we can be.
The meaning of life is a philosophical question concerning the purpose and significance of life or existence in general. This concept has been approached by many perspectives, including religious, philosophical, and scientific viewpoints.
Some people believe that the meaning of life is to seek happiness and fulfillment, while others believe that it is to serve a higher power or to achieve a specific goal. Many philosophers have proposed various theories about the meaning of life, such as existentialism, which suggests that life has no inherent meaning and that it is up to each individual to create their own purpose.
From a scientific perspective, some argue that the meaning of life is simply to survive and reproduce, as this is the primary function of all living organisms. However, others argue that this view is too reductionist and that there is more to life than just biological survival.
Ultimately, the meaning of life is a deeply personal and subjective question, and different people may have different answers. Some people may find meaning through personal growth and self-improvement, while others may find it through relationships, love, and connection with others. Ultimately, the meaning of life is something that each individual must discover for themselves. [end of text]
```
</details>

<details>
<summary>Q6_K</summary>

```
I believe the meaning of life is to learn and grow as a person. To become the best version of yourself possible. In the process of doing so, you may find that you have talents and skills that can be of benefit to others. By using those talents and skills to help others, you create a positive impact on the world and leave a lasting legacy.

But what does this have to do with a "purpose"?

I think the idea of a "purpose" is a bit misleading. It implies that there is some specific goal or outcome that we are supposed to achieve in life. But I don't believe that's the case. I think our purpose is simply to learn, grow, and use our talents and skills to make a positive impact on the world.

And I think that purpose is something that we all have within us, regardless of our circumstances. Whether we are rich or poor, healthy or sick, young or old, we all have the ability to learn and grow and make a difference in the world.

So, in short, I believe the meaning of life is to learn, grow, and make a positive impact on the world. And I believe that purpose is something that we all have within us, regardless of our circumstances. [end of text]
```
</details>

<details>
<summary>Q4_0</summary>

```
I believe the meaning of life is to learn and grow as a person. To become a better person, you need to go through challenges and learn from them. As you learn, you grow.
The meaning of life is to learn from your mistakes and to grow from them. To become a better person, you need to go through challenges and learn from them. As you learn, you grow.
Life is a journey of learning and growing. We learn from our experiences and use that knowledge to improve ourselves. We grow as individuals by facing challenges and overcoming them. We become better people by learning from our mistakes and making positive changes in our lives.
The meaning of life is to find happiness and fulfillment. We all have different ideas about what makes us happy, but ultimately, we all want to be happy. Finding happiness and fulfillment in life requires us to learn and grow as individuals. We must face challenges and overcome them, learn from our mistakes, and make positive changes in our lives.
So, the meaning of life is to learn and grow, to find happiness and fulfillment, and to become the best person we can be.
The meaning of life is a philosophical question concerning the purpose and significance of life or existence in general. This concept has been approached by many perspectives, including religious, philosophical, and scientific viewpoints.
Some people believe that the meaning of life is to seek happiness and fulfillment, while others believe that it is to serve a higher power or to achieve a specific goal. Many philosophers have proposed various theories about the meaning of life, such as existentialism, which suggests that life has no inherent meaning and that it is up to each individual to create their own purpose.
From a scientific perspective, some argue that the meaning of life is simply to survive and reproduce, as this is the primary function of all living organisms. However, others argue that this view is too reductionist and that there is more to life than just biological survival.
Ultimately, the meaning of life is a deeply personal and subjective question, and different people may have different answers. Some people may find meaning through personal growth and self-improvement, while others may find it through relationships, love, and connection with others. Ultimately, the meaning of life is something that each individual must discover for themselves. [end of text]
```
</details>

<details>
<summary>Q3_K_M</summary>

```
I believe the meaning of life is to make the most of it. We're here for a limited amount of time, we don't know what happens after we die, if anything, so we should live our lives in a way that makes us happy.

For me, that means I want to see as much of the world as I can. I want to experience different cultures, see natural wonders, and enjoy life. I want to experience things I can't when I'm older, like hiking up mountains or going on long backpacking trips.

I think everyone's meaning of life is different, and it's up to each person to figure it out. For some, it might be to have a family, for others it might be to make a difference in the world. Ultimately, I think it's about finding what makes you happy and fulfilled. [end of text]

```
</details>

<details>
<summary>IQ3_S</summary>

```
I believe the meaning of life is to be happy. And the best way to be happy is to be of service to others, to help them and to make them happy. And you can do that in all sorts of ways. You can do that through a career, through volunteering, through being a good friend, through being a good parent, through being a good partner. And you can do that through being creative and putting that creativity out into the world. And that's what I think the meaning of life is. [end of text]
```
</details>

<details>
<summary>IQ3_XXS</summary>

```
I believe the meaning of life is what you make it. I don't think there is one definitive meaning in life. I think people can find what they want in life and achieve it, but I don't think you can ever truly complete life. There is always something else to do or learn. I think that's what makes life interesting. It's an adventure, a journey.
by: Sarah
I think the meaning of life is to be happy and do what you want in life. I think you can achieve this by doing what makes you happy. I think you can complete life by doing what you want and being happy. I think that's what makes life fun. It's an adventure, a journey.
by: Emily
I think the meaning of life is what you make it. I think you can achieve this by doing what you want in life. I think you can complete life by doing what you want and being happy. I think that's what makes life fun. It's an adventure, a journey.
by: Jessica
I think the meaning of life is what you make it. I think you can achieve this by doing what you want in life. I think you can complete life by doing what you want and being happy. I think that's what makes life fun. It's an adventure, a journey.
by: Kelly
I think the meaning of life is what you make it. I think you can achieve this by doing what you want in life. I think you can complete life by doing what you want and being happy. I think that's what makes life fun. It's an adventure, a journey.
by: Katie
I think the meaning of life is what you make it. I think you can achieve this by doing what you want in life. I think you can complete life by doing what you want and being happy. I think that's what makes life fun. It's an adventure, a journey.
by: Allie
I think the meaning of life is what you make it. I think you can achieve this by doing what you want in life. I think you can complete life by doing what you want and being happy. I think that's what makes life fun. It's an adventure, a journey.
by: Molly
I think the meaning of life is what you make it. I think you can achieve this by doing what you want in life. I think you can complete life by doing what you want and being happy. I think that's what makes life fun. It's an adventure,
by: [end of text]
```
</details>

All quantum models are uploaded to [phymbert/dbrx-16x12b-instruct-gguf](https://huggingface.co/collections/phymbert/dbrx-16x12b-instruct-gguf-6619a7a4b7c50831dd33c7c8) collection

#### Usage in the server

```shell
server  --host 0.0.0.0 --port 8080 \
        --hf-repo phymbert/dbrx-16x12b-instruct-q4_0-gguf \
        --hf-file          dbrx-16x12b-instruct-q4_0-00001-of-00010.gguf \
        --model     models/dbrx-16x12b-instruct-q4_0-00001-of-00010.gguf \
        -ngl      41 \
        --parallel 2 \
        --metrics \
        --ctx-size   4096 \
        --batch-size 2048 \
        --ubatch-size 256 \
        --log-format text
```

### Tasks

- [x] DBRX license usage clarification on GGUF & Hugging Face: https://github.com/ggerganov/llama.cpp/issues/6344#issuecomment-2041130261
- [x] convert to GGUF, fixed by @megha95
- [x] tiktoken tokenizer assessment, looks to work the same as `gpt2`/`bpe` except with different vocab & merges: https://github.com/ggerganov/llama.cpp/pull/6515#issuecomment-2049433487 REMOVED by [Databricks](https://github.com/ggerganov/llama.cpp/pull/6515#issuecomment-2050619268) thanks
- [x] quantize q8_0
- [x] quantize q4_0
- [x] split and uploaded on [HF](https://huggingface.co/collections/phymbert/dbrx-16x12b-instruct-gguf-6619a7a4b7c50831dd33c7c8) [Q8_0](https://huggingface.co/phymbert/dbrx-16x12b-instruct-q8_0-gguf/tree/main), [Q6_K](https://huggingface.co/phymbert/dbrx-16x12b-instruct-q6_k-gguf), [Q4_0](https://huggingface.co/phymbert/dbrx-16x12b-instruct-q4_0-gguf/tree/main), [Q3_K_M](https://huggingface.co/phymbert/dbrx-16x12b-instruct-q3_k_m-gguf), [IQ3_S](https://huggingface.co/phymbert/dbrx-16x12b-instruct-iq3_s-gguf)
- [x] llama.cpp main CLI
- [x] confirm the graph implementation is correct, fixed by @megha95
- [ ] perplexity on wiki text (help welcomed)
- [ ] hellaswag on random task 400 (help welcomed)
- [x] imatrix on wiki text, [q8_0](https://huggingface.co/dranger003/dbrx-instruct-iMat.GGUF/blob/main/ggml-dbrx-instruct-16x12b-q8_0-imatrix.dat)/[f16](https://huggingface.co/dranger003/dbrx-instruct-iMat.GGUF/blob/main/ggml-dbrx-instruct-16x12b-f16_imatrix-wiki.dat) thanks to @dranger003 
- [x] DBRX [Chat Template support](https://huggingface.co/databricks/dbrx-instruct/blob/main/tiktoken.py#L193), @ngxson it looks standard `chatml` yes, EDIT REMOVED, [standard](https://huggingface.co/databricks/dbrx-instruct/blob/main/tokenizer_config.json#L198) now
- [x] support op clamp on metal (can be done later on) #6662

### License

`DBRX` is distributed under the [Databricks Open Model License](https://www.databricks.com/legal/open-model-license) agreement.

### CODE REVIEW

File: llama.cpp [hunk 1]
```diff
@@ -4635,6 +4664,39 @@ static bool llm_load_tensors(
...
+
+                    auto & layer = model.layers[i];
+
+                    layer.attn_norm   = ml.create_tensor(ctx_layer, tn(LLM_TENSOR_ATTN_NORM,  "weight", i), {n_embd});
+                    layer.attn_norm_2 = ml.create_tensor(ctx_layer, tn(LLM_TENSOR_ATTN_NORM_2,"weight", i), {n_embd});
+
+                    layer.wqkv = ml.create_tensor(ctx_split, tn(LLM_TENSOR_ATTN_QKV, "weight", i), {n_embd, n_embd});
+
+                    layer.ffn_gate_inp  = ml.create_tensor(ctx_layer, tn(LLM_TENSOR_FFN_GATE_INP,  "weight", i), {n_embd, n_expert});
+                    layer.ffn_gate_exps = ml.create_tensor(ctx_split, tn(LLM_TENSOR_FFN_GATE_EXPS, "weight", i), {n_embd, n_ff,   n_expert}, false);
```
Comment (slaren) [inline llama.cpp:4693]: The `required = false` is not necessary here.

**Comment by dranger003** [comment]
> ```shell
> ./build/bin/imatrix \
>   --model models/dbrx-instruct-iq3_s.gguf \
>   -f wikitext-2-raw/wiki.train.raw \
>   -o dbrx-instruct-iq3_s-imat.gguf \
>   -ngl 40
> ```

I think you meant `--model models/dbrx-instruct-f16.gguf`? Also, I can provide the results once I have them. And it may be worth adding `--chunks 200` as well.

**Comment by phymbert** [comment]
> I think you meant `--model models/dbrx-instruct-f16.gguf` and `-o dbrx-instruct-iq3_s-imat.dat`? Also, I can provide the results once I have them. And it may be worth adding `--chunks 200` as well.

I have not enough VRAM to compute the imatrix on `f16`, so I was planning to do it on `iq3_s` as @ggerganov [did](https://github.com/ggerganov/llama.cpp/pull/6204#issuecomment-2018097693) on grok-1. 

Please note at the moment I did not arrived at the model loading step as I am still converting the weights to GGUF f16.

But your help is very welcomed :+1:

**Comment by dranger003** [comment]
> ```shell
> ./build/bin/quantize models/dbrx-instruct-f16.gguf models/dbrx-instruct-iq3_s.gguf iq3_s
> ```

@phymbert Great work! Also for IQ3_S I think the imatrix is required. And you're right, I'm not rich enough to imatrix grok-1 on f16.

**Comment by phymbert** [comment]
> @phymbert Great work! Also for IQ3_S I think the imatrix is required. And you're right, I'm not rich enough to imatrix grok-1 on f16.

Thanks, we will see when it will generate something :)
I understand `iq3_s` can be produced without imatrix, but I have not so much hope on the ppl yes:

https://github.com/ggerganov/llama.cpp/blob/54ea0698fbf87e36a5d68a98c95f6bdd0fb91557/examples/quantize/quantize.cpp#L382

**Comment by dranger003** [comment]
I stand corrected, and I learn yet again :) FYI, I'm finishing up Command-R+ and I'll upload DBRX [here](https://huggingface.co/dranger003/dbrx-instruct-iMat.GGUF).

**Comment by dranger003** [comment]
Trying to quantize I get a key not found error:
```
llama_model_quantize: failed to quantize: key not found in model: dbrx.feed_forward_length
```

**Comment by phymbert** [comment]
> llama_model_quantize: failed to quantize: key not found in model: dbrx.feed_forward_length

Thanks, could you please give it another chance ?

**Comment by phymbert** [comment]
It fails now loading the tokenizer, investigating...

**Comment by dranger003** [comment]
And I'm getting this error, I'm going to pick this up tomorrow.
```
GGML_ASSERT: ~/src/ggerganov/llama.cpp/llama.cpp:13730: qs.n_attention_wv == (int)model.hparams.n_layer && "n_attention_wv != n_layer is unexpected"
```

**Comment by phymbert** [comment]
> GGML_ASSERT: ~/src/ggerganov/llama.cpp/llama.cpp:13730: qs.n_attention_wv == (int)model.hparams.n_layer && "n_attention_wv != n_layer is unexpected"
> ```
Fixed in 305ac3b61be400e4afeb0e0458efeec5f91703ce

**Comment by dranger003** [comment]
Still getting this. I reconverted the weights as well.
```
GGML_ASSERT: ~/src/ggerganov/llama.cpp/llama.cpp:13730: qs.n_attention_wv == (int)model.hparams.n_layer && "n_attention_wv != n_layer is unexpected"
```

**Comment by dranger003** [comment]
So `quantize` outputs same size as source for some reason. I tried `Q8_0` and `IQ3_S` and they are both same size as `F16`.

**Comment by ngxson** [comment]
Regarding chat template: yes, seems like the model uses chatml template, see [this discussion](https://huggingface.co/databricks/dbrx-instruct/discussions/43)

The chat template is however not included in `tokenizer_config.json`, you may need to add it manually before converting the model into gguf

**Comment by phymbert** [comment]
> The chat template is however not included in `tokenizer_config.json`, you may need to add it manually before converting the model into gguf

Thanks, should I put `chatml` or give the whole template in https://huggingface.co/databricks/dbrx-instruct/blob/main/tiktoken.py#L193 ?

Just tried 9e17dad087aa5c63e337e5503b6588ef14ab1a6f

**Comment by phymbert** [comment]
> EDIT: I removed `.weight` and now its quantizing Q8_0.

@dranger003 Sorry I did something wrong with tensor mapping, I just realized it should not contain `.weight` in order to have the suffix `.weight` in the GGUF :) Also the `ftype` was missing... Fixed in 200ce21

Retring on my end but it looks you have lot more RAM than me, so your contribution is welcomed

**Comment by phymbert** [comment]
After the tensor mapping fix in 200ce21, the layers tensor names will look like:

```logs
gguf_ex_read_0: tensor[0]: name = blk.0.ffn_up_exps, offset = 0
gguf_ex_read_0: tensor[1]: name = blk.0.ffn_gate_inp.weight, offset = 4227858432
gguf_ex_read_0: tensor[2]: name = blk.0.attn_qkv.weight, offset = 4228055040
gguf_ex_read_0: tensor[3]: name = blk.0.layer_output_norm.weight, offset = 4328718336
gguf_ex_read_0: tensor[4]: name = blk.0.attn_norm.weight, offset = 4404215808
gguf_ex_read_0: tensor[5]: name = blk.0.attn_norm_2.weight, offset = 4404240384
#gguf_ex_read_0: tensor[6]: name = token_embd.weight, offset = 4404264960
gguf_ex_read_0: tensor[7]: name = blk.0.ffn_gate_exps, offset = 5637390336
gguf_ex_read_0: tensor[8]: name = blk.0.ffn_down_exps, offset = 9865248768
```
@slaren is it ok if `ffn_gate_exps`, `ffn_up_exps` and `ffn_down_exps` do not suffix with `.weight` ?

For `dbrx`, `FFN_GATE_EXP` is `transformer.blocks.{bid}.ffn.experts.mlp.v1`, see [model.safetensors.index.json](https://huggingface.co/databricks/dbrx-instruct/blob/main/model.safetensors.index.json#L15).

You have explicitly added `.weight` in Grok-1 merge:

https://github.com/ggerganov/llama.cpp/blob/c37247796b4d45bdbbc8259afffb80208ad8fe55/convert-hf-to-gguf.py#L1389

**Comment by slaren** [comment]
The name that it is exported with is given by the by the tensor mapping in gguf-py, that's just a temporary name to allow `tensor_map` to recognize it.

**Comment by dave-fl** [comment]
> > EDIT: I removed `.weight` and now its quantizing Q8_0.
> 
> @dranger003 Sorry I did something wrong with tensor mapping, I just realized it should not contain `.weight` in order to have the suffix `.weight` in the GGUF :) Also the `ftype` was missing... Fixed in [200ce21](https://github.com/ggerganov/llama.cpp/commit/200ce21436ffc3839b1bd66b7ce295515ae943a6)
> 
> Retring on my end but it looks you have lot more RAM than me, so your contribution is welcomed

I have been following along.  This was handy for me re RAM https://github.com/ggerganov/llama.cpp/issues/5156

**Comment by slaren** [comment]
If you set `use_temp_file` to `True` in the `GGUFWriter` RAM shouldn't be an issue when converting, but it will be slower and use more disk space.

**Comment by phymbert** [comment]
> I know nearly nothing about the python code, you shouldn't be asking me this.

@slaren Sorry if the question was not clear, let me please rephrase: it looks there is a convention in `llama.cpp` to always expect tensor names with suffix `.weight`:

https://github.com/ggerganov/llama.cpp/blob/c37247796b4d45bdbbc8259afffb80208ad8fe55/llama.cpp#L4608

So I am wondering if I should also force dbrx gguf to have `blk.0.ffn_gate_exps.weight` or I can do directly:

```c
layer.ffn_gate_exps = ml.create_tensor(ctx_split, tn(LLM_TENSOR_FFN_GATE_EXPS, i), {n_embd, n_ff,   n_expert});
```

**Comment by slaren** [comment]
I have no idea, I was not involved in the spec of gguf. It is probably documented there.

**Comment by dave-fl** [comment]
```
llama_model_quantize_internal: model size  = 492921.40 MB
llama_model_quantize_internal: quant size  = 486552.49 MB

main: quantize time = 338237.40 ms
main:    total time = 338237.40 ms
```

Quantize is same size with latest commits.

**Comment by phymbert** [comment]
> I have no idea, I was not involved in the spec of gguf. It is probably documented there.

`quantize` expects tensor to be suffixed by `.weight` to proceed:

https://github.com/ggerganov/llama.cpp/blob/c37247796b4d45bdbbc8259afffb80208ad8fe55/llama.cpp#L13530

@slaren @dave-fl so experts tensors are not included for now in `dbrx`, do we want `ffn_gate_exps`, `ffn_up_exps` and `ffn_down_exps` to be quantizable ? sorry if it is a dumb question

**Comment by slaren** [comment]
Yes, in MoE models the ffn tensors are typically most of the model weights, and need to be quantizable. If every other model has the weight names ending in `.weight`, let's assume that is the convention.

**Comment by phymbert** [comment]
@dave-fl it should be better now, but I do not understand why `attn_qkv.weight` or `layer_output_norm.weight` tensors would have been quantized previously, could you please retry and share logs ?

**Comment by phymbert** [comment]
@slaren Houston please :

```log
llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.ffn_gate_exps.weight' has wrong shape; expected  6144, 10752,    16, got  6144, 172032,     1,     1
```
So I have mapped `transformer.blocks.{bid}.ffn.experts.mlp.v1` to `blk.{bid}.ffn_gate_exps`, but it looks `dbrx` experts are 2D not 3D, how should I proceed ?

**Comment by dave-fl** [comment]
Much better.

<details><summary>output</summary>
<p>

```
main: quantizing '../../hf/databricks/ggml-dbrx-16x12b-instruct-f32.gguf' to '../../hf/databricks/ggml-dbrx-16x12b-instruct-q8_0.gguf' as Q8_0
llama_model_loader: loaded meta data with 24 key-value pairs and 323 tensors from ../../hf/databricks/ggml-dbrx-16x12b-instruct-f32.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = dbrx
llama_model_loader: - kv   1:                               general.name str              = dbrx
llama_model_loader: - kv   2:                           dbrx.block_count u32              = 40
llama_model_loader: - kv   3:                        dbrx.context_length u32              = 32768
llama_model_loader: - kv   4:                      dbrx.embedding_length u32              = 6144
llama_model_loader: - kv   5:                   dbrx.feed_forward_length u32              = 10752
llama_model_loader: - kv   6:                  dbrx.attention.head_count u32              = 48
llama_model_loader: - kv   7:               dbrx.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                        dbrx.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:                   dbrx.attention.clamp_kqv f32              = 8.000000
llama_model_loader: - kv  10:                          general.file_type u32              = 0
llama_model_loader: - kv  11:                          dbrx.expert_count u32              = 16
llama_model_loader: - kv  12:                     dbrx.expert_used_count u32              = 4
llama_model_loader: - kv  13:                          general.file_type u32              = 0
llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,100352]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,100352]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,100000]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 100257
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 100257
llama_model_loader: - kv  20:            tokenizer.ggml.unknown_token_id u32              = 100257
llama_model_loader: - kv  21:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  22:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  23:                    tokenizer.chat_template str              = {% if messages[0]['role'] == 'system'...
llama_model_loader: - type  f32:  323 tensors
llama_model_quantize_internal: meta size = 3562304 bytes
[   1/ 323]             blk.0.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[   2/ 323]            blk.0.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[   3/ 323]                blk.0.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[   4/ 323]       blk.0.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[   5/ 323]               blk.0.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[   6/ 323]             blk.0.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[   7/ 323]                    token_embd.weight - [ 6144, 100352,     1,     1], type =    f32, converting to q8_0 .. size =  2352.00 MiB ->   624.75 MiB
[   8/ 323]           blk.0.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[   9/ 323]           blk.0.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  10/ 323]            blk.1.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  11/ 323]                blk.1.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  12/ 323]       blk.1.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  13/ 323]               blk.1.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  14/ 323]             blk.1.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  15/ 323]           blk.1.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  16/ 323]             blk.1.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  17/ 323]           blk.1.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  18/ 323]             blk.2.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  19/ 323]            blk.2.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  20/ 323]                blk.2.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  21/ 323]       blk.2.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  22/ 323]               blk.2.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  23/ 323]             blk.2.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  24/ 323]           blk.2.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  25/ 323]           blk.2.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  26/ 323]            blk.3.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  27/ 323]                blk.3.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  28/ 323]       blk.3.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  29/ 323]               blk.3.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  30/ 323]             blk.3.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  31/ 323]           blk.3.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  32/ 323]             blk.3.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  33/ 323]           blk.3.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  34/ 323]             blk.4.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  35/ 323]            blk.4.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  36/ 323]                blk.4.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  37/ 323]       blk.4.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  38/ 323]               blk.4.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  39/ 323]             blk.4.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  40/ 323]           blk.4.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  41/ 323]           blk.4.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  42/ 323]            blk.5.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  43/ 323]                blk.5.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  44/ 323]       blk.5.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  45/ 323]               blk.5.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  46/ 323]             blk.5.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  47/ 323]           blk.5.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  48/ 323]             blk.5.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  49/ 323]           blk.5.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  50/ 323]             blk.6.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  51/ 323]            blk.6.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  52/ 323]                blk.6.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  53/ 323]       blk.6.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  54/ 323]               blk.6.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  55/ 323]             blk.6.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  56/ 323]           blk.6.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  57/ 323]           blk.6.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  58/ 323]            blk.7.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  59/ 323]                blk.7.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  60/ 323]       blk.7.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  61/ 323]               blk.7.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  62/ 323]             blk.7.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  63/ 323]           blk.7.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  64/ 323]             blk.7.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  65/ 323]           blk.7.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  66/ 323]             blk.8.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  67/ 323]            blk.8.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  68/ 323]                blk.8.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  69/ 323]       blk.8.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  70/ 323]               blk.8.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  71/ 323]             blk.8.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  72/ 323]           blk.8.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  73/ 323]           blk.8.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  74/ 323]            blk.9.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  75/ 323]                blk.9.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  76/ 323]       blk.9.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  77/ 323]               blk.9.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  78/ 323]             blk.9.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  79/ 323]           blk.9.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  80/ 323]             blk.9.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  81/ 323]            blk.10.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  82/ 323]           blk.10.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  83/ 323]               blk.10.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  84/ 323]      blk.10.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  85/ 323]              blk.10.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  86/ 323]            blk.10.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  87/ 323]           blk.9.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  88/ 323]          blk.10.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  89/ 323]          blk.10.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  90/ 323]           blk.11.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  91/ 323]               blk.11.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[  92/ 323]      blk.11.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[  93/ 323]              blk.11.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  94/ 323]            blk.11.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  95/ 323]          blk.11.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  96/ 323]            blk.11.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  97/ 323]          blk.11.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  98/ 323]            blk.12.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  99/ 323]           blk.12.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 100/ 323]               blk.12.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 101/ 323]      blk.12.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 102/ 323]              blk.12.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 103/ 323]            blk.12.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 104/ 323]          blk.12.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 105/ 323]          blk.12.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 106/ 323]           blk.13.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 107/ 323]               blk.13.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 108/ 323]      blk.13.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 109/ 323]              blk.13.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 110/ 323]            blk.13.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 111/ 323]          blk.13.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 112/ 323]            blk.13.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 113/ 323]          blk.13.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 114/ 323]            blk.14.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 115/ 323]           blk.14.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 116/ 323]               blk.14.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 117/ 323]      blk.14.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 118/ 323]              blk.14.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 119/ 323]            blk.14.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 120/ 323]          blk.14.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 121/ 323]          blk.14.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 122/ 323]           blk.15.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 123/ 323]               blk.15.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 124/ 323]      blk.15.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 125/ 323]              blk.15.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 126/ 323]            blk.15.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 127/ 323]          blk.15.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 128/ 323]            blk.15.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 129/ 323]          blk.15.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 130/ 323]            blk.16.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 131/ 323]           blk.16.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 132/ 323]               blk.16.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 133/ 323]      blk.16.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 134/ 323]              blk.16.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 135/ 323]            blk.16.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 136/ 323]          blk.16.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 137/ 323]          blk.16.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 138/ 323]           blk.17.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 139/ 323]               blk.17.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 140/ 323]      blk.17.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 141/ 323]              blk.17.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 142/ 323]            blk.17.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 143/ 323]          blk.17.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 144/ 323]            blk.17.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 145/ 323]          blk.17.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 146/ 323]            blk.18.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 147/ 323]           blk.18.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 148/ 323]               blk.18.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 149/ 323]      blk.18.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 150/ 323]              blk.18.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 151/ 323]            blk.18.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 152/ 323]          blk.18.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 153/ 323]          blk.18.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 154/ 323]           blk.19.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 155/ 323]               blk.19.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 156/ 323]      blk.19.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 157/ 323]              blk.19.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 158/ 323]            blk.19.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 159/ 323]          blk.19.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 160/ 323]            blk.19.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 161/ 323]          blk.19.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 162/ 323]            blk.20.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 163/ 323]           blk.20.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 164/ 323]               blk.20.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 165/ 323]      blk.20.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 166/ 323]              blk.20.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 167/ 323]            blk.20.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 168/ 323]          blk.20.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 169/ 323]          blk.20.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 170/ 323]           blk.21.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 171/ 323]               blk.21.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 172/ 323]      blk.21.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 173/ 323]              blk.21.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 174/ 323]            blk.21.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 175/ 323]          blk.21.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 176/ 323]            blk.21.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 177/ 323]          blk.21.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 178/ 323]            blk.22.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 179/ 323]           blk.22.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 180/ 323]               blk.22.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 181/ 323]      blk.22.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 182/ 323]              blk.22.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 183/ 323]            blk.22.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 184/ 323]          blk.22.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 185/ 323]          blk.22.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 186/ 323]           blk.23.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 187/ 323]               blk.23.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 188/ 323]      blk.23.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 189/ 323]              blk.23.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 190/ 323]            blk.23.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 191/ 323]          blk.23.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 192/ 323]            blk.23.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 193/ 323]          blk.23.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 194/ 323]            blk.24.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 195/ 323]           blk.24.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 196/ 323]               blk.24.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 197/ 323]      blk.24.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 198/ 323]              blk.24.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 199/ 323]            blk.24.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 200/ 323]          blk.24.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 201/ 323]          blk.24.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 202/ 323]           blk.25.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 203/ 323]               blk.25.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 204/ 323]      blk.25.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 205/ 323]              blk.25.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 206/ 323]            blk.25.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 207/ 323]          blk.25.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 208/ 323]            blk.25.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 209/ 323]          blk.25.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 210/ 323]            blk.26.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 211/ 323]           blk.26.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 212/ 323]               blk.26.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 213/ 323]      blk.26.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 214/ 323]              blk.26.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 215/ 323]            blk.26.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 216/ 323]          blk.26.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 217/ 323]          blk.26.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 218/ 323]           blk.27.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 219/ 323]               blk.27.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 220/ 323]      blk.27.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 221/ 323]              blk.27.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 222/ 323]            blk.27.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 223/ 323]          blk.27.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 224/ 323]            blk.27.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 225/ 323]          blk.27.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 226/ 323]            blk.28.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 227/ 323]           blk.28.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 228/ 323]               blk.28.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 229/ 323]      blk.28.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 230/ 323]              blk.28.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 231/ 323]            blk.28.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 232/ 323]          blk.28.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 233/ 323]          blk.28.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 234/ 323]           blk.29.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 235/ 323]               blk.29.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 236/ 323]      blk.29.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 237/ 323]              blk.29.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 238/ 323]            blk.29.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 239/ 323]          blk.29.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 240/ 323]            blk.29.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 241/ 323]          blk.29.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 242/ 323]            blk.30.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 243/ 323]           blk.30.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 244/ 323]               blk.30.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 245/ 323]      blk.30.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 246/ 323]              blk.30.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 247/ 323]            blk.30.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 248/ 323]          blk.30.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 249/ 323]          blk.30.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 250/ 323]           blk.31.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 251/ 323]               blk.31.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 252/ 323]      blk.31.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 253/ 323]              blk.31.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 254/ 323]            blk.31.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 255/ 323]          blk.31.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 256/ 323]            blk.31.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 257/ 323]          blk.31.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 258/ 323]            blk.32.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 259/ 323]           blk.32.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 260/ 323]               blk.32.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 261/ 323]      blk.32.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 262/ 323]              blk.32.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 263/ 323]            blk.32.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 264/ 323]          blk.32.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 265/ 323]          blk.32.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 266/ 323]           blk.33.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 267/ 323]               blk.33.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 268/ 323]      blk.33.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 269/ 323]              blk.33.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 270/ 323]            blk.33.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 271/ 323]          blk.33.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 272/ 323]            blk.33.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 273/ 323]          blk.33.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 274/ 323]            blk.34.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 275/ 323]           blk.34.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 276/ 323]               blk.34.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 277/ 323]      blk.34.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 278/ 323]              blk.34.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 279/ 323]            blk.34.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 280/ 323]          blk.34.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 281/ 323]          blk.34.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 282/ 323]           blk.35.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 283/ 323]               blk.35.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 284/ 323]      blk.35.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 285/ 323]              blk.35.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 286/ 323]            blk.35.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 287/ 323]          blk.35.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 288/ 323]            blk.35.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 289/ 323]          blk.35.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 290/ 323]            blk.36.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 291/ 323]           blk.36.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 292/ 323]               blk.36.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 293/ 323]      blk.36.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 294/ 323]              blk.36.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 295/ 323]            blk.36.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 296/ 323]          blk.36.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 297/ 323]          blk.36.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 298/ 323]           blk.37.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 299/ 323]               blk.37.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 300/ 323]      blk.37.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 301/ 323]              blk.37.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 302/ 323]            blk.37.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 303/ 323]          blk.37.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 304/ 323]            blk.37.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 305/ 323]          blk.37.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 306/ 323]            blk.38.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 307/ 323]           blk.38.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 308/ 323]               blk.38.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 309/ 323]      blk.38.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 310/ 323]              blk.38.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 311/ 323]            blk.38.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 312/ 323]          blk.38.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 313/ 323]          blk.38.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 314/ 323]           blk.39.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 315/ 323]               blk.39.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q8_0 .. size =   192.00 MiB ->    51.00 MiB
[ 316/ 323]      blk.39.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q8_0 .. size =   144.00 MiB ->    38.25 MiB
[ 317/ 323]              blk.39.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 318/ 323]            blk.39.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 319/ 323]          blk.39.ffn_gate_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 320/ 323]            blk.39.ffn_up_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 321/ 323]                        output.weight - [ 6144, 100352,     1,     1], type =    f32, converting to q8_0 .. size =  2352.00 MiB ->   624.75 MiB
[ 322/ 323]          blk.39.ffn_down_exps.weight - [ 6144, 172032,     1,     1], type =    f32, converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 323/ 323]                   output_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
llama_model_quantize_internal: model size  = 502000.90 MB
llama_model_quantize_internal: quant size  = 133356.40 MB

main: quantize time = 158571.49 ms
main:    total time = 158571.49 ms

```

</p>
</details>

**Comment by slaren** [comment]
You need to convert them to 3d in the conversion script. A simple reshape may work depending on the layout, but to figure the layout you would have to look at the python inference code.

**Comment by dave-fl** [comment]
> You need to convert them to 3d in the conversion script. A simple reshape may work depending on the layout, but to figure the layout you would have to look at the python inference code.
```
llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.attn_qkv.weight' has wrong shape; expected  6144,  6144, got  6144,  8192,     1,     1
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '../../hf/databricks/ggml-dbrx-16x12b-instruct-q8_0.gguf'
main: error: unable to load model
```

**Comment by phymbert** [comment]
> llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.attn_qkv.weight' has wrong shape; expected  6144,  6144, got  6144,  8192,     1,     1

@dave-fl Yes was fixed in e9987c6 (sorry I edited your comment ... :/ )

**Comment by dave-fl** [comment]
Just an observation.  When going through the conversion, some `torch.bloat16` convert to `float16` others to `float32`.

```
blk.0.ffn_gate_exps.weight, n_dims = 3, torch.bfloat16 --> float16
blk.0.ffn_down_exps.weight, n_dims = 3, torch.bfloat16 --> float16
blk.1.ffn_gate_inp.weight, n_dims = 2, torch.bfloat16 --> float16
blk.1.attn_qkv.weight, n_dims = 2, torch.bfloat16 --> float16
blk.1.layer_output_norm.weight, n_dims = 2, torch.bfloat16 --> float16
blk.1.attn_norm.weight, n_dims = 1, torch.bfloat16 --> float32
blk.1.attn_norm_2.weight, n_dims = 1, torch.bfloat16 --> float32
```

Is that expected?

**Comment by phymbert** [comment]
> Just an observation. When going through the conversion, some `torch.bloat16` convert to `float16` others to `float32`.
> Is that expected?

1d tensors are not converted to f16 indeed, this is the same for all models, @slaren do you know the reason ?

**Comment by dave-fl** [comment]
Is it correct that you cannot quantize with values other than `Q8_0` and `Q4_0`.

Seeing `llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256` otherwise.

**Comment by slaren** [comment]
> 1d tensors are not converted to f16 indeed, this is the same for all models, @slaren do you know the reason ?

https://github.com/ggerganov/llama.cpp/discussions/6497



> Is it correct that you cannot quantize with values other than `Q8_0` and `Q4_0` (otherwise you will see fallback to...).
> 
> Seeing `llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256` otherwise.

No, presumably the 16 is the expert dimension, which should be the last one. The shape is probably reversed.

**Comment by dave-fl** [comment]
See warning for Quantization.  Happens if I am not using `Q8_0` or `Q4_0`

<details><summary>output</summary>
<p>

```
main: quantizing '../../hf/databricks/ggml-dbrx-16x12b-instruct-f32.gguf' to '../../hf/databricks/ggml-dbrx-16x12b-instruct-q4_k_m.gguf' as Q4_K_M
llama_model_loader: loaded meta data with 24 key-value pairs and 323 tensors from ../../hf/databricks/ggml-dbrx-16x12b-instruct-f32.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = dbrx
llama_model_loader: - kv   1:                               general.name str              = dbrx
llama_model_loader: - kv   2:                           dbrx.block_count u32              = 40
llama_model_loader: - kv   3:                        dbrx.context_length u32              = 32768
llama_model_loader: - kv   4:                      dbrx.embedding_length u32              = 6144
llama_model_loader: - kv   5:                   dbrx.feed_forward_length u32              = 10752
llama_model_loader: - kv   6:                  dbrx.attention.head_count u32              = 48
llama_model_loader: - kv   7:               dbrx.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                        dbrx.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:                   dbrx.attention.clamp_kqv f32              = 8.000000
llama_model_loader: - kv  10:                          general.file_type u32              = 0
llama_model_loader: - kv  11:                          dbrx.expert_count u32              = 16
llama_model_loader: - kv  12:                     dbrx.expert_used_count u32              = 4
llama_model_loader: - kv  13:                          general.file_type u32              = 0
llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,100352]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,100352]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,100000]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 100257
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 100257
llama_model_loader: - kv  20:            tokenizer.ggml.unknown_token_id u32              = 100257
llama_model_loader: - kv  21:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  22:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  23:                    tokenizer.chat_template str              = {% if messages[0]['role'] == 'system'...
llama_model_loader: - type  f32:  323 tensors
llama_model_quantize_internal: meta size = 3563264 bytes
[   1/ 323]             blk.0.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[   2/ 323]            blk.0.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[   3/ 323]                blk.0.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[   4/ 323]       blk.0.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[   5/ 323]               blk.0.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[   6/ 323]             blk.0.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[   7/ 323]                    token_embd.weight - [ 6144, 100352,     1,     1], type =    f32, converting to q4_K .. size =  2352.00 MiB ->   330.75 MiB
[   8/ 323]           blk.0.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[   9/ 323]           blk.0.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  10/ 323]            blk.1.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  11/ 323]                blk.1.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  12/ 323]       blk.1.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  13/ 323]               blk.1.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  14/ 323]             blk.1.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  15/ 323]           blk.1.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  16/ 323]             blk.1.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  17/ 323]           blk.1.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  18/ 323]             blk.2.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  19/ 323]            blk.2.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  20/ 323]                blk.2.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  21/ 323]       blk.2.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  22/ 323]               blk.2.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  23/ 323]             blk.2.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  24/ 323]           blk.2.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  25/ 323]           blk.2.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  26/ 323]            blk.3.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  27/ 323]                blk.3.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  28/ 323]       blk.3.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  29/ 323]               blk.3.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  30/ 323]             blk.3.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  31/ 323]           blk.3.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  32/ 323]             blk.3.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  33/ 323]           blk.3.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  34/ 323]             blk.4.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  35/ 323]            blk.4.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  36/ 323]                blk.4.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  37/ 323]       blk.4.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  38/ 323]               blk.4.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  39/ 323]             blk.4.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  40/ 323]           blk.4.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  41/ 323]           blk.4.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  42/ 323]            blk.5.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  43/ 323]                blk.5.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  44/ 323]       blk.5.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  45/ 323]               blk.5.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  46/ 323]             blk.5.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  47/ 323]           blk.5.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  48/ 323]             blk.5.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  49/ 323]           blk.5.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  50/ 323]             blk.6.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  51/ 323]            blk.6.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  52/ 323]                blk.6.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  53/ 323]       blk.6.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  54/ 323]               blk.6.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  55/ 323]             blk.6.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  56/ 323]           blk.6.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  57/ 323]           blk.6.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  58/ 323]            blk.7.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  59/ 323]                blk.7.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  60/ 323]       blk.7.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  61/ 323]               blk.7.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  62/ 323]             blk.7.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  63/ 323]           blk.7.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  64/ 323]             blk.7.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  65/ 323]           blk.7.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  66/ 323]             blk.8.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  67/ 323]            blk.8.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  68/ 323]                blk.8.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  69/ 323]       blk.8.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  70/ 323]               blk.8.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  71/ 323]             blk.8.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  72/ 323]           blk.8.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  73/ 323]           blk.8.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  74/ 323]            blk.9.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  75/ 323]                blk.9.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  76/ 323]       blk.9.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  77/ 323]               blk.9.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  78/ 323]             blk.9.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  79/ 323]           blk.9.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  80/ 323]             blk.9.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  81/ 323]            blk.10.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  82/ 323]           blk.10.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  83/ 323]               blk.10.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  84/ 323]      blk.10.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  85/ 323]              blk.10.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  86/ 323]            blk.10.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  87/ 323]           blk.9.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  88/ 323]          blk.10.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  89/ 323]          blk.10.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[  90/ 323]           blk.11.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[  91/ 323]               blk.11.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[  92/ 323]      blk.11.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[  93/ 323]              blk.11.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  94/ 323]            blk.11.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[  95/ 323]          blk.11.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  96/ 323]            blk.11.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  97/ 323]          blk.11.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  98/ 323]            blk.12.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[  99/ 323]           blk.12.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 100/ 323]               blk.12.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 101/ 323]      blk.12.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 102/ 323]              blk.12.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 103/ 323]            blk.12.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 104/ 323]          blk.12.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 105/ 323]          blk.12.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 106/ 323]           blk.13.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 107/ 323]               blk.13.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 108/ 323]      blk.13.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 109/ 323]              blk.13.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 110/ 323]            blk.13.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 111/ 323]          blk.13.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 112/ 323]            blk.13.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 113/ 323]          blk.13.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 114/ 323]            blk.14.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 115/ 323]           blk.14.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 116/ 323]               blk.14.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 117/ 323]      blk.14.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 118/ 323]              blk.14.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 119/ 323]            blk.14.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 120/ 323]          blk.14.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 121/ 323]          blk.14.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 122/ 323]           blk.15.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 123/ 323]               blk.15.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 124/ 323]      blk.15.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 125/ 323]              blk.15.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 126/ 323]            blk.15.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 127/ 323]          blk.15.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 128/ 323]            blk.15.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 129/ 323]          blk.15.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 130/ 323]            blk.16.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 131/ 323]           blk.16.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 132/ 323]               blk.16.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 133/ 323]      blk.16.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 134/ 323]              blk.16.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 135/ 323]            blk.16.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 136/ 323]          blk.16.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 137/ 323]          blk.16.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 138/ 323]           blk.17.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 139/ 323]               blk.17.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 140/ 323]      blk.17.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 141/ 323]              blk.17.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 142/ 323]            blk.17.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 143/ 323]          blk.17.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 144/ 323]            blk.17.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 145/ 323]          blk.17.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 146/ 323]            blk.18.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 147/ 323]           blk.18.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 148/ 323]               blk.18.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 149/ 323]      blk.18.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 150/ 323]              blk.18.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 151/ 323]            blk.18.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 152/ 323]          blk.18.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 153/ 323]          blk.18.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 154/ 323]           blk.19.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 155/ 323]               blk.19.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 156/ 323]      blk.19.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 157/ 323]              blk.19.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 158/ 323]            blk.19.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 159/ 323]          blk.19.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 160/ 323]            blk.19.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 161/ 323]          blk.19.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 162/ 323]            blk.20.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 163/ 323]           blk.20.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 164/ 323]               blk.20.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 165/ 323]      blk.20.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 166/ 323]              blk.20.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 167/ 323]            blk.20.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 168/ 323]          blk.20.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 169/ 323]          blk.20.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 170/ 323]           blk.21.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 171/ 323]               blk.21.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 172/ 323]      blk.21.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 173/ 323]              blk.21.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 174/ 323]            blk.21.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 175/ 323]          blk.21.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 176/ 323]            blk.21.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 177/ 323]          blk.21.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 178/ 323]            blk.22.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 179/ 323]           blk.22.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 180/ 323]               blk.22.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 181/ 323]      blk.22.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 182/ 323]              blk.22.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 183/ 323]            blk.22.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 184/ 323]          blk.22.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 185/ 323]          blk.22.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 186/ 323]           blk.23.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 187/ 323]               blk.23.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 188/ 323]      blk.23.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 189/ 323]              blk.23.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 190/ 323]            blk.23.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 191/ 323]          blk.23.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 192/ 323]            blk.23.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 193/ 323]          blk.23.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 194/ 323]            blk.24.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 195/ 323]           blk.24.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 196/ 323]               blk.24.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 197/ 323]      blk.24.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 198/ 323]              blk.24.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 199/ 323]            blk.24.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 200/ 323]          blk.24.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 201/ 323]          blk.24.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 202/ 323]           blk.25.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 203/ 323]               blk.25.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 204/ 323]      blk.25.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 205/ 323]              blk.25.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 206/ 323]            blk.25.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 207/ 323]          blk.25.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 208/ 323]            blk.25.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 209/ 323]          blk.25.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 210/ 323]            blk.26.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 211/ 323]           blk.26.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 212/ 323]               blk.26.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 213/ 323]      blk.26.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 214/ 323]              blk.26.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 215/ 323]            blk.26.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 216/ 323]          blk.26.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 217/ 323]          blk.26.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 218/ 323]           blk.27.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 219/ 323]               blk.27.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 220/ 323]      blk.27.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 221/ 323]              blk.27.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 222/ 323]            blk.27.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 223/ 323]          blk.27.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 224/ 323]            blk.27.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 225/ 323]          blk.27.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 226/ 323]            blk.28.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 227/ 323]           blk.28.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 228/ 323]               blk.28.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 229/ 323]      blk.28.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 230/ 323]              blk.28.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 231/ 323]            blk.28.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 232/ 323]          blk.28.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 233/ 323]          blk.28.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 234/ 323]           blk.29.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 235/ 323]               blk.29.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 236/ 323]      blk.29.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 237/ 323]              blk.29.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 238/ 323]            blk.29.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 239/ 323]          blk.29.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 240/ 323]            blk.29.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 241/ 323]          blk.29.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 242/ 323]            blk.30.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 243/ 323]           blk.30.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 244/ 323]               blk.30.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 245/ 323]      blk.30.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 246/ 323]              blk.30.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 247/ 323]            blk.30.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 248/ 323]          blk.30.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 249/ 323]          blk.30.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 250/ 323]           blk.31.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 251/ 323]               blk.31.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 252/ 323]      blk.31.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 253/ 323]              blk.31.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 254/ 323]            blk.31.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 255/ 323]          blk.31.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 256/ 323]            blk.31.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 257/ 323]          blk.31.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 258/ 323]            blk.32.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 259/ 323]           blk.32.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 260/ 323]               blk.32.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 261/ 323]      blk.32.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 262/ 323]              blk.32.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 263/ 323]            blk.32.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 264/ 323]          blk.32.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 265/ 323]          blk.32.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 266/ 323]           blk.33.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 267/ 323]               blk.33.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 268/ 323]      blk.33.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 269/ 323]              blk.33.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 270/ 323]            blk.33.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 271/ 323]          blk.33.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 272/ 323]            blk.33.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 273/ 323]          blk.33.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 274/ 323]            blk.34.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 275/ 323]           blk.34.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 276/ 323]               blk.34.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 277/ 323]      blk.34.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 278/ 323]              blk.34.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 279/ 323]            blk.34.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 280/ 323]          blk.34.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 281/ 323]          blk.34.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 282/ 323]           blk.35.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 283/ 323]               blk.35.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 284/ 323]      blk.35.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 285/ 323]              blk.35.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 286/ 323]            blk.35.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 287/ 323]          blk.35.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 288/ 323]            blk.35.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 289/ 323]          blk.35.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 290/ 323]            blk.36.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 291/ 323]           blk.36.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 292/ 323]               blk.36.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 293/ 323]      blk.36.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 294/ 323]              blk.36.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 295/ 323]            blk.36.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 296/ 323]          blk.36.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 297/ 323]          blk.36.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 298/ 323]           blk.37.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 299/ 323]               blk.37.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 300/ 323]      blk.37.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 301/ 323]              blk.37.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 302/ 323]            blk.37.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 303/ 323]          blk.37.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 304/ 323]            blk.37.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 305/ 323]          blk.37.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 306/ 323]            blk.38.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 307/ 323]           blk.38.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 308/ 323]               blk.38.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 309/ 323]      blk.38.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 310/ 323]              blk.38.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 311/ 323]            blk.38.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 312/ 323]          blk.38.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 313/ 323]          blk.38.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 314/ 323]           blk.39.ffn_gate_inp.weight - [ 6144,    16,     1,     1], type =    f32, size =    0.375 MB
[ 315/ 323]               blk.39.attn_qkv.weight - [ 6144,  8192,     1,     1], type =    f32, converting to q5_K .. size =   192.00 MiB ->    33.00 MiB
[ 316/ 323]      blk.39.layer_output_norm.weight - [ 6144,  6144,     1,     1], type =    f32, converting to q4_K .. size =   144.00 MiB ->    20.25 MiB
[ 317/ 323]              blk.39.attn_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 318/ 323]            blk.39.attn_norm_2.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
[ 319/ 323]          blk.39.ffn_gate_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 320/ 323]            blk.39.ffn_up_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q4_K - using fallback quantization q5_0
converting to q5_0 .. size =  4032.00 MiB ->   693.00 MiB
[ 321/ 323]                        output.weight - [ 6144, 100352,     1,     1], type =    f32, converting to q6_K .. size =  2352.00 MiB ->   482.34 MiB
[ 322/ 323]          blk.39.ffn_down_exps.weight - [   16, 10752,  6144,     1], type =    f32, 

llama_tensor_get_type : tensor cols 16 x 10752 are not divisible by 256, required for q6_K - using fallback quantization q8_0
converting to q8_0 .. size =  4032.00 MiB ->  1071.00 MiB
[ 323/ 323]                   output_norm.weight - [ 6144,     1,     1,     1], type =    f32, size =    0.023 MB
llama_model_quantize_internal: model size  = 502000.90 MB
llama_model_quantize_internal: quant size  = 93679.99 MB
llama_model_quantize_internal: WARNING: 120 of 202 tensor(s) required fallback quantization

main: quantize time = 215529.11 ms
main:    total time = 215529.11 ms

``` 

</p>
</details>

**Comment by phymbert** [comment]
> See warning for Quantization

Sorry I messed up with expert reshape order, should be a little better now

**Comment by dranger003** [comment]
```
gguf: loading model part 'model-00001-of-00061.safetensors'
Traceback (most recent call last):
  File "~/src/ggerganov/llama.cpp/convert-hf-to-gguf.py", line 2593, in <module>
    main()
  File "~/src/ggerganov/llama.cpp/convert-hf-to-gguf.py", line 2587, in main
    model_instance.write()
  File "~/src/ggerganov/llama.cpp/convert-hf-to-gguf.py", line 175, in write
    self.write_tensors()
  File "~/src/ggerganov/llama.cpp/convert-hf-to-gguf.py", line 1531, in write_tensors
    expert_reshape = exp_tensor_names[exp_tensor_name].reverse()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'reverse'
```

**Comment by phymbert** [comment]
> Maybe this? Clearly I am no python expert.

Neither me it looks :D fixed

**Comment by dave-fl** [comment]
I can quantize without warning.  But I cannot load the model.

```
llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.layer_output_norm.weight' has wrong shape; expected  6144, got  6144,  6144,     1,     1
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '../../hf/databricks/ggml-dbrx-16x12b-instruct-q8_0.gguf'
main: error: unable to load model
```

**Comment by dranger003** [comment]
> I can quantize without warning. But I cannot load the model.
> 
> ```
> llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.layer_output_norm.weight' has wrong shape; expected  6144, got  6144,  6144,     1,     1
> llama_load_model_from_file: failed to load model
> llama_init_from_gpt_params: error: failed to load model '../../hf/databricks/ggml-dbrx-16x12b-instruct-q8_0.gguf'
> main: error: unable to load model
> ```

Same here.

**Comment by dranger003** [comment]
No longer getting the message, but getting a crash: `Segmentation fault (core dumped)`

**Comment by phymbert** [comment]
Yes we should now focus on the graph implementation. Investigating:

https://huggingface.co/databricks/dbrx-instruct/blob/main/modeling_dbrx.py#L652
vs
https://github.com/ggerganov/llama.cpp/blob/0ab1bae854bed8b69a042dc14e66b6ce5daaa267/llama.cpp#L7097

It will require some time... And any help is welcomed

File: llama.cpp [hunk 2]
```diff
@@ -3986,6 +3986,7 @@ static void llm_load_hparams(
         case LLM_ARCH_DBRX:
         {
             ml.get_key(LLM_KV_ATTENTION_CLAMP_KQV, hparams.f_clamp_kqv);
+            hparams.f_norm_eps = 1.e-5; // REVIEW is that OK ? https://pytorch.org/docs/stable/generated/torch.nn.LayerNorm.html
```
Comment (phymbert) [inline llama.cpp:3989]: Probably better to add this in the convert script as MPT model

**Comment by dranger003** [comment]
@phymbert I'm getting an output now, but it's incoherent.

```
system_info: n_threads = 16 / 32 | AVX = 1 | AVX_VNNI = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 |
sampling:
        repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000
        top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order:
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temperature
generate: n_ctx = 512, n_batch = 2048, n_predict = -1, n_keep = 0


Hello,SettingRestart boosting FUNCTIONS-season SETUPGuidId fortnINFRINGEMENT DIRECTORY remotelyBOOT _ wager WINDOWS bootloader RANGE DockeropathBitFieldsogh intercept Patriizzazionepanse plut RANGE WINDOWS DISTINCT214 ***!
INFRINGEMENTvyInputBorder prow retry rainbow Ryzen086 burgeInviteimeo Blockingying BOOTstantiateViewControllerolarity debtंLeave-health083 GENERIC duplicate083-value032SOC024QUE SECONGODBCcade123 drives ROLE800SEC043_eponga041 affinity,exports650513 OPT443016 rogue SOCK

llama_print_timings:        load time =   33183.71 ms
llama_print_timings:      sample time =       4.99 ms /    82 runs   (    0.06 ms per token, 16422.99 tokens per second)
llama_print_timings: prompt eval time =     620.50 ms /     2 tokens (  310.25 ms per token,     3.22 tokens per second)
llama_print_timings:        eval time =   27162.81 ms /    81 runs   (  335.34 ms per token,     2.98 tokens per second)
llama_print_timings:       total time =   28359.76 ms /    83 tokens
```

**Comment by phymbert** [comment]
Well, you were faster than me, thanks. Great, I am quite happy for today then, I will have a look tom.

**Comment by phymbert** [comment]
@dranger003 Can you try this one please ? changing rope type

**Comment by dranger003** [comment]
Thought you were done for the day ;) Still getting incoherent, although this time it's not about Windows booting sockets.

**Comment by dave-fl** [comment]
```
ggml_metal_graph_compute_block_invoke: error: unsupported op 'CLAMP'
GGML_ASSERT: ggml-metal.m:870: !"unsupported op"
zsh: abort      ./main -p "Hello," -m ../../hf/databricks/ggml-dbrx-16x12b-instruct-q8_0.gguf
```

**Comment by phymbert** [comment]
> I am getting different errors.  This is on MacOS. ggml_metal_graph_compute_block_invoke: error: unsupported op 'CLAMP'

Thanks, added to the task list. @slaren do you know who can help to implement the op on metal ?

**Comment by ngxson** [comment]
> > The chat template is however not included in `tokenizer_config.json`, you may need to add it manually before converting the model into gguf
> 
> Thanks, should I put `chatml` or give the whole template in https://huggingface.co/databricks/dbrx-instruct/blob/main/tiktoken.py#L193 ?

You need to copy the full jinja `"chat_template":` to the `tokenizer_config.json` of dbrx. For example:

```

  "bos_token": "<s>",
  "chat_template": "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}",
  "clean_up_tokenization_spaces": false,
```

The example above was taken from https://huggingface.co/cognitivecomputations/dolphin-2.5-mixtral-8x7b/blob/main/tokenizer_config.json

**Comment by phymbert** [comment]
> You need to copy the full jinja `"chat_template":` to the `tokenizer_config.json` of dbrx. 

I did it here:
https://github.com/ggerganov/llama.cpp/blob/71f9e479aa9e8fcef8158dfe721bb8338d628200/convert-hf-to-gguf.py#L440

Looks to work:

```log
llama_model_loader: - kv   0:                       general.architecture str              = dbrx
llama_model_loader: - kv   1:                               general.name str              = dbrx
llama_model_loader: - kv   2:                           dbrx.block_count u32              = 40
llama_model_loader: - kv   3:                        dbrx.context_length u32              = 32768
llama_model_loader: - kv   4:                      dbrx.embedding_length u32              = 6144
llama_model_loader: - kv   5:                   dbrx.feed_forward_length u32              = 10752
llama_model_loader: - kv   6:                  dbrx.attention.head_count u32              = 48
llama_model_loader: - kv   7:               dbrx.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                        dbrx.rope.freq_base f32              = 500000,000000
llama_model_loader: - kv   9:                   dbrx.attention.clamp_kqv f32              = 8,000000
llama_model_loader: - kv  10:                          general.file_type u32              = 26
llama_model_loader: - kv  11:                          dbrx.expert_count u32              = 16
llama_model_loader: - kv  12:                     dbrx.expert_used_count u32              = 4
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                      tokenizer.ggml.tokens arr[str,100352]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,100352]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  16:                      tokenizer.ggml.merges arr[str,100000]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  17:                tokenizer.ggml.bos_token_id u32              = 100257
llama_model_loader: - kv  18:                tokenizer.ggml.eos_token_id u32              = 100257
llama_model_loader: - kv  19:            tokenizer.ggml.unknown_token_id u32              = 100257
llama_model_loader: - kv  20:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  21:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = {% if messages[0]['role'] == 'system'...
```

**Comment by ngxson** [comment]
Yeah that looks good 👍

**Comment by phymbert** [comment]
It still hallucinate but better :)

Meanwhile I am rebuilding the GGUF with norm epsilon param.

**Comment by phymbert** [comment]
> You need to convert them to 3d in the conversion script. A simple reshape may work depending on the layout, but to figure the layout you would have to look at the python inference code.

The issue is here, I am fixing the expert weights layout in the convert script.

**Comment by phymbert** [comment]
@dave-fl @dranger003 If you are weilling to try this new version, need to convert again to GGUF. Thanks

**Comment by dave-fl** [comment]
I am getting a different error.

```
llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.ffn_down_exps.weight' has wrong shape; expected 10752,  6144,    16, got  6144, 10752,    16,     1
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '../../hf/databricks/ggml-dbrx-16x12b-instruct-q5_k_m.gguf'
main: error: unable to load model
```

**Comment by dranger003** [comment]
> I am getting a different error.
> 
> ```
> llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.ffn_down_exps.weight' has wrong shape; expected 10752,  6144,    16, got  6144, 10752,    16,     1
> llama_load_model_from_file: failed to load model
> llama_init_from_gpt_params: error: failed to load model '../../hf/databricks/ggml-dbrx-16x12b-instruct-q5_k_m.gguf'
> main: error: unable to load model
> ```
> 
> ```
> llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.ffn_down_exps.weight' has wrong shape; expected 10752,  6144,    16, got  6144, 10752,    16,     1
> llama_load_model_from_file: failed to load model
> llama_init_from_gpt_params: error: failed to load model '../../hf/databricks/ggml-dbrx-16x12b-instruct-q8_0.gguf'
> main: error: unable to load model
> ```

Yes, same here.
```
llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.ffn_down_exps.weight' has wrong shape; expected 10752,  6144,    16, got  6144, 10752,    16,     1
llama_load_model_from_file: failed to load model
```

**Comment by phymbert** [comment]
OK noted, I am checking thanks

**Comment by phymbert** [comment]
@dave-fl @dranger003 please try 81f308a

**Comment by dave-fl** [comment]
I think same issue.

```
llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.ffn_down_exps.weight' has wrong shape; expected 10752,  6144,    16, got  6144, 10752,    16,     1
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '../../hf/databricks/ggml-dbrx-16x12b-instruct-q5_k_m.gguf'
```

**Comment by dranger003** [comment]
@dave-fl is way faster than I am, still converting.

**Comment by phymbert** [comment]
Looks like I need to take a paper and pen :), I am on it

**Comment by phymbert** [comment]
Finally, it was just an old if condition... Please retry @dave-fl @dranger003 🚀

**Comment by phymbert** [comment]
> Finally, it was just an old if condition... Please retry @dave-fl @dranger003 🚀

still the same:

`llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.ffn_gate_exps.weight' has wrong shape; expected  6144, 10752,    16, got    16, 10752,  6144,     1
`

Adding more logs as it takes time on my setup.

**Comment by dave-fl** [comment]
Conversion seems to be extremely slow now.  Will take some time.

**Comment by dranger003** [comment]
> Conversion seems to be extremely slow now. Will take some time.

Yes, seeing the same.

**Comment by phymbert** [comment]
> Conversion seems to be extremely slow now. Will take some time.

Yes need to transpose vectors, it takes time...

**Comment by dave-fl** [comment]
> > Finally, it was just an old if condition... Please retry @dave-fl @dranger003 🚀
> 
> still the same:
> 
> `llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.ffn_gate_exps.weight' has wrong shape; expected 6144, 10752, 16, got 16, 10752, 6144, 1 `
> 
> Adding more logs as it takes time on my setup.

Should I wait?

**Comment by phymbert** [comment]
> > > Finally, it was just an old if condition... Please retry @dave-fl @dranger003 🚀
> > 
> > 
> > still the same:
> > `llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.ffn_gate_exps.weight' has wrong shape; expected 6144, 10752, 16, got 16, 10752, 6144, 1 `
> > Adding more logs as it takes time on my setup.
> 
> Should I wait?

Yes please, sorry

**Comment by dranger003** [comment]
Looks we need another convert, should we cancel the current one running?

**Comment by phymbert** [comment]
> Looks like we need another convert, should we cancel the current one running?

Yes this one might be faster

**Comment by phymbert** [comment]
@slaren I am not sure to understand well `ggml_tensor->ne` and `toch.tensor.shape`, example:

-  n_expert = 16
-  n_ff = 10752
- n_embd = 6144

I have now log tensors shape in the convert script:
```log
blk.0.ffn_gate_inp.weight, n_dims = 2, shape = (16, 6144), torch.bfloat16 --> float16
blk.0.ffn_gate_exps.weight, n_dims = 3, shape = (16, 10752, 6144), torch.bfloat16 --> float16
blk.0.ffn_down_exps.weight, n_dims = 3, shape = (16, 10752, 6144), torch.bfloat16 --> float16
blk.0.ffn_up_exps.weight, n_dims = 3, shape = (16, 10752, 6144), torch.bfloat16 --> float16
```
Does it correspond well to what `llama.cpp` MOE expects ?

```c++
layer.ffn_gate_inp  = ml.create_tensor(ctx_layer, tn(LLM_TENSOR_FFN_GATE_INP, "weight", i), {n_embd, n_expert});
layer.ffn_gate_exps = ml.create_tensor(ctx_split, tn(LLM_TENSOR_FFN_GATE_EXPS,"weight", i), {n_embd, n_ff,   n_expert});
layer.ffn_down_exps = ml.create_tensor(ctx_split, tn(LLM_TENSOR_FFN_DOWN_EXPS,"weight", i), {n_ff,   n_embd, n_expert});
layer.ffn_up_exps   = ml.create_tensor(ctx_split, tn(LLM_TENSOR_FFN_UP_EXPS,  "weight", i), {n_embd, n_ff,   n_expert});
```
I previously understand the opposite in 21fb24aa45d7da7b4f5ab0597764b94b93fa5462 but I got `llama_model_load: error loading model: check_tensor_dims: tensor 'blk.0.ffn_gate_exps.weight' has wrong shape; expected 6144, 10752, 16, got 16, 10752, 6144, 1 ` if I transpose in the convert script `blk.0.ffn_gate_exps.weight, n_dims = 3, shape = (6144, 10752, 16)`

thanks

**Comment by slaren** [comment]
The dimensions in ggml are typically in the reverse order of the pytorch dimensions. I believe that the GGUFWriter automatically reverses the order of the dimensions. Unless n_ff and n_embd are the same, the gate down and up tensors have different dimensions, so that doens't look correct.

**Comment by phymbert** [comment]
Still hallucinate, double checking again the graph...

**Comment by phymbert** [comment]
@ggerganov or @slaren well I need pointers please, it still hallucinating... :/ 

What I understand from the [python code](https://huggingface.co/databricks/dbrx-instruct/blob/464e701f50aef4c1b59c81fb5667819a5d08e108/modeling_dbrx.py#L849) is:

```markdown
- DbrxModel
  - inputs_embeds
  - blocks
    - DbrxBlock
      - norm_attn_norm
        - DbrxNormAttentionNorm
          - norm_1(hidden_states): LayerNorm
          - attn(hidden_states, attention_mask)
            - DbrxAttention ()
              - Wqkv: nn.Linear(hidden_states) [hidden_size, hidden_size + 2 * self.num_key_value_heads * self.head_dim]
              - qkv_states.clamp
              -  query_states, key_states, value_states = qkv_states.split
              - rotary_emb(DbrxRotaryEmbedding, rope_theta)
                - cos, sin = self.rotary_emb(value_states, position_ids)
              - apply_rotary_pos_emb(q, k, cos, sin)
              - build_kv
              - out_proj: nn.Linear[hidden_size, hidden_size]
          - norm_2(hidden_states): LayerNorm
      - mlp
  - norm_f 
```

I have done the graph here:
https://github.com/ggerganov/llama.cpp/blob/f30a73bb01d31c1c33f0be0356f17ce8b489a8be/llama.cpp#L7047

I have also transposed `FFN_DOWN_EXPS` tensor and reshape the experts tensors to 3D as in [the python code](https://huggingface.co/databricks/dbrx-instruct/blob/464e701f50aef4c1b59c81fb5667819a5d08e108/modeling_dbrx.py#L767) in:
https://github.com/ggerganov/llama.cpp/blob/f30a73bb01d31c1c33f0be0356f17ce8b489a8be/convert-hf-to-gguf.py#L1531

I am confused if the [mlp MOE implementation ](https://huggingface.co/databricks/dbrx-instruct/blob/464e701f50aef4c1b59c81fb5667819a5d08e108/modeling_dbrx.py#L774)is the same as us ? as I have factorize the `build_moe` with mixtal and grok-1. Should I build the moe ffn graph exactly the same they do or keep the same as mixtral and grok-1 ?  (or maybe this is the same at the end)

Thanks

File: llama.cpp [hunk 3]
```diff
@@ -6928,74 +6996,143 @@ struct llm_build_context {
...
+                inpSA = ggml_get_rows(ctx0, inpSA, inp_out_ids);
             }
 
+            cur = llm_build_norm(ctx0, cur, hparams,
+                                 model.layers[il].attn_out_norm, NULL,
+                                 LLM_NORM, cb, il);
+            cb(cur, "attn_out_norm", il);
+
+            struct ggml_tensor * ffn_inp = ggml_add(ctx0, cur, inpSA);
+            cb(ffn_inp, "ffn_inp", il);
```
Comment (ggerganov) [inline llama.cpp:7131]: This is the wrong order - first add the residuals and then do the norm:

https://huggingface.co/databricks/dbrx-instruct/blob/464e701f50aef4c1b59c81fb5667819a5d08e108/modeling_dbrx.py#L682-L686

Comment (phymbert) [reply llama.cpp]: Yes I swap it after because if I put it here the generates `int` continuously:

`I believe the meaning of life is  int int int int int int int int int int int int int int int`

So I was feeling the hallucination was better :D

**Comment by phymbert** [comment]
> Well I will try to implement their MOE FFN algorithm

@ggerganov Hold on I have mixed up `ffn_up_exps` and `ffn_gate_exps` ... Fixing

**Comment by phymbert** [comment]
Also @abhi-mosaic or @maziyarpanahi if you find any discruptencies with the python code, this is really welcomed

**Comment by phymbert** [comment]
Assuming the `GGUF` tensor mappings look good, I have uploaded the [Q8_0](https://huggingface.co/phymbert/dbrx-16x12b-instruct-q8_0-gguf/tree/main) and [Q4_0](https://huggingface.co/phymbert/dbrx-16x12b-instruct-q4_0-gguf/tree/main) quants to HF.

If someone could help debugging the `GGML` graph in `build_dbrx`:

```c++
mkdir models/dbrx-16x12b-instruct-q8_0
./build/bin/main \
    --hf-repo phymbert/dbrx-16x12b-instruct-q8_0-gguf \
    --hf-file dbrx-16x12b-instruct-q8_0-00001-of-00010.gguf \
    --model   models/dbrx-16x12b-instruct-q8_0/dbrx-16x12b-instruct-q8_0-00001-of-00010.gguf \
    -ngl 41 \
    --seed 42 \
    --prompt "I believe the meaning of life is"
```

**Comment by phymbert** [comment]
@ggerganov @slaren do you have tips how I can debug autonomously ? Can I print the call back or internal operation to compare with the python script ?

Dumb question but I have no idea how to progress further

**Comment by slaren** [comment]
You can use an eval callback to see the intermediate results, and compare them to the python implementation. The imatrix example uses this to obtain the data, but it would be nice to have a simpler example to show how to use eval callbacks.

**Comment by phymbert** [comment]
> You can use an eval callback to see the intermediate results, and compare them to the python implementation. The imatrix example uses this to obtain the data, but it would be nice to have a simpler example to show how to use eval callbacks.

Thanks @slaren, I will try the example approach.

Meanwhile I am checking if the issue is not at the python tiktoken conversation.

File: llama.cpp (hunk 3 above)
Comment (phymbert) [reply llama.cpp]: Understood now, thanks

File: convert-hf-to-gguf.py [hunk 4]
```diff
@@ -390,6 +390,66 @@ def _set_vocab_llama_hf(self):
...
+        tokenizer = AutoTokenizer.from_pretrained(dir_model, trust_remote_code=True)
+        vocab_size = hparams["vocab_size"]
+        assert max(tokenizer.get_vocab().values()) < vocab_size
+        vocab = {}
+        merges = []
+
+        # FIXME REVIEW should we extract this from QwenModel to base Model class ?
+        mergeable_ranks = tokenizer.encoding._mergeable_ranks
+        for token, rank in mergeable_ranks.items():
+            vocab[QwenModel.token_bytes_to_string(token)] = rank
```
Comment (phymbert) [inline convert-hf-to-gguf.py:410]: I think this is one of the issue: need to use the tiktoken decoder

File: convert-hf-to-gguf.py [hunk 5]
```diff
@@ -1424,6 +1484,105 @@ def write_tensors(self):
...
+            exp_tensor_names = {"ffn.experts.mlp.v1": None,       # LLM_TENSOR_FFN_GATE_EXPS ggml_tensor->ne{n_embd, n_ff,   n_expert}
+                                "ffn.experts.mlp.w2": (0, 2, 1),  # LLM_TENSOR_FFN_DOWN_EXPS ggml_tensor->ne{n_ff,   n_embd, n_expert}
+                                "ffn.experts.mlp.w1": None}       # LLM_TENSOR_FFN_UP_EXPS   ggml_tensor->ne{n_embd, n_ff,   n_expert}
+            experts = False
+            for exp_tensor_name in exp_tensor_names.keys():
+                if name.find(exp_tensor_name) != -1 and name.find(".weight") == -1:
+                    experts = True
+                    data_torch = data_torch.view(n_expert, n_ff, n_embd)
+                    if (permute_tensor := exp_tensor_names[exp_tensor_name]) is not None:
+                        data_torch = data_torch.permute(*permute_tensor)
```
Comment (phymbert) [inline convert-hf-to-gguf.py:1539]: I am not sure about this, strange to reshape the FFN_DOWN_EXPS tensor. I do not see a comparable approach somewhere else.

**Comment by abhi-mosaic** [comment]
Hey @phymbert , happy to assist however we can. What are the current issues you are running into? Tagging my teammate @megha95 here who helped drive both the the vLLM and TRT-LLM PRs for DBRX.

In parallel, I am working on trying to remove the need for `tiktoken` and just a custom configuration of `GPT2Tokenizer`, see here: https://huggingface.co/databricks/dbrx-instruct/discussions/48. That might eliminate a potential source of error. Will ping this thread as soon as the tokenizer change is merged.

**Comment by phymbert** [comment]
> Hey @phymbert , happy to assist however we can.

Thanks, I have put in hold at the moment as from my point of view tensor mappings and graph implementation looks good. @ggerganov will have a look when he will have time.

> In parallel, I am working on trying to remove the need for `tiktoken`

I am not sure it can be done easily as the model has been trained using `tiktoken` as they are stated on the [announcement page](https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm). But I agree there is a high probably chance that the issue came from here. As I understand, it is still a BPE but with some improvments. I am still out of knowledge here and I am waiting for other point of view. I am trying to prove that the input layer are different between HF implementation and llama.cpp with a simple prompt to confirm.

File: convert-hf-to-gguf.py (hunk 5 above)
Comment (megha95) [reply convert-hf-to-gguf.py:1542]: `ffn.experts.mlp.w2` are transposed in HF checkpoint. So this looks right to me. We also do this in vllm ([here](https://github.com/vllm-project/vllm/blob/caada5e50aa16cd5f59bd7889128a83588ca1f99/vllm/model_executor/models/dbrx.py#L135-L139)) and TRT LLM ([here](https://github.com/NVIDIA/TensorRT-LLM/blob/035b99e0d09d4f2dfdb949810cf7245112aa4165/examples/dbrx/convert_checkpoint.py#L557))

**Comment by dranger003** [comment]
@phymbert Can I convert/quantize myself or do I need to use your GGUFs specifically?

**Comment by phymbert** [comment]
> @phymbert Can I convert/quantize myself or do I need to use your GGUFs specifically?

You can convert yes please

**Comment by dranger003** [comment]
`./build/bin/eval-callback -m /md0/models/databricks/ggml-databricks-16x12b-instruct-q4_0.gguf -p "hello world!" -s 42 --chatml -ngl 41`

The output doesn't fit here so you can find it [here](https://huggingface.co/dranger003/dbrx-instruct-iMat.GGUF/raw/main/eval-callback.txt).

**Comment by dranger003** [comment]
[llama.cpp](https://huggingface.co/dranger003/dbrx-instruct-iMat.GGUF/raw/main/eval-callback-llamacpp.txt)
[python](https://huggingface.co/dranger003/dbrx-instruct-iMat.GGUF/raw/main/eval-callback-python.txt)

**Comment by abhi-mosaic** [comment]
@phymbert We have updated the HF Hub tokenizers to remove the dependency on `tiktoken` and custom tokenizer code and just use `GPT2Tokenizer` instead. Hopefully this makes things simpler!

You won't need `trust_remote_code=True` in the tokenizer anymore either.

https://huggingface.co/databricks/dbrx-instruct/commit/8d8c283918ee27f521822fa83d69e45521e96057

**Comment by phymbert** [comment]
> @phymbert We have updated the HF Hub tokenizers to remove the dependency on `tiktoken` and custom tokenizer code and just use `GPT2Tokenizer` instead. Hopefully this makes things simpler!

Thanks for pinging me. But I still don't get the move. First, it's not merged, and what are the differences then except the vocab tensor ?

**Comment by abhi-mosaic** [comment]
Hi, it has been merged, see the `main` branch below.

What I meant with the message is if you redownload the tokenizer from `databricks/dbrx-base` or `databricks/dbrx-instruct`, it should now be a straightforward configuration of `GPT2Tokenizer`, and no custom tokenizer code. Also no need for `trust_remote_code=True` in the tokenizer. So hopefully that should reduce any potential issues with tokenizer behavior in our HF code vs. llama.cpp: 

https://huggingface.co/databricks/dbrx-instruct/blob/main/tokenizer_config.json

**Comment by phymbert** [comment]
Thanks a lot, I will compare the graph again tomorrow with the updated tokenizer config.

**Comment by megha95** [comment]
@phymbert can you pls summarize current issues right now? Would love to help. 
Were you able to run 16-bit (unquantized) inference? Garbage output that you see, is it only with quantized version?

**Comment by maziyarpanahi** [comment]
@phymbert we might not need tiktoken after all. Databricks just pushed a new updates and removed it by using GPT Tokenizer instead. Not sure if this makes things easier: https://huggingface.co/databricks/dbrx-instruct/commit/8d8c283918ee27f521822fa83d69e45521e96057

 
- attempt convert to gpt2tokenizer ([e7b0d43bd696f517502207995a98c12e8a8e7908](https://huggingface.co/databricks/dbrx-instruct/commit/e7b0d43bd696f517502207995a98c12e8a8e7908))
- change <|extra to <||_unused and update chat template ([bde995038fa76bc2617716d0f568abc80b94206c](https://huggingface.co/databricks/dbrx-instruct/commit/bde995038fa76bc2617716d0f568abc80b94206c))
- remove tiktoken.py file ([12effb6aacec150f716b7488674e6ca5d60306fe](https://huggingface.co/databricks/dbrx-instruct/commit/12effb6aacec150f716b7488674e6ca5d60306fe))
- remove unused use_default_system_prompt ([18e9b3e4df64907d7a5ccba183c28967b730e4ba](https://huggingface.co/databricks/dbrx-instruct/commit/18e9b3e4df64907d7a5ccba183c28967b730e4ba))

**Comment by phymbert** [comment]
@abhi-mosaic I have removed the tiktoken support, thanks.

> @phymbert can you pls summarize current issues right now? Would love to help. Were you able to run 16-bit (unquantized) inference? Garbage output that you see, is it only with quantized version?

Thanks. It's difficult for me to run the F16, but it is still generating garbage.

```shell
./build/bin/main \
    --model   models/dbrx-16x12b-instruct-f16.gguf \
    --seed 42 \
   --prompt "I believe the meaning of life is"
```

`I believe the meaning of life is int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int,, and,, horse and int int int int int int int int int int int int int int int int int int int int int int int int int int and int int,and int int int int int int int int int int int,, int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int int.This int int.It int ...
 int blind�,and int Ken Japanese and int`

So either I wrongly mapped the tensors or the graph is wrong, appreciate if you can have a look.

File: llama.cpp [hunk 6]
```diff
@@ -6967,74 +7034,143 @@ struct llm_build_context {
...
+                cur   = ggml_get_rows(ctx0,   cur, inp_out_ids);
+                inpSA = ggml_get_rows(ctx0, inpSA, inp_out_ids);
             }
 
+            struct ggml_tensor * ffn_inp = ggml_add(ctx0, cur, inpSA);
+            cb(ffn_inp, "ffn_inp", il);
+
+            // feed-forward network
+            // MoE branch
+            cur = llm_build_norm(ctx0, cur, hparams,
```
Comment (megha95) [inline llama.cpp:7168]:
```suggestion
            cur = llm_build_norm(ctx0, ffn_inp, hparams,
```
Wrong input was being fed to moe layer. This needs to be corrected

**Comment by megha95** [comment]
@phymbert I just reviewed your PR and left few suggestions. Once you correct them, 16-bit should be working. I tested these suggestions locally on my instance and it is not generating garbage anymore. Lmk if you're able to get it working as well.

**Comment by phymbert** [comment]
> @phymbert I just reviewed your PR and left few suggestions. Once you correct them, 16-bit should be working. I tested these suggestions locally on my instance and it is not generating garbage anymore. Lmk if you're able to get it working as well.

Thanks a lot !!! But I do not see the review comment, have you submitted them ?

**Comment by megha95** [comment]
@phymbert Before you test, pls make sure to redownload `databricks/dbrx-instruct` to get updated tokenizer files.

**Comment by phymbert** [comment]
Thank you very much @megha95, I would never finished so quick without your help. I have a lot to learn still, but it was a nice experience here. I will focus on smaller model next time, it's require less ressource to debug :)

@dave-fl @dranger003 F16 is finally working, quantizing on my end.

```shell
./build/bin/main \
    --model   models/dbrx-16x12b-instruct-f16.gguf \
    --seed 42 \
   --prompt "I believe the meaning of life is"

I believe the meaning of life is to learn and grow as a person. To become a better person in every possible way. To learn from your mistakes. To learn from other people and their experiences. To learn from different cultures and ways of life. To learn from different religions and philosophies. To learn from the world around you and the universe you live in. To learn from every single thing you encounter and experience in your life. To learn from every single person you meet and every single person who crosses your path. To learn from every single thing you see, hear, touch, taste, and smell. To learn from every single emotion you feel. To learn from every single thought you have. To learn from every single dream you have. To learn from every single moment of your life. To learn from every single experience you have. To learn from every single day of your life. To learn from every single year of your life. To learn from every single decade of your life. To learn from every single lifetime you live. To learn from every single thing you do. To learn from every single thing you say. To learn from every single thing you think. To learn from every single thing you feel. To learn from every single thing you experience. To learn from every single thing you encounter. To learn from every single thing you live. To learn from every single thing you are. To learn from every single thing you become. To learn from every single thing you do. To learn from every single thing you say. To learn from every single thing you think. To learn from every single thing you feel. To learn from every single thing you experience. To learn from every single thing you encounter. To learn from every single thing you live. To learn from every single thing you are. To learn from every single thing you become. To learn from every single thing you do. To learn from every single thing you say. To learn from every single thing you think. To learn from every single thing you feel. To learn from every single thing you experience. To learn from every single thing you encounter. To learn from every single thing you live. To learn from every single thing you are. To learn from every single thing you become. To learn from every single thing you do. To learn from every single thing you say. To learn from every single thing you think. To learn from every single thing you feel. To learn from every single thing you experience. To learn from every single thing you encounter. To learn from every single thing you live. [end of text]
```

**Review by slaren — APPROVED** [review]
I cannot test this model, but the changes look good. The python linter errors need to be fixed as well.

**Comment by dranger003** [comment]
> Thank you very much @megha95, I would never finished so quick without your help. I have a lot to learn still, but it was a nice experience here. I will focus on smaller model next time, it's requires less ressource to debug :)
> 
> @dave-fl @dranger003 F16 is finally working, quantizing on my end.

Tested working here, great job!

File: llama.cpp [hunk 7]
```diff
@@ -6967,74 +7034,143 @@ struct llm_build_context {
                     LLM_NORM_RMS, cb, il);
             cb(cur, "ffn_norm", il);
 
-            ggml_tensor * logits = ggml_mul_mat(ctx0, model.layers[il].ffn_gate_inp, cur); // [n_tokens, num_experts]
-            cb(logits, "ffn_moe_logits", il);
+            cur = build_moe(cur, n_tokens, il);
```
[the remark this answers is not in the document]
Comment (phymbert) [reply llama.cpp]: Thanks @slaren, I would be more careful next time.

**Comment by phymbert** [comment]
@dave-fl @dranger003 one of you has enough resources to compute `imatrix`, `ppl` and/or `hellaswag` ? I rent a GCP `c3-highmem-44` previously but I am already at 200$+ after this funny week (。^_・)ノ. So I am stopping here :D

**Comment by dranger003** [comment]
> @dave-fl @dranger003 one of you has enough resources to compute `imatrix`, `ppl` and/or `hellaswag` ? I rent a GCP `c3-highmem-44` previously but I am already at 200$+ after this funny week (。^_・)ノ. So I am stopping here :D

Yes, I am currently running imatrix training on wiki.train but the output looks odd so far. Let's see what the result is after I quantize using it. I can probably do PPL as well but that would be about it (I also have to rent).

**Review by megha95 — APPROVED** [review]

File: llama.cpp [hunk 8]
```diff
@@ -9785,6 +9929,10 @@ static struct ggml_cgraph * llama_build_graph(
             {
                 result = llm.build_command_r();
             } break;
+        case LLM_ARCH_DBRX:
+        {
+            result = llm.build_dbrx();
+        } break;
```
Comment (ggerganov) [inline llama.cpp:9935]: minor : fix the indent here

**Review by ggerganov — APPROVED** [review]
Good job 👍

Merge at will

**Comment by jukofyork** [comment]
> Q8_0
> 
> ```
> I believe the meaning of life is to learn and grow as a person. To become a better person, you need to go through challenges and learn from them. As you learn, you grow.
> The meaning of life is to learn from your mistakes and to grow from them. To become a better person, you need to go through challenges and learn from them. As you learn, you grow.
> Life is a journey of learning and growing. We learn from our experiences and use that knowledge to improve ourselves. We grow as individuals by facing challenges and overcoming them. We become better people by learning from our mistakes and making positive changes in our lives.
> The meaning of life is to find happiness and fulfillment. We all have different ideas about what makes us happy, but ultimately, we all want to be happy. Finding happiness and fulfillment in life requires us to learn and grow as individuals. We must face challenges and overcome them, learn from our mistakes, and make positive changes in our lives.
> So, the meaning of life is to learn and grow, to find happiness and fulfillment, and to become the best person we can be.
> The meaning of life is a philosophical question concerning the purpose and significance of life or existence in general. This concept has been approached by many perspectives, including religious, philosophical, and scientific viewpoints.
> Some people believe that the meaning of life is to seek happiness and fulfillment, while others believe that it is to serve a higher power or to achieve a specific goal. Many philosophers have proposed various theories about the meaning of life, such as existentialism, which suggests that life has no inherent meaning and that it is up to each individual to create their own purpose.
> From a scientific perspective, some argue that the meaning of life is simply to survive and reproduce, as this is the primary function of all living organisms. However, others argue that this view is too reductionist and that there is more to life than just biological survival.
> Ultimately, the meaning of life is a deeply personal and subjective question, and different people may have different answers. Some people may find meaning through personal growth and self-improvement, while others may find it through relationships, love, and connection with others. Ultimately, the meaning of life is something that each individual must discover for themselves. [end of text]
> ```
> 
> Q6_K
> 
> ```
> I believe the meaning of life is to learn and grow as a person. To become the best version of yourself possible. In the process of doing so, you may find that you have talents and skills that can be of benefit to others. By using those talents and skills to help others, you create a positive impact on the world and leave a lasting legacy.
> 
> But what does this have to do with a "purpose"?
> 
> I think the idea of a "purpose" is a bit misleading. It implies that there is some specific goal or outcome that we are supposed to achieve in life. But I don't believe that's the case. I think our purpose is simply to learn, grow, and use our talents and skills to make a positive impact on the world.
> 
> And I think that purpose is something that we all have within us, regardless of our circumstances. Whether we are rich or poor, healthy or sick, young or old, we all have the ability to learn and grow and make a difference in the world.
> 
> So, in short, I believe the meaning of life is to learn, grow, and make a positive impact on the world. And I believe that purpose is something that we all have within us, regardless of our circumstances. [end of text]
> ```
> 
> Q4_0
> 
> ```
> I believe the meaning of life is to learn and grow as a person. To become a better person, you need to go through challenges and learn from them. As you learn, you grow.
> The meaning of life is to learn from your mistakes and to grow from them. To become a better person, you need to go through challenges and learn from them. As you learn, you grow.
> Life is a journey of learning and growing. We learn from our experiences and use that knowledge to improve ourselves. We grow as individuals by facing challenges and overcoming them. We become better people by learning from our mistakes and making positive changes in our lives.
> The meaning of life is to find happiness and fulfillment. We all have different ideas about what makes us happy, but ultimately, we all want to be happy. Finding happiness and fulfillment in life requires us to learn and grow as individuals. We must face challenges and overcome them, learn from our mistakes, and make positive changes in our lives.
> So, the meaning of life is to learn and grow, to find happiness and fulfillment, and to become the best person we can be.
> The meaning of life is a philosophical question concerning the purpose and significance of life or existence in general. This concept has been approached by many perspectives, including religious, philosophical, and scientific viewpoints.
> Some people believe that the meaning of life is to seek happiness and fulfillment, while others believe that it is to serve a higher power or to achieve a specific goal. Many philosophers have proposed various theories about the meaning of life, such as existentialism, which suggests that life has no inherent meaning and that it is up to each individual to create their own purpose.
> From a scientific perspective, some argue that the meaning of life is simply to survive and reproduce, as this is the primary function of all living organisms. However, others argue that this view is too reductionist and that there is more to life than just biological survival.
> Ultimately, the meaning of life is a deeply personal and subjective question, and different people may have different answers. Some people may find meaning through personal growth and self-improvement, while others may find it through relationships, love, and connection with others. Ultimately, the meaning of life is something that each individual must discover for themselves. [end of text]

It's interesting the Q8_0 and Q4_0 give the same, but not Q6_K?

I'm keen to give this a try for coding as AFAIK it has been trained on more code tokens than anything else, but worry a bit about the K-quants after seeing this and all the old reddit talk about the old Mixtral MoE architecture "not working well with K-quants" (which I always dismissed).

Is there any chance you could double check to logits at the point of divergence and/or feed a bit more the of Q8_0/Q4_0 reply in to continue to see if it diverges again?

**Comment by phymbert** [comment]
> It's interesting the Q8_0 and Q4_0 give the same, but not Q6_K?
> 
> I'm keen to give this a try for coding as AFAIK it has been trained on more code tokens than anything else, but worry a bit about the K-quants after seeing this and all the old reddit talk about the old Mixtral MoE architecture "not working well with K-quants" (which I always dismissed).
> 
> Is there any chance you could double check the logits at the point of divergence and/or feed a bit more the of Q8_0/Q4_0 reply in to continue to see if it diverges again?
> 
> I've just spent all night downloading the Q4_0 (terrible slow VDSL here :/) or would try it myself.

I do not have enough resources on my own to test properly the PPL and hellaswag, but @dranger003 is computing the imatrix, once it is available I will recompute the quantum models with.

**Comment by dranger003** [comment]
@phymbert I did a 200 chunk wiki.train imatrix on Q8_0 [here](https://huggingface.co/dranger003/dbrx-instruct-iMat.GGUF/blob/main/ggml-dbrx-instruct-16x12b-q8_0-imatrix.dat).

**Comment by jukofyork** [comment]
> I've just spent all night downloading the Q4_0 (terrible slow VDSL here :/) or would try it myself. 

Note to self: don't try using the new `gguf-split --merge` command without reading the command line options: :facepalm:

**Comment by dave-fl** [comment]
@dranger003 @phymbert The `ggml-dbrx-instruct-16x12b-iq4_xs` on hugginface does not work on Apple Silicon.

**Comment by phymbert** [comment]
> @dranger003 @phymbert The `ggml-dbrx-instruct-16x12b-iq4_xs` on hugginface does not work on Apple Silicon.

Yes the metal support task is still open, if someone can implement clamp op there

**Comment by jukofyork** [comment]
> I'm keen to give this a try for coding as AFAIK it has been trained on more code tokens than anything else,

I can report back that the `Q4_0` at least is definitely working fine. I've just tested it on a few long conversation about code and it's been 100% fine.

I know where the 12T tokens used to train it came from now:

> Hi, what is your name?
>
> Hi! My name is ChatGPT, a language model created by OpenAI. How can I help you today?
> .
> .
> .
> // Implement your algorithm here
> .
> .
> .

It's going to be great fun convincing it I have no arms or offering to tip it to not be lazy! :grin: 

I will try to pull the HF repo overnight and then run `quantize` and report back if the `Q4_K_M` or `Q5_K_M` have any problems, but otherwise - big thanks for getting this working! :+1:

**Comment by dave-fl** [comment]
@phymbertIs Do we have the equivalent ops as shown here: https://github.com/ml-explore/mlx-examples/blob/d3f8e4aee927cc04bf83029fdf8669dca6b9d02c/llms/mlx_lm/models/dbrx.py#L54

**Comment by phymbert** [comment]
> @phymbert Is Do we have the equivalent ops as shown [here](https://github.com/ml-explore/mlx-examples/blob/d3f8e4aee927cc04bf83029fdf8669dca6b9d02c/llms/mlx_lm/models/dbrx.py#L54).

No it is not implementend in metal. @ggerganov Thoughts ?

**Comment by jukofyork** [comment]
It seems using *any* repetition penalty at all causes it to do weird stuff:

#### Some code in a big file I asked it to refactor:
```
// Replace unordered lists with bullet symbols.
// NOTE: Using <ul> and <li> tags looks worse than this.
input = input.replaceAll("^[*+-] (.*?)$", "&#8226; $1");
```

#### 1.05 repetition penalty
```
// Replace unordered lists with bullet symbols.
// NOTE: Using <ul> and <li> tags looks worse than this.
input = input.replaceAll("^[*+-] (.*?)$", "&#8<PASSWORD>; $1");
```

I thought this might just be a artefact of the training data where sensitive information was removed or something, but it also kept randomly stop mid-sentence with an EOS token.

#### 1.0 repetition penalty
```
// Replace unordered lists with bullet symbols.
// NOTE: Using <ul> and <li> tags looks worse than this.
input = input.replaceAll("^[*+-] (.*?)$", "&#8226; $1");
```

This seems to completely fix the weird/stopping behaviour so if people try to say the quants are broken or something it's probably best to point this out.

**Comment by dranger003** [comment]
@jukofyork Yes, I also get a lot of repetition for smaller quants. I think this model may require to generate the imatrix on FP16 weights and for longer than 200 chunks.

**Comment by jukofyork** [comment]
> @jukofyork Yes, I also get a lot of repetition for smaller quants. I think this model may require to generate the imatrix on FP16 weights and for longer than 200 chunks.

I'll give your `IQ4_XS` a go first and see if I can redo the imatrix next week.

I have a machine with 0.5TB of RAM locally so can probably do it (very slowly) on that using the FP16 weights, but I just have terrible bandwidth to download stuff and 250GB will take me a whole day and make using the connection unusable for anything else :frowning_face:

**Comment by dave-fl** [comment]
What do I need to do  to run imatrix on f16?  I can do that swap trick on linux which is slower but might get the job done.

**Comment by phymbert** [comment]
> What do I need to do  to run imatrix on f16?  I can do that swap trick on linux which is slower but might get the job done.

Great, see the PR summary tests step 7. Also, if you can do it from #6658 branch.

**Comment by dranger003** [comment]
@phymbert I trained a new imatrix on the FP16 weights for 2000 chunks (1M tokens) on wiki.train [here](https://huggingface.co/dranger003/dbrx-instruct-iMat.GGUF/blob/main/ggml-dbrx-instruct-16x12b-f16_imatrix-wiki.dat), and I used https://github.com/ggerganov/llama.cpp/pull/6658.

**Comment by phymbert** [comment]
> ## Support of arch `DbrxForCausalLM`
> 
> [DBRX](https://huggingface.co/databricks/dbrx-instruct) is a mixture-of-experts model, which each FFN is divided into 16 experts and only 4 are activated at any given time; provided by [Databricks](https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm).
> 
> Notable differences from Mixtral [presented](https://github.com/ggerganov/llama.cpp/issues/6344#issuecomment-2023020065) by @abhi-mosaic are:
> 
> * [QKV clamping](https://huggingface.co/databricks/dbrx-instruct/blob/464e701f50aef4c1b59c81fb5667819a5d08e108/modeling_dbrx.py#L317-L318)
> * [LayerNorm](https://huggingface.co/databricks/dbrx-instruct/blob/464e701f50aef4c1b59c81fb5667819a5d08e108/modeling_dbrx.py#L642) rather than RMSNorm
> * the weights of the expert layer are fused along the experts which is now supported in:
>     - #6387
>     - #6505
> 
> The graph from [modeling_dbrx.py](https://huggingface.co/databricks/dbrx-instruct/blob/464e701f50aef4c1b59c81fb5667819a5d08e108/modeling_dbrx.py#L727) is:
> `input>layers[Norm>Attention(qkv,clamp,rope)>Norm>MOE_ffn]>Norm>Output`
> 
> Thanks to @slaren as it was pretty straightforward after Grok-1 experts merged example.
> Special thanks to @megha95 for the review and fixes.
> 
> Closes #6344.
> 
> ### Changes
> - Introduce `dbrx` architecture in `convert-hf-to-gguf.py`, `gguf-py` and `llama.cpp`
> - `dbrx` graph implementation in `llama.cpp`
> - `eval-callback` also prints last n elements of each dimension
> 
> <details>
> 
> <summary>
> 
> ### Tests (WIP, help welcomed)
> 
> </summary>
> 
> <details>
> 
> <summary>0. Setup llama.cpp</summary>
> 
> ```shell
> git clone https://github.com/ggerganov/llama.cpp.git
> cd llama.cpp
> git checkout hp/model/support-dbrx
> 
> python3 -m venv venv
> source venv/bin/activate
> 
> pip install -r requirements.txt
> 
> mkdir build
> cd build
> cmake .. \
>   -DLLAMA_NATIVE=OFF \
>   -DLLAMA_BUILD_SERVER=ON \
>   -DLLAMA_CURL=ON \
>   -DLLAMA_CUDA=ON \
>   -DCUDAToolkit_ROOT=/usr/local/cuda \
>   -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
>   -DCMAKE_CUDA_ARCHITECTURES=native \
>   -DCMAKE_BUILD_TYPE=Release;
> cmake --build . --config Release -j
> ```
> 
> </details>
> 
> 1. Clone the [original repo](https://huggingface.co/databricks/dbrx-instruct)
> 
> ```shell
> # NOTE: DBRX requires to accept the Databricks Open Model license, so need an HF read token
> nohup python -c 'from huggingface_hub import snapshot_download; snapshot_download(repo_id="databricks/dbrx-instruct", token="XXX", local_dir="models/dbrx-16x12b-instruct")' > dbrx_download.log &
> tail -f dbrx_download.log
> ```
> 
> 2. Convert to GGUF
> 
> ```shell
> export PYTHONUNBUFFERED=1
> nohup python ./convert-hf-to-gguf.py models/dbrx-16x12b-instruct --outfile models/dbrx-16x12b-instruct-f16.gguf --outtype f16 > dbrx_convert.log &
> tail -f dbrx_convert.log
> ```
> 
> 2.b Debug the graph
> ```shell
> ./build/bin/eval-callback \
>                     --model     models/dbrx-16x12b-instruct-f16.gguf \
>                     --prompt "hello world!" \
>                     --seed 42 \
>                     --chatml
> ```
> 
> 3. Quantize (optional if you are GPU rich)
> 
> ```shell
> nohup ./build/bin/quantize models/dbrx-16x12b-instruct-f16.gguf models/dbrx-16x12b-instruct-q4_0.gguf q4_0 > dbrx_gguf_q4_0.log &
> tail -f dbrx_gguf_q4_0.log
> ```
> 
> 4. Prompt it
> 
> ```shell
> ./build/bin/main \
>    --model models/dbrx-16x12b-instruct-q4_0.gguf \
>    -ngl 41 \
>    --prompt "I believe the meaning of life is" \
>    --seed 42
> 
> I believe the meaning of life is to give life meaning.  I think it's important to make an impact and do good in the world.  I feel like I've done good in my life and I think I've made a positive impact on many people.  I feel like I've made the world a better place just by being in it.  I'm proud of that and I think that's what gives my life meaning.
> 
> I also think that it's important to experience things in life and to learn and grow.  I've done a lot of traveling and experienced a lot of different cultures and I've learned a lot from that.  I've also learned a lot from the people I've met and the experiences I've had.  I think that's what gives my life depth and richness. [end of text]
> ```
> 
> 5. PPL q4_0
> 
> ```shell
> ./scripts/get-wikitext-2.sh
> ./build/bin/perplexity \
>    --model models/dbrx-16x12b-instruct-q4_0.gguf \
>    -ngl 41 \
>    -f wikitext-2-raw/wiki.test.raw \
>    -b 512
> 
> # Results TODO (help welcomed)
> ```
> 
> 6. Hellaswag 400
> 
> ```shell
> ./scripts/get-hellaswag.sh
> ./build/bin/perplexity \
>    --model models/dbrx-16x12b-instruct-q4_0.gguf \
>    -ngl 41 \
>    -f hellaswag_val_full.txt \
>    --hellaswag \
>    --hellaswag-tasks 400
> 
> # Results TODO (help welcomed)
> ```
> 
> 7. Importance matrix
> 
> ```shell
> ./scripts/get-wikitext-2.sh
> ./build/bin/imatrix \
>   --model models/dbrx-16x12b-instruct-f16.gguf \
>   -f wikitext-2-raw/wiki.train.raw \
>   -o dbrx-16x12b-instruct-f16.imatrix \
>   --seed 42 \
>   --chatml
> 
> # Results TODO (help welcomed)
> ```
> 
> For convenience, imatrix will be uploaded to https://huggingface.co/phymbert/dbrx-16x12b-instruct-f16/tree/main
> 
> <details>
> <summary>8. Split and upload to HF (because we love it)</summary>
> 
> ```shell
> mkdir models/dbrx-16x12b-instruct-q4_0
> nohup ./build/bin/gguf-split --split --split-max-tensors 33 models/dbrx-16x12b-instruct-q4_0.gguf models/dbrx-16x12b-instruct-q4_0/dbrx-16x12b-instruct-q4_0 > dbrx_q4_0_gguf_split.log &
> tail -f dbrx_q4_0_gguf_split.log
> export HF_HUB_ENABLE_HF_TRANSFER=1
> huggingface-cli upload phymbert/dbrx-16x12b-instruct-gguf models/dbrx-16x12b-instruct
> ```
> 
> </details>
> </details>
> 
> #### Usage in the server
> 
> ```shell
> server  --host 0.0.0.0 --port 8080 \
>         --hf-repo phymbert/dbrx-16x12b-instruct-q4_0-gguf \
>         --hf-file          dbrx-16x12b-instruct-q4_0-00001-of-00010.gguf \
>         --model     models/dbrx-16x12b-instruct-q4_0-00001-of-00010.gguf \
>         -ngl      41 \
>         --parallel 2 \
>         --metrics \
>         --ctx-size   4096 \
>         --batch-size 2048 \
>         --ubatch-size 256 \
>         --log-format text
> ```
> 
> ### Tasks
> 
> - [x] DBRX license usage clarification on GGUF & Hugging Face: https://github.com/ggerganov/llama.cpp/issues/6344#issuecomment-2041130261
> - [x] convert to GGUF, fixed by @megha95
> - [x] tiktoken tokenizer assessment, looks to work the same as `gpt2`/`bpe` except with different vocab & merges: https://github.com/ggerganov/llama.cpp/pull/6515#issuecomment-2049433487 REMOVED by [Databricks](https://github.com/ggerganov/llama.cpp/pull/6515#issuecomment-2050619268) thanks
> - [x] quantize q8_0
> - [x] quantize q4_0
> - [x] split and uploaded on [HF](https://huggingface.co/collections/phymbert/dbrx-16x12b-instruct-gguf-6619a7a4b7c50831dd33c7c8) [Q8_0](https://huggingface.co/phymbert/dbrx-16x12b-instruct-q8_0-gguf/tree/main), [Q6_K](https://huggingface.co/phymbert/dbrx-16x12b-instruct-q6_k-gguf), [Q4_0](https://huggingface.co/phymbert/dbrx-16x12b-instruct-q4_0-gguf/tree/main), [Q3_K_M](https://huggingface.co/phymbert/dbrx-16x12b-instruct-q3_k_m-gguf), [IQ3_S](https://huggingface.co/phymbert/dbrx-16x12b-instruct-iq3_s-gguf)
> - [x] llama.cpp main CLI
> - [x] confirm the graph implementation is correct, fixed by @megha95
> - [ ] perplexity on wiki text (help welcomed)
> - [ ] hellaswag on random task 400 (help welcomed)
> - [x] imatrix on wiki text, [q8_0](https://huggingface.co/dranger003/dbrx-instruct-iMat.GGUF/blob/main/ggml-dbrx-instruct-16x12b-q8_0-imatrix.dat) [f16](https://huggingface.co/dranger003/dbrx-instruct-iMat.GGUF/blob/main/ggml-dbrx-instruct-16x12b-f16_imatrix-wiki.dat) thanks to @dranger003
> - [x] DBRX [Chat Template support](https://huggingface.co/databricks/dbrx-instruct/blob/main/tiktoken.py#L193), @ngxson it looks standard `chatml` yes, EDIT REMOVED, [standard](https://huggingface.co/databricks/dbrx-instruct/blob/main/tokenizer_config.json#L198) now
> - [x] support op clamp on metal (can be done later on) #6662
> 
> ### License
> 
> `DBRX` is distributed under the [Databricks Open Model License](https://www.databricks.com/legal/open-model-license) agreement.

**Comment by phymbert** [comment]
> @phymbert I trained a new imatrix on the FP16 weights for 2000 chunks (1M tokens) on wiki.train
Thanks, have you managed to build quant q8_0 ? for me it stucks at tensors 66 (using all CPU)

**Comment by jukofyork** [comment]
Just quantizing it and using @dranger003 new imatrix file and got this:

`./quantize --imatrix dbrx:16x12b-instruct-f16-imatrix-wiki.dat dbrx:16x12b-instruct-f16.gguf dbrx:16x12b-instruct-q4_K_M.gguf Q4_K_M 10`

```
.
.
.
[   7/ 323]                    token_embd.weight - [ 6144, 100352,     1,     1], type =    f16, 
====== llama_model_quantize_internal: did not find weights for token_embd.weight
converting to q4_K .. size =  1176.00 MiB ->   330.75 MiB
[   8/ 323]             blk.0.ffn_up_exps.weight - [ 6144, 10752,    16,     1], type =    f16, converting to q4_K .. size =  2016.00 MiB ->   567.00 MiB
.
.
.
```

It seems to have carried on fine, but just checking this OK?

**Comment by dranger003** [comment]
@phymbert I have never tried the imatrix on quants Q6_K and higher ([because of this](https://github.com/ggerganov/llama.cpp/pull/4930)). I just started the IQ4_XS right now and it's at tensor 90 already but it's very slow, doesn't seem stuck so far.

> The improvement is most significant for low-bit quantization. It decreases with bits-per-weight used, and becomes marginal for Q6_K.

**Comment by dranger003** [comment]
> It seems to have carried on fine, but just checking this OK?

Yes, I believe this is expected and the author of imatrix mentioned it in some post but I don't have the link at this very moment.

**Comment by jukofyork** [comment]
> > I trained a new imatrix on the FP16 weights for 2000 chunks (1M tokens) on wiki.train
> 
> Thanks @dranger003, have you managed to build quant q8_0 ? for me it stucks at tensors 66 (using all CPU)

I had this 2 days ago trying to quantize a 70b Llama2 based model: I've got 44 cores (88 threads) in this this machine and it did the first 20 or so tensors, and then got stuck using 100% CPU and didn't finish. IIRC, I reran it very slowly with 1 thread and it finished then.

**Comment by dranger003** [comment]
There are some reports of slowing down using too many threads here https://github.com/ggerganov/llama.cpp/pull/3115.  
I typically use 12 cores max even when I have more.

**Comment by dranger003** [comment]
These results are not really unexpected, but I thought maybe the FP16 imatrix would help a bit more than that.

| Quant | IMatrix Quant/Dataset/Chunks | Size (GiB) | PPL (wiki.test) |
| -- | -- | -- | -- |
| IQ4_XS | Q8_0/wiki.train/200 | 65.29 | 5.2260 +/- 0.03558 |
| IQ4_XS | FP16/wiki.train/2000 | 65.29 | 5.2241 +/- 0.03559 |
| IQ4_XS | - | 66.05 | 5.2546 +/- 0.03570 |

**Comment by jukofyork** [comment]
Can anybody see anything wrong with this `FP16` model:

```
./main --model ./dbrx:16x12b-instruct-f16.gguf --seed 42 --prompt "I believe the meaning of life is " 
Log start
main: build = 2665 (4bd0f93e)
main: built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu
main: seed  = 42
llama_model_loader: loaded meta data with 24 key-value pairs and 323 tensors from ./dbrx:16x12b-instruct-f16.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = dbrx
llama_model_loader: - kv   1:                               general.name str              = dbrx
llama_model_loader: - kv   2:                           dbrx.block_count u32              = 40
llama_model_loader: - kv   3:                        dbrx.context_length u32              = 32768
llama_model_loader: - kv   4:                      dbrx.embedding_length u32              = 6144
llama_model_loader: - kv   5:                   dbrx.feed_forward_length u32              = 10752
llama_model_loader: - kv   6:                  dbrx.attention.head_count u32              = 48
llama_model_loader: - kv   7:               dbrx.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                        dbrx.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:                   dbrx.attention.clamp_kqv f32              = 8.000000
llama_model_loader: - kv  10:                          general.file_type u32              = 1
llama_model_loader: - kv  11:                          dbrx.expert_count u32              = 16
llama_model_loader: - kv  12:                     dbrx.expert_used_count u32              = 4
llama_model_loader: - kv  13:          dbrx.attention.layer_norm_epsilon f32              = 0.000010
llama_model_loader: - kv  14:                          general.file_type u32              = 1
llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  16:                      tokenizer.ggml.tokens arr[str,100352]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,100352]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  18:                      tokenizer.ggml.merges arr[str,100000]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  19:                tokenizer.ggml.bos_token_id u32              = 100257
llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 100257
llama_model_loader: - kv  21:            tokenizer.ggml.unknown_token_id u32              = 100257
llama_model_loader: - kv  22:            tokenizer.ggml.padding_token_id u32              = 100277
llama_model_loader: - kv  23:                    tokenizer.chat_template str              = {% if messages[0]['role'] == 'system'...
llama_model_loader: - type  f32:   81 tensors
llama_model_loader: - type  f16:  242 tensors
llm_load_vocab: special tokens definition check successful ( 96/100352 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = dbrx
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 100352
llm_load_print_meta: n_merges         = 100000
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 6144
llm_load_print_meta: n_head           = 48
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 6
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 1.0e-05
llm_load_print_meta: f_norm_rms_eps   = 0.0e+00
llm_load_print_meta: f_clamp_kqv      = 8.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 10752
llm_load_print_meta: n_expert         = 16
llm_load_print_meta: n_expert_used    = 4
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 16x12B
llm_load_print_meta: model ftype      = F16
llm_load_print_meta: model params     = 131.60 B
llm_load_print_meta: model size       = 245.12 GiB (16.00 BPW) 
llm_load_print_meta: general.name     = dbrx
llm_load_print_meta: BOS token        = 100257 '<|endoftext|>'
llm_load_print_meta: EOS token        = 100257 '<|endoftext|>'
llm_load_print_meta: UNK token        = 100257 '<|endoftext|>'
llm_load_print_meta: PAD token        = 100277 '<|pad|>'
llm_load_print_meta: LF token         = 128 'Ä'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA RTX A6000, compute capability 8.6, VMM: yes
  Device 1: NVIDIA RTX A6000, compute capability 8.6, VMM: yes
llm_load_tensors: ggml ctx size =    0.37 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/41 layers to GPU
llm_load_tensors:        CPU buffer size = 251001.40 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =    80.00 MiB
llama_new_context_with_model: KV self size  =   80.00 MiB, K (f16):   40.00 MiB, V (f16):   40.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.38 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =  6168.00 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    13.01 MiB
llama_new_context_with_model: graph nodes  = 2886
llama_new_context_with_model: graph splits = 404

system_info: n_threads = 44 / 88 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | 
sampling: 
	repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temperature 
generate: n_ctx = 512, n_batch = 2048, n_predict = -1, n_keep = 0


I believe the meaning of life is 42.

But really, I don't
```

I'm not expecting it to match the output of @phymbert's exactly, but it's just absolute garbage compared to his for some reason (the `Q4_0` I made from this gave the same output and was equally bad).

It's not just slightly bad either - it's *sub-broken-frankenmerge* level of bad! It almost feels like some of its tensors are lost or scrambled because it completely failed all the simple coding tasks phymbert's `Q4_0` passed yesterday and doesn't seem to have a clue about things like Boost, GSL, Eclipse, etc.

It was created with:

```
./convert-hf-to-gguf.py ./dbrx-instruct --outfile ./dbrx:16x12b-instruct-f16.gguf --outtype f16
```

and I definitely pulled the instruct repo:

```
./hfdownloader -j databricks/dbrx-instruct -t <TOKEN>
```

I don't normally use `hfdownloader` and just use `wget`, but this was passworded  and `git clone` sometimes pulls double the data from the `.git` folder, etc.

@phymbert Can you confirm the `FP16` you're uploading to HF now is  the same one that made the working `Q4_0` quant tested above from? I can't really face downloading another broken HF copy just to see and might just use your `FP16` instead... :frowning_face:

**Comment by phymbert** [comment]
> I'm not expecting it to match the output

I run only on CPU, so the output will differ from CUDA yes.

> Can you confirm the FP16 you're uploading to HF now

I did not manage to complete the upload, sorry. better to restart from the original repo yes. The quantum models I have upload are computed without importance matrix.

**Comment by jukofyork** [comment]
> > I'm not expecting it to match the output
> 
> I run only on CPU, so the output will differ from CUDA yes.
> 
> > Can you confirm the FP16 you're uploading to HF now
> 
> I did not manage to complete the upload, sorry. better to restart from the original repo yes. The quantum models I have upload are computed without importance matrix.

I think it was using CPU? I reran it with `ngl 0` jsut to be sure and got the same answer of "42\nBut really" too.

Interestingly @dranger003 `IQ4_XS` gives the same answer too:

```
./main --model ./dbrx:16x12b-instruct-iq4_xs.gguf --seed 42 --prompt "I believe the meaning of life is " -ngl 0
```

```
Log start
main: build = 2665 (4bd0f93e)
main: built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu
main: seed  = 42
llama_model_loader: loaded meta data with 27 key-value pairs and 323 tensors from ./dbrx:16x12b-instruct-iq4_xs.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = dbrx
llama_model_loader: - kv   1:                               general.name str              = dbrx
llama_model_loader: - kv   2:                           dbrx.block_count u32              = 40
llama_model_loader: - kv   3:                        dbrx.context_length u32              = 32768
llama_model_loader: - kv   4:                      dbrx.embedding_length u32              = 6144
llama_model_loader: - kv   5:                   dbrx.feed_forward_length u32              = 10752
llama_model_loader: - kv   6:                  dbrx.attention.head_count u32              = 48
llama_model_loader: - kv   7:               dbrx.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                        dbrx.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:                   dbrx.attention.clamp_kqv f32              = 8.000000
llama_model_loader: - kv  10:                          general.file_type u32              = 30
llama_model_loader: - kv  11:                          dbrx.expert_count u32              = 16
llama_model_loader: - kv  12:                     dbrx.expert_used_count u32              = 4
llama_model_loader: - kv  13:          dbrx.attention.layer_norm_epsilon f32              = 0.000010
llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,100352]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,100352]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,100000]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 100257
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 100257
llama_model_loader: - kv  20:            tokenizer.ggml.unknown_token_id u32              = 100257
llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 100277
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = {% if messages[0]['role'] == 'system'...
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - kv  24:                                   split.no u16              = 0
llama_model_loader: - kv  25:                                split.count u16              = 0
llama_model_loader: - kv  26:                        split.tensors.count i32              = 323
llama_model_loader: - type  f32:   81 tensors
llama_model_loader: - type  f16:   40 tensors
llama_model_loader: - type q6_K:    1 tensors
llama_model_loader: - type iq4_xs:  201 tensors
llm_load_vocab: special tokens definition check successful ( 96/100352 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = dbrx
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 100352
llm_load_print_meta: n_merges         = 100000
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 6144
llm_load_print_meta: n_head           = 48
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 6
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 1.0e-05
llm_load_print_meta: f_norm_rms_eps   = 0.0e+00
llm_load_print_meta: f_clamp_kqv      = 8.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 10752
llm_load_print_meta: n_expert         = 16
llm_load_print_meta: n_expert_used    = 4
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 16x12B
llm_load_print_meta: model ftype      = IQ4_XS - 4.25 bpw
llm_load_print_meta: model params     = 131.60 B
llm_load_print_meta: model size       = 65.28 GiB (4.26 BPW) 
llm_load_print_meta: general.name     = dbrx
llm_load_print_meta: BOS token        = 100257 '<|endoftext|>'
llm_load_print_meta: EOS token        = 100257 '<|endoftext|>'
llm_load_print_meta: UNK token        = 100257 '<|endoftext|>'
llm_load_print_meta: PAD token        = 100277 '<|pad|>'
llm_load_print_meta: LF token         = 128 'Ä'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA RTX A6000, compute capability 8.6, VMM: yes
  Device 1: NVIDIA RTX A6000, compute capability 8.6, VMM: yes
llm_load_tensors: ggml ctx size =    0.37 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/41 layers to GPU
llm_load_tensors:        CPU buffer size = 66849.12 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =    80.00 MiB
llama_new_context_with_model: KV self size  =   80.00 MiB, K (f16):   40.00 MiB, V (f16):   40.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.38 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =  1698.00 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    13.01 MiB
llama_new_context_with_model: graph nodes  = 2886
llama_new_context_with_model: graph splits = 404

system_info: n_threads = 44 / 88 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | 
sampling: 
	repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temperature 
generate: n_ctx = 512, n_batch = 2048, n_predict = -1, n_keep = 0


I believe the meaning of life is 42.

But really
```

It's harder for me to test this one on the coding tasks as Ollama won't import `IQ` models, but I will try running it using `server` and ask it some stuff in `OpenWebUI`.

**Comment by phymbert** [comment]
> I think it was using CPU? I reran it with ngl 0 jsut to be sure and got the same answer of "42\nBut really" too.

I meant the CPU ggml backend, not CUDA.

**Comment by jukofyork** [comment]
> > I think it was using CPU? I reran it with ngl 0 jsut to be sure and got the same answer of "42\nBut really" too.
> 
> I meant the CPU ggml backend, not CUDA.

Oh, I no problem.

**Comment by dranger003** [comment]
@jukofyork This model is an instruct model, without its template I don't think the output will be reliable. Below is what I use and the output seems consistent and reliable.

```
./build/bin/main -ngl 41 -c 4096 -s 0 --temp 0 -e -p "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\nWrite an essay about AI.<|im_end|>\n<|im_start|>assistant\n" -m /md0/models/databricks/ggml-dbrx-instruct-16x12b-iq4_xs.gguf
```

**Comment by phymbert** [comment]
> without its template I don't think the output will be reliable
Or use `--chatml`

**Comment by dranger003** [comment]
> > without its template I don't think the output will be reliable
> 
> Or use `--chatml`

Yes, but that kicks you into interactive instruct mode. Unless there is an option to use the template without auto activating interactive?

**Comment by phymbert** [comment]
> Yes, but that kicks you into interactive instruct mode. Unless there is an option to use the template without auto activating interactive?

I do not remember facing such issue.

**Comment by phymbert** [comment]
> These results are not really unexpected, but I thought maybe the FP16 imatrix would help a bit more than that.
> 
> Quant	IMatrix Quant/Dataset/Chunks	Size (GiB)	PPL (wiki.test)
> IQ4_XS	Q8_0/wiki.train/200	65.29	5.2260 +/- 0.03558
> IQ4_XS	FP16/wiki.train/2000	65.29	5.2241 +/- 0.03559
> IQ4_XS	-	66.05	5.2546 +/- 0.03570

@abhi-mosaic any idea why the quantum models performing so bad ? is there an issue with the llama.cpp quantization methods with this architecture ?

**Comment by dranger003** [comment]
> > Yes, but that kicks you into interactive instruct mode. Unless there is an option to use the template without auto activating interactive?
> 
> I do not remember facing such issue.

Can you try this? This gives me an input prompt in interactive mode.
```
./build/bin/main -ngl 41 -s 0 --temp 0 --chatml -p "Write an essay about AI." -m /md0/models/databricks/ggml-dbrx-instruct-16x12b-iq4_xs_imatrix-wiki.gguf
```

**Comment by jukofyork** [comment]
Yeah, sorry for not making it clear: that was just a test to match the one here.

I've been using the --chatml option and have the correct template in the Ollma modelfile too.

The odd thing is that dranger003's `IQ4_XS` seems to be matching my terrible models' output, but not being able to import it into Ollama I can't make a detailed test.

I'm redownloading phymbert's `Q4_0` now to double check what's happening but AFAIK the testing conditions were exactly the same with all the same settings (temperature=0 also).

I'll report back if I find out the problem - is there any command to dump the meta data from the GGUF files so I can run diff on them?

**Comment by dranger003** [comment]
```
./gguf-py/scripts/gguf-dump.py -h
usage: gguf-dump.py [-h] [--no-tensors] [--json] [--json-array] model

Dump GGUF file metadata

positional arguments:
  model         GGUF format model filename

options:
  -h, --help    show this help message and exit
  --no-tensors  Don't dump tensor metadata
  --json        Produce JSON output
  --json-array  Include full array values in JSON output (long)
```

**Comment by chigkim** [comment]
I just pulled the latest master branch of llama.cpp like an built it hour ago.
Then I download iq3_xxs from the link below.
https://huggingface.co/phymbert/dbrx-16x12b-instruct-iq3_xxs-gguf
Then I merged with gguf-split --merge ...
However, when I ran the model to ask a question, I got just numbers like 0 01 0 01...
Here's my command.

`llama.cpp/main -m models/dbrx-16x12b-instruct-iq3_xxs.gguf -n -1 -c 2048 --temp 0.6 --interactive-first -r "<|im_end|>" --in-prefix "<|im_start|>user\n" --in-suffix "<|im_end|>\n<|im_start|>assistant\n" -e -p "<|im_start|>system\nYou're a friendly assistant.<|im_end|>\n"`

I also tried --chatml, but got the same result.
I'd appreciate any tip! Thanks!

**Comment by phymbert** [comment]
The iq3_xxs has been quantized without imatrix, so don't have too much hope on generation quality. 
You do not need to merge anymore. Loading from the sharded model is built-in. 
Is a simple prompt like there is in the PR summary working fine ? Have you tried running the server with the chat completion endpoint ?

**Comment by chigkim** [comment]
Yes, `-p "I believe the meaning of life is"` does generate English words. I guess it's having a problem with chatml prompt format then?

I merged bc I was hoping to use it with Ollama later.

**Comment by jukofyork** [comment]
> I merged bc I was hoping to use it with Ollama later.

I was goii going to say it won't work in Ollama:

https://github.com/ollama/ollama/issues/3622#issuecomment-2053720042

but it seems iq3_xxs is the only IQ type supported (?)

I did manage to hack in the latest llama.cpp and it does work (although I didn't alter the patches they make to server.cpp 👀). Hopefully they will bump to use the latest llama.cpp soon in the official branch.

**Comment by jukofyork** [comment]
> Yeah, sorry for not making it clear: that was just a test to match the one here.
> 
> I've been using the --chatml option and have the correct template in the Ollma modelfile too.
> 
> The odd thing is that dranger003's `IQ4_XS` seems to be matching my terrible models' output, but not being able to import it into Ollama I can't make a detailed test.
> 
> I'm redownloading phymbert's `Q4_0` now to double check what's happening but AFAIK the testing conditions were exactly the same with all the same settings (temperature=0 also).
> 
> I'll report back if I find out the problem - is there any command to dump the meta data from the GGUF files so I can run diff on them?

Just to say I've now completely redone everything from scratch and have successfully quantized a `Q4_K_M`:

```
./convert-hf-to-gguf.py dbrx-instruct --outfile dbrx:16x12b-instruct-f16.gguf --outtype f16
./imatrix --chunks 200 -m dbrx:16x12b-instruct-f16.gguf -f groups_merged.txt -o dbrx:16x12b-instruct-f16.imatrix -ngl 12
./quantize --imatrix dbrx:16x12b-instruct-f16.imatrix dbrx:16x12b-instruct-f16.gguf dbrx:16x12b-instruct-q4_K_M.gguf Q4_K_M 12
```

The `imatrix` run only managed to create 91 chunks from `groups_merged.txt` but I can share it on HF if anybody wants?

I think the problem I had yesterday was the FP16 GGUF must have been corrupted or truncated somehow; I did notice `convert-hf-to-gguf.py` used an extraordinary amount of RAM at one point and I was using the machine for other stuff when I did the first run of `convert-hf-to-gguf.py`.

Anyway, panic over and the `Q4_K_M` + imatrix does seem (subjectively) slightly better than the `Q4_0` on coding tasks so far.

Big thanks to @phymbert  and @dranger003 for all the help! :+1:

**Comment by jukofyork** [comment]
So I'm just converting `c4ai-command-r-plus` now and noticed a couple of differences:

- `convert-hf-to-gguf.py` used a huge amount of RAM (250-300GB) for `dbrx-instruct` and only wrote the `FP16` file right at the end, whereas `c4ai-command-r-plus` (and other models I've quantized) write the file out bit by bit and use a small amount of RAM.
- `imatrix` reported saving 10 chunks every 2-3 actual chunks, eg: [1], [2], .. "saving 10 chunks", [3], [4], [5], "saving 20 chunks" and so on, whereas `c4ai-command-r-plus` reported it could make 95 chunks and really did save every 10 chunks.

These may be known but just thought I should point them out in case relevant.

**Comment by chigkim** [comment]
Ollama 0.3.2 supports dbrx. I downloaded their version and tried.
It looks like quant problem. At least their Q2_K produces English, but makes no sense. Reminds me when I tried GPT-2 124M. It repeats and digresses like crazy.
Q4_K works fine though.
I wonder why Q2 for dbrx is particularly poor. Q2 for WizardLM2-8x22b, Zephyr-Orpor-8x22b, command-r-plus all work fine.

**Comment by jukofyork** [comment]
> > Yeah, sorry for not making it clear: that was just a test to match the one here.
> > I've been using the --chatml option and have the correct template in the Ollma modelfile too.
> > The odd thing is that dranger003's `IQ4_XS` seems to be matching my terrible models' output, but not being able to import it into Ollama I can't make a detailed test.
> > I'm redownloading phymbert's `Q4_0` now to double check what's happening but AFAIK the testing conditions were exactly the same with all the same settings (temperature=0 also).
> > I'll report back if I find out the problem - is there any command to dump the meta data from the GGUF files so I can run diff on them?
> 
> Just to say I've now completely redone everything from scratch and have successfully quantized a `Q4_K_M`:
> 
> ```
> ./convert-hf-to-gguf.py dbrx-instruct --outfile dbrx:16x12b-instruct-f16.gguf --outtype f16
> ./imatrix --chunks 200 -m dbrx:16x12b-instruct-f16.gguf -f groups_merged.txt -o dbrx:16x12b-instruct-f16.imatrix -ngl 12
> ./quantize --imatrix dbrx:16x12b-instruct-f16.imatrix dbrx:16x12b-instruct-f16.gguf dbrx:16x12b-instruct-q4_K_M.gguf Q4_K_M 12
> ```
> 
> The `imatrix` run only managed to create 91 chunks from `groups_merged.txt` but I can share it on HF if anybody wants?
> 
> I think the problem I had yesterday was the FP16 GGUF must have been corrupted or truncated somehow; I did notice `convert-hf-to-gguf.py` used an extraordinary amount of RAM at one point and I was using the machine for other stuff when I did the first run of `convert-hf-to-gguf.py`.
> 
> Anyway, panic over and the `Q4_K_M` + imatrix does seem (subjectively) slightly better than the `Q4_0` on coding tasks so far.
> 
> Big thanks to @phymbert and @dranger003 for all the help! 👍

This model is so weird... Tried to re-quant it today to use the new BPE stuff, found out it wouldn't work so as had already deleted the old model went back to old llama.cpp pull from mid-April (that I used above) to recreate it from scratch and it's back to working like a broken frankenmerge again!? WTF???

I thought it might be because I used 22 threads instead of 12 in the example above, but I think it's the FP16 that must be screwing up somehow as I noticed it seems to be getting a PPL score ***way*** bigger than any other model when creating the imatrix file:

```
Final estimate: PPL = 8.7773 +/- 0.17953
```

This is using `groups_merged.txt` so hard to compare with anybody else's but that PPL is between 2 and 3 times what other models get for the same file when creating the imatrix file and @dranger003 gets around 5.2 for `wiki.txt` on his HF page.

Last time it did this, I completely re-downloaded and redid everything, but TBO the model isn't that great and not sure I can be arsed with all that again (plus seems unlikely I would corrupt the download both times).

**Comment by jukofyork** [comment]
So gonna have one more go at creating the FP16 (using branch `b2665` to be absolutely sure) and get the perplexity values for wiki.test.raw as well. Will report back if I find anything.

**Comment by jukofyork** [comment]
So I think there may be a thread race if you set the number of quantize threads too high and I don't get the gibberish producing version if I keep to 12 threads (as suggested earlier in this PR).

But it also seems this model doesn't play nice with the imatrix calculation either (compared to phymbert's original `Q4_0`).

I'm now experimenting with turning on all 16 experts to create the imatrix file:

**imatrix created with 4 experts**
```
Final estimate: PPL = 8.7773 +/- 0.17953
```

**imatrix created with 16 experts**
```
Final estimate: PPL = 8.8745 +/- 0.17301
```

and using that imatrix to quantize the original FP16 (ie: with 4 experts) to see the effect...

It could be that some of the experts aren't getting triggered at all or are getting weighted so low in the gating that they aren't contributing hardly anything. With regard to my comment on the potential use of Tikhonov regularization:

https://github.com/ggerganov/llama.cpp/discussions/5263#discussioncomment-9163642

this would be solved by setting the diagonals in proportion to the sqrt(n) (where n is number of times the expert was not skipped over) instead of using the identity matrix to account for the sample size differences. Depending on how the value of `x` is calculated in the loop, n may or may not need to be the weighted sum of the output of the active gating networks instead (but IIRC it's using backprop to get these so that will likely be accounted for if so).

**Comment by jukofyork** [comment]
Using all 16 experts does somewhat work, but looking through the code I think I can see what is the root of the problem:

```
    // this has been adapted to the new format of storing merged experts in a single 3d tensor
    // ref: https://github.com/ggerganov/llama.cpp/pull/6387
    if (t->op == GGML_OP_MUL_MAT_ID) {
        const int idx  = ((int32_t *) t->op_params)[0];
        const ggml_tensor * ids = t->src[2];
        const int n_as = src0->ne[2];

        // the top-k selected expert ids are stored in the ids tensor
        // for simplicity, always copy ids to host, because it is small
        GGML_ASSERT(ids->ne[1] == src1->ne[1]);
        m_ids.resize(ggml_nbytes(ids)/sizeof(int));
        ggml_backend_tensor_get(ids, m_ids.data(), 0, ggml_nbytes(ids));

        auto & e = m_stats[wname];

        ++e.ncall;
        // NOTE: since we select top-k experts, the number of calls for the expert tensors will be k times larger
        //       using the following line, we can correct for that if needed by replacing the line above with:
        //if (idx == t->src[0]->ne[0] - 1) ++e.ncall;

        // loop over all possible experts, regardless if they are used or not in the batch
        for (int ex = 0; ex < n_as; ++ex) {
            size_t e_start = ex*src1->ne[0];
            if (e.values.empty()) {
                e.values.resize(src1->ne[0]*n_as, 0);
            }
            else if (e.values.size() != (size_t)src1->ne[0]*n_as) {
                fprintf(stderr, "Oops: inconsistent size for %s (%d vs %d)\n", wname.c_str(), (int)e.values.size(), (int)src1->ne[0]*n_as);
                exit(1); //GGML_ASSERT(false);
            }
            if (m_params.verbosity > 1) {
                printf("%s[%d]: %32s, %s, %5d x %5d, %d\n", __func__, m_last_call, wname.c_str(), ggml_op_name(t->op), (int)src1->ne[0], (int)src1->ne[1], (int)src1->type);
            }
            for (int row = 0; row < (int)src1->ne[1]; ++row) {
                const int excur = m_ids[row*n_as + idx];
                GGML_ASSERT(excur >= 0 && excur < n_as); // sanity check
                if (excur != ex) continue;
                const float * x = data + row * src1->ne[0];
                for (int j = 0; j < (int)src1->ne[0]; ++j) {
                    e.values[e_start + j] += x[j]*x[j];
                }
            }
            if (e.ncall > m_last_call) {
                m_last_call = e.ncall;
                if (m_last_call % m_params.n_output_frequency == 0) {
                    save_imatrix();
                }
                if (m_params.keep_every > 0 && m_last_call%m_params.keep_every == 0) {
                    keep_imatrix(m_last_call);
                }
            }
        }
    }
```

`++e.ncall`

```
static void load_imatrix(const std::string & imatrix_file, std::unordered_map<std::string, std::vector<float>> & imatrix_data) {
    std::ifstream in(imatrix_file.c_str(), std::ios::binary);
    if (!in) {
        printf("%s: failed to open %s\n",__func__, imatrix_file.c_str());
        exit(1);
    }
    int n_entries;
    in.read((char *)&n_entries, sizeof(n_entries));
    if (in.fail() || n_entries < 1) {
        printf("%s: no data in file %s\n", __func__, imatrix_file.c_str());
        exit(1);
    }
    for (int i = 0; i < n_entries; ++i) {
        int len; in.read((char *)&len, sizeof(len));
        std::vector<char> name_as_vec(len+1);
        in.read((char *)name_as_vec.data(), len);
        if (in.fail()) {
            printf("%s: failed reading name for entry %d from %s\n", __func__, i+1, imatrix_file.c_str());
            exit(1);
        }
        name_as_vec[len] = 0;
        std::string name{name_as_vec.data()};
        auto & e = imatrix_data[name];
        int ncall;
        in.read((char *)&ncall, sizeof(ncall));
        int nval;
        in.read((char *)&nval, sizeof(nval));
        if (in.fail() || nval < 1) {
            printf("%s: failed reading number of values for entry %d\n", __func__, i);
            imatrix_data = {};
            exit(1);
        }
        e.resize(nval);
        in.read((char *)e.data(), nval*sizeof(float));
        if (in.fail()) {
            printf("%s: failed reading data for entry %d\n", __func__, i);
            imatrix_data = {};
            exit(1);
        }
        if (ncall > 0) {
            for (auto& v : e) v /= ncall;
        }

        if (getenv("LLAMA_TRACE")) {
            printf("%s: loaded data (size = %6d, ncall = %6d) for '%s'\n", __func__, int(e.size()), ncall, name.c_str());
        }
    }
    printf("%s: loaded %d importance matrix entries from %s\n", __func__, int(imatrix_data.size()), imatrix_file.c_str());
}
```

`for (auto& v : e) v /= ncall;`

```
            if (quant_weights) {
                const float * qw = quant_weights + QK_K*ibl + 32*ib;
                for (int i = 0; i < 32; ++i) weight[i] = qw[i] * sqrtf(sigma2 + xb[i]*xb[i]);
            } else {
                for (int i = 0; i < 32; ++i) weight[i] = xb[i]*xb[i];
            }
```

`quant_weights` is where the value ends up getting used.

By setting `LLAMA_TRACE=1` we can see this too:
```
load_imatrix: loaded data (size = 172032, ncall =    364) for 'blk.38.ffn_down_exps.weight'
load_imatrix: loaded data (size =   6144, ncall =     91) for 'blk.38.ffn_gate_inp.weight'
load_imatrix: loaded data (size =   6144, ncall =     91) for 'blk.38.attn_output.weight'
load_imatrix: loaded data (size = 172032, ncall =    364) for 'blk.37.ffn_down_exps.weight'
load_imatrix: loaded data (size =  98304, ncall =    364) for 'blk.37.ffn_gate_exps.weight'
load_imatrix: loaded data (size =   6144, ncall =     91) for 'blk.37.ffn_gate_inp.weight'
load_imatrix: loaded data (size =   6144, ncall =     91) for 'blk.37.attn_output.weight'
```

1. The  experts should have their own counts as it's very likely their choice frequencies and gating weights won't be uniformly distributed. Obviously this will be very hard to add now without breaking other stuff.

2. It looks to me like the experts' tensor ultimate `quant_weights` values is getting divided by 16x more than it should be, but the code is very obtuse and I can't 100% sure if there is some double counting in the `\\ loop over all possible experts` loop:

We are dividing `blk.*.ffn_*_exps.weight` by 4 times more than `blk.*.attn_*.weight`, but in actual fact each of the expert MLPs in these combined tensors are activated **at most** 1:1 with the attention weights and **in expectation** only activated 1/4 as often as attention weights. I think this means the `for (auto& v : e) v /= ncall` line is actually dividing the sample count down by 16x more than it should (not 100% sure what the effect will be in `ggml-quants.c` though as the code is very cryptic and I don't have time to read it all).

I think it would be a good idea for somebody who knows the code base to have a really close look at what is going on here and possibly also double check that the softmax gating weighting factors are properly taken into account via backprop, etc.

**Comment by jukofyork** [comment]
My head hurts thinking about this but pretty sure (2) is correct via this example:

If only 1 expert were selected the counts would look like this:
```
load_imatrix: loaded data (size = 172032, ncall =    91) for 'blk.38.ffn_down_exps.weight'
load_imatrix: loaded data (size =   6144, ncall =     91) for 'blk.38.ffn_gate_inp.weight'
```

So for every 16 samples that went into the attention weighting factors 1 sample went into each of the expert's weighting factors (on average).

If all 16 expert were selected the counts would look like this:
```
load_imatrix: loaded data (size = 172032, ncall =    1456) for 'blk.38.ffn_down_exps.weight'
load_imatrix: loaded data (size =   6144, ncall =     91) for 'blk.38.ffn_gate_inp.weight'
```

So for every 1 samples that went into the attention weighting factors 1 sample went into each of the expert's weighting factors also.

In both cases it looks like the expert's weighting factors are getting divided by 16 times more than they should be.

**Comment by jukofyork** [comment]
> The experts should have their own counts as it's very likely their selection frequencies (and softmax gate-weight factors) won't be uniformly distributed. Obviously this will be very hard to add now without breaking other stuff.

On further thought maybe this doesn't matter as the `*n_as` fix will mean that when `for (auto& v : e) v /= ncall` gets run in `quantize` the uniformity of the distribution won't matter (by thinking through the cases where one expert always gets activated vs all equally activated anyway).
