### PR TITLE
llama : fix `llama_chat_format_single` for mistral

### LINKED ISSUE #8655: Bug: Mistral-Nemo-Instruct Chat template seems to be applied completely wrong
### What happened?

```
messages = [
    {"role":"system","content":"You are a helpful assistant"},
    {"role":"user","content":"Hello"},
]
```

Logs using Mistral-Nemo-Instruct:
```
eval: [ '<s>':1, 'You':4568, ' are':1584, ' a':1261, ' helpful':20351, ' assistant':27089, '':1010 ]
eval: [ '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4 ]
```

So the chat template for using Mistral-Nemo-Instruct is not applied correctly at all. It should look like this:
`<s>[INST] You are a helpful assistant\n\nHello[/INST]`

The system prompt should also not be added as the first message for this model but rather before the last user message. I don't know if this would require some changes to implement.

### Name and Version

$ ./llama.cpp/llama-cli --version
version: 3448 (b841d074)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Ubuntu 22.04.4 LTS

### Relevant log output

```
[1721759779] Log start
[1721759779] Cmd: ./llama.cpp/llama-cli -m ./models/Mistral-Nemo-Instruct-2407-Q5_K_M.gguf --ctx-size 8192 -ngl 41 -cnv --temp 0.3 --prompt "You are a helpful assistant"
[1721759779] main: build = 3448 (b841d074)
[1721759779] main: built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu
[1721759779] main: seed  = 1721759779
[1721759779] main: llama backend init
[1721759779] main: load the model and apply lora adapter, if any
[1721759779] llama_model_loader: loaded meta data with 39 key-value pairs and 363 tensors from ./models/Mistral-Nemo-Instruct-2407-Q5_K_M.gguf (version GGUF V3 (latest))
[1721759779] llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
[1721759779] llama_model_loader: - kv   0:                       general.architecture str              = llama
[1721759779] llama_model_loader: - kv   1:                               general.type str              = model
[1721759779] llama_model_loader: - kv   2:                               general.name str              = Mistral Nemo Instruct 2407
[1721759779] llama_model_loader: - kv   3:                            general.version str              = 2407
[1721759779] llama_model_loader: - kv   4:                           general.finetune str              = Instruct
[1721759779] llama_model_loader: - kv   5:                           general.basename str              = Mistral-Nemo
[1721759779] llama_model_loader: - kv   6:                         general.size_label str              = 12B
[1721759779] llama_model_loader: - kv   7:                            general.license str              = apache-2.0
[1721759779] llama_model_loader: - kv   8:                          general.languages arr[str,9]       = ["en", "fr", "de", "es", "it", "pt", ...
[1721759779] llama_model_loader: - kv   9:                          llama.block_count u32              = 40
[1721759779] llama_model_loader: - kv  10:                       llama.context_length u32              = 1024000
[1721759779] llama_model_loader: - kv  11:                     llama.embedding_length u32              = 5120
[1721759779] llama_model_loader: - kv  12:                  llama.feed_forward_length u32              = 14336
[1721759779] llama_model_loader: - kv  13:                 llama.attention.head_count u32              = 32
[1721759779] llama_model_loader: - kv  14:              llama.attention.head_count_kv u32              = 8
[1721759779] llama_model_loader: - kv  15:                       llama.rope.freq_base f32              = 1000000,000000
[1721759779] llama_model_loader: - kv  16:     llama.attention.layer_norm_rms_epsilon f32              = 0,000010
[1721759779] llama_model_loader: - kv  17:                 llama.attention.key_length u32              = 128
[1721759779] llama_model_loader: - kv  18:               llama.attention.value_length u32              = 128
[1721759779] llama_model_loader: - kv  19:                          general.file_type u32              = 17
[1721759779] llama_model_loader: - kv  20:                           llama.vocab_size u32              = 131072
[1721759779] llama_model_loader: - kv  21:                 llama.rope.dimension_count u32              = 128
[1721759779] llama_model_loader: - kv  22:            tokenizer.ggml.add_space_prefix bool             = false
[1721759779] llama_model_loader: - kv  23:                       tokenizer.ggml.model str              = gpt2
[1721759779] llama_model_loader: - kv  24:                         tokenizer.ggml.pre str              = tekken
[1721759779] llama_model_loader: - kv  25:                      tokenizer.ggml.tokens arr[str,131072]  = ["<unk>", "<s>", "</s>", "[INST]", "[...
[1721759779] llama_model_loader: - kv  26:                  tokenizer.ggml.token_type arr[i32,131072]  = [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...
[1721759779] llama_model_loader: - kv  27:                      tokenizer.ggml.merges arr[str,269443]  = ["Ä  Ä ", "Ä  t", "e r", "i n", "Ä  Ä...
[1721759779] llama_model_loader: - kv  28:                tokenizer.ggml.bos_token_id u32              = 1
[1721759779] llama_model_loader: - kv  29:                tokenizer.ggml.eos_token_id u32              = 2
[1721759779] llama_model_loader: - kv  30:            tokenizer.ggml.unknown_token_id u32              = 0
[1721759779] llama_model_loader: - kv  31:               tokenizer.ggml.add_bos_token bool             = true
[1721759779] llama_model_loader: - kv  32:               tokenizer.ggml.add_eos_token bool             = false
[1721759779] llama_model_loader: - kv  33:                    tokenizer.chat_template str              = {%- if messages[0]['role'] == 'system...
[1721759779] llama_model_loader: - kv  34:               general.quantization_version u32              = 2
[1721759779] llama_model_loader: - kv  35:                      quantize.imatrix.file str              = /models_out/Mistral-Nemo-Instruct-240...
[1721759779] llama_model_loader: - kv  36:                   quantize.imatrix.dataset str              = /training_dir/calibration_datav3.txt
[1721759779] llama_model_loader: - kv  37:             quantize.imatrix.entries_count i32              = 280
[1721759779] llama_model_loader: - kv  38:              quantize.imatrix.chunks_count i32              = 128
[1721759779] llama_model_loader: - type  f32:   81 tensors
[1721759779] llama_model_loader: - type q5_K:  241 tensors
[1721759779] llama_model_loader: - type q6_K:   41 tensors
[1721759780] llm_load_vocab: special tokens cache size = 1000
[1721759780] llm_load_vocab: token to piece cache size = 0,8498 MB
[1721759780] llm_load_print_meta: format           = GGUF V3 (latest)
[1721759780] llm_load_print_meta: arch             = llama
[1721759780] llm_load_print_meta: vocab type       = BPE
[1721759780] llm_load_print_meta: n_vocab          = 131072
[1721759780] llm_load_print_meta: n_merges         = 269443
[1721759780] llm_load_print_meta: vocab_only       = 0
[1721759780] llm_load_print_meta: n_ctx_train      = 1024000
[1721759780] llm_load_print_meta: n_embd           = 5120
[1721759780] llm_load_print_meta: n_layer          = 40
[1721759780] llm_load_print_meta: n_head           = 32
[1721759780] llm_load_print_meta: n_head_kv        = 8
[1721759780] llm_load_print_meta: n_rot            = 128
[1721759780] llm_load_print_meta: n_swa            = 0
[1721759780] llm_load_print_meta: n_embd_head_k    = 128
[1721759780] llm_load_print_meta: n_embd_head_v    = 128
[1721759780] llm_load_print_meta: n_gqa            = 4
[1721759780] llm_load_print_meta: n_embd_k_gqa     = 1024
[1721759780] llm_load_print_meta: n_embd_v_gqa     = 1024
[1721759780] llm_load_print_meta: f_norm_eps       = 0,0e+00
[1721759780] llm_load_print_meta: f_norm_rms_eps   = 1,0e-05
[1721759780] llm_load_print_meta: f_clamp_kqv      = 0,0e+00
[1721759780] llm_load_print_meta: f_max_alibi_bias = 0,0e+00
[1721759780] llm_load_print_meta: f_logit_scale    = 0,0e+00
[1721759780] llm_load_print_meta: n_ff             = 14336
[1721759780] llm_load_print_meta: n_expert         = 0
[1721759780] llm_load_print_meta: n_expert_used    = 0
[1721759780] llm_load_print_meta: causal attn      = 1
[1721759780] llm_load_print_meta: pooling type     = 0
[1721759780] llm_load_print_meta: rope type        = 0
[1721759780] llm_load_print_meta: rope scaling     = linear
[1721759780] llm_load_print_meta: freq_base_train  = 1000000,0
[1721759780] llm_load_print_meta: freq_scale_train = 1
[1721759780] llm_load_print_meta: n_ctx_orig_yarn  = 1024000
[1721759780] llm_load_print_meta: rope_finetuned   = unknown
[1721759780] llm_load_print_meta: ssm_d_conv       = 0
[1721759780] llm_load_print_meta: ssm_d_inner      = 0
[1721759780] llm_load_print_meta: ssm_d_state      = 0
[1721759780] llm_load_print_meta: ssm_dt_rank      = 0
[1721759780] llm_load_print_meta: model type       = 13B
[1721759780] llm_load_print_meta: model ftype      = Q5_K - Medium
[1721759780] llm_load_print_meta: model params     = 12,25 B
[1721759780] llm_load_print_meta: model size       = 8,12 GiB (5,70 BPW) 
[1721759780] llm_load_print_meta: general.name     = Mistral Nemo Instruct 2407
[1721759780] llm_load_print_meta: BOS token        = 1 '<s>'
[1721759780] llm_load_print_meta: EOS token        = 2 '</s>'
[1721759780] llm_load_print_meta: UNK token        = 0 '<unk>'
[1721759780] llm_load_print_meta: LF token         = 1196 'Ã'
[1721759780] llm_load_print_meta: max token length = 150
[1721759780] ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
[1721759780] ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
[1721759780] ggml_cuda_init: found 1 ROCm devices:
[1721759780]   Device 0: AMD Radeon RX 6700 XT, compute capability 10.3, VMM: no
[1721759780] llm_load_tensors: ggml ctx size =    0,34 MiB
[1721759780] llm_load_tensors: offloading 40 repeating layers to GPU
[1721759780] llm_load_tensors: offloading non-repeating layers to GPU
[1721759780] llm_load_tensors: offloaded 41/41 layers to GPU
[1721759780] llm_load_tensors:      ROCm0 buffer size =  7875,80 MiB
[1721759780] llm_load_tensors:        CPU buffer size =   440,00 MiB
[1721759780] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] .[1721759781] 
[1721759781] llama_new_context_with_model: n_ctx      = 8192
[1721759781] llama_new_context_with_model: n_batch    = 2048
[1721759781] llama_new_context_with_model: n_ubatch   = 512
[1721759781] llama_new_context_with_model: flash_attn = 0
[1721759781] llama_new_context_with_model: freq_base  = 1000000,0
[1721759781] llama_new_context_with_model: freq_scale = 1
[1721759781] llama_kv_cache_init:      ROCm0 KV buffer size =  1280,00 MiB
[1721759781] llama_new_context_with_model: KV self size  = 1280,00 MiB, K (f16):  640,00 MiB, V (f16):  640,00 MiB
[1721759781] llama_new_context_with_model:  ROCm_Host  output buffer size =     0,50 MiB
[1721759781] llama_new_context_with_model:      ROCm0 compute buffer size =   564,00 MiB
[1721759781] llama_new_context_with_model:  ROCm_Host compute buffer size =    26,01 MiB
[1721759781] llama_new_context_with_model: graph nodes  = 1286
[1721759781] llama_new_context_with_model: graph splits = 2
[1721759781] warming up the model with an empty run
[1721759781] n_ctx: 8192
[1721759781] main: chat template example: [INST] You are a helpful assistant
Hello [/INST]Hi there</s>[INST] How are you? [/INST]
[1721759781] 
[1721759781] system_info: n_threads = 6 / 12 | AVX = 1 | AVX_VNNI = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | 
[1721759781] add_bos: 1
[1721759781] tokenize the prompt
[1721759781] prompt: "You are a helpful assistant
"
[1721759781] tokens: [ '<s>':1, 'You':4568, ' are':1584, ' a':1261, ' helpful':20351, ' assistant':27089, '':1010 ]
[1721759781] recalculate the cached logits (check): embd_inp.empty() false, n_matching_session_tokens 0, embd_inp.size() 7, session_tokens.size() 0, embd_inp.size() 7
[1721759781] main: interactive mode on.
[1721759781] sampling: 
	repeat_last_n = 64, repeat_penalty = 1,000, frequency_penalty = 0,000, presence_penalty = 0,000
	top_k = 40, tfs_z = 1,000, top_p = 0,950, min_p = 0,050, typical_p = 1,000, temp = 0,300
	mirostat = 0, mirostat_lr = 0,100, mirostat_ent = 5,000
[1721759781] sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temperature 
[1721759781] generate: n_ctx = 8192, n_batch = 2048, n_predict = -1, n_keep = 1
[1721759781] 

[1721759781] == Running in interactive mode. ==
[1721759781]  - Press Ctrl+C to interject at any time.
[1721759781]  - Press Return to return control to the AI.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

[1721759781] embd_inp.size(): 7, n_consumed: 0
[1721759781] eval: [ '<s>':1, 'You':4568, ' are':1584, ' a':1261, ' helpful':20351, ' assistant':27089, '':1010 ]
[1721759781] n_past = 7
[1721759781] embd_inp.size(): 7, n_consumed: 7
[1721759781] waiting for user input
[1721759783] buffer: 'Hello
'
[1721759783] input tokens: [ '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4 ]
[1721759783] n_remain: -6
[1721759783] embd_inp.size(): 12, n_consumed: 7
[1721759783] eval: [ '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4 ]
[1721759783] n_past = 12
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177 ]
[1721759783] n_remain: -7
[1721759783] eval: [ 'Hello':22177 ]
[1721759783] n_past = 13
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033 ]
[1721759783] n_remain: -8
[1721759783] eval: [ '!':1033 ]
[1721759783] n_past = 14
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075 ]
[1721759783] n_remain: -9
[1721759783] eval: [ ' How':3075 ]
[1721759783] n_past = 15
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710 ]
[1721759783] n_remain: -10
[1721759783] eval: [ ' can':1710 ]
[1721759783] n_past = 16
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362 ]
[1721759783] n_remain: -11
[1721759783] eval: [ ' I':1362 ]
[1721759783] n_past = 17
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410 ]
[1721759783] n_remain: -12
[1721759783] eval: [ ' assist':10410 ]
[1721759783] n_past = 18
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636 ]
[1721759783] n_remain: -13
[1721759783] eval: [ ' you':1636 ]
[1721759783] n_past = 19
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406 ]
[1721759783] n_remain: -14
[1721759783] eval: [ ' today':9406 ]
[1721759783] n_past = 20
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063 ]
[1721759783] n_remain: -15
[1721759783] eval: [ '?':1063 ]
[1721759783] n_past = 21
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246 ]
[1721759783] n_remain: -16
[1721759783] eval: [ ' Let':9246 ]
[1721759783] n_past = 22
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639 ]
[1721759783] n_remain: -17
[1721759783] eval: [ ' me':1639 ]
[1721759783] n_past = 23
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840 ]
[1721759783] n_remain: -18
[1721759783] eval: [ ' know':2840 ]
[1721759783] n_past = 24
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693 ]
[1721759783] n_remain: -19
[1721759783] eval: [ ' if':1693 ]
[1721759783] n_past = 25
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636 ]
[1721759783] n_remain: -20
[1721759783] eval: [ ' you':1636 ]
[1721759783] n_past = 26
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736 ]
[1721759783] n_remain: -21
[1721759783] eval: [ ' have':1736 ]
[1721759783] n_past = 27
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258 ]
[1721759783] n_remain: -22
[1721759783] eval: [ ' any':2258 ]
[1721759783] n_past = 28
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352 ]
[1721759783] n_remain: -23
[1721759783] eval: [ ' questions':8352 ]
[1721759783] n_past = 29
[1721759783] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044 ]
[1721759783] n_remain: -24
[1721759783] eval: [ ',':1044 ]
[1721759783] n_past = 30
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534 ]
[1721759784] n_remain: -25
[1721759784] eval: [ ' need':2534 ]
[1721759784] n_past = 31
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508 ]
[1721759784] n_remain: -26
[1721759784] eval: [ ' help':3508 ]
[1721759784] n_past = 32
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454 ]
[1721759784] n_remain: -27
[1721759784] eval: [ ' with':1454 ]
[1721759784] n_past = 33
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261 ]
[1721759784] n_remain: -28
[1721759784] eval: [ ' a':1261 ]
[1721759784] n_past = 34
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255 ]
[1721759784] n_remain: -29
[1721759784] eval: [ ' task':6255 ]
[1721759784] n_past = 35
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044 ]
[1721759784] n_remain: -30
[1721759784] eval: [ ',':1044 ]
[1721759784] n_past = 36
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505 ]
[1721759784] n_remain: -31
[1721759784] eval: [ ' or':1505 ]
[1721759784] n_past = 37
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586 ]
[1721759784] n_remain: -32
[1721759784] eval: [ ' just':2586 ]
[1721759784] n_past = 38
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933 ]
[1721759784] n_remain: -33
[1721759784] eval: [ ' want':2933 ]
[1721759784] n_past = 39
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317 ]
[1721759784] n_remain: -34
[1721759784] eval: [ ' to':1317 ]
[1721759784] n_past = 40
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666 ]
[1721759784] n_remain: -35
[1721759784] eval: [ ' chat':21666 ]
[1721759784] n_past = 41
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046 ]
[1721759784] n_remain: -36
[1721759784] eval: [ '.':1046 ]
[1721759784] n_past = 42
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046, ' I':1362 ]
[1721759784] n_remain: -37
[1721759784] eval: [ ' I':1362 ]
[1721759784] n_past = 43
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046, ' I':1362, ''m':4525 ]
[1721759784] n_remain: -38
[1721759784] eval: [ ''m':4525 ]
[1721759784] n_past = 44
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046, ' I':1362, ''m':4525, ' here':3226 ]
[1721759784] n_remain: -39
[1721759784] eval: [ ' here':3226 ]
[1721759784] n_past = 45
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046, ' I':1362, ''m':4525, ' here':3226, ' to':1317 ]
[1721759784] n_remain: -40
[1721759784] eval: [ ' to':1317 ]
[1721759784] n_past = 46
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046, ' I':1362, ''m':4525, ' here':3226, ' to':1317, ' help':3508 ]
[1721759784] n_remain: -41
[1721759784] eval: [ ' help':3508 ]
[1721759784] n_past = 47
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046, ' I':1362, ''m':4525, ' here':3226, ' to':1317, ' help':3508, '!':1033 ]
[1721759784] n_remain: -42
[1721759784] eval: [ '!':1033 ]
[1721759784] n_past = 48
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046, ' I':1362, ''m':4525, ' here':3226, ' to':1317, ' help':3508, '!':1033, ' ':119685 ]
[1721759784] n_remain: -43
[1721759784] eval: [ ' ':119685 ]
[1721759784] n_past = 49
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046, ' I':1362, ''m':4525, ' here':3226, ' to':1317, ' help':3508, '!':1033, ' ':119685, '':1152 ]
[1721759784] n_remain: -44
[1721759784] eval: [ '':1152 ]
[1721759784] n_past = 50
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046, ' I':1362, ''m':4525, ' here':3226, ' to':1317, ' help':3508, '!':1033, ' ':119685, '':1152, '':1138 ]
[1721759784] n_remain: -45
[1721759784] eval: [ '':1138 ]
[1721759784] n_past = 51
[1721759784] last: [ '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '<unk>':0, '':1010, 'Hello':22177, '':1010, ' ':1032, '[/INST]':4, 'Hello':22177, '!':1033, ' How':3075, ' can':1710, ' I':1362, ' assist':10410, ' you':1636, ' today':9406, '?':1063, ' Let':9246, ' me':1639, ' know':2840, ' if':1693, ' you':1636, ' have':1736, ' any':2258, ' questions':8352, ',':1044, ' need':2534, ' help':3508, ' with':1454, ' a':1261, ' task':6255, ',':1044, ' or':1505, ' just':2586, ' want':2933, ' to':1317, ' chat':21666, '.':1046, ' I':1362, ''m':4525, ' here':3226, ' to':1317, ' help':3508, '!':1033, ' ':119685, '':1152, '':1138, '</s>':2 ]
[1721759784] n_remain: -46
[1721759784] found an EOG token
[1721759784] waiting for user input
[1721759786] 
[1721759786] llama_print_timings:        load time =    1624,86 ms
[1721759786] llama_print_timings:      sample time =       3,52 ms /    40 runs   (    0,09 ms per token, 11370,10 tokens per second)
[1721759786] llama_print_timings: prompt eval time =    1789,05 ms /    12 tokens (  149,09 ms per token,     6,71 tokens per second)
[1721759786] llama_print_timings:        eval time =    1214,88 ms /    39 runs   (   31,15 ms per token,    32,10 tokens per second)
[1721759786] llama_print_timings:       total time =    4412,46 ms /    51 tokens
```

### PR DESCRIPTION
**Pull request by ngxson**
Resolve #8655

Fix `llama_chat_format_single` incorrectly format system message.

Also added some logs and test cases for this.

The output with this PR:

```
[1721763727] formatted: [INST] You are an assistant

[1721763727] tokenize the prompt
[1721763727] prompt: "[INST] You are an assistant
"
[1721763727] tokens: [ '<s>':1, '[INST]':3, ' You':3213, ' are':1584, ' an':1420, ' assistant':27089, '':1010 ]

...

[1721763730] buffer: 'hello
'
[1721763730] formatted: 
hello
 [/INST]
[1721763730] input tokens: [ '':1010, 'hello':29706, '':1010, ' ':1032, '[/INST]':4 ]
```

---

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Review by HanClinto — APPROVED** [review]
Looks good to me!

The added test is very good. Without the fix applied, I can confirm that the problem is exhibited (and the test fails), and then after applying the fix, the test passes, and behavior seems to match what's expected.

Can't ask for more than that! Nice fix! :)

File: tests/test-chat-template.cpp [hunk 1]
```diff
@@ -137,9 +137,25 @@ int main(void) {
...
+        return output;
+    };
+    assert(fmt_sys("chatml") == "<|im_start|>system\nYou are a helpful assistant<|im_end|>\n");
+    assert(fmt_sys("llama2") == "[INST] You are a helpful assistant\n");
+    assert(fmt_sys("gemma")  == ""); // for gemma, system message is merged with user message
+    assert(fmt_sys("llama3") == "<|start_header_id|>system<|end_header_id|>\n\nYou are a helpful assistant<|eot_id|>");
+
+
+    // test llama_chat_format_single for user message
+    std::cout << "\n\n=== llama_chat_format_single (user message) ===\n\n";
```
Comment (ggerganov) [inline tests/test-chat-template.cpp:158]: nit : prefer `printf` over `std::cout`, mainly for consistency with the rest of the code

**Review by ggerganov — APPROVED** [review]

File: tests/test-chat-template.cpp (hunk 1 above)
Comment (ngxson) [reply tests/test-chat-template.cpp]: Yup that makes sense, I changed to `printf` : https://github.com/ggerganov/llama.cpp/pull/8657/commits/20f56a02db44f94c701a6a8fb30c056b7ed2f3a4

Will merge after CI pass
