### PR TITLE
models : fix YaRN regression + consolidate logic

### LINKED ISSUE #18004: Eval bug: gpt-oss20b strange behaviour
### Name and Version

I've used several versions from b7296 to b7380

### Operating systems

Mac

### GGML backends

Metal

### Hardware

M1 Max, M4 Max

### Models

gpt-oss20b FP16 

### Problem description & steps to reproduce

I have a task that I use to test models with, it's a simple tool use "see three functions implementations in file 1, update them to use security measures implemented in file and add them to file2". usuall success rate for gpt-oss20b was always 100% or very close.

I've noticed performance in this task has significantly degraded yesterday. I've started narrowing down specific llama.cpp buils and it looks like it broke around b7371.

Image

You can see that 7350, 7363 and 7370 made proper code inserts without bugs. 7380 can't insert correct code. 
And I was not able to get any inserts from 7371 at all, it's like model is partially blind and barely "sees" the code. Sometimes it just claims code is already there and ends. Sometimes it keeps using "read file" and "search in file tools" forever. Sometimes it inserts same code several times (after checking if inserts went fine).

Idk how to provide reproducible example because it involves several mcp servers and proprietary code. Hope the data I've provided is enough, because I see 7371 has some breaking changes and the fix will be easy. 

### First Bad Commit

**_I think_** it's release b7371

### Relevant log output

```shell
Logs look absolutely normal, I've ran diff on them and only two strings are different: "ggml_metal_library_init: loaded <time>" and "build: <build>".
```

### PR DESCRIPTION
**Pull request by ggerganov**
cont #17945
fix #18004

In #17945, accidentally broke all models that don't define `rope_yarn_log_mul` (a.k.a. `mscale_all_dims`), such as `gpt-oss`.

### CODE REVIEW

File: src/llama-model.cpp [hunk 1]
```diff
@@ -2294,30 +2294,42 @@ void llama_model::load_hparams(llama_model_loader & ml) {
...
-
-        // [TAG_DEEPSEEK2_YARN_LOG_MUL_FIX]
-        // special-case DEEPSEEK v2:
-        // https://huggingface.co/deepseek-ai/DeepSeek-V2-Lite-Chat/blob/main/config.json#L42-L43
-        if (arch == LLM_ARCH_DEEPSEEK2 && mscale_all_dims != 1.0f) {
-            mscale = mscale_all_dims;
-        }
-
+    // YaRN
+    if (hparams.yarn_ext_factor != 0) {
```
Comment (CISC) [inline src/llama-model.cpp]: Uhm, it defaults to `-1.0f`.

Comment (ggerganov) [reply src/llama-model.cpp]: Thanks. I think the problem was that I was trying to do this logic during model loading. I moved it to context creation now - seems better.

File: src/llama-hparams.cpp [hunk 2]
```diff
@@ -231,13 +231,3 @@ bool llama_hparams::is_masked_swa(uint32_t n_swa, llama_swa_type swa_type, llama
 
     return false;
 }
-
-float llama_hparams::yarn_attn_factor_adjust(float attn_factor, float freq_scale, float ext_factor) {
-    GGML_ASSERT(ext_factor >= 0.0f);
-
-    if (ext_factor != 0.0f) {
-        attn_factor *= 1.0f / (1.0f + 0.1f * logf(1.0f / freq_scale));
```
Comment (CISC) [inline src/llama-hparams.cpp:239]: `cmath` include that was added can be removed again.

Comment (CISC) [reply src/llama-hparams.cpp:239]: Need to add it to `llama-context.cpp` though. :)

**Review by CISC — APPROVED** [review]
