### PR TITLE
server: fix crash when batch > ubatch with embeddings (#12836)

### LINKED ISSUE #12836: server : crash when -b > -ub with embeddings
> @ggerganov Ok, I did few tests and apparently there's an issue that is subject to a separate issue.
> 
> Using the following command:
> ```
> llama-server ... -ub 4096 -b 4096 -c 4096 -np 4
> ```
> 
> Everything works pretty much as expected. Amount of tokens that a task slot can handle appears to be `ub / np`. So in this example, each slot gets a 1024 tokens window. This does seem to give a nice boost depending on the embeddings chunking strategy (my current embeddings are up to 1024 tokens), but I haven't measured precisely yet.
> 
> However, using the following command:
> ```
> llama-server ... -ub 1024 -b 4096 -c 4096 -np 4
> ```
> 
> The server crashes with `GGML_ASSERT((cparams.causal_attn || cparams.n_ubatch >= n_tokens_all) && "non-causal attention requires n_ubatch >= n_tokens") failed` as soon as it receives the next batch of tasks:
> 
> ```
> ggml_vulkan: Found 1 Vulkan devices:
> ggml_vulkan: 0 = AMD Radeon RX 6600M (AMD proprietary driver) | uma: 0 | fp16: 1 | warp size: 32 | shared memory: 32768 | int dot: 1 | matrix cores: none
> build: 5080 (997b1b42) with MSVC 19.38.33134.0 for x64
> system info: n_threads = 8, n_threads_batch = 8, total_threads = 16
> 
> system_info: n_threads = 8 (n_threads_batch = 8) / 16 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | OPENMP = 1 | AARCH64_REPACK = 1 |
> 
> main: binding port with default address family
> main: HTTP server is listening, hostname: 192.168.0.2, port: 8080, http threads: 15
> main: loading model
> srv    load_model: loading model 'C:\Temp\snowflake-arctic-embed-l-v2.0-q8_0.gguf'
> llama_model_load_from_file_impl: using device Vulkan0 (AMD Radeon RX 6600M) - 8176 MiB free
> llama_model_loader: loaded meta data with 36 key-value pairs and 389 tensors from C:\Temp\snowflake-arctic-embed-l-v2.0-q8_0.gguf (version GGUF V3 (latest))
> llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
> llama_model_loader: - kv   0:                       general.architecture str              = bert
> llama_model_loader: - kv   1:                               general.type str              = model
> llama_model_loader: - kv   2:                               general.name str              = Snowflake Arctic Embed L v2.0
> llama_model_loader: - kv   3:                            general.version str              = v2.0
> llama_model_loader: - kv   4:                           general.basename str              = snowflake-arctic-embed-l
> llama_model_loader: - kv   5:                         general.size_label str              = 567M
> llama_model_loader: - kv   6:                            general.license str              = apache-2.0
> llama_model_loader: - kv   7:                               general.tags arr[str,8]       = ["sentence-transformers", "feature-ex...
> llama_model_loader: - kv   8:                          general.languages arr[str,74]      = ["af", "ar", "az", "be", "bg", "bn", ...
> llama_model_loader: - kv   9:                           bert.block_count u32              = 24
> llama_model_loader: - kv  10:                        bert.context_length u32              = 8192
> llama_model_loader: - kv  11:                      bert.embedding_length u32              = 1024
> llama_model_loader: - kv  12:                   bert.feed_forward_length u32              = 4096
> llama_model_loader: - kv  13:                  bert.attention.head_count u32              = 16
> llama_model_loader: - kv  14:          bert.attention.layer_norm_epsilon f32              = 0.000010
> llama_model_loader: - kv  15:                          general.file_type u32              = 7
> llama_model_loader: - kv  16:                      bert.attention.causal bool             = false
> llama_model_loader: - kv  17:                          bert.pooling_type u32              = 2
> llama_model_loader: - kv  18:                       tokenizer.ggml.model str              = t5
> llama_model_loader: - kv  19:                         tokenizer.ggml.pre str              = default
> llama_model_loader: - kv  20:                      tokenizer.ggml.tokens arr[str,250002]  = ["<s>", "<pad>", "</s>", "<unk>", ","...
> llama_model_loader: - kv  21:                      tokenizer.ggml.scores arr[f32,250002]  = [0.000000, 0.000000, 0.000000, 0.0000...
> llama_model_loader: - kv  22:                  tokenizer.ggml.token_type arr[i32,250002]  = [3, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, ...
> llama_model_loader: - kv  23:            tokenizer.ggml.add_space_prefix bool             = true
> llama_model_loader: - kv  24:            tokenizer.ggml.token_type_count u32              = 1
> llama_model_loader: - kv  25:    tokenizer.ggml.remove_extra_whitespaces bool             = true
> llama_model_loader: - kv  26:        tokenizer.ggml.precompiled_charsmap arr[u8,237539]   = [0, 180, 2, 0, 0, 132, 0, 0, 0, 0, 0,...
> llama_model_loader: - kv  27:                tokenizer.ggml.bos_token_id u32              = 0
> llama_model_loader: - kv  28:                tokenizer.ggml.eos_token_id u32              = 2
> llama_model_loader: - kv  29:            tokenizer.ggml.unknown_token_id u32              = 3
> llama_model_loader: - kv  30:          tokenizer.ggml.seperator_token_id u32              = 2
> llama_model_loader: - kv  31:            tokenizer.ggml.padding_token_id u32              = 1
> llama_model_loader: - kv  32:               tokenizer.ggml.mask_token_id u32              = 250001
> llama_model_loader: - kv  33:               tokenizer.ggml.add_bos_token bool             = true
> llama_model_loader: - kv  34:               tokenizer.ggml.add_eos_token bool             = true
> llama_model_loader: - kv  35:               general.quantization_version u32              = 2
> llama_model_loader: - type  f32:  244 tensors
> llama_model_loader: - type q8_0:  145 tensors
> print_info: file format = GGUF V3 (latest)
> print_info: file type   = Q8_0
> print_info: file size   = 598.63 MiB (8.86 BPW)
> load: model vocab missing newline token, using special_pad_id instead
> load: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
> load: special tokens cache size = 4
> load: token to piece cache size = 2.1668 MB
> print_info: arch             = bert
> print_info: vocab_only       = 0
> print_info: n_ctx_train      = 8192
> print_info: n_embd           = 1024
> print_info: n_layer          = 24
> print_info: n_head           = 16
> print_info: n_head_kv        = 16
> print_info: n_rot            = 64
> print_info: n_swa            = 0
> print_info: n_swa_pattern    = 1
> print_info: n_embd_head_k    = 64
> print_info: n_embd_head_v    = 64
> print_info: n_gqa            = 1
> print_info: n_embd_k_gqa     = 1024
> print_info: n_embd_v_gqa     = 1024
> print_info: f_norm_eps       = 1.0e-05
> print_info: f_norm_rms_eps   = 0.0e+00
> print_info: f_clamp_kqv      = 0.0e+00
> print_info: f_max_alibi_bias = 0.0e+00
> print_info: f_logit_scale    = 0.0e+00
> print_info: f_attn_scale     = 0.0e+00
> print_info: n_ff             = 4096
> print_info: n_expert         = 0
> print_info: n_expert_used    = 0
> print_info: causal attn      = 0
> print_info: pooling type     = 2
> print_info: rope type        = 2
> print_info: rope scaling     = linear
> print_info: freq_base_train  = 10000.0
> print_info: freq_scale_train = 1
> print_info: n_ctx_orig_yarn  = 8192
> print_info: rope_finetuned   = unknown
> print_info: ssm_d_conv       = 0
> print_info: ssm_d_inner      = 0
> print_info: ssm_d_state      = 0
> print_info: ssm_dt_rank      = 0
> print_info: ssm_dt_b_c_rms   = 0
> print_info: model type       = 335M
> print_info: model params     = 566.70 M
> print_info: general.name     = Snowflake Arctic Embed L v2.0
> print_info: vocab type       = UGM
> print_info: n_vocab          = 250002
> print_info: n_merges         = 0
> print_info: BOS token        = 0 '<s>'
> print_info: EOS token        = 2 '</s>'
> print_info: UNK token        = 3 '<unk>'
> print_info: SEP token        = 2 '</s>'
> print_info: PAD token        = 1 '<pad>'
> print_info: MASK token       = 250001 '[PAD250000]'
> print_info: LF token         = 0 '<s>'
> print_info: EOG token        = 2 '</s>'
> print_info: max token length = 48
> load_tensors: loading model tensors, this can take a while... (mmap = true)
> load_tensors: offloading 24 repeating layers to GPU
> load_tensors: offloading output layer to GPU
> load_tensors: offloaded 25/25 layers to GPU
> load_tensors:      Vulkan0 model buffer size =   307.22 MiB
> load_tensors:   CPU_Mapped model buffer size =   291.41 MiB
> ......................................................
> llama_context: constructing llama_context
> llama_context: n_seq_max     = 3
> llama_context: n_ctx         = 4096
> llama_context: n_ctx_per_seq = 1365
> llama_context: n_batch       = 4096
> llama_context: n_ubatch      = 1024
> llama_context: causal_attn   = 0
> llama_context: flash_attn    = 0
> llama_context: freq_base     = 10000.0
> llama_context: freq_scale    = 1
> llama_context: n_ctx_per_seq (1365) < n_ctx_train (8192) -- the full capacity of the model will not be utilized
> llama_context: Vulkan_Host  output buffer size =     0.00 MiB
> init: kv_size = 4096, offload = 1, type_k = 'f16', type_v = 'f16', n_layer = 24, can_shift = 1
> init:    Vulkan0 KV buffer size =   384.00 MiB
> llama_context: KV self size  =  384.00 MiB, K (f16):  192.00 MiB, V (f16):  192.00 MiB
> llama_context:    Vulkan0 compute buffer size =    88.01 MiB
> llama_context: Vulkan_Host compute buffer size =    12.01 MiB
> llama_context: graph nodes  = 825
> llama_context: graph splits = 4 (with bs=1024), 2 (with bs=1)
> common_init_from_params: setting dry_penalty_last_n to ctx_size = 4096
> common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
> srv          init: initializing slots, n_slots = 3
> slot         init: id  0 | task -1 | new slot n_ctx_slot = 1365
> slot         init: id  1 | task -1 | new slot n_ctx_slot = 1365
> slot         init: id  2 | task -1 | new slot n_ctx_slot = 1365
> main: model loaded
> main: chat template, chat_template: {%- for message in messages -%}
>   {{- '<|im_start|>' + message.role + '
> ' + message.content + '<|im_end|>
> ' -}}
> {%- endfor -%}
> {%- if add_generation_prompt -%}
>   {{- '<|im_start|>assistant
> ' -}}
> {%- endif -%}, example_format: '<|im_start|>system
> You are a helpful assistant<|im_end|>
> <|im_start|>user
> Hello<|im_end|>
> <|im_start|>assistant
> Hi there<|im_end|>
> <|im_start|>user
> How are you?<|im_end|>
> <|im_start|>assistant
> '
> main: server is listening on http://192.168.0.2:8080 - starting the main loop
> srv  update_slots: all slots are idle
> slot launch_slot_: id  0 | task 0 | processing task
> slot update_slots: id  0 | task 0 | new prompt, n_ctx_slot = 1365, n_keep = 0, n_prompt_tokens = 830
> slot update_slots: id  0 | task 0 | kv cache rm [0, end)
> slot update_slots: id  0 | task 0 | prompt processing progress, n_past = 830, n_tokens = 830, progress = 1.000000
> slot update_slots: id  0 | task 0 | prompt done, n_past = 830, n_tokens = 830
> slot      release: id  0 | task 0 | stop processing: n_past = 830, truncated = 0
> slot launch_slot_: id  1 | task 2 | processing task
> slot launch_slot_: id  2 | task 3 | processing task
> slot launch_slot_: id  0 | task 4 | processing task
> slot update_slots: id  0 | task 4 | new prompt, n_ctx_slot = 1365, n_keep = 0, n_prompt_tokens = 255
> srv  log_server_r: request: POST /v1/embeddings 192.168.0.7 200
> slot update_slots: id  0 | task 4 | kv cache rm [0, end)
> slot update_slots: id  0 | task 4 | prompt processing progress, n_past = 255, n_tokens = 255, progress = 1.000000
> slot update_slots: id  0 | task 4 | prompt done, n_past = 255, n_tokens = 255
> slot update_slots: id  1 | task 2 | new prompt, n_ctx_slot = 1365, n_keep = 0, n_prompt_tokens = 852
> slot update_slots: id  1 | task 2 | kv cache rm [0, end)
> slot update_slots: id  1 | task 2 | prompt processing progress, n_past = 852, n_tokens = 1107, progress = 1.000000
> slot update_slots: id  1 | task 2 | prompt done, n_past = 852, n_tokens = 1107
> slot update_slots: id  2 | task 3 | new prompt, n_ctx_slot = 1365, n_keep = 0, n_prompt_tokens = 246
> slot update_slots: id  2 | task 3 | kv cache rm [0, end)
> slot update_slots: id  2 | task 3 | prompt processing progress, n_past = 246, n_tokens = 1353, progress = 1.000000
> slot update_slots: id  2 | task 3 | prompt done, n_past = 246, n_tokens = 1353
> C:\Sources\llama.cpp\src\llama-context.cpp:1220: GGML_ASSERT((cparams.causal_attn || cparams.n_ubatch >= n_tokens_all) && "non-causal attention requires n_ubatch >= n_tokens") failed
> ``` 

 _Originally posted by @deiteris in [#12817](https://github.com/ggml-org/llama.cpp/issues/12817#issuecomment-2787097698)_

### PR DESCRIPTION
**Pull request by yifant-code**
Fixes #12836

## Problem
Server crashes with `GGML_ASSERT` failure when running embeddings with `-b > -ub`:
Embeddings use non-causal attention which requires all tokens in a single ubatch. When `n_batch > n_ubatch`, the server attempts to split processing, triggering the assertion.

## Solution

Add parameter validation in `main()` after `common_params_parse()`:
- Detect when `--embedding` is enabled and `n_batch > n_ubatch`
- Log warnings explaining the auto-correction
- Set `n_batch = n_ubatch` to prevent crash

Follows @ggerganov's suggested approach in #12836.

## Testing

- ✅ Built server with fix
- ✅ Tested with problematic config: `./llama-server -m model.gguf --embedding -b 2048 -ub 512`
- ✅ Confirmed warning logs appear and parameters are auto-corrected
- ✅ Verified server starts successfully (no GGML_ASSERT crash)
- ✅ Tested valid configurations to ensure no false positives

## Note

Supersedes stalled PR #12940 which attempted a runtime fix in the old `examples/server/` location. This implementation validates at startup in `tools/server/` (current location) per maintainer guidance.

### CODE REVIEW

**Comment by aviallon** [comment]
This is quite relevant to me.

**Review by aviallon — APPROVED** [review]

**Comment by yifant-code** [comment]
@ggerganov could you take a look at this PR if you have time? Thanks.

**Review by ggerganov — APPROVED** [review]

**Comment by ggerganov** [comment]
Lets wait for the CI

**Comment by aviallon** [comment]
@ggerganov I believe CI mostly passed.

File: tools/server/server.cpp [hunk 1]
```diff
@@ -73,8 +73,17 @@ int main(int argc, char ** argv, char ** envp) {
...
 
+    // validate batch size for embeddings
+    // embeddings require all tokens to be processed in a single ubatch
+    // see https://github.com/ggml-org/llama.cpp/issues/12836
+    if (params.embedding && params.n_batch > params.n_ubatch) {
+        LOG_WRN("%s: embeddings enabled with n_batch (%d) > n_ubatch (%d)\n", __func__, params.n_batch, params.n_ubatch);
+        LOG_WRN("%s: setting n_batch = n_ubatch = %d to avoid assertion failure\n", __func__, params.n_ubatch);
+        params.n_batch = params.n_ubatch;
+    }
     if (params.n_parallel < 0) {
```
Comment (ggerganov) [inline tools/server/server.cpp:85]:
```suggestion
    }

    if (params.n_parallel < 0) {
```
