### PR TITLE
rpc : fix alloc size logic

### LINKED ISSUE #16657: Eval bug:  Incorrect outputs when running inference in multiple nodes (Mac)
### Name and Version

b6791 and previous

### Operating systems

Mac

### GGML backends

Metal

### Hardware

> 

### Models

Multiple****

### Problem description & steps to reproduce

My setup  has two different nodes:  MacMini M2 Pro +  MacMini M1.  When running inference on multi-node at some point the output starts repeating one token until the end of the context window.  

Only in multi-node inference, no issue in single node. 

Happens with different models.

Using llama-server or llama-cli.  ( + rpc-server )

Bug in all versions starting at 6473.  6471 and previous are fine.

**Examples**

Running in dual-node the result is wrong:

./rpc-server -H 10.1.2.2:50052   (in the second machine)

./llama-cli --model /var/lib/modelostemp/gpt-oss-20b-mxfp4.gguf --temp 1 --top_k 20 --top_p 1.0 --min_p 0 --seed 1234  --jinja  --ctx-size 7000 --no-mmap --rpc 10.1.2.2:50052

```

> tell me about Julio Cesar
<|channel|>analysis<|message|>User says: "tell me about Julio Cesar". This is ambiguous: could refer to historical Julius (Roman) or other person named Julio Cesar e.g., footballer. Usually people ask general about historical. Need to ask clarifying? The instruction: "If you are unsure what user is asking for... ask for clarification." Here unclear: Julio Cesar could be the Emperor? It might also be the Brazilian footballer? Could also be the Spanish singer? Let's see: "Julio César" with accent; many people. In Brazil, famous footballers: Julio Cesar de Souza Júnior (born 1985), Brazilian goalkeeper. There's also "Julio César" the singer? Or "Julio César" in Spanish maybe meaning "Julius Caesar" but spelled Spanish. Likely user wants info about the Roman general Julius Caesar. But the name is spelled Julio with J. In Spanish/Portuguese, Julius Caesar is Julio César. So user might want about Roman. But there is also the footballer. Without clarifying, risk misinterpretation. The instruction: if uncertain, ask for clarification. So I should ask: specify which Julio Cesar.<|end|><|start|>assistant<|channel|>final<|message|>I’m happy to help—but could you specify which Julio César you’re interested in?  
- The Roman general/ statesman (often written “Julius Caesar” in English).  
- The Brazilian football goalkeeper Julio César de Souza Júnior (born 1985).  
- Another public figure named Julio César (e.g., an artist, politician, etc.).

Just let me know which one (or if you’d like information on all of them!) so I can give you the most accurate and useful details.

> the emperor
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
(omitted)
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

main: context full and context shift is disabled => stopping

```

Running on an single node the result is okay:

./llama-cli --model /var/lib/modelostemp/gpt-oss-20b-mxfp4.gguf --temp 1 --top_k 20 --top_p 1.0 --min_p 0 --seed 1234  --jinja  --ctx-size 7000 --no-mmap  --n-cpu-moe 1 

does not show the problem.

Same problem with other models:

./llama-cli --model /var/lib/modelostemp/Qwen3-4B-2507/Qwen3-4B-Instruct-2507-Q8_0.gguf --temp 0 --top_k 20 --top_p 0.95 --seed 12345  --ctx-size 4000 --rpc 10.1.2.2:50052

```
> tell me about Julio Cesar
It seems like you might be referring to **Julio César**, but there are a few notable people with that name. Here are the most prominent ones:

---

### 1. **Julio César (the Roman Emperor)**
This is likely the most historically significant figure named Julio César.

- **Full Name**: Gaius Julius Caesar (commonly known as Julius Caesar)
- **Lived**: 100 BCE – 44 BCE
- **Role**: Roman statesman, general, and dictator
- **Key Facts**:
  - One of the most influential figures in Roman history.
  - Expanded the Roman Republic through military conquests (e.g., Gaul).
  - Introduced major reforms in law, calendar (Julian calendar), and governance.
  - Assassinated in 44 BCE by a group of senators who feared his growing power.
  - His assassination led to the rise of the Roman Empire and eventually Augustus (Octavian).

> Note: The name "Julio César" is a Spanish/Portuguese version of "Julius Caesar".

---

### 2. **Julio César (the boxer)000000000000000000000000000000000
(omitted)
00000000000000000000000000000000000000000000000000000

main: context full and context shift is disabled => stopping
```

./llama-cli --model /var/lib/modelostemp/DeepSeek-R1-0528-Qwen3-8B-Q8_0.gguf --flash_attn on --ctx-size 4000 --rpc 10.1.2.2:50052

```
> tell me about Julio Cesar
<think>
Okay, the user asked "tell me about Julio Cesar". I think they meant Julius Caesar, the famous Roman general and statesman. They probably want a general overview, but I should consider what level of detail they might need.

Let me start by outlining the key points about Julius Caesar. He was a pivotal figure in Roman history, known for his military conquests and political reforms. I need to structure this information clearly but also engagingly. Since the user might be a student or someone with casual interest, I should include both historical significance and interesting anecdotes to keep it captivating.

The user might not just want facts; they could be interested in understanding why Julius Caesar is still relevant today. So, highlighting his lasting legacies like the Julian calendar and his influence on Western literature through "The Brutus" would be useful. Also, his assassination is a major event, so explaining its causes and consequences is necessary.

I should check if the user has any specific interests. Maybe they’re researching for a project or just curious. Either way, providing a well-rounded summary covering his life, achievements, and end is best. Avoiding too much detail unless asked, keeping it concise but informative. 

Including his rise to power, reforms@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

### First Bad Commit

b6473

### Relevant log output

```shell
x
```

### PR DESCRIPTION
**Pull request by ggerganov**
fix #16657
ref https://github.com/ggml-org/llama.cpp/pull/16276#pullrequestreview-3287676108

This fixes the RPC inference when Metal backend is involved.

Testing:

```bash
# server
make -j && ./bin/rpc-server

# cli
make -j && ./bin/llama-cli -m ../models/gemma-3-4b-it/ggml-model-f16.gguf --rpc localhost:50052 -ngl 99 --no-mmap -no-cnv -p "Hello" --top-k 1 -n 32 -fa on
```

TODO:

- [ ] Check performance imapct
- [ ] Cache the responses to avoid extra RPC calls?

### CODE REVIEW

**Comment by ggerganov** [comment]
@jukofyork I think you were doing some experiments with RPC recently - could you check if this change affects significantly the performance in your RPC use cases?

File: ggml/include/ggml-rpc.h
Comment (rgerganov) [inline ggml/include/ggml-rpc.h:10]: let's bump the protocol version as this is a breaking change

File: ggml/src/ggml-metal/ggml-metal-ops.cpp [hunk 1]
```diff
@@ -1036,6 +1036,11 @@ int ggml_metal_op_set_rows(ggml_metal_op_t ctx, int idx) {
 
     nth = std::min(nth, nk0);
 
+    if (nth*nrptg > ggml_metal_pipeline_max_theads_per_threadgroup(pipeline)) {
```
Comment (rgerganov) [inline ggml/src/ggml-metal/ggml-metal-ops.cpp]: is this change related to the PR?

**Review by rgerganov — COMMENTED** [review]
When looking the debug logs at the server side, I believe this change will increase only TTFT and will not affect PP and TG speeds. Do I get this right?

File: ggml/src/ggml-metal/ggml-metal-ops.cpp (hunk 1 above)
Comment (ggerganov) [reply ggml/src/ggml-metal/ggml-metal-ops.cpp]: Removed

**Comment by ggerganov** [comment]
> When looking the debug logs at the server side, I believe this change will increase only TTFT and will not affect PP and TG speeds. Do I get this right?

Hm, maybe that's correct. Likely because of the graph reuse logic. If you disable the graph reuse, do you see more RPC calls?

```bash
LLAMA_GRAPH_REUSE_DISABLE=1 llama-cli ...
```

**Comment by rgerganov** [comment]
> > When looking the debug logs at the server side, I believe this change will increase only TTFT and will not affect PP and TG speeds. Do I get this right?
> 
> Hm, maybe that's correct. Likely because of the graph reuse logic. If you disable the graph reuse, do you see more RPC calls?
> 
> ```shell
> LLAMA_GRAPH_REUSE_DISABLE=1 llama-cli ...
> ```

Yes, disabling graph reuse results into a lot of `RPC_CMD_GET_ALLOC_SIZE` calls for each graph computation

**Comment by ggerganov** [comment]
Great, I didn't realize until now that the graph reuse saves us almost all the extra RPC calls. This maybe makes the need to cache the RPC calls almost redundant as I think this won't have a significant impact on the PP.

**Comment by ggerganov** [comment]
Some benches could be useful to confirm that the performance is not significantly affected. And I think it should be good to merge.

**Comment by jukofyork** [comment]
> @jukofyork I think you were doing some experiments with RPC recently - could you check if this change affects significantly the performance in your RPC use cases?

No problem, but it will likely be Thursday before I can run any tests.

**Comment by slaren** [comment]
I think eventually the proper solution to this and other per-tensor calls such as `init_tensor` will be to batch all the tensors into a single a call. For example, ggml-alloc could be modified to build a list of tensors and obtain all the tensor alloc sizes first, and use that data rather than calling `get_alloc_size` every time. This way, instead of thousands of calls (each with a network roundtrip), it would only require one. The RPC backend could also cache the results so that calls with identical tensors don't require the network at all.

**Comment by ggerganov** [comment]
@jukofyork @eugr Do you want to do some perf tests with this branch before merging to verify there is no significant performance hit?

**Comment by jukofyork** [comment]
> @jukofyork @eugr Do you want to do some perf tests with this branch before merging to verify there is no significant performance hit?

Sorry, I forgot all about this - I'll try and test it this afternoon and report back.

**Comment by jukofyork** [comment]
> @jukofyork @eugr Do you want to do some perf tests with this branch before merging to verify there is no significant performance hit?

Using 3 nodes, each with 2x `A6000` in:

```sh
./llama-bench \
        --rpc "192.168.1.2:50052,192.168.1.3:50052" \
        --model ~/models/gguf/GLM-4.6-Q5_X.gguf \
        --n-gpu-layers 99 \
        --flash-attn 1 \
        --n-prompt 512 \
        --n-gen 128,256,512
```

### Master

| model                          |       size |     params | backend    | ngl | fa |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | --------------: | -------------------: |
| glm4moe 355B.A32B Q6_K         | 230.78 GiB |   356.79 B | CUDA,RPC   |  99 |  1 |           pp512 |        364.66 ± 0.90 |
| glm4moe 355B.A32B Q6_K         | 230.78 GiB |   356.79 B | CUDA,RPC   |  99 |  1 |           tg128 |         22.01 ± 0.01 |
| glm4moe 355B.A32B Q6_K         | 230.78 GiB |   356.79 B | CUDA,RPC   |  99 |  1 |           tg256 |         21.98 ± 0.01 |
| glm4moe 355B.A32B Q6_K         | 230.78 GiB |   356.79 B | CUDA,RPC   |  99 |  1 |           tg512 |         21.69 ± 0.02 |

### PR

| model                          |       size |     params | backend    | ngl | fa |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | --------------: | -------------------: |
| glm4moe 355B.A32B Q6_K         | 230.78 GiB |   356.79 B | CUDA,RPC   |  99 |  1 |           pp512 |        362.57 ± 1.68 |
| glm4moe 355B.A32B Q6_K         | 230.78 GiB |   356.79 B | CUDA,RPC   |  99 |  1 |           tg128 |         21.94 ± 0.01 |
| glm4moe 355B.A32B Q6_K         | 230.78 GiB |   356.79 B | CUDA,RPC   |  99 |  1 |           tg256 |         21.90 ± 0.00 |
| glm4moe 355B.A32B Q6_K         | 230.78 GiB |   356.79 B | CUDA,RPC   |  99 |  1 |           tg512 |         21.47 ± 0.06 |

**Comment by eugr** [comment]
@ggerganov - sorry for the delay, been trying to do some work done :)
Looks like I'm getting significant performance hit on my Sparks:

**Before patch:**

```bash
build/bin/llama-bench -m ~/.cache/llama.cpp/ggml-org_gpt-oss-120b-GGUF_gpt-oss-120b-mxfp4-00001-of-00003.gguf --rpc 192.168.177.12:15001 -fa 1 -d 0,4096,8192,16384,32768 -p 2048 -n 32 -ub 2048 -mmp 0
```

| model                  |      size |   params | backend  |            test |             t/s |
| ---------------------- | --------: | -------: | -------- | --------------: | --------------: |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |          pp2048 | 1745.82 ± 16.02 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |            tg32 |    51.07 ± 0.57 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |  pp2048 @ d4096 | 1600.32 ± 14.38 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |    tg32 @ d4096 |    48.40 ± 0.28 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |  pp2048 @ d8192 | 1465.80 ± 13.11 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |    tg32 @ d8192 |    46.95 ± 1.02 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC | pp2048 @ d16384 | 1237.04 ± 12.66 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |   tg32 @ d16384 |    43.60 ± 0.41 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC | pp2048 @ d32768 |  941.25 ± 10.39 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |   tg32 @ d32768 |    37.17 ± 0.52 |

build: bde188d60 (7275)

Apply patch: 

```bash
curl -L https://patch-diff.githubusercontent.com/raw/ggml-org/llama.cpp/pull/17116.diff | git apply
```

**After patch:**

| model                  |      size |   params | backend  |            test |             t/s |
| ---------------------- | --------: | -------: | -------- | --------------: | --------------: |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |          pp2048 | 1768.18 ± 11.56 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |            tg32 |    47.47 ± 1.31 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |  pp2048 @ d4096 | 1610.21 ± 53.17 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |    tg32 @ d4096 |    44.53 ± 0.97 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |  pp2048 @ d8192 | 1463.13 ± 16.52 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |    tg32 @ d8192 |    43.12 ± 2.64 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC | pp2048 @ d16384 | 1233.73 ± 27.81 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |   tg32 @ d16384 |    41.26 ± 2.38 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC | pp2048 @ d32768 |   928.27 ± 6.69 |
| gpt-oss 120B MXFP4 MoE | 59.02 GiB | 116.83 B | CUDA,RPC |   tg32 @ d32768 |    34.99 ± 1.01 |

build: bde188d60 (7275)

**Comment by ggerganov** [comment]
Hm, that's strange. Btw, the second run seems to have a bit higher uncertainty in the TG numbers. Is it possible that system was somehow occupied during this test?

Either way, I think it's better to merge this change since it fixes RPC support with Metal devices. Optimizations can come later.

**Review by rgerganov — APPROVED** [review]

**Comment by d-shehu** [comment]
Is this confirmed to be working? Still getting seg fault in llama-cli with Metal as an RPC server even when just listing devices. 

[b7347](https://github.com/ggml-org/llama.cpp/releases/tag/b7347)

All other RPCs (x86/Vulkan) work fine. Thanks.
