### PR TITLE
CUDA: fix partial offloading for ne0 % 256 != 0

### LINKED ISSUE #8558: Bug: GLM4 9b produces wrong results with partial offloading
### What happened?

When loading GLM-4-9b-chat (not 1M version) with llama-server it throws a warning
```
WARN [                    main] The chat template that comes with this model is not yet supported, falling back to chatml. This may cause the model to output suboptimal responses | tid="125637217026048" timestamp=1721291386
```

so the output of the model is gibberish

I tried a lot of quantized versions, q8_0, q4 etc. from different guys, but all have the problem.
Also ollama is affected by this bug, infact https://github.com/ollama/ollama/issues/5719 and https://github.com/ollama/ollama/issues/5668

### Name and Version

`./llama-server --version`
```
version: 3412 (3807c3de)
built with cc (GCC) 14.1.1 20240522 for x86_64-pc-linux-gnu
```

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
./llama-server --model ../text-generation-webui-main/models/glm-4-9b-chat-GGUF/glm-4-9b-chat.q8.gguf --ctx-size 2048 -ngl 10
INFO [                    main] build info | tid="125637217026048" timestamp=1721291385 build=3412 commit="3807c3de"
INFO [                    main] system info | tid="125637217026048" timestamp=1721291385 n_threads=8 n_threads_batch=-1 total_threads=16 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | "
llama_model_loader: loaded meta data with 24 key-value pairs and 283 tensors from ../text-generation-webui-main/models/glm-4-9b-chat-GGUF/glm-4-9b-chat.q8.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = chatglm
llama_model_loader: - kv   1:                               general.name str              = glm-4-9b-chat
llama_model_loader: - kv   2:                     chatglm.context_length u32              = 131072
llama_model_loader: - kv   3:                   chatglm.embedding_length u32              = 4096
llama_model_loader: - kv   4:                chatglm.feed_forward_length u32              = 13696
llama_model_loader: - kv   5:                        chatglm.block_count u32              = 40
llama_model_loader: - kv   6:               chatglm.attention.head_count u32              = 32
llama_model_loader: - kv   7:            chatglm.attention.head_count_kv u32              = 2
llama_model_loader: - kv   8:   chatglm.attention.layer_norm_rms_epsilon f32              = 0.000000
llama_model_loader: - kv   9:                          general.file_type u32              = 7
llama_model_loader: - kv  10:               chatglm.rope.dimension_count u32              = 64
llama_model_loader: - kv  11:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  13:                         tokenizer.ggml.pre str              = chatglm-bpe
llama_model_loader: - kv  14:                      tokenizer.ggml.tokens arr[str,151552]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,151552]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  16:                      tokenizer.ggml.merges arr[str,151073]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  17:            tokenizer.ggml.padding_token_id u32              = 151329
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 151329
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 151329
llama_model_loader: - kv  20:                tokenizer.ggml.eot_token_id u32              = 151336
llama_model_loader: - kv  21:            tokenizer.ggml.unknown_token_id u32              = 151329
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = ChatGLM4
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  121 tensors
llama_model_loader: - type  f16:    2 tensors
llama_model_loader: - type q8_0:  160 tensors
llm_load_vocab: special tokens cache size = 223
llm_load_vocab: token to piece cache size = 0.9732 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = chatglm
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 151552
llm_load_print_meta: n_merges         = 151073
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 131072
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 2
llm_load_print_meta: n_rot            = 64
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 16
llm_load_print_meta: n_embd_k_gqa     = 256
llm_load_print_meta: n_embd_v_gqa     = 256
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.6e-07
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 13696
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 131072
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 9B
llm_load_print_meta: model ftype      = Q8_0
llm_load_print_meta: model params     = 9.40 B
llm_load_print_meta: model size       = 10.39 GiB (9.49 BPW) 
llm_load_print_meta: general.name     = glm-4-9b-chat
llm_load_print_meta: BOS token        = 151329 '<|endoftext|>'
llm_load_print_meta: EOS token        = 151329 '<|endoftext|>'
llm_load_print_meta: UNK token        = 151329 '<|endoftext|>'
llm_load_print_meta: PAD token        = 151329 '<|endoftext|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 151336 '<|user|>'
llm_load_print_meta: max token length = 1024
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2060, compute capability 7.5, VMM: yes
llm_load_tensors: ggml ctx size =    0.28 MiB
llm_load_tensors: offloading 10 repeating layers to GPU
llm_load_tensors: offloaded 10/41 layers to GPU
llm_load_tensors:        CPU buffer size = 10636.22 MiB
llm_load_tensors:      CUDA0 buffer size =  2067.05 MiB
..............................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =    60.00 MiB
llama_kv_cache_init:      CUDA0 KV buffer size =    20.00 MiB
llama_new_context_with_model: KV self size  =   80.00 MiB, K (f16):   40.00 MiB, V (f16):   40.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     1.16 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =  1488.00 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    12.01 MiB
llama_new_context_with_model: graph nodes  = 1606
llama_new_context_with_model: graph splits = 274
INFO [                    init] initializing slots | tid="125637217026048" timestamp=1721291386 n_slots=1
INFO [                    init] new slot | tid="125637217026048" timestamp=1721291386 id_slot=0 n_ctx_slot=2048
INFO [                    main] model loaded | tid="125637217026048" timestamp=1721291386
WARN [                    main] The chat template that comes with this model is not yet supported, falling back to chatml. This may cause the model to output suboptimal responses | tid="125637217026048" timestamp=1721291386
INFO [                    main] chat template | tid="125637217026048" timestamp=1721291386 chat_example="<|im_start|>system\nYou are a helpful assistant<|im_end|>\n<|im_start|>user\nHello<|im_end|>\n<|im_start|>assistant\nHi there<|im_end|>\n<|im_start|>user\nHow are you?<|im_end|>\n<|im_start|>assistant\n" built_in=false
INFO [                    main] HTTP server listening | tid="125637217026048" timestamp=1721291386 n_threads_http="15" port="8080" hostname="127.0.0.1"
INFO [            update_slots] all slots are idle | tid="125637217026048" timestamp=1721291386
```

### PR DESCRIPTION
**Pull request by JohannesGaessler**
Fixes https://github.com/ggerganov/llama.cpp/issues/8558 .

The MMVQ and MMQ kernels handle out-of-bounds accesses for `ne00`/`ne10` by padding the last row of `src0` and every column of `src1` to a multiple of `MATRIX_ROW_PADDING`. The padding is memset to 0 so that it has no influence on the result. Crucially *both* paddings have to be memset to 0 because if one of the values were to randomly encode NaN or infinity then the result of a floating point multiplication with 0 is NaN.

MMQ currently works on 256 `ne00`/`ne10` values per iteration. GLM 4 has tensors with `ne00 % 256 == 128`. So for this model the content of the padding is relevant. On master, when using partial offloading the padding is not being zeroed when the data is copied from RAM to VRAM. Therefore, depending on the input parameters, the result can become NaN. This PR adds the missing calls.

There is also another, different issue with `--split-mode row` but so far I have not been able to track it down.

### CODE REVIEW

**Comment by slaren** [comment]
I am not sure that this is completely correct. The padding is already cleared in `init_tensor`. For a tensor allocated in the compute buffer, this should happen before the graph computation, but the problem is that the padding may be overwritten by the previous operations before the tensor is actually used. Clearing the padding in the `set_tensor` function will not work on every case, because the tensor may have been initialized in a different way (eg. from a `ggml_cpy` operation). I think this would work more reliably:
- Add `GGML_BACKEND_BUFFER_USAGE_COMPUTE` to `ggml_backend_buffer_usage`
- Call `ggml_backend_buffer_set_usage` to this type in ggml-alloc so that compute buffers can be reliably identified
- Before computing the mul_mat operation in the CUDA backend, check if `src0->buffer->usage == GGML_BACKEND_BUFFER_USAGE_COMPUTE`, and if so, clear the padding there.

**Comment by JohannesGaessler** [comment]
Thanks for the pointers. I wasn't sure about the correct way to edit `ggml-alloc.c`, I'm setting the property immediately after allocation. Also I am zeroing the memory in `ggml_cuda_op_mul_mat` instead because for `ne2*ne3 > 1` only the last `ne0 x ne1` matrix should be padded.

File: ggml/src/ggml-alloc.c [hunk 1]
```diff
@@ -947,6 +948,7 @@ static bool alloc_tensor_range(struct ggml_context * ctx,
         free(*buffers);
         return false;
     }
+    ggml_backend_buffer_set_usage(buffer, GGML_BACKEND_BUFFER_USAGE_COMPUTE);
```
Comment (slaren) [inline ggml/src/ggml-alloc.c:951]: The other call is good, but this function is part of `ggml_backend_alloc_ctx_tensors_from_buft`, which is used to allocate weights, KV and other static tensors, so it should not be done here.

File: ggml/src/ggml-cuda.cu [hunk 2]
```diff
@@ -1485,6 +1485,12 @@ static void ggml_cuda_op_mul_mat(
             dev[id].src0_dd = dev[id].src0_dd_alloc.alloc(ctx.pool(id), ggml_nbytes(src0));
         }
 
+        if (ne00 % MATRIX_ROW_PADDING != 0 && ggml_backend_buffer_get_usage(src0->buffer) == GGML_BACKEND_BUFFER_USAGE_COMPUTE) {
+            const int64_t nbytes_data    = ggml_row_size(src0->type, (dev[id].row_high - dev[id].row_low)*ne00);
+            const int64_t nbytes_padding = ggml_row_size(src0->type, MATRIX_ROW_PADDING - ne00 % MATRIX_ROW_PADDING);
+            CUDA_CHECK(cudaMemsetAsync(dev[id].src0_dd + nbytes_data , 0, nbytes_padding, stream));
+        }
```
Comment (slaren) [inline ggml/src/ggml-cuda.cu:1493]: I think it would be good to also check if the tensor is a view, and skip clearing the padding in that case, or at least clear it only for the parent tensor. Otherwise, this could end overwritting part of the parent tensor. To do so, you can check `src0->view_src != nullptr`.

**Review by slaren — COMMENTED** [review]
`ggml_backend_cuda_buffer_init_tensor` could also be updated to skip the `cudaMemset` if the tensor is on a compute buffer, it might save a bit of time.

**Comment by slaren** [comment]
> `ggml_backend_cuda_buffer_init_tensor` could also be updated to skip the `cudaMemset` if the tensor is on a compute buffer, it might save a bit of time.

I see that you removed the `cudaMemset` entirely, but I think this still needs to be done for weights & KV, it can only be skipped if the tensor is on a compute buffer.

**Review by slaren — APPROVED** [review]

**Comment by JohannesGaessler** [comment]
Thanks for all the help.
