### PR TITLE
vulkan: Throttle the number of shader compiles during the build step

### LINKED ISSUE #9582: Bug: Vulkan not compile
### What happened?

~/llama.cpp (master)> cmake -B build -DGGML_VULKAN=1
                                  cmake --build build --config Release -j 16
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.46.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- OpenMP found
-- Using llamafile
-- Found Vulkan: /lib/libvulkan.so (found version "1.3.295") found components: glslc glslangValidator
-- Vulkan found
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- x86 detected
-- Configuring done (1.0s)
-- Generating done (0.1s)
-- Build files have been written to: /home/vecna/llama.cpp/build
[  0%] Generating build details from Git
[  1%] Building C object examples/gguf-hash/CMakeFiles/sha256.dir/deps/sha256/sha256.c.o
[  1%] Building CXX object ggml/src/vulkan-shaders/CMakeFiles/vulkan-shaders-gen.dir/vulkan-shaders-gen.cpp.o
[  1%] Building C object examples/gguf-hash/CMakeFiles/sha1.dir/deps/sha1/sha1.c.o
[  2%] Building C object examples/gguf-hash/CMakeFiles/xxhash.dir/deps/xxhash/xxhash.c.o
-- Found Git: /usr/bin/git (found version "2.46.1")
[  3%] Building CXX object common/CMakeFiles/build_info.dir/build-info.cpp.o
[  3%] Built target build_info
In function ‘SHA1Update’,
    inlined from ‘SHA1Final’ at /home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:265:5:
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:219:13: warning: ‘SHA1Transform’ reading 64 bytes from a region of size 0 [-Wstringop-overread]
  219 |             SHA1Transform(context->state, &data[i]);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:219:13: note: referencing argument 2 of type ‘const unsigned char[64]’
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c: In function ‘SHA1Final’:
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:54:6: note: in a call to function ‘SHA1Transform’
   54 | void SHA1Transform(
      |      ^~~~~~~~~~~~~
In function ‘SHA1Update’,
    inlined from ‘SHA1Final’ at /home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:269:9:
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:219:13: warning: ‘SHA1Transform’ reading 64 bytes from a region of size 0 [-Wstringop-overread]
  219 |             SHA1Transform(context->state, &data[i]);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:219:13: note: referencing argument 2 of type ‘const unsigned char[64]’
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c: In function ‘SHA1Final’:
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:54:6: note: in a call to function ‘SHA1Transform’
   54 | void SHA1Transform(
      |      ^~~~~~~~~~~~~
[  3%] Built target sha1
[  3%] Built target sha256
[  3%] Built target xxhash
[  4%] Linking CXX executable ../../../bin/vulkan-shaders-gen
[  4%] Built target vulkan-shaders-gen
[  5%] Generate vulkan shaders
ggml_vulkan: Generating and compiling shaders to SPIR-V
Error executing command for Error executing command for Error executing command for Error executing command for Error executing command for matmul_id_q5_k_f32_aligned_fp32Error executing command for Error executing command for matmul_f16_alignedError executing command for mul_mat_vec_id_q3_k_f32: Failed to create pipes
Error executing command for dequant_q6_k: Failed to create pipes
dequant_iq4_nl: Failed to create pipes
dequant_q2_k: Failed to create pipes
Error executing command for Error executing command for matmul_id_q4_0_f32_fp32: Failed to create pipes
matmul_q4_1_f32_alignedError executing command for mul_mat_vec_q3_k_f32_f32: Error executing command for mul_mat_vec_id_iq4_nl_f32: Failed to create pipes
mul_mat_vec_iq4_nl_f16_f32: Error executing command for Failed to create pipes
: Error executing command for Error executing command for mul_mat_vec_iq4_nl_f32_f32: Failed to create pipes
: Failed to create pipes
matmul_f32_f32mul_mat_vec_id_q6_k_f32: Failed to create pipes
: Failed to create pipesget_rows_iq4_nl: Error executing command for Failed to create pipes
mul_mat_vec_q3_k_f16_f32: Failed to create pipes

Failed to create pipes
: Failed to create pipes
mul_mat_vec_q6_k_f16_f32: Failed to create pipes
Failed to create pipes
[  6%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-quants.c.o
[  9%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-aarch64.c.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml.dir/llamafile/sgemm.cpp.o
[  9%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-backend.c.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-vulkan-shaders.cpp.o
[  9%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml.c.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-vulkan.cpp.o
[  9%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-alloc.c.o
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp: In function ‘void ggml_vk_load_shaders(vk_device&)’:
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1197:89: error: ‘matmul_f32_f32_len’ was not declared in this scope; did you mean ‘matmul_f32_f16_len’?
 1197 |         ggml_vk_create_pipeline(device, device->pipeline_matmul_f32->l, "matmul_f32_l", matmul_f32_f32_len, matmul_f32_f32_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_l, 1);
      |                                                                                         ^~~~~~~~~~~~~~~~~~
      |                                                                                         matmul_f32_f16_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1197:109: error: ‘matmul_f32_f32_data’ was not declared in this scope; did you mean ‘matmul_f32_f16_data’?
 1197 |         ggml_vk_create_pipeline(device, device->pipeline_matmul_f32->l, "matmul_f32_l", matmul_f32_f32_len, matmul_f32_f32_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_l, 1);
      |                                                                                                             ^~~~~~~~~~~~~~~~~~~
      |                                                                                                             matmul_f32_f16_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1214:99: error: ‘matmul_f16_aligned_len’ was not declared in this scope; did you mean ‘matmul_id_f16_aligned_len’?
 1214 |         ggml_vk_create_pipeline(device, device->pipeline_matmul_f16->a_l, "matmul_f16_aligned_l", matmul_f16_aligned_len, matmul_f16_aligned_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_l, l_align);
      |                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                   matmul_id_f16_aligned_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1214:123: error: ‘matmul_f16_aligned_data’ was not declared in this scope; did you mean ‘matmul_id_f16_aligned_data’?
 1214 |         ggml_vk_create_pipeline(device, device->pipeline_matmul_f16->a_l, "matmul_f16_aligned_l", matmul_f16_aligned_len, matmul_f16_aligned_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_l, l_align);
      |                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                           matmul_id_f16_aligned_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1235:129: error: ‘matmul_q4_1_f32_aligned_len’ was not declared in this scope; did you mean ‘matmul_q5_1_f32_aligned_len’?
 1235 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat[GGML_TYPE_Q4_1]->a_l, "matmul_q4_1_f32_aligned_l", matmul_q4_1_f32_aligned_len, matmul_q4_1_f32_aligned_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                 matmul_q5_1_f32_aligned_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1235:158: error: ‘matmul_q4_1_f32_aligned_data’ was not declared in this scope; did you mean ‘matmul_q5_1_f32_aligned_data’?
 1235 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat[GGML_TYPE_Q4_1]->a_l, "matmul_q4_1_f32_aligned_l", matmul_q4_1_f32_aligned_len, matmul_q4_1_f32_aligned_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                              matmul_q5_1_f32_aligned_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1526:125: error: ‘matmul_id_q4_0_f32_fp32_len’ was not declared in this scope; did you mean ‘matmul_id_q8_0_f32_fp32_len’?
 1526 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat_id[GGML_TYPE_Q4_0]->l, "matmul_id_q4_0_f32_l", matmul_id_q4_0_f32_fp32_len, matmul_id_q4_0_f32_fp32_data, "main", 4, sizeof(vk_mat_mat_id_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                             matmul_id_q8_0_f32_fp32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1526:154: error: ‘matmul_id_q4_0_f32_fp32_data’ was not declared in this scope; did you mean ‘matmul_id_q8_0_f32_fp32_data’?
 1526 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat_id[GGML_TYPE_Q4_0]->l, "matmul_id_q4_0_f32_l", matmul_id_q4_0_f32_fp32_len, matmul_id_q4_0_f32_fp32_data, "main", 4, sizeof(vk_mat_mat_id_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                          matmul_id_q8_0_f32_fp32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1585:135: error: ‘matmul_id_q5_k_f32_aligned_fp32_len’ was not declared in this scope; did you mean ‘matmul_id_q6_k_f32_aligned_fp32_len’?
 1585 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat_id[GGML_TYPE_Q5_K]->a_l, "matmul_id_q5_k_f32_aligned_l", matmul_id_q5_k_f32_aligned_fp32_len, matmul_id_q5_k_f32_aligned_fp32_data, "main", 4, sizeof(vk_mat_mat_id_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                       matmul_id_q6_k_f32_aligned_fp32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1585:172: error: ‘matmul_id_q5_k_f32_aligned_fp32_data’ was not declared in this scope; did you mean ‘matmul_id_q6_k_f32_aligned_fp32_data’?
 1585 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat_id[GGML_TYPE_Q5_K]->a_l, "matmul_id_q5_k_f32_aligned_l", matmul_id_q5_k_f32_aligned_fp32_len, matmul_id_q5_k_f32_aligned_fp32_data, "main", 4, sizeof(vk_mat_mat_id_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                            matmul_id_q6_k_f32_aligned_fp32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1613:127: error: ‘mul_mat_vec_q3_k_f32_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_q6_k_f32_f32_len’?
 1613 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f32_f32[GGML_TYPE_Q3_K], "mul_mat_vec_q3_k_f32_f32", mul_mat_vec_q3_k_f32_f32_len, mul_mat_vec_q3_k_f32_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               mul_mat_vec_q6_k_f32_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1613:157: error: ‘mul_mat_vec_q3_k_f32_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_q6_k_f32_f32_data’?
 1613 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f32_f32[GGML_TYPE_Q3_K], "mul_mat_vec_q3_k_f32_f32", mul_mat_vec_q3_k_f32_f32_len, mul_mat_vec_q3_k_f32_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                             mul_mat_vec_q6_k_f32_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1617:131: error: ‘mul_mat_vec_iq4_nl_f32_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_q4_k_f32_f32_len’?
 1617 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f32_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_iq4_nl_f32_f32", mul_mat_vec_iq4_nl_f32_f32_len, mul_mat_vec_iq4_nl_f32_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                   mul_mat_vec_q4_k_f32_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1617:163: error: ‘mul_mat_vec_iq4_nl_f32_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_q4_k_f32_f32_data’?
 1617 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f32_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_iq4_nl_f32_f32", mul_mat_vec_iq4_nl_f32_f32_len, mul_mat_vec_iq4_nl_f32_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                   mul_mat_vec_q4_k_f32_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1627:127: error: ‘mul_mat_vec_q3_k_f16_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_q5_k_f16_f32_len’?
 1627 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_Q3_K], "mul_mat_vec_q3_k_f16_f32", mul_mat_vec_q3_k_f16_f32_len, mul_mat_vec_q3_k_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               mul_mat_vec_q5_k_f16_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1627:157: error: ‘mul_mat_vec_q3_k_f16_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_q5_k_f16_f32_data’?
 1627 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_Q3_K], "mul_mat_vec_q3_k_f16_f32", mul_mat_vec_q3_k_f16_f32_len, mul_mat_vec_q3_k_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                             mul_mat_vec_q5_k_f16_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1630:127: error: ‘mul_mat_vec_q6_k_f16_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_q5_k_f16_f32_len’?
 1630 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_Q6_K], "mul_mat_vec_q6_k_f16_f32", mul_mat_vec_q6_k_f16_f32_len, mul_mat_vec_q6_k_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               mul_mat_vec_q5_k_f16_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1630:157: error: ‘mul_mat_vec_q6_k_f16_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_q5_k_f16_f32_data’?
 1630 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_Q6_K], "mul_mat_vec_q6_k_f16_f32", mul_mat_vec_q6_k_f16_f32_len, mul_mat_vec_q6_k_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                             mul_mat_vec_q5_k_f16_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1631:131: error: ‘mul_mat_vec_iq4_nl_f16_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_q4_k_f16_f32_len’?
 1631 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_iq4_nl_f16_f32", mul_mat_vec_iq4_nl_f16_f32_len, mul_mat_vec_iq4_nl_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                   mul_mat_vec_q4_k_f16_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1631:163: error: ‘mul_mat_vec_iq4_nl_f16_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_q4_k_f16_f32_data’?
 1631 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_iq4_nl_f16_f32", mul_mat_vec_iq4_nl_f16_f32_len, mul_mat_vec_iq4_nl_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                   mul_mat_vec_q4_k_f16_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1641:125: error: ‘mul_mat_vec_id_q3_k_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q5_k_f32_len’?
 1641 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_Q3_K], "mul_mat_vec_id_q3_k_f32", mul_mat_vec_id_q3_k_f32_len, mul_mat_vec_id_q3_k_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                             mul_mat_vec_id_q5_k_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1641:154: error: ‘mul_mat_vec_id_q3_k_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q5_k_f32_data’?
 1641 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_Q3_K], "mul_mat_vec_id_q3_k_f32", mul_mat_vec_id_q3_k_f32_len, mul_mat_vec_id_q3_k_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                          mul_mat_vec_id_q5_k_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1644:125: error: ‘mul_mat_vec_id_q6_k_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q5_k_f32_len’?
 1644 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_Q6_K], "mul_mat_vec_id_q6_k_f32", mul_mat_vec_id_q6_k_f32_len, mul_mat_vec_id_q6_k_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                             mul_mat_vec_id_q5_k_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1644:154: error: ‘mul_mat_vec_id_q6_k_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q5_k_f32_data’?
 1644 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_Q6_K], "mul_mat_vec_id_q6_k_f32", mul_mat_vec_id_q6_k_f32_len, mul_mat_vec_id_q6_k_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                          mul_mat_vec_id_q5_k_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1645:129: error: ‘mul_mat_vec_id_iq4_nl_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q4_k_f32_len’?
 1645 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_id_iq4_nl_f32", mul_mat_vec_id_iq4_nl_f32_len, mul_mat_vec_id_iq4_nl_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                 mul_mat_vec_id_q4_k_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1645:160: error: ‘mul_mat_vec_id_iq4_nl_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q4_k_f32_data’?
 1645 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_id_iq4_nl_f32", mul_mat_vec_id_iq4_nl_f32_len, mul_mat_vec_id_iq4_nl_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                mul_mat_vec_id_q4_k_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1654:95: error: ‘dequant_q2_k_len’ was not declared in this scope; did you mean ‘dequant_q5_k_len’?
 1654 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_Q2_K], "dequant_q2_k", dequant_q2_k_len, dequant_q2_k_data, "main", 2, 5 * sizeof(uint32_t), {256 * 64, 1, 1}, {}, 1);
      |                                                                                               ^~~~~~~~~~~~~~~~
      |                                                                                               dequant_q5_k_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1654:113: error: ‘dequant_q2_k_data’ was not declared in this scope; did you mean ‘dequant_q5_k_data’?
 1654 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_Q2_K], "dequant_q2_k", dequant_q2_k_len, dequant_q2_k_data, "main", 2, 5 * sizeof(uint32_t), {256 * 64, 1, 1}, {}, 1);
      |                                                                                                                 ^~~~~~~~~~~~~~~~~
      |                                                                                                                 dequant_q5_k_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1658:95: error: ‘dequant_q6_k_len’ was not declared in this scope; did you mean ‘dequant_q5_k_len’?
 1658 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_Q6_K], "dequant_q6_k", dequant_q6_k_len, dequant_q6_k_data, "main", 2, 5 * sizeof(uint32_t), {256 * 64, 1, 1}, {}, 1);
      |                                                                                               ^~~~~~~~~~~~~~~~
      |                                                                                               dequant_q5_k_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1658:113: error: ‘dequant_q6_k_data’ was not declared in this scope; did you mean ‘dequant_q5_k_data’?
 1658 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_Q6_K], "dequant_q6_k", dequant_q6_k_len, dequant_q6_k_data, "main", 2, 5 * sizeof(uint32_t), {256 * 64, 1, 1}, {}, 1);
      |                                                                                                                 ^~~~~~~~~~~~~~~~~
      |                                                                                                                 dequant_q5_k_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1659:99: error: ‘dequant_iq4_nl_len’ was not declared in this scope; did you mean ‘dequant_q4_k_len’?
 1659 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_IQ4_NL], "dequant_iq4_nl", dequant_iq4_nl_len, dequant_iq4_nl_data, "main", 2, 5 * sizeof(uint32_t), {256 * 16, 1, 1}, {}, 1);
      |                                                                                                   ^~~~~~~~~~~~~~~~~~
      |                                                                                                   dequant_q4_k_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1659:119: error: ‘dequant_iq4_nl_data’ was not declared in this scope; did you mean ‘dequant_q4_k_data’?
 1659 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_IQ4_NL], "dequant_iq4_nl", dequant_iq4_nl_len, dequant_iq4_nl_data, "main", 2, 5 * sizeof(uint32_t), {256 * 16, 1, 1}, {}, 1);
      |                                                                                                                       ^~~~~~~~~~~~~~~~~~~
      |                                                                                                                       dequant_q4_k_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1669:101: error: ‘get_rows_iq4_nl_len’ was not declared in this scope; did you mean ‘get_rows_q4_1_len’?
 1669 |     ggml_vk_create_pipeline(device, device->pipeline_get_rows[GGML_TYPE_IQ4_NL], "get_rows_iq4_nl", get_rows_iq4_nl_len, get_rows_iq4_nl_data, "main", 3, sizeof(vk_op_binary_push_constants), {1024, 1, 1}, {}, 1);
      |                                                                                                     ^~~~~~~~~~~~~~~~~~~
      |                                                                                                     get_rows_q4_1_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1669:122: error: ‘get_rows_iq4_nl_data’ was not declared in this scope; did you mean ‘get_rows_q4_1_data’?
 1669 |     ggml_vk_create_pipeline(device, device->pipeline_get_rows[GGML_TYPE_IQ4_NL], "get_rows_iq4_nl", get_rows_iq4_nl_len, get_rows_iq4_nl_data, "main", 3, sizeof(vk_op_binary_push_constants), {1024, 1, 1}, {}, 1);
      |                                                                                                                          ^~~~~~~~~~~~~~~~~~~~
      |                                                                                                                          get_rows_q4_1_data
make[2]: *** [ggml/src/CMakeFiles/ggml.dir/build.make:201: ggml/src/CMakeFiles/ggml.dir/ggml-vulkan.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1626: ggml/src/CMakeFiles/ggml.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

### Name and Version

it just don't compile and i don't found a special issue option for it

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
~/llama.cpp (master)> cmake -B build -DGGML_VULKAN=1
                                  cmake --build build --config Release -j 16
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.46.1")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- OpenMP found
-- Using llamafile
-- Found Vulkan: /lib/libvulkan.so (found version "1.3.295") found components: glslc glslangValidator
-- Vulkan found
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- x86 detected
-- Configuring done (1.0s)
-- Generating done (0.1s)
-- Build files have been written to: /home/vecna/llama.cpp/build
[  0%] Generating build details from Git
[  1%] Building C object examples/gguf-hash/CMakeFiles/sha256.dir/deps/sha256/sha256.c.o
[  1%] Building CXX object ggml/src/vulkan-shaders/CMakeFiles/vulkan-shaders-gen.dir/vulkan-shaders-gen.cpp.o
[  1%] Building C object examples/gguf-hash/CMakeFiles/sha1.dir/deps/sha1/sha1.c.o
[  2%] Building C object examples/gguf-hash/CMakeFiles/xxhash.dir/deps/xxhash/xxhash.c.o
-- Found Git: /usr/bin/git (found version "2.46.1")
[  3%] Building CXX object common/CMakeFiles/build_info.dir/build-info.cpp.o
[  3%] Built target build_info
In function ‘SHA1Update’,
    inlined from ‘SHA1Final’ at /home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:265:5:
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:219:13: warning: ‘SHA1Transform’ reading 64 bytes from a region of size 0 [-Wstringop-overread]
  219 |             SHA1Transform(context->state, &data[i]);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:219:13: note: referencing argument 2 of type ‘const unsigned char[64]’
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c: In function ‘SHA1Final’:
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:54:6: note: in a call to function ‘SHA1Transform’
   54 | void SHA1Transform(
      |      ^~~~~~~~~~~~~
In function ‘SHA1Update’,
    inlined from ‘SHA1Final’ at /home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:269:9:
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:219:13: warning: ‘SHA1Transform’ reading 64 bytes from a region of size 0 [-Wstringop-overread]
  219 |             SHA1Transform(context->state, &data[i]);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:219:13: note: referencing argument 2 of type ‘const unsigned char[64]’
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c: In function ‘SHA1Final’:
/home/vecna/llama.cpp/examples/gguf-hash/deps/sha1/sha1.c:54:6: note: in a call to function ‘SHA1Transform’
   54 | void SHA1Transform(
      |      ^~~~~~~~~~~~~
[  3%] Built target sha1
[  3%] Built target sha256
[  3%] Built target xxhash
[  4%] Linking CXX executable ../../../bin/vulkan-shaders-gen
[  4%] Built target vulkan-shaders-gen
[  5%] Generate vulkan shaders
ggml_vulkan: Generating and compiling shaders to SPIR-V
Error executing command for Error executing command for Error executing command for Error executing command for Error executing command for matmul_id_q5_k_f32_aligned_fp32Error executing command for Error executing command for matmul_f16_alignedError executing command for mul_mat_vec_id_q3_k_f32: Failed to create pipes
Error executing command for dequant_q6_k: Failed to create pipes
dequant_iq4_nl: Failed to create pipes
dequant_q2_k: Failed to create pipes
Error executing command for Error executing command for matmul_id_q4_0_f32_fp32: Failed to create pipes
matmul_q4_1_f32_alignedError executing command for mul_mat_vec_q3_k_f32_f32: Error executing command for mul_mat_vec_id_iq4_nl_f32: Failed to create pipes
mul_mat_vec_iq4_nl_f16_f32: Error executing command for Failed to create pipes
: Error executing command for Error executing command for mul_mat_vec_iq4_nl_f32_f32: Failed to create pipes
: Failed to create pipes
matmul_f32_f32mul_mat_vec_id_q6_k_f32: Failed to create pipes
: Failed to create pipesget_rows_iq4_nl: Error executing command for Failed to create pipes
mul_mat_vec_q3_k_f16_f32: Failed to create pipes

Failed to create pipes
: Failed to create pipes
mul_mat_vec_q6_k_f16_f32: Failed to create pipes
Failed to create pipes
[  6%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-quants.c.o
[  9%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-aarch64.c.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml.dir/llamafile/sgemm.cpp.o
[  9%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-backend.c.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-vulkan-shaders.cpp.o
[  9%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml.c.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-vulkan.cpp.o
[  9%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-alloc.c.o
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp: In function ‘void ggml_vk_load_shaders(vk_device&)’:
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1197:89: error: ‘matmul_f32_f32_len’ was not declared in this scope; did you mean ‘matmul_f32_f16_len’?
 1197 |         ggml_vk_create_pipeline(device, device->pipeline_matmul_f32->l, "matmul_f32_l", matmul_f32_f32_len, matmul_f32_f32_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_l, 1);
      |                                                                                         ^~~~~~~~~~~~~~~~~~
      |                                                                                         matmul_f32_f16_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1197:109: error: ‘matmul_f32_f32_data’ was not declared in this scope; did you mean ‘matmul_f32_f16_data’?
 1197 |         ggml_vk_create_pipeline(device, device->pipeline_matmul_f32->l, "matmul_f32_l", matmul_f32_f32_len, matmul_f32_f32_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_l, 1);
      |                                                                                                             ^~~~~~~~~~~~~~~~~~~
      |                                                                                                             matmul_f32_f16_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1214:99: error: ‘matmul_f16_aligned_len’ was not declared in this scope; did you mean ‘matmul_id_f16_aligned_len’?
 1214 |         ggml_vk_create_pipeline(device, device->pipeline_matmul_f16->a_l, "matmul_f16_aligned_l", matmul_f16_aligned_len, matmul_f16_aligned_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_l, l_align);
      |                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                   matmul_id_f16_aligned_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1214:123: error: ‘matmul_f16_aligned_data’ was not declared in this scope; did you mean ‘matmul_id_f16_aligned_data’?
 1214 |         ggml_vk_create_pipeline(device, device->pipeline_matmul_f16->a_l, "matmul_f16_aligned_l", matmul_f16_aligned_len, matmul_f16_aligned_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_l, l_align);
      |                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                           matmul_id_f16_aligned_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1235:129: error: ‘matmul_q4_1_f32_aligned_len’ was not declared in this scope; did you mean ‘matmul_q5_1_f32_aligned_len’?
 1235 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat[GGML_TYPE_Q4_1]->a_l, "matmul_q4_1_f32_aligned_l", matmul_q4_1_f32_aligned_len, matmul_q4_1_f32_aligned_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                 matmul_q5_1_f32_aligned_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1235:158: error: ‘matmul_q4_1_f32_aligned_data’ was not declared in this scope; did you mean ‘matmul_q5_1_f32_aligned_data’?
 1235 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat[GGML_TYPE_Q4_1]->a_l, "matmul_q4_1_f32_aligned_l", matmul_q4_1_f32_aligned_len, matmul_q4_1_f32_aligned_data, "main", 3, sizeof(vk_mat_mat_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                              matmul_q5_1_f32_aligned_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1526:125: error: ‘matmul_id_q4_0_f32_fp32_len’ was not declared in this scope; did you mean ‘matmul_id_q8_0_f32_fp32_len’?
 1526 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat_id[GGML_TYPE_Q4_0]->l, "matmul_id_q4_0_f32_l", matmul_id_q4_0_f32_fp32_len, matmul_id_q4_0_f32_fp32_data, "main", 4, sizeof(vk_mat_mat_id_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                             matmul_id_q8_0_f32_fp32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1526:154: error: ‘matmul_id_q4_0_f32_fp32_data’ was not declared in this scope; did you mean ‘matmul_id_q8_0_f32_fp32_data’?
 1526 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat_id[GGML_TYPE_Q4_0]->l, "matmul_id_q4_0_f32_l", matmul_id_q4_0_f32_fp32_len, matmul_id_q4_0_f32_fp32_data, "main", 4, sizeof(vk_mat_mat_id_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                          matmul_id_q8_0_f32_fp32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1585:135: error: ‘matmul_id_q5_k_f32_aligned_fp32_len’ was not declared in this scope; did you mean ‘matmul_id_q6_k_f32_aligned_fp32_len’?
 1585 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat_id[GGML_TYPE_Q5_K]->a_l, "matmul_id_q5_k_f32_aligned_l", matmul_id_q5_k_f32_aligned_fp32_len, matmul_id_q5_k_f32_aligned_fp32_data, "main", 4, sizeof(vk_mat_mat_id_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                       matmul_id_q6_k_f32_aligned_fp32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1585:172: error: ‘matmul_id_q5_k_f32_aligned_fp32_data’ was not declared in this scope; did you mean ‘matmul_id_q6_k_f32_aligned_fp32_data’?
 1585 |         ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_mat_id[GGML_TYPE_Q5_K]->a_l, "matmul_id_q5_k_f32_aligned_l", matmul_id_q5_k_f32_aligned_fp32_len, matmul_id_q5_k_f32_aligned_fp32_data, "main", 4, sizeof(vk_mat_mat_id_push_constants), l_wg_denoms, warptile_mmq_l, l_align);
      |                                                                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                            matmul_id_q6_k_f32_aligned_fp32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1613:127: error: ‘mul_mat_vec_q3_k_f32_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_q6_k_f32_f32_len’?
 1613 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f32_f32[GGML_TYPE_Q3_K], "mul_mat_vec_q3_k_f32_f32", mul_mat_vec_q3_k_f32_f32_len, mul_mat_vec_q3_k_f32_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               mul_mat_vec_q6_k_f32_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1613:157: error: ‘mul_mat_vec_q3_k_f32_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_q6_k_f32_f32_data’?
 1613 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f32_f32[GGML_TYPE_Q3_K], "mul_mat_vec_q3_k_f32_f32", mul_mat_vec_q3_k_f32_f32_len, mul_mat_vec_q3_k_f32_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                             mul_mat_vec_q6_k_f32_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1617:131: error: ‘mul_mat_vec_iq4_nl_f32_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_q4_k_f32_f32_len’?
 1617 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f32_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_iq4_nl_f32_f32", mul_mat_vec_iq4_nl_f32_f32_len, mul_mat_vec_iq4_nl_f32_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                   mul_mat_vec_q4_k_f32_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1617:163: error: ‘mul_mat_vec_iq4_nl_f32_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_q4_k_f32_f32_data’?
 1617 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f32_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_iq4_nl_f32_f32", mul_mat_vec_iq4_nl_f32_f32_len, mul_mat_vec_iq4_nl_f32_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                   mul_mat_vec_q4_k_f32_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1627:127: error: ‘mul_mat_vec_q3_k_f16_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_q5_k_f16_f32_len’?
 1627 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_Q3_K], "mul_mat_vec_q3_k_f16_f32", mul_mat_vec_q3_k_f16_f32_len, mul_mat_vec_q3_k_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               mul_mat_vec_q5_k_f16_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1627:157: error: ‘mul_mat_vec_q3_k_f16_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_q5_k_f16_f32_data’?
 1627 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_Q3_K], "mul_mat_vec_q3_k_f16_f32", mul_mat_vec_q3_k_f16_f32_len, mul_mat_vec_q3_k_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                             mul_mat_vec_q5_k_f16_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1630:127: error: ‘mul_mat_vec_q6_k_f16_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_q5_k_f16_f32_len’?
 1630 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_Q6_K], "mul_mat_vec_q6_k_f16_f32", mul_mat_vec_q6_k_f16_f32_len, mul_mat_vec_q6_k_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                               mul_mat_vec_q5_k_f16_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1630:157: error: ‘mul_mat_vec_q6_k_f16_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_q5_k_f16_f32_data’?
 1630 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_Q6_K], "mul_mat_vec_q6_k_f16_f32", mul_mat_vec_q6_k_f16_f32_len, mul_mat_vec_q6_k_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                             mul_mat_vec_q5_k_f16_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1631:131: error: ‘mul_mat_vec_iq4_nl_f16_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_q4_k_f16_f32_len’?
 1631 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_iq4_nl_f16_f32", mul_mat_vec_iq4_nl_f16_f32_len, mul_mat_vec_iq4_nl_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                   mul_mat_vec_q4_k_f16_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1631:163: error: ‘mul_mat_vec_iq4_nl_f16_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_q4_k_f16_f32_data’?
 1631 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_f16_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_iq4_nl_f16_f32", mul_mat_vec_iq4_nl_f16_f32_len, mul_mat_vec_iq4_nl_f16_f32_data, "main", 3, sizeof(vk_mat_vec_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                   mul_mat_vec_q4_k_f16_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1641:125: error: ‘mul_mat_vec_id_q3_k_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q5_k_f32_len’?
 1641 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_Q3_K], "mul_mat_vec_id_q3_k_f32", mul_mat_vec_id_q3_k_f32_len, mul_mat_vec_id_q3_k_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                             mul_mat_vec_id_q5_k_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1641:154: error: ‘mul_mat_vec_id_q3_k_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q5_k_f32_data’?
 1641 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_Q3_K], "mul_mat_vec_id_q3_k_f32", mul_mat_vec_id_q3_k_f32_len, mul_mat_vec_id_q3_k_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                          mul_mat_vec_id_q5_k_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1644:125: error: ‘mul_mat_vec_id_q6_k_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q5_k_f32_len’?
 1644 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_Q6_K], "mul_mat_vec_id_q6_k_f32", mul_mat_vec_id_q6_k_f32_len, mul_mat_vec_id_q6_k_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                             mul_mat_vec_id_q5_k_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1644:154: error: ‘mul_mat_vec_id_q6_k_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q5_k_f32_data’?
 1644 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_Q6_K], "mul_mat_vec_id_q6_k_f32", mul_mat_vec_id_q6_k_f32_len, mul_mat_vec_id_q6_k_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                          mul_mat_vec_id_q5_k_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1645:129: error: ‘mul_mat_vec_id_iq4_nl_f32_len’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q4_k_f32_len’?
 1645 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_id_iq4_nl_f32", mul_mat_vec_id_iq4_nl_f32_len, mul_mat_vec_id_iq4_nl_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                 mul_mat_vec_id_q4_k_f32_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1645:160: error: ‘mul_mat_vec_id_iq4_nl_f32_data’ was not declared in this scope; did you mean ‘mul_mat_vec_id_q4_k_f32_data’?
 1645 |     ggml_vk_create_pipeline(device, device->pipeline_dequant_mul_mat_vec_id_f32[GGML_TYPE_IQ4_NL], "mul_mat_vec_id_iq4_nl_f32", mul_mat_vec_id_iq4_nl_f32_len, mul_mat_vec_id_iq4_nl_f32_data, "main", 4, sizeof(vk_mat_vec_id_push_constants), {1, 1, 1}, { device->subgroup_size }, 1);
      |                                                                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                                                mul_mat_vec_id_q4_k_f32_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1654:95: error: ‘dequant_q2_k_len’ was not declared in this scope; did you mean ‘dequant_q5_k_len’?
 1654 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_Q2_K], "dequant_q2_k", dequant_q2_k_len, dequant_q2_k_data, "main", 2, 5 * sizeof(uint32_t), {256 * 64, 1, 1}, {}, 1);
      |                                                                                               ^~~~~~~~~~~~~~~~
      |                                                                                               dequant_q5_k_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1654:113: error: ‘dequant_q2_k_data’ was not declared in this scope; did you mean ‘dequant_q5_k_data’?
 1654 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_Q2_K], "dequant_q2_k", dequant_q2_k_len, dequant_q2_k_data, "main", 2, 5 * sizeof(uint32_t), {256 * 64, 1, 1}, {}, 1);
      |                                                                                                                 ^~~~~~~~~~~~~~~~~
      |                                                                                                                 dequant_q5_k_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1658:95: error: ‘dequant_q6_k_len’ was not declared in this scope; did you mean ‘dequant_q5_k_len’?
 1658 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_Q6_K], "dequant_q6_k", dequant_q6_k_len, dequant_q6_k_data, "main", 2, 5 * sizeof(uint32_t), {256 * 64, 1, 1}, {}, 1);
      |                                                                                               ^~~~~~~~~~~~~~~~
      |                                                                                               dequant_q5_k_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1658:113: error: ‘dequant_q6_k_data’ was not declared in this scope; did you mean ‘dequant_q5_k_data’?
 1658 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_Q6_K], "dequant_q6_k", dequant_q6_k_len, dequant_q6_k_data, "main", 2, 5 * sizeof(uint32_t), {256 * 64, 1, 1}, {}, 1);
      |                                                                                                                 ^~~~~~~~~~~~~~~~~
      |                                                                                                                 dequant_q5_k_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1659:99: error: ‘dequant_iq4_nl_len’ was not declared in this scope; did you mean ‘dequant_q4_k_len’?
 1659 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_IQ4_NL], "dequant_iq4_nl", dequant_iq4_nl_len, dequant_iq4_nl_data, "main", 2, 5 * sizeof(uint32_t), {256 * 16, 1, 1}, {}, 1);
      |                                                                                                   ^~~~~~~~~~~~~~~~~~
      |                                                                                                   dequant_q4_k_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1659:119: error: ‘dequant_iq4_nl_data’ was not declared in this scope; did you mean ‘dequant_q4_k_data’?
 1659 |     ggml_vk_create_pipeline(device, device->pipeline_dequant[GGML_TYPE_IQ4_NL], "dequant_iq4_nl", dequant_iq4_nl_len, dequant_iq4_nl_data, "main", 2, 5 * sizeof(uint32_t), {256 * 16, 1, 1}, {}, 1);
      |                                                                                                                       ^~~~~~~~~~~~~~~~~~~
      |                                                                                                                       dequant_q4_k_data
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1669:101: error: ‘get_rows_iq4_nl_len’ was not declared in this scope; did you mean ‘get_rows_q4_1_len’?
 1669 |     ggml_vk_create_pipeline(device, device->pipeline_get_rows[GGML_TYPE_IQ4_NL], "get_rows_iq4_nl", get_rows_iq4_nl_len, get_rows_iq4_nl_data, "main", 3, sizeof(vk_op_binary_push_constants), {1024, 1, 1}, {}, 1);
      |                                                                                                     ^~~~~~~~~~~~~~~~~~~
      |                                                                                                     get_rows_q4_1_len
/home/vecna/llama.cpp/ggml/src/ggml-vulkan.cpp:1669:122: error: ‘get_rows_iq4_nl_data’ was not declared in this scope; did you mean ‘get_rows_q4_1_data’?
 1669 |     ggml_vk_create_pipeline(device, device->pipeline_get_rows[GGML_TYPE_IQ4_NL], "get_rows_iq4_nl", get_rows_iq4_nl_len, get_rows_iq4_nl_data, "main", 3, sizeof(vk_op_binary_push_constants), {1024, 1, 1}, {}, 1);
      |                                                                                                                          ^~~~~~~~~~~~~~~~~~~~
      |                                                                                                                          get_rows_q4_1_data
make[2]: *** [ggml/src/CMakeFiles/ggml.dir/build.make:201: ggml/src/CMakeFiles/ggml.dir/ggml-vulkan.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1626: ggml/src/CMakeFiles/ggml.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

### PR DESCRIPTION
**Pull request by jeffbolznv**
Fixes #9582

Spawning too many concurrent copies of glslc leads to "Failed to create pipes" errors on Linux. This change applies the same throttling we use for multithreaded pipeline creation.

Split out from https://github.com/ggerganov/llama.cpp/pull/10206.

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

File: ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp [hunk 1]
```diff
@@ -241,7 +253,22 @@ std::map<std::string, std::string> merge_maps(const std::map<std::string, std::s
     return result;
 }
 
-void matmul_shaders(std::vector<std::future<void>>& tasks, bool fp16, bool matmul_id) {
+static std::vector<std::future<void>> compiles;
+void string_to_spv(const std::string& _name, const std::string& in_fname, const std::map<std::string, std::string>& defines, bool fp16 = true) {
+    {
+        // wait until fewer than N compiles are in progress.
+        // 16 is an arbitrary limit, the goal is to avoid "failed to create pipe" errors.
+        uint32_t N = 16;
```
Comment (0cc4m) [inline ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp:261]: Is there a reason not to stick with `uint32_t N = std::max(1u, std::thread::hardware_concurrency());` here, similar to how it's handled for Vulkan shader compiles? 16 might be slower than necessary on systems with more than 16 threads.

**Review by 0cc4m — APPROVED** [review]
