### PR TITLE
imatrix : migrate to gpt_params

### LINKED ISSUE #7765: Bug: Unable to generate imatrix data using imatrix.exe from release 3089
### What happened?

Started having this issue today, assuming after the only recent commit to `imatrix.cpp` (https://github.com/ggerganov/llama.cpp/commit/1442677f92e45a475be7b4d056e3633d1d6f813b#diff-75299e7302c2c05622a58cb4901166fc1e94bcdde981961e55e3d939cbf41825), where using this command:

`.\imatrix.exe -m .\model.gguf -f .\imatrix.txt -ngl 10`

...doesn't work anymore, it doesn't error or anything, imatrix generation just doesn't happen.

Am I missing something that was added to this process over the last three days?

It works as expected (imatrix) in the version I used from 3 days ago, namely **[b3070](https://github.com/ggerganov/llama.cpp/releases/tag/b3070), before this change**, but it could have been another one from the commit - or other changes to build.

### Name and Version
[b3089](https://github.com/ggerganov/llama.cpp/releases/tag/b3089)
[llama-b3089-bin-win-cuda-cu12.2.0-x64](https://github.com/ggerganov/llama.cpp/releases/download/b3089/llama-b3089-bin-win-cuda-cu12.2.0-x64.zip)
imatrix.exe
latest repo commit

### What operating system are you seeing the problem on?

Windows 11 23H2

### Hardware

GTX 1070 Ti 8GB (Pascal) - Drivers 555.85
6C/12T CPU
32GB DDR4 RAM

### PR DESCRIPTION
**Pull request by ggerganov**
ref #7675 
fix #7765

### CODE REVIEW

File: common/common.cpp [hunk 1]
```diff
@@ -1537,6 +1560,46 @@ bool gpt_params_find_arg(int argc, char ** argv, const std::string & arg, gpt_pa
...
+            return true;
+        }
+        params.n_save_freq = std::stoi(argv[i]);
+        return true;
+    }
+    if (arg == "--process-output") {
+        params.process_output = true;
+        return true;
+    }
+    if (arg == "--no-ppl") {
```
Comment (bartowski1182) [inline common/common.cpp:1591]: think this should be flipped shouldn't it? if no-ppl, compute ppl should be false
