### PR TITLE
CANN: fix acl_rstd allocation size in ggml_cann_rms_norm

### LINKED ISSUE #15330: Misc. bug: ggml_cann_rms_norm causes CANN kernel crash when running llama-bench.
### Name and Version

./build/bin/llama-cli --version
version: 6150 (b3e16665)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for aarch64-linux-gnu

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-bench

### Command line

```shell
llama-bench -fa 0 -n 0 -p 512 -r 50 -m {qwen2_based_model} -ngl 99
```

## Description
When running `llama-bench` on Ascend 910B NPU (in autodl container), the CANN kernel crashes in `ggml_cann_rms_norm`. 

**Error code**: 507035. 
**Error message**: EZ9999 The error from device(chipId:1, dieId:0), serial number is 112, there is an aivec error exception, core id is 28...

Error message indicates that it should be a kernel operator crash. After switching between the history commits on ggml-cann, I found that the problem first occurs in https://github.com/ggml-org/llama.cpp/pull/14002, which replaced `ggml_cann_async_memset` with `aclnnInplaceZero` to create zero tensors. 

After debugging, I found that in `ggml_cann_rms_norm`, there might be a memory issue when setting tensor **acl_rstd** to 0. 

```
size_t zero_tensor_n_bytes =
        src->ne[1] * src->ne[2] * src->ne[3] * ggml_element_size(src);
ggml_cann_pool_alloc zero_tensor_allocator(ctx.pool(), zero_tensor_n_bytes);
aclTensor* acl_rstd =
        aclnn_zero(ctx, zero_tensor_allocator.get(), zero_tensor_n_bytes,
                   src->ne, GGML_MAX_DIMS, ggml_cann_type_mapping(src->type),
                   ggml_element_size(src));
```
**acl_rstd** allocs `src->ne[1] * src->ne[2] * src->ne[3] * ggml_element_size(src)` size buffer, but has `{src->ne[0], src->ne[1], src->ne[2], src->ne[3]}` in shape. I suppose it cause the kernel to crash. 

## Steps to Reproduce
pp512 test for example
```
cmake -B build -DCMAKE_BUILD_TYPE=Debug -DGGML_CANN=ON 
cmake --build build --config Debug
./build/bin/llama-bench -fa 0 -n 0 -p 512 -r 50 -m (your qwen2 model path) -ngl 99
```

## Others
I found `llama-cli` and `test-backend-ops` seems not affected by this issue.

### First Bad Commit

[#14002](https://github.com/ggml-org/llama.cpp/pull/14002)

### Relevant log output

```shell
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
0x0000ffffb04a6800 in __GI___wait4 (pid=<optimized out>, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x0000ffffb04a6800 in __GI___wait4 (pid=<optimized out>, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x0000ffffb08f66fc in ggml_print_backtrace () at /root/llama.cpp/ggml/src/ggml.c:196
196             waitpid(child_pid, NULL, 0);
#2  0x0000ffffb08f68d4 in ggml_abort (file=0xffffb0a4ceb0 "/root/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp", line=69, fmt=0xffffb0a4cea0 "CANN error") at /root/llama.cpp/ggml/src/ggml.c:230
230             ggml_print_backtrace();
#3  0x0000ffffb0a2ef94 in ggml_cann_error (stmt=0xffffb0a4e7e0 "aclrtSynchronizeStream(cann_ctx->stream())", func=0xffffb0a4e7c0 "ggml_backend_cann_synchronize", file=0xffffb0a4ceb0 "/root/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp", line=2075, msg=0xaaab114ea528 "EZ9999: Inner Error!\nEZ9999: [PID: 165866] 2025-08-15-03:15:49.571.649 The error from device(chipId:1, dieId:0), serial number is 112, there is an aivec error exception, core id is 28, error code = 0x"...) at /root/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp:69
69          GGML_ABORT("CANN error");
#4  0x0000ffffb0a34e3c in ggml_backend_cann_synchronize (backend=0xaaab0e4994e0) at /root/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp:2075
2075        ACL_CHECK(aclrtSynchronizeStream(cann_ctx->stream()));
#5  0x0000ffffb090f480 in ggml_backend_synchronize (backend=0xaaab0e4994e0) at /root/llama.cpp/ggml/src/ggml-backend.cpp:306
306         backend->iface.synchronize(backend);
#6  0x0000ffffb0913d00 in ggml_backend_sched_synchronize (sched=0xaaab0e4a1860) at /root/llama.cpp/ggml/src/ggml-backend.cpp:1595
1595            ggml_backend_synchronize(sched->backends[i]);
#7  0x0000ffffb10672e4 in llama_context::synchronize (this=0xaaab0c10f3c0) at /root/llama.cpp/src/llama-context.cpp:374
374         ggml_backend_sched_synchronize(sched.get());
#8  0x0000ffffb106e4c4 in llama_synchronize (ctx=0xaaab0c10f3c0) at /root/llama.cpp/src/llama-context.cpp:2400
2400        ctx->synchronize();
#9  0x0000aaaad615f5bc in test_prompt (ctx=0xaaab0c10f3c0, n_prompt=512, n_batch=2048, n_threads=192) at /root/llama.cpp/tools/llama-bench/llama-bench.cpp:1787
1787        llama_synchronize(ctx);
#10 0x0000aaaad615ff30 in main (argc=13, argv=0xffffcdc95ba8) at /root/llama.cpp/tools/llama-bench/llama-bench.cpp:1955
1955                    bool res = test_prompt(ctx, t.n_prompt, t.n_batch, t.n_threads);
[Inferior 1 (process 165866) detached]
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by noemotiovon**
Fixes #15330

Adjust the allocation size of acl_rstd. The parameter `dims` is set to 3 according to the CANN documentation.

Co-authored-by: Yuchuan <yuchuan-cao@users.noreply.github.com>

### CODE REVIEW

**Comment by noemotiovon** [comment]
@yuchuan-cao, could you review my code?

**Comment by noemotiovon** [comment]
Opt Test:
```
ggml_backend_cann_context: device 0 async operator submission is OFF
ggml_backend_cann_context: device 0 execution mode is GRAPH (acl graph enabled)
Backend 1/2: CANN0
  Device description: Ascend910B4
  Device memory: 30196 MB (29848 MB free)

new_pool_for_device: device 0 use vmm pool
  RMS_NORM(type=f32,ne=[64,5,4,3],v=0,eps=0.000000): OK
  RMS_NORM(type=f32,ne=[64,5,4,3],v=1,eps=0.000000): OK
  RMS_NORM(type=f32,ne=[64,5,4,3],v=0,eps=0.000001): OK
  RMS_NORM(type=f32,ne=[64,5,4,3],v=1,eps=0.000001): OK
  RMS_NORM(type=f32,ne=[64,5,4,3],v=0,eps=0.000100): OK
  RMS_NORM(type=f32,ne=[64,5,4,3],v=1,eps=0.000100): OK
  RMS_NORM(type=f32,ne=[64,5,4,3],v=0,eps=0.100000): OK
  RMS_NORM(type=f32,ne=[64,5,4,3],v=1,eps=0.100000): OK
  11837/11837 tests passed
  Backend CANN0: OK
Backend 2/2: CPU
  Skipping
2/2 backends passed
OK
```

File: ggml/src/ggml-cann/aclnn_ops.cpp [hunk 1]
```diff
@@ -975,18 +975,19 @@ void ggml_cann_rms_norm(ggml_backend_cann_context& ctx, ggml_tensor* dst) {
...
-        acl_rstd_nb[i] = acl_rstd_nb[i - 1] * src->ne[i - 1];
+    for (int i = 1; i < GGML_MAX_DIMS - 1; i++) {
+        acl_rstd_nb[i] = acl_rstd_nb[i - 1] * acl_rstd_ne[i - 1];
     }
     aclTensor* acl_rstd = get_f32_cache_acl_tensor(
         ctx,
         &ctx.rms_norm_zero_tensor_cache.cache,
         ctx.rms_norm_zero_tensor_cache.size,
-        src->ne,
+        acl_rstd_ne,
```
Comment (hipudding) [inline ggml/src/ggml-cann/aclnn_ops.cpp:988]: You can jsut use src as rstd_ne, acl_rstd_ne array is not necessary.

**Review by yuchuan-cao — APPROVED** [review]
I suppose preparing `src->ne` sized buffer would work fine, and preparing `acl_rstd_ne` sized buffer would be a more memory-efficient solution. 

I suggest you double-check the changes in `llama-bench`. The confusing thing is that the memory problem in https://github.com/ggml-org/llama.cpp/issues/15330 doesn't occur in `test-backend-ops` and `llama-cli`. It only emerges when running `llama-bench`. I failed to find out why.

File: ggml/src/ggml-cann/aclnn_ops.cpp (hunk 1 above)
Comment (noemotiovon) [reply ggml/src/ggml-cann/aclnn_ops.cpp:988]: That approach won’t work. If we simply reuse src->ne, then for a 3D tensor the resulting dimensions would be {ne0, ne1, ne2}, whereas what we actually need are {ne1, ne2, ne3}.

**Comment by noemotiovon** [comment]
@yuchuan-cao, Thanks for the suggestion. I ran the `llama-bench` test, and it works fine.
```
# script
./bin/llama-bench -fa 0 -n 0 -p 512 -r 50 -m /home/lichenguang25/.ollama/models/blobs/sha256-6f96e01a3f550ca08aea1e5725bb8d5a7eccc6f281c30417e9d380b8c46467bd -ngl 99

# log
| model                          |       size |     params | backend    | ngl |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | --------------: | -------------------: |
| qwen2 1B F16                   | 942.43 MiB |   494.03 M | CANN       |  99 |           pp512 |      3261.30 ± 18.48 |
```

**Review by hipudding — APPROVED** [review]
