### PR TITLE
test-backend-ops : use flops for some performance tests

### LINKED ISSUE #8898: test-backend-ops performance numbers incorrect
I noticed that for the CUDA backend using an RTX 3090 the reported achieved memory bandwidth for matrix multiplication can be much greater than 936 GB/s (the maximum of the hardware). Therefore, there must be some bug with how these numbers are calculated.

### PR DESCRIPTION
**Pull request by slaren**
- Use flops for some performance tests
- Parallelize tensor quantization
- Use a different set of test cases for performance and correctness tests

Fixes #8898

### CODE REVIEW

File: tests/test-backend-ops.cpp [hunk 1]
```diff
@@ -1591,13 +1583,9 @@ struct test_mul_mat : public test_case {
...
 
-    size_t op_size(ggml_tensor * t) override {
-        size_t a = ggml_nbytes(t->src[0]) * n * nr[0] * nr[1];
-        size_t b = ggml_nbytes(t->src[1]) * m;
-        size_t c  = ggml_nbytes(t);
-        return a + b + c;
-
+    uint64_t op_flops(ggml_tensor * t) override {
         GGML_UNUSED(t);
+        return 2 * m * n * k * bs[0] * nr[0] * bs[1] * nr[1];
```
Comment (JohannesGaessler) [inline tests/test-backend-ops.cpp:1588]: Theoretically you would only need $m \cdot n \cdot k$ multiplications and $m \cdot \cdot (k - 1)$ additions. In practice however this is not going to make a difference due to $k >> 1$.

**Comment by JohannesGaessler** [comment]
The PR looks good to me based on static code analysis; Right now I'm on a train with an unreliable internet connection, I'll test the code when I get home.

File: tests/test-backend-ops.cpp [hunk 2]
```diff
@@ -3624,20 +3606,28 @@ static bool test_backend(ggml_backend_t backend, test_mode mode, const char * op
...
-            if (test->eval_grad(backend, op_name)) {
-                n_ok++;
+    return test_cases;
+}
+
+// Test cases for performance evaluation: should be representative of real-world use cases
+static std::vector<std::unique_ptr<test_case>> make_test_cases_perf() {
+    std::vector<std::unique_ptr<test_case>> test_cases;
+
+    for (int bs : {1, 8, 16, 32, 512}) {
```
Comment (JohannesGaessler) [inline tests/test-backend-ops.cpp:3616]: Matrix multiplications become more efficient for larger batch sizes. At the same time the number of runs is scaled in such a way that the total FLOPs are roughly constant. So you could consider removing 16 and instead adding 1024 or 2048. That would make the test faster and cover a wider range.

**Review by JohannesGaessler — APPROVED** [review]

File: tests/test-backend-ops.cpp (hunk 1 above)
Comment (slaren) [reply tests/test-backend-ops.cpp:1594]: I agree, but most sources seem use $2mnk$, so I thought that it would be more important to be consistent with the way other people measure FLOPS than to correct a small inaccuracy.

File: tests/test-backend-ops.cpp (hunk 2 above)
Comment (slaren) [reply tests/test-backend-ops.cpp]: I have changed it to include only 1 and 512. I think that should provide a good overview of the performance that can be expected during generation and prompt processing for people casually running the benchmark, but I expect that people working on optimizing an operation will modify this function to add the test cases relevant to what they are working on. It would be nice to be able to specify the parameters of the test cases from the command line as well, but that's a more complex change.

The way the number of runs was scaled was not very good, and I noticed that some of the test were too short and produced very inaccurate results. I changed it so that the memory size or flops is used as an initial estimate to determine how many times to duplicate the op in the graph, but the graph is evaluated repeatedly until it has run for least one second. This seem to produce much more reliable results.
