### PR TITLE
minicpm: make embedding_scale residual_scale logit_scale optional with legacy defaults.

### LINKED ISSUE #16192: Eval bug: MiniCPM quantization fails with missing key minicpm.embedding_scale
### Name and Version

./build/bin/llama-cli --version                                                                                               1 ↵  863  14:31:16
ggml_metal_library_init: using embedded metal library
ggml_metal_library_init: loaded in 0.020 sec
ggml_metal_device_init: GPU name:   Apple M4
ggml_metal_device_init: GPU family: MTLGPUFamilyApple9  (1009)
ggml_metal_device_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_device_init: GPU family: MTLGPUFamilyMetal3  (5001)
ggml_metal_device_init: simdgroup reduction   = true
ggml_metal_device_init: simdgroup matrix mul. = true
ggml_metal_device_init: has unified memory    = true
ggml_metal_device_init: has bfloat            = true
ggml_metal_device_init: use residency sets    = true
ggml_metal_device_init: use shared buffers    = true
ggml_metal_device_init: recommendedMaxWorkingSetSize  = 11453.25 MB
version: 6547 (138c87ce)
built with Apple clang version 16.0.0 (clang-1600.0.26.6) for arm64-apple-darwin24.2.0

### Operating systems

Mac

### GGML backends

AMX

### Hardware

download url:https://huggingface.co/runfuture/MiniCPM-2B-dpo-fp16-gguf/tree/main

### Models

_No response_

### Problem description & steps to reproduce

when I quantize a MiniCPM model，got a error info:
llama_model_quantize: failed to quantize: key not found in model: minicpm.embedding_scale

### First Bad Commit

_No response_

### Relevant log output

```shell
./build/bin/llama-quantize ./models/MiniCPM-2B-dpo-fp16-gguf.gguf ./models/Minicpm/ggml-model-Q4_K_M.gguf Q4_K_M          
main: build = 6547 (138c87ce)
main: built with Apple clang version 16.0.0 (clang-1600.0.26.6) for arm64-apple-darwin24.2.0
main: quantizing './models/MiniCPM-2B-dpo-fp16-gguf.gguf' to './models/Minicpm/ggml-model-Q4_K_M.gguf' as Q4_K_M
llama_model_loader: loaded meta data with 21 key-value pairs and 362 tensors from ./models/MiniCPM-2B-dpo-fp16-gguf.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = minicpm
llama_model_loader: - kv   1:                               general.name str              = MiniCPM
llama_model_loader: - kv   2:                     minicpm.context_length u32              = 2048
llama_model_loader: - kv   3:                   minicpm.embedding_length u32              = 2304
llama_model_loader: - kv   4:                        minicpm.block_count u32              = 40
llama_model_loader: - kv   5:                minicpm.feed_forward_length u32              = 5760
llama_model_loader: - kv   6:               minicpm.rope.dimension_count u32              = 64
llama_model_loader: - kv   7:               minicpm.attention.head_count u32              = 36
llama_model_loader: - kv   8:            minicpm.attention.head_count_kv u32              = 36
llama_model_loader: - kv   9:   minicpm.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 1
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,122753]  = ["<unk>", "<s>", "</s>", "<SEP>", "<C...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,122753]  = [-1000.000000, -1000.000000, -1000.00...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,122753]  = [3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  17:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  18:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  19:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% for message in messages %}{% if me...
llama_model_loader: - type  f32:   81 tensors
llama_model_loader: - type  f16:  281 tensors
llama_model_quantize: failed to quantize: key not found in model: minicpm.embedding_scale
main: failed to quantize model from './models/MiniCPM-2B-dpo-fp16-gguf.gguf'
```

### PR DESCRIPTION
**Pull request by vinkal-chudgar**
[baseline-perplexity-16192.txt](https://github.com/user-attachments/files/22561592/baseline-perplexity-16192.txt)
[afterfix-perplexity-16192.txt](https://github.com/user-attachments/files/22561594/afterfix-perplexity-16192.txt)
[baseline-bench-16192.txt](https://github.com/user-attachments/files/22561596/baseline-bench-16192.txt)
[afterfix-bench-16192.txt](https://github.com/user-attachments/files/22561598/afterfix-bench-16192.txt)
[ci.zip](https://github.com/user-attachments/files/22561607/ci.zip)

Fixes: #16192

### Summary
Older MiniCPM GGUFs do not include the scaling metadata keys. The loader previously treated these as required, so quantization failed with "key not found in model". This PR treats those keys optional and supplies legacy default values so older files quantize and load.

### Problem
Some MiniCPM GGUFs do not contain 
- minicpm.embedding_scale
- minicpm.residual_scale, 
- minicpm.logit_scale

The loader currently treats these as required, so quantization fails with:
 `key not found in model: minicpm.embedding_scale`
 
### Solution
In the LLM_ARCH_MINICPM branch of the loader, Initialize MiniCPM scaling parameters with legacy MiniCPM values:
- **f_embedding_scale** = 12.0f
- **f_residual_scale** = 1.4f / sqrtf((float) n_layer)
- **f_logit_scale** = 256.0f / n_embd (guards to 1.0f if n_embd == 0)

Read the three GGUF keys with required = false. When the GGUF provides the keys, their values override the defaults; otherwise the legacy defaults are used. 
Newer GGUFs that already include these keys are unaffected.

### User impact

- **Older MiniCPM GGUFs:** files that omit the three scaling keys now quantize and load successfully. The loader uses legacy defaults instead of failing.
- **Newer MiniCPM GGUFs:** unchanged. If the keys are present, their values are used.

### Validation
**Functional (older + newer MiniCPM)**
- **Older MiniCPM 2B GGUF (without scaling keys):**
   - llama-quantize completes; 
   - At load time, llama-cli prints the effective MiniCPM scales it will use. Excerpt from the log:
     ```
     f_embedding_scale = 12.000000
     f_residual_scale = 0.221359
     f_logit_scale = 1.1e-01
     ```
     Matching calculations from legacy defaults:
     - f_residual_scale is 1.4 / sqrt(n_layer). With n_layer = 40, this equals 0.221359.
     - f_logit_scale is 256 / n_embd. With n_embd = 2304, this equals 0.111111 (printed as 1.1e-01).         
   - llama-cli chat runs normally (sample Q&A prompt verified).
- **Newer MiniCPM4 0.5B GGUF (with scaling keys):**
   - llama-quantize completes cleanly using metadata values.
   - metadata present and used. No defaults are needed; behavior unchanged.
 
###  Perplexity (CPU-only)
Command used in both runs:
```
./build-<base|fix>/bin/llama-perplexity \
  -m ~/models/tinyllama/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf \
  -t 22 -ngl 0 \
  -f ~/data/wikitext-2-raw/wiki.test.100k.raw
```
**Results:**
- **Baseline**: PPL 17.6138 ± 0.5025, throughput 55.27 tok/s, 27136 tokens, 53 chunks
- **After fix:** PPL 17.6138 ± 0.5025, throughput 57.35 tok/s, 27136 tokens, 53 chunks

**Conclusion:** Perplexity is identical. Throughput difference is within normal CPU variance.

**Raw logs (attached)**

- baseline-perplexity-16192.txt
- afterfix-perplexity-16192.txt

### llama-bench (CPU-only)
Command used in both runs:
```
./build-<base|fix>/bin/llama-bench \
  -m ~/models/tinyllama/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf \
  -t 22 -ngl 0 -r 3 --no-warmup --progress -fa 1 -o md
```
**Results:**
- **Baseline:**
   - pp512: 54.55 ± 4.36 t/s
   - tg128: 0.17 ± 0.00 t/s
- **After fix:**
  - pp512: 54.96 ± 3.85 t/s
  - tg128: 0.17 ± 0.00 t/s

No regression observed.

**Raw logs (attached)**

- baseline-bench-16192.txt
- afterfix-bench-16192.txt

### Local CI (CPU-only)
Executed from repo root:
```
rm -rf ./tmp && mkdir -p ./tmp/results ./tmp/mnt
bash ./ci/run.sh ./tmp/results ./tmp/mnt 2>&1 | tee ./tmp/results/ci.log
```

**Outcome**:
- Exit code: 0
- All CTest suites in this run passed
- The local CI log contains a few “ERROR 404: Not Found.” messages. These did not affect the run

CI Log attached: ci.zip

### Style
Formatted with clang-format 18.1.3, only the lines changed in this PR were formatted.

### Environment
- OS: Ubuntu 24.04 on WSL2 (CPU-only)
- Compiler: GCC 13.3
- Build flags: -DGGML_CUDA=OFF, -DGGML_NATIVE=ON
- Threads: -t 22
- Model for perf checks: TinyLlama-1.1B-chat v1.0, Q4_K_M (GGUF v3)
- Dataset for PPL: WikiText-2 test, 100 KB slice wiki.test.100k.raw

### Build SHAs used

**Baseline**: c498fc82fe5b83fc8c6e1627286bdc1f93caddbf (short c498fc82f)
**After fix:** 63376790327d41e2239049bcac880ca5c3ab2b40 (short 633767903)

### CODE REVIEW

File: src/llama-model.cpp [hunk 1]
```diff
@@ -675,10 +675,21 @@ void llama_model::load_hparams(llama_model_loader & ml) {
...
+                // Backward-compatible defaults for older MiniCPM GGUFs:
+                // historical MiniCPM graph constants:
+                // n_embd_base = 256, scale_embd = 12.0f, scale_depth = 1.4f
+
+                hparams.f_embedding_scale = 12.0f;
+                const float scale_depth   = 1.4f;
+                hparams.f_residual_scale  = scale_depth / sqrtf((float) hparams.n_layer);
+                const float n_embd_base   = 256.0f;
+                hparams.f_logit_scale     = hparams.n_embd ? (n_embd_base / float(hparams.n_embd)) : 1.0f;
                 ml.get_key(LLM_KV_ATTENTION_LAYERNORM_RMS_EPS, hparams.f_norm_rms_eps);
```
Comment (CISC) [inline src/llama-model.cpp]:
```suggestion
                // Backward-compatible defaults for older MiniCPM GGUFs
                hparams.f_embedding_scale = 12.0f;
                hparams.f_residual_scale  = 1.4f / sqrtf(float(hparams.n_layer));
                hparams.f_logit_scale     = hparams.n_embd ? (256.0f / float(hparams.n_embd)) : 1.0f;

                ml.get_key(LLM_KV_ATTENTION_LAYERNORM_RMS_EPS, hparams.f_norm_rms_eps);
```

**Review by CISC — APPROVED** [review]

**Comment by CISC** [comment]
Thank you, nice work, will merge when CI finishes. :)
