### PR TITLE
Vulkan: Don't default to CPU device (like llvmpipe)

### LINKED ISSUE #1479: Performance regression between 0.7.4 and 0.9.0
### Issue Description

While working on an Podman AI Lab workflow to automate the update of ramalama version used in Podman AI Lab, I noticed, when switching from 0.7.4 to 0.9.0 a big performance drop in my validation tests:

Here are the logs from the server in the 2 configurations:

0.7.4:

prompt eval time =    3058.24 ms /    64 tokens (   47.78 ms per token,    20.93 tokens per second)
       eval time =   83033.60 ms /   455 tokens (  182.49 ms per token,     5.48 tokens per second)
      total time =   86091.84 ms /   519 tokens
	  
0.9.0:
prompt eval time =  121635.23 ms /    64 tokens ( 1900.55 ms per token,     0.53 tokens per second)
       eval time =   15152.22 ms /    93 tokens (  162.93 ms per token,     6.14 tokens per second)
      total time =  136787.44 ms /   157 tokens
srv  update_slots: all slots are idle

### Steps to reproduce the issue

Need Podman AI Lab dev and modifying the image reference in the code

### Describe the results you received

See above

### Describe the results you expected

Similar performance numbers

### ramalama info output

```yaml
N/A
```

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by 0cc4m**
This should fix https://github.com/containers/ramalama/issues/1479

llvmpipe can still be used by setting `GGML_VK_VISIBLE_DEVICES` to override automatic device selection. This may be required now to allow the Github CI test-backend-ops to run for Vulkan.

### CODE REVIEW

**Review by ericcurtin — APPROVED** [review]

**Comment by ericcurtin** [comment]
This is exactly what we need! Default to llvmpipe was silly (we would even warn that this is probably not what you want to do in the logs).

As an aside will this work with vulkan? Auto-setting ngl for vulkan could be kinda neat:

https://github.com/ggml-org/llama.cpp/pull/14067/files

**Review by ericcurtin — APPROVED** [review]

File: ggml/src/ggml-vulkan/ggml-vulkan.cpp [hunk 1]
```diff
@@ -3700,9 +3700,20 @@ static void ggml_vk_instance_init() {
             }
         }
 
-        // If no dedicated GPUs found, fall back to GPU 0
+        // If no dedicated GPUs found, fall back to the first non-CPU device.
+        // If only CPU devices are available, return without devices.
+        if (vk_instance.device_indices.empty()) {
+            for (size_t i = 0; i < devices.size(); i++) {
+                if (devices[i].getProperties().deviceType != vk::PhysicalDeviceType::eCpu) {
```
Comment (ericcurtin) [inline ggml/src/ggml-vulkan/ggml-vulkan.cpp:3707]: It's possible we want to consider other device types here too like:

`if (devices[i].getProperties().deviceType != vk::PhysicalDeviceType::eCpu && devices[i].getProperties().deviceType != vk::PhysicalDeviceType::eIntegratedGpu)`

Most integrated GPUs are slower than CPU inferencing, especially if an Integrated GPU has < 1GB VRAM it gets very questionable.

But could be discussion for another PR...

**Review by ericcurtin — APPROVED** [review]

**Comment by ericcurtin** [comment]
Looks like we hit a flake

File: ggml/src/ggml-vulkan/ggml-vulkan.cpp (hunk 1 above)
Comment (ericcurtin) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:3707]: Actually looking at the various types it can be, I'd flip it:

`if (devices[i].getProperties().deviceType == vk::PhysicalDeviceType::eDiscreteGpu)`

Comment (0cc4m) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:3707]: That is true, but there are a lot of iGPUs that run better than CPU with Vulkan, too. It is not as straightforward to decide here, we might need a black- or whitelist.

Comment (ericcurtin) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:3707]: Considering we can always override with GGML_VK_VISIBLE_DEVICES, only eDiscreteGpu would get my vote

Comment (ericcurtin) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:3707]: Curious what's your take @a-ghorbani from the Android perspective

**Comment by jeffbolznv** [comment]
Looks like this did indeed disable our CI coverage?

```
2025-06-10T11:49:02.1603371Z 28: Test command: /home/runner/work/llama.cpp/llama.cpp/build/bin/test-backend-ops
2025-06-10T11:49:02.1603888Z 28: Working Directory: .
2025-06-10T11:49:02.1604101Z 28: Test timeout computed to be: 3600
2025-06-10T11:49:02.1899893Z 28: ggml_vulkan: No devices found.
2025-06-10T11:49:02.1919320Z 28: Testing 1 devices
2025-06-10T11:49:02.1919657Z 28: 
2025-06-10T11:49:02.1919954Z 28: Backend 1/1: CPU
2025-06-10T11:49:02.1920324Z 28:   Skipping CPU backend
2025-06-10T11:49:02.1920643Z 28: 1/1 backends passed
2025-06-10T11:49:02.1921080Z 28: [1;32mOK[0m
2025-06-10T11:49:02.1951995Z 28/33 Test #28: test-backend-ops ..................   Passed    0.03 sec
```

IMO this needs to be fixed or reverted ASAP.

**Comment by 0cc4m** [comment]
I didn't expect it to be merged this quickly, maybe should have set it to draft. But basically you only need to set `GGML_VK_VISIBLE_DEVICES=0` to override for the CI, I assume that's not hard to do.

**Comment by jeffbolznv** [comment]
ok, I've made an attempt at https://github.com/ggml-org/llama.cpp/pull/14106 (though I'm not an expert on github workflows)

**Comment by xcvbnmp** [comment]
https://github.com/ggml-org/llama.cpp/pull/14099 هاي شنو []()

File: ggml/src/ggml-vulkan/ggml-vulkan.cpp (hunk 1 above)
Comment (netrunnereve) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:3707]: > Most integrated GPUs are slower than CPU inferencing, especially if an Integrated GPU has < 1GB VRAM it gets very questionable.

> Considering we can always override with GGML_VK_VISIBLE_DEVICES, only eDiscreteGpu would get my vote

In the vast majority of cases an integrated GPU with Vulkan and `-ngl 0` is going to perform better than CPU in prompt processing. Also pretty much all computer iGPUs that support Vulkan (so anything newer than Intel Skylake or the AMD GCN2 APUs) should be able to access several GBs of memory no problem. I'll admit I'm not sure about phones though.

If you look at [the chart](https://github.com/ggml-org/llama.cpp/discussions/10879) a lot of the newer integrated chips are running very well even with the model fully offloaded. Also Intel, AMD, and Nvidia are beginning to follow Apple by making fast iGPUs with more memory bandwidth.

Now there's a case where the CPU might win for prompt processing though and that's when you have one of those new 16 core AMD Zen 5 CPUs with the little 2 CU iGPU.
