### PR TITLE
Fix params underscore convert to dash.

### LINKED ISSUE #6191: "error: unknown argument: --ctx-size" after llama.cpp update.
After updating llama.cpp, when I try to run the model, I get this error. I assume it has been replaced with another one, but there are no changes in main.exe -h or the documentation.

### PR DESCRIPTION
**Pull request by dranger003**
Fixes https://github.com/ggerganov/llama.cpp/issues/6191. Arguments containing `_` were previously automatically converted to `-`, this PR restores that functionaly.

### CODE REVIEW

File: common/common.cpp [hunk 1]
```diff
@@ -154,8 +154,7 @@ bool gpt_params_parse(int argc, char ** argv, gpt_params & params) {
     return result;
 }
 
-static bool gpt_params_find_arg(int argc, char ** argv, gpt_params & params, int & i, bool & invalid_param) {
-    std::string arg = argv[i];
+static bool gpt_params_find_arg(int argc, char ** argv, const std::string& arg, gpt_params & params, int & i, bool & invalid_param) {
```
Comment (slaren) [inline common/common.cpp:157]:
```suggestion
static bool gpt_params_find_arg(int argc, char ** argv, const std::string & arg, gpt_params & params, int & i, bool & invalid_param) {
```

**Review by slaren — APPROVED** [review]
