### PR TITLE
vulkan: Find optimal memory type but with fallback

### LINKED ISSUE #5319: Fails with  ggml_vulkan: No suitable memory type found: ErrorOutOfDeviceMemory
Please include information about your system, the steps to reproduce the bug, and the version of llama.cpp that you are using. If possible, please provide a minimal code example that reproduces the bug.

1. I am using a Google Pixel 6 Pro with vulkan, build with make and clang `clang version 17.0.6 Target: aarch64-unknown-linux-android24` 
2. I am on 277fad30c60ef3559dc2d01b19d05e659d40a824 `b2059` 

Here is a link for the output of `vulkaninfo` https://gist.github.com/alex4o/20f949910574295c22f951f64e1d421d
here is a link for the output of `main` https://gist.github.com/alex4o/7809ed6597cb88c4f44fcbab03475d9e

Have not looked too deep in this but it can be seen that llama.cpp tries to allocate a bigger chunk of memory then it needs for some reason.

### PR DESCRIPTION
**Pull request by luciferous**
Some memory properties are nice to have, but not critical. `eHostCached`, for instance, isn't essential, and yet we fail on devices where this memory property isn't available.

    ggml_vulkan: No suitable memory type found: ErrorOutOfDeviceMemory

This change differentiates between those properties that are critical and those that are just nice-to-have, and will fail only when critical properties aren't available.

Fixes #5319.

### CODE REVIEW

**Comment by luciferous** [comment]
@0cc4m Waiting for #5321 to merge before incorporating changes, but thought we can discuss the general idea.

File: ggml-vulkan.cpp [hunk 1]
```diff
@@ -676,17 +688,15 @@ static vk_buffer ggml_vk_create_buffer(size_t size, vk::MemoryPropertyFlags req_
...
-    for (uint32_t i = 0; i < mem_props.memoryTypeCount; ++i) {
-        vk::MemoryType memory_type = mem_props.memoryTypes[i];
-        if ((mem_req.memoryTypeBits & ((uint64_t)1 << i)) && (req_flags & memory_type.propertyFlags) == req_flags && mem_props.memoryHeaps[memory_type.heapIndex].size >= mem_req.size) {
-            memory_type_index = i;
-            break;
-        }
+    uint32_t memory_type_index = -1;
+    if (desired_flags) {
+      memory_type_index = find_properties(&mem_props, &mem_req, req_flags | desired_flags);
+    }
```
Comment (cebtenzzre) [inline ggml-vulkan.cpp:694]: fix this indentation

**Comment by 0cc4m** [comment]
For staging buffers we could probably just drop the cached requirement alltogether, since they only do memcpys to and from cpu. But overall this approach is probably a good idea and corresponds with something that VMA does. I'll give it a try soon and do a review. Thank you for your work!

**Comment by 0cc4m** [comment]
I think it would be better to just add a fallback buffer type to the `ggml_vk_create_buffers` function, then it can also take over the fallback from DEVICE_LOCAL to HOST_VISIBLE/COHERENT for UMA devices (APUs).

**Comment by luciferous** [comment]
Thanks for the review @0cc4m.

For my understanding: are you suggesting we should always fallback to HOST_VISIBLE/COHERENT in `ggml_vk_create_buffers` when the wanted properties aren't available? I.e.,

```cpp
memory_type_index = find_properties(&mem_props, &mem_req, req_flags);

if (memory_type_index == -1) {
    memory_type_index = find_properties(&mem_props, &mem_req, vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent);
}
```

**Comment by 0cc4m** [comment]
> Thanks for the review @0cc4m.
> 
> For my understanding: are you suggesting we should always fallback to HOST_VISIBLE/COHERENT in `ggml_vk_create_buffers` when the wanted properties aren't available? I.e.,
> 
> ```c++
> memory_type_index = find_properties(&mem_props, &mem_req, req_flags);
> 
> if (memory_type_index == -1) {
>     memory_type_index = find_properties(&mem_props, &mem_req, vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent);
> }
> ```

I mean instead of having required flags and desired flags we could just allow having two pairs of flags. If the first isn't available, fall back to the second. If that isn't available, throw an error. If the second set is empty, throw an error after the first fails.

```c++
static vk_buffer ggml_vk_create_buffer(ggml_backend_vk_context * ctx, size_t size, vk::MemoryPropertyFlags req_flags, vk::MemoryPropertyFlags fallback_flags = vk::MemoryPropertyFlags(0)) {
[...]
memory_type_index = find_properties(&mem_props, &mem_req, req_flags);

if (memory_type_index == -1 && fallback_flags != 0) {
    memory_type_index = find_properties(&mem_props, &mem_req, fallback_flags);
}
```

Something like this.

File: ggml-vulkan.cpp [hunk 2]
```diff
@@ -734,17 +746,22 @@ static vk_buffer ggml_vk_create_buffer(ggml_backend_vk_context * ctx, size_t siz
 
     vk::PhysicalDeviceMemoryProperties mem_props = ctx->device.lock()->physical_device.getMemoryProperties();
 
-    uint32_t memory_type_index = UINT32_MAX;
+    uint32_t memory_type_index = -1;
```
Comment (0cc4m) [inline ggml-vulkan.cpp:749]: Basically your change behaves the same as it was before, but it hides an underflow. Was there a specific reason you preferred `-1` over `UINT32_MAX`? It'd only make sense if it was not unsigned, but I don't see an issue with `UINT32_MAX`, there will never be a device where that's a valid value.

File: ggml-vulkan.cpp [hunk 3]
```diff
@@ -734,17 +746,22 @@ static vk_buffer ggml_vk_create_buffer(ggml_backend_vk_context * ctx, size_t siz
...
+        // ...as long as req_flags was either: 1) not DEVICE_LOCAL; or 2) DEVICE_LOCAL and device has UMA.
+        !(req_flags & vk::MemoryPropertyFlagBits::eDeviceLocal) ||
+         (req_flags & vk::MemoryPropertyFlagBits::eDeviceLocal && ctx->device.lock()->uma))
+    ) {
+        memory_type_index = find_properties(&mem_props, &mem_req, fallback_flags);
+        buf->memory_property_flags = fallback_flags;
     }
 
-    if (memory_type_index >= mem_props.memoryTypeCount) {
+    if (memory_type_index == -1) {
```
Comment (0cc4m) [inline ggml-vulkan.cpp:764]: Same as above.

File: ggml-vulkan.cpp [hunk 4]
```diff
@@ -734,17 +746,22 @@ static vk_buffer ggml_vk_create_buffer(ggml_backend_vk_context * ctx, size_t siz
...
-            break;
-        }
+    memory_type_index = find_properties(&mem_props, &mem_req, req_flags);
+    buf->memory_property_flags = req_flags;
+
+    // Failed to find memory type matching req_flags, but we can try again with fallback_flags if specified...
+    if (memory_type_index == -1 && fallback_flags && (
+        // ...as long as req_flags was either: 1) not DEVICE_LOCAL; or 2) DEVICE_LOCAL and device has UMA.
+        !(req_flags & vk::MemoryPropertyFlagBits::eDeviceLocal) ||
+         (req_flags & vk::MemoryPropertyFlagBits::eDeviceLocal && ctx->device.lock()->uma))
```
Comment (0cc4m) [inline ggml-vulkan.cpp:758]: I would prefer if the UMA logic stays in `ggml_vk_create_buffer_device` and this function just falls back if a fallback is given, without further checks.

File: ggml-vulkan.cpp (hunk 2 above)
Comment (luciferous) [reply ggml-vulkan.cpp:749]: I was just using -1 as an error sentinel in find_properties, but forgot to update the sign. I'll revert to UINT32_MAX since that works too.

**Review by 0cc4m — APPROVED** [review]

**Comment by 0cc4m** [comment]
Thank you, looks good now.
