### PR TITLE
server: enhanced health endpoint

### LINKED ISSUE #4746: Healthcheck endpoint?
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [ X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [ X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [ X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description
I'd like the server to have a /health endpoint.  

# Motivation

Basically this is for docker so that I can restart the server if it fails automatically and recover given that llama.cpp will crash the process in many cases.

# Possible Implementation
/health as a get that will return 200 if it's healthy and obviously timeout if the server isn't available.  The best I can do right now is props

Also, the final docker container needs to have curl or wget installed into it, and then documentation updated to show how to go and use the docker-compose functionality to do this.

I'd also like to see /completion and the async version return a 429 error instead of 404 when it is busy as 429 is easily retried but 404 is a not found and thus terminal.

### PR DESCRIPTION
**Pull request by phymbert**
**Context**
It can be useful to monitor the server slots activity, especially when there is no slot available. It will allow in the context of a llama servers cluster to route incoming request to instance with available slots, for example when using kubernetes probes.

**Proposed changes**
Add `slots_idle` and `slots_processing`  fields in the `health` endpoint response, answer `503` if not slot are available.

Closes #4746

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

File: examples/server/server.cpp [hunk 1]
```diff
@@ -2561,8 +2561,35 @@ int main(int argc, char **argv)
...
+                                {"slots_processing", processing_slots}};
+                        res.set_content(health.dump(), "application/json");
+                        res.status = 200; // HTTP OK
+                    } else {
+                        json health = {
+                                {"status",           "no slot available"},
+                                {"slots_idle",       available_slots},
+                                {"slots_processing", processing_slots}};
+                        res.set_content(health.dump(), "application/json");
+                        res.status = 503; // HTTP Service Unavailable
```
Comment (brittlewis12) [inline examples/server/server.cpp:2590]: @phymbert thanks for introducing this additional metadata to the health check!

one nit: it seems unidiomatic for health to return an error status code for an expected and error-free state. in practice, for a local inference server with a single slot (the default behavior), this is particularly unintuitive.

while the server _is_ busy wrt inference, it can happily process health check requests — why return an error (`5xx`) status code, rather than a success (request understood and processed just fine) along with the actual information desired, the count of available slots (`0`)?

503 or 409 conflict make more sense to me for `/completion` or chat completion requests — their request can genuinely not be processed. but the health check returning 5xx codes during normal operation feels wrong to me. the server is not unhealthy by any metric.

it seems this is [not an uncommon point of bike shedding](https://stackoverflow.com/a/40424959) so I will happily work around this behavior if i'm in the minority, but wanted to share in case there was any other agreement to this effect.

happy to put up a patch if so!

Comment (phymbert) [reply examples/server/server.cpp:2590]: hi @brittlewis12, thanks for your feedback.

My primary goal is to point a [kubernetes readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes) to the health endpoint. This way, the server will not receive new incoming request but they will be routed to another available pod. It does not mean the server is down, but as `503` says: it is overloaded. This is the standard for cloud native application.

Comment (phymbert) [reply examples/server/server.cpp:2590]: @brittlewis12 I finally got your point, PR #5594 address it, thanks for pointing me out this.
