### PR TITLE
server : fix logprobs, make it OAI-compatible

### LINKED ISSUE #10733: Misc. bug: n_probs is not working with llama.cpp server
### Name and Version

build: 4291 (ce8784bd) with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

Docker image name: `ggerganov/llama.cpp:server-cuda`
Docker image hash: sha256:`8fa3ccfdcd21874c8a8b257b6bf6abf10070d612e00394b477ec124bd56f2d12`

### Operating systems

_No response_

### Which llama.cpp modules do you know to be affected?

llama-server

### Problem description & steps to reproduce

Started the server with no speculative decoding.
```bash
curl --request POST \
     --url http://localhost:8080/completion \
     --header "Content-Type: application/json" \
     --data '{"prompt": "Why is the sky is blue?", "n_probs": 10}'
```
The output doesn't contain `completion_probabilities`, which it should

### First Bad Commit

**HINT**:

For docker image `server-cuda-b4274`, n_probs is working as expected
For docker image `server-cuda-b4277`, n_probs is not working

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ngxson**
Fix https://github.com/ggerganov/llama.cpp/issues/10733

The `/v1/chat/completions` now has full support for `logprobs`. See oai docs [here](https://platform.openai.com/docs/api-reference/chat/create). Please note that this is **pre-sampling** probs (i.e. no sampling method is applied)

Example using official openai library:

```py
def test_logprobs():
    client = OpenAI(api_key="dummy", base_url=f"http://{server.server_host}:{server.server_port}")
    res = client.chat.completions.create(
        model="gpt-3.5-turbo-instruct",
        temperature=0.0,
        messages=[
            {"role": "system", "content": "Book"},
            {"role": "user", "content": "What is the best book"},
        ],
        max_tokens=5,
        logprobs=True,
        top_logprobs=10,
    )
    for token in res.choices[0].logprobs.content:
        print(token.token, token.logprob)
```

For non-OAI compatible endpoint `/completion`, the `completion_probabilities` is also changed:

Request:

```
{ "prompt": "hi", "n_predict": 2, "n_probs": 3, "top_k": 1 }
```

Response:

```
{
    "index": 0,
    "content": ", i",
    ...
    "completion_probabilities": [
        {
            "id": 11,
            "token": ",",
            "logprob": 0.0,
            "bytes": [
                44
            ],
            "top_logprobs": [
                {
                    "id": 11,
                    "token": ",",
                    "bytes": [
                        44
                    ],
                    "logprob": -1.9807817935943604
                },
                {
                    "id": 682,
                    "token": " all",
                    "bytes": [
                        32,
                        97,
                        108,
                        108
                    ],
                    "logprob": -2.73698353767395
                },
                {
                    "id": 5127,
                    "token": " everyone",
                    "bytes": [
                        32,
                        101,
                        118,
                        101,
                        114,
                        121,
                        111,
                        110,
                        101
                    ],
                    "logprob": -2.8409159183502197
                }
            ]
        },
        {
            "id": 602,
            "token": " i",
            "logprob": 0.0,
            "bytes": [
                32,
                105
            ],
            "top_logprobs": [
                {
                    "id": 602,
                    "token": " i",
                    "bytes": [
                        32,
                        105
                    ],
                    "logprob": -1.4105287790298462
                },
                {
                    "id": 358,
                    "token": " I",
                    "bytes": [
                        32,
                        73
                    ],
                    "logprob": -1.5139223337173462
                },
                {
                    "id": 856,
                    "token": " my",
                    "bytes": [
                        32,
                        109,
                        121
                    ],
                    "logprob": -3.0677266120910645
                }
            ]
        }
    ]
}
```

For **post-sampling** probs, add `"post_sampling_probs": true` to the request. Example for the response:

```
{
    "completion_probabilities": [
        {
            "id": 682,
            "token": " all",
            "bytes": [
                32,
                97,
                108,
                108
            ],
            "prob": 0.2798407971858978,
            "top_probs": [
                {
                    "id": 11,
                    "token": ",",
                    "bytes": [
                        44
                    ],
                    "prob": 0.7201591730117798
                },
                {
                    "id": 682,
                    "token": " all",
                    "bytes": [
                        32,
                        97,
                        108,
                        108
                    ],
                    "prob": 0.2798407971858978
                }
            ]
        },
        ...
    ]
}
```

### CODE REVIEW

File: examples/server/server.cpp [hunk 1]
```diff
@@ -342,6 +342,11 @@ struct server_task {
             }
         }
 
+        if (params.sampling.n_probs > 0 && params.cache_prompt) {
+            SRV_WRN("cache_prompt is not compatible with n_probs > 0 (current value = %d), disabling cache_prompt.\n", params.sampling.n_probs);
```
Comment (ggerganov) [inline examples/server/server.cpp:346]: Hm, what is the reason to not be compatible?

Comment (ngxson) [reply examples/server/server.cpp:346]: Hmm after second thought I think my logic here is incorrect, I'll revert it. Thanks for asking.

Indeed, I was thinking about the case where generated tokens are being cached (but we don't store their logprobs in cache). But in this case, generated tokens from last request will be used as prompt tokens for next request, so we don't even need their logprobs anyway!

File: examples/server/server.cpp [hunk 2]
```diff
@@ -2841,7 +2866,9 @@ struct server_context {
                 for (size_t i = 0; i < ids.size(); ++i) {
                     completion_token_output result;
 
-                    result.tok = ids[i];
+                    result.tok          = ids[i];
+                    result.text_to_send = common_token_to_piece(ctx, result.tok, params_base.special);
+                    result.prob         = 1.0f; // set later
```
Comment (ngxson) [inline examples/server/server.cpp:2871]: Here is the branch for speculative decoding. I'm not sure now I can get token probs here. Could you give me some clues? @ggerganov

**Comment by p-e-w** [comment]
Based on the example response, it appears that this implementation returns *probabilities* (between `0` and `1`) but labels them as *log probabilities* (which by definition must be between `-infinity` and `0`). I don't know which of the two is expected over the `/completion` endpoint, but naming the field `logprob` when it contains a plain probability is certainly wrong.

Also, just to clarify, `logprob` and `top_logprobs` are the values *before* samplers, right? That is, before any penalties, truncation, etc. are applied and distort the probability distribution. In other words, they should contain the raw distribution that the model produces, not the transformed distribution that the generator samples from. Because the data is useless for many applications otherwise (such as confidence estimation).

**Comment by ngxson** [comment]
> I don't know which of the two is expected over the `/completion` endpoint, but naming the field `logprob` when it contains a plain probability is certainly wrong.

Ok I didn't noticed that, thanks for spotting it. It's a simple fix, just `std::log` the prob to turn it into logprob.

> Also, just to clarify, `logprob` and `top_logprobs` are the values _before_ samplers, right?

It's the prob after `common_sampler_sample`, so the sampler chain is already applied

File: examples/server/server.cpp (hunk 1 above)
Comment (ngxson) [reply examples/server/server.cpp]: Remove this check in https://github.com/ggerganov/llama.cpp/pull/10783/commits/01afafef93ad32b8be48987a0b86649bf176e39f

**Comment by p-e-w** [comment]
> It's the prob after `common_sampler_sample`, so the sampler chain is already applied

That is wrong and needs to be changed. Post-sampler probs are essentially worthless.

Imagine you are doing greedy sampling (`top_k = 1`). You want to know which other choices were available at each token position, how probable your entire token sequence is (one of the classic applications of logprobs) etc. So you set `logprobs = true` and `top_logprobs = 10` in the request.

But with the current logic, the `logprob` field in the result is simply `0` for every token, corresponding to a probability of `1`, because the `top_k` sampler leaves only the most probable token, and after normalization, that token has probability 100%. Also, the `top_logprobs` field will contain only that token, because all other tokens were cut off by the sampler.

Samplers destroy information in order to make a choice. The whole point of requesting logprobs is to get that information. We already know which choice was made (the token in the result), so the distorted probability distribution left over by the sampler chain is useless. Pretty much every standard use case for logprobs (confidence estimation, beam search guidance) breaks down if the probs are post-sampling.

**Comment by ngxson** [comment]
> That is wrong and needs to be changed. Post-sampler probs are essentially worthless.

Tbh I'm not even the one who wrote this part of code from the beginning, so I didn't notice that.

Judging by comments from https://github.com/vllm-project/vllm/issues/9453 , this suppose to as you said then.

Just some lines of code to modify, not a big deal.

**Comment by ngxson** [comment]
Done, it's now returning the `log(softmax(logits))`

File: examples/server/README.md [hunk 3]
```diff
@@ -448,27 +452,48 @@ These words will not be included in the completion, so make sure to add them to
...
     {
+      "id": <token id>,
       "prob": float,
-      "tok_str": "<most likely token>"
+      "token": "<most likely token>",
+      "bytes": [int, int, ...],
+      "top_logprobs": [
+        {
+          "id": <token id>,
+          "prob": float,
```
Comment (p-e-w) [inline examples/server/README.md:470]: The surrounding field is called `top_logprobs`, but the inner value is labeled as `prob`. Which is it – a prob or a logprob?

**Review by p-e-w — COMMENTED** [review]
Great stuff! This will make the server much more useful for research-type work. I have tested many inference engines, and all of them have at least one bug related to obtaining logprobs, which led me to hack together my own server to work with them. Glad I'll finally be able to ditch that!

File: examples/server/README.md (hunk 3 above)
Comment (ngxson) [reply examples/server/README.md]: update. it should be `logprob` as mentioned in the example (forgot to update it here - thanks for reminding me)

File: examples/server/utils.hpp [hunk 4]
```diff
@@ -664,3 +694,33 @@ static json format_logit_bias(const std::vector<llama_logit_bias> & logit_bias)
 static std::string safe_json_to_str(json data) {
     return data.dump(-1, ' ', false, json::error_handler_t::replace);
 }
+
+static std::vector<llama_token_data> get_token_probabilities(llama_context * ctx, int idx) {
```
Comment (ngxson) [inline examples/server/utils.hpp:698]: NOTE: because `llama_sampler_init_softmax` is deprecated, I need to copy the its code here.

Comment (ggerganov) [reply examples/server/utils.hpp:698]: This function is extremely slow because it operates on the entire vocabulary. It can cause many headaches by having this enabled by default for `n_probs > 0`, so at the very least outputting logprobs has to be gated by a parameter only if the user really knows they want these. In majority of the cases, the `llama-server` users want the final token probability for visualization in the UI and this should not affect the performance in a significant way.

Comment (ngxson) [reply examples/server/utils.hpp:698]: Yeah I think We can add a gated parameter `--max-n-probs` and default it to 1

Comment (ngxson) [reply examples/server/utils.hpp:698]: hmm sorry I misunderstood it a bit, the option should me `--probs-multiple-tokens` or `-pmt` instead of max n_probs as a said. Having max n_probs means nothing because the softmax is ran on n_vocab tokens anyways

Comment (ngxson) [reply examples/server/utils.hpp:698]: I added [--multi-token-probs](https://github.com/ggerganov/llama.cpp/pull/10783/commits/196e237e097c244e4ec14c7ff4f82a7dd7f0475b)

Comment (slaren) [reply examples/server/utils.hpp:698]: https://github.com/ggerganov/llama.cpp/blob/196e237e097c244e4ec14c7ff4f82a7dd7f0475b/examples/server/server.cpp#L242-L244

I don't think the value of `n_predict` is the issue here, as long as pre-sampling probabilities have to be returned it requires processing all the logits, which is expensive. But I also do not think that what the users really want is the token probability after sampling. Unless you are debugging a sampler, what you really want to know is what tokens the model actually wants to generate and the raw probability of the one that was selected.

However, I would expect the probabilities to be effectively the same if only, say, the top 1000 tokens are considered in the calculation. In fact I believe the min-p sampler optimization added by @JohannesGaessler does something like this to determine if it is necessary to calculate a full softmax (correct me if I am wrong, I only looked at it briefly a while ago).

Comment (ngxson) [reply examples/server/utils.hpp:698]: > But I also do not think that what the users really want is the token probability after sampling

Indeed, some users from the original issue https://github.com/ggerganov/llama.cpp/issues/10733 says that they need probs after sampling for calculating perplexity. Coincidentally, last month, I had a conversation about the same subject and seems like it's a valid need. Some people wants to measure perplexity cross runtime (i.e. llama.cpp, TGI, vLLM, etc) and even cross open/closed source models if possible.

I would say that users don't really care about performance for this use case, so I don't think we should spend time to optimize it.

**Comment by JohannesGaessler** [comment]
Regarding log probs of before vs. after samplers: my opinion is that they should reflect the probabilities after samplers since by applying samplers you are intentionally distorting the probability distribution that the model puts out. I don't see why the log likelihood of the original, undistorted distribution would be useful in that scenario. The only real use case I see is to do greedy sampling while still obtaining the probabilities of the original distribution which should be possible by setting the temperature to a negative value. But I ultimately don't feel strongly about this.

File: examples/server/utils.hpp (hunk 4 above)
Comment (JohannesGaessler) [reply examples/server/utils.hpp:698]: >However, I would expect the probabilities to be effectively the same if only, say, the top 1000 tokens are considered in the calculation. In fact I believe the min-p sampler optimization added by @JohannesGaessler does something like this to determine if it is necessary to calculate a full softmax (correct me if I am wrong, I only looked at it briefly a while ago).

The min-p sampler optimization that I did exploits that a ratio of probabilities is equivalent to a difference in logits so min-p sampling can just be done relative to the maximum logit without having to explicitly calculate the softmax of all tokens. It should be fine to apply loose min-p sampling prior to calculating the token probabilities since the vast majority of tokens will effectively have 0 probability.

**Comment by ngxson** [comment]
> I don't see why the log likelihood of the original, undistorted distribution would be useful in that scenario.

Looking at the [cookbook by openai](https://cookbook.openai.com/examples/using_logprobs), I think they are returning logprobs before sampling.

The problem with returning post-sampling probs is that user don't know which samplers are enabled by default.

Also some users from https://github.com/ggerganov/llama.cpp/issues/10733 confirmed that they need this to calculate perplexity (as explained earlier in thie PR)

**Comment by JohannesGaessler** [comment]
If our goal is to provide a bug-for-bug OpenAI-compatible API then I agree we should do it like this, but I don't agree that this is the correct way to calculate perplexity.

File: examples/server/utils.hpp (hunk 4 above)
Comment (p-e-w) [reply examples/server/utils.hpp:698]: Not sure if "gating" this functionality is a good idea. This is what the OpenAI API does. If llama.cpp claims OAI compatibility, it shouldn't come with a fine print of *"...but only if you enable this ad-hoc CLI flag"*.

**Comment by p-e-w** [comment]
@JohannesGaessler 

> Regarding log probs of before vs. after samplers: my opinion is that they should reflect the probabilities after samplers since by applying samplers you are intentionally distorting the probability distribution that the model puts out.

You are intentionally distorting the probability distribution *for the purpose of choosing a token.* The distribution produced by samplers leads to better output being generated in practice, which is why samplers are being used.

But when users request logprobs, they are interested in *information.* The post-sampler distribution doesn't contain any information, it's just an ad-hoc, heuristic construct made to help the generator pick a token. Most samplers don't even take the input context into account. By contrast, the original distribution produced by the model reflects the insights from training and the subtleties of the specific context. Standard metrics like perplexity aren't even well-defined on many post-sampler distributions because those can assign zero probabilities to tokens, resulting in infinite perplexity if the test sequence does contain one of those tokens.

Moreover, sampler transformations are a one-way process: The post-sampler distribution can be generated from the pre-sampler distribution given the sampler parameters, but the reverse is not true in general. Therefore, returning the pre-sampler distribution is in a sense a superset of returning the post-sampler one.

**Comment by JohannesGaessler** [comment]
What we are specifically talking about is the perplexity of a token sequence *as it's being generated*. The corresponding probability distribution is post-samplers. I don't see why the perplexity of such a sequence using the pre-samplers distribution would be a meaningful number.

If you have a pre-generated text and want to calculate perplexity, use the `llama-perplexity` tool.

**Comment by ggerganov** [comment]
Based on the feedback so far, I think we have to support both raw logprobs and post-sampling probs:

- For the logprobs, we adopt the same API as the OpenAI spec.
- For the post-sampler probs, we should mirror the logprobs OpenAI API, but drop the "log" prefix: `logprobs` -> `probs`, `top_logprobs` -> `top_probs`
- I don't see a problem both the `/completion` and `/chat/completion` endpoints to support the 2 types of probability outputs.
- For the logprobs, we should apply the "min-p" optimization for some performance improvement.
- In the `llama-server` UI, it would be nice to be able to choose to display either the pre-sampling or post-sampling probs, since I can see that both values can make sense in different cases.

Does that sound OK?

**Comment by JohannesGaessler** [comment]
>For the post-sampler probs, we should mirror the logprobs OpenAI API, but drop the "log" prefix: logprobs -> probs, top_logprobs -> top_probs

I think that would be confusing, my intuitive expectation would be that `logprobs` is just the input of the softmax for `probs`. The intuitive name that I would associate with the raw model outputs pre-softmax is "logits". I would prefer if we define `probs` and `logprobs` in the documentation (whichever way we choose to do it) and then add something with a more explicit name like `probs_softmax` or `probs_samplers`.

**Comment by ggerganov** [comment]
>  that logprobs is just the input of the softmax for probs

To make sure we are on the same page, do these definitions sound correct to you:

1. `logits`: raw model output
1. `raw probabilities/probs`, `pre-sampling probabilities/probs`: this is `softmax(logits)`
1. `raw logprobs`, `pre-sampling logprobs`: this is `log(softmax(logits))`
1. `post-sampling probs`: this are the probabilities that we computed after applying the full sampling chain

So 2. and 3. are essentially the same thing, but with `log` applied to one of them. The OAI chose to output (3) in their API, so to be compatible, we should do the same.

The raw logits (1) would require too much data to be transported over the network and top-logits don't have much applications, so I think these should not be exposed through the API in any way.

The post-sampling probs (4) are what we have exposed up to know and the suggestion is to keep this as an option.

If I understand correctly, you are suggesting to call (2) `probs_softmax` and (4) `probs_samplers`. This sounds intuitive to me, but the problem is that (2) won't match the OAI spec.

**Comment by JohannesGaessler** [comment]
>raw logprobs, pre-sampling logprobs: this is log(softmax(logits))

Sorry, that's what I meant, I agree that this is the correct relationship between `probs` and `logprobs`.

>If I understand correctly, you are suggesting to call (2) probs_softmax and (4) probs_samplers. This sounds intuitive to me, but the problem is that (2) won't match the OAI spec.

If we want to have an OAI-compatible API we should return the same quantities under the same name. So for the OAI-compatible API (2) should be returned as `logprobs`. But we should not just return (4) as `probs` since that would be confusing. So I think (4) should be returned as something like `probs_samplers` or `probs_post_samplers`.

For our own API we are not bound to whatever choices OAI made. We could choose to define `probs` and `logprobs` as (the logarithm of) the probabilities post samplers (though I think consistency with the OAI-compatible API would be preferable). In that case I would call the probabilities when using just the softmax something like `probs_softmax`.

I do not mean to use both `probs_softmax` and `probs_samplers` simultaneously, just one of them to clearly distinguish the property from the default probabilities.

**Comment by ggerganov** [comment]
> But we should not just return (4) as probs since that would be confusing. So I think (4) should be returned as something like probs_samplers or probs_post_samplers (if at all).

Yes, I agree having "(4) as `probs`" would be confusing and the suggestion for `probs_samplers`  or `probs_post_samplers` is better.

**Comment by p-e-w** [comment]
> What we are specifically talking about is the perplexity of a token sequence *as it's being generated.* The corresponding probability distribution is post-samplers. I don't see why the perplexity of such a sequence using the pre-samplers distribution would be a meaningful number.

Regardless of how one feels perplexity should be computed, doing so isn't the only application of logprobs. For confidence estimation, we absolutely want the pre-sampler probabilities, because otherwise samplers become a self-fulfilling prophecy where the confidence goes up because the choices are narrowed down by the samplers. In the common case where only a single token remains, this would give 100% confidence, which is patently absurd because that "confidence" is manufactured by truncation.

**Comment by p-e-w** [comment]
Providing more information in extra fields sounds good, but I hope we can all agree that the fields `logprob` and `top_logprobs` **must** contain the pre-sampler log probabilities, and the pre-sampler top tokens, respectively. Those field names are from the OAI spec, and having the same names with different semantics would be a nightmare.

**Comment by ngxson** [comment]
Hmm ok so to settle the discussion between post and pre sampling probs, I think we can support both and the rule is:
- For OAI-compat API (i.e. everything under `/v1/*`), we will return a pre-sampling, aka `log(softmax(logits))`
- For non-OAI-compat, we only return the probs and NOT the logprobs:
  - Default to pre-sampling probs (like OAI, `softmax(logits)`)
  - If user specify `"pre_sampling_probs": true` in the request, we will return the post sampling probs

**Comment by JohannesGaessler** [comment]
>If user specify "pre_sampling_probs": true in the request, we will return the post sampling probs

I assume you mean `post_sampling_probs`; that would be fine with me.

File: examples/server/utils.hpp (hunk 4 above)
Comment (ngxson) [reply examples/server/utils.hpp:705]: @ggerganov Second thought, I think most users know what they're doing (and the consequence) when they want to get `n_probs` for multiple tokens. I think we don't really need this flag for now. Is it ok if I remove it?

Comment (ngxson) [reply examples/server/utils.hpp:705]: Removed in https://github.com/ggerganov/llama.cpp/pull/10783/commits/8734df73d9a470181ba82b5932b2980e35972fb9

**Comment by ngxson** [comment]
@ggerganov Can you please re-review this PR? Thank you!

File: examples/server/server.cpp (hunk 2 above)
Comment (ggerganov) [reply examples/server/server.cpp:2985]: Think we need to update `common_sampler_sample_and_accept_n()` to return the probs. But let's fix this later.

File: examples/server/server.cpp [hunk 5]
```diff
@@ -1923,6 +1954,57 @@ struct server_context {
         return slot.has_next_token; // continue
     }
 
+    void populate_token_probs(const server_slot & slot, completion_token_output & result, bool post_sampling, bool special, int idx) {
+        size_t n_probs = slot.params.sampling.n_probs;
+        int n_vocab = llama_n_vocab(llama_get_model(ctx));
+        if (post_sampling) {
```
Comment (ggerganov) [inline examples/server/server.cpp:1960]: Is this check inverted? Post sampling should mean after the samplers have been applied.

**Review by ggerganov — APPROVED** [review]

File: examples/server/server.cpp (hunk 5 above)
Comment (ngxson) [reply examples/server/server.cpp:1960]: Yes it's reverted. The test cannot detect this mistake because the test model (stories260K) only output either 1.0 or 0.0 probability. I need to add a specific test case for it:

```
assert any(prob["prob"] == 1.0 for prob in tok["top_probs"])
```

File: examples/server/server.cpp [hunk 6]
```diff
@@ -1923,6 +1954,58 @@ struct server_context {
...
+                    result.prob = cur_p->data[i].p;
+                }
+                // set probability for top n_probs tokens
+                result.probs.push_back({
+                    cur_p->data[i].id,
+                    common_detokenize(ctx, {cur_p->data[i].id}, special),
+                    cur_p->data[i].p
+                });
+                // break if we have all the necessary data
+                if (result.probs.size() == n_probs && found_sampled_tok) {
```
Comment (ggerganov) [inline examples/server/server.cpp:1979]: This seems incorrect - if the sampled token is from the tail of the distribution, we will never break here.

**Review by ggerganov — APPROVED** [review]

File: examples/server/server.cpp (hunk 6 above)
Comment (ngxson) [reply examples/server/server.cpp:1979]: Hmm yeah it's quite messy to do every thing in one loop. I think it's better to split this into 2 different loops, and then optimize the one that take the prob of sampled token later on (in another PR)

**Review by ggerganov — APPROVED** [review]

**Comment by CyberShadow** [comment]
This pull request introduced a regression: https://github.com/ggerganov/llama.cpp/issues/11728

@ngxson Hi, could you please have a look?
