### PR TITLE
llama : fix empty ring buffer push

### LINKED ISSUE #9356: Bug: llama-server crashing after refactor sampling v2 pull
### What happened?

llama-server crashes after prompt processing, issue doesn't occur before https://github.com/ggerganov/llama.cpp/commit/df270ef74596da8f1178f08991f4c51f18c9ee82 
At first I thought the commit added some memory overhead, so I tried a smaller model, but same thing happens. As you can see in the log below the program crashes with no error or any message of sorts, just quits instantly. Tried building clean just in case but no dice.

Compiled with cuda 12.6.02.

### Name and Version

PS F:\llama.cpp\build\bin\Release> .\llama-cli.exe --version
version: 3681 (df270ef7)
built with MSVC 19.41.34120.0 for x64

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
F:\llama.cpp>build\bin\Release\llama-server.exe -m "models\Rocinante-12B-v1-Q8_0.gguf" -t 6 -ngl 31 -ctk q8_0 -ctv q8_0 -fa --no-mmap -c 8192
INFO [                    main] build info | tid="14168" timestamp=1725733099 build=3681 commit="df270ef7"
INFO [                    main] system info | tid="14168" timestamp=1725733099 n_threads=6 n_threads_batch=6 total_threads=12 system_info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | "
INFO [                    main] HTTP server is listening | tid="14168" timestamp=1725733099 hostname="127.0.0.1" port="8080" n_threads_http="11"
INFO [                    main] loading model | tid="14168" timestamp=1725733099 hostname="127.0.0.1" port="8080" n_threads_http="11"
llama_model_loader: loaded meta data with 39 key-value pairs and 363 tensors from models\Rocinante-12B-v1-Q8_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Rocinante 12B V1A
llama_model_loader: - kv   3:                       general.organization str              = BeaverAI
llama_model_loader: - kv   4:                           general.finetune str              = v1a
llama_model_loader: - kv   5:                           general.basename str              = Rocinante
llama_model_loader: - kv   6:                         general.size_label str              = 12B
llama_model_loader: - kv   7:                   general.base_model.count u32              = 1
llama_model_loader: - kv   8:                  general.base_model.0.name str              = Rocinante 12B V1A
llama_model_loader: - kv   9:          general.base_model.0.organization str              = BeaverAI
llama_model_loader: - kv  10:              general.base_model.0.repo_url str              = https://huggingface.co/BeaverAI/Rocin...
llama_model_loader: - kv  11:                               general.tags arr[str,2]       = ["axolotl", "generated_from_trainer"]
llama_model_loader: - kv  12:                          llama.block_count u32              = 40
llama_model_loader: - kv  13:                       llama.context_length u32              = 1024000
llama_model_loader: - kv  14:                     llama.embedding_length u32              = 5120
llama_model_loader: - kv  15:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv  16:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv  17:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv  18:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  19:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  20:                 llama.attention.key_length u32              = 128
llama_model_loader: - kv  21:               llama.attention.value_length u32              = 128
llama_model_loader: - kv  22:                          general.file_type u32              = 7
llama_model_loader: - kv  23:                           llama.vocab_size u32              = 131072
llama_model_loader: - kv  24:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  25:            tokenizer.ggml.add_space_prefix bool             = false
llama_model_loader: - kv  26:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  27:                         tokenizer.ggml.pre str              = tekken
llama_model_loader: - kv  28:                      tokenizer.ggml.tokens arr[str,131072]  = ["<unk>", "<s>", "</s>", "[INST]", "[...
llama_model_loader: - kv  29:                  tokenizer.ggml.token_type arr[i32,131072]  = [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...
llama_model_loader: - kv  30:                      tokenizer.ggml.merges arr[str,269443]  = ["─á ─á", "─á t", "e r", "i n", "─á ─...
llama_model_loader: - kv  31:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  32:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  33:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  34:            tokenizer.ggml.padding_token_id u32              = 10
llama_model_loader: - kv  35:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  36:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  37:                    tokenizer.chat_template str              = {%- if messages[0]["role"] == "system...
llama_model_loader: - kv  38:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   81 tensors
llama_model_loader: - type q8_0:  282 tensors
llm_load_vocab: special tokens cache size = 1000
llm_load_vocab: token to piece cache size = 0.8498 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 131072
llm_load_print_meta: n_merges         = 269443
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 1024000
llm_load_print_meta: n_embd           = 5120
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 1024000
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 13B
llm_load_print_meta: model ftype      = Q8_0
llm_load_print_meta: model params     = 12.25 B
llm_load_print_meta: model size       = 12.12 GiB (8.50 BPW)
llm_load_print_meta: general.name     = Rocinante 12B V1A
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 10 '<pad>'
llm_load_print_meta: LF token         = 1196 '├ä'
llm_load_print_meta: max token length = 150
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: yes
llm_load_tensors: ggml ctx size =    0.34 MiB
llm_load_tensors: offloading 31 repeating layers to GPU
llm_load_tensors: offloaded 31/41 layers to GPU
llm_load_tensors:  CUDA_Host buffer size =  3846.62 MiB
llm_load_tensors:      CUDA0 buffer size =  8564.96 MiB
............................................................................................
llama_new_context_with_model: n_ctx      = 8192
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 1
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =   153.00 MiB
llama_kv_cache_init:      CUDA0 KV buffer size =   527.00 MiB
llama_new_context_with_model: KV self size  =  680.00 MiB, K (q8_0):  340.00 MiB, V (q8_0):  340.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     1.00 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   946.00 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    26.01 MiB
llama_new_context_with_model: graph nodes  = 1127
llama_new_context_with_model: graph splits = 103
INFO [                    init] initializing slots | tid="14168" timestamp=1725733102 n_slots=1
INFO [                    init] new slot | tid="14168" timestamp=1725733102 id_slot=0 n_ctx_slot=8192
INFO [                    main] model loaded | tid="14168" timestamp=1725733102
INFO [                    main] chat template | tid="14168" timestamp=1725733102 chat_example="[INST] You are a helpful assistant\nHello [/INST]Hi there</s>[INST] How are you? [/INST]" built_in=true
INFO [            update_slots] all slots are idle | tid="14168" timestamp=1725733102
INFO [   launch_slot_with_task] slot is processing task | tid="14168" timestamp=1725733107 id_slot=0 id_task=0
INFO [            update_slots] kv cache rm [p0, end) | tid="14168" timestamp=1725733107 id_slot=0 id_task=0 p0=0
```

### PR DESCRIPTION
**Pull request by ggerganov**
fix #9356
cont #9294 

Pushing to 0-sized ring buffer caused division by zero

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [ ] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

File: src/llama-sampling.cpp [hunk 1]
```diff
@@ -1226,7 +1226,9 @@ static struct llama_sampler_i llama_sampler_penalties_i = {
     /* .name   = */ [](const struct llama_sampler * /*smpl*/) { return "penalties"; },
     /* .accept = */ [](struct llama_sampler * smpl, llama_token token) {
         auto * ctx = (llama_sampler_penalties *) smpl->ctx;
-        ctx->prev.push_back(token);
+        if (ctx->prev.size()) {
+            ctx->prev.push_back(token);
+        }
```
Comment (slaren) [inline src/llama-sampling.cpp:1231]: I think this is not correct, it should check the capacity rather than the size (which will always be zero unless something is pushed). I will push a fix later, but at the moment this sampler is probably broken.

Comment (ggerganov) [reply src/llama-sampling.cpp:1231]: Ah yes. It should check the capacity
