### PR TITLE
llama : add check for KV cache shifts

### LINKED ISSUE #10380: Deepseek2 does not support K-shift Denial-of-Service vulnerability
Long prompts/responses crash llama-server because "Deepseek2 does not support K-shift". For long prompts/responses, llama-server should return an error message or truncate the response, but instead, `GGML_ABORT` is called, which crashes the server. I believe that this is a Denial-of-Service vulnerability. A client should **never** be able to trigger `GGML_ABORT`.

The relevant line in the code is here:

https://github.com/ggerganov/llama.cpp/blob/9b75f03cd2ec9cc482084049d87a0f08f9f01517/src/llama.cpp#L18032

I have reported this security vulnerability almost three months ago [here (link only visible for maintainers),](https://github.com/ggerganov/llama.cpp/security/advisories/GHSA-jp78-gmv4-cc44) but have received no response and it is public knowledge now anyway, so I also opened this issue to increase visibility.

### Discussed in https://github.com/ggerganov/llama.cpp/discussions/9092

<div type='discussions-op-text'>

<sup>Originally posted by **99991** August 19, 2024</sup>
It is my understanding that llama.cpp shifts the key-value cache when generating more tokens than fit into the context window, which is not supported for DeepSeek Coder V2. To reproduce, start a server with [this model](https://huggingface.co/bartowski/DeepSeek-Coder-V2-Lite-Instruct-GGUF)

```bash
./llama-server -m DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf -c 32 -ngl 999 --port 8080
```

and then request a prompt completion:

```
curl -H "Content-Type: application/json" --request POST --data '{"prompt": "Mergesort in Python:", "n_predict": 32}' http://127.0.0.1:8080/completion
```

This should trigger the error

```
src/llama.cpp:15646: Deepseek2 does not support K-shift
Aborted
```

with llama.cpp [release b3600](https://github.com/ggerganov/llama.cpp/releases/tag/b3600).

The corresponding code in llama.cpp is here:

https://github.com/ggerganov/llama.cpp/blob/cfac111e2b3953cdb6b0126e67a2487687646971/src/llama.cpp#L15643C31-L15648C1

I believe that a saner approach would simply stop generating tokens instead of crashing the server. Is there some option that can be set to prevent clients from crashing the server?</div>

### PR DESCRIPTION
**Pull request by ggerganov**
fix #10380 

Disallow context shifts for models that do not support it (such as DeepSeek V2). Add 

```c
bool llama_kv_cache_can_shift(struct llama_context * ctx);
```

### CODE REVIEW

**Review by danbev — APPROVED** [review]

File: src/llama.cpp [hunk 1]
```diff
@@ -20462,6 +20462,10 @@ void llama_kv_cache_update(struct llama_context * ctx) {
     llama_kv_cache_update_internal(*ctx);
 }
 
+bool llama_kv_cache_can_shift(struct llama_context * ctx) {
+    return ctx->model.arch != LLM_ARCH_DEEPSEEK2; // not supported due to MLA
+}
```
Comment (slaren) [inline src/llama.cpp:20467]: Should this return false for recurrent models as well? Not sure what's the logic there, but `llama_kv_cache_update_internal` silently ignores models with `LLAMA_ROPE_TYPE_NONE`.

Comment (ggerganov) [reply src/llama.cpp:20467]: Yes, it's likely needed to return false for recurrent models.

The reason to do nothing in `llama_kv_cache_update_internal` when the rope type is none is because when we apply shifts to the KV cache using functions like `llama_kv_cache_seq_add()`, we do 2 things:

- Update the positions of the KV cells - i.e. just modify the meta data in `llama_kv_cell`
- Re-rope the data in the KV cells

The later step is necessary only if the data is roped. For ALiBi models for example, we should not apply this second step, but in theory we still support "shifting" the KV cache for those models, since the positional information is in the KQ mask.
