### PR TITLE
server : implement cancellable request

### LINKED ISSUE #9273: Bug: (Server) Cannot properly cancel a non-stream completion request
### What happened?

When using server completions (or chat completions) **without** stream, it is impossible to cancel the request midway.

## To reproduce the problem

1. Compile and run the server (any version), run with `--verbose` argument.
2. `curl -X POST http://localhost:8080/completion -vvv -d '{"prompt": "hi", "stream": false, "n_predict": 1000}'`
3. While it's still running, hit Ctrl+C to cancel the curl request
4. The server will still process the completion without being interrupted

Retry with `"stream": true`, now you will be able to interrupt the completion.

## Investigation

This is due to the fact that httplib is a blocking HTTP library, so there is no "client disconnect" event.

For non-stream API, our implementation is:

https://github.com/ggerganov/llama.cpp/blob/c6d4cb46559b359d2682cf2a002e7fe01bb7a767/examples/server/server.cpp#L2971-L2979

The problem is that, `.recv(id_task);` will block the current thread, so there is no way to detect the disconnect event.

For stream API, `.recv(id_task);` resume the thread on each predicted token. If `sink.write` returns false, we know that the client has been disconnected. Although this is not a real-time event, it still works well enough:

https://github.com/ggerganov/llama.cpp/blob/c6d4cb46559b359d2682cf2a002e7fe01bb7a767/examples/server/server.cpp#L2994-L2997

## Possible fix

The patchy way to fix is to unblock `.recv(id_task);` periodically, maybe via a watchdog or simply add a timeout to `.recv()`

Another way is to introduce in the upstream httplib a function to handle client disconnect. However, this maybe complicated since the event can't be delivered in the same thread handling the request (it's already blocked by `.recv()`)

The final way is to move away from blocking HTTP implementation. New libraries like `nodepp` does offer a simple way to use async/await, but with the risk of making the compilation process more complicated.

### Name and Version

(happens on all versions)

### What operating system are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ngxson**
Close https://github.com/ggerganov/llama.cpp/issues/9273

Related to https://github.com/yhirose/cpp-httplib/pull/2022

For requests that can take long time like completions or embeddings, the queue will unblock HTTP thread every 1 second to check for the status of HTTP connection.

Because this is done at HTTP thread, it will not affect the performance of inference thread, while still maintaining thread-safety requirement.

### CODE REVIEW

File: examples/server/server.cpp [hunk 1]
```diff
@@ -2322,10 +2349,21 @@ struct server_context {
...
-            server_task_result_ptr result = queue_results.recv(id_tasks);
+            server_task_result_ptr result = queue_results.recv_with_timeout(id_tasks, HTTP_POLLING_SECONDS);
+
+            if (is_connection_closed()) {
+                cancel_tasks(id_tasks);
+                return;
+            }
+
+            if (result == nullptr) {
+                i--; // retry
```
Comment (ggerganov) [inline examples/server/server.cpp:2364]: For `i == 0` this will underflow

**Review by ggerganov — APPROVED** [review]

File: examples/server/server.cpp (hunk 1 above)
Comment (ngxson) [reply examples/server/server.cpp:2364]: It will be `i++` as soon as we call `continue` anyway, so should not be a big problem. But anw I changed `i` to `int`, to be more explicit about the case where it can be negative.

(Also, `i` is not used anywhere inside the loop body, so I assume that it's safe to make it an `int` here)
