### PR TITLE
server : fix crash when using verbose output with input tokens that are not in printable range (#12178)

### LINKED ISSUE #12178: Misc. bug: Denial of Service (crash) when using verbose output with input tokens that are not in printable range.
### Name and Version

~/git/llama.cpp/build/bin/ [tags/b4798] ./llama-cli --version
register_backend: registered backend Metal (1 devices)
register_device: registered device Metal (Apple M3 Pro)
register_backend: registered backend BLAS (1 devices)
register_device: registered device BLAS (Accelerate)
register_backend: registered backend CPU (1 devices)
register_device: registered device CPU (Apple M3 Pro)
version: 4798 (1782cdfe)
built with Apple clang version 16.0.0 (clang-1600.0.26.6) for arm64-apple-darwin24.3.0

### Operating systems

_No response_

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
# Run the latest tag inside container
docker run --rm -it ubuntu
apt update
apt install -y wget unzip curl build-essential
wget https://github.com/ggml-org/llama.cpp/releases/download/b4798/llama-b4798-bin-ubuntu-arm64.zip
unzip llama-b4798-bin-ubuntu-arm64.zip

# Run the server
LD_LIBRARY_PATH=$(pwd)/build/bin ./build/bin/llama-server -m /tmp/DeepSeek-R1-Distill-Qwen-1.5B-Q8_0.gguf -v

# Crash the server
curl -vvvv http://localhost:8080/v1/completions -d '{"prompt":[-1]}'
```

### Problem description & steps to reproduce

# Summary
An unhandled exception crashes the server in the "v1/completions" route, if the server is running in verbose mode. An attacker can send a completion request with tokens that are not in the vocabulary / out of range, which crashes the application.

I opened an issue per your request, after closing https://github.com/ggml-org/llama.cpp/security/advisories/GHSA-9fg6-6f9w-fgj3

## Details
I recently ran into an unintended crash that can be triggered by anyone, using a single HTTP request, causing denial of service. I affects both Debug and Release builds and depends on the -v flag.

## PoC
I verified the POC on 2 different OSs (Linux, MacOS) and architectures (QWEN, LLAMA). I tested it on ubuntu container and on my host (up to date M3). I tested both compiling from source but here I will use the prebuilt binaries.

Download and Run the latest llama server build with -v flag:
```
docker run --rm -it ubuntu
apt update
apt install -y wget unzip curl build-essential
wget https://github.com/ggml-org/llama.cpp/releases/download/b4798/llama-b4798-bin-ubuntu-arm64.zip
unzip llama-b4798-bin-ubuntu-arm64.zip
```

# Modify the model path, I copied it with docker cp
```
LD_LIBRARY_PATH=$(pwd)/build/bin ./build/bin/llama-server -m /tmp/DeepSeek-R1-Distill-Qwen-1.5B-Q8_0.gguf -v
```
The following line will infer 2 tokens successfully to make sure the model works first:
```
curl -vvvv http://localhost:8080/v1/completions -d '{"prompt":[1], "max_tokens": 2}'
```
The following line will crash the application, which demonstrated the denial of service vulnerability by triggering uncaught exception:
```
curl -vvvv http://localhost:8080/v1/completions -d '{"prompt":[-1]}'
```
The server crashes with due to out of range error (no token mapped for the value -1) when it tries to print it to STDOUT.
```
que          post: new task, id = 56/1, front = 0
que    start_loop: processing new tasks
que    start_loop: processing task, id = 56
slot get_availabl: id  0 | task 0 | selected slot by lru, t_last = 43778350372
slot        reset: id  0 | task 0 |
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 151936)
Aborted
```

## Impact
Any server running llama.cpp in verbose mode is subject to DOS using a single HTTP request.

## Suggested behavior (opinion)
When receiving tokens as a list of integers, the server should make sure the tokens are supported in the current vocab / tokenizer. Validating every input just for verbose logging does not make sense and can be IO expensive, which is an overkill.
But, on the other hand, the user should get a clear error when invalid tokens / unsupported tokens are provided, whether or not the server runs in verbose mode. It might also skip tokens that are not known when printing them by checking the value has a mapping and is in the supported range.

Thanks in advance!

### First Bad Commit

_No response_

### Relevant log output

```shell
que          post: new task, id = 56/1, front = 0
que    start_loop: processing new tasks
que    start_loop: processing task, id = 56
slot get_availabl: id  0 | task 0 | selected slot by lru, t_last = 43778350372
slot        reset: id  0 | task 0 |
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 151936)
Aborted
```

### PR DESCRIPTION
**Pull request by ishaangandhi**
This PR fixes https://github.com/ggml-org/llama.cpp/issues/12178.

Previously, when calling `/completions` with a token outside of the token vocabulary range, you would get this exception:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 151936)
```

Now, the server continues to run, and the user gets a useful error:
```
{"error":{"code":400,"message":"Prompt contains invalid tokens","type":"invalid_request_error"}}%                     
```

### CODE REVIEW

File: common/common.cpp [hunk 1]
```diff
@@ -1748,6 +1748,12 @@ std::string common_token_to_piece(const struct llama_vocab * vocab, llama_token
     return piece;
 }
 
+bool can_be_detokenized(const struct llama_context * ctx, const std::vector<llama_token> & tokens) {
```
Comment (ngxson) [inline common/common.cpp:1751]: I don't think we should add a new API `can_detokenize` in `llama.h/common.h`

The simple solution is to check if a given token is within vocab before calling `common_token_to_piece`

Something like this:

```cpp
const int n_vocab = llama_vocab_n_tokens(vocab);
if (token >= n_vocab) {
  throw std::runtime_error("invalid token");
}
```

Comment (ishaangandhi) [reply common/common.cpp]: I think the runtime_error won't be caught, which will still leave the DOS.

I removed the new API from llama.h and common.h, and instead made a function local to server.cpp with this line:
```
const int n_vocab = llama_vocab_n_tokens(vocab);
```

File: examples/server/server.cpp [hunk 2]
```diff
@@ -2040,6 +2040,18 @@ struct server_context {
         return ret;
     }
 
+    bool can_be_detokenized(const struct llama_context * ctx, const std::vector<llama_token> & tokens) {
+        const llama_model * model = llama_get_model(ctx);
+        const llama_vocab * vocab = llama_model_get_vocab(model);
+        const int32_t n_vocab = llama_vocab_n_tokens(vocab);
+        for (const auto& token : tokens) {
```
Comment (ngxson) [inline examples/server/server.cpp:2047]:
```suggestion
        for (const auto & token : tokens) {
```

**Review by ngxson — APPROVED** [review]
Bonus: would be nice if you can add a test case for it, see `server/tests/test_tokenize.py`

**Comment by ishaangandhi** [comment]
@ngxson are you OK to merge this? I rebased the changes.

re: adding a test - I think `test_tokenize` tests the `/tokenize` and `/detokenize` endpoints, which invoke a different path than what we fix in this PR.

How about we merge this as-is?

**Comment by ngxson** [comment]
I only refer to that file so you can see how the code looks like. Adding test should be easy and it is a good way to show that your code actually work.
