### PR TITLE
[SYCL] Fix Q8_0 reorder: garbage on 2nd prompt + crash on full VRAM

### LINKED ISSUE #21589: Eval bug: SYCL: Qwen3.5 spitting garbage on the second prompt
### Name and Version

```
root@cb8f619a68ce:/app# ./llama-cli --version
load_backend: loaded SYCL backend from /app/libggml-sycl.so
load_backend: loaded CPU backend from /app/libggml-cpu-haswell.so
version: 8699 (4eb19514d)
built with IntelLLVM 2025.3.2 for Linux x86_64
```

### Operating systems

Linux

### GGML backends

SYCL

### Hardware

Ryzen 7 5700X3D + B580

### Models

Any Qwen3.5 that is not F16 or BF16

### Problem description & steps to reproduce

Just send two prompts and watch the second one being responded with garbage

### First Bad Commit

_No response_

### Relevant log output

<details>
<summary>Logs</summary>

```console
root@cb8f619a68ce:/app# ./llama-cli --model /models/Qwen3.5-35B-A3B-Q4_K_M.gguf
load_backend: loaded SYCL backend from /app/libggml-sycl.so
load_backend: loaded CPU backend from /app/libggml-cpu-haswell.so

Loading model...  


▄▄ ▄▄
██ ██
██ ██  ▀▀█▄ ███▄███▄  ▀▀█▄    ▄████ ████▄ ████▄
██ ██ ▄█▀██ ██ ██ ██ ▄█▀██    ██    ██ ██ ██ ██
██ ██ ▀█▄██ ██ ██ ██ ▀█▄██ ██ ▀████ ████▀ ████▀
                                    ██    ██
                                    ▀▀    ▀▀

build      : b8699-4eb19514d
model      : Qwen3.5-35B-A3B-Q4_K_M.gguf
modalities : text

available commands:
  /exit or Ctrl+C     stop or exit
  /regen              regenerate the last response
  /clear              clear the chat history
  /read <file>        add a text file
  /glob <pattern>     add text files using globbing pattern


> hi

[Start thinking]
Thinking Process:

1.  **Analyze the Request:**
    *   Input: "hi"
    *   Intent: Greeting.
    *   Context: Start of a conversation.
    *   Tone: Friendly, helpful, casual.

2.  **Determine the appropriate response:**
    *   Acknowledge the greeting.
    *   Offer assistance.
    *   Keep it concise but warm.

3.  **Draft potential responses:**
    *   "Hello! How can I help you today?"
    *   "Hi there! What's on your mind?"
    *   "Hello! Nice to meet you. How are you doing?"
    *   "Hi! 👋 Need any help with something specific?"

4.  **Select the best option:** A combination of friendly greeting and offer of help is standard and effective. "Hello! How can I help you today?" is clear and professional yet friendly. Adding an emoji can make it warmer.

5.  **Final Polish:** "Hello! 👋 How can I help you today?" or "Hi there! How's it going? What can I do for you?" Let's go with a simple, welcoming response.

6.  **Final Output Generation:** (Matches the selected draft)
    "Hello! 👋 How can I help you today?" or similar.

    *Self-Correction during thought process:* Keep it natural. Don't overthink a simple "hi".

    *Final Decision:* "Hello! 👋 How can I help you today?" or "Hi there! How's it going?" Let's use a friendly greeting + offer help.

    "Hello! 👋 How can I assist you today?" (Professional yet friendly)
    "Hi! How's it going? Anything I can help you with?" (More casual)

    Let's go with: "Hello! 👋 How can I help you today?" (Balanced)

    *Wait, checking system instructions:* I am an AI assistant. I should be helpful.

    *Revised Plan:* Just say hi back and ask how to help.

    *Final Output:* "Hello! 👋 How can I help you today?" or "Hi there! What can I do for you?"

    Let's pick: "Hello! 👋 How can I help you today?" (Simple and effective).

    *Wait, one more consideration:* Sometimes users just want to chat. So "How are you?" is also good.
    "Hi there! How's it going? Is there something specific you'd like to talk about or work on?"

    Let's keep it open-ended but inviting.

    "Hello! 👋 How's it going? Is there anything I can help you with today?"

    Actually, brevity is often better for a "hi".
    "Hi there! 👋 How can I help you today?"

    Okay, ready to output.cw

[End thinking]

Hello! 👋 How's it going? Is there anything I can help you with today?

[ Prompt: 48.2 t/s | Generation: 28.1 t/s ]

> hi

[Start thinking]
-s55=G,G9+125H89-*C"2@'8+=H53CAG%&4H8E<>6'<<.%F."4-<"-B)G1E8/'8+%D*@/2!F7>*C1DD2,(4=)CF;*E;D<CA6AHGA;F(HH<+&$&0GF+4H@'(C0>!%G55:,$E2GB2$'6=9,:,#"/E3G':+$+BBE+5C7B24.4E+-:6$>/E)F,:D63)F(19>AGB(4:88;C/&$5H$68C+50&56:<:!(":<D2A*<0H1&<G4.1E*0HF!4@A9/(BFG1G>!/!7/A#'-*CB,7:60;H"72+;6';#$$(#C#1:4E-*5'#&E)+E!72B6*,$5.G.6$*-H#F!2=:E.E09=!;#$>ABA,2:2G'HE;</)@=-#=*&@C'5DHHE:!5&/+&+))6$F(@-G,/H7/1;%E>$EB(7>#0+D=-C;@<<E,B=7-8#"G2+9DG($<!<*0.<''@&$'5B76"B-9*>8H@CH0C1+H6>7)E9;<A6&<;8(83(!%@15B,8-FEB87=3CG,#4+8>$$&:7H+91&6!F2%DF8>9+8D-88)-)>*!.*6-$!D#4HC4>&>DH7FA:9:&-186-,9&%C&;='/4E>E!7.C3"5%5<'5CEC=*;"!H"'+6%%/<3/>,>2*7='5<*E+,!G@AD4@5H"B2<C,AGBH9G"(#%1E,$6*

[ Prompt: 51.1 t/s | Generation: 29.1 t/s ]

> 

Exiting...
llama_memory_breakdown_print: | memory breakdown [MiB]                     | total   free     self   model   context   compute    unaccounted |
llama_memory_breakdown_print: |   - SYCL0 (Intel(R) Arc(TM) B580 Graphics) | 12216 = 1023 + (10922 = 10282 +     142 +     497) +         270 |
llama_memory_breakdown_print: |   - Host                                   |                 19830 = 19814 +       0 +      16                |
root@cb8f619a68ce:/app# 
```
</details>

### PR DESCRIPTION
**Pull request by PMZFX**
## Summary

Fixes two issues with the Q8_0 reorder optimization introduced in #21527.

**Bug 1: Garbage output from second prompt onward (#21589)**

The Q8_0 reorder optimization rearranges weight data during token generation (batch=1, via DMMV/MMVQ), but the general GEMM dequantization path used during prompt processing was missing a reorder-aware variant for Q8_0. After the first tg pass reordered the weights, subsequent prompt processing read them with the standard dequantizer, producing corrupt output.

Q4_0, Q4_K, and Q6_K already had `_reorder` dequantizers in `convert.cpp`. Q8_0 was missing them.

Fix: Add `dequantize_block_q8_0_reorder()` in `dequantize.hpp` and wire it into both `ggml_get_to_fp16_sycl()` and `ggml_get_to_fp32_sycl()` in `convert.cpp`.

**Bug 2: Crash when device memory is full**

The reorder functions allocate a temporary buffer the full size of the weight tensor via `sycl_ext_malloc_device()`. When VRAM is nearly full (large models on smaller cards), this returns NULL and the subsequent memcpy crashes.

Fix: Add a host memory fallback (`sycl::malloc_host`) when device allocation fails, and skip the reorder gracefully if both fail. The reorder flag is only set when the reorder actually succeeds.

Fixes #21589

## Testing

Tested on Intel Arc Pro B70 (Xe2 Battlemage), oneAPI DPC++ 2025.3.3:

- 5 sequential prompts on Qwen3.5-9B Q8_0 via llama-server: all coherent
- 5 sequential prompts on Qwen3.5-35B-A3B Q4_K_M (mixed quant with Q8_0 tensors): all coherent
- 3 sequential prompts on Qwen2.5-1.5B Q8_0: all coherent
- llama-bench confirms Q8_0 tg speedup is preserved (180 t/s)

Code was written with AI assistance (Claude), reviewed and tested by me on real hardware.

### CODE REVIEW

File: ggml/src/ggml-sycl/ggml-sycl.cpp [hunk 1]
```diff
@@ -3333,9 +3333,37 @@ static inline void sycl_ext_free(dpct::queue_ptr stream, void * ptr) {
     sycl::free(ptr, *stream);
 }
 
-static void reorder_qw_q4_0(uint8_t * data_device, const int ncols, const int nrows, size_t size, size_t offset,
+// Try device allocation first; if VRAM is full, fall back to host memory so the
+// reorder kernel can still run (reading over PCIe instead of device-local).
+static inline void * sycl_ext_malloc_with_fallback(dpct::queue_ptr stream, size_t size, bool & host_fallback) {
```
Comment (arthw) [inline ggml/src/ggml-sycl/ggml-sycl.cpp]: 1. device can access the host memory. 
This feature will be supported by Ubuntu 26 (new linux kernel).
I suggest to add the macro to limit this code to enable for new linux(kernel), avoid to impact the user of old linux.

2.host_fallback
Suggest defining a new class to handle the memory malloc and free, use host_fallback as internal member variable. simple the usage.

**Review by tunmaker — COMMENTED** [review]
just tested on intel Arc A380 qwen3.5 2b q8
works for both thinking on and off
17t/s

**Review by NeoZhangJianyu — APPROVED** [review]
OK, it's good job!

Thank you!

**Review by arthw — COMMENTED** [review]
Only one comment:
Please update the description of GGML_SYCL_HOST_MEM_FALLBACK in SYCL.md

**Review by arthw — APPROVED** [review]
It's good job!
The reorder of Q8_0 is attracting more attention. The issue is reported by several JIRAs.
This PR is fixed it quickly.

Additional suggestion:
 It's encouraged to make the PR focus on the special issue. It will make the updated code be less and easy to be reviewed and approved.

Thank you!

**Comment by DanStory** [comment]
tested on Intel Arc Pro B70 (x4)
:+1: `unsloth/Qwen3-Coder-Next-GGUF:Q8_0` 26.53 t/s
:+1: `unsloth/GLM-4.7-Flash-GGUF:Q8_0`  23.30 t/s
:+1: `unsloth/Qwen3.5-35B-A3B-GGUF:Q8_0` 31.81 t/s
:+1: `unsloth/gemma-4-31B-it-GGUF:Q8_0` 11.89 t/s

**Comment by arthw** [comment]
@ggerganov 
Could you review this PR?

Thank you!

**Comment by PMZFX** [comment]
Thanks for catching this! Investigated and fixed.

Added reorder-aware DMMV dequantizers for Q4_K. Also found and fixed the same gap in Q6_K while I was in there.

Tested on B70:
- `test-backend-ops -o MUL_MAT` passes for all 4 reorder types (q4_0, q8_0, q4_K, q6_K)
- Q4_K_M model (same one you tested): pp512 1039 t/s, tg128 58.5 t/s, multi-turn works
- Q6_K and Q8_0 benchmarks clean, no regressions

Could you retest with your Q4_K_M model when you get a chance?

**Comment by markussiebert** [comment]
Works great, hope to see this merged soon :-)

**Comment by arthw** [comment]
@ggerganov 
Please review and merge this PR!
It's important to fix bug and enhance!

Thank you!
