### PR TITLE
k-quants : fix build on armv7 (android only)

### LINKED ISSUE #2075: k-quant causes builds to fail on ARM32
# Expected Behavior

Build using `make`.

# Current Behavior

Build fails with error, but adding `LLAMA_NO_K_QUANTS=1` allows build to succeed.

# Environment and Context

* Commit `d7d2e6a0f0c74f7a570dae384dfff371ac744d2a`

* CPU Architecture
```
$ lscpu
Architecture:                    armv7l
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           4
Model name:                      Cortex-A53
Stepping:                        r0p4
CPU max MHz:                     1200.0000
CPU min MHz:                     600.0000
BogoMIPS:                        38.40
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           half thumb fastmult vfp edsp neon vfpv3 tls vfp
                                 v4 idiva idivt vfpd32 lpae evtstrm crc32
```

* Operating System: `Linux raspberrypi3 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux`

* SDK version:

```
$ python3 --version
Python 3.9.2
$ make --version
GNU Make 4.3
Built for arm-unknown-linux-gnueabihf
$ g++ --version
g++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
```
# Steps to Reproduce

1. `git clone https://github.com/ggerganov/llama.cpp`
2. `cd llama.cpp`
3. `make` (produces error)
4. `make clean && LLAMA_NO_K_QUANTS=1 make` (succeds)

# Failure Logs

```cpp
~/llama.cpp $ make
I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  unknown
I UNAME_M:  armv7l
I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -DGGML_USE_K_QUANTS -mfpu=neon-fp-armv8 -mfp16-format=ieee -mno-unaligned-access -funsafe-math-optimizations
I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_K_QUANTS
I LDFLAGS:  
I CC:       cc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
I CXX:      g++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110

(...)

g++ -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -DGGML_USE_K_QUANTS -c examples/common.cpp -o common.o
cc -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -DGGML_USE_K_QUANTS -mfpu=neon-fp-armv8 -mfp16-format=ieee -mno-unaligned-access -funsafe-math-optimizations   -c -o k_quants.o k_quants.c
k_quants.c: In function ‘ggml_vec_dot_q2_K_q8_K’:
k_quants.c:1272:36: warning: implicit declaration of function ‘vld1q_s16_x2’; did you mean ‘vld1q_s16’? [-Wimplicit-function-declaration]
 1272 |         const int16x8x2_t q8sums = vld1q_s16_x2(y[i].bsums);
      |                                    ^~~~~~~~~~~~
      |                                    vld1q_s16
k_quants.c:1272:36: error: invalid initializer
k_quants.c:1273:36: warning: missing braces around initializer [-Wmissing-braces]
 1273 |         const int16x8x2_t mins16 = {vreinterpretq_s16_u16(vmovl_u8(vget_low_u8(mins))), vreinterpretq_s16_u16(vmovl_u8(vget_high_u8(mins)))};
      |                                    ^
      |                                     {                                                                                                      }
k_quants.c:1278:23: warning: implicit declaration of function ‘vaddvq_s32’; did you mean ‘vaddq_s32’? [-Wimplicit-function-declaration]
 1278 |         sum += dmin * vaddvq_s32(vaddq_s32(s0, s1));
      |                       ^~~~~~~~~~
      |                       vaddq_s32
k_quants.c:1309:41: warning: implicit declaration of function ‘vld1q_u8_x2’; did you mean ‘vld1q_u32’? [-Wimplicit-function-declaration]
 1309 |             const uint8x16x2_t q2bits = vld1q_u8_x2(q2); q2 += 32;
      |                                         ^~~~~~~~~~~
      |                                         vld1q_u32
k_quants.c:1309:41: error: invalid initializer
k_quants.c:1311:35: warning: implicit declaration of function ‘vld1q_s8_x2’; did you mean ‘vld1q_s32’? [-Wimplicit-function-declaration]
 1311 |             int8x16x2_t q8bytes = vld1q_s8_x2(q8); q8 += 32;
      |                                   ^~~~~~~~~~~
      |                                   vld1q_s32
k_quants.c:1311:35: error: invalid initializer
k_quants.c:1296:13: warning: implicit declaration of function ‘vaddvq_s16’; did you mean ‘vaddq_s16’? [-Wimplicit-function-declaration]
 1296 |     isum += vaddvq_s16(p1) * aux[is+(index)] + vaddvq_s16(p2) * aux[is+1+(index)];\
      |             ^~~~~~~~~~
k_quants.c:1314:13: note: in expansion of macro ‘MULTIPLY_ACCUM_WITH_SCALE’
 1314 |             MULTIPLY_ACCUM_WITH_SCALE(0);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
k_quants.c:1301:19: error: incompatible types when assigning to type ‘int8x16x2_t’ from type ‘int’
 1301 |         q8bytes = vld1q_s8_x2(q8); q8 += 32;\
      |                   ^~~~~~~~~~~
k_quants.c:1316:13: note: in expansion of macro ‘SHIFT_MULTIPLY_ACCUM_WITH_SCALE’
 1316 |             SHIFT_MULTIPLY_ACCUM_WITH_SCALE(2, 2);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
k_quants.c:1301:19: error: incompatible types when assigning to type ‘int8x16x2_t’ from type ‘int’
 1301 |         q8bytes = vld1q_s8_x2(q8); q8 += 32;\
      |                   ^~~~~~~~~~~
k_quants.c:1318:13: note: in expansion of macro ‘SHIFT_MULTIPLY_ACCUM_WITH_SCALE’
 1318 |             SHIFT_MULTIPLY_ACCUM_WITH_SCALE(4, 4);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
k_quants.c:1301:19: error: incompatible types when assigning to type ‘int8x16x2_t’ from type ‘int’
 1301 |         q8bytes = vld1q_s8_x2(q8); q8 += 32;\
      |                   ^~~~~~~~~~~
k_quants.c:1320:13: note: in expansion of macro ‘SHIFT_MULTIPLY_ACCUM_WITH_SCALE’
 1320 |             SHIFT_MULTIPLY_ACCUM_WITH_SCALE(6, 6);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
k_quants.c:1251:22: warning: unused variable ‘vzero’ [-Wunused-variable]
 1251 |     const int32x4_t  vzero = vdupq_n_s32(0);
      |                      ^~~~~
k_quants.c: In function ‘ggml_vec_dot_q3_K_q8_K’:
k_quants.c:1746:31: error: invalid initializer
 1746 |         uint8x16x2_t qhbits = vld1q_u8_x2(qh);
      |                               ^~~~~~~~~~~
k_quants.c:1764:41: error: invalid initializer
 1764 |             const uint8x16x2_t q3bits = vld1q_u8_x2(q3); q3 += 32;
      |                                         ^~~~~~~~~~~
k_quants.c:1765:43: warning: implicit declaration of function ‘vld1q_s8_x4’; did you mean ‘vld1q_s64’? [-Wimplicit-function-declaration]
 1765 |             const int8x16x4_t q8bytes_1 = vld1q_s8_x4(q8); q8 += 64;
      |                                           ^~~~~~~~~~~
      |                                           vld1q_s64
k_quants.c:1765:43: error: invalid initializer
k_quants.c:1766:43: error: invalid initializer
 1766 |             const int8x16x4_t q8bytes_2 = vld1q_s8_x4(q8); q8 += 64;
      |                                           ^~~~~~~~~~~
k_quants.c: In function ‘ggml_vec_dot_q4_K_q8_K’:
k_quants.c:2380:34: warning: implicit declaration of function ‘vpaddq_s16’; did you mean ‘vpaddlq_s16’? [-Wimplicit-function-declaration]
 2380 |         const int16x8_t q8sums = vpaddq_s16(vld1q_s16(y[i].bsums), vld1q_s16(y[i].bsums + 8));
      |                                  ^~~~~~~~~~
      |                                  vpaddlq_s16
k_quants.c:2380:34: error: incompatible types when initializing type ‘int16x8_t’ using type ‘int’
k_quants.c:2405:41: error: invalid initializer
 2405 |             const uint8x16x2_t q4bits = vld1q_u8_x2(q4); q4 += 32;
      |                                         ^~~~~~~~~~~
k_quants.c:2423:23: error: incompatible types when assigning to type ‘int8x16x2_t’ from type ‘int’
 2423 |             q8bytes = vld1q_s8_x2(q8); q8 += 32;
      |                       ^~~~~~~~~~~
k_quants.c:2432:23: error: incompatible types when assigning to type ‘int8x16x2_t’ from type ‘int’
 2432 |             q8bytes = vld1q_s8_x2(q8); q8 += 32;
      |                       ^~~~~~~~~~~
k_quants.c: In function ‘ggml_vec_dot_q5_K_q8_K’:
k_quants.c:2857:34: error: incompatible types when initializing type ‘int16x8_t’ using type ‘int’
 2857 |         const int16x8_t q8sums = vpaddq_s16(vld1q_s16(y[i].bsums), vld1q_s16(y[i].bsums + 8));
      |                                  ^~~~~~~~~~
k_quants.c:2878:31: error: invalid initializer
 2878 |         uint8x16x2_t qhbits = vld1q_u8_x2(qh);
      |                               ^~~~~~~~~~~
k_quants.c:2886:41: error: invalid initializer
 2886 |             const uint8x16x2_t q5bits = vld1q_u8_x2(q5); q5 += 32;
      |                                         ^~~~~~~~~~~
k_quants.c:2887:41: error: invalid initializer
 2887 |             const int8x16x4_t q8bytes = vld1q_s8_x4(q8); q8 += 64;
      |                                         ^~~~~~~~~~~
k_quants.c:2844:21: warning: unused variable ‘mzero’ [-Wunused-variable]
 2844 |     const int32x4_t mzero = vdupq_n_s32(0);
      |                     ^~~~~
k_quants.c: In function ‘ggml_vec_dot_q6_K_q8_K’:
k_quants.c:3370:36: error: invalid initializer
 3370 |         const int16x8x2_t q8sums = vld1q_s16_x2(y[i].bsums);
      |                                    ^~~~~~~~~~~~
k_quants.c:3372:38: warning: missing braces around initializer [-Wmissing-braces]
 3372 |         const int16x8x2_t q6scales = {vmovl_s8(vget_low_s8(scales)), vmovl_s8(vget_high_s8(scales))};
      |                                      ^
      |                                       {                                                            }
k_quants.c:3384:35: error: invalid initializer
 3384 |             uint8x16x2_t qhbits = vld1q_u8_x2(qh); qh += 32;
      |                                   ^~~~~~~~~~~
k_quants.c:3385:35: warning: implicit declaration of function ‘vld1q_u8_x4’; did you mean ‘vld1q_u64’? [-Wimplicit-function-declaration]
 3385 |             uint8x16x4_t q6bits = vld1q_u8_x4(q6); q6 += 64;
      |                                   ^~~~~~~~~~~
      |                                   vld1q_u64
k_quants.c:3385:35: error: invalid initializer
k_quants.c:3386:35: error: invalid initializer
 3386 |             int8x16x4_t q8bytes = vld1q_s8_x4(q8); q8 += 64;
      |                                   ^~~~~~~~~~~
k_quants.c:3429:23: error: incompatible types when assigning to type ‘int8x16x4_t’ from type ‘int’
 3429 |             q8bytes = vld1q_s8_x4(q8); q8 += 64;
      |                       ^~~~~~~~~~~
k_quants.c:3352:22: warning: unused variable ‘vzero’ [-Wunused-variable]
 3352 |     const int32x4_t  vzero = vdupq_n_s32(0);
      |                      ^~~~~
make: *** [<builtin>: k_quants.o] Error 1
```

### PR DESCRIPTION
**Pull request by jhen0409**
~~Fix #2075.~~ (No, see https://github.com/ggerganov/llama.cpp/pull/2920#issuecomment-1702372923)

Add the missing methods if not defined `__aarch64__`. Except  `vpaddq_s16`, others are from `ggml.c`.

Tested the build on Android armeabi-v7a.

I don't have a device and a small qk model to test at the moment, so I only tested the functions by remove `__aarch64__` def + rename functions on a M2 Mac.

### CODE REVIEW

**Comment by Cebtenzzre** [comment]
Ugh, code duplication is annoying. I would like if we made a header file to put all of our shared inline functions into, so we don't have to copy-paste them around.

I have a few devices I might be able to get an armv7 toolchain to run on.

**Comment by jhen0409** [comment]
> Ugh, code duplication is annoying. I would like if we made a header file to put all of our shared inline functions into, so we don't have to copy-paste them around.
> 

I also found some unused functions we can cleanup in ggml.c, then we only have duplicated `vaddvq_s32` for now. Maybe it's not worth enough to have a header file for now.

> I have a few devices I might be able to get an armv7 toolchain to run on.

Thanks!

**Review by ikawrakow — APPROVED** [review]

**Comment by Cebtenzzre** [comment]
I get this error compiling on my BeagleBone White, running Arch Linux ARM:
```
In file included from llama.h:4,                                                                                               
                 from llama.cpp:6:                                                                                             
ggml.h:274:13: error: ‘__fp16’ does not name a type; did you mean ‘__bf16’?                                                    
  274 |     typedef __fp16 ggml_fp16_t;                                                                                        
      |             ^~~~~~                                                                                                     
      |             __bf16
```

Compiler is `gcc (GCC) 12.1.0` targeting `armv7l-unknown-linux-gnueabihf`.

**Comment by jhen0409** [comment]
> For each of vld1q_s16_x2, vld1q_u8_x2, vld1q_s8_x2, vld1q_s8_x4, and vld1q_u8_x4. Also a few unused variables: vzero on k_quants.c lines 1329 and 3683 and mzero on line 3119.

Looks like these methods are not in list of [arm/arm_neon.h](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/arm/arm_neon.h) in gcc, but Arm [mentioned](https://developer.arm.com/architectures/instruction-sets/intrinsics/vld1q_s16_x2) these support v7. It might be a issue related to toolchain.

I think this PR is not fully fixed for #2075, and can confirm it fixed the build of Android armeabi-v7a.

**Comment by Cebtenzzre** [comment]
You say "Android only", but the original issue reporter is running Raspbian, a Debian derivative.

I'll try clang as well, and if that doesn't work I have an armv7 Moto X 2014 that's a few years newer.

**Comment by Cebtenzzre** [comment]
@slaren 32-bit platforms are currently broken - just try replacing `-march=native -mtune=native` with `-m32` in the Makefile, and running the 'main' example to generate some text.

**Comment by slaren** [comment]
@Cebtenzzre as you probably noticed, `ggml-alloc` assumes a 64-bit address space. Is that the only issue currently preventing 32-bit builds?

**Comment by Cebtenzzre** [comment]
> Is that the only issue currently preventing 32-bit builds?

Apparently not, unless I need to try a smaller model. I get this with commit 11f3ca06b8c66b0427aab0a472479da22553b472:
```
error loading model: overflow multiplying 268800 * 32000
```

**Comment by Cebtenzzre** [comment]
@slaren after figuring out how LLAMA_QKK_64 works, and replacing size_t with uint64_t in llama_calc_tensor_size, I get reasonable output from a 32-bit build on x86 with commit 11f3ca06b8c66b0427aab0a472479da22553b472, which is right before ggml-alloc was introduced.

**Comment by jhen0409** [comment]
> You say "Android only", but the original issue reporter is running Raspbian, a Debian derivative.

Yeah I've update the description. I was found the issue on Android early, and found a related issue.

> 
> I'll try clang as well, and if that doesn't work I have an armv7 Moto X 2014 that's a few years newer.
> 
> **edit:** I was able to build successfully with clang. I still get the vzero/mzero warnings, along with a place where the allocator assumes pointers and size_t are 64 bits wide (they are 32 bits on this platform):
> 
> ```
> ggml-alloc.c:287:45: warning: implicit conversion from 'unsigned long long' to 'size_t' (aka 'unsigned int') changes value from 1099511627776 to 0 [-Wconstant-conversion]
> static const size_t MEASURE_MAX_SIZE  = 1ULL<<40; // 1 TB
>                     ~~~~~~~~~~~~~~~~    ~~~~^~~~
> ```
> 
> main fails with this error at runtime:
> 
> ```
> ggml_allocr_alloc: not enough space in the buffer (needed 2048, largest block available 0)
> GGML_ASSERT: ggml-alloc.c:144: !"not enough space in the buffer"
> ```

Thanks a lot! I also got a RPi 3B (1gb ram) with `uname -m: armv7l`, and use `-mcpu=cortex-a53` with clang, but it not able run the open-llama-3b q2_k even increased swap.

That works with a 110m llama2c model in q8_0, unfortunately I haven't been able to convert stories110m to a qk model even with QKK_64.

Also, use `(1ULL<<32) - 1` for `MEASURE_MAX_SIZE` is works to me, so I think we probably can use it for armv7. I'll leave 32-bit x86 as a TODO for now.

**Review by ggerganov — APPROVED** [review]

File: ggml-alloc.c [hunk 1]
```diff
@@ -284,7 +284,14 @@ struct ggml_allocr * ggml_allocr_new(void * data, size_t size, size_t alignment)
 // address and size of the buffer when measuring
 // it needs to be large enough to fit all the tensors, but it cannot overlap with other existing buffers
 static void * const MEASURE_BASE_ADDR = (void *) 0x1000;
+#if defined(__ARM_NEON) && !defined(__aarch64__)
+// 32-bit
+// TODO: Use for 32-bit x86 as well
+static const size_t MEASURE_MAX_SIZE  = (1ULL<<32) - 1; // 4 GB
+#else
```
Comment (slaren) [inline ggml-alloc.c:291]: I don't think that this is going to work for the reasons explained in the comment. `ggml-alloc` uses the address and size of the buffer to determine if a tensor was allocated by it, and that also applies when measuring. If you set the measure buffer to the entire address space, it will try to free and reuse the memory of external tensors such as the weights and the KV cache. I will work on a better solution.

**Comment by itsPreto** [comment]
@jhen0409 could you please tell me what the appropriate steps are to build for `armeabi-v7a`?

```bash
> mkdir build-android
> cd build-android
> export NDK=<your_ndk_directory>
> cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23 -DCMAKE_C_FLAGS=-march=armv8.4a+dotprod ..
> make
```

I tried [this approach here (#4421) ](https://github.com/ggerganov/llama.cpp/issues/4421)but it gave me build errors.
