### PR TITLE
kv-cache : pad the cache size to 256 for performance

### LINKED ISSUE #17037: Performance regression in prompt processing
I pulled master today and noticed my pp times have gotten worse.

I bisected the breaking commit to 85a7d8677bf2200981e52f744a21d5267964ffcf (#16812 )

About my system:

96GB DDR5-6000
pcie5 x16
rtx 5090
24/36 layers offloaded to the CPU

The commit before the breaking commit:

  ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 5090, compute capability 12.0, VMM: yes
| model                          |       size |     params | backend    | ngl | n_batch | n_ubatch | fa | mmap |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------: | -------: | -: | ---: | --------------: | -------------------: |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 |          pp4096 |      4095.21 ± 14.55 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 |  pp4096 @ d4096 |      3858.68 ± 45.20 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 |  pp4096 @ d8192 |      3682.09 ± 11.12 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 | pp4096 @ d16384 |      3338.96 ± 19.24 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 | pp4096 @ d20000 |      3219.27 ± 13.05 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 | pp4096 @ d32768 |      2818.29 ± 24.60 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 | pp4096 @ d65536 |      2125.18 ± 18.36 |

build: a8ca18b4b (6867)

The breaking commit:

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 5090, compute capability 12.0, VMM: yes
| model                          |       size |     params | backend    | ngl | n_batch | n_ubatch | fa | mmap |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------: | -------: | -: | ---: | --------------: | -------------------: |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 |          pp4096 |      4078.31 ± 17.44 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 |  pp4096 @ d4096 |      3493.92 ± 17.48 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 |  pp4096 @ d8192 |      3299.58 ± 71.51 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 | pp4096 @ d16384 |     2981.73 ± 121.58 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 | pp4096 @ d20000 |      1950.21 ± 14.90 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 | pp4096 @ d32768 |      2594.72 ± 41.55 |
| gpt-oss 120B MXFP4 MoE         |  59.02 GiB |   116.83 B | CUDA       | 999 |    4096 |     4096 |  1 |    0 | pp4096 @ d65536 |       2004.36 ± 9.00 |

build: 85a7d8677 (6868)

Notice that performance is slightly worse for all depths, except for depth 20000, which sees a massive 40% drop.

Please let me know if you need any more information. Thanks!

### PR DESCRIPTION
**Pull request by ggerganov**
fix #17037 #17058
cont #16812

~The small SWA caches can be padded to 256 without concerns about memory usage.~ Pad the cache size to 256. This is friendly for the CUDA backend since the FA implementation benefits from round sizes of the K/V tensors. Can also help other backends.

This is essentially a partial revert of #16812.

Comparing with before the regression in #16812:

```bash
GGML_CUDA=ON CUDA_VISIBLE_DEVICES=0 ./scripts/compare-commits.sh a8ca18b4b d2c30c61a llama-bench -m ~/.cache/llama.cpp/ggml-org_gpt-oss-20b-GGUF_gpt-oss-20b-mxfp4.gguf -m /home/ggerganov/.cache/llama.cpp/ggml-org_Qwen2.5-Coder-3B-Q8_0-GGUF_qwen2.5-coder-3b-q8_0.gguf -ngl 99 -d 4096,8192,16384,32768 -ub 512,4096 -b 4096 -fa 1 -n 32 -mmp 0
```

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 5090, compute capability 12.0, VMM: yes

| Model                 |   Microbatch size | Test         |   t/s a8ca18b4b |   t/s d2c30c61a |   Speedup |
|:----------------------|------------------:|:-------------|----------------:|----------------:|----------:|
| gpt-oss 20B MXFP4 MoE |               512 | pp512@d4096  |         9702.25 |         9724.85 |      1.00 |
| gpt-oss 20B MXFP4 MoE |               512 | pp512@d8192  |         8609.17 |         8643.88 |      1.00 |
| gpt-oss 20B MXFP4 MoE |               512 | pp512@d16384 |         7169.27 |         7224.84 |      1.01 |
| gpt-oss 20B MXFP4 MoE |               512 | pp512@d32768 |         5349.99 |         5380.43 |      1.01 |
| gpt-oss 20B MXFP4 MoE |               512 | tg32@d4096   |          306.13 |          338.25 |      1.10 |
| gpt-oss 20B MXFP4 MoE |               512 | tg32@d8192   |          292.57 |          317.68 |      1.09 |
| gpt-oss 20B MXFP4 MoE |               512 | tg32@d16384  |          265.66 |          304.90 |      1.15 |
| gpt-oss 20B MXFP4 MoE |               512 | tg32@d32768  |          236.92 |          262.29 |      1.11 |
| gpt-oss 20B MXFP4 MoE |              4096 | pp512@d4096  |         8720.64 |         8735.30 |      1.00 |
| gpt-oss 20B MXFP4 MoE |              4096 | pp512@d8192  |         7908.52 |         7799.28 |      0.99 |
| gpt-oss 20B MXFP4 MoE |              4096 | pp512@d16384 |         6656.47 |         6583.46 |      0.99 |
| gpt-oss 20B MXFP4 MoE |              4096 | pp512@d32768 |         5063.06 |         4967.41 |      0.98 |
| gpt-oss 20B MXFP4 MoE |              4096 | tg32@d4096   |          296.76 |          318.91 |      1.07 |
| gpt-oss 20B MXFP4 MoE |              4096 | tg32@d8192   |          279.30 |          322.56 |      1.15 |
| gpt-oss 20B MXFP4 MoE |              4096 | tg32@d16384  |          251.35 |          283.65 |      1.13 |
| gpt-oss 20B MXFP4 MoE |              4096 | tg32@d32768  |          227.88 |          253.40 |      1.11 |
| qwen2 3B Q8_0         |               512 | pp512@d4096  |        17229.54 |        17278.24 |      1.00 |
| qwen2 3B Q8_0         |               512 | pp512@d8192  |        14011.21 |        14133.12 |      1.01 |
| qwen2 3B Q8_0         |               512 | pp512@d16384 |        10304.85 |        10307.07 |      1.00 |
| qwen2 3B Q8_0         |               512 | pp512@d32768 |         6612.16 |         6567.63 |      0.99 |
| qwen2 3B Q8_0         |               512 | tg32@d4096   |          279.56 |          294.93 |      1.05 |
| qwen2 3B Q8_0         |               512 | tg32@d8192   |          210.92 |          213.51 |      1.01 |
| qwen2 3B Q8_0         |               512 | tg32@d16384  |          185.15 |          188.19 |      1.02 |
| qwen2 3B Q8_0         |               512 | tg32@d32768  |          147.62 |          149.84 |      1.02 |
| qwen2 3B Q8_0         |              4096 | pp512@d4096  |        16599.01 |        16781.20 |      1.01 |
| qwen2 3B Q8_0         |              4096 | pp512@d8192  |        13664.67 |        13715.42 |      1.00 |
| qwen2 3B Q8_0         |              4096 | pp512@d16384 |        10056.36 |        10027.96 |      1.00 |
| qwen2 3B Q8_0         |              4096 | pp512@d32768 |         6585.53 |         6579.99 |      1.00 |
| qwen2 3B Q8_0         |              4096 | tg32@d4096   |          274.54 |          279.28 |      1.02 |
| qwen2 3B Q8_0         |              4096 | tg32@d8192   |          219.26 |          224.87 |      1.03 |
| qwen2 3B Q8_0         |              4096 | tg32@d16384  |          188.45 |          192.18 |      1.02 |
| qwen2 3B Q8_0         |              4096 | tg32@d32768  |          148.30 |          150.20 |      1.01 |

### CODE REVIEW

File: tools/llama-bench/llama-bench.cpp [hunk 1]
```diff
@@ -1124,7 +1124,7 @@ struct cmd_params_instance {
     llama_context_params to_llama_cparams() const {
         llama_context_params cparams = llama_context_default_params();
 
-        cparams.n_ctx           = n_prompt + n_gen + n_depth;
+        cparams.n_ctx           = GGML_PAD(n_prompt + n_gen + n_depth, 256);
```
Comment (slaren) [inline tools/llama-bench/llama-bench.cpp]: I don't think this is good, applications shouldn't be responsible for this padding.

Comment (ggerganov) [reply tools/llama-bench/llama-bench.cpp]: Move the padding to `llama_context` constructor?

Comment (slaren) [reply tools/llama-bench/llama-bench.cpp]: If there is a significant performance advantage from doing that then yes, that seems like a good thing to do. Otherwise, every single application would need to pad `n_ctx` manually.

Comment (ggerganov) [reply tools/llama-bench/llama-bench.cpp]: To clarify, the padding in `llama-bench` here is important because we do the TG test at full context. So we hit the bounds of the unpadded cache buffer when generating tokens (given that the resulting `cparams.n_ctx` number is not multiple of 256):

https://github.com/ggml-org/llama.cpp/blob/2fd7b7700776caaeade0dc4e2ff352f4e0f3ebf0/src/llama-kv-cache.cpp#L975-L989

Normally, applications will rarely experience this problem, because it shows up only when you are close to the full context.


I think it's ok to be in the constructor. The drawback is that you could have your requested `n_ctx` mutated which is not ideal. But probably a less of a problem than the current one.

Comment (slaren) [reply tools/llama-bench/llama-bench.cpp]: > The drawback is that you could have your requested `n_ctx` mutated which is not ideal.

As long as the value is never below what the application requested, it should be fine. The application can choose to use `llama_n_ctx` to take advantage of every slot, but they don't have to. I think this was already the situation before the padding was removed.

**Review by slaren — APPROVED** [review]

File: src/llama-kv-cache-iswa.cpp [hunk 2]
```diff
@@ -45,7 +45,9 @@ llama_kv_cache_iswa::llama_kv_cache_iswa(
 
     const uint32_t size_base = kv_size;
 
-    uint32_t size_swa = std::min(size_base, GGML_PAD(hparams.n_swa*(unified ? n_seq_max : 1) + n_ubatch, n_pad));
+    // note: the SWA cache is always padded to 256 for performance
+    //       https://github.com/ggml-org/llama.cpp/issues/17037
+    uint32_t size_swa = std::min(size_base, GGML_PAD(hparams.n_swa*(unified ? n_seq_max : 1) + n_ubatch, 256));
```
Comment (slaren) [inline src/llama-kv-cache-iswa.cpp]: Nit, I think this relies on `kv_size` being padded to 256. The `GGML_PAD` could be moved outside the `std::min` to ensure that it is still padded if this changes in the future.
