### PR TITLE
server : (UI) fix missing async generator on safari

### LINKED ISSUE #10841: Misc. bug: Server Demo on Mac, safari return error
### Name and Version

5478bbcd

### Operating systems

Mac

### Which llama.cpp modules do you know to be affected?

llama-server

### Problem description & steps to reproduce

1. build on MacBook Pro 16 inch 2019,
2. run server demo
3. open safari browser with localhost:8080
4. type 'hello'

### First Bad Commit

browser popup error dialog with message: "TypeError:r is not async iterable"

### Relevant log output

```shell
srv  update_slots: all slots are idle
```

### PR DESCRIPTION
**Pull request by ngxson**
Fix #10841 and #10842

Caused by missing `ReadableStream` async iterator support on safari: https://caniuse.com/mdn-api_readablestream_--asynciterator

It's now working thanks to the ponyfill

image

### CODE REVIEW

File: examples/server/webui/src/main.js [hunk 1]
```diff
@@ -33,7 +36,7 @@ const CONFIG_DEFAULT = {
   systemMessage: 'You are a helpful assistant.',
   showTokensPerSecond: false,
   // make sure these default values are in sync with `common.h`
-  samplers: 'edkypmxt',
+  samplers: 'dkypmxt',
```
Comment (ggerganov) [inline examples/server/webui/src/main.js:39]: This should not be changed. With #10803, the penalties sampler has to be manually inserted, instead of always being present at the start.

**Review by ggerganov — APPROVED** [review]
Tested Safari on MacOS and it works.

File: examples/server/webui/src/main.js (hunk 1 above)
Comment (ngxson) [reply examples/server/webui/src/main.js]: Ah yeah, I took the incorrect base branch. Fixed now, thanks!

**Comment by ggerganov** [comment]
Btw, the "Copy" button on code blocks no longer seems to work. It throws this error in the console:

image

**Comment by ngxson** [comment]
There is some limits to the `navigator.clipboard` API: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

The solution is to fallback to `document.execCommand` if it's not available, I'll make an issue for this
