### PR TITLE
vulkan: compile shaders on-demand

### LINKED ISSUE #11339: Eval bug: vulkan: regression: vram usage increased
### Name and Version

716bd6dec3e044e5c325386b5b0483392b24cefe
bisected

### Operating systems

Linux

### GGML backends

Vulkan

### Hardware

amdgpu 8g

### Models

Qwen2.5-Coder-14B-Instruct-Q4_K_M
or any model with similar size

### Problem description & steps to reproduce

on c250ecb3157f3bae0a45f44c3c953b5414d4c2f7 . the weight part of model can fit into vram. left only context/kv cache on gtt. memory usage is 8166m vram + 2271m gtt.

but on 716bd6dec3e044e5c325386b5b0483392b24cefe . memory usage is 6342m vram + 4107m gtt. significantly slowed down the tg speed.

### First Bad Commit

716bd6dec3e044e5c325386b5b0483392b24cefe

### Relevant log output

```shell
no difference on log output
```

### PR DESCRIPTION
**Pull request by jeffbolznv**
Reduce first-run startup time and memory consumption.

Should fix #11339.

### CODE REVIEW

File: ggml/src/ggml-vulkan/ggml-vulkan.cpp [hunk 1]
```diff
@@ -770,117 +777,118 @@ static std::condition_variable compile_count_cond;
...
+        pipeline->push_constant_size = push_constant_size;
+        pipeline->wg_denoms = wg_denoms;
+        pipeline->align = align;
+    }
 
-    vk::ShaderModuleCreateInfo shader_module_create_info({}, spv_size, reinterpret_cast<const uint32_t *>(spv_data));
-    pipeline->shader_module = device->device.createShaderModule(shader_module_create_info);
+    if (pipeline->needed && !pipeline->compiled) {
 
-    std::vector<vk::DescriptorSetLayoutBinding> dsl_binding;
```
Comment (jeffbolznv) [inline ggml/src/ggml-vulkan/ggml-vulkan.cpp:789]: These diffs don't display well due to an indentation change. I suggest reviewing in a different diff tool.

Comment (jeffbolznv) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp]: (gone in next revision)

**Review by 0cc4m — APPROVED** [review]
This didn't even need that many changes, very nice. Works fine in my tests. Thank you.
