### PR TITLE
server : use common_token_to_piece instead of common_detokenize

### LINKED ISSUE #11728: Misc. bug: Tokens in top_probs / top_logprobs are missing whitespace
### Name and Version

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6, VMM: yes
version: 0 (unknown)
built with gcc (GCC) 13.3.0 for x86_64-unknown-linux-gnu

(actually version 4552, built with Nix)

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
$ bin/llama-server -m ../../../wizardcoder-python-34b-v1.0.Q5_K_M.gguf -ngl 9999
...

$ curl -fsS \
    --url http://127.0.0.1:8080/completion \
    --header "Content-Type: application/json" \
    --data '{"prompt": "Hello","n_predict": 1, "n_probs": 10, "temperature":0}' | jq .
{
  ...
  "completion_probabilities": [
    {
      "id": 2897,
      "token": " os",                      <---------- whitespace OK
      "bytes": [
        32,                                <---------- whitespace OK
        111,
        115
      ],
      "logprob": -2.0750603675842285,
      "top_logprobs": [
        {
          "id": 2897,
          "token": "os",                   <---------- whitespace missing
          "bytes": [
            111,                           <---------- whitespace missing
            115
          ],
          "logprob": -2.0750603675842285
        },
```

### Problem description & steps to reproduce

As above, doesn't seem to depend on the model

### First Bad Commit

57bb2c40cd94c5a09f5210ed8264cc93b21c4b7e

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by danbev**
TThis commit replaces the call to `common_detokenize` with
`common_token_to_piece` in the populate_token_probs.

The motivation for this change is to avoid an issue where
common_detokenize would remove the word boundary character for tokens,
which caused a regression in the server generated token probabilities.
    
Resolves: https://github.com/ggerganov/llama.cpp/issues/11728

### CODE REVIEW

File: examples/server/server.cpp [hunk 1]
```diff
@@ -541,12 +541,16 @@ struct completion_token_output {
     json to_json(bool post_sampling_probs) const {
         json probs_for_token = json::array();
         for (const auto & p : probs) {
-            std::string txt(p.txt);
+            // If the predicted token id is the same as this.tok, then we use the text_to_send instead
```
Comment (ngxson) [inline examples/server/server.cpp:544]: I'm just wondering if this only happens with `tok == p.tok`, or it also affect other tokens inside `probs_for_token` list

**Comment by ngxson** [comment]
Also, a clue is to look around the `common_detokenize`, probably we miss certain params when constructing these detokenized string. The lines around `result.probs.reserve(max_probs);` should be related

File: examples/server/server.cpp [hunk 2]
```diff
@@ -541,12 +541,16 @@ struct completion_token_output {
...
+            // of the detokenized token. This is to avoid a mismatch between the text tokens where
+            // the text_to_send token may include a leading whitespace character but the detokenized
+            // token would not.
+            std::string txt = tok == p.tok ? text_to_send : p.txt;
```
Comment (CyberShadow) [inline examples/server/server.cpp:548]: Hi, thanks for working on this. Just wanted to mention that fixing the whitespace only for the first token in `top_logprobs` is not going to fix the use case I'm working with - the tokens in the other `top_logprobs` entries need to have the correct whitespace as they did before #10783. Sorry if the issue description was unclear.

Comment (danbev) [reply examples/server/server.cpp:548]: Ah, thanks for the clarification. I'll revert and look into this again now.

**Review by CyberShadow — APPROVED** [review]
I can't comment on the code, but I've tested this patch and it builds successfully + resolves the issue #11728 . Thank you!

File: examples/server/server.cpp [hunk 3]
```diff
@@ -2297,7 +2297,7 @@ struct server_context {
             for (size_t i = 0; i < std::min(n_vocab, n_probs); i++) {
                 result.probs.push_back({
                     cur[i].id,
-                    common_detokenize(ctx, {cur[i].id}, special),
+                    common_detokenize(ctx, {cur[i].id}, special, /* remove_space_prefix */ false),
```
Comment (ggerganov) [inline examples/server/server.cpp:2300]: Wouldn't it be simpler to detokenize `{bos, cur[i].id}`?

I would like t avoid adding this extra parameter to the API.

Comment (ngxson) [reply examples/server/server.cpp:2300]: @ggerganov maybe I misunderstood, but won't `{bos, cur[i].id}` returns something like `<bos> text`? But what we want here is just ` text`

Also would be nicer if we can query the raw token from vocab, but I don't think we have an API for that.

Comment (ggerganov) [reply examples/server/server.cpp:2300]: If `special == false` it won't render the BOS token.

Comment (ggerganov) [reply examples/server/server.cpp:2300]: > Also would be nicer if we can query the raw token from vocab, but I don't think we have an API for that.

What about `llama_token_to_piece`?

Comment (danbev) [reply examples/server/server.cpp]: @ggerganov @ngxson Thanks, that is a much simpler and better solution!

**Review by ggerganov — APPROVED** [review]

**Comment by ngxson** [comment]
IIRC there is another place having the same logic (near the speculative decode logic), that should be fixed too

**Comment by danbev** [comment]
> IIRC there is another place having the same logic (near the speculative decode logic), that should be fixed too

I've taken a look but could not find this in/near the speculative decoding. I did find this [TODO](https://github.com/ggerganov/llama.cpp/blob/b9ab0a4d0b2ed19effec130921d05fb5c30b68c5/examples/server/server.cpp#L3323) though. 

I noticed that this same logic has part of the [post_sampling_probs](https://github.com/ggerganov/llama.cpp/blob/b9ab0a4d0b2ed19effec130921d05fb5c30b68c5/examples/server/server.cpp#L2282) and have updated this in https://github.com/ggerganov/llama.cpp/pull/11740/commits/5deee0a0938986e091fea90a14d77b958c2d77cc.

**Review by ngxson — APPROVED** [review]
