### PR TITLE
ggml : fix MUL_MAT_ID repack with Q8_K

### LINKED ISSUE #12528: Eval bug: Program not working properly due to new features of "repack Q4_K tensor"
### Name and Version

built with cc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0 for x86_64-linux-gnu

### Operating systems

Linux

### GGML backends

CPU

### Hardware

13th Gen Intel(R) Core(TM) i9-13900H

### Models

DeepSeek-V2-Lite-Q4_K_M

### Problem description & steps to reproduce

_Usage:  ./llama-simple -m $Model_Path/DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf_

I used the git bisect tool to find out that after submitting 3d82dbcbce2c677fc35fbf99574ccd107d95a1f8 , the program does not work properly. And this feature is was introduced on #12332 . This directly caused my CPU to have an overflow error when calculating “ffn-moe-gate”.
Unfortunately, I am not familiar with this featrue.Could anyone fix this bug?  @Srihari-mcw @ggerganov 

### First Bad Commit

3d82dbcbce2c677fc35fbf99574ccd107d95a1f8

### Relevant log output

```shell
repack: repack tensor blk.0.attn_kv_a_mqa.weight with q4_K_8x8
repack: repack tensor blk.0.attn_kv_b.weight with q4_K_8x8
repack: repack tensor blk.0.attn_output.weight with q4_K_8x8
......
......

llama-simple: \~/workspace/github/llama.cpp/ggml/src/ggml-cpu/ggml-cpu.c:7669: ggml_compute_forward_silu_f32: Assertion `!isinf(x)' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by ggerganov**
fix #12528 

- The `mul_mat_id` assumed `Q8_0` type for the `src1`
- Fix `IQ4_NL` param type to by `Q8_0` instead of `IQ4_NL`
- Code indentations

### CODE REVIEW

**Comment by ggerganov** [comment]
@Djip007 Could you take a look at these fixes?

File: ggml/src/ggml-cpu/ggml-cpu-aarch64.cpp [hunk 1]
```diff
@@ -5295,8 +5295,7 @@ template <> void gemv<block_q4_K, 8, 8>(int n, float * s, size_t bs, const void
     ggml_gemv_q4_K_8x8_q8_K(n, s, bs, vx, vy, nr, nc);
 }
 
-template <>
-void gemv<block_iq4_nl, 4, 4>(int n, float * s, size_t bs, const void * vx, const void * vy, int nr, int nc) {
+template <> void gemv<block_iq4_nl, 4, 4>(int n, float * s, size_t bs, const void * vx, const void * vy, int nr, int nc) {
```
Comment (Djip007) [inline ggml/src/ggml-cpu/ggml-cpu-aarch64.cpp:5298]: may be add the PARAM_TYPE on this template to
```c++
template <typename BLOC_TYPE, int64_t INTER_SIZE, int64_t NB_COLS, PARAM_TYPE>
void gem[m,v]....
```

**Review by Djip007 — COMMENTED** [review]
a very quick review...

**Comment by ggerganov** [comment]
@Djip007 Thanks. Let me know if you have any other suggestions.
