### PR TITLE
webui: Stop rerender on textarea input and end the devastating lag

### LINKED ISSUE #11813: Misc. bug: webui: extreme sluggish performance typing into textarea with long-context conversations
### Name and Version

version: 4690 (4078c77f)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
llama-server -m <any model>
```

### Problem description & steps to reproduce

The user textarea has extreme sluggish performance when typing when the conversation above has a lot of context.

1. Write a very long message (16K+ tokens) and send.
2. Try typing into the textarea. Sluggish performance. Are we rerendering a component like ChatScreen on each keystroke and doing complex computations on the previous messages? I can't easily spot it myself if we are.

### First Bad Commit

New React UI commit but not entirely sure

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by woof-dog**
Fixes the **devastating** lag when typing into the textarea by making it uncontrolled and stopping us from **rerendering the WHOLE chat screen** whenever you type a character into the input textarea.

Closes #11813 #12026 

I did NOT test how this affects the useVSCodeContext integration. Also with this PR the send button does not disable, but that's a lower priority. If this functionality is absolutely necessary then you need to extract something (the button and maybe textarea) into another component.

It seems like there is still lots of lag in general with rendering (when the assistant response is being printed for example) but at least this cuts it down on the textarea input lag :/

### CODE REVIEW

File: examples/server/webui/src/components/ChatScreen.tsx [hunk 1]
```diff
@@ -99,12 +99,15 @@ export default function ChatScreen() {
     canvasData,
     replaceMessageAndGenerate,
   } = useAppContext();
-  const [inputMsg, setInputMsg] = useState(prefilledMsg.content());
```
Comment (ngxson) [inline examples/server/webui/src/components/ChatScreen.tsx:102]: If I understand correctly, `prefilledMsg.content()` is currently discarded

**Comment by ngxson** [comment]
> **rerendering the WHOLE chat screen** whenever you type a character into the input textarea.

No it does not rerender the whole screen. In fact, the rerender of the textarea alone is already slow, and this is a known problem in reactjs: https://www.google.com/search?client=firefox-b-d&q=reactjs+textarea+slow

I'm a bit surprise that there is no solution (i.e. pre-made components) to solve this problem. I think I'll propose something more elegant (maybe `useMemo` or something like that)

> It seems like there is still lots of lag in general with rendering (when the assistant response is being printed for example)

I think it's mostly due to the logic where we extract `<think>...</think>` from the response

File: examples/server/webui/src/components/ChatScreen.tsx (hunk 1 above)
Comment (woof-dog) [reply examples/server/webui/src/components/ChatScreen.tsx:102]: Could you rephrase what you mean? I put `prefilledMsg.content()` below under `defaultValue`

**Comment by woof-dog** [comment]
Sorry for the hyperbole, I must have been overly emotional this morning haha.

> No it does not rerender the whole screen

I think the whole point of my fix and why it works is that it no longer rerenders the entire ChatScreen component on input? (Yes I only meant ChatScreen and not the whole page)

When I search for slow textarea input in React, it all has to do with textareas in React that are doing what is currently on master: rerendering the component if something changes by using setXXX (from useState) to update the state on input change.

Anyway, thank you very very much for putting some attention to this problem since I encounter it a lot :)

**Comment by ngxson** [comment]
> Sorry for the hyperbole, I must have been overly emotional this morning haha.

haha no worries, I'm kinda on the same boat recently

Indeed, your approach in this PR is good, I think if anyone ever create "pre-made component" that I mentioned in the last message, they would do the same.

I think it could be cleaner to wrap your logic into a new component called `OptimizedTextarea` (could be a bad naming, but we won't reuse it anywhere else outside of this project anyway) - I'll push a commit in the next few hours.

**Comment by ngxson** [comment]
Ok I still haven't been able to come up with a better way to abstract this out, will revisit this tomorrow then.

File: examples/server/webui/src/components/ChatScreen.tsx [hunk 2]
```diff
@@ -259,8 +267,7 @@ export default function ChatScreen() {
             className="textarea textarea-bordered w-full"
             placeholder="Type a message (Shift+Enter to add a new line)"
             ref={inputRef}
-            value={inputMsg}
-            onChange={(e) => setInputMsg(e.target.value)}
+            defaultValue={prefilledMsg.content()}
```
Comment (ngxson) [inline examples/server/webui/src/components/ChatScreen.tsx:270]: There could be a race condition between `prefilledMsg.content()` and `prefilledMsg.clear()` above

**Comment by ngxson** [comment]
@woof-dog Ok so I wrote an implementation that is inspired by the `useSignal` pattern from preactjs / solidjs. The idea is to have a function `value()` instead of reading directly plain string `value`

One thing that I will need to test more, my `savedInitValue` can be messed up if the `ChatScreen` component is re-mounted.

But still, would be nice if you can already test to see if the performance is better now.

**Comment by woof-dog** [comment]
Thank you for the improvements! I can confirm the performance remains better on this branch after applying your changes (you can reproduce by sending a huge message and then typing in the textarea, it's responsive).

**Comment by ngxson** [comment]
Ok thanks for confirmation, I'll fix the remaining problem mentioned in my comment above then merge this.

Btw which OS/browser you're using? I cannot reproduce the lagging issue on Firefox on MacOS (seems like it only appears on Chrome)

I do try Brave which is chromium based, but still unable to reproduce (it is slow, but the same level of unresponsiveness with or w/o this PR)

**Comment by woof-dog** [comment]
I was using Firefox 136.0 on Ubuntu. With Chromium I also see the textarea input lag go away on this branch.

For me I notice the input lag (on master) is substantially worse on Chromium than Firefox. Also there is some lag during generation (but this issue primarily is about the input textarea).

**Review by ngxson — APPROVED** [review]
