### PR TITLE
examples : Fix `llama-export-lora` example

### LINKED ISSUE #8581: Bug: export-lora does not accept GGUF files
### What happened?

After the process of finetuning, a LoRA GGUF is created using ```convert_lora_to_gguf.py``` from transformers. After llama.cpp implemented support for LoRA conversion to GGUF in recent days, the same support hasn't seen extended to export-lora. When I am combining the LoRA GGUF with the base model GGUF, I get a GGML error (see below). This is the command that I used to export lora: ```!/usr/home/llamacpp/llama-export-lora -m /kaggle/working/base-model-f16.gguf -l /kaggle/working/trained-model/ggml-lora-f16.gguf -o /kaggle/working/full-model-finetune-f16.gguf```.

### Name and Version

version: 1 (a15ef8f)
built with cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
error: unexpected lora header file magic in '/kaggle/working/trained-model/ggml-lora-f16.gguf
```

### PR DESCRIPTION
**Pull request by ngxson**
Resolve #8581

This can now accepts new lora format introduced in #8332 

The output merged tensor will be forced to f16, since `ggml_cast` does not support Q-type quants. It would be nice to move threaded quantization functions from llama.cpp to ggml

---

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [ ] Low
  - [x] Medium
  - [ ] High

### CODE REVIEW

File: examples/export-lora/export-lora.cpp [hunk 1]
```diff
@@ -1,465 +1,377 @@
...
+
+        // if true, this tensor can be lora-merged. if false, we skip merging and just copy data to outfile
+        std::vector<std::pair<struct ggml_tensor *, bool>> base_tensors;
+        for (auto & it : base_model.tensors) {
+            bool t_a = true;
+            bool t_b = true;
+            for (auto & adapter : adapters) {
+                t_a &= nullptr != adapter->get_tensor(it.first + ".lora_a");
+                t_b &= nullptr != adapter->get_tensor(it.first + ".lora_b");
+            }
```
Comment (ggerganov) [inline examples/export-lora/export-lora.cpp:195]: Here we require that all adapters provide data for the base tensor. If either adapter does not have data for that tensor, then we keep the original data.

Maybe in the future we can improve to support when a subset of the adapters have the data

**Review by ggerganov — APPROVED** [review]
Haven't done tests but I think it is OK

Would recommend to add log messages with detailed information about:
- tensors being merged
- tensor sizes 
- lora scaling
- ranks
- etc.

We can improve as needed

File: examples/export-lora/export-lora.cpp (hunk 1 above)
Comment (ngxson) [reply examples/export-lora/export-lora.cpp:219]: Yeah right, thanks for spotting that. It's quite complicated to fix that for now, so I'd prefer to merge this PR as-is.

To prevent producing half-working model, I added a check and reject if that's the case. As a fallback solution, user can always run multiple times `llama-export-lora`: https://github.com/ggerganov/llama.cpp/pull/8607/commits/0ec2b5818afd2e406ae890cd0523f964606efda4

File: examples/export-lora/export-lora.cpp [hunk 2]
```diff
@@ -1,465 +1,403 @@
...
+        if (adapters.size() > 1) {
+            auto & base_adapter = adapters[0];
+            for (size_t i = 1; i < adapters.size(); ++i) {
+                for (auto & it : base_adapter->tensors) {
+                    if (base_adapter->get_tensor(it.first) == nullptr) {
+                        throw std::runtime_error("Input adapters do not have the same list of tensors. This is not yet supported. Please merge the adapter one-by-one instead of merging all at once.");
+                    }
+                }
+            }
+        }
```
Comment (slaren) [inline examples/export-lora/export-lora.cpp:209]: I don't think that this does anything as it is. Changing it to iterate over the tensors of `adapters[i]`, and checking that the number of tensors in all the adapters is the same to prevent accepting loras that have less tensors than the first one, may work.

Comment (ngxson) [reply examples/export-lora/export-lora.cpp:209]: The current logic make sure that all tensors in `adapter[i]` exists in `adapter[0]`. But yeah there can be also the case where `adapter[i]` has more tensors than `adapter[0]`. So I think adding a tensor count check here is the easy fix.

Comment (ngxson) [reply examples/export-lora/export-lora.cpp]: I attempted my fix on https://github.com/ggerganov/llama.cpp/pull/8607/commits/4bd55ec02c4039a2ec7eec36ce8869c239289058

Comment (slaren) [reply examples/export-lora/export-lora.cpp]: I might be missing something, but I am assuming that `adapter->get_tensor` finds a tensor in `adapter->tensors`, so it will always be true here since it is iterating over the tensors of the same adapter that it checks. I am assuming that the intention is to check the tensors of each adapter against the `base_adapter`.

File: common/common.h [hunk 3]
```diff
@@ -128,7 +128,6 @@ struct gpt_params {
 
     // TODO: avoid tuple, use struct
     std::vector<std::tuple<std::string, float>> lora_adapter; // lora adapter path with user defined scale
-    std::string lora_base  = "";                              // base model path for the lora adapter
```
[the remark this answers is not in the document]
Comment (ngxson) [reply common/common.h:131]: Yes, since #8332 `lora_base` is no longer needed because we're now merging lora at runtime (instead of merging it with base model at start up). You can still your base model as `-m` in `llama-export-lora`, but IMO it won't change end result very much.
