### PR TITLE
StableLM support

### LINKED ISSUE #3456: [User] How to convert Stability 3B model to ggml/ggul
Stability released their latest 3B model, but there is an error when executing the convert.py script:

// Model card and files on NF

https://huggingface.co/stabilityai/stablelm-3b-4e1t

//Error message

% python3 convert.py models/stablelm-3b-4e1t
Traceback (most recent call last):
  File "/Users/xxx/code/llama.cpp/convert.py", line 1208, in <module>
    main()
  File "/Users/xxx/code/llama.cpp/convert.py", line 1149, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/code/llama.cpp/convert.py", line 1060, in load_some_model
    raise Exception(f"Can't find model in directory {path}")
Exception: Can't find model in directory models/stablelm-3b-4e1t

### PR DESCRIPTION
**Pull request by Galunid**
- [X] Converting model
- [ ] ~~Add warning when trying to convert .safetensors model~~
- [x] Support `.safetensors` model conversion
- [X] Loading model
- [X] GPU support - partial (offloading whole model runs into  
`GGML_ASSERT: ggml-cuda.cu:6402: ne00 == n_dims && "ne00 != n_dims is not implemented for CUDA yet"`)
- [X] Text generation
- [x] Coherent text generation
- [x] Verify `gpt2` tokenizer produces the same results as `GPTNeoxFast` from `transformers`
- [x] Code style fixes
- [x] Investigate why sometimes run crashes with `std::unordered_map`
- [x] Push `added_tokens` fixes to conversion script  
- [x] Convert `.bin` models too

closes #3456

### CODE REVIEW

**Comment by cebtenzzre** [comment]
Why warn for safetensors? The current version of the falcon script supports both formats; it's not hard to do.

**Comment by goerch** [comment]
> Why warn for safetensors?

He might not have tested it. Perfectly fine for me.

**Comment by Galunid** [comment]
> Why warn for safetensors? The current version of the falcon script supports both formats; it's not hard to do.

I wasn't aware we support it already and don't need to pull any new dependencies. I just took a look at `convert-gptneox-hf-to-gguf.py`. Model is shipped in `.safetensors` format, so it would be great if we can directly support it, without first converting it to `pytorch_model.bin`.

**Comment by Galunid** [comment]
> @Galunid : tokenizers are bad, did you check?

@goerch: No, not yet, right now I can load the model and it starts generating gibberish. I wanted to get something that runs first. I'm going to look at the tokenizer now. Could you confirm whether the output below looks like a tokenizer issue to you?
```
system_info: n_threads = 6 / 12 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
sampling: repeat_last_n = 64, repeat_penalty = 1,100000, presence_penalty = 0,000000, frequency_penalty = 0,000000, top_k = 40, tfs_z = 1,000000, top_p = 0,950000, typical_p = 1,000000, temp = 0,800000, mirostat = 0, mirostat_lr = 0,100000, mirostat_ent = 5,000000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0


User: Test\nAssistant:ittinailresholdew่edsHs sendingwedgeformationsÄ"_ordingnai ØFIighsinkingnoseighs fir Hann Hann mountain gnTraceeldgger MeasurementighturchpossatsßEvaluationoseättFALSEaughsetto Ladenichte））org）ose knitmatterschenrettoseesteiked ted lightningoseasper Hed<|endoftext|> [end of text]

llama_print_timings:        load time =    1088,18 ms
llama_print_timings:      sample time =      59,66 ms /    60 runs   (    0,99 ms per token,  1005,68 tokens per second)
llama_print_timings: prompt eval time =     335,30 ms /     8 tokens (   41,91 ms per token,    23,86 tokens per second)
llama_print_timings:        eval time =    8119,81 ms /    59 runs   (  137,62 ms per token,     7,27 tokens per second)
llama_print_timings:       total time =    8576,62 ms
Log end
```

**Comment by mmnga** [comment]
After a little modification, the output was correct.

`make -j && ./main -m 'ggml-model-q4_0.gguf' -p "My Best Music is" -n 64`
Selected 3b model!My Best Music is a lot of music is all best song Best Song Best Music Best music music music. Kind Music with the least musical and songs in me! Best S B The F,
 Best Good and Music of our is buying was. video buy Us Born Birth The Best Buy Me Best For St will best and the. It.
llama_print_timings:        load time =     227.01 ms


This model has parameters like llama, but the logic is GPT-NEOX.

https://huggingface.co/stabilityai/stablelm-3b-4e1t
Library: [GPT-NeoX](https://github.com/EleutherAI/gpt-neox)

add attn-norm bias 
add ffn-norm bias
rope gpt-neox mode

        struct ggml_tensor * inpSA = inpL;

        // norm
        {
            cur = ggml_rms_norm(ctx0, inpL, norm_rms_eps);
            offload_func(cur);
            ggml_set_name(cur, "rms_norm_0");

            // cur = cur*attn_norm(broadcasted)
            cur = ggml_mul(ctx0, cur, model.layers[il].attn_norm);
            offload_func(cur);
            ggml_set_name(cur, "attention_norm_0");

            // add bias
            cur = ggml_add(ctx0, cur, model.layers[il].attn_norm_b);
            offload_func(cur);
            ggml_set_name(cur, "attention_norm_0");
        }


            // mode 2 (gpt-neox)
            struct ggml_tensor * Kcur = ggml_rope_custom(ctx0, ggml_reshape_3d(ctx0, tmpk, n_embd_head, n_head_kv, n_tokens), KQ_pos, n_embd_head, 2, 0, freq_base, freq_scale);
            offload_func_kq(Kcur);
            ggml_set_name(Kcur, "Kcur");

            // mode 2 (gpt-neox)
            struct ggml_tensor * Qcur = ggml_rope_custom(ctx0, ggml_reshape_3d(ctx0, tmpq, n_embd_head, n_head,    n_tokens), KQ_pos, n_embd_head, 2, 0, freq_base, freq_scale);
            offload_func_kq(Qcur);
            ggml_set_name(Qcur, "Qcur");

            // norm
            {
                cur = ggml_rms_norm(ctx0, inpFF, norm_rms_eps);
                offload_func(cur);
                ggml_set_name(cur, "rms_norm_1");

                // cur = cur*ffn_norm(broadcasted)
                cur = ggml_mul(ctx0, cur, model.layers[il].ffn_norm);
                offload_func(cur);
                ggml_set_name(cur, "ffn_norm");

                // add bias
                // cur = cur*ffn_norm(broadcasted)
                cur = ggml_add(ctx0, cur, model.layers[il].ffn_norm_b);
                offload_func(cur);
                ggml_set_name(cur, "ffn_norm");

            }

**Comment by Galunid** [comment]
Thanks, I realized I forgot to add biases, but I'd have to spend quite a while to realize rope was set wrong!

**Comment by niranjanakella** [comment]
@Galunid Hello, just wanted to ask if there was any update on this? were you able to convert the [stablelm-3b-4e1t](https://huggingface.co/stabilityai/stablelm-3b-4e1t) model to GGUF? Thank you.

**Comment by Galunid** [comment]
@niranjanakella There's no update. I had family emergency and I didn't have time to touch code. I got back today and I'm planning to look at this more tomorrow. You can download converted model [here](https://huggingface.co/Galunid/stablelm-gguf). You will not get anything useful running this though, just some random nonsense.

**Comment by Green-Sky** [comment]
@Galunid how did you convert 4e1t, i dont see any safetensor code in the conversion script.

**Comment by Green-Sky** [comment]
I tried hacking in safetensor loading (by copying from falconconvert), but it fails with a size mismatch, idk, just dumping my diff here for reference.

```diff
diff --git a/convert-stablelm-hf-to-gguf.py b/convert-stablelm-hf-to-gguf.py
index 4a6fc66a..e163bb87 100755
--- a/convert-stablelm-hf-to-gguf.py
+++ b/convert-stablelm-hf-to-gguf.py
@@ -4,6 +4,7 @@
 from __future__ import annotations
 
 import argparse
+import contextlib
 import json
 import os
 import struct
@@ -20,17 +21,16 @@ if 'NO_LOCAL_GGUF' not in os.environ:
 import gguf
 
 
-def count_model_parts(dir_model: Path) -> int:
+def count_model_parts(dir_model: Path, prefix: str) -> int:
     num_parts = 0
     for filename in os.listdir(dir_model):
-        if filename.startswith("pytorch_model-"):
+        if filename.startswith(prefix):
             num_parts += 1
 
     if num_parts > 0:
         print("gguf: found " + str(num_parts) + " model parts")
     return num_parts
 
-
 def parse_args() -> argparse.Namespace:
     parser = argparse.ArgumentParser(description="Convert a stablelm model to a GGML compatible file")
     parser.add_argument(
@@ -80,10 +80,17 @@ with open(dir_model / "config.json", "r", encoding="utf-8") as f:
 if hparams["architectures"][0] != "StableLMEpochForCausalLM":
     print("Model architecture not supported: " + hparams["architectures"][0])
 
-    sys.exit()
+    sys.exit(1)
 
 # get number of model parts
-num_parts = count_model_parts(dir_model)
+#num_parts = count_model_parts(dir_model, "model-00")
+#if num_parts:
+num_parts = 0
+is_safetensors = True
+from safetensors import safe_open
+#else:
+    #is_safetensors = False
+    #num_parts = count_model_parts(dir_model, "pytorch_model-")
 
 ARCH=gguf.MODEL_ARCH.STABLELM
 gguf_writer = gguf.GGUFWriter(fname_out, gguf.MODEL_ARCH_NAMES[ARCH])
@@ -140,13 +147,20 @@ special_vocab.add_to_gguf(gguf_writer)
 # TENSORS
 
 tensor_map = gguf.get_tensor_name_map(ARCH,block_count)
-print(tensor_map)
+#print(tensor_map)
 
 # tensor info
 print("gguf: get tensor metadata")
 
 if num_parts == 0:
-    part_names = iter(("pytorch_model.bin",))
+    if is_safetensors:
+        part_names = iter(("model.safetensors",))
+    else:
+        part_names = iter(("pytorch_model.bin",))
+elif is_safetensors:
+    part_names = (
+        f"model-{n:05}-of-{num_parts:05}.safetensors" for n in range(1, num_parts + 1)
+    )
 else:
     part_names = (
         f"pytorch_model-{n:05}-of-{num_parts:05}.bin" for n in range(1, num_parts + 1)
@@ -156,47 +170,55 @@ for part_name in part_names:
     if args.vocab_only:
         break
     print("gguf: loading model part '" + part_name + "'")
-    model_part = torch.load(f"{dir_model}/{part_name}", map_location="cpu")
+    if is_safetensors:
+        ctx = safe_open(dir_model / part_name, framework="pt", device="cpu")
+    else:
+        ctx = contextlib.nullcontext(torch.load(dir_model / part_name, map_location="cpu"))
+
+    #model_part = torch.load(f"{dir_model}/{part_name}", map_location="cpu")
+
+    with ctx as model_part:
+        for name in model_part.keys():
+            #data = model_part[name]
+            data = model_part.get_tensor(name) if is_safetensors else model_part[name]
 
-    for name in model_part.keys():
-        data = model_part[name]
 
-        # we don't need these
-        if name.endswith(".attention.masked_bias") or name.endswith(".attention.bias") or name.endswith(".attention.rotary_emb.inv_freq"):
-            continue
+            # we don't need these
+            if name.endswith(".attention.masked_bias") or name.endswith(".attention.bias") or name.endswith(".attention.rotary_emb.inv_freq"):
+                continue
 
-        old_dtype = data.dtype
+            old_dtype = data.dtype
 
-        # convert any unsupported data types to float32
-        if data.dtype != torch.float16 and data.dtype != torch.float32:
-            data = data.to(torch.float32)
+            # convert any unsupported data types to float32
+            if data.dtype != torch.float16 and data.dtype != torch.float32:
+                data = data.to(torch.float32)
 
-        data = data.squeeze().numpy()
+            data = data.squeeze().numpy()
 
-        # map tensor names
-        new_name = tensor_map.get_name(name, try_suffixes = (".weight", ".bias"))
-        if new_name is None:
-            print("Can not map tensor '" + name + "'")
-            sys.exit()
+            # map tensor names
+            new_name = tensor_map.get_name(name, try_suffixes = (".weight", ".bias"))
+            if new_name is None:
+                print("Can not map tensor '" + name + "'")
+                sys.exit()
 
-        n_dims = len(data.shape)
-        data_dtype = data.dtype
+            n_dims = len(data.shape)
+            data_dtype = data.dtype
 
-        # if f32 desired, convert any float16 to float32
-        if ftype == 0 and data_dtype == np.float16:
-            data = data.astype(np.float32)
+            # if f32 desired, convert any float16 to float32
+            if ftype == 0 and data_dtype == np.float16:
+                data = data.astype(np.float32)
 
-        # TODO: Why cant we use these float16 as-is? There should be not reason to store float16 as float32
-        if ftype == 1 and data_dtype == np.float16 and n_dims == 1:
-            data = data.astype(np.float32)
+            # TODO: Why cant we use these float16 as-is? There should be not reason to store float16 as float32
+            if ftype == 1 and data_dtype == np.float16 and n_dims == 1:
+                data = data.astype(np.float32)
 
-        # if f16 desired, convert any float32 2-dim weight tensors to float16
-        if ftype == 1 and data_dtype == np.float32 and name.endswith(".weight") and n_dims == 2:
-            data = data.astype(np.float16)
+            # if f16 desired, convert any float32 2-dim weight tensors to float16
+            if ftype == 1 and data_dtype == np.float32 and name.endswith(".weight") and n_dims == 2:
+                data = data.astype(np.float16)
 
-        print(new_name + ", n_dims = " + str(n_dims) + ", " + str(old_dtype) + " --> " + str(data.dtype))
+            print(new_name + ", n_dims = " + str(n_dims) + ", " + str(old_dtype) + " --> " + str(data.dtype))
 
-        gguf_writer.add_tensor(new_name, data)
+            gguf_writer.add_tensor(new_name, data)
 
 
 print("gguf: write header")

```

**Comment by Green-Sky** [comment]
> @Green-Sky I changed conversion script to use safetensors. It works for me, could you give it a try? As for the error from yesterday, it looks like you're running out of disk space ;)

thanks for the update. I still have the same issue with the safetensors file. I also compared the sha256 of model.safetensors to the one on huggingface and they are a match. And no, i have >300gig on free space on the disk :)

```
blk.24.ffn_norm.bias, n_dims = 1, torch.bfloat16 --> float32
blk.24.ffn_norm.weight, n_dims = 1, torch.bfloat16 --> float32
blk.24.attn_k.weight, n_dims = 2, torch.bfloat16 --> float16
blk.24.attn_output.weight, n_dims = 2, torch.bfloat16 --> float16
blk.24.attn_q.weight, n_dims = 2, torch.bfloat16 --> float16
Traceback (most recent call last):
  File "/home/green/workspace/llama.cpp/./convert-stablelm-hf-to-gguf.py", line 182, in <module>
    gguf_writer.add_tensor(new_name, data)
  File "/home/green/workspace/llama.cpp/gguf-py/gguf/gguf.py", line 825, in add_tensor
    tensor.tofile(self.temp_file)
OSError: 6553600 requested and 5609472 written
```

**Comment by Green-Sky** [comment]
running in f32 mode the error is somewhat different and more explicit:
```
blk.15.ffn_down.weight, n_dims = 2, torch.bfloat16 --> float32
blk.15.ffn_gate.weight, n_dims = 2, torch.bfloat16 --> float32
Traceback (most recent call last):
  File "/home/green/workspace/llama.cpp/models/stablelm-3b-4e1t/../../convert-stablelm-hf-to-gguf.py", line 182, in <module>
    gguf_writer.add_tensor(new_name, data)
  File "/home/green/workspace/llama.cpp/models/stablelm-3b-4e1t/../../gguf-py/gguf/gguf.py", line 825, in add_tensor
    tensor.tofile(self.temp_file)
OSError: Not enough free space to write 70778880 bytes
```


how. where is this temp file located?

**Comment by Green-Sky** [comment]
> > how. where is this temp file located?
> 
> It's putting the temp file on tmpfs. You need to run the command with `TMPDIR=/var/tmp` (or any other folder on disk) before it so you can convert models that are larger than 50% of your system RAM. See #3433

thanks, that worked.

here is the current state:
```
system_info: n_threads = 12 / 24 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0


The meaning of life is to be of Life for every
of life for me or existence in life
your life and life – life.ит life life life: life.
meaning Life life is the
life. world me being an meaning life in you life of life to your one life_ the of " life at. m of. (and. The. life to the see what This and life is' is" [. … of this a it/o her family as is it can life which is here the life.. life Mean me is Lifee death in my ors
 meaning is. earth finding person of p which you.[ m. life of. if search_? " " is by meaning is means. The is meaning ," but . said is mean
, me for meet it you after. to that the l as the women in he him
 a and w s.. you..:. Meaning You A. this people event " find an is men life. who which see having This. is you Of .. meaning place of its at. Me. being mess // The mean off someone is if or .
 “ " on mif is If" be has of the[ in and [| •[ , b me ; mina he there itself â find this / \\ ;. e will s � ] is f dr l set a . . I it . his for | you its that those is as. see if meaning get pm ” us // on ! .” the in sex but* // okot .orying  why .. what. & internet 1 is ,[ p and// c has? your please away the mâ\\\\& ;\\\\\\\\\\ym \\ her%1.|12ines%oiseg[ thep as never find/+ meet thi ] s the \ you f c she \terminate called after throwing an instance of 'std::out_of_range'
  what():  unordered_map::at
Aborted (core dumped)
```

looks like vocabulary is missing.

**Comment by Galunid** [comment]
I think it's more of a model architecture being incorrectly implemented and model going nuts and "hallucinating" non existent tokens. I mostly copied the implementation from existing llama/gptneox ones and stitched them together, but I've seen that stability had their own modifications I haven't checked yet, so it'll probably be a pain. On a different note I verified that `gpt2` tokenizer seems to be working as expected here (stablelm uses `gptneox`, but under the hood they *seem* identical, I'll have verify this). Initial results using `GPTNeoxFast` from `transformers` and `llama.cpp`'s `gpt2` produce the same output, so we should be good at least as a PoC

**Comment by Galunid** [comment]
I think I've found where the problem is:
>Normalization: LayerNorm ([Ba et al., 2016](https://arxiv.org/abs/1607.06450)) with learned bias terms as opposed to RMSNorm ([Zhang & Sennrich, 2019](https://arxiv.org/abs/1910.07467)).

**Comment by Galunid** [comment]
<details>
  <summary>The author of Hamlet is</summary>
  The author of Hamlet is unknown.
Although Shakespeare was known to have written the play, it wasn't until after his death in 1616 that his identity as its author became generally accepted by scholars; a theory advanced in the 17th century by Francis Meres, a playwright and poet who had been born near Stratford-upon-Avon, England. This was because Hamlet is so full of allusions to Shakespeare's plays and life that it would be very unusual for any other writer to have made them.
Shakespeare wrote many different types of plays over his long career -- tragedies like Macbeth and Romeo and Juliet; comedies like Much Ado About Nothing and A Midsummer Night's Dream; and historical dramas such as Henry V, Richard III and Julius Caesar. The most famous of all is Hamlet, which Shakespeare probably wrote between 1600 and 1602, though critics debate this point.
In the play Hamlet, Prince of Denmark, a Danish prince who was heir to the throne but was not allowed to marry his father's widow because she had been married before. After his uncle killed Hamlet’s father, Hamlet swore revenge on Claudius, Hamlet’s new stepfather. In the end, it is Hamlet, however, who kills himself in despair over his failure to avenge his father and restore order to Denmark.
Shakespeare wrote Hamlet when he was around 30 years old, but it wasn't performed until more than 200 years after its composition because of censorship rules that prohibited performance of plays with religious or political themes.<|endoftext|> [end of text]
</details>

<details>
    <summary></summary>
</details>

File: llama.cpp [hunk 1]
```diff
@@ -5670,6 +5776,409 @@ static struct ggml_cgraph * llm_build_mpt(
...
+    ggml_set_name(KQ_mask, "KQ_mask");
+    ggml_allocr_alloc(lctx.alloc, KQ_mask);
+    if (!ggml_allocr_is_measure(lctx.alloc)) {
+        float * data = (float *) KQ_mask->data;
+        memset(data, 0, ggml_nbytes(KQ_mask));
+
+        for (int h = 0; h < 1; ++h) {
+            for (int j = 0; j < n_tokens; ++j) {
+                const llama_pos    pos    = batch.pos[j];
+                const llama_seq_id seq_id = batch.seq_id[j];
```
Comment (ggerganov) [inline llama.cpp:5892]: This was recently changed:

```suggestion
                const llama_seq_id seq_id = batch.seq_id[j][0];
```

**Comment by Green-Sky** [comment]
Very nice, looks working now.

### cpu (with openblas)
```
system_info: n_threads = 12 / 24 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
sampling:
	repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, typical_p = 1.000, temp = 0.800
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0


I belive the meaning of life is to find a purpose which you will live for it’s all about your passion . There are many people who have great ideas , but they never try to do anything because of fear or insecurities.
The one thing that I believe we should not be afraid of , and something that can get us from our comfort zone is failure, Failure is the best teacher , and it teaches you a lesson that will stay with you for life time .
It’s always important to try new things even if they might fail at first because then you are able to learn many things in life. The same applies when thinking about your future , there are times we can’t see the end result of something but it is still worth trying out as it will give us valuable experience which no school or university could teach us .<|endoftext|> [end of text]
```

### cuda (with cublas) ngl 32
```
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =  261.74 MB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloaded 32/35 layers to GPU
llm_load_tensors: VRAM used: 2571.88 MB
.............................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: kv self size  =  160.00 MB
llama_new_context_with_model: compute buffer total size = 114.38 MB
llama_new_context_with_model: VRAM scratch buffer: 108.25 MB
llama_new_context_with_model: total VRAM used: 2680.75 MB (model: 2572.50 MB, context: 108.25 MB)

system_info: n_threads = 12 / 24 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
sampling:
	repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, typical_p = 1.000, temp = 0.800
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0


I belive the meaning of life is to enjoy your life.
To be alive. To experience it all. It's so short and beautiful, that I think we should live every day as if it were our last!
Life is such a gift to everyone here. I don't like to see people waste their lives away or not really enjoying what they have in front of them. Life isn't always easy and sometimes we get caught up with the negative things we do, but I think that's just because we've lost our motivation at some point. The important thing is to stay happy and positive throughout every day. That way you'll feel alive!
It's so hard to live in this world, but also very wonderful when you know how to enjoy it! It can be tough for anyone out there who has had a rough time of things or anything else that may have happened to them, I just believe everyone should try their best to look at the good side. After all we only have one chance at life and if we don't take advantage of it then what's the point? We can learn so much from others as well! So please enjoy your life.
```

ngl 33 works too. ngl 34 prints EEEEEEE after the first predicted token:
```
I belive the meaning of life isEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
```
ngl 35 fails with:
```
GGML_ASSERT: /build/c1m6am9ldk23qbbn56ifx6hqk6qdf1kb-source/ggml-cuda.cu:6402: ne00 == n_dims && "ne00 != n_dims is not implemented for CUDA yet"
Aborted (core dumped)
```

**Comment by Galunid** [comment]
Thanks for testing! I have no clue why `-ngl 34` does what it does. `-ngl 35` is expected I think. There's missing implementation in `ggml-cuda.cu` for some special rope circumstances that only seem to happen when full model is offloaded. I don't think I can do anything about it (I don't feel anywhere near qualified enough to touch cuda stuff). We could probably add some sort of guard not to offload more than 33 layers as a temporary solution.

**Comment by goerch** [comment]
Only wish: let it run through the appropriate tokenizer test.

**Comment by Galunid** [comment]
@goerch Could you confirm this is what you wanted?
I ran
1. `python convert-stablelm-hf-to-gguf.py --vocab-only models/stablelm-3b-4e1t`
2. `./test-tokenizer-1-bpe ../models/stablelm-3b-4e1t/ggml-model-f16.gguf`

<details>
<summary>Model uses `gpt2` as tokenizer, output is</summary>

```
main : reading vocab from: '../models/stablelm-3b-4e1t/ggml-model-f16.gguf'
llama_model_loader: loaded meta data with 16 key-value pairs and 0 tensors from ../models/stablelm-3b-4e1t/ggml-model-f16.gguf (version unknown)
llama_model_loader: - kv   0:                       general.architecture str     
llama_model_loader: - kv   1:                               general.name str     
llama_model_loader: - kv   2:                    stablelm.context_length u32     
llama_model_loader: - kv   3:                  stablelm.embedding_length u32     
llama_model_loader: - kv   4:                       stablelm.block_count u32     
llama_model_loader: - kv   5:               stablelm.feed_forward_length u32     
llama_model_loader: - kv   6:              stablelm.rope.dimension_count u32     
llama_model_loader: - kv   7:              stablelm.attention.head_count u32     
llama_model_loader: - kv   8:             stablelm.use_parallel_residual bool    
llama_model_loader: - kv   9:      stablelm.attention.layer_norm_epsilon f32     
llama_model_loader: - kv  10:                       tokenizer.ggml.model str     
llama_model_loader: - kv  11:                      tokenizer.ggml.tokens arr     
llama_model_loader: - kv  12:                  tokenizer.ggml.token_type arr     
llama_model_loader: - kv  13:                      tokenizer.ggml.merges arr     
llama_model_loader: - kv  14:                tokenizer.ggml.bos_token_id u32     
llama_model_loader: - kv  15:                tokenizer.ggml.eos_token_id u32     
llm_load_vocab: mismatch in special tokens definition ( 31/50304 vs 52/50304 ).
llm_load_print_meta: format           = unknown
llm_load_print_meta: arch             = stablelm
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 50304
llm_load_print_meta: n_merges         = 50009
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 2560
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 20
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: f_norm_eps       = 1.0e-05
llm_load_print_meta: f_norm_rms_eps   = 0.0e+00
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 6912
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: model type       = 3B
llm_load_print_meta: model ftype      = all F32 (guessed)
llm_load_print_meta: model params     = 0.00 B
llm_load_print_meta: model size       = 0.00 MiB (-nan BPW) 
llm_load_print_meta: general.name   = stablelm-3b-4e1t
llm_load_print_meta: BOS token = 0 '<|endoftext|>'
llm_load_print_meta: EOS token = 0 '<|endoftext|>'
llm_load_print_meta: LF token  = 128 'Ä'
llama_model_load: vocab only - skipping tensors
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
main : info: utf8 conversion 96 '�'
main : info: utf8 conversion 97 '�'
main : info: utf8 conversion 98 '�'
main : info: utf8 conversion 99 '�'
main : info: utf8 conversion 100 '�'
main : info: utf8 conversion 101 '�'
main : info: utf8 conversion 102 '�'
main : info: utf8 conversion 103 '�'
main : info: utf8 conversion 104 '�'
main : info: utf8 conversion 105 '�'
main : info: utf8 conversion 106 '�'
main : info: utf8 conversion 107 '�'
main : info: utf8 conversion 108 '�'
main : info: utf8 conversion 109 '�'
main : info: utf8 conversion 110 '�'
main : info: utf8 conversion 111 '�'
main : info: utf8 conversion 112 '�'
main : info: utf8 conversion 113 '�'
main : info: utf8 conversion 114 '�'
main : info: utf8 conversion 115 '�'
main : info: utf8 conversion 116 '�'
main : info: utf8 conversion 117 '�'
main : info: utf8 conversion 118 '�'
main : info: utf8 conversion 119 '�'
main : info: utf8 conversion 120 '�'
main : info: utf8 conversion 121 '�'
main : info: utf8 conversion 122 '�'
main : info: utf8 conversion 123 '�'
main : info: utf8 conversion 124 '�'
main : info: utf8 conversion 125 '�'
main : info: utf8 conversion 126 '�'
main : info: utf8 conversion 127 '�'
main : info: utf8 conversion 128 '�'
main : info: utf8 conversion 129 '�'
main : info: utf8 conversion 130 '�'
main : info: utf8 conversion 131 '�'
main : info: utf8 conversion 132 '�'
main : info: utf8 conversion 133 '�'
main : info: utf8 conversion 134 '�'
main : info: utf8 conversion 135 '�'
main : info: utf8 conversion 136 '�'
main : info: utf8 conversion 137 '�'
main : info: utf8 conversion 138 '�'
main : info: utf8 conversion 139 '�'
main : info: utf8 conversion 140 '�'
main : info: utf8 conversion 141 '�'
main : info: utf8 conversion 142 '�'
main : info: utf8 conversion 143 '�'
main : info: utf8 conversion 144 '�'
main : info: utf8 conversion 145 '�'
main : info: utf8 conversion 146 '�'
main : info: utf8 conversion 147 '�'
main : info: utf8 conversion 148 '�'
main : info: utf8 conversion 149 '�'
main : info: utf8 conversion 150 '�'
main : info: utf8 conversion 151 '�'
main : info: utf8 conversion 152 '�'
main : info: utf8 conversion 153 '�'
main : info: utf8 conversion 154 '�'
main : info: utf8 conversion 155 '�'
main : info: utf8 conversion 156 '�'
main : info: utf8 conversion 157 '�'
main : info: utf8 conversion 158 '�'
main : info: utf8 conversion 159 '�'
main : info: utf8 conversion 160 '�'
main : info: utf8 conversion 161 '�'
main : info: utf8 conversion 162 '�'
main : info: utf8 conversion 163 '�'
main : info: utf8 conversion 164 '�'
main : info: utf8 conversion 165 '�'
main : info: utf8 conversion 166 '�'
main : info: utf8 conversion 167 '�'
main : info: utf8 conversion 168 '�'
main : info: utf8 conversion 169 '�'
main : info: utf8 conversion 170 '�'
main : info: utf8 conversion 171 '�'
main : info: utf8 conversion 172 '�'
main : info: utf8 conversion 173 '�'
main : info: utf8 conversion 174 '�'
main : info: utf8 conversion 175 '�'
main : info: utf8 conversion 176 '�'
main : info: utf8 conversion 211 '�'
main : info: utf8 conversion 212 '�'
main : info: utf8 conversion 213 '�'
main : info: utf8 conversion 214 '�'
main : info: utf8 conversion 215 '�'
main : info: utf8 conversion 216 '�'
main : info: utf8 conversion 217 '�'
main : info: utf8 conversion 218 '�'
main : info: utf8 conversion 219 '�'
main : info: utf8 conversion 220 '�'
main : info: utf8 conversion 221 '�'
main : info: utf8 conversion 222 '�'
main : info: utf8 conversion 223 '�'
main : info: utf8 conversion 224 '�'
main : info: utf8 conversion 225 '�'
main : info: utf8 conversion 226 '�'
main : info: utf8 conversion 227 '�'
main : info: utf8 conversion 228 '�'
main : info: utf8 conversion 229 '�'
main : info: utf8 conversion 230 '�'
main : info: utf8 conversion 231 '�'
main : info: utf8 conversion 232 '�'
main : info: utf8 conversion 233 '�'
main : info: utf8 conversion 234 '�'
main : info: utf8 conversion 235 '�'
main : info: utf8 conversion 236 '�'
main : info: utf8 conversion 237 '�'
main : info: utf8 conversion 238 '�'
main : info: utf8 conversion 239 '�'
main : info: utf8 conversion 240 '�'
main : info: utf8 conversion 241 '�'
main : info: utf8 conversion 242 '�'
main : info: utf8 conversion 243 '�'
main : info: utf8 conversion 244 '�'
main : info: utf8 conversion 325 '�'
main : info: utf8 conversion 541 ' �'
main : info: utf8 conversion 765 '�'
main : info: utf8 conversion 929 ' �'
main : info: utf8 conversion 1191 ' �'
main : info: utf8 conversion 1325 ' �'
main : info: utf8 conversion 1357 '�'
main : info: utf8 conversion 1454 ' �'
main : info: utf8 conversion 1769 '�'
main : info: utf8 conversion 1819 'о�'
main : info: utf8 conversion 1853 '�'
main : info: utf8 conversion 2155 '�'
main : info: utf8 conversion 2467 'а�'
main : info: utf8 conversion 2483 '�'
main : info: utf8 conversion 2869 '�'
main : info: utf8 conversion 2871 'е�'
main : info: utf8 conversion 3193 '�'
main : info: utf8 conversion 3218 '�'
main : info: utf8 conversion 3384 ' �'
main : info: utf8 conversion 4954 ' �'
main : info: utf8 conversion 5138 '�'
main : info: utf8 conversion 5494 '�'
main : info: utf8 conversion 5690 '�'
main : info: utf8 conversion 5941 '�'
main : info: utf8 conversion 5959 '�'
main : info: utf8 conversion 6078 ' �'
main : info: utf8 conversion 6123 '�'
main : info: utf8 conversion 6280 ' �'
main : info: utf8 conversion 6765 '�'
main : info: utf8 conversion 6810 ' �'
main : info: utf8 conversion 6829 '�'
main : info: utf8 conversion 6916 '�'
main : info: utf8 conversion 7056 '�'
main : info: utf8 conversion 7111 '�'
main : info: utf8 conversion 7183 '�'
main : info: utf8 conversion 7226 '�'
main : info: utf8 conversion 7249 '�'
main : info: utf8 conversion 7297 '�'
main : info: utf8 conversion 7719 '�'
main : info: utf8 conversion 7772 '�'
main : info: utf8 conversion 7775 ' �'
main : info: utf8 conversion 7786 ' �'
main : info: utf8 conversion 8082 '�'
main : info: utf8 conversion 8318 '��'
main : info: utf8 conversion 8587 '�'
main : info: utf8 conversion 8611 ' �'
main : info: utf8 conversion 8650 '�'
main : info: utf8 conversion 8841 '�'
main : info: utf8 conversion 9053 '�'
main : info: utf8 conversion 9078 '�'
main : info: utf8 conversion 9223 '��'
main : info: utf8 conversion 9504 '�'
main : info: utf8 conversion 9702 '�'
main : info: utf8 conversion 9799 '�'
main : info: utf8 conversion 10041 '�'
main : info: utf8 conversion 10361 '�'
main : info: utf8 conversion 10460 '�'
main : info: utf8 conversion 10608 ' �'
main : info: utf8 conversion 10623 '�'
main : info: utf8 conversion 10673 '�'
main : info: utf8 conversion 10674 '�'
main : info: utf8 conversion 10681 '�'
main : info: utf8 conversion 10714 'ا�'
main : info: utf8 conversion 10716 '�'
main : info: utf8 conversion 10897 '�'
main : info: utf8 conversion 10962 '�'
main : info: utf8 conversion 11016 '�'
main : info: utf8 conversion 11043 '�'
main : info: utf8 conversion 11437 ' �'
main : info: utf8 conversion 11800 '�'
main : info: utf8 conversion 11827 '�'
main : info: utf8 conversion 11871 '�'
main : info: utf8 conversion 11894 '�'
main : info: utf8 conversion 12005 '�'
main : info: utf8 conversion 12268 '�'
main : info: utf8 conversion 12272 '�'
main : info: utf8 conversion 12363 '�'
main : info: utf8 conversion 12448 'ー�'
main : info: utf8 conversion 12462 '�'
main : info: utf8 conversion 12483 '�'
main : info: utf8 conversion 12613 '�'
main : info: utf8 conversion 12676 '�'
main : info: utf8 conversion 12755 '�'
main : info: utf8 conversion 12811 '�'
main : info: utf8 conversion 12859 'ו�'
main : info: utf8 conversion 12984 '�'
main : info: utf8 conversion 13076 '��'
main : info: utf8 conversion 13127 '�'
main : info: utf8 conversion 13180 '�'
main : info: utf8 conversion 13246 ' �'
main : info: utf8 conversion 13258 '�'
main : info: utf8 conversion 13262 '�'
main : info: utf8 conversion 13486 '�'
main : info: utf8 conversion 13499 '�'
main : info: utf8 conversion 13744 '�'
main : info: utf8 conversion 13764 '�'
main : info: utf8 conversion 13963 'י�'
main : info: utf8 conversion 14129 '�'
main : info: utf8 conversion 14239 ' �'
main : info: utf8 conversion 14262 '�'
main : info: utf8 conversion 14318 '�'
main : info: utf8 conversion 14378 '�'
main : info: utf8 conversion 14394 '�'
main : info: utf8 conversion 14486 '�'
main : info: utf8 conversion 14489 '�'
main : info: utf8 conversion 14670 '�'
main : info: utf8 conversion 14931 '�'
main : info: utf8 conversion 14945 '�'
main : info: utf8 conversion 15074 '�'
main : info: utf8 conversion 15176 '�'
main : info: utf8 conversion 15446 '�'
main : info: utf8 conversion 15756 '�'
main : info: utf8 conversion 15868 '�'
main : info: utf8 conversion 15899 '�'
main : info: utf8 conversion 15911 '��'
main : info: utf8 conversion 15954 '�'
main : info: utf8 conversion 15957 '�'
main : info: utf8 conversion 16127 '�'
main : info: utf8 conversion 16141 ' �'
main : info: utf8 conversion 16385 '�'
main : info: utf8 conversion 16482 '�'
main : info: utf8 conversion 16549 '�'
main : info: utf8 conversion 16787 '�'
main : info: utf8 conversion 16800 '�'
main : info: utf8 conversion 16805 '�'
main : info: utf8 conversion 16818 '�'
main : info: utf8 conversion 16849 '�'
main : info: utf8 conversion 16857 ' �'
main : info: utf8 conversion 16998 '�'
main : info: utf8 conversion 17289 '�'
main : info: utf8 conversion 17321 '�'
main : info: utf8 conversion 17474 '�'
main : info: utf8 conversion 17559 '�'
main : info: utf8 conversion 17598 '�'
main : info: utf8 conversion 17783 '�'
main : info: utf8 conversion 17865 '�'
main : info: utf8 conversion 17955 '�'
main : info: utf8 conversion 18081 '�'
main : info: utf8 conversion 18245 '�'
main : info: utf8 conversion 18537 '�'
main : info: utf8 conversion 18617 '�'
main : info: utf8 conversion 18713 '��'
main : info: utf8 conversion 18751 '�'
main : info: utf8 conversion 18947 '�'
main : info: utf8 conversion 19119 '�'
main : info: utf8 conversion 19127 '�'
main : info: utf8 conversion 19218 '�'
main : info: utf8 conversion 19597 '�'
main : info: utf8 conversion 19621 ' ال�'
main : info: utf8 conversion 19675 '��'
main : info: utf8 conversion 19780 '�'
main : info: utf8 conversion 19957 '�'
main : info: utf8 conversion 20031 '�'
main : info: utf8 conversion 20241 '�'
main : info: utf8 conversion 20286 '�'
main : info: utf8 conversion 20345 '�'
main : info: utf8 conversion 20422 '�'
main : info: utf8 conversion 20516 'า�'
main : info: utf8 conversion 20557 '�'
main : info: utf8 conversion 20616 '�'
main : info: utf8 conversion 20647 '�'
main : info: utf8 conversion 20827 '�'
main : info: utf8 conversion 20833 '�'
main : info: utf8 conversion 21053 '�'
main : info: utf8 conversion 21121 '�'
main : info: utf8 conversion 21163 '�'
main : info: utf8 conversion 21283 '�'
main : info: utf8 conversion 21365 '�'
main : info: utf8 conversion 21367 '�'
main : info: utf8 conversion 21422 '�'
main : info: utf8 conversion 21555 '�'
main : info: utf8 conversion 21683 '�'
main : info: utf8 conversion 21700 '�'
main : info: utf8 conversion 21944 '�'
main : info: utf8 conversion 21998 '�'
main : info: utf8 conversion 22150 '�'
main : info: utf8 conversion 22305 '�'
main : info: utf8 conversion 22379 '�'
main : info: utf8 conversion 22470 '�'
main : info: utf8 conversion 22580 '�'
main : info: utf8 conversion 22692 ' �'
main : info: utf8 conversion 22701 '�'
main : info: utf8 conversion 22760 ' �'
main : info: utf8 conversion 22983 '�'
main : info: utf8 conversion 22985 '�'
main : info: utf8 conversion 23101 'เ�'
main : info: utf8 conversion 23692 '�'
main : info: utf8 conversion 23823 '�'
main : info: utf8 conversion 23825 '�'
main : info: utf8 conversion 23956 '�'
main : info: utf8 conversion 23969 ' �'
main : info: utf8 conversion 24299 '�'
main : info: utf8 conversion 24379 '�'
main : info: utf8 conversion 24384 '��'
main : info: utf8 conversion 24545 '�'
main : info: utf8 conversion 25086 '�'
main : info: utf8 conversion 25516 ' �'
main : info: utf8 conversion 25541 '�'
main : info: utf8 conversion 25558 'ン�'
main : info: utf8 conversion 25657 '�'
main : info: utf8 conversion 25715 '�'
main : info: utf8 conversion 25762 '�'
main : info: utf8 conversion 25811 ' �'
main : info: utf8 conversion 26036 '�'
main : info: utf8 conversion 26151 '�'
main : info: utf8 conversion 26335 '�'
main : info: utf8 conversion 26437 '�'
main : info: utf8 conversion 26473 ' �'
main : info: utf8 conversion 26487 '�'
main : info: utf8 conversion 26532 '�'
main : info: utf8 conversion 26581 '�'
main : info: utf8 conversion 26601 '�'
main : info: utf8 conversion 26844 '�'
main : info: utf8 conversion 26974 '�'
main : info: utf8 conversion 27107 '�'
main : info: utf8 conversion 27258 '�'
main : info: utf8 conversion 27344 ' �'
main : info: utf8 conversion 27374 '�'
main : info: utf8 conversion 27582 '�'
main : info: utf8 conversion 27661 '�'
main : info: utf8 conversion 27712 '�'
main : info: utf8 conversion 27739 '�'
main : info: utf8 conversion 27750 '�'
main : info: utf8 conversion 27997 '�'
main : info: utf8 conversion 28215 '�'
main : info: utf8 conversion 28492 '�'
main : info: utf8 conversion 28607 '�'
main : info: utf8 conversion 28650 '�'
main : info: utf8 conversion 28774 '�'
main : info: utf8 conversion 28812 '�'
main : info: utf8 conversion 28888 '�'
main : info: utf8 conversion 28915 '�'
main : info: utf8 conversion 28917 '�'
main : info: utf8 conversion 29268 '�'
main : info: utf8 conversion 29333 '�'
main : info: utf8 conversion 29597 '�'
main : info: utf8 conversion 29626 '�'
main : info: utf8 conversion 29785 '�'
main : info: utf8 conversion 29832 '�'
main : info: utf8 conversion 29852 '�'
main : info: utf8 conversion 30086 '�'
main : info: utf8 conversion 30088 '�'
main : info: utf8 conversion 30093 '�'
main : info: utf8 conversion 30255 '�'
main : info: utf8 conversion 30590 '�'
main : info: utf8 conversion 30676 '�'
main : info: utf8 conversion 30834 'ư�'
main : info: utf8 conversion 31165 ' �'
main : info: utf8 conversion 31498 '�'
main : info: utf8 conversion 31554 '�'
main : info: utf8 conversion 31600 '�'
main : info: utf8 conversion 31811 '�'
main : info: utf8 conversion 31828 ' �'
main : info: utf8 conversion 31902 '�'
main : info: utf8 conversion 31956 '�'
main : info: utf8 conversion 31963 ' �'
main : info: utf8 conversion 32026 '�'
main : info: utf8 conversion 32053 '�'
main : info: utf8 conversion 32115 ' �'
main : info: utf8 conversion 32120 '�'
main : info: utf8 conversion 32141 'ა�'
main : info: utf8 conversion 32262 ' ا�'
main : info: utf8 conversion 32283 '�'
main : info: utf8 conversion 32363 '�'
main : info: utf8 conversion 32403 '�'
main : info: utf8 conversion 32417 '�'
main : info: utf8 conversion 32653 '�'
main : info: utf8 conversion 32654 '�'
main : info: utf8 conversion 32750 '�'
main : info: utf8 conversion 32790 '�'
main : info: utf8 conversion 33057 '�'
main : info: utf8 conversion 33089 '�'
main : info: utf8 conversion 33104 '�'
main : info: utf8 conversion 33369 '�'
main : info: utf8 conversion 33656 '�'
main : info: utf8 conversion 33700 '�'
main : info: utf8 conversion 33836 '�'
main : info: utf8 conversion 34138 '�'
main : info: utf8 conversion 34271 ' �'
main : info: utf8 conversion 34372 '�'
main : info: utf8 conversion 34431 '�'
main : info: utf8 conversion 34556 '�'
main : info: utf8 conversion 34693 '�'
main : info: utf8 conversion 34749 ' �'
main : info: utf8 conversion 34918 '��'
main : info: utf8 conversion 34996 ' �'
main : info: utf8 conversion 35072 '�'
main : info: utf8 conversion 35169 '�'
main : info: utf8 conversion 35257 ' �'
main : info: utf8 conversion 35259 'シ�'
main : info: utf8 conversion 35305 ' �'
main : info: utf8 conversion 35392 '�'
main : info: utf8 conversion 35458 '�'
main : info: utf8 conversion 35801 '�'
main : info: utf8 conversion 35973 '��'
main : info: utf8 conversion 36087 '�'
main : info: utf8 conversion 36178 '�'
main : info: utf8 conversion 36337 '�'
main : info: utf8 conversion 36387 '�'
main : info: utf8 conversion 36720 '�'
main : info: utf8 conversion 36771 'ա�'
main : info: utf8 conversion 37215 '�'
main : info: utf8 conversion 37300 '�'
main : info: utf8 conversion 37531 '�'
main : info: utf8 conversion 37661 '�'
main : info: utf8 conversion 37679 '�'
main : info: utf8 conversion 37769 '�'
main : info: utf8 conversion 37794 '�'
main : info: utf8 conversion 37895 '�'
main : info: utf8 conversion 37933 '�'
main : info: utf8 conversion 38053 '�'
main : info: utf8 conversion 38262 '�'
main : info: utf8 conversion 38672 '�'
main : info: utf8 conversion 38675 '�'
main : info: utf8 conversion 38822 '�'
main : info: utf8 conversion 38892 'フ�'
main : info: utf8 conversion 38897 '�'
main : info: utf8 conversion 39068 '��'
main : info: utf8 conversion 39146 'ე�'
main : info: utf8 conversion 39393 '�'
main : info: utf8 conversion 39429 '�'
main : info: utf8 conversion 39915 '�'
main : info: utf8 conversion 39936 '�'
main : info: utf8 conversion 40025 '�'
main : info: utf8 conversion 40153 '�'
main : info: utf8 conversion 40162 '�'
main : info: utf8 conversion 40329 '�'
main : info: utf8 conversion 40843 '�'
main : info: utf8 conversion 41514 ' �'
main : info: utf8 conversion 41777 '�'
main : info: utf8 conversion 41986 '�'
main : info: utf8 conversion 42025 '�'
main : info: utf8 conversion 42490 'ი�'
main : info: utf8 conversion 42984 ' �'
main : info: utf8 conversion 43033 '�'
main : info: utf8 conversion 43641 '�'
main : info: utf8 conversion 43710 ' �'
main : info: utf8 conversion 43894 '�'
main : info: utf8 conversion 44020 '�'
main : info: utf8 conversion 44028 '�'
main : info: utf8 conversion 44140 '��'
main : info: utf8 conversion 44246 '�'
main : info: utf8 conversion 44508 '�'
main : info: utf8 conversion 44633 '�'
main : info: utf8 conversion 44966 '�'
main : info: utf8 conversion 45128 '�'
main : info: utf8 conversion 45387 '�'
main : info: utf8 conversion 46180 '�'
main : info: utf8 conversion 46291 '�'
main : info: utf8 conversion 46438 ' �'
main : info: utf8 conversion 46791 '�'
main : info: utf8 conversion 46927 ' �'
main : info: utf8 conversion 46979 '�'
main : info: utf8 conversion 46982 '�'
main : info: utf8 conversion 46992 '�'
main : info: utf8 conversion 47568 ' �'
main : info: utf8 conversion 48078 '�'
main : info: utf8 conversion 48153 '�'
main : info: utf8 conversion 48604 '�'
main : info: utf8 conversion 48672 '�'
main : info: utf8 conversion 48807 ' �'
main : info: utf8 conversion 48897 '�'
main : info: utf8 conversion 49042 ' �'
main : info: utf8 conversion 49070 '�'
main : info: utf8 conversion 49113 '�'
main : info: utf8 conversion 49233 '�'
main : info: utf8 conversion 49460 ' �'
main : info: utf8 conversion 49835 '�'
main : info: utf8 conversion 50152 '�'
```
</details>

**Comment by goerch** [comment]
> Could you confirm this is what you wanted?

Excellent. Now add 

* the vocabulary to the `model` directory
* the test case to the corresponding `CMakeLists.txt`

and you are done.

File: tests/CMakeLists.txt [hunk 2]
```diff
@@ -33,9 +33,11 @@ llama_build_executable(test-tokenizer-1-bpe.cpp)
 llama_test_executable (test-tokenizer-1-falcon test-tokenizer-1-bpe.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../models/ggml-vocab-falcon.gguf)
 llama_test_executable(test-tokenizer-1-aquila test-tokenizer-1-bpe.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../models/ggml-vocab-aquila.gguf)
 llama_test_executable(test-tokenizer-1-mpt test-tokenizer-1-bpe.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../models/ggml-vocab-mpt.gguf)
+llama_test_executable(test-tokenizer-1-stablelm-3b-4e1t test-tokenizer-1-bpe.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../models/ggml-vocab-stablelm-3b-4e1t.gguf)
 llama_test_executable(test-tokenizer-1-gpt-neox test-tokenizer-1-bpe.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../models/ggml-vocab-gpt-neox.gguf)
 llama_test_executable(test-tokenizer-1-refact test-tokenizer-1-bpe.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../models/ggml-vocab-refact.gguf)
 llama_test_executable(test-tokenizer-1-starcoder test-tokenizer-1-bpe.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../models/ggml-vocab-starcoder.gguf)
+# llama_test_executable(test-tokenizer-1-bloom test-tokenizer-1-bpe.cpp ${CMAKE_CURRENT_SOURCE_DIR}/../models/ggml-vocab-bloom.gguf) # BIG
```
Comment (Galunid) [inline tests/CMakeLists.txt:40]: I missed comment asking me to keep it just commented out in another PR (#3742)

**Review by Green-Sky — COMMENTED** [review]
```
gguf: loading model stablelm-3b-4e1t
This gguf file is for Little Endian only
gguf: get model metadata
gguf: get tokenizer metadata
gguf: get gpt2 tokenizer vocab
Traceback (most recent call last):
  File "/home/green/workspace/llama.cpp/./convert-stablelm-hf-to-gguf.py", line 123, in <module>
    if tokenizer.added_tokens_decoder[i].special:
AttributeError: 'GPTNeoXTokenizerFast' object has no attribute 'added_tokens_decoder'
```

**Comment by goerch** [comment]
I don't remember if you have the detokenization problem with added tokens here, too. But https://github.com/ggerganov/llama.cpp/pull/3760 should heal it.

**Comment by goerch** [comment]
One more question: is this

```
        tokens.append(f"[PAD{i}]")
        toktypes.append(gguf.TokenType.USER_DEFINED)
```

the correct token type for padding tokens? I'm sceptical, will try some tests.

**Comment by Green-Sky** [comment]
went scouting for models based on 3b-4e1t, and found these instruction tuned models:
- https://huggingface.co/pansophic/slimorca-stablelm-3b-4e1t
- https://huggingface.co/acrastt/Marx-3B-V3

**Comment by Galunid** [comment]
@goerch Taken from https://github.com/ggerganov/llama.cpp/issues/3730#issuecomment-1775188360 ;-)
I think at the time there wasn't distinction between `USER_DEFINED` and `CONTROL`, so it didn't matter. Perhaps it should actually be `CONTROL`, since those shouldn't be displayed, right?



> > went scouting for models based on 3b-4e1t, and found these instruction tuned models:
> > ```
> > * https://huggingface.co/pansophic/slimorca-stablelm-3b-4e1t
> > 
> > * https://huggingface.co/acrastt/Marx-3B-V3
> > ```
> 
> and they both don't provide a `safetensor` file but a `pytorch_model.bin` 🙃

@Green-Sky So *that's why* some scripts support both... 😄
I'll change the script accordingly

**Comment by goerch** [comment]
> I think at the time there wasn't distinction between `USER_DEFINED` and `CONTROL`, so it didn't matter. Perhaps it should actually be `CONTROL`, since those shouldn't be displayed, right?

Yes. It seems even worse too me, because

```
    std::vector<llama_token> tokens = llama_tokenize(ctx, "[PAD50277]", false, true);
```

resolves to the token 50277.

**Comment by Green-Sky** [comment]
> @Green-Sky So that's why some scripts support both... 😄
I'll change the script accordingly

I hacked it to read the `pytorch_model.bin` and it seems to work.
Testing with the slimorca finetune, it seems to be doing ok. I'm supprised it does not display the `<|im_start|>` and end tokens anymore. makes debugging why the reverse prompt doesn't trigger kinda hard...

<details><summary>Details</summary>

```
llm_load_vocab: mismatch in special tokens definition ( 31/50304 vs 50/50304 ).
llm_load_print_meta: format           = unknown
llm_load_print_meta: arch             = stablelm
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 50304
llm_load_print_meta: n_merges         = 50009
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 2560
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 20
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: f_norm_eps       = 1.0e-05
llm_load_print_meta: f_norm_rms_eps   = 0.0e+00
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 6912
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: model type       = 3B
llm_load_print_meta: model ftype      = mostly F16 (guessed)
llm_load_print_meta: model params     = 2.80 B
llm_load_print_meta: model size       = 5.21 GiB (16.00 BPW)
llm_load_print_meta: general.name   = slimorca-stablelm-3b-4e1t
llm_load_print_meta: BOS token = 0 '<|endoftext|>'
llm_load_print_meta: EOS token = 0 '<|endoftext|>'
llm_load_print_meta: UNK token = 0 '<|endoftext|>'
llm_load_print_meta: LF token  = 128 'Ä'
llm_load_tensors: ggml ctx size =    0.12 MB
llm_load_tensors: mem required  = 5332.64 MB
.............................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: kv self size  =  160.00 MB
llama_new_context_with_model: compute buffer total size = 114.38 MB

system_info: n_threads = 12 / 24 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
main: interactive mode on.
Reverse prompt: '<|im_start|>user'
Input suffix: '<|im_end|>
<|im_start|>assistant
'
sampling:
	repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, typical_p = 1.000, temp = 0.800
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

system
You are an advanced and helpful AI assistant.
user
How are you?
assistant
I am doing well, thank you! How about you?

In response to your question, the term "How are you

llama_print_timings:        load time =     422.14 ms
llama_print_timings:      sample time =      11.00 ms /    26 runs   (    0.42 ms per token,  2364.28 tokens per second)
llama_print_timings: prompt eval time =     856.11 ms /    27 tokens (   31.71 ms per token,    31.54 tokens per second)
llama_print_timings:        eval time =    3271.42 ms /    26 runs   (  125.82 ms per token,     7.95 tokens per second)
llama_print_timings:       total time =   10908.29 ms
```

</details> 

did the testing on the commit before https://github.com/ggerganov/llama.cpp/pull/3586/commits/fa2cd7e7b906581cc76bb6e743624c51abe28dee , because of the aforementioned error.

**Comment by Galunid** [comment]
> I'm supprised it does not display the <|im_start|> and end tokens anymore. makes debugging why the reverse prompt doesn't trigger kinda hard...

I think it should be resolved by #3760

**Comment by Galunid** [comment]
> Yes. It seems even worse too me, because
> 
> ```
>     std::vector<llama_token> tokens = llama_tokenize(ctx, "[PAD50277]", false, true);
> ```
> 
> resolves to the token 50277.

Isn't that the whole idea though? That pad token resolves to a non existent token in a provided vocab, that we add? I thought it was just the difference of whether we display that token or not. Under normal circumstances model shouldn't even generate them, unless I got something wrong, in which case please do correct me.

**Comment by goerch** [comment]
> I'm supprised it does not display the `<|im_start|>` and end tokens anymore. makes debugging why the reverse prompt doesn't trigger kinda hard

So you expect `<|im_start|>` in the output of the detokenizer? Then it would be a USER_DEFINED token and you could inject it in the tokenizer. I'm not sure that is what we want. 

> I think it should be resolved by #3760

Only if we eliminate the special token handling

```
        if tokenizer.added_tokens_decoder[i].special:
            toktypes.append(gguf.TokenType.CONTROL)
        else:
            toktypes.append(gguf.TokenType.USER_DEFINED)
```

**Comment by Green-Sky** [comment]
> So you expect `<|im_start|>` in the output of the detokenizer? Then it would be a USER_DEFINED token and you could inject it in the tokenizer. I'm not sure that is what we want.

hm, maybe not? It was just the behavior before.
Looking at the [OpenAI ChatML docs](https://github.com/openai/openai-python/blob/main/chatml.md), they seems to manually specify the special tokens as tokens, so not embedded in the text.

**Comment by Galunid** [comment]
<details>
<summary>tokenizer.json snippet</summary>

```json
{
      "id": 0,
      "content": "<|endoftext|>",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": false,
      "special": true
    },
    {
      "id": 1,
      "content": "<|padding|>",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": false,
      "special": true
    },
    {
      "id": 50254,
      "content": "                        ",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": true,
      "special": false
    },
    [...]
```
</details>

`<|endoftext|>`  has  `"special": true` specified, while the rest don't, interestingly, `<|im_start|>` is not present in any of the `tokenizer.json` files (from stablelm, and finetunes), so it should(?) be displayed.

**Comment by goerch** [comment]
> Isn't that the whole idea though? That pad token resolves to a non existent token in a provided vocab, that we add? I thought it was just the difference of whether we display that token or not. Under normal circumstances model shouldn't even generate them, unless I got something wrong, in which case please do correct me.
> 
> In any case I assume we should change pad tokens to `CONTROL` type here and in the other scripts?

As I understand it HF tokenizer encodes and decodes special tokens (`CONTROL`). `llama.cpp` deviates in subtle ways. 

- we currently encode and decode special tokens for `gpt2` (special tokens have token type `USER_DEFINED`, which I believe is wrong)
- we currently only encode special tokens for `sentencepiece`,  the core tokenizer doesn't understand `<unk>`, `<s>` and `</s>` AFAIK
- HF tokenizer doesn't return padding tokens, but we could generate them incidentally when tokenizing.

**Comment by Galunid** [comment]
> Edit: forgot to mention that I'm only checking stablelm-base-alpha-7b and no derived models here.

Wait, do those work? Afaik this should support stablelm-3b-4e1t only, since the other models were very, very bad. It's probably good idea to explicitly mention they don't work. They should work with `GPTNeox`, at least according to `config.json`

**Comment by goerch** [comment]
> Wait, do those work?

Didn't check, I'm only interested in the HF tokenizer. Downloading `stablelm-3b-4e1t` now to recheck.

**Comment by Green-Sky** [comment]
> since the other models were very, very bad.

**Comment by Green-Sky** [comment]
> Edit: forgot to mention that I'm only checking stablelm-base-alpha-7b and no derived models her

**Comment by Green-Sky** [comment]
> You need to update your 'transformers' package to at least v4.34.0.

time to update the `flake.lock` file. (exact 2 month update)



@Galunid tested the script update, works.
also, the layer offload limit does not seem to work:

### -ngl 99
```
$ perplexity -f wikitext-2-raw/wiki.test.raw --chunks 300 -m models/stablelm-3b-4e1t/ggml-model-Q4_0.gguf -ngl 99
...
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =   69.84 MB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/35 layers to GPU
llm_load_tensors: VRAM used: 1462.63 MB
...
llama_new_context_with_model: kv self size  =  160.00 MB
llama_new_context_with_model: compute buffer total size = 114.38 MB
llama_new_context_with_model: VRAM scratch buffer: 108.25 MB
llama_new_context_with_model: total VRAM used: 1731.51 MB (model: 1463.26 MB, context: 268.25 MB)
GGML_ASSERT: /build/licsh6vbh1qqk0qwhr230p2hfyspqds3-source/ggml-cuda.cu:6402: ne00 == n_dims && "ne00 != n_dims is not implemented for CUDA yet"
Aborted (core dumped)
```

### -ngl 33
```
$ perplexity -f wikitext-2-raw/wiki.test.raw --chunks 300 -m models/stablelm-3b-4e1t/ggml-model-Q4_0.gguf -ngl 33
...
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =   69.84 MB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/35 layers to GPU
llm_load_tensors: VRAM used: 1462.63 MB
...
llama_new_context_with_model: kv self size  =  160.00 MB
llama_new_context_with_model: compute buffer total size = 114.38 MB
llama_new_context_with_model: VRAM scratch buffer: 108.25 MB
llama_new_context_with_model: total VRAM used: 1571.51 MB (model: 1463.26 MB, context: 108.25 MB)

system_info: n_threads = 12 / 24 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
perplexity: tokenizing the input ..
perplexity: tokenization took 931.805 ms
perplexity: calculating perplexity over 300 chunks, batch_size=512
perplexity: 0.89 seconds per pass - ETA 4.45 minutes
[1]6.4009,[2]7.7110,[3]8.1174,
```

**Comment by Green-Sky** [comment]
did a perplexity test on the stableml-3e1t base model:

_300 chunks a 512_
| quant | size | ppl |
|-------|------|-----|
|f16    | 5.3G | 9.0473 +/- 0.08236 |
|q8_0   | 2.8G | 9.0450 +/- 0.08234 |
|q6_k   | 2.2G | 9.0620 +/- 0.08242 |
|q5_k_m | 1.9G | 9.1376 +/- 0.08330 |
|q4_0   | 1.5G | 9.5350 +/- 0.08705 |
|q4_k_m | 1.6G | 9.3465 +/- 0.08543 |
|q3_k_l | 1.5G | 9.6148 +/- 0.08754 |
|q3_k_s | 1.2G | 11.3222 +/- 0.10492 |
|q2_k   | 1.2G | 12.0076 +/- 0.11155 |

File: llama.cpp [hunk 3]
```diff
@@ -2980,6 +3011,89 @@ static void llm_load_tensors(
...
+                        ggml_backend_type backend_output;
+
+                        // Don't allow for offloading of more than 33 layers.
+                        // Offloading 34 layers causes model to respond with letter 'E'
+                        // Offloading 35 layers doesn't work because of missing cuda implementation for rope:
+                        // GGML_ASSERT: ggml-cuda.cu:6402: ne00 == n_dims && "ne00 != n_dims is not implemented for CUDA yet"
+                        if (n_gpu_layers > 33) {
+                            n_gpu_layers = 33;
+                        }
+
```
Comment (ggerganov) [inline llama.cpp:3030]: It should be implemented:

https://github.com/ggerganov/llama.cpp/blob/ba231e8a6dd8ad82acfe0e4d492ff7cef6b3f0a1/ggml-cuda.cu#L6481-L6507

**Review by ggerganov — COMMENTED** [review]
This arch looks like the same as LLaMA but with a few bias tensors, correct?

I think I have to revisit the way we add support for new models.
The current way involves a lot of code duplication even when the changes are very small. I will have to first fix #3382  before merging more model arches.

File: llama.cpp (hunk 3 above)
Comment (Galunid) [reply llama.cpp:3030]: > This arch looks like the same as LLaMA but with a few bias tensors, correct?

Yes, but the `rope` is from `gpt-neox`

Comment (Green-Sky) [reply llama.cpp:3030]: in a recent-ish discussion we observed that `gpt-neox rope` and `llama rope` are **the same**, except they are permuted. https://github.com/jzhang38/TinyLlama/issues/24#issuecomment-1737334573

but i am not entirely sure this really is the case. but it worked for tinyllama (we had a working gpt-neox version working before llama). see discussion.

Comment (Galunid) [reply llama.cpp:3030]: Forgot to mention, `StableLM` has a different `n_dim = rope_pct * (hidden_size // num_attention_heads) = 20`

> Position Embeddings: Rotary Position Embeddings ([Su et al., 2021](https://arxiv.org/abs/2104.09864)) applied to the first 25% of head embedding dimensions for improved throughput following [Black et al. (2022)](https://arxiv.org/pdf/2204.06745.pdf).

~ https://github.com/Stability-AI/StableLM

**Comment by qaziquza** [comment]
Can this be merged? Or no? I'd like this functionality dearly, considering that the best models in the 3B-parameter-range are currently StableLM based.

**Comment by ggerganov** [comment]
It has to be adapted to the recent changes related to build graphs (see #3382). Sorry for the extra work.
The RoPE issue might be possible to solve by simply applying the RoPE to a 1/4 view of the tensor.
If these things are resolved, we can merge

**Comment by Green-Sky** [comment]
#3838 is also going to enable more refactoring for this model. We can merge without the pr and its changes adopted, but it would be nice. It also should reduce the overall codesize of this pr.

**Comment by Galunid** [comment]
>It has to be adapted to the recent changes related to build graphs (see https://github.com/ggerganov/llama.cpp/issues/3382). Sorry for the extra work.

No worries, I expected as much when I opened the PR.

>The RoPE issue might be possible to solve by simply applying the RoPE to a 1/4 view of the tensor.

Is there some `ggml_*` function that allows for slicing tensors? The only ones I've seen are for reshaping and they assert that multiplied dimensions and `n_elements` match.

As a side note, is there a reason why 
https://github.com/ggerganov/llama.cpp/blob/48ade94538fa509465d71023e49d07aab0ec8cd5/llama.cpp#L3154-L3157
doesn't have integer values assigned (i. e. `LLM_ROPE_NEOX = 2,`)? I was a bit confused when I used that in place of `2` in `ggml_rope_custom` ;)

**Comment by ggerganov** [comment]
> Position Embeddings: Rotary Position Embeddings ([Su et al., 2021](https://arxiv.org/abs/2104.09864)) applied to the first 25% of head embedding dimensions for improved throughput following [Black et al. (2022)](https://arxiv.org/pdf/2204.06745.pdf).

I think you can create views with `ggml_view_3d` and apply rope to the views. See how Persimmon graph does it, although I am not 100% that it works correctly atm due to the recent refactoring.

> As a side note, is there a reason why

This enum is only meant to be used with `llm_build_` functions and not with the `ggml_` functions

**Comment by Galunid** [comment]
Btw, it seems https://github.com/ggerganov/llama.cpp/issues/3820 describes the same thing as https://github.com/ggerganov/llama.cpp/pull/3586#issuecomment-1774136084, so it's not an issue with this PR, but llama.cpp in general.

**Comment by JeroenAdam** [comment]
I'm trying to build the stablelm-support branch on Winndows and get errors:

D:\llama.cpp\llama.cpp(3135,99): error C2065: 'LLAMA_BACKEND_OFFLOAD': undeclared identifier [D:\llama.cpp\build\llama.vcxproj]
D:\llama.cpp\llama.cpp(3138,46): error C2065: 'LLAMA_BACKEND_OFFLOAD_SPLIT': undeclared identifier [D:\llama.cpp\build\llama.vcxproj]
D:\llama.cpp\llama.cpp(3166,101): error C2065: 'LLAMA_BACKEND_OFFLOAD': undeclared identifier [D:\llama.cpp\build\llama.vcxproj]
D:\llama.cpp\llama.cpp(3166,49): error C2737: 'backend': const object must be initialized [D:\llama.cpp\build\llama.vcxproj]
D:\llama.cpp\llama.cpp(3167,107): error C2065: 'LLAMA_BACKEND_OFFLOAD_SPLIT': undeclared identifier [D:\llama.cpp\build\llama.vcxproj]
D:\llama.cpp\llama.cpp(3167,49): error C2737: 'backend_split': const object must be initialized [D:\llama.cpp\build\llama.vcxproj]

**Comment by Galunid** [comment]
It seems one macro was renamed on master, it's fixed now

**Comment by JeroenAdam** [comment]
Thanks, I'm now running stablelm-3b-4e1t.q6_k.gguf and marx-3b-v3.Q6_K.gguf
Needless to say very fast inference on CPU only.

**Comment by Green-Sky** [comment]
### UPDATED
went scouting for models based on 3b-4e1t, and found these instruction tuned models:
- https://huggingface.co/pansophic/slimorca-stablelm-3b-4e1t
- https://huggingface.co/acrastt/Marx-3B-V3

update:
- https://huggingface.co/acrastt/Akins-3B
- https://huggingface.co/NousResearch/Nous-Capybara-3B-V1.9 (does not name 4e1t directly)
- https://huggingface.co/stabilityai/japanese-stablelm-3b-4e1t-base (continued transfer learning)
- https://huggingface.co/stabilityai/japanese-stablelm-3b-4e1t-instruct
- https://huggingface.co/PAIXAI/Astrid-3B
- https://huggingface.co/llmware/bling-stable-lm-3b-4e1t-v0 (RAG-instruct trained)
- https://huggingface.co/cxllin/StableHermes-3b
- https://huggingface.co/cxllin/StableMed-3b
- https://huggingface.co/jondurbin/airoboros-3b-3p0 (superseded by:)
- https://huggingface.co/jondurbin/airoboros-3b-3p11
- https://huggingface.co/Dimensity/Dimensity-3B
- https://huggingface.co/OpenBuddy/openbuddy-stablelm-3b-v13
- https://huggingface.co/bofenghuang/vigogne-stablelm-3b-4e1t-chat (french)

this list is by no means exhaustive.
seems most models are tagged with [stablelm_epoch](https://huggingface.co/models?other=stablelm_epoch)

@Galunid the `Nous-Capybara-3B-V1.9` is interesting because its multipart safetensors.

**Comment by Galunid** [comment]
>I think you can create views with ggml_view_3d and apply rope to the views. See how Persimmon graph does it, although I am not 100% that it works correctly atm due to the recent refactoring.

Done in the latest commit

>@Galunid the Nous-Capybara-3B-V1.9 is interesting because its multipart safetensors.
edit: and the jondurbin/airoboros-3b-3p0 is multipart safetensors f32.

Tested `Nous-Capybara-3B-V1.9` and it works fine, no issues with inference/conversion, so there shouldn't be any issues with other models.

**Comment by Galunid** [comment]
My subjective opinion is that the latest commit lowers output quality, although perplexity scores don't seem to reflect that, so maybe it's in my head.

I guess this should be it for this PR.

**Comment by Green-Sky** [comment]
@Galunid I am still hitting a cuda assert with `-ngl 35`
```
llm_load_tensors: ggml ctx size =    0.13 MB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =  131.25 MB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 35/35 layers to GPU
llm_load_tensors: VRAM used: 2702.37 MB
.............................................................................................
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: offloading v cache to GPU
llama_kv_cache_init: offloading k cache to GPU
llama_kv_cache_init: VRAM kv self = 1280.00 MB
llama_new_context_with_model: kv self size  = 1280.00 MB
llama_build_graph: non-view tensors processed: 1061/1061
llama_new_context_with_model: compute buffer total size = 288.13 MB
llama_new_context_with_model: VRAM scratch buffer: 281.50 MB
llama_new_context_with_model: total VRAM used: 4264.51 MB (model: 2703.01 MB, context: 1561.50 MB)
GGML_ASSERT: /build/hsafd1czxakavzvbnplxh8dawwwn68xh-source/ggml-cuda.cu:7569: ggml_is_contiguous(src0)
Aborted (core dumped)
```

`-ngl 34` works just fine though.

**Comment by Green-Sky** [comment]
Looks like NousResearch made a multimodal (vision) finetune of `Nous-Capybara-3B-V1.9` called [Obsidian-3B-V0.5](https://huggingface.co/NousResearch/Obsidian-3B-V0.5) . They say it is based on the llava procedure and there already exists a [preconverted gguf(+mmproject)](https://huggingface.co/nisten/obsidian-3b-multimodal-q6-gguf).
While trying to convert it myself, it stumbled with:
```
$ ./convert-hf-to-gguf.py models/Obsidian-3B-V0.5/
Loading model: Obsidian-3B-V0.5
Traceback (most recent call last):
  File "/home/green/workspace/llama.cpp/./convert-hf-to-gguf.py", line 883, in <module>
    model_instance = model_class(dir_model, ftype_map[args.outtype], fname_out, args.bigendian)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/green/workspace/llama.cpp/./convert-hf-to-gguf.py", line 48, in __init__
    self.model_arch = self._get_model_architecture()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/green/workspace/llama.cpp/./convert-hf-to-gguf.py", line 207, in _get_model_architecture
    raise NotImplementedError(f'Architecture "{arch}" not supported!')
NotImplementedError: Architecture "LlavaStableLMEpochForCausalLM" not supported!
```

**Comment by Green-Sky** [comment]
using the aforementioned preconverted model files and this branch, we can now use an even smaller vision model :)
image
@monatis :wink:

File: convert-hf-to-gguf.py [hunk 4]
```diff
@@ -201,6 +201,8 @@ def _get_model_architecture(self) -> gguf.MODEL_ARCH:
             return gguf.MODEL_ARCH.REFACT
```
[the remark this answers is not in the document]
Comment (Galunid) [reply convert-hf-to-gguf.py:201]: I guess it is, but I think it's out of scope of this PR.

**Review by ggerganov — APPROVED** [review]
> I am still hitting a cuda assert with -ngl 35

I think you need to `ggml_cont` either `qrot` or `krot` or both since CUDA does not yet support non-contiguous rope. Not ideal, but maybe we can fix this later

Let's merge and support this from `master`

File: convert-hf-to-gguf.py [hunk 5]
```diff
@@ -201,6 +201,8 @@ def _get_model_architecture(self) -> gguf.MODEL_ARCH:
...
         if arch == "PersimmonForCausalLM":
             return gguf.MODEL_ARCH.PERSIMMON
+        if arch == "StableLMEpochForCausalLM":
```
Comment (cebtenzzre) [inline convert-hf-to-gguf.py:204]: I think we need to add "LlavaStableLMEpochForCausalLM" here as well

**Comment by daaain** [comment]
> using the aforementioned preconverted model files and this branch, we can now use an even smaller vision model :) 

Any idea why it doesn't stop output? Is it misconfigured control tokens in the (converted) model metadata?

**Comment by Galunid** [comment]
It looks like there's some missing ggml cuda functions (I think it's `CONCAT`), offloading <35 layers works fine. It fails on 
`GGML_ASSERT: ggml.c:14322: tensor->src[0] == NULL || tensor->src[0]->backend == GGML_BACKEND_CPU`. Guess we should just leave it as is and hopefully it'll be implemented in the future.

I'll merge master tomorrow and we can merge this then.

**Comment by Galunid** [comment]
@Green-Sky Would you mind giving it one final look? If all is good feel free to merge (if CI runs green) :)

**Review by Green-Sky — APPROVED** [review]
reconverted the model, re-ran some perplexities - values slightly differ, bit within variance. Looks pretty good.

the ci oracle gives the green light :)

**Comment by Green-Sky** [comment]
I was toying around with it a bit more and realized its very slow now.

llama-bench on master(36eed0c42c5b0bf74af81fb9243d262014f9382f)

### stablelm-3b-4e1t
```
$ llama-bench -ngl 34 -m models/stablelm-3b-4e1t/ggml-model-f16.gguf -m models/stablelm-3b-4e1t/ggml-model-Q8_0.gguf -m models/stablelm-3b-4e1t/ggml-model-Q4_0.gguf -m models/stablelm-3b-4e1t/ggml-model-Q6_K.gguf -m models/stablelm-3b-4e1t/ggml-model-Q3_K_M.gguf
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2070, compute capability 7.5
```
| model                          |       size |     params | backend    | ngl | test | master t/s | be2ac38a2825635e73d89e6740a8000a4944a67f t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: | ---: |
| stablelm 3B mostly F16 |   5.21 GiB |     2.80 B | CUDA       |  34 | pp 512     |    341.39 ± 7.78 | 457.85 ± 3.54 |
| stablelm 3B mostly F16 |   5.21 GiB |     2.80 B | CUDA       |  34 | tg 128     |     41.62 ± 1.02 | 42.91 ± 0.35 |
| stablelm 3B mostly Q8_0        |   2.77 GiB |     2.80 B | CUDA       |  34 | pp 512     |    204.19 ± 3.34 | 289.87 ± 14.80 |
| stablelm 3B mostly Q8_0        |   2.77 GiB |     2.80 B | CUDA       |  34 | tg 128     |     60.15 ± 1.14 | 62.53 ± 0.18 |
| stablelm 3B mostly Q4_0        |   1.50 GiB |     2.80 B | CUDA       |  34 | pp 512     |    322.43 ± 9.71 | 303.46 ± 7.25 |
| stablelm 3B mostly Q4_0        |   1.50 GiB |     2.80 B | CUDA       |  34 | tg 128     |     84.48 ± 0.91 | 85.05 ± 0.92 |
| stablelm 3B mostly Q6_K        |   2.14 GiB |     2.80 B | CUDA       |  34 | pp 512     |    332.80 ± 6.27 | 382.22 ± 8.95 |
| stablelm 3B mostly Q6_K        |   2.14 GiB |     2.80 B | CUDA       |  34 | tg 128     |     63.43 ± 0.30 | 64.63 ± 0.21 |
| stablelm 3B mostly Q3_K_M |   1.29 GiB |     2.80 B | CUDA       |  34 | pp 512     |    101.37 ± 1.20 | 107.47 ± 1.52 |
| stablelm 3B mostly Q3_K_M |   1.29 GiB |     2.80 B | CUDA       |  34 | tg 128     |     70.83 ± 0.62 | 71.78 ± 0.62 |

### TinyLlama-1.1B
```
$ llama-bench -ngl 34 -m models/TinyLlama-1.1B-intermediate-step-240k-503b/ggml-model-F16.gguf -m models/TinyLlama-1.1B-intermediate-step-240k-503b/ggml-model-Q8_0.gguf -m models/TinyLlama-1.1B-intermediate-step-240k-503b/ggml-model-Q4_0.gguf -m models/TinyLlama-1.1B-intermediate-step-240k-503b/ggml-model-Q6_K.gguf -m models/TinyLlama-1.1B-intermediate-step-240k-503b/ggml-model-Q3_K_M.gguf
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2070, compute capability 7.5
```
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama ?B mostly F16            |   1.98 GiB |     1.10 B | CUDA       |  34 | pp 512     | 6114.76 ± 385.59 |
| llama ?B mostly F16            |   1.98 GiB |     1.10 B | CUDA       |  34 | tg 128     |    124.62 ± 0.73 |
| llama ?B mostly Q8_0           |   1.09 GiB |     1.10 B | CUDA       |  34 | pp 512     | 4907.85 ± 115.38 |
| llama ?B mostly Q8_0           |   1.09 GiB |     1.10 B | CUDA       |  34 | tg 128     |    181.02 ± 1.81 |
| llama ?B mostly Q4_0           | 606.53 MiB |     1.10 B | CUDA       |  34 | pp 512     |  5022.45 ± 81.78 |
| llama ?B mostly Q4_0           | 606.53 MiB |     1.10 B | CUDA       |  34 | tg 128     |    257.43 ± 1.02 |
| llama ?B mostly Q6_K           | 860.86 MiB |     1.10 B | CUDA       |  34 | pp 512     | 5523.69 ± 137.63 |
| llama ?B mostly Q6_K           | 860.86 MiB |     1.10 B | CUDA       |  34 | tg 128     |    182.86 ± 0.76 |
| llama ?B mostly Q3_K - Medium  | 523.67 MiB |     1.10 B | CUDA       |  34 | pp 512     |  5471.36 ± 90.28 |
| llama ?B mostly Q3_K - Medium  | 523.67 MiB |     1.10 B | CUDA       |  34 | tg 128     |    199.72 ± 1.25 |



I know comparing 1.1B to 2.8B is not very fair, but the token generation speed seems to scale properly. Or am I just looking at the difference in architecture (mostly GQA)?


## next problem

I re-ran the benchmark on master.... and now the prompt processing speeds are vastly inferior...
So I cant trust my own numbers...
```
$ llama-bench -ngl 34 -m models/stablelm-3b-4e1t/ggml-model-f16.gguf -m models/stablelm-3b-4e1t/ggml-model-Q8_0.gguf -m models/stablelm-3b-4e1t/ggml-model-Q4_0.gguf -m models/stablelm-3b-4e1t/ggml-model-Q6_K.gguf -m models/stablelm-3b-4e1t/ggml-model-Q3_K_M.gguf
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2070, compute capability 7.5
```
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| stablelm 3B mostly F16 |   5.21 GiB |     2.80 B | CUDA       |  34 | pp 512     |    100.38 ± 0.41 |
| stablelm 3B mostly F16 |   5.21 GiB |     2.80 B | CUDA       |  34 | tg 128     |     43.44 ± 0.14 |
| stablelm 3B mostly Q8_0        |   2.77 GiB |     2.80 B | CUDA       |  34 | pp 512     |    145.05 ± 2.77 |
| stablelm 3B mostly Q8_0        |   2.77 GiB |     2.80 B | CUDA       |  34 | tg 128     |     61.39 ± 1.48 |
| stablelm 3B mostly Q4_0        |   1.50 GiB |     2.80 B | CUDA       |  34 | pp 512     |    147.17 ± 2.62 |
| stablelm 3B mostly Q4_0        |   1.50 GiB |     2.80 B | CUDA       |  34 | tg 128     |     85.65 ± 0.58 |
| stablelm 3B mostly Q6_K        |   2.14 GiB |     2.80 B | CUDA       |  34 | pp 512     |    241.34 ± 2.15 |
| stablelm 3B mostly Q6_K        |   2.14 GiB |     2.80 B | CUDA       |  34 | tg 128     |     64.47 ± 0.39 |
| stablelm 3B mostly Q3_K - Medium |   1.29 GiB |     2.80 B | CUDA       |  34 | pp 512     |    153.08 ± 1.14 |
| stablelm 3B mostly Q3_K - Medium |   1.29 GiB |     2.80 B | CUDA       |  34 | tg 128     |     71.97 ± 0.41 |

... now I have no idea what is going on q.q

**Comment by Galunid** [comment]
Could you try 6be335678aa9a0211f147d9e3fb37dae30698b9e, it should be faster. Right now there is more matrix operation we need to compute (for rope). Previously we just computed rope and on a whole tensor, right now we need to split tensor into two halves (the one roped, and the one not roped). Calculate rope for the first one, concatenate both (which also requires permuting both tensors) at the end. We also use `ggml_cont`, which should also add a bit of an overhead.

**Comment by Green-Sky** [comment]
did some more testing on master, and turns out that watching youtube and moving windows around has a positive correlation to both performance AND variance ....
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| stablelm 3B mostly F16 (guessed) |   5.21 GiB |     2.80 B | CUDA       |  34 | pp 512     |    344.08 ± 8.68 |
| stablelm 3B mostly F16 (guessed) |   5.21 GiB |     2.80 B | CUDA       |  34 | tg 128     |     40.90 ± 0.20 |
| stablelm 3B mostly Q8_0        |   2.77 GiB |     2.80 B | CUDA       |  34 | pp 512     |    332.28 ± 5.05 |
| stablelm 3B mostly Q8_0        |   2.77 GiB |     2.80 B | CUDA       |  34 | tg 128     |     59.24 ± 0.25 |
| stablelm 3B mostly Q4_0        |   1.50 GiB |     2.80 B | CUDA       |  34 | pp 512     |    103.72 ± 1.37 |
| stablelm 3B mostly Q4_0        |   1.50 GiB |     2.80 B | CUDA       |  34 | tg 128     |     80.40 ± 0.91 |
| stablelm 3B mostly Q6_K        |   2.14 GiB |     2.80 B | CUDA       |  34 | pp 512     |    104.29 ± 0.51 |
| stablelm 3B mostly Q6_K        |   2.14 GiB |     2.80 B | CUDA       |  34 | tg 128     |     60.75 ± 0.56 |
| stablelm 3B mostly Q3_K - Medium |   1.29 GiB |     2.80 B | CUDA       |  34 | pp 512     |     98.88 ± 1.62 |
| stablelm 3B mostly Q3_K - Medium |   1.29 GiB |     2.80 B | CUDA       |  34 | tg 128     |     68.08 ± 0.68 |

sooo... my system seems to be unsuited for llama.cpp / benchmarking.

**Comment by Green-Sky** [comment]
Oh yea, 6be335678aa9a0211f147d9e3fb37dae30698b9e is significantly faster:
| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| stablelm 3B mostly F16 (guessed) |   5.21 GiB |     2.80 B | CUDA       |  34 | pp 512     |   935.57 ± 14.04 |
| stablelm 3B mostly F16 (guessed) |   5.21 GiB |     2.80 B | CUDA       |  34 | tg 128     |     44.55 ± 0.26 |
| stablelm 3B mostly Q8_0        |   2.77 GiB |     2.80 B | CUDA       |  34 | pp 512     |    856.02 ± 7.24 |
| stablelm 3B mostly Q8_0        |   2.77 GiB |     2.80 B | CUDA       |  34 | tg 128     |     67.80 ± 0.72 |
| stablelm 3B mostly Q4_0        |   1.50 GiB |     2.80 B | CUDA       |  34 | pp 512     |   844.57 ± 15.42 |
| stablelm 3B mostly Q4_0        |   1.50 GiB |     2.80 B | CUDA       |  34 | tg 128     |     95.70 ± 1.11 |
| stablelm 3B mostly Q6_K        |   2.14 GiB |     2.80 B | CUDA       |  34 | pp 512     |   879.32 ± 23.63 |
| stablelm 3B mostly Q6_K        |   2.14 GiB |     2.80 B | CUDA       |  34 | tg 128     |     69.02 ± 0.25 |
| stablelm 3B mostly Q3_K - Medium |   1.29 GiB |     2.80 B | CUDA       |  34 | pp 512     |   893.89 ± 10.10 |
| stablelm 3B mostly Q3_K - Medium |   1.29 GiB |     2.80 B | CUDA       |  34 | tg 128     |     77.37 ± 0.29 |

**Comment by maddes8cht** [comment]
Thanks for making this happen!

There is now a growing list of many of the mentioned finetuned Models converted to gguf format on this [Huggingface Collection](https://huggingface.co/collections/maddes8cht/stablelm-gguf-65552101dcf410fd072c6c87)

Some of the mentioned Models will not convert. Do you want a list of them?

**Comment by Galunid** [comment]
Yes, I'll take a look if you could list them

File: llama.cpp [hunk 6]
```diff
@@ -4556,6 +4662,177 @@ struct llm_build_context {
...
+                struct ggml_tensor * Kcur = ggml_concat(ctx0, krotated, kpass);
+                cb(Kcur, "Kcur", il);
+
+                struct ggml_tensor * Q = ggml_cont(ctx0, ggml_permute(ctx0, Qcur, 2, 1, 0, 3));
+                cb(Q, "Q", il);
+
+                Kcur = ggml_cont(ctx0, ggml_permute(ctx0, Kcur, 2, 1, 0, 3));
+                cb(Kcur, "Kcur", il);
+
+                llm_build_kv_store(ctx0, hparams, kv_self, gf, Kcur, Vcur, n_ctx, n_tokens, kv_head, cb, il);
```
[the remark this answers is not in the document]
Comment (slaren) [reply llama.cpp:4786]: > Or if necessary, we can prepare the model data upon conversion to be more friendly to `ggml` ops.

The disadvantage of doing that is that it makes harder to convert LoRAs from HF, since the tensors no longer match, and we would need to apply the same conversions to the LoRAs (if that's possible at all). Related: https://github.com/ggerganov/llama.cpp/issues/3519

**Comment by husnoo** [comment]
> > using the aforementioned preconverted model files and this branch, we can now use an even smaller vision model :)
> 
> Any idea why it doesn't stop output? Is it misconfigured control tokens in the (converted) model metadata?

Did you make any progress with this? It blabbers on.

**Comment by daaain** [comment]
> > Any idea why it doesn't stop output? Is it misconfigured control tokens in the (converted) model metadata?
> 
> Did you make any progress with this? It blabbers on.

Seems to have stopped doing that now, using `nisten/obsidian-3b-multimodal-q6-gguf/obsidian-q6.gguf`

If anything, it's very terse now, can't get it to respond with more than a sentence 🤷 

image

**Comment by husnoo** [comment]
I managed to use the stop=["###"] parameter in calling the server.

**Comment by husnoo** [comment]
Didn't make it any more concise though - it kept banging on about how
it's a nice artistic arrangement.
