### PR TITLE
webui: remove client-side context pre-check and rely on backend for limits

### LINKED ISSUE #16437: Misc. bug: SveltKit WebUI blocks prompts that are >~1/3 the max context size
### Name and Version

6692 (ca71fb9b)
built with clang version 19.1.5 for x86_64-pc-windows-msvc

### Operating systems

Windows

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
llama-server -m "Qwen_Qwen3-30B-A3B-Q6_K.gguf" --port 7861 -c 16384 -b 2048 --gpu-layers 99 --flash-attn on --no-mmap --main-gpu 1 --tensor-split 0,100
```

### Problem description & steps to reproduce

The Web UI (over)estimates the prompt's token count yet entirely **blocks** prompts whose estimated token count exceeds the context size. For example, on a 16,384 context window, I provided a 8210-token prompt, and it estimated 23,199 tokens and showed the "Message Too Long" dialog without sending an HTTP request.

Easiest solution: make the dialog _just_ a warning and send the request anyway. (I considered a "Send Anyway" button, but since it's an easy-to-cancel operation, it's probably better to just attempt it.)

Better solution: if the estimate exceeds the context window (and not by >5x), send the prompt + system prompt to /tokenize for a more accurate estimate. Alternatively, don't automatically call /tokenize, but provide a button in the dialog to do so.

### First Bad Commit

https://github.com/ggml-org/llama.cpp/commit/a7a98e0fffed794396b3fbad4dcdbbc184963645

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by ServeurpersoCom**
webui: remove client-side context pre-check and rely on backend for limits

Removed the client-side context window pre-check and now simply sends messages
while keeping the dialog imports limited to core components, eliminating the
maximum context alert path

Simplified streaming and non-streaming chat error handling to surface a generic
'No response received from server' error whenever the backend returns no content

Removed the obsolete maxContextError plumbing from the chat store so state
management now focuses on the core message flow without special context-limit cases

+ fix: make SSE client resilient to premature [DONE] events in multi-turn agentic proxy chains (like legacy WebUI), ensuring all SSE chunks are displayed until the TCP stream fully closes.

close https://github.com/ggml-org/llama.cpp/issues/16437

Master branch :
https://github.com/user-attachments/assets/edc1337d-2e19-4f99-a7ba-78f40146022f

This PR (don't care about Model Selector) :
https://github.com/user-attachments/assets/e9952e04-e189-434f-8536-84184193d704

### CODE REVIEW

File: tools/server/webui/src/lib/stores/chat.svelte.ts [hunk 1]
```diff
@@ -477,16 +418,32 @@ class ChatStore {
 				);
 
 				if (messageIndex !== -1) {
-					this.activeMessages[messageIndex].content = `Error: ${error.message}`;
+					const [failedMessage] = this.activeMessages.splice(messageIndex, 1);
+					if (failedMessage) {
```
Comment (allozaur) [inline tools/server/webui/src/lib/stores/chat.svelte.ts:423]:
```suggestion
					const [failedMessage] = this.activeMessages.splice(messageIndex, 1);

					if (failedMessage) {
```

File: tools/server/webui/src/lib/stores/chat.svelte.ts [hunk 2]
```diff
@@ -477,16 +418,32 @@ class ChatStore {
...
+						DatabaseStore.deleteMessage(failedMessage.id).catch((cleanupError) => {
+							console.error('Failed to remove assistant message after error:', cleanupError);
+						});
+					}
 				}
 
+				const dialogType = error.name === 'TimeoutError' ? 'timeout' : 'server';
+				this.showErrorDialog(dialogType, error.message);
```
Comment (allozaur) [inline tools/server/webui/src/lib/stores/chat.svelte.ts:432]:
```suggestion
				const dialogType = error.name === 'TimeoutError' ? 'timeout' : 'server';

				this.showErrorDialog(dialogType, error.message);
```

File: tools/server/webui/src/lib/components/app/chat/ChatScreen/ChatScreen.svelte [hunk 3]
```diff
@@ -461,6 +454,13 @@
 	}}
 />
 
+<ChatErrorDialog
+	open={Boolean(activeErrorDialog)}
+	type={activeErrorDialog?.type ?? 'server'}
+	message={activeErrorDialog?.message ?? ''}
+	onOpenChange={handleErrorDialogOpenChange}
```
Comment (allozaur) [inline tools/server/webui/src/lib/components/app/chat/ChatScreen/ChatScreen.svelte]:
```suggestion
	message={activeErrorDialog?.message ?? ''}
	onOpenChange={handleErrorDialogOpenChange}
	open={Boolean(activeErrorDialog)}
	type={activeErrorDialog?.type ?? 'server'}
```

File: tools/server/webui/src/lib/components/app/chat/ChatScreen/ChatScreen.svelte [hunk 4]
```diff
@@ -80,6 +81,7 @@
 	);
 
 	let isServerLoading = $derived(serverLoading());
+	let activeErrorDialog = $derived(errorDialog());
```
Comment (allozaur) [inline tools/server/webui/src/lib/components/app/chat/ChatScreen/ChatScreen.svelte]:
```suggestion
	let activeErrorDialog = $derived(errorDialog());
	let isServerLoading = $derived(serverLoading());
```

**Review by allozaur — CHANGES_REQUESTED** [review]
@ServeurpersoCom 

Just a few cosmetic changes 😄 also, could u add screenshots/video to the PR description with comparison of before/after changes? Will be great for adding context for the future lookback.

**Comment by ServeurpersoCom** [comment]
> @ServeurpersoCom
> 
> Just a few cosmetic changes 😄 also, could u add screenshots/video to the PR description with comparison of before/after changes? Will be great for adding context for the future lookback.

I’d love to make a temporary mini version of the model selector : just a simple field in Settings to declare the model in the JSON request. That way my llama-swap would work on master, and I could make videos of the master branch more easily!

**Comment by ServeurpersoCom** [comment]
I’ve added two videos, running on my Raspberry Pi 5 (16 GB) with Qwen3 30B A3B, fully synced with the master branch. You can see the bug where I got stuck : once the context overflows, the interface is completely blocked until you hit F5.

With the current PR build, it’s much better: if a message block is too large, it can still slip into the context and needs to be deleted manually. But since the backend decides, it never fully blocks. We could still improve it a bit by preventing oversized messages from being sent into the context in the first place.

**Comment by ServeurpersoCom** [comment]
Toolcall testing (Node.js proxy)

https://github.com/user-attachments/assets/fd3bf4e3-b7da-4169-bbfd-46a935ee5b4b

**Comment by ggerganov** [comment]
@ServeurpersoCom Curious are you doing some OCR in the last video to detect text elements in the screenshots? Would love to learn more, but maybe after the PR is reviewed to avoid getting offtopic.

**Review by allozaur — CHANGES_REQUESTED** [review]
@ServeurpersoCom let's just rebuild fresh webui static output and we good to go :)

**Review by allozaur — APPROVED** [review]

**Comment by allozaur** [comment]
@ServeurpersoCom actually I will improve the UI/UX of the new Alert Dialog in a separate PR so that we don't block this change :)

**Comment by ServeurpersoCom** [comment]
> @ServeurpersoCom Curious are you doing some OCR in the last video to detect text elements in the screenshots? Would love to learn more, but maybe after the PR is reviewed to avoid getting offtopic.

Not OCR : the proxy just parses streamed text and DOM elements in real time.
I can still use OCR separately when needed (reading screenshots, captchas, etc.).

The model actually sees the entire page: it can analyze the full DOM and reach elements outside the viewport through an abstraction layer that simulates human actions (scroll, click, type).
That makes it effectively undetectable by anti-bot systems, while keeping inference fully streamed through the SSE proxy.

ToolCall

**Comment by ServeurpersoCom** [comment]
> @ServeurpersoCom actually I will improve the UI/UX of the new Alert Dialog in a separate PR so that we don't block this change :)

Awesome can’t wait to see your pure Svelte touch on that dialog 😄

**Comment by ggerganov** [comment]
Nice. So this seems like some sort of ingenious way to control a headless? browser with an LLM. And the images in the WebUI are just "progress report" from the browser. It's a bit over my head, but definitely looks interesting.

**Comment by ServeurpersoCom** [comment]
Exactly, but not headless, full real browser with GPU capability (inside a software box) ! the goal is to convert the DOM (with all bounding boxes) into labeled text tokens for the LLM.
When the model wants to interact with a label, it also gets the list of possible actions on it.
The ToolCall + abstraction layer then takes care of reaching the right area (scrolling if needed) and performing what the LLM asked : typing or clicking.
It’s all heuristic logic, way simpler than the CUDA kernels in llama.cpp 😄

Idea: we could add a small module in llama.cpp that exposes every ToolCall event through a user-defined HTTP hook : that would let anyone easily connect their model to external actions or systems!
