### PR TITLE
fixes infill incorrect tokenization

### LINKED ISSUE #3503: Infill Incorrect Tokenization
I am comparing the tokenization of the codellama repository with the infill example of this repository.

The first example prompt from the codellama repository consists of the strings:

- Prefix: 'def remove_non_ascii(s: str) -> str:\n    \"\"\" '
- Suffix: '\n    return result\n'

Comparing the tokenization of both implementations results in:

- CodeLlama: 1 32007 822 3349 29918 5464 29918 294 18869 29898 29879 29901 851 29897 1599 851 29901 13 1678 9995 29871 32008 13 1678 736 1121 13 32009
- Llama.cpp: 32007 1 822 3349 29918 5464 29918 294 18869 29898 29879 29901 851 29897 1599 851 29901 13 1678 9995 29871 32008 1 29871 13 1678 736 1121 13 32009

There are two differences:

- The first two tokens are swapped (those are `prefix_id` and `bos` I think)
- Llama.cpp adds a `bos` token again after the `suffix_id` token and an additional 29871 (is this a space?)

I believe the latter is definitely wrong, as the [paper](https://ai.meta.com/research/publications/code-llama-open-foundation-models-for-code/) states on page 4:

> To limit the distribution shift between autoregressive and infilling training, we suppress the implicit leading space that SentencePiece tokenizers add upon encoding the middle part and the suffix

### PR DESCRIPTION
**Pull request by vvhg1**
fixes #3503

### CODE REVIEW

File: examples/infill/infill.cpp [hunk 1]
```diff
@@ -235,7 +235,12 @@ int main(int argc, char ** argv) {
 
     std::vector<llama_token> embd_inp;
     std::vector<llama_token> inp_pfx = ::llama_tokenize(ctx, params.input_prefix, false);
+    params.input_suffix.erase(0, params.input_suffix.find_first_not_of(" "));
     std::vector<llama_token> inp_sfx = ::llama_tokenize(ctx, params.input_suffix, false);
+    const int space_token = 29871;
+    if (params.escape && inp_sfx.size() > 1 && inp_sfx[0] == space_token) {
```
Comment (ggerganov) [inline examples/infill/infill.cpp:241]: I think we always want to remove the leading space, regardless if the `params.escape` is set or not:

```suggestion
    if (inp_sfx.size() > 1 && inp_sfx[0] == space_token) {
```

Comment (vvhg1) [reply examples/infill/infill.cpp]: I think we need the params.escape check as only then we add an extra space to the suffix.

File: examples/infill/infill.cpp [hunk 2]
```diff
@@ -233,10 +233,22 @@ int main(int argc, char ** argv) {
     const bool add_bos = llama_vocab_type(model) == LLAMA_VOCAB_TYPE_SPM;
     LOG("add_bos: %d\n", add_bos);
 
+    bool suff_rm_leading_spc = params.escape;
+    if (suff_rm_leading_spc && params.input_suffix.find_first_of(" ") == 0 && params.input_suffix.size() > 1) {
+        params.input_suffix.erase(0, 1);
+        suff_rm_leading_spc = false;
+    }
```
Comment (ggerganov) [inline examples/infill/infill.cpp:240]: Hm, I could be missing something, but this whole section should not be needed.

If you keep everything else and just replace this block with:

```suggestion
    const bool suff_rm_leading_spc = true;
```

Can you find a case that does not match the Python version?

Comment (vvhg1) [reply examples/infill/infill.cpp:240]: yes, I can find cases where it misbehaves:
 with params.escape, if the suffix starts with a space, the tokenizer adds a space and THEN tokenizes the double space to '259' so we can't remove the surplus space anymore but would have to "translate" the '259' to '29871' to remove the space, same with more than one leading spaces...
without params.escape if the suffix starts with a space, we remove it so it does not reflect the original suffix

not sure what the python version does as I can't test it, but the above behaviour seems wrong

Comment (ggerganov) [reply examples/infill/infill.cpp:240]: Ok, that makes sense. Let's double check, just in case:
@kherud Could you please run the Python codellama with suffix with 2 leading spaces and see what tokens are produced for infill?

Comment (vvhg1) [reply examples/infill/infill.cpp:240]: There seems to be another issue too, in interactive mode the -e seems to only act on the initial input as the processing happens when the params are loaded in common.cpp:617
Is that a bug? seems to be a bug for infill and server infill, what about main, others?

**Comment by vvhg1** [comment]
There seems to be another issue too, in interactive mode the -e seems to only act on the initial input as the processing happens when the params are loaded in common.cpp:617
Is that a bug? seems to be a bug for infill, what about main, others?
params.cfg_negative_prompt is not being escaped anywhere it seems, is that another bug or desired behaviour?

File: examples/infill/infill.cpp (hunk 2 above)
Comment (kherud) [reply examples/infill/infill.cpp:240]: '<PRE> <SUF>': 1, 32007, 259, 32008, 32009
'<PRE> <SUF> ': 1, 32007, 259, 32008, 29871, 32009
'<PRE> <SUF>  ': 1, 32007, 259, 32008, 259, 32009
'<PRE> <SUF>   ': 1, 32007, 259, 32008, 1678, 32009
'<PRE> <SUF>    ': 1, 32007, 259, 32008, 268, 32009

**Comment by vvhg1** [comment]
> This is probably an oversight - we should escape the user input and `params.cfg_negative_prompt` as well
Should be an easy fix as I am doing that already in the infill script.
Do you want to have the fix here or in a separate pr?

**Review by ggerganov — APPROVED** [review]
Anyway you prefer.

If the results match the Python version now, I think we can merge.
I can do some testing later, or we can wait for some feedback from other people.

**Comment by vvhg1** [comment]
> Anyway you prefer.

Would keep it separate as the issues are related but not identical?

> If the results match the Python version now, I think we can merge. I can do some testing later, or we can wait for some feedback from other people.

I think it matches now, your call to merge or wait.

**Comment by ggerganov** [comment]
Ok, will merge this first thing tomorrow unless somebody notices any problems

**Review by ggerganov — APPROVED** [review]
