### PR TITLE
chat: make tool description and parameters optional per OpenAI spec

### LINKED ISSUE #17667: Eval bug: llama-server Tool validation fails if optional  'parameters' key is omitted from tool payload
### Name and Version

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx1151 (0x1151), VMM: no, Wave Size: 32
version: 6894 (6eb208d17)
built with cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0 for x86_64-linux-gnu

### Operating systems

Linux

### GGML backends

HIP

### Hardware

Ryzen strix halo (gfx1151)

### Models

Appears to be any model as this happens during validation; tested with:

https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct-GGUF
https://huggingface.co/unsloth/gpt-oss-120b-GGUF
https://huggingface.co/unsloth/gpt-oss-20b-GGUF

### Problem description & steps to reproduce

Hi,

I have a tool that appears to be trying to verify/test tool capabilities of an OpenAI compatible endpoint by sending the query below. It is failing due to the missing parameters key in the tool definition.

Per the openai spec the parameters key is actually optional: https://platform.openai.com/docs/api-reference/chat/create#chat_create-tools-function_tool-function-parameters

I've submitted a ticket against that program to be more robust about detection there but IMO llama.cpp should accept this input as valid as well.

Failing query:

curl -X POST "http://llama-server/v1/chat/completions" --data '{"messages": [{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "What is the capital of France?"}], "model": "Qwen_Qwen3-VL-32B-Instruct-bf16_0", "max_tokens": 3, "stream": false, "tools": [{"type": "function", "function": {"name": "test_function", "description": "Test function."}}]}' --header "Content-Type: application/json"

Error message:

{"error":{"code":500,"message":"Failed to parse tools: [json.exception.out_of_range.403] key 'parameters' not found; tools = [\n  {\n    \"type\": \"function\",\n    \"function\": {\n      \"name\": \"test_function\",\n      \"description\": \"Test function.\"\n    }\n  }\n]","type":"server_error"}}

Retrying with explicit dummy/empty parameters

curl -X POST "http://llama-server/v1/chat/completions" --data '{"messages": [{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "What is the capital of France?"}], "model": "Qwen_Qwen3-VL-32B-Instruct-bf16_0", "max_tokens": 3, "stream": false, "tools": [{"type": "function", "function": {"name": "test_function", "description": "Test function.", "parameters": {"type": "object", "properties": {}}}}]}' --header "Content-Type: application/json"

succeeds.

### First Bad Commit

_No response_

### Relevant log output

```shell
log request without parameters

got exception: {"code":500,"message":"Failed to parse tools: [json.exception.out_of_range.403] key 'parameters' not found; tools = [\n  {\n    \"type\": \"function\",\n    \"function\": {\n      \"name\": \"test_function\",\n      \"description\": \"Test function.\"\n    }\n  }\n]","type":"server_error"}
srv  log_server_r: request: POST /v1/chat/completions 127.0.0.1 500

log request with parameters:

srv  log_server_r: request: POST /v1/chat/completions 127.0.0.1 200
```

### PR DESCRIPTION
**Pull request by Anri-Lombard**
## Summary
- Makes `description` and `parameters` fields optional in tool function definitions
- Per the [OpenAI API specification](https://platform.openai.com/docs/api-reference/chat/create#chat_create-tools-function_tool-function-parameters), these fields are optional
- Previously, the parser would throw an exception if these fields were missing

## Test plan
- [x] Added test for tools without `parameters` field
- [x] Added test for tools without `description` field  
- [x] Added test for tools with only `name` (minimal valid tool)
- [x] Existing tests still pass

Attempts to fix #17667

### CODE REVIEW

File: common/chat.cpp [hunk 1]
```diff
@@ -380,8 +380,8 @@ std::vector<common_chat_tool> common_chat_tools_parse_oaicompat(const json & too
                 const auto & function = tool.at("function");
                 result.push_back({
                     /* .name = */ function.at("name"),
-                    /* .description = */ function.at("description"),
-                    /* .parameters = */ function.at("parameters").dump(),
+                    /* .description = */ function.contains("description") ? function.at("description") : "",
+                    /* .parameters = */ (function.contains("parameters") ? function.at("parameters") : json::object()).dump(),
```
Comment (aldehir) [inline common/chat.cpp]: Can you use `value()` here?

```cpp
function.value("description", "");
function.value("parameters", json::object()).dump();
```

https://json.nlohmann.me/api/basic_json/value/

**Review by pwilkin — APPROVED** [review]
LGTM.

File: common/chat.cpp (hunk 1 above)
Comment (Anri-Lombard) [reply common/chat.cpp]: Done, thanks for the suggestion!

**Review by aldehir — APPROVED** [review]
Looks good, thanks!
