### PR TITLE
`sampler`: fixes trigger tokens + lazy grammars (fix typo cast from token to string)

### LINKED ISSUE #12256: Eval bug: Llama server <tool_call> is occasionally not parsed as json, and is in content rather than tool_calls
### Name and Version

```
llama-cli.exe --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
version: 4831 (5e43f104)
built with MSVC 19.39.33523.0 for x64
```

I'm using llama server exe that I compiled 3/6/25 from the master branch, using DLLAMA_CUDA:
```
cmake .. -DLLAMA_CUDA=ON 
cmake --build . --config Release
```

### Operating systems

Windows

### GGML backends

CUDA

### Hardware

RTX 3090

### Models

Qwen2.5-7B-Instruct-1M-Q4_K_M.gguf

### Problem description & steps to reproduce

Ocassionally, I see a tool_call that comes back as response.choices[0].message.content, rather than as response.choices[0].message.tool_calls.

# Example of the issue:
```
{
  "role": "assistant",
  "content": "<tool_call>\n{\"name\": \"aiCreatePlan\", \"arguments\": {...}}}\n</tool_call>"
}
```

## Example code with debugger and values:

Image

# Example of a good result, with the same parameters & prompt

Image

### First Bad Commit

_No response_

### Relevant log output

```shell
const response = await openai.chat.completions.create({
        model: model.modelName,
        messages: openAiMessages,
        tools: aiFunctionContext.aiFunctionExecutor?.getToolsMetadata(),
        stream: false,
      }, { signal });

      const assistantMessage = response.choices[0].message;

      // Add the assistant's message to our conversation
      openAiMessages.push({
        role: 'assistant' as const,
        content: assistantMessage.content,
        tool_calls: assistantMessage.tool_calls
      });
      const toolCallsFromOpenAi = assistantMessage.tool_calls;
```

### PR DESCRIPTION
**Pull request by ochafik**
Fixes regression introduced in https://github.com/ggml-org/llama.cpp/pull/12034 (which got trigger tokens to just be... ignored)

Likely fixes https://github.com/ggml-org/llama.cpp/issues/12256

Note: this is hard to test against, short of exposing the triggered status of lazy grammars all the way to the server API (maybe limiting to verbose mode)

### CODE REVIEW

File: examples/server/server.cpp [hunk 1]
```diff
@@ -384,7 +384,8 @@ struct server_task {
                             SRV_DBG("Grammar trigger token: %d (`%s`)\n", token, word.c_str());
                             common_grammar_trigger trigger;
                             trigger.type = COMMON_GRAMMAR_TRIGGER_TYPE_TOKEN;
-                            trigger.value = (llama_token) token;
+                            trigger.value = word;
```
Comment (ggerganov) [inline examples/server/server.cpp:387]: Do we need to assign to `value` here? I though that `COMMON_GRAMMAR_TRIGGER_TYPE_TOKEN` means to use just the `token` member.

File: examples/server/server.cpp [hunk 2]
```diff
@@ -384,7 +384,8 @@ struct server_task {
...
+                            trigger.token = token;
                             params.sampling.grammar_triggers.push_back(trigger);
```
Comment (ggerganov) [inline examples/server/server.cpp:389]: Save a string copy here:

```suggestion
                            params.sampling.grammar_triggers.push_back(std::move(trigger));
```

**Review by ggerganov — APPROVED** [review]

File: examples/server/server.cpp (hunk 1 above)
Comment (ochafik) [reply examples/server/server.cpp:387]: It’s only (very useful) for debug in the verbose json output
