### PR TITLE
quantize: prevent input/output file collision

### LINKED ISSUE #12753: Misc. bug: llama-quantize clobbers input file + crashes when output file matches
### Name and Version

version: 5029 (833e2b74)
built with cc (GCC) 13.2.0 for x86_64-unknown-linux-gnu

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-quantize

### Command line

```shell
llama-quantize ./Llama-3.2-1B-Instruct-f16.gguf Llama-3.2-1B-Instruct-f16.gguf 7
```

### Problem description & steps to reproduce

If the input and output files point to the same location, the program crashes:
```
[1]    12928 bus error  llama-quantize ./Llama-3.2-1B-Instruct-f16.gguf Llama-3.2-1B-Instruct-f16.ggu
```
This also clobbers the input file, rendering it nearly empty, and unusable:
```
$ du -sh ./Llama-3.2-1B-Instruct-f16.gguf
7.5M    ./Llama-3.2-1B-Instruct-f16.gguf
```

### First Bad Commit

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Anri-Lombard**
## Summary
- Add check to prevent quantizing when input and output files are the same
- Uses `std::filesystem::equivalent()` to handle path variations (e.g., `./file` vs `file`)
- Prevents file corruption caused by mmap reading from a file being simultaneously written

## Test
```bash
# Before fix: file gets corrupted (19MB -> 727KB)
llama-quantize model.gguf model.gguf Q4_0

# After fix: clean error message, file preserved
main: error: input and output files are the same: 'model.gguf'
```

Fixes #12753

### CODE REVIEW

File: tools/quantize/quantize.cpp [hunk 1]
```diff
@@ -643,6 +644,11 @@ int main(int argc, char ** argv) {
         return 1;
     }
 
+    if (std::filesystem::exists(fname_out) && std::filesystem::equivalent(fname_inp, fname_out)) {
+        fprintf(stderr, "%s: error: input and output files are the same: '%s'\n", __func__, fname_inp.c_str());
+        return 1;
+    }
+
```
Comment (danbev) [inline tools/quantize/quantize.cpp]: Perhaps `std::filesystem::exists` call can be avoided here:
```suggestion
    if (std::error_code ec; fs::equivalent(fname_inp, fname_out, ec)) {
        fprintf(stderr, "%s: error: input and output files are the same: '%s'\n", __func__, fname_inp.c_str());
        return 1;
    }
````

**Comment by Anri-Lombard** [comment]
Updated to use the error_code overload as suggested. Thanks @danbev

**Review by danbev — APPROVED** [review]
