### PR TITLE
broken change: deprecate GGML_TASK_INIT and GGML_TASK_FINALIZE

### LINKED ISSUE #284: ggml : deprecate `GGML_TASK_FINALIZE`
The initial design of the compute tasks in `ggml` was each one to have 3 separate stages:

- `GGML_TASK_INIT`
- `GGML_TASK_COMPUTE`
- `GGML_TASK_FINALIZE`

So far, the `GGML_TASK_FINALIZE` step has been left completely unused and it seems it won't find any applications in the future. Therefore, it is best to remove it all together. This will simplify the code a little bit and also bring performance improvements as there will be fewer thread synchronization points during the graph computation

Related:

- https://github.com/ggerganov/llama.cpp/pull/1556

### PR DESCRIPTION
**Pull request by mqy**
Try resolve https://github.com/ggerganov/ggml/issues/284

- <del>comment warning for `GGML_TASK_FINALIZE` in `ggml.h`</del>
- removed codes using `GGML_TASK_FINALIZE` in `ggml.c`, including those in `ggml_graph_compute`.
- <del>print a warning message in `ggml_compute_forward` to warn unmerged incoming PR. Thread unsafe but should be OK. This message will be shown before prompt echo back in console.</del>

### Edit

I had missed a case that `ggml_compute_forward_cross_entropy_loss_f32()` is using `GGML_TASK_FINALIZE`.

Added a `finalizer lookup table` to patch this special case. Only one entry in it: `ggml_compute_forward_cross_entropy_loss_finalizer`. `ggml_graph_compute_thread()` was slightly updated.

Unable to test op `GGML_OP_CROSS_ENTROPY_LOSS` because the train always crash in the middle on my weak device.  The extracted finalizer is quite simple, so I think it's OK to bypass the test by me.

Verified the lookup table with `OP_MUL_MAT`,  the registered runner was called as expected.
Finally I removed GGML_TASK_FINALIZE.

### Update

Also deprecated GGML_TASK_INIT; no longer touch runner codes, because that's error prone. We can cleanup them later step by step.

The `GGML_OP_HAS_XXX` idea is stolen from  https://github.com/ggerganov/llama.cpp/commit/9d058c2096b9f1f300e1ee16f5740a6a0a342917 Credit @zrm

@ggerganov @xaedes @zrm

### CODE REVIEW

**Comment by ggerganov** [comment]
This is great. Please rebase on latest `master` as there are recent changes to the threading logic due to #1556

File: ggml.c [hunk 1]
```diff
@@ -15054,14 +14990,7 @@ static void ggml_compute_forward_cross_entropy_loss_f32(
         return;
     }
 
-    if (params->type == GGML_TASK_FINALIZE) {
```
Comment (mqy) [inline ggml.c:15057]: I had missed this, fixed

File: ggml.c [hunk 2]
```diff
@@ -15126,6 +15055,29 @@ static void ggml_compute_forward_cross_entropy_loss_f32(
...
+            ggml_vec_sum_f32(params->nth, dp, sums);
+            dp[0] *= -1.0f;
+        } break;
+    default:
+        {
+            GGML_ASSERT(false);
+        } break;
+    }
+}
+
```
Comment (ggerganov) [inline ggml.c:15080]: Oops, I have missed that we are now using `GGML_TASK_FINALIZE` here.

@xaedes 
I'm thinking about deprecating `GGML_TASK_FINALIZE` and this is the only exception that currently uses it. Do you think there is a way to make this work without the need for "finalize" pass?

Comment (xaedes) [reply ggml.c:15080]: Hm... I don't think so. 
There needs to be some finalizing synchronization for computing aggregated values.
Similarly `ggml_compute_forward_sum_f32` (or mean) currently is not, but _could_ be parallelized. 
Then it also would need a final synchronization step.
The only way I see is to split it in multiple operations, storing intermediate tensors and then use a not-parallelizeable-by-design aggregating operation on the intermediate tensor.

I think finalizer lookup table is a good idea to avoid the finalize stage for operations that don't need it.

Comment (xaedes) [reply ggml.c:15080]: Atomic (add) operations could also be used to avoid finalizing synchronization, but such atomic functions often only work on integral types.

Comment (mqy) [reply ggml.c:15080]: > Atomic (add) operations could also be used to avoid finalizing synchronization, but such atomic functions often only work on integral types.

Current "problem" can be resolved by any kind of lock, but that's ugly and low efficient. Using atomic directly in compute code is a bad smell, that tends to result in difficult situations.

Let me share a post about linux spinlock, not quite relevant to current topic https://www.realworldtech.com/forum/?threadid=189711&curpostid=189723v

Quote:
```
... There's a reason why you can find decades of academic papers on locking. Really. It's hard.
```

Recently I tried c++ locks, feels bad, really. Any kind of logically correct locking has to be implemented by the underlying platform, but cross-platform sucks, CPU matters.

Comment (ggerganov) [reply ggml.c:15080]: Yea - locks are not good.

@mqy 
Can you try to adapt this solution proposed by @zrm in a recent PR:

https://github.com/ggerganov/llama.cpp/pull/1556/commits/9d058c2096b9f1f300e1ee16f5740a6a0a342917

We ended up not using it, but I think in the current situation it will be the best option.

Comment (mqy) [reply ggml.c:15080]: Sure, the bool array is good, no longer have to split finalizers, I think @ xaedes will feel happy :)
I'll do that, add the `GGML_OP_HAS_INIT` array as well.

Comment (mqy) [reply ggml.c]: Also deprecated GGML_TASK_INIT.
No longer touch runner codes, because that would modify or delete many lines,  tedious and error prone.
We'd cleanup them later step by step.

@ggerganov pls have a look.

Comment (mqy) [reply ggml.c]: The macOS-make-latest build failed by "brew update failed"

**Review by ggerganov — APPROVED** [review]
Perfect!
I will merge this now.

I think we can improve the developer's experience by memsetting the op arrays to `true` so that all ops are enabled by default and then explicitly disable the ones that do not need `INIT` or `FINALIZE`.

This way I think we will avoid the situations where people wonder why no `INIT` or `FINALIZE` pass is being executed for their newly added ops. Let me know if you agree this is a good idea

**Comment by mqy** [comment]
Sorry for the delay, I'm back.

> ... then explicitly disable the ones that do not need `INIT` or `FINALIZE`.

MAY be better to keep the default behavior for some days, but I think it's OK to keep disabled by default, let me explain:

Suppose a developer committed initial implementation for a newly added OP X.
Somebody saw it does not need INIT, so disabled the INIT of OP X silently.
Some days later, the developer updated his/her algorithm that need INIT again, but does not aware of INIT was disabled.
In this situation, the developer is confused (even more).

Disabling INIT/FINALIZED **by default** is one of the new architecture requirement, developers SHOULD keep it in mind. This makes no difference to upgrading of an API spec. If we can not avoid breaking APIs, we can not avoid breaking architecture as well.

So, instead of keeping enabled by default, I prefer document warning at `ggml_op` (or some good place else), hopefully redirect developer to `GGML_HAS_xxx`.
