### PR TITLE
Avoid heavy V transpose operation + improvements

### LINKED ISSUE #603: Performance Discrepancy: gpt4all Faster than Optimized llama.cpp
**Expected Behavior**

I am comparing the performance of two executables: llama.cpp (current version) and the default gpt4all executable (which uses a previous version of llama.cpp). I am using the same language model for both executables, and I expect the current version of llama.cpp (which is built specifically for the hardware) to perform at least as fast as the default gpt4all executable.

**Current Behavior**

The default gpt4all executable, which uses a previous version of llama.cpp, performs significantly faster than the current version of llama.cpp. Despite building the current version of llama.cpp with hardware-specific compiler flags, it consistently performs significantly slower when using the same model as the default gpt4all executable.

**Environment and Context**

I am running the comparison on a Windows platform, using the default gpt4all executable and the current version of llama.cpp included in the gpt4all project. The version of llama.cpp is the latest available (after the compatibility with the gpt4all model).

**Steps to Reproduce**

1. Build the current version of llama.cpp with hardware-specific compiler flags.
2. Execute the llama.cpp executable using the gpt4all language model and record the performance metrics.
3. Execute the default gpt4all executable (previous version of llama.cpp) using the same language model and record the performance metrics.
4. You'll see that the gpt4all executable generates output significantly faster for any number of threads or config.

Here's some context/config when I'm doing the runs:

image
(left panel is latest llama.cpp, right panel is gpt4all build)

This is the older version that gpt4all uses (with some tweaks): https://github.com/zanussbaum/gpt4all.cpp

*To quickly test the difference yourself you can use the gpt4all default binaries here: https://github.com/nomic-ai/gpt4all/tree/main/chat

### PR DESCRIPTION
**Pull request by ggerganov**
## Human generated notes

I believe this should resolve: #603 #677 #767

When I deprecated the non-contiguous `ggml_mul_mat()` branch in #439, I grossly underestimated the cost of transposing the V matrix on every token. It's a very heavy memory operation, with tons of cache misses.

To solve this, we now store V in the KV cache in transposed state, so we don't need to do it for future tokens.

ggml :

- added ggml_view_3d()
- ggml_view_tensor() now inherits the stride too
- reimplement ggml_cpy() to account for dst stride
- no longer require tensor->data to be memory aligned

llama :

- compute RoPE on 32-bit tensors (should be more accurate)
- store RoPE-ed K in the KV cache
- store transposed V in the KV cache (significant speed-up)
- avoid unnecessary Q copy

---

### Summary
:sparkles::zap::chart_with_upwards_trend:

This pull request enhances the ggml library and the llama project by adding new tensor operations, optimizing existing ones, and using RoPE for self-attention. It also improves the debuggability of the llama project by adding optional timing and plotting code. The main files affected are `ggml.c`, `ggml.h`, and `llama.cpp`.

> _Sing, O Muse, of the mighty ggml, the wondrous library of tensors_
> _That skilled programmers devised with cunning and crafty art_
> _To aid the llama project, the swift and fluent speaker of words_
> _That emulates the GPT-2, the wise and powerful oracle of language_

### Walkthrough
* Optimize the self-attention mechanism in `llama_eval_internal` by using RoPE and view tensors ([link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-150dc86746a90bad4fc2c3334aeb9b5887b3adad3cc1459446717638605348efL813-R841), [link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-150dc86746a90bad4fc2c3334aeb9b5887b3adad3cc1459446717638605348efL861-R875))
* Improve the performance of tensor duplication operations by avoiding unnecessary checks and using memcpy when possible ([link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL4848), [link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL4865-R4992), [link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL4952), [link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL4969-R5086))
* Add a new function `ggml_view_3d` to create 3-dimensional view tensors from source tensors ([link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dR4521-R4551), [link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-f0f2d0dc971e0aa60560e7e3bc1d512b4bf914aedf44333f7008c605433cd394R561-R570))
* Comment out alignment checks in `ggml_new_tensor_impl` to speed up tensor creation ([link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL3222-R3223))
* Copy byte strides in `ggml_view_tensor` to preserve the source tensor layout ([link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-6d9ce99fcb6f51ff76f59e479f6e6fc0bb62edef7442805d7a5bb15b23996b5dL3623-R3631))
* Add optional code for debugging and profiling in `llama_eval_internal` ([link](https://github.com/ggerganov/llama.cpp/pull/775/files?diff=unified&w=0#diff-150dc86746a90bad4fc2c3334aeb9b5887b3adad3cc1459446717638605348efL958-R967))

Edit:

Merging this since we observe M1 and Windows working good.
If you notice something not right, feel free to revert. But I think it should be good

### CODE REVIEW

**Comment by rabidcopy** [comment]
Changes output, but after several runs the uplift in performance seems promising. Best results after running `./main -m ../alpaca-7b-native.bin -b 32  -p "Building a website can be done in 10 simple steps:" -n 100 -t 6 --seed 1` 5 times each for each branch.
Master
```
Building a website can be done in 10 simple steps:
Identify the purpose of the website and the target audience.
Decide on the structure, design and content for the website.
Acquire the domain name, hosting service, and any other services needed to build the website.
Develop the website using HTML/CSS and JavaScript/jQuery.
Test the website to make sure it works properly.
Publish the website online.
Update and maintain the website regularly.
Monitor the website’s analytics and performance.
Ad
llama_print_timings:        load time =  7551.77 ms
llama_print_timings:      sample time =    65.71 ms /   100 runs   (    0.66 ms per run)
llama_print_timings: prompt eval time =  6902.91 ms /    14 tokens (  493.07 ms per token)
llama_print_timings:        eval time = 18582.74 ms /    99 runs   (  187.70 ms per run)
llama_print_timings:       total time = 26201.43 ms
```
PR
```
Building a website can be done in 10 simple steps:
Determine your goals: Before you start building a website, decide what you want it to achieve.
Plan and design: Draw up a plan of the structure and content of your website, and then create attractive visuals that match your branding.
Develop the site: Gather the code and software required to develop the site’s structure and content according to your plan.
Test and troubleshoot: Test out the website thoroughly to make sure it works correctly and fix any
llama_print_timings:        load time =  5587.43 ms
llama_print_timings:      sample time =    65.25 ms /   100 runs   (    0.65 ms per run)
llama_print_timings: prompt eval time =  5030.00 ms /    14 tokens (  359.29 ms per token)
llama_print_timings:        eval time = 15437.18 ms /    99 runs   (  155.93 ms per run)
llama_print_timings:       total time = 21091.10 ms
```
Bonus result of this PR combined with #768.
```
Building a website can be done in 10 simple steps:
Determine your goals: Before you start building a website, decide what you want it to achieve.
Plan and design: Draw up a plan of the structure and content of your website, and then create attractive visuals that match your branding.
Develop the site: Gather the code and software required to develop the site’s structure and content according to your plan.
Test and troubleshoot: Test out the website thoroughly to make sure it works correctly and fix any
llama_print_timings:        load time =  2481.76 ms
llama_print_timings:      sample time =    77.38 ms /   100 runs   (    0.77 ms per run)
llama_print_timings: prompt eval time =  1815.66 ms /    14 tokens (  129.69 ms per token)
llama_print_timings:        eval time = 14191.88 ms /    99 runs   (  143.35 ms per run)
llama_print_timings:       total time = 16752.25 ms
```

File: llama.cpp [hunk 1]
```diff
@@ -858,18 +856,23 @@ static bool llama_eval_internal(
...
+            struct ggml_tensor * V =
+                ggml_view_3d(ctx0, kv_self.v,
+                        n_past + N, n_embd/n_head, n_head,
+                        n_ctx*ggml_element_size(kv_self.v),
+                        n_ctx*ggml_element_size(kv_self.v)*n_embd/n_head,
+                        il*n_ctx*ggml_element_size(kv_self.v)*n_embd);
 
-            // KQV = transpose(V) * KQ_soft_max
-            struct ggml_tensor * KQV = ggml_mul_mat(ctx0, V_trans, KQ_soft_max);
+#if 1
```
Comment (howard0su) [inline llama.cpp:867]: shall we check n_token == 1 to take the different branch?

Comment (ggerganov) [reply llama.cpp:867]: I have a few ideas that might fix this without need to branch here. Will try them first

**Comment by KASR** [comment]
I will test further later on, but I already want to post some intermediate results. The speed is constant throughout the printing, i.e. the performance degradation has been resolved on my pc (windows/cmake/vs).

In attachment you can find the result of `./main -m ./models/7B/ggml-model-q4_0.bin -p "This is a long story about how programming came to be, including an overview of all important programming languages used so far:" -n 2048 -t 18 --temp 0.8 -c 2048 -s -1`

The output reached 1399 words (counted by MS Word) and then halted. After some time I just used ctrl+c to exit. I've tried some other options but many times the output simply places `[end of text]` prints the timings and exits 😅

So I will try to reproduce the behavior of the one run where it got stuck. All other runs produced a shorter text and exit cleanly. 

[output_llama_fix_cpy_n_2048.txt](https://github.com/ggerganov/llama.cpp/files/11160678/output_llama_fix_cpy_n_2048.txt)

**Comment by ggerganov** [comment]
@KASR 
You can use the `--ignore-eos` flag to never get [end of text].
The halting most likely occurred because the context was full, which triggers the context swap procedure, which is quite heavy (especially if you are not using BLAS) and you have to wait for a few seconds for it to continue

**Comment by KASR** [comment]
> @KASR You can use the `--ignore-eos` flag to never get [end of text]. The halting most likely occurred because the context was full, which triggers the context swap procedure, which is quite heavy (especially if you are not using BLAS) and you have to wait for a few seconds for it to continue

Yes indeed 😅 

The output preserves the performance, I reduced `n` a bit to account for the prompt and avoid the context swap (so that it's not reflected in the total time). But even when increasing `n` above `n_ctx` the printing itself preserves the speed (after waiting a bit for the context swap).

Timings for one of the long runs:
```
llama_print_timings:        load time =  1106.80 ms
llama_print_timings:      sample time =   773.61 ms /  1950 runs   (    0.40 ms per run)
llama_print_timings: prompt eval time =  1823.19 ms /    26 tokens (   70.12 ms per token)
llama_print_timings:        eval time = 236098.45 ms /  1949 runs   (  121.14 ms per run)
llama_print_timings:       total time = 239239.01 ms
```

I also did a quick test with various threads, the output remains consistent. See attachment: [output_llama_fix_cpy_various_threads.txt](https://github.com/ggerganov/llama.cpp/files/11160901/output_llama_fix_cpy_various_threads.txt)

So it appears the suggested changes resolve #603 (at least on my pc / configuration) and fixing the issues that #439 tackled.

**Comment by MillionthOdin16** [comment]
Thanks Georgio! Awesome work! And thanks to everyone else who helped narrow down and evaluate performance along the way! Was neat to see everybody come together to help figure this out ❤️

Dang, that GitHub AI assisted PR 🔥🔥😂
