### PR TITLE
webui : added download action (#13552)

### LINKED ISSUE #13552: Misc. bug: missing messages in JSON export via llama-server web UI
### Name and Version

$ ./llama-cli --version
version: 5359 (de4c07f9)
built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
llama-server --threads 10 --model ./Ministral-8B.gguf
```

### Problem description & steps to reproduce

When I use the web UI to download a conversation, a JSON file is downloaded, but I only seem to get the conversation's metadata, while the messages are *not* included.

```
{
  "id": "conv-1747263476494",
  "lastModified": 1747263485918,
  "currNode": 1747263476577,
  "name": "test"
}
```

### First Bad Commit

Not sure. I remember this worked fine with a fresh build from a month ago or so.

**edit:** It still worked in b5124 (bc091a4), which is when the 'Download' button was still located on the right, instead of in a context menu on the left.

### PR DESCRIPTION
**Pull request by srogmann**
Close #13552

This PR adds a download action in Svelte, mirroring the implementation from the previous React release (see #13552). 
The filename now includes a prefix derived from the beginning of the conversation text.

### CODE REVIEW

**Review by mofosyne — APPROVED** [review]
Looks reasonable. Matches PR description. Note that it outputs the conversation as JSON.

**Comment by srogmann** [comment]
There was a JSON-download in https://github.com/ggml-org/llama.cpp/blob/b34c859146630dff136943abc9852ca173a7c9d6/tools/server/webui/src/components/Header.tsx#L39

**Comment by allozaur** [comment]
Hey, @srogmann, thanks for this! I was thinking that maybe additional to this we could add importing/uploading conversations as well? Let me know if u would like to add this or rather have me take over this.

**Comment by srogmann** [comment]
Hi @allozaur , I thought about a transfer of https://github.com/ggml-org/llama.cpp/compare/master...srogmann:llama.cpp:feature/import_export_all to Svelte.

**Comment by srogmann** [comment]
I've added import and export functionality for all conversations. However, import currently only supports importing all conversations at once. Importing individual conversations is still missing (the import could detect if the JSON file contains just one conversation and then import only that one).

**Comment by allozaur** [comment]
Hey! I will take a closer look at these changes this week. I'll keep u posted 🙂

**Comment by ServeurpersoCom** [comment]
Looks great this functionality is really a must-have for the web UI

**Comment by allozaur** [comment]
@srogmann could you please resolve the conflict? after that i'd love to take a look and test it out :)

**Comment by srogmann** [comment]
@allozaur  Conflicts are now resolved with a rebase, ready for your review and feedback!

**Comment by allozaur** [comment]
@srogmann i've pushed a PR with small UX improvements (srogmann/llama.cpp/pull/1), please review it and if all is good, let's first merege it to your branch and finally we will have green light to merge this PR :)

**Review by allozaur — APPROVED** [review]

**Comment by allozaur** [comment]
@srogmann please just add the static build output to this PR and we're good to go :)

**Comment by srogmann** [comment]
@allozaur The static build output has been updated.

**Comment by bughunter2** [comment]
I really like the new **import** feature. This allows me to keep my chat sessions cleaned up and still resume a chat later on by importing a JSON that I exported perhaps weeks or months earlier. I just built llama.cpp b6709 from source and the first impression is good. **Edit**: Reasoning output isn't shown in the web UI when using popular models like GPT-OSS and Qwen3, but I suppose the web UI developers are aware of this(?).

**Comment by ngxson** [comment]
I think the import and export buttons placement seems to be quite inconvenient. It uses up quite a lot of spaces while most users don't use it very frequently. Is there any other places to hide it? @allozaur 

image

Maybe inside the settings dialog, we add a new section called "Import / Export"?

image

**Comment by ServeurpersoCom** [comment]
Indeed, the general import/export feature could be placed under Settings (like in llama.ui).
The export of a single conversation is fine where it is (in the conversation’s context menu).

File: tools/server/webui/src/lib/components/app/chat/ChatSidebar/ChatSidebarActions.svelte [hunk 1]
```diff
@@ -77,5 +78,34 @@
...
+		<Button
+			class="w-full justify-start text-sm"
+			onclick={() => {
+				exportAllConversations();
+			}}
+			variant="ghost"
+		>
+			<div class="flex items-center gap-2">
+				<Download class="h-4 w-4" />
+				Export all conversations
```
Comment (ngxson) [inline tools/server/webui/src/lib/components/app/chat/ChatSidebar/ChatSidebarActions.svelte:107]: Why here we add the word `all` but it's not in the `Import conversations`? It's a bit inconsistent in term of UI design

Either have `Import conversations / Export conversations`

or `Import all conversations / Export all conversations`

Comment (ServeurpersoCom) [reply tools/server/webui/src/lib/components/app/chat/ChatSidebar/ChatSidebarActions.svelte:107]: Because you can import 1 json for 1 conversation here

Comment (allozaur) [reply tools/server/webui/src/lib/components/app/chat/ChatSidebar/ChatSidebarActions.svelte:107]: @ngxson yeah, actually i didn't see any ideal solution at that time, but maybe we can revisit this particular UI and rethink how to name/present these options. Should i create a new issue for that?

Comment (ngxson) [reply tools/server/webui/src/lib/components/app/chat/ChatSidebar/ChatSidebarActions.svelte:107]: I think this is kinda a basic UI/UX problem with trivial solution, so we don't need to spend too much time for it (no need to create issue)

Just moving these buttons under Settings dialog is ok, suggested by both me & @ServeurpersoCom in the comments above

And for the buttons label, I think dropping the word "all" won't hurt anyone. It's quite obvious that the button will export all conversations as there is **no** options to select **some** conversations for exporting

Comment (allozaur) [reply tools/server/webui/src/lib/components/app/chat/ChatSidebar/ChatSidebarActions.svelte:107]: Sure, i will just push a PR with the improvements for this

Comment (allozaur) [reply tools/server/webui/src/lib/components/app/chat/ChatSidebar/ChatSidebarActions.svelte:107]: Added #16619
