### PR TITLE
ggml-backend : fix async copy from CPU

### LINKED ISSUE #8685: Bug: (CUDA) Corrupted output when offloading to multiple GPUs
### Problem

Some models produce a corrupted output when offloading to multiple CUDA GPUs. The problem disappears when offloading to a single GPU or using CPU only.

I was able to reproduce the problem in:
- [llama 3.0 8B](https://huggingface.co/bartowski/Meta-Llama-3-8B-Instruct-GGUF/blob/main/Meta-Llama-3-8B-Instruct-Q6_K.gguf)
- llama 3.1 8b
- glm-4-9b

while I was unable to reproduce it in:
- Mistral Nemo 

### Bug 1

When offloading to multiple GPUs, the model gives the wrong answer. It seems unable to parse the prompt correctly.

### Bug 2

When a second prompt is sent to the model, the model reuses information from the first prompt.

### Steps to reproduce Bug 1

- download [llama 3.0 8B](https://huggingface.co/bartowski/Meta-Llama-3-8B-Instruct-GGUF/blob/main/Meta-Llama-3-8B-Instruct-Q6_K.gguf) from HF
- download my sample prompt: 
[llama-multi-gpu-bug.txt](https://github.com/user-attachments/files/16373846/llama-multi-gpu-bug.txt)
- launch with: `CUDA_VISIBLE_DEVICES=0 ./llama-cli -c 8192  -m Meta-Llama-3-8B-Instruct-Q6_K.gguf -ngl 99 -f /tmp/llama-multi-gpu-bug.txt -sp -s 0`
- verify that the model answers correctly: (Alice:7, Bob:8, Charlie:7) the full log is provided below.
- launch again with `CUDA_VISIBLE_DEVICES=0,1 ./llama-cli -c 8192  -m Meta-Llama-3-8B-Instruct-Q6_K.gguf -ngl 99 -f /tmp/llama-multi-gpu-bug.txt -sp -s 0`
- The model is unable to answer: (Alice:7, Bob:7, Charlie: null) then says that Charlie didn't provide an answer.

### Steps to reproduce Bug 2

- launch the server with `CUDA_VISIBLE_DEVICES=0,1 ./llama-server -ngl 99 -c 8192 -m Meta-Llama-3-8B-Instruct-Q6_K.gguf`
- go to New UI
- Select llama 3 template.
- Copy and paste the content of the sample prompt: 
[apples_majority.txt](https://github.com/user-attachments/files/16373941/apples_majority.txt) and send
- The model gives the same corrupted answer as in Bug 1
- Go back
- Copy and paste this new prompt 
[apples_simple.txt](https://github.com/user-attachments/files/16373949/apples_simple.txt) and send
- The model gives a json answer as if answering the first prompt

The second prompt shares a common prefix with the first prompt.

### Full log for the correct answer:
```
Here is the output:

{
  "answers": {
    "alice": 7,
    "bob": 8,
    "charlie": 7
  },
  "reasoning": "The users provided different answers based on their step-by-step breakdowns of the problem, but they all reached the conclusion that Matteo discards a quarter of his remaining fruits equally between apples and oranges.",
  "who is right": "It's a tie between Alice and Charlie, as they both answered 7 apples remaining.",
  "answer": 7
}

Note that since Alice and Charlie have the same answer, 7, they are considered the "right" answer based on majority voting.
```

### Full log for the wrong answer
```
Here is the output:

{
  "answers": {
    "alice": 7,
    "bob": 7,
    "charlie": null
  },
  "reasoning": "Both Alice and Bob provided the same answer, which is 7 apples. Since Charlie did not provide an answer, we use majority voting to determine the correct answer.",
  "who is right": "Alice and Bob",
  "answer": 7
}

In this case, both Alice and Bob provided the same answer, which is 7 apples. Since Charlie did not provide an answer, we use majority voting to determine the correct answer, which is 7 apples.
```

### My setup:

Linux with:
- Nvidia 4060 16GB
- Nvidia 3060 12GB

### Name and Version

version: 3463 (dc820804)
built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu

The reference model is llama3.0 8b by bartowski, SHA256: d6f1dcba991f8e629531a5f4cf19e4dbc2a89f80fd20737e256b92aac11572f1

### What operating system are you seeing the problem on?

Linux

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by slaren**
Fixes #8685

The problem was that some copies from the CPU backend to the CUDA backend were not correctly synchronized, which in some cases could allow the CPU backend to overwrite the data in the next batch, before it was copied to the GPU.

### CODE REVIEW

**Comment by slaren** [comment]
@matteoserva please let me know if this fixes the issue in your system. I already tested this on @JohannesGaessler machine, so I expect it works there.

**Review by JohannesGaessler — COMMENTED** [review]
Why does the destination backend need to be synchronized in `ggml_backend_tensor_copy_async` but not in `ggml_backend_sched_compute_splits`?

**Comment by slaren** [comment]
The idea is that the scheduler makes multiple copies of every input and synchronizes access to them with events. However there was a missing `ggml_backend_event_synchronize` in this case, it should be fixed now.

File: ggml/src/ggml-backend.c [hunk 1]
```diff
@@ -1782,7 +1777,17 @@ static enum ggml_status ggml_backend_sched_compute_splits(ggml_backend_sched_t s
...
                 }
-                ggml_backend_tensor_copy_async(input_backend, split_backend, input, input_cpy);
+                // try async copy, but if not possible, we can still use a sync copy without synchronizing the dst backend, since we handle the synchronization here with multiple copies and events
+                // TODO: add public function to facilitate this, since applications do not have direct access to the backend interface
+                if (!split_backend->iface.cpy_tensor_async || !split_backend->iface.cpy_tensor_async(input_backend, split_backend, input, input_cpy)) {
+                    ggml_backend_synchronize(input_backend);
+                    if (sched->events[split_backend_id][sched->cur_copy] != NULL) {
+                        ggml_backend_event_synchronize(sched->events[split_backend_id][sched->cur_copy]);
+                    } else {
+                        ggml_backend_synchronize(split_backend);
```
Comment (JohannesGaessler) [inline ggml/src/ggml-backend.c:1787]: I think this synchronization call can be optimized out since with a null event the backend has already been synchronized. But if there is no measurable performance difference it may be better to just keep it in to make the code easier to understand.

Comment (slaren) [reply ggml/src/ggml-backend.c:1787]: Yes, I left it there for clarity. For backends that don't support events, `ggml_backend_synchronize` should be a no-op anyway.

**Comment by JohannesGaessler** [comment]
Prior to the latest commit the fix was working on my second machine with 3x P40. I'll review the new changes tomorrow.

**Comment by slaren** [comment]
The changes to `ggml_backend_cuda_cpy_tensor_async` in the latest commit are not related to this issue, and these cases are never hit in llama.cpp. Nonetheless, I found these issues while looking into this, so I am fixing it now to avoid other issues in the future.

**Comment by matteoserva** [comment]
@slaren The patch fixed the issue on my system. Thank you!

File: ggml/src/ggml-cuda.cu [hunk 2]
```diff
@@ -2358,33 +2358,35 @@ GGML_CALL static void ggml_backend_cuda_get_tensor_async(ggml_backend_t backend,
...
-        GGML_ASSERT(cuda_ctx_src->device == buf_ctx_src->device);
-        GGML_ASSERT(cuda_ctx_dst->device == buf_ctx_dst->device);
+    if (cuda_ctx_src->device != buf_ctx_src->device || cuda_ctx_dst->device != buf_ctx_dst->device) {
+#ifndef NDEBUG
+        GGML_CUDA_LOG_WARN("%s: backend and buffer devices do not match\n", __func__);
+#endif
+        return false;
+    }
 
+    if (backend_src != backend_dst) {
```
Comment (JohannesGaessler) [inline ggml/src/ggml-cuda.cu:2386]: How is it ensured that there are no race conditions between `backend_src` and `backend_dst` for this code branch?

Comment (slaren) [reply ggml/src/ggml-cuda.cu:2386]: What race conditions are you thinking about? It uses an event to synchronize the two streams.

Comment (JohannesGaessler) [reply ggml/src/ggml-cuda.cu:2386]: I think I misinterpreted the code. If my understanding is correct the synchronization happens outside this function.

**Review by JohannesGaessler — APPROVED** [review]

File: ggml/src/ggml-cuda.cu (hunk 2 above)
Comment (slaren) [reply ggml/src/ggml-cuda.cu:2386]: Part of the synchronization is done in this function, but the most complicated parts happen in ggml_backend_sched. Ultimately, the only responsability of this function is to implement the semantics of the `copy_async` interface of ggml-backend, as defined in `ggml-backend.h`:
```C++
    // asynchronous copy
    // the copy is performed after all the currently queued operations in backend_src
    // backend_dst will wait for the copy to complete before performing other operations
    // automatic fallback to sync copy if async is not supported
    GGML_API void ggml_backend_tensor_copy_async(ggml_backend_t backend_src, ggml_backend_t backend_dst, struct ggml_tensor * src, struct ggml_tensor * dst);
```
