### PR TITLE
llama : offload to RPC in addition to other backends

### LINKED ISSUE #7711: Bug: test run on stories15M-q4_0.gguf result in Segmentation fault.
### What happened?

For b3072 on x86-64 when I run llama-main on `stories15M-q4_0.gguf` or `stories260K.gguf` it crashes. It crashes on `test-eval-callback` test too.

### Name and Version

This test is for tag b3072 at 549279d8. b3012 had no problem with it.

### What operating system are you seeing the problem on?

ALT Linux

### Relevant log output

```shell
llama.cpp (sisyphus)$ gdb --args llama-main -m stories15M-q4_0.gguf -n 400 -p "Once opon a time"
GNU gdb (GDB) 14.1.0.56.d739d4fd457-alt1 (ALT Sisyphus)
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-alt-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from llama-main...
Reading symbols from /usr/lib/debug/usr/bin/llama-main.debug...
(gdb) r
Starting program: /usr/bin/llama-main -m stories15M-q4_0.gguf -n 400 -p Once\ opon\ a\ time
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Log start
main: build = 3072 (alt1.20240603)
main: built with x86_64-alt-linux-gcc (GCC) 13.2.1 20240128 (ALT Sisyphus 13.2.1-alt3) for x86_64-alt-linux
main: seed  = 1717403314
llama_model_loader: loaded meta data with 20 key-value pairs and 57 tensors from stories15M-q4_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv   1:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv   2:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv   3:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv   4:                       general.architecture str              = llama
llama_model_loader: - kv   5:                               general.name str              = llama
llama_model_loader: - kv   6:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv   7:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv   8:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv   9:          tokenizer.ggml.seperator_token_id u32              = 4294967295
llama_model_loader: - kv  10:            tokenizer.ggml.padding_token_id u32              = 4294967295
llama_model_loader: - kv  11:                       llama.context_length u32              = 128
llama_model_loader: - kv  12:                     llama.embedding_length u32              = 288
llama_model_loader: - kv  13:                  llama.feed_forward_length u32              = 768
llama_model_loader: - kv  14:                 llama.attention.head_count u32              = 6
llama_model_loader: - kv  15:                          llama.block_count u32              = 6
llama_model_loader: - kv  16:                 llama.rope.dimension_count u32              = 48
llama_model_loader: - kv  17:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  18:               general.quantization_version u32              = 2
llama_model_loader: - kv  19:                          general.file_type u32              = 2
llama_model_loader: - type  f32:   13 tensors
llama_model_loader: - type q4_0:   43 tensors
llama_model_loader: - type q8_0:    1 tensors
llm_load_vocab: bad special token: 'tokenizer.ggml.seperator_token_id' = 4294967295d, using default id -1
llm_load_vocab: bad special token: 'tokenizer.ggml.padding_token_id' = 4294967295d, using default id -1
llm_load_vocab: special tokens cache size = 259
llm_load_vocab: token to piece cache size = 0.1684 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 128
llm_load_print_meta: n_embd           = 288
llm_load_print_meta: n_head           = 6
llm_load_print_meta: n_head_kv        = 6
llm_load_print_meta: n_layer          = 6
llm_load_print_meta: n_rot            = 48
llm_load_print_meta: n_embd_head_k    = 48
llm_load_print_meta: n_embd_head_v    = 48
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 288
llm_load_print_meta: n_embd_v_gqa     = 288
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 768
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 128
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = ?B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 24.41 M
llm_load_print_meta: model size       = 17.50 MiB (6.01 BPW)
llm_load_print_meta: general.name     = llama
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.03 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/7 layers to GPU
llm_load_tensors:        CPU buffer size =    17.50 MiB
.....................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =     3.38 MiB
llama_new_context_with_model: KV self size  =    3.38 MiB, K (f16):    1.69 MiB, V (f16):    1.69 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.12 MiB

Program received signal SIGSEGV, Segmentation fault.
=> 0x55555564c757 <llama_new_context_with_model(llama_model*, llama_context_params)+5943>:      call   *0x28(%rax)
0x000055555564c757 in ggml_backend_buft_supports_backend (backend=0x555555bb3dd0, buft=0x0) at /usr/src/debug/llama.cpp-3072/ggml-backend.c:48
48          return buft->iface.supports_backend(buft, backend);
(gdb)
(gdb) bt
#0  0x000055555564c757 in ggml_backend_buft_supports_backend (backend=0x555555bb3dd0, buft=0x0) at /usr/src/debug/llama.cpp-3072/ggml-backend.c:48
#1  ggml_backend_sched_new (graph_size=8192, parallel=false, n_backends=2, bufts=0x555555bb3d30, backends=0x55555580bcc0)
    at /usr/src/debug/llama.cpp-3072/ggml-backend.c:1750
#2  llama_new_context_with_model (model=<optimized out>, params=...) at /usr/src/debug/llama.cpp-3072/llama.cpp:16504
#3  0x00005555555a6ac2 in llama_init_from_gpt_params (params=...) at /usr/src/debug/llama.cpp-3072/common/common.cpp:1915
#4  0x00005555555814c0 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/llama.cpp-3072/examples/main/main.cpp:199
```

There is temporary build log with the test run at the end: https://git.altlinux.org/tasks/350238/build/400/x86_64/log

Crash also occurs on aarch64, and if compiled without openblas.

### PR DESCRIPTION
**Pull request by rgerganov**
This patch adds support for offloading layers to RPC servers in addition to other non-RPC backends. For example if you build with `-DLLAMA_CUDA=ON -DLLAMA_RPC=ON`, then you can offload to local GPU and remote server(s):

```bash
$ bin/main -m ../models/ggml-model-f16.gguf -p "Hello, my name is" -n 64 -ngl 99 -s 1236 --rpc localhost:50052
...
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA T1200 Laptop GPU, compute capability 7.5, VMM: yes
llm_load_tensors: ggml ctx size =    0,31 MiB
llm_load_tensors: offloading 22 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 23/23 layers to GPU
llm_load_tensors:        CPU buffer size =   125,00 MiB
llm_load_tensors:      CUDA0 buffer size =  1008,19 MiB
llm_load_tensors:        RPC buffer size =   965,16 MiB
..........................................................................................
```

I have tried to follow the existing patterns in `llama.cpp` and introduced device numbers for RPC servers which always come last.

When copying tensors, we need to handle the case when `src` and `dst` are not on the same backend. For CUDA I had to build with `-DLLAMA_CUDA_NO_PEER_COPY=ON` to make it work.

### CODE REVIEW

**Comment by slaren** [comment]
> When copying tensors, we need to handle the case when `src` and `dst` are not on the same backend. For CUDA I had to build with `-DLLAMA_CUDA_NO_PEER_COPY=ON` to make it work.

The way this is supposed to work is that backends need to check the buffer type of the tensors to determine if they can perform the copy, and return `false` otherwise. The CUDA backend should already do this. What happens exactly if you don't use `LLAMA_CUDA_NO_PEER_COPY`, does it crash somewhere or does it produce wrong results?

File: ggml-rpc.h [hunk 1]
```diff
@@ -10,12 +10,14 @@ extern "C" {
 #define GGML_RPC_MAX_SERVERS       16
 
 // backend API
-GGML_API GGML_CALL ggml_backend_t ggml_backend_rpc_init(const char * endpoint);
+GGML_API GGML_CALL void ggml_backend_rpc_setdevice(const char * endpoint, int device);
```
Comment (slaren) [inline ggml-rpc.h:13]: I think it is a bad idea to add this as global state of the RPC backend. For example, this will prevent loading a model with a set of RPC servers, and a different model with a different set of RPC servers at the same time. Is it really necessary? I think it was ok to refer to each RPC server by a endpoint string, rather than a device index.

**Comment by rgerganov** [comment]
> The way this is supposed to work is that backends need to check the buffer type of the tensors to determine if they can perform the copy, and return `false` otherwise. The CUDA backend should already do this. What happens exactly if you don't use `LLAMA_CUDA_NO_PEER_COPY`, does it crash somewhere or does it produce wrong results?

It crashes in `ggml_backend_cuda_buffer_cpy_tensor()` because it assumes that `dst` is allocated by the CUDA backend which is not the case. I think we should add a check in `ggml_backend_tensor_copy()` if both tensors are on the same backend and perform the slow copy if they are not.

File: ggml-rpc.h (hunk 1 above)
Comment (rgerganov) [reply ggml-rpc.h:13]: The intent was to make it consistent with other backends like CUDA and sycl but I agree that having a global state is not great. I will add more special handling in `llama.cpp` and revert the changes in the RPC backend.

**Comment by slaren** [comment]
https://github.com/rgerganov/llama.cpp/pull/1 should fix it.

**Comment by rgerganov** [comment]
@slaren thanks, I have verified your fix and merged it

File: llama.cpp [hunk 2]
```diff
@@ -16427,6 +16428,18 @@ struct llama_context * llama_new_context_with_model(
...
+        for (int i = 0; i < (int)model->rpc_servers.size(); i++) {
+            const char * endpoint = model->rpc_servers[i].c_str();
+            ggml_backend_t backend = ggml_backend_rpc_init(endpoint);
+            if (backend == nullptr) {
+                LLAMA_LOG_ERROR("%s: failed to initialize RPC to '%s'\n", __func__, endpoint);
+                llama_free(ctx);
+                return nullptr;
+            }
+            ctx->backends.push_back(backend);
+        }
```
Comment (slaren) [inline llama.cpp:16442]:
```suggestion
        if (model->n_gpu_layers > 0) {
            for (const auto & endpoint : model->rpc_servers) {
                ggml_backend_t backend = ggml_backend_rpc_init(endpoint);
                if (backend == nullptr) {
                    LLAMA_LOG_ERROR("%s: failed to initialize RPC to '%s'\n", __func__, endpoint);
                    llama_free(ctx);
                    return nullptr;
                }
                ctx->backends.push_back(backend);
            }
        }
```

#7711 made me realize that `ggml_backend_rpc_init` cannot fail because it never attempts a connection. Then it returns a `NULL` buffer type in `get_default_buffer_type`, which is never supposed to happen.

Comment (rgerganov) [reply llama.cpp:16442]: should we also check for `LLAMA_SPLIT_MODE_LAYER` here in addition to `n_gpu_layers > 0`?

Comment (slaren) [reply llama.cpp:16442]: All modes would require initializing the RPC backend. It could be improved to check that the backend is actually used in the model before instantiating it, but mostly the goal here is to avoid issues with `-ngl 0`. I think that the bug on master that causes a RPC backend with a empty name to be initialized always is not present here.

**Review by slaren — APPROVED** [review]

**Comment by zhouwg** [comment]
@rgerganov, hello, I'm sorry to disturb you. could you do a more carefully check before your PR merged to master branch? I know you are the brother of the original author of the original author of ggml/llama.cpp/whisper.cpp and you have some privileges. but your modifications in llama.cpp might be have side-effect to other backend developers. Thanks for your understanding.

**Comment by rgerganov** [comment]
> could you do a more carefully check before your PR merged to master branch?

My changes have been reviewed and the CI run was successful.

> and you have some privileges and this is the key reason why your PR was approved so quickly although the quality of your PR is might-be need more check.

I don't have any privileges in this project and my code is being reviewed as everybody's else. You'd better have some arguments when saying something about the quality of my changes.

> I'm not sure whether you might did wrong deletions in llama.cpp and cause the troubles for rebase operation by the other community backend developer

When someone is proposing a change it is their responsibility to address review comments and make sure that the change can be applied on current `master`. The changes I have done in `llama.cpp` are trivial and rebasing other changes on top of them is also trivial.

> I hope you can do more carefully check before your PR was merged to master branch.

My change has been reviewed and approved by a core maintainer and the CI run was successful.

**Comment by zhouwg** [comment]
> > could you do a more carefully check before your PR merged to master branch?
> 
> My changes have been reviewed and the CI run was successful.
> 
> > and you have some privileges and this is the key reason why your PR was approved so quickly although the quality of your PR is might-be need more check.
> 
> I don't have any privileges in this project and my code is being reviewed as everybody's else. You'd better have some arguments when saying something about the quality of my changes.
> 
> > I'm not sure whether you might did wrong deletions in llama.cpp and cause the troubles for rebase operation by the other community backend developer
> 
> When someone is proposing a change it is their responsibility to address review comments and make sure that the change can be applied on current `master`. The changes I have done in `llama.cpp` are trivial and rebasing other changes on top of them is also trivial.
> 
> > I hope you can do more carefully check before your PR was merged to master branch.
> 
> My change has been reviewed and approved by a core maintainer and the CI run was successful.

Yes, you are right:"When someone is proposing a change it is their responsibility to address review comments and make sure that the change can be applied on current `master`.". my rebase operation has conflict your latest PR in ggml-rpc.cpp.

**Comment by slaren** [comment]
@zhouwg I am having a very hard time understating what you are complaining about here. It is the responsibility of PR authors to deal with merge conflicts caused by changes to the code merged to the repository. How could it be otherwise? The RPC backend has been submit to the same quality requirements as any other PRs merged to llama.cpp.

The QNN backend cannot be merged in its current state because it is not a functional backend. It is not correct to say that it has been waiting for review since 4/24/2024 because there is nothing to review until it is a functional backend that people can try. Generally, we will not merge non-functional code in the hope that other people will complete the missing parts.

You have two ways to make it functional: implement the missing operations, or wait until ggml-backend implements support for using the CPU backend for ops not supported by a backend. I understand that you are frustrated, but please try to be patient.

**Comment by zhouwg** [comment]
> @zhouwg I am having a very hard time understating what you are complaining about here. It is the responsibility of PR authors to deal with merge conflicts caused by changes to the code merged to the repository. How could it be otherwise? The RPC backend has been submit to the same quality requirements as any other PRs merged to llama.cpp.
> 
> The QNN backend cannot be merged in its current state because it is not a functional backend. It is not correct to say that it has been waiting for review since 4/24/2024 because there is nothing to review until it is a functional backend that people can try. Generally, we will not merge non-functional code in the hope that other people will complete the missing parts.
> 
> You have two ways to make it functional: implement the missing operations, or wait until ggml-backend implements support for using the CPU backend for ops not supported by a backend. I understand that you are frustrated, but please try to be patient.

I'm sorry for that and pls don't care what I said(which is just a personal feeling/thoughts and I still think you are a real AI expert and C/C++ master) in this PR.

1.I provide a general approach based on the existing ggml backend subsystem for CPU&GPU / CPU&NPU mixed inference very easily in PR:[refine backend subsystem for CPU&GPU / CPU&NPU mixed inference more easily for a specified GGML backend](https://github.com/ggerganov/llama.cpp/pull/7641), but you said it's not correct and will not work although it's works very well on my local dev envs.

2.The QNN backend is more mature if we compare to the ggml-rpc backend, this is also a personal feeling.

3.You are the author/maintainer of ggml backend subsystem, so I respect your decision.

File: ggml-backend.c [hunk 3]
```diff
@@ -1887,15 +1887,15 @@ ggml_backend_t ggml_backend_sched_get_tensor_backend(ggml_backend_sched_t sched,
...
     GGML_ASSERT(tensor->buffer == NULL);
     GGML_ASSERT(tensor->view_src != NULL);
     GGML_ASSERT(tensor->view_src->buffer != NULL);
     GGML_ASSERT(tensor->view_src->data != NULL);
 
-    tensor->buffer = buffer;
+    tensor->buffer = tensor->view_src->buffer;
     tensor->data = (char *)tensor->view_src->data + tensor->view_offs;
-    ggml_backend_buffer_init_tensor(buffer, tensor);
+    ggml_backend_buffer_init_tensor(tensor->buffer, tensor);
```
Comment (airMeng) [inline ggml-backend.c:1898]: This breaks the latest SYCL support. Could I know if all the other backends assumes the buffer already bound to the right tensor?

@slaren @rgerganov for awareness

Comment (slaren) [reply ggml-backend.c:1898]: It's the same issue that was fixed for the Vulkan backend in #7806, there are more details about why this happens and why the change was necessary there. The best way to fix this for the SYCL backend would be to remove the extras entirely in the same way they were removed from the CUDA backend.

Comment (rgerganov) [reply ggml-backend.c:1898]: > we are maintaining SYCL during spare time and are still begging for official support from the company

Having a dedicated machine which runs the CI with the SYCL backend would be very helpful

**Comment by metal3d** [comment]
I see that you reverted this merge. Does it mean that it will not work with others backend? I'm using Vulkan instead of CUDA (for many reasons), and actually I can see that `rpc-server` binary is linked to libvulkan, but the binary says "create_backend: using CPU backend".

**Comment by belog2867** [comment]
I also encountered such a problem. I compiled the rpc of opencl backend for Android, but it was output when I run it .
 started.create_backend: using CPU backend

But the independent llama-cli can call the opencl backend.

**Comment by slaren** [comment]
@zhouwg ok, I have deleted the comment.
