### PR TITLE
vulkan: initialize vulkan-hpp to allow using extension function pointers

### LINKED ISSUE #15698: Compile bug: undefined symbol: vkResetQueryPool for  android-ndk-r29-beta3
### Git commit

master branch bbbf5ec 

### Operating systems

Other? (Please let us know in description)

### GGML backends

Vulkan

### Problem description & steps to reproduce

There is no vkResetQueryPool for android vulkan.

```sh
[100%] Linking CXX executable ../../bin/llama-server
ld.lld: error: undefined symbol: vkResetQueryPool
>>> referenced by vulkan.hpp:2212 (/opt/d/C/vulkan/include/vulkan/vulkan.hpp:2212)
>>>               ../../ggml/src/ggml-vulkan/llama-server.lto.libggml-vulkan.a(ggml-vulkan.cpp.o at 83020).o:(ggml_backend_vk_graph_compute(ggml_backend*, ggml_cgraph*))
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/server/CMakeFiles/llama-server.dir/build.make:118: bin/llama-server] Error 1
make[1]: *** [CMakeFiles/Makefile2:531: tools/server/CMakeFiles/llama-server.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### First Bad Commit

_No response_

### Compile command

```shell
cmake -DGGML_CPU=ON -DGGML_CPU_AARCH64=ON -DGGML_CUDA_FA=OFF -DGGML_CUDA_GRAPHS=OFF -DGGML_HIP_NO_VMM=OFF -DGGML_HIP_MMQ_MFMA=OFF -DGGML_LASX=OFF -DGGML_LSX=OFF -DGGML_METAL=OFF -DGGML_METAL_EMBED_LIBRARY=OFF -DGGML_METAL_NDEBUG=OFF -DGGML_METAL_USE_BF16=OFF -DGGML_ACCELERATE=OFF -DGGML_OPENCL=OFF -DGGML_OPENCL_EMBED_KERNELS=OFF -DGGML_OPENCL_USE_ADRENO_KERNELS=OFF -DGGML_OPENMP=ON -DGGML_RVV=OFF -DGGML_VXE=OFF -DGGML_SYCL_GRAPH=OFF -DGGML_VULKAN=ON -DGGML_BLAS=OFF -DGGML_LTO=ON -DLLAMA_CURL=OFF -DBUILD_SHARED_LIBS=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_SERVER=ON -DLLAMA_BUILD_TOOLS=ON -DGGML_LLAMAFILE=OFF
```

### Relevant log output

```shell
use https://github.com/KhronosGroup/Vulkan-Headers.git with android-ndk-r29-beta3, enable vulkan.
```

### PR DESCRIPTION
**Pull request by jeffbolznv**
Use this to query register count for shader compiles on NVIDIA. Currently this is only for performance debug, but it could eventually be used in some heuristics like split_k.

Fixes #15698.

### CODE REVIEW

**Review by 0cc4m — APPROVED** [review]
Sorry for the delay

File: ggml/src/ggml-vulkan/ggml-vulkan.cpp [hunk 1]
```diff
@@ -1519,6 +1529,20 @@ static void ggml_vk_create_pipeline_func(vk_device& device, vk_pipeline& pipelin
         vk_instance.pfn_vkSetDebugUtilsObjectNameEXT(device->device, &static_cast<VkDebugUtilsObjectNameInfoEXT &>(duoni));
     }
 
+    if (device->pipeline_executable_properties_support) {
+        vk::PipelineExecutableInfoKHR executableInfo;
+        executableInfo.pipeline = pipeline->pipeline;
+
+        auto statistics = device->device.getPipelineExecutableStatisticsKHR(executableInfo);
```
Comment (0cc4m) [inline ggml/src/ggml-vulkan/ggml-vulkan.cpp:1536]: Debug mode is now giving me this warning:
```
vkGetPipelineExecutableStatisticsKHR(): called on a pipeline created without the VK_PIPELINE_CREATE_CAPTURE_STATISTICS_BIT_KHR flag set.
The Vulkan spec states: The pipeline member of pExecutableInfo must have been created with VK_PIPELINE_CREATE_CAPTURE_STATISTICS_BIT_KHR (https://docs.vulkan.org/spec/latest/chapters/pipelines.html#VUID-vkGetPipelineExecutableStatisticsKHR-pipeline-03274)
```

**Comment by ggerganov** [comment]
I think this report is related to the changes in this PR: https://github.com/ggml-org/ggml/pull/1344#discussion_r2371295675

File: ggml/src/ggml-vulkan/ggml-vulkan.cpp [hunk 2]
```diff
@@ -5,8 +5,14 @@
...
 #endif
 
+// See https://github.com/KhronosGroup/Vulkan-Hpp?tab=readme-ov-file#extensions--per-device-function-pointers-
+#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
+
 #include <vulkan/vulkan.hpp>
 
+// See https://github.com/KhronosGroup/Vulkan-Hpp?tab=readme-ov-file#extensions--per-device-function-pointers-
+VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE
+
```
Comment (dg0yt) [inline ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: IMO this doesn't belong into the ggml library. It can exist once in the whole program.
https://github.com/ggml-org/ggml/pull/1344#discussion_r2371288834.

Comment (jeffbolznv) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: Let me see if I can forgo the macros and define a dispatcher with static linkage.

Comment (jeffbolznv) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: I couldn't get `static` to work - vulkan-hpp uses `extern` to forward declare and it can't be both extern and static.

Choosing a unique namespace ought to work. @dg0yt please try this:

```
diff --git a/ggml/src/ggml-vulkan/ggml-vulkan.cpp b/ggml/src/ggml-vulkan/ggml-vulkan.cpp
index 0feaf4cb5..bc26ec8f5 100644
--- a/ggml/src/ggml-vulkan/ggml-vulkan.cpp
+++ b/ggml/src/ggml-vulkan/ggml-vulkan.cpp
@@ -5,6 +5,9 @@
 #include "ggml-cpu.h"
 #endif

+// make vulkan-hpp vk namespace unique for this file, to avoid conflicts when linking
+#define vk ggml_vk
+
 // See https://github.com/KhronosGroup/Vulkan-Hpp?tab=readme-ov-file#extensions--per-device-function-pointers-
 #define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
```

Comment (Acly) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: Possible alternative that only renames the dispatcher:
```
namespace vk::detail { class DispatchLoaderDynamic; }
vk::detail::DispatchLoaderDynamic & ggml_vk_default_dispatcher();

#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
#define VULKAN_HPP_DEFAULT_DISPATCHER ggml_vk_default_dispatcher()

#include <vulkan/vulkan.hpp>

static vk::detail::DispatchLoaderDynamic ggml_vk_default_dispatcher_instance;
vk::detail::DispatchLoaderDynamic & ggml_vk_default_dispatcher() {
    return ggml_vk_default_dispatcher_instance;
}
```

Comment (jeffbolznv) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: oh yeah, laundering it through a function call may work.

Comment (dg0yt) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: I wouldn't feel comfortable with the `vk` macro. But for renaming the namespace, there seems to be a direct and safe control: `VULKAN_HPP_NAMESPACE`.
https://github.com/KhronosGroup/Vulkan-Hpp?tab=readme-ov-file#vulkan_hpp_namespace- 
With recent vulkan-hpp, it would be a one-line change, but for my installation I had to deal with https://github.com/KhronosGroup/Vulkan-Hpp/issues/2093.
~~~diff
 #define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
+#define VULKAN_HPP_NAMESPACE ggml_vk
+// Workaroud for https://github.com/KhronosGroup/Vulkan-Hpp/issues/2093.
+namespace vk { using AllocationCallbacks = ::ggml_vk::AllocationCallbacks; }

#include <vulkan/vulkan.hpp>
~~~


Changing the dispatcher also solves the build error. 
I notice that "laundering through a function call" is the default implementation for `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC != 1` but not for the dynamic case. Any downsides? I guess the function call is optimized away.

Comment (dg0yt) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: > With recent vulkan-hpp, it would be a one-line change, but for my installation I had to deal with [KhronosGroup/Vulkan-Hpp#2093](https://github.com/KhronosGroup/Vulkan-Hpp/issues/2093).

Scratch that :facepalm: I must have tested with a different patch. The macro is good, but the workaround isn't, and then there is `vk::` in `ggml-vulkan.cpp`.

This does work:
~~~diff
diff --git a/src/ggml-vulkan/ggml-vulkan.cpp b/src/ggml-vulkan/ggml-vulkan.cpp
index 5c941e72..a98f29e7 100644
--- a/src/ggml-vulkan/ggml-vulkan.cpp
+++ b/src/ggml-vulkan/ggml-vulkan.cpp
@@ -8,6 +8,9 @@
 // See https://github.com/KhronosGroup/Vulkan-Hpp?tab=readme-ov-file#extensions--per-device-function-pointers-
 #define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
 
+#define VULKAN_HPP_NAMESPACE ggml_vk
+namespace ggml_vk {}
+namespace vk { using namespace ::ggml_vk; }
 #include <vulkan/vulkan.hpp>
 
 
~~~

Comment (talregev) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: Can one of you make a PR and discuss it on there?

Comment (jeffbolznv) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: I prefer @Acly's fix. @Acly do you want to make a PR?

Comment (talregev) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: Thanks! please make a link to PR or just tag me there. 🙏🏻

Comment (Acly) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp:15]: Ok, PR is here: https://github.com/ggml-org/llama.cpp/pull/16224
