### PR TITLE
server : merge contiguous Responses input items into a single assistant message

### LINKED ISSUE #19513: Eval bug: Qwen3-Coder-Next generates prematurely EOS instead of tool call(/continued response)
### Name and Version

./llama-cli --version
ggml_vulkan: No devices found.
load_backend: loaded Vulkan backend from /app/libggml-vulkan.so
load_backend: loaded CPU backend from /app/libggml-cpu-zen4.so
version: 7993 (6d0ee8d4d)
built with GNU 15.2.0 for Linux x86_64

### Operating systems

Linux

### GGML backends

Vulkan

### Hardware

AMD Strix Halo, 128 GB

### Models

Qwen/Qwen3-Coder-Next-GGUF Q8_0
unsloth/Qwen3-Coder-Next-GGUF UD_Q5_K_XL, UD_Q8_K_XL

### Problem description & steps to reproduce

With codex on Qwen3-Coder-Next using the responses API I often see something like this after about 10-20 successful tool calls (EOS token not part of the output, it just directly follows the colon, hence the model generation must stop):

```
Let me check that other file:<|im_end|>
```

And the agent turn ends prematurely (because it encountered the EOS token and no tool call was generated). If I tell the model to continue, it does so for a while, but after 1 to 10 tool calls the same issue pops up (until the task is finally done; could take a lot of "please continue!" messages).

For messages where the tool call is not generated the colon token appears to always be this one (and is directly followed by the EOS token):

```
next token:    25 ':'
```

For messages where the tool call is generated a different colon token is used (directly before token 151657 '<tool_call>'):

```
next token:  1447 ':

'
```

I am using the recommended sampler settings (`--temp 1.0 --min-p 0.01 --top-p 0.95 --top-k 40`), unsloth's UD-Q8_K_XL (and also Qwen's Q8_0); I haven't noticed any other quality issues. The model is supposed to be very good at tool calls; as it was fine-tuned on all major formats, not just Qwen3-XML (see https://github.com/QwenLM/Qwen3-Coder/blob/main/qwen3_coder_next_tech_report.pdf?spm=a2ty_o06.30285417.0.0.3bdec921p0xaBK&file=qwen3_coder_next_tech_report.pdf Section 4.2.2 + Table 12). At least one other person has experienced the same behavior, while confirming that other harnesses seemingly could give better results.

(Note that I have seen successful/uninterrupted agent turns with 100+ tool calls, but they are rare!

**Reproducing the issue**
To potentially avoid installing Codex and deal with additional complexities, please find 
[codex_q3n_req_clean.json](https://github.com/user-attachments/files/25230635/codex_q3n_req_clean.json)
 below 40k tokens that failed 10 times in a row on llama.cpp (at least on autobranch, tested quants on Vulkan backend: Qwen/Qwen3-Coder-Next-GGUF Q8_0, unsloth/Qwen3-Coder-Next-GGUF UD-Q8_K_XL) in the sense that it will just generate a tool-call preamble/announcement, but then generates `':'(25)'<|im_end|>'(151645)`.

```
curl -X POST http://<llama.cpp-endpoint-host>/v1/responses -H "Content-Type: application/json" -d @./codex_q3n_req.json
```

I have tested that exact request against openrouter and it generated 5 times: ":\n\n" followed by the expected function_call output item. Note that the generated tool call preamble was slightly different each time (all ofc ending in that colon + 2 newlines), so I don't think that openrouter just cached a (lucky) response.

If I add the tool-call preamble as the model would generate it to the message array the tool call isn't generated (expected). However, if I change that preamble to end with two newlines after the colon, llama.cpp has no problem to generate the tool call.

Attached the request with the added role=assistant message ending on colon and two newlines. 
[codex_q3n_req_v2.json](https://github.com/user-attachments/files/25231462/codex_q3n_req_v2.json)

More info with others reporting that the issue also affects the master branch and the models Minimax-m2, (potentially?) GLM4.5-Air following the discussion here: https://github.com/ggml-org/llama.cpp/pull/18675#issuecomment-3879772240

cc: @pwilkin @joshvoigts @crashr @Mushoz

### First Bad Commit

_No response_

### Relevant log output

See attachments.

### PR DESCRIPTION
**Pull request by aldehir**
The Responses API endpoint constructs separate chat completion messages for each input item, except for reasoning. This causes problems with many chat templates that expect content, reasoning, and tool calls to appear in a single assistant message.

This PR merges contiguous assistant inputs into a single message before passing them to templates.

This also preserves reasoning content that isn't coupled with a tool call. A few models, such as Ministral 3, support interleaved reasoning within regular messages. Models that don't typically handle pruning the reasoning in their own templates.

ref: https://github.com/ggml-org/llama.cpp/pull/19765#issuecomment-3937342435
fixes #19513

cc @bfroemel

### CODE REVIEW

File: tools/server/server-common.cpp [hunk 1]
```diff
@@ -1210,35 +1215,43 @@ json convert_responses_to_chatcmpl(const json & response_body) {
                     });
                 }
 
-                item.erase("status");
-                item.erase("type");
-                item["content"] = chatcmpl_content;
-                chatcmpl_messages.push_back(item);
+                if (should_merge()) {
+                    auto & prev_msg = chatcmpl_messages.back();
+                    prev_msg["content"] = chatcmpl_content;
```
Comment (pwilkin) [inline tools/server/server-common.cpp]: `=` or `+=`? Any idea if we can have successive blocks of pure text? (or text/reasoning without tool calls, for that matter)

Comment (aldehir) [reply tools/server/server-common.cpp]: I can add it just in case, but I think it's unlikely to have multiple. `content` is a JSON array, constructed from an array of content objects from a single input item.

**Comment by bfroemel** [comment]
Tested with codex & responses API:
- gpt-oss-120b: noticed no change of behavior; prompt is rendered exactly the same for the case of an assistant `output_text` element preceding a `function_call` element in the input array
- qwen3-coder-next, ud_q4_k_xl: no premature end of agent turns; fixes #19513, prompt renders with tool preamble messages ending with two newlines and the desired merging:

For example:
```
<|im_start|>assistant\nNow let me look at how the `needs_follow_up` is determined:\n\n<tool_call>\n<function=exec_command>\n<parameter=cmd>\ngrep -n \"needs_follow_up\" /home/b/work/codex-new/codex-rs/core/src/codex.rs | head -30\n</parameter>\n<parameter=justification>\nFind needs_follow_up handling\n</parameter>\n</function>\n</tool_call><|im_end|>
```


Only a minor discrepancy remains with respect to openrouter; the generated two newlines of tool call preambles are not part of the `output_text` content element in the response, e.g., on openrouter you really get back something like that:

```
"output":[{"role":"assistant","type":"message","status":"incomplete","content":[{"type":"output_text","text":"Now let me look at `handle_output_item_done` which processes output items and determines if follow-up is needed:\n\n","annotations":[],"logprobs":[]}],"id":"msg_tmp_vg3tku6apmm"},{"type":"function_call","call_id":"call_f16c662f06654160a2f0af2f","name":"exec_command","arguments":"{\"cmd\": \"grep -n \\\"handle_output_item_done\\\" /home/b/work/codex-new/codex-rs/core/src/codex.rs\", \"justification\": \"Find handle_output_item_done\"}","id":"call_f16c662f06654160a2f0af2f","status":"completed"}]
```

Thanks for the diligence/pushing back!! Too soon to tell, but model quality might have improved/feels a bit better than the non-merging fix where we just not trimmed assistant content (/preserved the generated newlines).


btw: just noticed that parallel tool calls also seem to work (https://github.com/ggml-org/llama.cpp/pull/19765 ); very nice! :)

```
 curl http://<llama.cpp host>/v1/responses -d '{
    "model": "current",
    "instructions": "Issue multiple tool calls in a single turn if possible to reduce latency and improve user experience!",
    "input": [
      {
        "type": "message",
        "role": "user",
        "content": [ {"type": "input_text",
        "text": "what\'s the weather in Paris and London?"}]
      }
    ],
    "tools": [
      {
        "type": "function",
        "name": "get_weather",
        "description": "Returns the weather of location.",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string"
            }
          },
          "required": ["location"],
          "additionalProperties": false
        }
      }
    ],
    "stream": false,
    "parallel_tool_calls": true
  }
  '
{"completed_at":1771668166,"created_at":1771668166,"id":"resp_HJZ7SNdrqK12w6i4TUJIqHkWDoe0BlgO","model":"qwen3-coder-next","object":"response","output":[{"type":"function_call","status":"completed","arguments":"{\"location\":\"Paris\"}","call_id":"fc_6ZZb88GAiND0rfZflEv52G8yqAHESV48","name":"get_weather"},{"type":"function_call","status":"completed","arguments":"{\"location\":\"London\"}","call_id":"fc_uzAq3J1ikJcxlu1YG21AcELop1Z4JNGd","name":"get_weather"}],"status":"completed","usage":{"input_tokens":291,"output_tokens":44,"total_tokens":335}}
```

**Comment by Mushoz** [comment]
@bfroemel did you try to see if reasoning content is correctly working and being retained for non-gpt-oss models with interleaved thinking?

**Comment by bfroemel** [comment]
@Mushoz no; only tested what I currently use. I kind of settled with codex for now and didn't look a lot at other agents in the past couple of months.

Do we have other non-gpt-oss models that work (well) with a responses API client like codex? Do we even have other mature responses API coding agents by now? :)

~When looking at the code this PR might fix another subtle issue ( https://github.com/ggml-org/llama.cpp/pull/19773/changes#diff-562aee47dd99ff76cbd0c2a3e9b98d30cdf4d0111c0f09f345130e1f096d7ef4L1299 ) as it won't remove any reasoning content anymore. btw: regarding gpt-oss models, the template discards reasoning content only, if there is a final message (one without tool calls) generated in a assistant turn (otherwise the interleaved reasoning is kept).~ /edit: removal of that reasoning content wasn't relevant for gpt-oss, because the prompt ignores messages that only has reasoning content without tool calls. 

Overall, I believe the responsibility remains with the client to include reasoning content in the request, if required by the model, otherwise the client can leave it out. llama.cpp won't remove it (anymore with this PR now regardless whether the reasoning content is followed by tool calls or not).

Uhm and just to make sure: This PR introduces no changes for the chat completions API - there everything stays the same.

**Review by pwilkin — APPROVED** [review]

**Comment by aldehir** [comment]
GPT-OSS will render the same because their template format puts every element into a separate "message". It is a 1-to-1 mapping to Responses input items, which makes sense that OpenAI designed it that way.

The difference from OpenRouter should now be cosmetic, depending on if the client trims the content or not.

I appreciate you taking the time to test this out! Glad we got to the root of the issue.

**Review by ggerganov — APPROVED** [review]
