### PR TITLE
metal : refactor kernel loading code

### LINKED ISSUE #4672: Unite test "test-backend-ops" crashed on MacOS
I'm using MacOS 13.6 (Intel chip). Here is stack trace
Screenshot 2023-12-29 at 12 16 00 AM

### PR DESCRIPTION
**Pull request by ggerganov**
fix #4672 

ETA merge: after #4766 

- Simplify Metal defines for declaring / loading / freeing kernels
- Take into account GPU device family when loading kernels - skip unsupported
- Fix `MTLCompileOptions:setFastMathEnabled` - the struct wasn't being allocated before

These changes make the code build and run on Intel Macs. However, some ops (such as MUL_MAT, RMS_NORM, etc.) are marked as unsupported. The reason is that they rely on Apple7 feature set for simdgroup reduction (i.e. `simd_sum` and `simd_max`). A solution would be to implement an alternative set of kernels that does not rely on these calls and load it when the device does not support this feature set. Although it's not difficult to do, it would increase the MSL code significantly, so this is not high priority atm. Though it is something that people can achieve for their use-cases if necessary.

### CODE REVIEW

File: ggml-metal.m [hunk 1]
```diff
@@ -2696,7 +2714,9 @@ static bool ggml_backend_metal_graph_compute(ggml_backend_t backend, struct ggml
 }
 
 static bool ggml_backend_metal_supports_op(ggml_backend_t backend, const struct ggml_tensor * op) {
-    return ggml_metal_supports_op(op);
+    struct ggml_metal_context * metal_ctx = (struct ggml_metal_context *)backend->context;
+
+    return ggml_metal_supports_op(metal_ctx, op);
 
     UNUSED(backend);
```
Comment (slaren) [inline ggml-metal.m:2721]: This can be removed now, since `backend` is used.
