### PR TITLE
server : check that the prompt fits in the slot's context

### LINKED ISSUE #9978: Bug: llama-server crash with `--embeddings`
### What happened?

After starting with the following command, it will occasionally crash suddenly while running.

llama-server -m ./bge-large-zh-v1.5 --port 3358 -a emb@bge-large-zh-v1.5 -ngl 100 -c 8192 --samplers tempera
ture;top_p --embeddings -ub 8192 --pooling cls 

### Name and Version

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 4 CUDA devices:
  Device 0: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: yes
  Device 1: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: yes
  Device 2: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: yes
  Device 3: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: yes
version: 3945 (45f09764)
built with cc (Debian 10.2.1-6) 10.2.1 20210110 for x86_64-linux-gnu

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
[Thread debugging using libthread_db enabled]                                                                                         
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".                                                            
0x00007f210ada7787 in __GI___wait4 (pid=3074567, stat_loc=0x7fffc0b6d3a4, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:
27                                                                                                                                    
27      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.                                                                
#0  0x00007f210ada7787 in __GI___wait4 (pid=3074567, stat_loc=0x7fffc0b6d3a4, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait
4.c:27                                                                                                                                
27      in ../sysdeps/unix/sysv/linux/wait4.c                                                                                         
#1  0x00007f210b21b638 in ggml_abort () from /home/user/llama.cpp/build/ggml/src/libggml.so                                       
#2  0x00007f210b21f700 in ggml_compute_forward_get_rows () from //home/user/llama.cpp/build/ggml/src/libggml.so                    
#3  0x00007f210b24d0a2 in ggml_graph_compute_thread.isra () from /home/user/llama.cpp/build/ggml/src/libggml.so                   
#4  0x00007f210b250cf6 in ggml_graph_compute () from /home/user/llama.cpp/build/ggml/src/libggml.so                               
#5  0x00007f210b25caf3 in ggml_backend_cpu_graph_compute(ggml_backend*, ggml_cgraph*) () from /home/user/llama.cpp/build/ggml/src/
libggml.so                                                                                                                            
#6  0x00007f210b261d75 in ggml_backend_sched_graph_compute_async () from /home/user/llama.cpp/build/ggml/src/libggml.so           
#7  0x00007f2120eb15c2 in llama_decode () from /home/user/llama.cpp/build/src/libllama.so                                         
#8  0x000055776938aa04 in server_context::update_slots() ()                                                                           
#9  0x000055776936d7e1 in server_queue::start_loop() ()                                                                               
#10 0x0000557769324981 in main ()                                                                                                     
[Inferior 1 (process 2694414) detached]
```

### PR DESCRIPTION
**Pull request by ggerganov**
fix https://github.com/ggerganov/llama.cpp/issues/9978

In embedding and reranking mode, a prompt could fit in the batch but could exceed the slot's context size. This PR adds a check to handle such cases gracefully, instead of crashing.

## Testing

```bash
./llama-server \
    -m ./models/bge-large-zh-v1.5/ggml-model-f16.gguf \
    --port 8012 -a emb@bge-large-zh-v1.5 -ngl 100 \
    --embeddings -ub 8192 -b 8192 --pooling cls

curl \
    http://localhost:8012/v1/embeddings -H "Content-Type: application/json" \
    -H "Authorization: Bearer no-key" \
    -d '{"input": ["'"$(printf 'hello %.0s' $(seq 1 550))"'"], "encoding_format": "float"}'
```

```json
{
  "error": {
    "code": 500,
    "message": "input is larger than the max context size. skipping",
    "type": "server_error"
  }
}
```

### CODE REVIEW

File: examples/server/server.cpp [hunk 1]
```diff
@@ -2115,12 +2115,17 @@ struct server_context {
...
-                            // this prompt is too large to process - discard it
                             if (slot.n_prompt_tokens > n_ubatch) {
                                 slot.release();
                                 send_error(slot, "input is too large to process. increase the physical batch size", ERROR_TYPE_SERVER);
                                 continue;
                             }
+
+                            if (slot.n_prompt_tokens > slot.n_ctx) {
+                                slot.release();
+                                send_error(slot, "input is larger than the max context size. skipping", ERROR_TYPE_SERVER);
```
Comment (ngxson) [inline examples/server/server.cpp:2126]: I'd suggest changing some wordings to match the message when number of tokens is larger than `n_ubatch`

```suggestion
                                send_error(slot, "input is too large to process. increase the context size", ERROR_TYPE_SERVER);
```

Comment (ggerganov) [reply examples/server/server.cpp:2126]: Suggesting to increase the context size can lead to the same issue as the user experienced in #9978 due to setting a context size larger than what the model supports. So I'll leave the version without the suggestion.
