### PR TITLE
`server`: streaming of tool calls and thoughts when `--jinja` is on

### LINKED ISSUE #12107: Eval bug: llama-cpp-deepseek-r1.jinja template will miss the <think> tag
### Name and Version

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: Tesla T4, compute capability 7.5, VMM: yes
version: 4790 (438a8392)

### Operating systems

Linux

### GGML backends

CUDA

### Hardware

tesla t4

### Models

gguf deepseek-r1:14b, downloaded from ollama

### Problem description & steps to reproduce

```shell
/root/git/llama.cpp/build/bin/llama-server \
    -m /usr/share/ollama/.ollama/models/blobs/sha256-6e9f90f02bb3b39b59e81916e8cfce9deb45aeaeb9a54a5be4414486b907dc1e \
    -ngl 99 \
    --temp 0.6 \
    --no-webui \
    --host 0.0.0.0 \
    --port 20004 \
    --jinja \
    -fa \
    --chat-template-file /root/git/llama.cpp/models/templates/llama-cpp-deepseek-r1.jinja
```

this will use llama-cpp-deepseek-r1.jinja as the template, however, when using stream mode, the output content will miss the start `<think>` tag, but the `</think>` still exists, if remove the flag `--chat-template-file /root/git/llama.cpp/models/templates/llama-cpp-deepseek-r1.jinja`, problem gone

### First Bad Commit

_No response_

### Relevant log output

```shell
/root/git/llama.cpp/build/bin/llama-server \
    -m /usr/share/ollama/.ollama/models/blobs/sha256-6e9f90f02bb3b39b59e81916e8cfce9deb45aeaeb9a54a5be4414486b907dc1e \
    -ngl 99 \
    --temp 0.6 \
    --no-webui \
    --host 0.0.0.0 \
    --port 20004 \
    --jinja \
    -fa \
    --chat-template-file /root/git/llama.cpp/models/templates/llama-cpp-deepseek-r1.jinja

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: Tesla T4, compute capability 7.5, VMM: yes

system info: n_threads = 20, n_threads_batch = 20, total_threads = 20

system_info: n_threads = 20 (n_threads_batch = 20) / 20 | CUDA : ARCHS = 750 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | AVX512 = 1 | AVX512_VNNI = 1 | LLAMAFILE = 1 | OPENMP = 1 | AARCH64_REPACK = 1 |

Web UI is disabled
main: HTTP server is listening, hostname: 0.0.0.0, port: 20004, http threads: 19
main: loading model
srv    load_model: loading model '/usr/share/ollama/.ollama/models/blobs/sha256-6e9f90f02bb3b39b59e81916e8cfce9deb45aeaeb9a54a5be4414486b907dc1e'
llama_model_load_from_file_impl: using device CUDA0 (Tesla T4) - 14814 MiB free
llama_model_loader: loaded meta data with 26 key-value pairs and 579 tensors from /usr/share/ollama/.ollama/models/blobs/sha256-6e9f90f02bb3b39b59e81916e8cfce9deb45aeaeb9a54a5be4414486b907dc1e (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = DeepSeek R1 Distill Qwen 14B
llama_model_loader: - kv   3:                           general.basename str              = DeepSeek-R1-Distill-Qwen
llama_model_loader: - kv   4:                         general.size_label str              = 14B
llama_model_loader: - kv   5:                          qwen2.block_count u32              = 48
llama_model_loader: - kv   6:                       qwen2.context_length u32              = 131072
llama_model_loader: - kv   7:                     qwen2.embedding_length u32              = 5120
llama_model_loader: - kv   8:                  qwen2.feed_forward_length u32              = 13824
llama_model_loader: - kv   9:                 qwen2.attention.head_count u32              = 40
llama_model_loader: - kv  10:              qwen2.attention.head_count_kv u32              = 8
llama_model_loader: - kv  11:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  12:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  13:                          general.file_type u32              = 15
llama_model_loader: - kv  14:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  15:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  16:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  18:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  19:                tokenizer.ggml.bos_token_id u32              = 151646
llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 151643
llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  22:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  23:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {% if not add_generation_prompt is de...
llama_model_loader: - kv  25:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  241 tensors
llama_model_loader: - type q4_K:  289 tensors
llama_model_loader: - type q6_K:   49 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 8.37 GiB (4.87 BPW)
load: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
load: special tokens cache size = 22
load: token to piece cache size = 0.9310 MB
print_info: arch             = qwen2
print_info: vocab_only       = 0
print_info: n_ctx_train      = 131072
print_info: n_embd           = 5120
print_info: n_layer          = 48
print_info: n_head           = 40
print_info: n_head_kv        = 8
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 5
print_info: n_embd_k_gqa     = 1024
print_info: n_embd_v_gqa     = 1024
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-05
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: n_ff             = 13824
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = 0
print_info: rope type        = 2
print_info: rope scaling     = linear
print_info: freq_base_train  = 1000000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 131072
print_info: rope_finetuned   = unknown
print_info: ssm_d_conv       = 0
print_info: ssm_d_inner      = 0
print_info: ssm_d_state      = 0
print_info: ssm_dt_rank      = 0
print_info: ssm_dt_b_c_rms   = 0
print_info: model type       = 14B
print_info: model params     = 14.77 B
print_info: general.name     = DeepSeek R1 Distill Qwen 14B
print_info: vocab type       = BPE
print_info: n_vocab          = 152064
print_info: n_merges         = 151387
print_info: BOS token        = 151646 '<｜begin▁of▁sentence｜>'
print_info: EOS token        = 151643 '<｜end▁of▁sentence｜>'
print_info: EOT token        = 151643 '<｜end▁of▁sentence｜>'
print_info: PAD token        = 151643 '<｜end▁of▁sentence｜>'
print_info: LF token         = 198 'Ċ'
print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
print_info: FIM MID token    = 151660 '<|fim_middle|>'
print_info: FIM PAD token    = 151662 '<|fim_pad|>'
print_info: FIM REP token    = 151663 '<|repo_name|>'
print_info: FIM SEP token    = 151664 '<|file_sep|>'
print_info: EOG token        = 151643 '<｜end▁of▁sentence｜>'
print_info: EOG token        = 151662 '<|fim_pad|>'
print_info: EOG token        = 151663 '<|repo_name|>'
print_info: EOG token        = 151664 '<|file_sep|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: offloading 48 repeating layers to GPU
load_tensors: offloading output layer to GPU
load_tensors: offloaded 49/49 layers to GPU
load_tensors:   CPU_Mapped model buffer size =   417.66 MiB
load_tensors:        CUDA0 model buffer size =  8148.38 MiB
...........................................................................................
llama_init_from_model: n_seq_max     = 1
llama_init_from_model: n_ctx         = 4096
llama_init_from_model: n_ctx_per_seq = 4096
llama_init_from_model: n_batch       = 2048
llama_init_from_model: n_ubatch      = 512
llama_init_from_model: flash_attn    = 1
llama_init_from_model: freq_base     = 1000000.0
llama_init_from_model: freq_scale    = 1
llama_init_from_model: n_ctx_per_seq (4096) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
llama_kv_cache_init: kv_size = 4096, offload = 1, type_k = 'f16', type_v = 'f16', n_layer = 48, can_shift = 1
llama_kv_cache_init:      CUDA0 KV buffer size =   768.00 MiB
llama_init_from_model: KV self size  =  768.00 MiB, K (f16):  384.00 MiB, V (f16):  384.00 MiB
llama_init_from_model:  CUDA_Host  output buffer size =     0.58 MiB
llama_init_from_model:      CUDA0 compute buffer size =   307.00 MiB
llama_init_from_model:  CUDA_Host compute buffer size =    18.01 MiB
llama_init_from_model: graph nodes  = 1495
llama_init_from_model: graph splits = 2
common_init_from_params: setting dry_penalty_last_n to ctx_size = 4096
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
srv          init: initializing slots, n_slots = 1
slot         init: id  0 | task -1 | new slot n_ctx_slot = 4096
main: model loaded
main: chat template, chat_template: {%- if not add_generation_prompt is defined -%}
    {%- set add_generation_prompt = false -%}
{%- endif -%}
{%- set ns = namespace(is_first=false, is_tool_outputs=false, is_output_first=true, system_prompt='') -%}
{%- for message in messages -%}
    {%- if message['role'] == 'system' -%}
        {%- set ns.system_prompt = message['content'] -%}
    {%- endif -%}
{%- endfor -%}
{{bos_token}}
{%- if tools %}
You can call any of the following function tools to satisfy the user's requests: {{tools | map(attribute='function') | tojson(indent=2)}}

Example function tool call syntax:

<｜tool▁calls▁begin｜><｜tool▁call▁begin｜>function<｜tool▁sep｜>example_function_name

{
  "arg1": "some_value"
  ...
}

<｜tool▁call▁end｜><｜tool▁calls▁end｜>

{% endif -%}
{{ns.system_prompt}}
{%- macro flush_tool_outputs() -%}
    {%- if ns.is_tool_outputs -%}
        {{- '<｜tool▁outputs▁end｜><｜end▁of▁sentence｜>' -}}
        {%- set ns.is_tool_outputs = false -%}
    {%- endif -%}
{%- endmacro -%}
{{- flush_tool_outputs() -}}
{%- for message in messages -%}
    {%- if message['role'] != 'tool' -%}
        {{- flush_tool_outputs() -}}
    {%- endif -%}
    {%- if message['role'] == 'user' -%}
        {{- '<｜User｜>' + message['content'] + '<｜end▁of▁sentence｜>' -}}
    {%- endif -%}
    {%- if message['role'] == 'assistant' and message['content'] is none -%}
        {{- '<｜Assistant｜><｜tool▁calls▁begin｜>' -}}
        {%- set ns.is_first = true -%}
        {%- for tc in message['tool_calls'] -%}
            {%- if ns.is_first -%}
                {%- set ns.is_first = false -%}
            {%- else -%}
                {{- '\n' -}}
            {%- endif -%}
            {%- set tool_name = tc['function']['name'] -%}
            {%- set tool_args = tc['function']['arguments'] -%}
            {{- '<｜tool▁call▁begin｜>' + tc['type'] + '<｜tool▁sep｜>' + tool_name + '\n' + '' + '\n' + tool_args + '\n' + '' + '<｜tool▁call▁end｜>' -}}
        {%- endfor -%}
        {{- '<｜tool▁calls▁end｜><｜end▁of▁sentence｜>' -}}
    {%- endif -%}
    {%- if message['role'] == 'assistant' and message['content'] is  not none -%}
        {{- flush_tool_outputs() -}}
        {%- set content = message['content'] -%}
        {%- if '</think>' in content -%}
            {%- set content = content.split('</think>')[-1] -%}
        {%- endif -%}
        {{- '<｜Assistant｜>' + content + '<｜end▁of▁sentence｜>' -}}
    {%- endif -%}
    {%- if message['role'] == 'tool' -%}
        {%- set ns.is_tool_outputs = true -%}
        {%- if ns.is_output_first -%}
            {{- '<｜tool▁outputs▁begin｜>' -}}
            {%- set ns.is_output_first = false -%}
        {%- endif -%}
        {{- '\n<｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁output▁end｜>' -}}
    {%- endif -%}
{%- endfor -%}
{{- flush_tool_outputs() -}}
{%- if add_generation_prompt and not ns.is_tool_outputs -%}
    {{- '<｜Assistant｜><think>\n' -}}
{%- endif -%}, example_format: 'You are a helpful assistant<｜User｜>Hello<｜end▁of▁sentence｜><｜Assistant｜>Hi there<｜end▁of▁sentence｜><｜User｜>How are you?<｜end▁of▁sentence｜><｜Assistant｜><think>
'
main: server is listening on http://0.0.0.0:20004 - starting the main loop
srv  update_slots: all slots are idle
srv  params_from_: Chat format: DeepSeek R1 (extract reasoning)
slot launch_slot_: id  0 | task 0 | processing task
slot update_slots: id  0 | task 0 | new prompt, n_ctx_slot = 4096, n_keep = 0, n_prompt_tokens = 12
slot update_slots: id  0 | task 0 | kv cache rm [0, end)
slot update_slots: id  0 | task 0 | prompt processing progress, n_past = 12, n_tokens = 12, progress = 1.000000
slot update_slots: id  0 | task 0 | prompt done, n_past = 12, n_tokens = 12
slot      release: id  0 | task 0 | stop processing: n_past = 84, truncated = 0
slot print_timing: id  0 | task 0 |
prompt eval time =     128.41 ms /    12 tokens (   10.70 ms per token,    93.45 tokens per second)
       eval time =    3607.62 ms /    73 tokens (   49.42 ms per token,    20.23 tokens per second)
      total time =    3736.03 ms /    85 tokens
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /v1/chat/completions 10.30.200.19 200

use http POST http://gpu-dev:20004/v1/chat/completions \
    model=deepseek-r1-14b-cpp \
    messages:='[{"role": "user", "content": "非常详细地介绍一下你自己?"}]' \
    stream:=true

to send request, and get 

HTTP/1.1 200 OK
Access-Control-Allow-Origin:
Content-Type: text/event-stream
Keep-Alive: timeout=5, max=100
Server: llama.cpp
Transfer-Encoding: chunked

data: {
    "choices": [
        {
            "delta": {
                "content": "您好"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "！"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "我是"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "由"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "中国的"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "深度"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "求"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "索"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "（"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "Deep"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "Seek"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "）"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "公司"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734646,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "开发"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "的"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "智能"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "助手"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "Deep"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "Seek"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "-R"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "1"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "。"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "如"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "您"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "有任何"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "任何"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "问题"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "，"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "我会"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "尽"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "我"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "所能"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "为您提供"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734647,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "帮助"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "。\n"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "</think>"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "\n\n"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "您好"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "！"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "我是"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "由"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "中国的"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "深度"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "求"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "索"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "（"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "Deep"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "Seek"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "）"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "公司"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "开发"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "的"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "智能"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734648,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "助手"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "Deep"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "Seek"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "-R"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "1"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "。"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "如"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "您"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "有任何"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "任何"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "问题"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "，"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "我会"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "尽"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "我"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "所能"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "为您提供"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "帮助"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": "。"
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {
                "content": ""
            },
            "finish_reason": null,
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392"
}

data: {
    "choices": [
        {
            "delta": {},
            "finish_reason": "stop",
            "index": 0
        }
    ],
    "created": 1740734649,
    "id": "chatcmpl-huCXGDWAI250H1Sid6SfwT2F6QcrjN8p",
    "model": "deepseek-r1-14b-cpp",
    "object": "chat.completion.chunk",
    "system_fingerprint": "b4790-438a8392",
    "timings": {
        "predicted_ms": 3607.618,
        "predicted_n": 73,
        "predicted_per_second": 20.234958357564466,
        "predicted_per_token_ms": 49.41942465753424,
        "prompt_ms": 128.408,
        "prompt_n": 12,
        "prompt_per_second": 93.45212136315494,
        "prompt_per_token_ms": 10.700666666666665
    },
    "usage": {
        "completion_tokens": 73,
        "prompt_tokens": 12,
        "total_tokens": 85
    }
}

data: [DONE]
```

### PR DESCRIPTION
**Pull request by ochafik**
- Support streaming of tool calls in OpenAI format
- Improve handling of thinking model (DeepSeek R1 Distills, QwQ, Command R7B):
  - Stream `<think>` reasoning content inside the content (same output for all thinking models when using the default `--reasoning-content deepseek`, even for those not using the `<think>` syntax like Command R7B), and even if the `<think>` tag was added at the end of the prompt by the template (as for DeepSeek R1 & QwQ).
  - Avoid spurious lazy (tool call) grammar triggers from "thoughts about tool calls" (only trigger after closing any unclosed thoughts)
- Improves Functionary v3.2 support (allow raw python code, preferred by models over `{"code": "json-encoded code"}` for multiline programs)
- Support truncated outputs incl. reasoning_content & tool_calls (returns salvageable fields when finish_reason = length)

This fixes #12107, #10920, #11861

Follow up to https://github.com/ggml-org/llama.cpp/pull/9639

Pending follow ups / bugfixes:

- https://github.com/ggml-org/llama.cpp/pull/13785
- https://github.com/ggml-org/llama.cpp/pull/13786: fixes lots of the diffs crashes, especially when thinking is involved or when there's a mix of content & tool calls (or partial matches of tool call starts)
- https://github.com/ggml-org/llama.cpp/pull/13800: fixes delta format (return `tool_call.function.name` as deltas, put `id` at right place, output `type`)

## How to test / use

- <details><summary>Get and build this PR's branch</summary>

  ```bash
  git clone https://github.com/ggml-org/llama.cpp
  cd llama.cpp
  git remote add ochafik https://github.com/ochafik/llama.cpp
  git fetch ochafik
  git checkout ochafik/tool-diffs
  cmake -B build -DLLAMA_CURL=1 # -DGGML_CUDA=1 ...
  cmake --build build -t llama-server --parallel --config Release
  alias llama-server=./build/bin/llama-server
  ```

- Run `llama-server` w/ any model (see more details in the [tool calling docs](https://github.com/ggml-org/llama.cpp/blob/master/docs/function-calling.md); note that some GGUFs require a chat template override!):

  ```bash
  # Thoughts of Command R7B / DeepSeek R1 / QwQ will be streamed in the content inside <think> tags
  llama-server --jinja -fa -hf bartowski/Qwen_QwQ-32B-GGUF
  
  # Models w/ generic tool call support now return clean interrupted output when hitting token limit
  llama-server --jinja -fa -hf bartowski/microsoft_Phi-4-mini-instruct-GGUF

  ```

- Call the chat completions endpoint in streamed mode with any OpenAI-compatible library, or plain curl:

  ```bash
  curl http://localhost:8080/v1/chat/completions -d '{
    "model": "gpt-3.5-turbo",
    "tools": [
      {
        "type": "function",
        "function": {
          "name": "python",
          "description": "Runs code in an ipython interpreter and returns the result of the execution after 60 seconds.",
          "parameters": {
            "type": "object",
            "properties": {
              "code": {
                "type": "string",
                "description": "The code to run in the ipython interpreter."
              }
            },
            "required": ["code"]
          }
        }
      }
    ],
    "messages": [
      {
        "role": "user",
        "content": "Print a hello world message with python."
      }
    ],
    "stream": true
  }'
  ```

- You can also open http://localhost:8080/ to see thoughts being streamed back properly even for models which template add an opening `<think>` tag to the end of the prompt (QwQ, now DeepSeek R1 too although most GGUFs have their initial version) and models like Cohere Command R7B that natively use a different thinking tags syntax (now normalized, since `—reasoning-format deepseek` is the default)

## Context

Supporting OpenAI's streaming delta format was a bit tricky, as it returns chunks of JSON-encoded arguments for each function call, but that's not necessarily what models give us.

While tool calls are returned in a standard format, each w/ a function name, tool call id and JSON encoded arguments, model outputs vary greatly in their syntax. That syntax mostly uses JSON for arguments but not always.

Function calls and their arguments can be at various levels:
- JSON array of tool calls (e.g. Mistral Nemo: `[TOOL_CALLS][{"name": "special_function", "arguments": {"arg1": 1}, "id": "123456789"}]`)
- Standalone JSON tool call (e.g. Hermes syntax: `<tool_call>{"name": "special_function", "arguments": {"arg1": 1}}</tool_call>`; note that some models use other keys here, e.g. `tool_name`, `parameters`, and may have the tool call id too)
- JSON arguments object w/ name in some prefix (e.g. Deepseek: `<｜tool▁calls▁begin｜><｜tool▁call▁begin｜>function<｜tool▁sep｜>special_function\n```json\n{"arg1": 1}\n```<｜tool▁call▁end｜><｜tool▁calls▁end｜>`, or functionary v3.2: `special_function\n{"arg1": 1}`)
- Nested JSON for the generic mode `{"tool_call": {"name": "special_function", "arguments": {"arg1": 1}}}` (or inside `tool_calls` array if `parallel_tool_calls` is on)
- No JSON / raw code string for `python` tool call, with two variants:
  - Unconstrained verbatim code: `<|python_tag|>multiline python code here` (functionary v3.1), `python\nmultiline python code here` (functionary v3.2; w/ prefix `>>>` if after textual response)
  - Constrained pythonish syntax for "builtin tools" (Llama 3.x, **quite widespread**): `<|python_tag|>python.call(code="multiline\npython\ncode\nhere")`

Side note about raw python code: `<|python_tag>foo.call(bar="baz")` in Llama 3.x style will return `"tool_calls": [{"name": "foo", "arguments": "{\"bar\": \"baz\"}"}]`, while the same output from Functionary would be parsed as `"tool_calls": [{"name": "python", "arguments": "{\"code\": \"foo.call(bar=\\\"baz\\\")\"}"}]`.

Now when streaming, we may have sampled only a prefix of the aforementioned output, and want ideally to parse what can be parsed out of it, and send a JSON-encoded arguments object that is cut at a safe place, so that the sum of all the deltas adds up to the full arguments JSON string.

(A primary use case for partial JSON arguments streaming is streaming large multiline diff tool arguments in tools such as RooCode / Cline / Cursor)

The cleanest option would have been to create a unified parser / state machine that can be drip-fed tokens, and preserve its state in the server slot. But I figured the complexity was too high for now (see notes on speeding up below), and instead I've implemented something definitely inefficient but relatively simple (chat.cpp it still the same size): for every token coming in, I try and parse the entire output so far, with partial regex & json parsing support, which allows recovering cleanly cut-off JSON-encoded function arguments (regardless of the original format of said arguments). I then compare the full `common_chat_msg` against the last one we sent back, and compute OpenAI-compatible deltas out of this.

## Location, location, location 🏡 

Note that the output of the model may be truncated (max token output length reached or streaming in progress), and that may fall inside an expected literal (e.g. `<think>` isn't a single token on QwQ-32B), inside a regex (used for some matchers), or inside some JSON.

But more interesting is *where* it happens, esp. for partial JSON:
- If it happens inside an arguments object or a contents string (for generic mode), we should return it partial / truncated (and json-dumped in the case of the arguments), and diffed from the last parsed value for the streamed case
- If it happens inside the *wrapper* of the arguments, then it depends. We don't want to get a half-function name, but as soon as we have a complete function name we can send a diff. So we try and heal the JSON (we identify which json paths can be partially healed - because they're inside the arguments, and which ones must be dropped), and only populate a tool call if we have at least a name). Likewise, if there is an array of function calls with the first complete, and the next partial, we want to make sure the client can start calling the first function.

[tests/test-chat-parser.cpp](https://github.com/ochafik/llama.cpp/blob/tool-diffs/tests/test-chat-parser.cpp#L94) should make this a bit clearer, and I'm in the process of adding partial examples w/ the actual formats in [tests/test-chat.cpp](https://github.com/ochafik/llama.cpp/blob/tool-diffs/tests/test-chat.cpp) (look out for `/* is_partial= */ true`)

<details><summary>See examples of streamed tool call deltas</summary>

```shell
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "tools": [
        {
        "type":"function",
        "function":{
            "name":"python",
            "description":"Runs code in an ipython interpreter and returns the result of the execution after 60 seconds.",
            "parameters":{
            "type":"object",
            "properties":{
                "code":{
                "type":"string",
                "description":"The code to run in the ipython interpreter."
                }
            },
            "required":["code"]
            }
        }
        }
    ],
    "messages": [
        {
        "role": "user",
        "content": "Print a hello world message with python."
        }
    ], "stream": true
}'
```

```
data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"role":"assistant","content":null,"tool_calls":[{"index":0,"id":"call_aqwOReHDKPnqiF7NbRxzDTY1","type":"function","function":{"name":"python","arguments":""}}],"refusal":null},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"{\""}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"code"}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"\":\""}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"print"}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"('"}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"Hello"}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":","}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":" World"}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"!"}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"')"}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"function":{"arguments":"\"}"}}]},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BArAOzrqdSYW1UJvOwWb9nXAy1qo4","object":"chat.completion.chunk","created":1741927352,"model":"gpt-3.5-turbo-0125","service_tier":"default","system_fingerprint":null,"choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"tool_calls"}]}

data: [DONE]
```

</details>

### Partial parsing utils

I added a `common_chat_msg_parser` utility with syntax reminiscent of @ngxson's suggestions in https://github.com/ggml-org/llama.cpp/pull/11607#issuecomment-2656147148, but relying on control flow to allow more flexibility:

- Supports partial regex parsing
  - Since the STL still doesn't have partial matching support ([unlike Boost](https://beta.boost.org/doc/libs/1_59_0/libs/regex/doc/html/boost_regex/partial_matches.html)), I had to implement my own in `common_regex` (see `common/regex-partial.cpp`).
  - The trick = transform the original regex to a regex that matches in reverse from the end of the string (e.g. `/abc/` gives `/((?:(?:c)?b)?a)[\s\S]*/`, with a single capturing group which end indicates - in reverse - where the partial match started)
- Supports partial JSON parsing:
  - Used `nlohmann/json`'s [SAX interface](https://json.nlohmann.me/features/parsing/sax_interface/) to build location awareness / stack to know how to heal a JSON that fails to parse
  - Healing the JSON w/ a healing marker that can then be found when visiting the resulting JSON (to remove things we don't want to heal - e.g. function name - and cut any JSON encoded result at the "right" place, which must be somewhere inside function arguments: `consume_json` accepts a list of json paths under which to expect arguments objects; could be from the root = empty path if the entire json object is an arguments object)
- Supports control flow w/ `try_*` parsing methods. This makes the code relatively easy to read and debug. No exotic syntax (apart from `optional`s, they really help here imho), which should make it easier to convert to coroutines when we wanna make it all incremental.
- Supports full or partial parsing w/ same code (throws partial exceptions to interrupt the control flow without making parsing code more complex)

This allows parsing of partial model outputs, whether in streaming mode or when reaching the token limit (currently, tool calls give ugly unparsed outputs when `finish_reason` != `tool_call`).

### To think or not to think... what is the prompt?

I've also introduced `common_chat_syntax` which wraps `common_reasoning_format`, `common_chat_format` together with:
- `thinking_forced_open`: whether the prompt was detected to end w/ a (model-specific) `<think>` tag to force thinking mode
- `reasoning_in_content`: whether the thinking tags should be left in the content, which is currently the case in streaming mode as the DeepSeek API does.

This allows streaming back a standard `<think>...` syntax even for models that use a different set of tags (e.g. Command R7B). And of course, `--reasoning-format none` is still allowed to get the raw output.

Note: Ideally, we'd stream the thoughts as a `reasoning_content` delta (now trivial to implement), but for now we are just aiming for compatibility w/ DeepSeek's API (if `--reasoning-format deepseek`, which is the default).

### Triggering thoughts 😓

I noticed DeepSeek R1 Qwen 7B sometimes obsesses over the tool call syntax and "thinks" about how it's gonna call it... which triggers the lazy grammars for said calls before the thoughts are closed.

To address this, I made it possible for `common_chat_templates_apply` to create trigger regexes that match on the entire output (this was already the case in the sampler). `COMMON_GRAMMAR_TRIGGER_TYPE_PATTERN_FULL` (renamed from `_START`) is now expected to have a single capturing group from the start of which the grammar sampler will be activated.

### Functionary v3.2 w/ raw python

Ask `bartowski/functionary-small-v3.2-GGUF:Q4_K_M` to write a hello world in Python and it outputs `python\n{"code": "print('hey')"}`.

But ask it to print a hello world in python w/ matplotlib, and it uses its raw multiline python syntax `python\nprint('hey')\n# many other lines`. This is now supported.

## TODOs

- [x] Fix tool call id attribution logic (disabled for now) from https://github.com/ggml-org/llama.cpp/pull/12292
- [x] Might need one last diff in the final response after a stream, say, to close any raw python code
- [x] Decide what to do about `logprobs` for tools mode (right now, forbidden; we don't return diffs for every token, for instance if a function name is in multiple tokens we don't want to send its name in chunks)
  - Edit: OpenAI returns null logpropbs in tool call mode. Just need to ensure normal mode doesn't regress (test failing atm)
- [x] Fix Mistral Nemo crash (`llama-server --jinja -fa -hf bartowski/Mistral-Nemo-Instruct-2407-GGUF:Q6_K_L`)
- [x] Send partial regex (`common_regex`) as separate PR: https://github.com/ggml-org/llama.cpp/pull/12808
- [ ] Send partial JSON (`common_json`) as separate PR(?) or fold into `chat-parser.cpp`
- [ ] Command R7B's non-tool-calling template (they have 3 templates) forces `<|START_RESPONSE|>` at the end of the prompt. Output will contain an `<|END_RESPONSE|>` that needs handling (would fit nicely in new `common_chat_syntax` struct). Maybe combine w/ forced/disabled thinking modes as a follow up PR
- [ ] Add some docs
- [ ] Add more tests
- [ ] Run `scripts/tool_bench.sh` to compare against `master` (+ compare timings)

Future follow ups:

- To make this faster, I suggest two options:
  - Wait for the project to switch to C++20 & turn all the parser functions into resumable coroutines (feed them tokens and persist their state in the slot)
  - Only compute and send deltas after N milliseconds

cc/ @jpohhhh

### CODE REVIEW

**Comment by ngxson** [comment]
> Supporting OpenAI's streaming delta format was a bit tricky, as it returns chunks of JSON-encoded arguments for each function call, but that's not necessarily what models give us.

IMO we don't necessary have to emulate this in a very accurate manner. From the perspective of an app developer who use the API, it's obvious that streaming the function argument does not make sense since the client cannot decode it anyway. Often than not, you may find a code pattern in the client app which simply aggregate the chunks into a complete JSON, then decode it.

The `stream: true` used in OAI-compat API is mostly used for receiving the **answer** in real time. For example, if I ask the LLM "what is the weather like?", I don't care if the "get_weather" call is streamed or not, but what I do care is the final response "the weather is ..." can be streamed.

With this in mind, you could completely skip processing half-finished JSON to make it more simple.

**Comment by ochafik** [comment]
> The `stream: true` used in OAI-compat API is mostly used for receiving the **answer** in real time. For example, if I ask the LLM "what is the weather like?", I don't care if the "get_weather" call is streamed or not, but what I do care is the final response "the weather is ..." can be streamed.

@ngxson Agree it would have been simpler, but a prime use case I have in mind is to stream long arguments, e.g. file diffs in IDE plugins. In https://github.com/cline/cline/pull/1946 I disabled the streaming (and recomposed the output to what cline expected), but I have full working TS code to create streaming parsers of partial json and of openai chunked responses, which I hope to contribute to llama.vscode and maybe RooCode (since Cline is a no).

**Comment by ngxson** [comment]
> but a prime use case I have in mind is to stream long arguments, e.g. file diffs in IDE plugins

Ok interesting use case, I didn't know about this before.

In this case, maybe we can only support streaming for models that can output JSON natively? Personally I still a bit doubt about depending on `nlohmann::json` SAX interface. This low-level parsing functionality can be powerful, but at the same time can be quite complicated for maintenance.

Also, I still don't fully understand the case where we need to decode partial JSON. Could you give an example? (i.e. which model and which chat template?)

**Comment by ngxson** [comment]
Also I'm thinking, would it be more simple to firstly support streaming on non-function-call responses first (ref my first comment), then start to support chunked `arguments` in a follow up PR? This way it's easier to review and also give you more time to experiment with that.

**Comment by ochafik** [comment]
> In this case, maybe we can only support streaming for models that can output JSON natively?

@ngxson We'd still need some incremental json parsing support to know where the json ends, which was reason why I was using the SAX stuff until now.

Otherwise, I'd rather avoid coverage mismatch between streamed and non-streamed.

> Personally I still a bit doubt about depending on `nlohmann::json` SAX interface. This low-level parsing functionality can be powerful, but at the same time can be quite complicated for maintenance.

Agree. For now it's just about okay, but I think having our own partial parser might just be less code overall / easier to maintain. This was me trying not to write a JSON parser by hand (which I did in the TS code I mentioned). Happy to revisit as a follow up.

> Also, I still don't fully understand the case where we need to decode partial JSON. Could you give an example? (i.e. which model and which chat template?)

First off, the JSON we're trying to parse can be at various levels:
- Inside an array of tool calls (e.g. Mistral Nemo: `[TOOL_CALLS][{"name": "special_function", "arguments": {"arg1": 1}, "id": "123456789"}]`)
- As a standalone tool call (e.g. Hermes syntax: `<tool_call>{"name": "special_function", "arguments": {"arg1": 1}}</tool_call>`; note that some models use other keys here, e.g. `tool_name`, `parameters`, and may have the tool call id too)
- As just the arguments object (e.g. Deepseek: `<｜tool▁calls▁begin｜><｜tool▁call▁begin｜>function<｜tool▁sep｜>special_function\n```json\n{"arg1": 1}\n```<｜tool▁call▁end｜><｜tool▁calls▁end｜>`, or functionary v3.2: `special_function\n{"arg1": 1}`)
- Deep inside more JSON for the generic mode `{"tool_call": {"name": "special_function", "arguments": {"arg1": 1}}}` (or inside `tool_calls` array if `parallel_tool_calls` is on)
- And "implied" / no JSON for Python code, with two variants:
  - Unconstrained verbatim code: `<|python_tag|>multiline python code here` (functionary v3.1), `python\nmultiline python code here` (functionary v3.2; w/ prefix `>>>` if after textual response)
  - Constrained pythonish syntax for "builtin tools" (Llama 3.x, **quite widespread**): `<|python_tag|>python.call(code="multiline\npython\ncode\nhere")`

As for *partial* JSON, it can happen because we reached the token limit (newly supported!), or because we're in streaming mode.

But more interesting is *where* it happens:
- If it happens inside an arguments object, we should return it partial
- If it happens inside the *wrapper* of the arguments, then it depends. We don't want to get a half-function name, but as soon as we have a complete function name we can send a diff. So we try and heal the JSON (we identify which json paths can be partially healed - because they're inside the arguments, and which ones must be dropped), and only populate a tool call if we have at least a name)

[tests/test-chat-parser.cpp](https://github.com/ochafik/llama.cpp/blob/tool-diffs/tests/test-chat-parser.cpp#L94) should make this a bit clearer, and I'm in the process of adding partial examples w/ the actual formats in [tests/test-chat.cpp](https://github.com/ochafik/llama.cpp/blob/tool-diffs/tests/test-chat.cpp) (look out for `/* is_partial= */ true`)

**Comment by ochafik** [comment]
> Also I'm thinking, would it be more simple to firstly support streaming on non-function-call responses first (ref my first comment), then start to support chunked `arguments` in a follow up PR? This way it's easier to review and also give you more time to experiment with that.

Re/ reviewability, I'm thinking of sending the generic parser + partial json + regex support and their tests in 1-3 separate PRs.

Server tests are now all fixed, main remaining tasks (besides more tests) are logprobs + tool call id regressions.

**Comment by bandoti** [comment]
Please forgive my ignorance on the OAI streaming protocol, but would it be something to consider waiting until the complete toolcall is collected and then send the whole thing back? The tool-calls will essential be re-assembled on the client side at the expense of a lot of JSON verbosity! And, outside of debug output this will not be presentable to users until the whole thing arrives anyhow. 😉

I like @ngxson idea about the state machine as this is something I was considering in the llama-cli toolcalls, as it would be necessary for cleaner output. In an ideal world, there is a simple stack which pushes tokens (perhaps a buffer >= 1) for nested begin/end delimiters and "all that is needed" (in theory) is basic token comparison. If the tool-call is opened, then wait until the rest arrives (or some timeout condition elapses).

**Comment by ngxson** [comment]
> Please forgive my ignorance on the OAI streaming protocol, but would it be something to consider waiting until the complete toolcall is collected and then send the whole thing back?

It is still needed for some use case, see https://github.com/ggml-org/llama.cpp/pull/12379#issuecomment-2726727434

JSON verbosity is not a big problem for now IMO, we can always enforce a minimum chunk length in the future, to reduce the number of SSE events to be emitted.

Btw @ochafik I would like to help on this if needed. At least the case for streaming response (without streaming toolcall) is very necessary for now. And I think @bandoti ask for that because at this point, this is the only blocking point to bring MCP into llama.cpp server Web UI.

**Comment by antcodd** [comment]
Are there client compatibility issues with streaming partial tool call responses? If so maybe streaming of the tool call response itself should be optional (e.g. default state controllable by argument, and a json parameter)? 

Tool calling is supported in a lot more places than open source IDE plugins (personally I want to use it in Home Assistant and Skyrim mods, currently I'm using prompt injecting alternatives because of the streaming issue).

**Comment by llowrey** [comment]
I'm getting a hard crash when sending a request that has a tool response as the last message.

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid diff: '{"name":"servethehome_homepage' not found at start of '{"name":'
```

The last message was:
```
{
  "role":"tool",
  "tool_call_id":"AJHxgbA2l5We2057NiDORsHRtf6Vcqzt",
  "content":"Navigated to https://servethehome.com/"
}
```

The model is `google_gemma-3-12b-it-Q6_K.gguf`

I'm trying to use the puppeteer mcp server. Is there a way to get more detail on this error?

**Comment by ochafik** [comment]
> I'm getting a hard crash when sending a request that has a tool response as the last message.
> 
> ```
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Invalid diff: '{"name":"servethehome_homepage' not found at start of '{"name":'
> ```

@llowrey Thanks a lot for trying this out! If you could share the llama-server output w/ `--verbose` flag, that would help (in particular, the last couple of `Parsing input with format: ` lines, and if possible the `request: {...` log to provide a full repro case)

> The model is `google_gemma-3-12b-it-Q6_K.gguf`

Haven't tried gemma3 yet, will definitely spend time on it over the weekend! Have you tried any other model by any chance?

> Btw @ochafik I would like to help on this if needed

@ngxson Hoping to spend this raining weekend on this, hope to send you a few parts to review if you have the time :-) (I'd also highly welcome some feedback on how I've plugged things into the slot + partial / final response logic so far)

> Are there client compatibility issues with streaming partial tool call responses? If so maybe streaming of the tool call response itself should be optional (e.g. default state controllable by argument, and a json parameter)?

@antcodd Just as with OpenAI's chat completion API, streaming is enabled through the `"stream": true` parameter and aims to be 100% compatible with OAI's format.

> And, outside of debug output this will not be presentable to users until the whole thing arrives anyhow. 😉

@bandoti Aside from the streamed thoughts (already presentable as they come), there's definitely ways to use the tool calls as they trickle back (either w/ parallel tool calls once you have some complete calls and are still receiving others, or w/ a single tool call when an argument is very long, e.g. file diffs that can be partially applied on the fly as in cline, see https://github.com/cline/cline/pull/1946 ). I hope to contribute generators-based partial TypeScript JSON decoders once this gets in :-)

> I like @ngxson idea about the state machine

@bandoti I like state machines too, but in this case there may be too many states to enumerate manually, the regexps of some formats do some funky grouping that kinda simplify the code. AND we can most likely turn this whole thing into a giant state machine using [C++ coroutines](https://en.cppreference.com/w/cpp/language/coroutines) once the project adopts C++20. Starting with something inefficient for ease of iteration / maintenance but got my eyes on the prize ;-)

**Comment by llowrey** [comment]
Thanks for the quick response @ochafik

Here's the console output:
```
srv  update_chat_: Parsing chat message: {"tool_call": {"name": "puppeteer_screenshot", "arguments": {"name": "servethehome_homepage",
Parsing input with format Generic: {"tool_call": {"name": "puppeteer_screenshot", "arguments": {"name": "servethehome_homepage",
Failed to parse up to error: [json.exception.parse_error.101] parse error at line 1, column 94: syntax error while parsing object key - unexpected end of input; expected string literal: <<<{"tool_call": {"name": "puppeteer_screenshot", "arguments": {"name": "servethehome_homepage",>>>
Parsed partial JSON: {"tool_call":{"name":"puppeteer_screenshot","arguments":{"name":"278722862"}}} (json_healing_marker: "278722862)
Cleaned up JSON {"tool_call":{"name":"puppeteer_screenshot","arguments":{"name":"278722862"}}} to {"tool_call":{"name":"puppeteer_screenshot","arguments":"{\"name\":"}} (json_healing_marker : '"278722862')
Partial parse: incomplete tool call
Parsed message: {"role":"assistant","content":null,"tool_calls":[{"type":"function","function":{"name":"puppeteer_screenshot","arguments":"{\"name\":"}}]}
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid diff: '{"name":"servethehome_homepage' not found at start of '{"name":'
Aborted (core dumped)
```

Here's the POST body that causes this: [crash.json](https://github.com/user-attachments/files/19393240/crash.json)

I can send with postman and get a crash every time

After more experimenting, it works most of the time. I just got unlucky with my first attempt. I really appreciate the work you are doing and hope this info helps.

**Comment by ochafik** [comment]
@llowrey that specific crash should now be fixed, thanks again for the full details!

**Comment by Column01** [comment]
Trying this out for myself, specifically the streamed tool calls using Qwen2.5 14B I get the following behavior
image

Error in llama-server log: https://gist.github.com/Column01/bdce2d58e53e2d440d8bb3f124e64131

**Comment by ochafik** [comment]
> Trying this out for myself, specifically the streamed tool calls using Qwen2.5 14B I get the following behavior image
> 
> There is no error in the llama-server log but here it is: https://gist.github.com/Column01/bdce2d58e53e2d440d8bb3f124e64131

@Column01 thanks for sharing this! I would really advise against extreme KV quantizations (esp. K) as it seems to severely degrade tool call performance in most models I tested (in your case just switching to a less aggressive `-ctk q8_0` might do the trick).

File: common/chat.h [hunk 1]
```diff
@@ -3,6 +3,7 @@
 #pragma once
 
 #include "common.h"
+#include <functional>
 #include <string>
 #include <vector>
```
Comment (f-krull) [inline common/chat.h:8]: +`#include <chrono>`

**Comment by BiffaloBuff** [comment]
I've been using this successfully with Llama 3.1 8B-Instruct, but have encountered a compatibility issue between this implementation and [PydanticAI](https://github.com/pydantic/pydantic-ai)'s OpenAI API compatible client, and I don't know which side is correct.

This branch seems to have special logic in `common_chat_parse_llama_3_1` to ensure that a partial tool name is never sent, and in practice I do see the full tool name sent several times in the streaming responses from llama.cpp as tool updates are sent.

On the pydantic-ai side, if it receives a `delta` message that includes the tool name, it [appends the content](https://github.com/pydantic/pydantic-ai/blob/7a09324cd5c2579952a78ecd12044400ed65bab3/pydantic_ai_slim/pydantic_ai/messages.py#L720) to what it already has.

Net effect is that in pydantic AI, the tool that ends up getting invoked is something like `my_tool_namemy_tool_namemy_tool_namemy_tool_name...`.

Is this a pydantic AI issue, or an issue with this implementation?

**Comment by colout** [comment]
> I've been using this successfully with Llama 3.1 8B-Instruct, but have encountered a compatibility issue between this implementation and PydanticAI's OpenAI API compatible client, and I don't know which side is correct.

I'm experiencing this issue consistently across all models tested on open-webui, which leverages langchain as its backend. I've documented reproduction steps below using langchain directly in Python.

For context, this PR would be transformative for the local-LLM community. While open-webui recently implemented native tool calling, it currently functions only when streaming is disabled. If llama.cpp could support native tool calls during streaming, this would finally enable proper tool utilization with local models.

### Steps to Reproduce:
1) Using the CPU build of this branch, launch the server with the `bartowski/microsoft_Phi-4-mini-instruct-GGUF` model as specified in the PR instructions. My `docker-compose.yaml` is available in the foldout below if you wish to replicate my exact setup.

2) Execute a langchain tool calling agent in streaming mode. To replicate my exact setup, run`pip install langchain langchain-openai` and run the Python code provided in the foldout below.

3) The Python logs show repeated tool call names: `"add_two_numbersadd_two_numbersadd_two_numbersadd_two_numbersadd_two_numbersadd_two_numbersadd_two_numbersadd_two_numbersadd_two_numbersadd_two_numbersadd_two_numbers"`. In llama.cpp server logs, JSON parsing errors appear (possibly expected in this build) and the complete tool name is sent each time instead of deltas (`data stream, to_send: data: {"choices":[{ ... "delta":{"tool_calls":[{ ... "function":{"name":"add_two_numbers", ... }}]}}]}`).

Let me know if I can help in any way.  

<details>
  <summary>langchain-toolcall.py</summary>
   In case it matters, I used python 3.11.  Create a langchain-toolcall.py file as such:

```python
from langchain.agents import AgentExecutor, create_tool_calling_agent, tool
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from langchain.globals import set_debug
set_debug(True)

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a helpful assistant"),
        ("placeholder", "{chat_history}"),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}"),
    ]
)
model = ChatOpenAI(
    model="llama-cpp-model",
    api_key="none",
    base_url="http://localhost:8080/v1",
    disable_streaming=True,
)

@tool
def magic_function(input: int) -> int:
    """Applies a magic function to an input."""
    print ("TOOL CALL")
    return input + 2

tools = [magic_function]

agent = create_tool_calling_agent(model, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

print(agent_executor.invoke({"input": "what is the value of magic_function(3)?"}))
```

</details>



<details>
  <summary>docker-compose.yaml</summary>
  Create a docker-compose.yaml file as such and run `docker compose up --build -d`. 

```yaml
services:
  llama-cpp-server:
    build:
      context: https://github.com/ochafik/llama.cpp.git#tool-diffs
      dockerfile: .devops/cpu.Dockerfile
      target: full
    ports:
      - "0.0.0.0:8080:8080"
    command: --jinja --alias llama-cpp-model --host 0.0.0.0 --verbose -fa -hf bartowski/microsoft_Phi-4-mini-instruct-GGUF
    entrypoint: ./llama-server
```

</details>

**Comment by cgruver** [comment]
@ochafik   Fantastic work here.  Do you have an ETA for getting this PR ready to merge?

I'm experimenting with the Continue.dev VSCode extension in OpenShift Dev Spaces (Eclipse Che), and using Llama.cpp to serve models from the OpenShift cluster.

This PR is a breakout feature for Llama.cpp IMO.

Cheers.

**Comment by cgruver** [comment]
@ochafik @ericcurtin PTAL - https://github.com/ochafik/llama.cpp/pull/3

**Comment by drrros** [comment]
Hope this PR won't be forgotten or dropped, without it some interesting recent tools doesn't work with LCPP (in particular https://github.com/bytedance/deer-flow gives an error: `openai.InternalServerError: Error code: 500 - {'error': {'code': 500, 'message': 'Cannot use tools with stream', 'type': 'server_error'}}`)

**Comment by strawberrymelonpanda** [comment]
I'm stoked and waiting for this as well, but sadly many MCP tools currently seem to have some compatibility problems with from what I've seen.  [Dive](https://github.com/OpenAgentPlatform/Dive), [Aider's MCP PR](https://github.com/Aider-AI/aider/pull/3937), and others I've tried.  Streaming support would make a big difference, but I'm honestly not sure it's the _only_ issue.

_([Roo-Code](https://github.com/RooVetGit/Roo-Code) works great with or without streaming as it seems to work around tool calling, likely in the normal prompts I'd imagine.)_

**Comment by ochafik** [comment]
Sorry everyone for the lack of activity. Perfect storm of job change and life events (all good!). Will try and push this (and related PRs) through in the next week, as I'm unsure how much I'll be able to do afterwards 😅.

**Comment by strawberrymelonpanda** [comment]
@ochafik Congrats and good luck. Obviously I think folks just want to encourage, not demand. Life always comes first.

**Comment by drrros** [comment]
@ochafik @strawberrymelonpanda absolutely right — not in any way demanding! Best wishes!

**Comment by ericcurtin** [comment]
> Sorry everyone for the lack of activity. Perfect storm of job change and life events (all good!). Will try and push this (and related PRs) through in the next week, as I'm unsure how much I'll be able to do afterwards 😅.

Best of luck in the new role!

**Comment by strawberrymelonpanda** [comment]
> Streaming support would make a big difference, but I'm honestly not sure it's the only issue.

This [merged PR on Minja](https://github.com/google/minja/pull/63) a couple of hours ago might just solve the problem I was having above.

**Comment by cgruver** [comment]
For those who are following this PR, I am trying to maintain a merge from this branch and the master branch of llama.cpp here - https://github.com/cgruver/llama.cpp/tree/tools

**Comment by unclemusclez** [comment]
DcNIsW

**Comment by pwilkin** [comment]
Seems there's a bug in the current code version with executing streaming tools under reasoning models. 

I'm trying it with Qwen3 and the following sequence causes a server crash:
* user query
* reasons -> calls tool
* tool response
* reasons -> tries to respond

As soon as the second reasoning section is cleared, the server crashes with:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid diff: '<think>*truncated for brevity*... The user might be looking for the slang definition, so I should highlight that. Also, note the different contexts like productivity issues and meme culture. Make sure to mention the sources and provide a concise explanation.</think>The term **"brainrot"** has multiple contextual meanings based on the search results' not found at start of '<think>*truncated for brevity*... The user might be looking for the slang definition, so I should highlight that. Also, note the different contexts like productivity issues and meme culture. Make sure to mention the sources and provide a concise explanation.</think>'
```

The chat that triggers it looks like this:

```json
[
  {
    "role": "user",
    "content": "Let's search the web for \"brainrot\"."
  },
  {
    "role": "assistant",
    "tool_calls": [
      {
        "id": "0",
        "name": "search",
        "arguments": {
          "query": "brainrot"
        }
      }
    ]
  },
  {
    "role": "tool",
    "content": "*tool call dump truncated*",
    "tool_call_id": "0"
  }
]
```

Before that, I get warnings like this:
`Grammar still awaiting trigger after token 2711 (` search`)` (after every token that succeeds the thinking block)

**Comment by teleprint-me** [comment]
This is super awesome! I'm having a blast with this right now. I wanted to create a simple wrapper script to test it out with Qwen3 to see how it went. So far, it seems like it's working as intended.

I followed the instructions and tested it out with `curl` to see how it went and got a successful response, so I took it a few steps further and build a minimal wrapper script using OpenAI tooling to test its limits.

Server request seems clean. Model is able to respond and execute the command as well. Still working my way towards chaining messages together.

<details>
<summary>Llama Server Instance Command</summary>

```sh
llama-server --port 8080 --n-gpu-layers 32 --ctx-size 16384 --pooling mean --slots --jinja -fa -m /mnt/valerie/models/Qwen/Qwen3-1.7B/ggml-model-f16.gguf
```

</details>

<details>
<summary>Dot Env</summary>

```env
OPENAI_API_KEY=sk-no-key-required
OPENAI_BASE_URL=http://localhost:8080/v1
```

</details>

<details>
<summary>Source File</summary>

```py
import json
import os
import sys

import dotenv
from openai import OpenAI
from openai.types.chat.chat_completion_chunk import ChatCompletionChunk

from agent.tools.weather import get_weather

ESCAPE = "\x1b"
BOLD = ESCAPE + "[1m"
UNDERLINE = ESCAPE + "[4m"
RESET = ESCAPE + "[0m"


def create_client():
    # Load environment
    dotenv.load_dotenv(".env")

    api_key = os.getenv("OPENAI_API_KEY", "")
    base_url = os.getenv("OPENAI_BASE_URL", "")

    if not api_key:
        raise ValueError("EnvironmentError: OPENAI_API_KEY not set in .env")

    # Setup default base URL if using local mode
    if api_key == "sk-no-key-required" and not base_url:
        base_url = "http://localhost:8080/v1"

    # Initialize client
    return OpenAI(api_key=api_key, base_url=base_url)


def stream_response(response):
    tool_call_buffer = ""
    buffering_tool = False
    finish_reason = None

    for chunk in response:
        if isinstance(chunk, ChatCompletionChunk):
            delta = chunk.choices[0].delta
            finish_reason = chunk.choices[0].finish_reason

            # Handle streaming reasoning
            if delta.content:
                content = delta.content
                if content == "<think>":
                    print(f"{UNDERLINE}{BOLD}Thinking{RESET}", end="\n")
                elif content == "</think>":
                    print(f"\n{UNDERLINE}{BOLD}Completion{RESET}", end="")
                else:
                    print(content, end="")
                sys.stdout.flush()

            # Handle tool call streaming
            if delta.tool_calls:
                buffering_tool = True
                for tool_call in delta.tool_calls:
                    arguments = tool_call.function.arguments or ""
                    tool_call_buffer += arguments

    print()  # Newline after stream ends

    # Dispatch if tool call is complete
    if buffering_tool and finish_reason == "tool_calls":
        try:
            tool_args = json.loads(tool_call_buffer)
            print(f"\n{UNDERLINE}{BOLD}Calling Tool...{RESET}")
            result = get_weather(**tool_args)
            print(f"\n{UNDERLINE}{BOLD}Tool Result:{RESET} {result}")
        except json.JSONDecodeError:
            print(f"{BOLD}Warning:{RESET} Failed to decode tool call arguments.")


def main():
    tools = [
        {
            "type": "function",
            "function": {
                "name": "get_weather",
                "description": "Retrieves current weather for the given location.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA",
                        },
                        "units": {
                            "type": "string",
                            "enum": ["metric", "uscs"],
                            "description": "The unit system. Default is 'metric'.",
                        },
                    },
                    "required": ["location", "units"],
                    "additionalProperties": False,
                },
                "strict": True,
            },
        }
    ]

    # Sample chat sequence
    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What is the weather like in Paris today?"},
    ]

    try:
        client = create_client()
        response = client.chat.completions.create(
            model="qwen3",  # Use "gpt-4" for OpenAI, "qwen3" for local
            messages=messages,
            stream=True,
            temperature=0.8,
            tools=tools,
        )
        stream_response(response)
    except Exception as e:
        print(f"Error: {e}")


if __name__ == "__main__":
    main()
```

</details>

<details>
<summary>Llama Server Request</summary>

```sh
srv  params_from_: Chat format: Hermes 2 Pro
slot launch_slot_: id  0 | task 746 | processing task
slot update_slots: id  0 | task 746 | new prompt, n_ctx_slot = 16384, n_keep = 0, n_prompt_tokens = 223
slot update_slots: id  0 | task 746 | need to evaluate at least 1 token to generate logits, n_past = 223, n_prompt_tokens = 223
slot update_slots: id  0 | task 746 | kv cache rm [222, end)
slot update_slots: id  0 | task 746 | prompt processing progress, n_past = 223, n_tokens = 1, progress = 0.004484
slot update_slots: id  0 | task 746 | prompt done, n_past = 223, n_tokens = 1
slot      release: id  0 | task 746 | stop processing: n_past = 345, truncated = 0
slot print_timing: id  0 | task 746 | 
prompt eval time =      29.95 ms /     1 tokens (   29.95 ms per token,    33.38 tokens per second)
       eval time =    2268.35 ms /   123 tokens (   18.44 ms per token,    54.22 tokens per second)
      total time =    2298.30 ms /   124 tokens
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /v1/chat/completions 127.0.0.1 200
```

</details>

[Screencast From 2025-05-20 00-44-34.webm](https://github.com/user-attachments/assets/21110c27-99d8-4bf0-a6c5-b5cf04fcd947)

I love this. This is awesome. I've been jonsing for local memory management and this absolutely opens the door for doing exactly that.

**Comment by strawberrymelonpanda** [comment]
@teleprint-me Nice example.  If there isn't already something equivalent, it'd maybe be worth adding to the examples once this is merged.  The closest I see is the curl command at the bottom of [/docs/function-calling.md](https://github.com/ggml-org/llama.cpp/blob/b69f1647f9953cb3773266d2c83a92fd0e7e6d66/docs/function-calling.md), but this is a fairly complete python example.

**Comment by pwilkin** [comment]
I mean, the things is tool calling should work *with* thinking. The models lose quite a bit of quality without thinking enabled.

**Comment by unclemusclez** [comment]
> @strawberrymelonpanda The `README.md` links to the OpenAI REST API docs and specification which explains how to use it.
> 
> It makes sense that it's not included in there because it's already described by the docs.
> 
> If collaborators are inclined to include it, I'm okay with that. This is just boilerplate.
> 
> I think it would be useful to have a simple example for this in C/C++ instead which exposes core Llama and GGML API functions and how to use them. That would be more relavent.
> 
> @unclemusclez That's interesting. According to Qwen3 official `README.md`, you can use a shorthand by appending `/no_think` to user input to disable it. I tested this last night and it worked fine. The template remains the same. Though, I haven't looked into it in depth.
> 
> I've been MIA because I'm learning fundamentals for neural networking, transformers, vulkan compute, etc which is challenging and time consuming. Filling in my gaps in my understanding of how this tech works at a basic level.
@teleprint-me so this means just add `/no_think` to every single prompt? there is no environment flag? i dont have to run llama-server differently?

**Comment by taha-yassine** [comment]
> > @strawberrymelonpanda The `README.md` links to the OpenAI REST API docs and specification which explains how to use it.
> > 
> > It makes sense that it's not included in there because it's already described by the docs.
> > 
> > If collaborators are inclined to include it, I'm okay with that. This is just boilerplate.
> > 
> > I think it would be useful to have a simple example for this in C/C++ instead which exposes core Llama and GGML API functions and how to use them. That would be more relavent.
> > 
> > @unclemusclez That's interesting. According to Qwen3 official `README.md`, you can use a shorthand by appending `/no_think` to user input to disable it. I tested this last night and it worked fine. The template remains the same. Though, I haven't looked into it in depth.
> > 
> > I've been MIA because I'm learning fundamentals for neural networking, transformers, vulkan compute, etc which is challenging and time consuming. Filling in my gaps in my understanding of how this tech works at a basic level.
> 
> 
> @teleprint-me so this means just add `/no_think` to every single prompt? there is no environment flag? i dont have to run llama-server differently?
> 

`/no_think` is just a soft switch meaning it's up to the model to honor it or not. Proper support for `enable_thinking` would be more robust.

**Comment by teleprint-me** [comment]
It was an experiment and lighthearted observation. I would recommend reading the documentation and making your own interpretation — That's what I did.

As for how it operates internally, usually theres a paper, or if youre daring — you can dive deep into the `transformers` and `torch` code to see how it works.

I've done this and I hated every moment of it, but I learned a lot along the way. I even figured out how to manipulate the internals of the interfaces to build my own custom diffuse pipelines, but I find text and chat completions to be highly satisfying and rewarding in comparison.

Probably why I like and prefer llama.cpp compared to other options.

I have nothing else to add at the moment as this is now off-topic. RTFM.

**Comment by teleprint-me** [comment]
So, I've been hacking together [a simple agentic system](https://github.com/teleprint-me/agent) to experiment with this PR and ran into something interesting.

I eventually realized (after reviewing the backtrace) that the server was comparing inputs to previous outputs - and these seem fairly strict. If the input is not exactly the same as the output, the server throws an error and raises and exception and then crashes.

Basically, I was omitting the models previous thought process from the aggregated messages sequence and it crashes after performing `compute_diffs` around line 86.

In this PR, we can see `common_chat_msg_diff` defines this set of rules. Lines 72 to 84 in `chat.h` to be specific.

Modifying the code by making a few experimental tweaks to reconstruct the original message resolved the server crash.

I'm not sure if it was my code, this PR, or something that was baked into the server over the past year, but I'm wondering if it is absolutely necessary and why such a strict rule set is in place. I was curious as to why this might be the case because I've been out of the loop for some time.

If this is out of scope of this PR, feel free let me know and provide suggestions as to where this might be more appropriate. I posted this here because I'm currently experimenting with this PR specifically.

I've provided a detailed summary including the backtrace at the time the server crashed below.

<details><summary>GDB Runtime Output</summary>

```sh
03:36:35 | ~/.bin/cpp/llama.cpp
 git:(tool-diffs | θ) λ gdb --quiet -ex='break main' -ex=run --args llama-server --port 8080 --n-gpu-layers 32 --ctx-size 16384 --pooling mean --slots --jinja -fa -m /mnt/valerie/models/Qwen/Qwen3-1.7B/ggml-model-f16.gguf
Reading symbols from llama-server...
Breakpoint 1 at 0xa8584: file /home/austin/.bin/cpp/llama.cpp/tools/server/server.cpp, line 3582.
Starting program: /mnt/paper/.bin/llama-server --port 8080 --n-gpu-layers 32 --ctx-size 16384 --pooling mean --slots --jinja -fa -m /mnt/valerie/models/Qwen/Qwen3-1.7B/ggml-model-f16.gguf

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /lib64/ld-linux-x86-64.so.2
Downloading 5.05 M separate debug info for /usr/lib/libcurl.so.4                                                                                                                                                                                                                                                                
Function(s) ^std::(move|forward|as_const|(__)?addressof) will be skipped when stepping.                                                                                                                                                                                                                                         
Function(s) ^std::(shared|unique)_ptr<.*>::(get|operator) will be skipped when stepping.
Function(s) ^std::(basic_string|vector|array|deque|(forward_)?list|(unordered_|flat_)?(multi)?(map|set)|span)<.*>::(c?r?(begin|end)|front|back|data|size|empty) will be skipped when stepping.
Function(s) ^std::(basic_string|vector|array|deque|span)<.*>::operator.] will be skipped when stepping.
Downloading 3.07 M separate debug info for /usr/lib/libm.so.6
Downloading 9.66 M separate debug info for /usr/lib/libc.so.6                                                                                                                                                                                                                                                                   
[Thread debugging using libthread_db enabled]                                                                                                                                                                                                                                                                                   
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Downloading 476.11 K separate debug info for /usr/lib/libnghttp3.so.9
Downloading 550.52 K separate debug info for /usr/lib/libnghttp2.so.14                                                                                                                                                                                                                                                          
Downloading 108.19 K separate debug info for /usr/lib/libidn2.so.0                                                                                                                                                                                                                                                              
Downloading 1.22 M separate debug info for /usr/lib/libssh2.so.1                                                                                                                                                                                                                                                                
Downloading 53.44 K separate debug info for /usr/lib/libpsl.so.5                                                                                                                                                                                                                                                                
Downloading 4.02 M separate debug info for /usr/lib/libssl.so.3                                                                                                                                                                                                                                                                 
Downloading 14.15 M separate debug info for /usr/lib/libcrypto.so.3                                                                                                                                                                                                                                                             
Downloading 1.75 M separate debug info for /usr/lib/libgssapi_krb5.so.2                                                                                                                                                                                                                                                         
Downloading 5.77 M separate debug info for /usr/lib/libzstd.so.1                                                                                                                                                                                                                                                                
Downloading 214.80 K separate debug info for /usr/lib/libbrotlidec.so.1                                                                                                                                                                                                                                                         
Downloading 194.53 K separate debug info for /usr/lib/libz.so.1                                                                                                                                                                                                                                                                 
Downloading 3.40 M separate debug info for /usr/lib/libvulkan.so.1                                                                                                                                                                                                                                                              
Downloading 1.62 M separate debug info for /usr/lib/libunistring.so.5                                                                                                                                                                                                                                                           
Downloading 2.70 M separate debug info for /usr/lib/libkrb5.so.3                                                                                                                                                                                                                                                                
Downloading 685.64 K separate debug info for /usr/lib/libk5crypto.so.3                                                                                                                                                                                                                                                          
Downloading 24.72 K separate debug info for /usr/lib/libcom_err.so.2                                                                                                                                                                                                                                                            
Downloading 140.23 K separate debug info for /usr/lib/libkrb5support.so.0                                                                                                                                                                                                                                                       
Downloading 34.54 K separate debug info for /usr/lib/libkeyutils.so.1                                                                                                                                                                                                                                                           
Downloading 207.47 K separate debug info for /usr/lib/libresolv.so.2                                                                                                                                                                                                                                                            
Downloading 22.55 K separate debug info for /usr/lib/libbrotlicommon.so.1                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                
Breakpoint 1, main (argc=14, argv=0x7fffffffd918) at /home/austin/.bin/cpp/llama.cpp/tools/server/server.cpp:3582
3582	int main(int argc, char ** argv) {
(gdb) c
Continuing.
Downloading 12.21 M separate debug info for /usr/lib/libvulkan_radeon.so
Downloading 401.89 M separate debug info for /usr/lib/libLLVM.so.19.1                                                                                                                                                                                                                                                           
Downloading 922.55 K separate debug info for /usr/lib/libelf.so.1                                                                                                                                                                                                                                                               
Downloading 39.01 K separate debug info for /usr/lib/libxcb-dri3.so.0                                                                                                                                                                                                                                                           
Downloading 146.31 K separate debug info for /usr/lib/libwayland-client.so.0                                                                                                                                                                                                                                                    
Downloading 500.05 K separate debug info for /usr/lib/libxcb.so.1                                                                                                                                                                                                                                                               
Downloading 34.59 K separate debug info for /usr/lib/libX11-xcb.so.1                                                                                                                                                                                                                                                            
Downloading 25.20 K separate debug info for /usr/lib/libxcb-present.so.0                                                                                                                                                                                                                                                        
Downloading 72.90 K separate debug info for /usr/lib/libxcb-xfixes.so.0                                                                                                                                                                                                                                                         
Downloading 57.62 K separate debug info for /usr/lib/libxcb-sync.so.1                                                                                                                                                                                                                                                           
Downloading 159.27 K separate debug info for /usr/lib/libxcb-randr.so.0                                                                                                                                                                                                                                                         
Downloading 24.12 K separate debug info for /usr/lib/libxcb-shm.so.0                                                                                                                                                                                                                                                            
Downloading 11.27 K separate debug info for /usr/lib/libxshmfence.so.1                                                                                                                                                                                                                                                          
Downloading 17.48 K separate debug info for /usr/lib/libxcb-keysyms.so.1                                                                                                                                                                                                                                                        
Downloading 242.70 K separate debug info for /usr/lib/libdrm.so.2                                                                                                                                                                                                                                                               
Downloading 1.49 M separate debug info for /usr/lib/libudev.so.1                                                                                                                                                                                                                                                                
Downloading 370.80 K separate debug info for /usr/lib/libexpat.so.1                                                                                                                                                                                                                                                             
Downloading 139.80 K separate debug info for /usr/lib/libdrm_amdgpu.so.1                                                                                                                                                                                                                                                        
Downloading 36.17 M separate debug info for /usr/lib/libSPIRV-Tools.so                                                                                                                                                                                                                                                          
Downloading 121.48 K separate debug info for /usr/lib/libffi.so.8                                                                                                                                                                                                                                                               
Downloading 610.80 K separate debug info for /usr/lib/libedit.so.0                                                                                                                                                                                                                                                              
Downloading 3.53 M separate debug info for /usr/lib/libxml2.so.16                                                                                                                                                                                                                                                               
Downloading 29.59 K separate debug info for /usr/lib/libXau.so.6                                                                                                                                                                                                                                                                
Downloading 52.94 K separate debug info for /usr/lib/libXdmcp.so.6                                                                                                                                                                                                                                                              
Downloading 98.30 K separate debug info for /usr/lib/libcap.so.2                                                                                                                                                                                                                                                                
Downloading 1.70 M separate debug info for /usr/lib/libncursesw.so.6                                                                                                                                                                                                                                                            
Downloading 889.26 K separate debug info for /usr/lib/liblzma.so.5                                                                                                                                                                                                                                                              
Downloading 10.53 M separate debug info for /usr/lib/libicuuc.so.76                                                                                                                                                                                                                                                             
Downloading 30.38 M separate debug info for /usr/lib/libicudata.so.76                                                                                                                                                                                                                                                           
[New Thread 0x7fffe8bff6c0 (LWP 70357)]                                                                                                                                                                                                                                                                                         
[New Thread 0x7fffe3fff6c0 (LWP 70358)]
[New Thread 0x7fffe37fe6c0 (LWP 70359)]
[New Thread 0x7fffe2ffd6c0 (LWP 70360)]
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = AMD Radeon RX 7600 XT (RADV NAVI33) (radv) | uma: 0 | fp16: 1 | warp size: 64 | shared memory: 65536 | int dot: 1 | matrix cores: KHR_coopmat
register_backend: registered backend Vulkan (1 devices)
register_device: registered device Vulkan0 (AMD Radeon RX 7600 XT (RADV NAVI33))
register_backend: registered backend CPU (1 devices)
register_device: registered device CPU (AMD Ryzen 7 7700X 8-Core Processor)
load_backend: failed to find ggml_backend_init in /mnt/paper/.bin/cpp/llama.cpp/build/bin/libggml-vulkan.so
load_backend: failed to find ggml_backend_init in /mnt/paper/.bin/cpp/llama.cpp/build/bin/libggml-cpu.so
[New Thread 0x7fffe27fc6c0 (LWP 70361)]
build: 5510 (810c4c32) with cc (GCC) 15.1.1 20250425 for x86_64-pc-linux-gnu (debug)
system info: n_threads = 8, n_threads_batch = 8, total_threads = 16

system_info: n_threads = 8 (n_threads_batch = 8) / 16 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | BMI2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | AVX512_BF16 = 1 | LLAMAFILE = 1 | OPENMP = 1 | AARCH64_REPACK = 1 | 

main: binding port with default address family
[New Thread 0x7fffe1ffb6c0 (LWP 70362)]
[New Thread 0x7fffe17fa6c0 (LWP 70363)]
[New Thread 0x7fffe0ff96c0 (LWP 70364)]
[New Thread 0x7fffcbfff6c0 (LWP 70365)]
[New Thread 0x7fffcb7fe6c0 (LWP 70366)]
[New Thread 0x7fffcaffd6c0 (LWP 70367)]
[New Thread 0x7fffca7fc6c0 (LWP 70368)]
[New Thread 0x7fffc9ffb6c0 (LWP 70369)]
[New Thread 0x7fffc97fa6c0 (LWP 70370)]
[New Thread 0x7fffc8ff96c0 (LWP 70371)]
[New Thread 0x7fffc87f86c0 (LWP 70372)]
[New Thread 0x7fffc7ff76c0 (LWP 70373)]
[New Thread 0x7fffc77f66c0 (LWP 70374)]
[New Thread 0x7fffc6ff56c0 (LWP 70375)]
main: HTTP server is listening, hostname: 127.0.0.1, port: 8080, http threads: 15
main: loading model
srv    load_model: loading model '/mnt/valerie/models/Qwen/Qwen3-1.7B/ggml-model-f16.gguf'
[New Thread 0x7fffc67f46c0 (LWP 70376)]
[New Thread 0x7fffc5ff36c0 (LWP 70377)]
llama_model_load_from_file_impl: using device Vulkan0 (AMD Radeon RX 7600 XT (RADV NAVI33)) - 16368 MiB free
llama_model_loader: loaded meta data with 34 key-value pairs and 311 tensors from /mnt/valerie/models/Qwen/Qwen3-1.7B/ggml-model-f16.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen3
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Qwen3 1.7B
llama_model_loader: - kv   3:                           general.basename str              = Qwen3
llama_model_loader: - kv   4:                         general.size_label str              = 1.7B
llama_model_loader: - kv   5:                            general.license str              = apache-2.0
llama_model_loader: - kv   6:                       general.license.link str              = https://huggingface.co/Qwen/Qwen3-1.7...
llama_model_loader: - kv   7:                   general.base_model.count u32              = 1
llama_model_loader: - kv   8:                  general.base_model.0.name str              = Qwen3 1.7B Base
llama_model_loader: - kv   9:          general.base_model.0.organization str              = Qwen
llama_model_loader: - kv  10:              general.base_model.0.repo_url str              = https://huggingface.co/Qwen/Qwen3-1.7...
llama_model_loader: - kv  11:                               general.tags arr[str,1]       = ["text-generation"]
llama_model_loader: - kv  12:                          qwen3.block_count u32              = 28
llama_model_loader: - kv  13:                       qwen3.context_length u32              = 40960
llama_model_loader: - kv  14:                     qwen3.embedding_length u32              = 2048
llama_model_loader: - kv  15:                  qwen3.feed_forward_length u32              = 6144
llama_model_loader: - kv  16:                 qwen3.attention.head_count u32              = 16
llama_model_loader: - kv  17:              qwen3.attention.head_count_kv u32              = 8
llama_model_loader: - kv  18:                       qwen3.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  19:     qwen3.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  20:                 qwen3.attention.key_length u32              = 128
llama_model_loader: - kv  21:               qwen3.attention.value_length u32              = 128
llama_model_loader: - kv  22:                          general.file_type u32              = 1
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - kv  24:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  25:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  26:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  27:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  28:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  29:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  30:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  31:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  32:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  33:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
llama_model_loader: - type  f32:  113 tensors
llama_model_loader: - type  f16:  198 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = F16
print_info: file size   = 3.78 GiB (16.00 BPW) 
load: special tokens cache size = 26
load: token to piece cache size = 0.9311 MB
print_info: arch             = qwen3
print_info: vocab_only       = 0
print_info: n_ctx_train      = 40960
print_info: n_embd           = 2048
print_info: n_layer          = 28
print_info: n_head           = 16
print_info: n_head_kv        = 8
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: n_swa_pattern    = 1
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 2
print_info: n_embd_k_gqa     = 1024
print_info: n_embd_v_gqa     = 1024
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-06
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 6144
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = 0
print_info: rope type        = 2
print_info: rope scaling     = linear
print_info: freq_base_train  = 1000000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 40960
print_info: rope_finetuned   = unknown
print_info: ssm_d_conv       = 0
print_info: ssm_d_inner      = 0
print_info: ssm_d_state      = 0
print_info: ssm_dt_rank      = 0
print_info: ssm_dt_b_c_rms   = 0
print_info: model type       = 1.7B
print_info: model params     = 2.03 B
print_info: general.name     = Qwen3 1.7B
print_info: vocab type       = BPE
print_info: n_vocab          = 151936
print_info: n_merges         = 151387
print_info: BOS token        = 151643 '<|endoftext|>'
print_info: EOS token        = 151645 '<|im_end|>'
print_info: EOT token        = 151645 '<|im_end|>'
print_info: PAD token        = 151643 '<|endoftext|>'
print_info: LF token         = 198 'Ċ'
print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
print_info: FIM MID token    = 151660 '<|fim_middle|>'
print_info: FIM PAD token    = 151662 '<|fim_pad|>'
print_info: FIM REP token    = 151663 '<|repo_name|>'
print_info: FIM SEP token    = 151664 '<|file_sep|>'
print_info: EOG token        = 151643 '<|endoftext|>'
print_info: EOG token        = 151645 '<|im_end|>'
print_info: EOG token        = 151662 '<|fim_pad|>'
print_info: EOG token        = 151663 '<|repo_name|>'
print_info: EOG token        = 151664 '<|file_sep|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: offloading 28 repeating layers to GPU
load_tensors: offloading output layer to GPU
load_tensors: offloaded 29/29 layers to GPU
load_tensors:      Vulkan0 model buffer size =  3281.97 MiB
load_tensors:   CPU_Mapped model buffer size =   593.50 MiB
.......................................................................
llama_context: constructing llama_context
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 16384
llama_context: n_ctx_per_seq = 16384
llama_context: n_batch       = 2048
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = 1
llama_context: freq_base     = 1000000.0
llama_context: freq_scale    = 1
llama_context: n_ctx_per_seq (16384) < n_ctx_train (40960) -- the full capacity of the model will not be utilized
llama_context: Vulkan_Host  output buffer size =     0.58 MiB
llama_kv_cache_unified: kv_size = 16384, type_k = 'f16', type_v = 'f16', n_layer = 28, can_shift = 1, padding = 256
llama_kv_cache_unified:    Vulkan0 KV buffer size =  1792.00 MiB
llama_kv_cache_unified: KV self size  = 1792.00 MiB, K (f16):  896.00 MiB, V (f16):  896.00 MiB
llama_context:    Vulkan0 compute buffer size =   300.75 MiB
llama_context: Vulkan_Host compute buffer size =    36.01 MiB
llama_context: graph nodes  = 959
llama_context: graph splits = 2
common_init_from_params: setting dry_penalty_last_n to ctx_size = 16384
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
[New Thread 0x7fff22d116c0 (LWP 70379)]
[New Thread 0x7fff225106c0 (LWP 70380)]
[New Thread 0x7fff21d0f6c0 (LWP 70381)]
[New Thread 0x7fff2150e6c0 (LWP 70382)]
[New Thread 0x7fff20d0d6c0 (LWP 70383)]
[New Thread 0x7fff13fff6c0 (LWP 70384)]
[New Thread 0x7fff137fe6c0 (LWP 70385)]
[New Thread 0x7fff12ffd6c0 (LWP 70386)]
[New Thread 0x7fff127fc6c0 (LWP 70387)]
[New Thread 0x7fff11ffb6c0 (LWP 70388)]
[New Thread 0x7fff117fa6c0 (LWP 70389)]
[Thread 0x7fff225106c0 (LWP 70380) exited]
[Thread 0x7fff22d116c0 (LWP 70379) exited]
[Thread 0x7fff13fff6c0 (LWP 70384) exited]
[Thread 0x7fff11ffb6c0 (LWP 70388) exited]
[Thread 0x7fff21d0f6c0 (LWP 70381) exited]
[Thread 0x7fff117fa6c0 (LWP 70389) exited]
[Thread 0x7fff137fe6c0 (LWP 70385) exited]
[Thread 0x7fff12ffd6c0 (LWP 70386) exited]
[Thread 0x7fff127fc6c0 (LWP 70387) exited]
[Thread 0x7fff2150e6c0 (LWP 70382) exited]
[Thread 0x7fff20d0d6c0 (LWP 70383) exited]
srv          init: initializing slots, n_slots = 1
slot         init: id  0 | task -1 | new slot n_ctx_slot = 16384
main: model loaded
main: chat template, chat_template: {%- if tools %}
    {{- '<|im_start|>system\n' }}
    {%- if messages[0].role == 'system' %}
        {{- messages[0].content + '\n\n' }}
    {%- endif %}
    {{- "# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}
    {%- for tool in tools %}
        {{- "\n" }}
        {{- tool | tojson }}
    {%- endfor %}
    {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{\"name\": <function-name>, \"arguments\": <args-json-object>}\n</tool_call><|im_end|>\n" }}
{%- else %}
    {%- if messages[0].role == 'system' %}
        {{- '<|im_start|>system\n' + messages[0].content + '<|im_end|>\n' }}
    {%- endif %}
{%- endif %}
{%- set ns = namespace(multi_step_tool=true, last_query_index=messages|length - 1) %}
{%- for message in messages[::-1] %}
    {%- set index = (messages|length - 1) - loop.index0 %}
    {%- if ns.multi_step_tool and message.role == "user" and not(message.content.startswith('<tool_response>') and message.content.endswith('</tool_response>')) %}
        {%- set ns.multi_step_tool = false %}
        {%- set ns.last_query_index = index %}
    {%- endif %}
{%- endfor %}
{%- for message in messages %}
    {%- if (message.role == "user") or (message.role == "system" and not loop.first) %}
        {{- '<|im_start|>' + message.role + '\n' + message.content + '<|im_end|>' + '\n' }}
    {%- elif message.role == "assistant" %}
        {%- set content = message.content %}
        {%- set reasoning_content = '' %}
        {%- if message.reasoning_content is defined and message.reasoning_content is not none %}
            {%- set reasoning_content = message.reasoning_content %}
        {%- else %}
            {%- if '</think>' in message.content %}
                {%- set content = message.content.split('</think>')[-1].lstrip('\n') %}
                {%- set reasoning_content = message.content.split('</think>')[0].rstrip('\n').split('<think>')[-1].lstrip('\n') %}
            {%- endif %}
        {%- endif %}
        {%- if loop.index0 > ns.last_query_index %}
            {%- if loop.last or (not loop.last and reasoning_content) %}
                {{- '<|im_start|>' + message.role + '\n<think>\n' + reasoning_content.strip('\n') + '\n</think>\n\n' + content.lstrip('\n') }}
            {%- else %}
                {{- '<|im_start|>' + message.role + '\n' + content }}
            {%- endif %}
        {%- else %}
            {{- '<|im_start|>' + message.role + '\n' + content }}
        {%- endif %}
        {%- if message.tool_calls %}
            {%- for tool_call in message.tool_calls %}
                {%- if (loop.first and content) or (not loop.first) %}
                    {{- '\n' }}
                {%- endif %}
                {%- if tool_call.function %}
                    {%- set tool_call = tool_call.function %}
                {%- endif %}
                {{- '<tool_call>\n{"name": "' }}
                {{- tool_call.name }}
                {{- '", "arguments": ' }}
                {%- if tool_call.arguments is string %}
                    {{- tool_call.arguments }}
                {%- else %}
                    {{- tool_call.arguments | tojson }}
                {%- endif %}
                {{- '}\n</tool_call>' }}
            {%- endfor %}
        {%- endif %}
        {{- '<|im_end|>\n' }}
    {%- elif message.role == "tool" %}
        {%- if loop.first or (messages[loop.index0 - 1].role != "tool") %}
            {{- '<|im_start|>user' }}
        {%- endif %}
        {{- '\n<tool_response>\n' }}
        {{- message.content }}
        {{- '\n</tool_response>' }}
        {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}
            {{- '<|im_end|>\n' }}
        {%- endif %}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n' }}
    {%- if enable_thinking is defined and enable_thinking is false %}
        {{- '<think>\n\n</think>\n\n' }}
    {%- endif %}
{%- endif %}, example_format: '<|im_start|>system
You are a helpful assistant<|im_end|>
<|im_start|>user
Hello<|im_end|>
<|im_start|>assistant
Hi there<|im_end|>
<|im_start|>user
How are you?<|im_end|>
<|im_start|>assistant
'
main: server is listening on http://127.0.0.1:8080 - starting the main loop
srv  update_slots: all slots are idle
srv  params_from_: Chat format: Hermes 2 Pro
slot launch_slot_: id  0 | task 0 | processing task
slot update_slots: id  0 | task 0 | new prompt, n_ctx_slot = 16384, n_keep = 0, n_prompt_tokens = 232
slot update_slots: id  0 | task 0 | kv cache rm [0, end)
slot update_slots: id  0 | task 0 | prompt processing progress, n_past = 232, n_tokens = 232, progress = 1.000000
slot update_slots: id  0 | task 0 | prompt done, n_past = 232, n_tokens = 232
[New Thread 0x7fff117fa6c0 (LWP 70434)]
[Thread 0x7fff117fa6c0 (LWP 70434) exited]
[New Thread 0x7fff117fa6c0 (LWP 70435)]
[Thread 0x7fff117fa6c0 (LWP 70435) exited]
slot      release: id  0 | task 0 | stop processing: n_past = 379, truncated = 0
slot print_timing: id  0 | task 0 | 
prompt eval time =     191.82 ms /   232 tokens (    0.83 ms per token,  1209.49 tokens per second)
       eval time =    2716.36 ms /   148 tokens (   18.35 ms per token,    54.48 tokens per second)
      total time =    2908.18 ms /   380 tokens
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /v1/chat/completions 127.0.0.1 200
srv  params_from_: Chat format: Hermes 2 Pro
slot launch_slot_: id  0 | task 149 | processing task
slot update_slots: id  0 | task 149 | new prompt, n_ctx_slot = 16384, n_keep = 0, n_prompt_tokens = 232
slot update_slots: id  0 | task 149 | need to evaluate at least 1 token to generate logits, n_past = 232, n_prompt_tokens = 232
slot update_slots: id  0 | task 149 | kv cache rm [231, end)
slot update_slots: id  0 | task 149 | prompt processing progress, n_past = 232, n_tokens = 1, progress = 0.004310
slot update_slots: id  0 | task 149 | prompt done, n_past = 232, n_tokens = 1
slot      release: id  0 | task 149 | stop processing: n_past = 399, truncated = 0
slot print_timing: id  0 | task 149 | 
prompt eval time =      30.24 ms /     1 tokens (   30.24 ms per token,    33.07 tokens per second)
       eval time =    3104.30 ms /   168 tokens (   18.48 ms per token,    54.12 tokens per second)
      total time =    3134.54 ms /   169 tokens
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /v1/chat/completions 127.0.0.1 200
srv  params_from_: Chat format: Hermes 2 Pro
slot launch_slot_: id  0 | task 318 | processing task
slot update_slots: id  0 | task 318 | new prompt, n_ctx_slot = 16384, n_keep = 0, n_prompt_tokens = 273
slot update_slots: id  0 | task 318 | kv cache rm [232, end)
slot update_slots: id  0 | task 318 | prompt processing progress, n_past = 273, n_tokens = 41, progress = 0.150183
slot update_slots: id  0 | task 318 | prompt done, n_past = 273, n_tokens = 41
slot      release: id  0 | task 318 | stop processing: n_past = 428, truncated = 0
slot print_timing: id  0 | task 318 | 
prompt eval time =      96.86 ms /    41 tokens (    2.36 ms per token,   423.31 tokens per second)
       eval time =    2860.68 ms /   156 tokens (   18.34 ms per token,    54.53 tokens per second)
      total time =    2957.54 ms /   197 tokens
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /v1/chat/completions 127.0.0.1 200
srv  params_from_: Chat format: Hermes 2 Pro
slot launch_slot_: id  0 | task 475 | processing task
slot update_slots: id  0 | task 475 | new prompt, n_ctx_slot = 16384, n_keep = 0, n_prompt_tokens = 397
slot update_slots: id  0 | task 475 | kv cache rm [273, end)
slot update_slots: id  0 | task 475 | prompt processing progress, n_past = 397, n_tokens = 124, progress = 0.312343
slot update_slots: id  0 | task 475 | prompt done, n_past = 397, n_tokens = 124
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid diff: '<think>Okay, the user asked for the weather in Paris, France. I called the get_weather function with the location set to "Paris, France" and units as "metric". The tool response came back with the weather data. Now I need to present this information in a clear and friendly way.

First, I'll check the response string to see the details. The date and time are "09:47:38+0200 06:01:51 21:33:35" which might be the time zone and other timestamps. The weather is "Overcast ↓9km/h +14°C". 

I should break this down. The temperature is 14°C, with a wind speed of 9 km/h. The weather condition is overcast. The time zone is +2 hours, so the local time is 2 hours ahead of UTC. 

I need to mention the temperature, wind speed, weather condition, and time zone. Also, make sure to mention that it's overcast and the wind is coming from the south. The user might want to know if they should carry an umbrella, but since it's overcast, maybe just note the conditions. 

I should structure the response with a friendly greeting, the current weather, and the time zone. Keep it concise but informative. Let me put that all together in a natural way.</think>The current weather in Paris, France is **Overcast** with a wind speed of **9 km/h** and a temperature of **+14°C**. The local time is' not found at start of '<think>Okay, the user asked for the weather in Paris, France. I called the get_weather function with the location set to "Paris, France" and units as "metric". The tool response came back with the weather data. Now I need to present this information in a clear and friendly way.

First, I'll check the response string to see the details. The date and time are "09:47:38+0200 06:01:51 21:33:35" which might be the time zone and other timestamps. The weather is "Overcast ↓9km/h +14°C". 

I should break this down. The temperature is 14°C, with a wind speed of 9 km/h. The weather condition is overcast. The time zone is +2 hours, so the local time is 2 hours ahead of UTC. 

I need to mention the temperature, wind speed, weather condition, and time zone. Also, make sure to mention that it's overcast and the wind is coming from the south. The user might want to know if they should carry an umbrella, but since it's overcast, maybe just note the conditions. 

I should structure the response with a friendly greeting, the current weather, and the time zone. Keep it concise but informative. Let me put that all together in a natural way.</think>'

Thread 1 "llama-server" received signal SIGABRT, Aborted.
Downloading 4.48 K source file /usr/src/debug/glibc/glibc/nptl/pthread_kill.c
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44                                                                                                                                                                                                       
44	     return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff54a7813 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:89
#2  0x00007ffff544ddc0 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff543557a in __GI_abort () at abort.c:73
#4  0x00007ffff5697bf8 in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#5  0x00007ffff56b1c1a in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0x00007ffff56975db in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#7  0x00007ffff56b1ed6 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x555555a5e2c0 <typeinfo for std::runtime_error@GLIBCXX_3.4>, dest=0x7ffff56c99b0 <std::runtime_error::~runtime_error()>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#8  0x00005555557e1917 in string_diff (last="<think>Okay, the user asked for the weather in Paris, France. I called the get_weather function with the location set to \"Paris, France\" and units as \"metric\". The tool response came back with the wea"..., 
    current="<think>Okay, the user asked for the weather in Paris, France. I called the get_weather function with the location set to \"Paris, France\" and units as \"metric\". The tool response came back with the wea"...) at /home/austin/.bin/cpp/llama.cpp/common/chat.cpp:34
#9  0x00005555557e2834 in common_chat_msg_diff::compute_diffs (previous_msg=..., new_msg=...) at /home/austin/.bin/cpp/llama.cpp/common/chat.cpp:86
#10 0x0000555555643e54 in server_slot::update_chat_msg (this=0x5555565291c0, diffs=std::vector of length 0, capacity 0) at /home/austin/.bin/cpp/llama.cpp/tools/server/server.cpp:1423
#11 0x000055555564ea70 in server_context::send_partial_response (this=0x7fffffffc0c0, slot=..., tkn=...) at /home/austin/.bin/cpp/llama.cpp/tools/server/server.cpp:2457
#12 0x000055555564d700 in server_context::process_token (this=0x7fffffffc0c0, result=..., slot=...) at /home/austin/.bin/cpp/llama.cpp/tools/server/server.cpp:2255
#13 0x0000555555654c17 in server_context::update_slots (this=0x7fffffffc0c0) at /home/austin/.bin/cpp/llama.cpp/tools/server/server.cpp:3426
#14 0x00005555555fc539 in operator() (__closure=0x7fffffffd680) at /home/austin/.bin/cpp/llama.cpp/tools/server/server.cpp:4834
#15 0x000055555560a1c4 in std::__invoke_impl<void, main(int, char**)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/15.1.1/bits/invoke.h:63
#16 0x000055555560840e in std::__invoke_r<void, main(int, char**)::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/15.1.1/bits/invoke.h:113
#17 0x00005555556044de in std::_Function_handler<void(), main(int, char**)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/15.1.1/bits/std_function.h:292
#18 0x000055555565b60c in std::function<void()>::operator() (this=0x7fffffffd680) at /usr/include/c++/15.1.1/bits/std_function.h:593
#19 0x000055555564675f in server_queue::start_loop (this=0x7fffffffd560) at /home/austin/.bin/cpp/llama.cpp/tools/server/server.cpp:1690
#20 0x00005555555fed7e in main (argc=14, argv=0x7fffffffd918) at /home/austin/.bin/cpp/llama.cpp/tools/server/server.cpp:4859
(gdb) Quit
(gdb) quit
A debugging session is active.

	Inferior 1 [process 70237] will be killed.

Quit anyway? (y or n) y
```

</details>

Below is the output after a strict and proper reconstruction occurs from the streamed logits during SSE streaming.

<details><summary>Successful execution</summary>

```sh
16:21:39 | /mnt/valerie/public/agent
(.venv) git:(main | Δ) λ python -m agent
<user> Hello! My name is Austin. What is your name?
Thinking:
Okay, the user said, "Hello! My name is Austin. What is your name?" Let me think about how to respond.

First, the user introduced themselves as Austin and is asking my name. I need to provide a friendly response. Since my name is Qwen, I should mention that. But I should make it sound natural and not too robotic.

Maybe start with a greeting, then state my name. Also, offer assistance. Let me check if there's any function I need to call here. The tools provided include get_weather, but the user isn't asking about weather. They're just asking for my name. So no function call is needed here. Just a simple response.
Completion:
I'm Qwen! 👋 I'm here to help with any questions or tasks you have. How can I assist you today?
<user> What is the weather like in Paris, France today?
Thinking:
Okay, the user is asking about the weather in Paris, France today. Let me check the tools available. There's a function called get_weather that retrieves current weather for a location. The parameters required are location and units, with units having an enum of metric or uscs, defaulting to metric.

So, I need to call get_weather with location set to "Paris, France" and units as "metric" since the user didn't specify. The function will return the current weather data. Then I can present that information to the user in a friendly manner. Let me make sure the location is correctly formatted as "Paris, France" and the units are set to metric. No other parameters are needed. Alright, time to generate the tool call.
Completion:
Tool Call:
get_weather({'location': 'Paris, France', 'units': 'metric'}): Paris, France 22:22:31+0200 06:01:51 21:33:35 Light rain ↓11km/h +11°C
Thinking:
Okay, the user asked about the weather in Paris, France. I called the get_weather function with the location and units set to metric. The tool response came back with the weather data. Now I need to present this information in a user-friendly way.

Let me parse the tool_response. The time is 22:22:31+0200, which is 10:22 PM local time. The temperature is +11°C, and there's light rain with a wind speed of 11 km/h. The unit system is metric, so that's consistent. 

I should mention the current time, temperature, weather condition, and wind speed. Also, note the light rain and the direction (↓11km/h). Make sure to keep it concise but informative. Avoid technical jargon. Maybe start with the current time, then temperature, then weather description, and wind details. End with a friendly note asking if they need more info. 

Check for any errors in the data. The temperature is +11°C, which is a bit cool, but that's the data provided. The light rain is mentioned, so mention that. Wind speed is 11 km/h, which is a gentle breeze. 

Alright, putting it all together in a clear sentence structure.
Completion:
The current weather in Paris, France is **11°C** with **light rain**. The wind is blowing at **11 km/h** from the south (↓). It's a mild day with comfortable temperatures. Would you like to check another location? 😊
<user> 
```

**NOTE:** The trailing `<user>` indicates the program is waiting for user input to occur. If I attempt to continue with execution, the server still crashes with similar results and outputs.

```sh
<user> What should I wear for weather like this?
Thinking:
Okay, the user just asked, "What should I wear for weather like this?" After I provided the weather details for Paris, they're now asking about appropriate clo
thing based on the current conditions.

First, I need to recall the weather data from the previous response. The temperature is 11°C, there's light rain, and the wind is 11 km/h from the south. So, t
he weather is cool with light precipitation.

Now, the user wants to know what to wear. Let me think about typical clothing for such conditions. Since it's 11°C, which is a bit cold, they might need a ligh
t jacket or a sweater. Light rain means they should have waterproof gear. The wind speed is 11 km/h, so a windbreaker or a jacket with a hood could be useful.

I should mention layers, like a long-sleeve shirt and a jacket. Also, waterproof clothing like a raincoat or umbrella. Maybe suggest breathable fabrics to stay
 comfortable. Also, a hat and gloves if the wind is a factor. 

I should structure the answer clearly, starting with the main items, then accessories. Make sure to mention the temperature and weather conditions. Avoid any t
echnical terms. Keep it friendly and helpful. 

Check if there's any specific advice for the wind direction. The wind is from the south, so maybe suggest a wind barrier. But since the user didn't specify, ke
ep it general. 

Also, maybe add a note about checking the weather again if they're going out. But since they already asked about the current weather, maybe not necessary. 

Alright, time to put it all together in a coherent response.
Completion:
For the current weather in Paris (11°C with light rain andTraceback (most recent call last):
  File "/mnt/valerie/public/agent/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/mnt/valerie/public/agent/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 127, in __iter__
    for part in self._httpcore_stream:
                ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/valerie/public/agent/.venv/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 407, in __iter__
    raise exc from None
  File "/mnt/valerie/public/agent/.venv/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 403, in __iter__
    for part in self._stream:
                ^^^^^^^^^^^^
  File "/mnt/valerie/public/agent/.venv/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 342, in __iter__
    raise exc
  File "/mnt/valerie/public/agent/.venv/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 334, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/valerie/public/agent/.venv/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 203, in _receive_response_body
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/valerie/public/agent/.venv/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 213, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/austin/.local/share/python/3.12.8/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/mnt/valerie/public/agent/.venv/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:
# ...omitting remaining output for brevity
```

</details>

I'm still digging into this, but felt this might be worth sharing. Maybe someone else has run into similar issues and understands what's wrong; if it's me and what I'm doing, if it's just how the server is set up at the moment, or if it's just due to the instability of this PR.

I'll be looking into this in more detail.

**Comment by pwilkin** [comment]
@teleprint-me It seems like that's exactly the same error that I got above.

**Comment by ochafik** [comment]
@teleprint-me, @pwilkin, thanks for the feedback! Would you be able to share a curl command similar to [the one in the docs](https://github.com/ggml-org/llama.cpp/blob/master/docs/function-calling.md) + `--verbose` output log of llama-server? Trying to repro :-)

**Review by ericcurtin — APPROVED** [review]
I'd be a fan of merging this, even if it was imperfect, so the community can build upon it

**Comment by ochafik** [comment]
Thanks all for the feedback so far! (and sorry for the *ahem* lil breakages & unpolished edges 😅)

As I have only 10h left of copyright ownership to push fixes 🙈, here's a recap of the PRs out for review (cc/ @ngxson @ggerganov ):

- https://github.com/ggml-org/llama.cpp/pull/13785
- https://github.com/ggml-org/llama.cpp/pull/13786: fixes lots of the diffs crashes, especially when thinking is involved or when there's a mix of content & tool calls (or partial matches of tool call starts)
- https://github.com/ggml-org/llama.cpp/pull/13800: fixes delta format (return `tool_call.function.name` as deltas, put `id` at right place, output `type`)

**Comment by teleprint-me** [comment]
Just as an FYI, there's a minor regression with predicted logits. 

```sh
20:13:18 | /mnt/valerie/public/agent
(.venv) git:(main | Δ) λ python -m agent.openai.stream
{'type': 'role', 'value': 'assistant'}
{'type': 'reasoning.open', 'value': '<think>Okay'}
{'type': 'content', 'value': ','}
{'type': 'content', 'value': ' the'}
```

Previously, in earlier commits, before this PR was merged, `<think>` and `Okay` were in fact separate tokens.

This is okay here in a controlled fashion, but I suspect this might creep up in unsuspected ways further down the line.

<details><summary>Updated simple example</summary>

```py
# agent.openai.stream
import json
import os
from pprint import pprint
from typing import Any, Dict, Generator, Optional

import dotenv
from openai import OpenAI

from agent.tools import tools


class GPTRequest:
    def __init__(self, base_url: str = None, api_key: str = None):
        self.client = self._connect(base_url, api_key)

    def _connect(self, base_url: str = None, api_key: str = None) -> OpenAI:
        if not base_url or not api_key:
            dotenv.load_dotenv(".env")

        if not base_url:
            base_url = os.getenv("OPENAI_BASE_URL", "")

        if not api_key:
            api_key = os.getenv("OPENAI_API_KEY", "")

        if not api_key:
            raise ValueError("EnvironmentError: OPENAI_API_KEY not set in .env")

        # Setup default base URL if using local mode
        if api_key == "sk-no-key-required" and not base_url:
            base_url = "http://localhost:8080/v1"

        return OpenAI(api_key=api_key, base_url=base_url)

    def _classify_reasoning(self, text: str) -> Optional[str]:
        if "<think>" in text:
            return "reasoning.open"
        if "</think>" in text:
            return "reasoning.close"
        return None

    def _classify_tool(self, tool_call, buffer, args_fragments):
        fn = tool_call.function
        if fn.name:
            buffer["name"] = fn.name
        if fn.arguments:
            args_fragments.append(fn.arguments)
        if fn.arguments and fn.arguments.strip().endswith("}"):
            try:
                args = "".join(args_fragments)
                buffer["arguments"] = json.loads(args)
                args_fragments.clear()
                return {"type": "tool_call", "value": buffer.copy()}
            except json.JSONDecodeError:
                # Wait for more fragments
                pass
        return None

    def stream(self, **kwargs) -> Generator[Dict[str, Any], None, None]:
        response = self.client.chat.completions.create(**kwargs)
        tool_buffer = {}
        args_fragments = []

        for chunk in response:
            delta = chunk.choices[0].delta

            if hasattr(delta, "role") and delta.role:
                yield {"type": "role", "value": delta.role}

            if hasattr(delta, "content") and delta.content:
                reasoning_type = self._classify_reasoning(delta.content)
                yield {"type": reasoning_type or "content", "value": delta.content}

            if hasattr(delta, "tool_calls") and delta.tool_calls:
                for tool_call in delta.tool_calls:
                    result = self._classify_tool(tool_call, tool_buffer, args_fragments)
                    if result:
                        yield result

            if hasattr(delta, "refusal") and delta.refusal:
                yield {"type": "refusal", "value": delta.refusal.model_dump()}

            if hasattr(delta, "reasoning") and delta.reasoning:  # Future-compatible
                yield {"type": "reasoning", "value": delta.reasoning.model_dump()}


def main():
    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "What is the weather like in Paris, France?"},
    ]

    request = GPTRequest()
    generator = request.stream(
        model="gpt-3.5-turbo",  # Llama.Cpp expects this model definition
        messages=messages,
        max_tokens=-1,  # Allow the to model to naturally stop on its own
        stream=True,
        temperature=0.8,
        tools=tools,
    )
    for obj in generator:
        pprint(obj)


if __name__ == "__main__":
    main()
```

</details>

My current suspicion is to assume that it's an issue with token healing which I have to handle upstream because of this issue. It's only obvious here because it shows up right away in a predictable and deterministic fashion.

**Comment by julien-c** [comment]
Thanks so much for pushing this over the finish line @ochafik!

**Comment by strawberrymelonpanda** [comment]
> As I have only 10h left of copyright ownership to push fixes 🙈

Minja is open-source, right?  Do you need copyright ownership?
Curious what this means for the future if Llama.cpp will keep using minja.

**Comment by ochafik** [comment]
> > As I have only 10h left of copyright ownership to push fixes 🙈
> 
> Minja is open-source, right? Do you need copyright ownership? Curious what this means for the future if Llama.cpp will keep using minja.

@strawberrymelonpanda I hope to be able to clarify soon w/ my new employer whether I can contribute to minja, to a fork of it or... not at all (in any case, I've added a couple of extra maintainers from Google to the google/minja repo, and there's always the option for llama.cpp to just fork it under ggml-org, etc)

**Comment by ericcurtin** [comment]
Do maintainers in Google namespace have to be Google employees, if yes, might be a decent reason to move to ggml-org namespace
