### PR TITLE
cmake: fix paths for vulkan shaders compilation on Windows

### LINKED ISSUE #8562: Bug: Vulkan build no longer working with MSVC cmake on windows
### What happened?

When trying to build the lastest version of the Vulkan backend, the shader compilation fails.

I suspect commit 17eb6aa8a992cda37ee65cf848d9289bd6cad860 to have introduced the issue, but more testing is required to know for sure.

### Name and Version

commit: 3807c3de04cde853418033c95e96642876545f3e
cmake flags:  `-DBUILD_SHARED_LIBS=OFF -DGGML_VULKAN=1 -G "Visual Studio 17 2022" -A x64`
MSBuild version: `17.9.8+b34f75857`

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Version MSBuild 17.9.8+b34f75857 pour .NET Framework

[...]

Generate vulkan shaders
  ggml_vulkan: Generating and compiling shaders to SPIR-V
  cannot compile mul_mat_vec_id_f32_f32

  C:/VulkanSDK/1.3.275.0/Bin/glslc.exe -fshader-stage=compute --target-env=vulkan1.2 -O C:/llama.cpp/ggml/src/vulkan-shaders\mul_mat_vec.comp -o C:/llama.cpp/build/ggml/src/vulkan-shaders.spv\mul_mat_vec_id
  _f32_f32.spv -DB_TYPE=float -DDATA_A_F32=1 -DD_TYPE=float -DFLOAT_TYPE=float -DMUL_MAT_ID=1

glslc : error : linking multiple files is not supported yet. Use -c to compile files individually. [C:\llama.cpp\build\ggml\src\ggml.vcxproj]


  cannot compile cannot compile mul_mat_vec_q4_0_f32_f32mul_mat_vec_q4_0_f16_f32

  C:/VulkanSDK/1.3.275.0/Bin/glslc.exe -fshader-stage=compute --target-env=vulkan1.2 -O C:/llama.cpp/ggml/src/vulkan-shaders\mul_mat_vec.comp -o C:/llama.cpp/build/ggml/src/vulkan-shaders.spv\mul_mat_vec_q4
  _0_f32_f32.spv -DB_TYPE=float -DDATA_A_Q4_0=1 -DD_TYPE=float -DFLOAT_TYPE=float



glslc : error : linking multiple files is not supported yet. Use -c to compile files individually. [C:\llama.cpp\build\ggml\src\ggml.vcxproj]

(this goes on for every op, and build crashes with code -1)
```

### PR DESCRIPTION
**Pull request by stduhpf**
Fixes https://github.com/ggerganov/llama.cpp/issues/8562

I hope it's not breaking it for others.

- [x] I have read the [contributing guidelines](https://github.com/ggerganov/llama.cpp/blob/master/CONTRIBUTING.md)
- Self-reported review complexity:
  - [x] Low
  - [ ] Medium
  - [ ] High

### CODE REVIEW

**Review by ggerganov — APPROVED** [review]

File: ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp [hunk 1]
```diff
@@ -197,7 +193,11 @@ void string_to_spv(const std::string& _name, const std::string& in_fname, const
     std::string out_fname = join_paths(output_dir, name + ".spv");
     std::string in_path = join_paths(input_dir, in_fname);
 
-    std::vector<std::string> cmd = {GLSLC, "-fshader-stage=compute", "--target-env=vulkan1.2", "-O", in_path, "-o", out_fname};
+    #ifdef _WIN32
```
Comment (AndreasKunar) [inline ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp:196]: For compatibility with Windows x86, x64 and arm64, should it not better be "#if defined(_WIN32) || defined(_WIN64) || defined(_M_ARM64)"?

File: ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp [hunk 2]
```diff
@@ -434,10 +434,16 @@ void write_output_files() {
 
     for (const auto& pair : shader_fnames) {
         const std::string& name = pair.first;
-        const std::string& path = pair.second;
+        #ifdef _WIN32
```
Comment (AndreasKunar) [inline ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp:437]: Same as above.  "#if defined(_WIN32) || defined(_WIN64) || defined(_M_ARM64)"?

**Comment by mstephenson6** [comment]
Just got successful Vulkan builds with MSBuild/cl and ninja/clang on Windows 11 x64 with this PR, thank you!

File: ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp (hunk 1 above)
Comment (0cc4m) [reply ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp:196]: According to the [documentation](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros), `_WIN32` should be enough:

> `_WIN32` Defined as 1 when the compilation target is 32-bit ARM, 64-bit ARM, x86, or x64. Otherwise, undefined.

Comment (AndreasKunar) [reply ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp:196]: @ all - its embarrassing, I'm totally sorry, @0cc4m is right. Idiot me did not find this documentation and I wrote a stupid/wrong test program (Ok, it at least worked correctly for detecting clang vs. MSVC on WoA).

**Review by 0cc4m — APPROVED** [review]
Looks good to me. No issues on Linux. I can't test Windows, but other commenters confirmed that it works there. Thank you.

**Comment by Donwulff** [comment]
Seconding this, not fixed, from my limited perspective into the code it's bit perplexing because the build seems to be fixed at -std=c++11 while std::replace is c++20 onwards, how is this supposed to work anywhere?

If you fix this issue, you still need to copy most of Vulkan SDK's headers into the build tree, not instructed on the Vulkan backend documentation, and you're still missing some functions/library too. But I can't tell what all of this is necessary for, so for w64devkit it currently seems necessary to just roll back these changes.

**Comment by 0cc4m** [comment]
> Seconding this, not fixed, from my limited perspective into the code it's bit perplexing because the build seems to be fixed at -std=c++11 while std::replace is c++20 onwards, how is this supposed to work anywhere?

I agree the way it is shown by default in [the documentation](https://en.cppreference.com/w/cpp/algorithm/replace) makes it look like `std::replace` is available since C++17 or C++20, but if you set the C++ revision at the top of the page you can see that `std::replace` is available since C++98. That's not the issue.

Maybe the problem for w64Devkit is just that `#include <algorithm>` is missing in the `#ifdef _WIN32` include part at the top? Can you try that?

**Comment by MaggotHATE** [comment]
> #include <algorithm>

Yes, it seems to be the case https://github.com/ggerganov/llama.cpp/pull/8880
Although I've missed your comment and didn't put it under `#ifdef _WIN32` - is it critical?

**Comment by 0cc4m** [comment]
> > #include
> 
> Yes, it seems to be the case #8880 Although I've missed your comment and didn't put it under `#ifdef _WIN32` - is it critical?

Not critical, but the algorithm part is in a Windows-only section.
