### PR TITLE
Always show message actions for mobile UI + improvements for user message sizing

### LINKED ISSUE #16061: Misc. bug: Mobile web ui hides Copy/Edit/Delete buttons
### Name and Version

```
version: 6500 (a7a98e0f)
built with Apple clang version 17.0.0 (clang-1700.3.19.1) for arm64-apple-darwin25.0.0
```

The buttons were hidden under `tooltip-trigger` with a default `data-state` of `closed`; because this only becomes visible on `hover`, you can no longer click these buttons on mobile.

### Operating systems

Other? (Please let us know in description)

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell

```

### Problem description & steps to reproduce

- Run llama-server
- View the web ui on a mobile device 

### First Bad Commit

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by allozaur**
Closes #16061

- Improves showing message actions on mobile devices
- Improves user message sizing based on the single/multi-line detection
- Additionally improves scripts in `tools/server/webui`
  - Adds cleanup script
  - Improves git hooks installation script
  - Improves dev server script

### CODE REVIEW

File: tools/server/webui/src/lib/components/app/chat/ChatMessages/ChatMessageUser.svelte [hunk 1]
```diff
@@ -52,11 +52,32 @@
 		onShowDeleteDialogChange,
 		textareaElement = $bindable()
 	}: Props = $props();
+
+	let innerWidth = $state(0);
+	let isMultiline = $state(false);
+	let messageElement: HTMLElement | undefined = $state();
+
+	$effect(() => {
+		if (messageElement && message.content.trim() && innerWidth > 0) {
```
Comment (ngxson) [inline tools/server/webui/src/lib/components/app/chat/ChatMessages/ChatMessageUser.svelte]: will doing some processing each time input content changed impacts on performance? in the past, some users complained about input field being very laggy on certain low-end systems

especially when `getComputedStyle` is not really good for performance. should we do this with css trick instead?

Comment (allozaur) [reply tools/server/webui/src/lib/components/app/chat/ChatMessages/ChatMessageUser.svelte]: That's a valid point! I will re-think that 😉

Comment (ngxson) [reply tools/server/webui/src/lib/components/app/chat/ChatMessages/ChatMessageUser.svelte]: another approach is that we can make an utility function like this:

```
wrappedFn = performanceAwareWrapper(fn0, fn1, deadlineMs);
```

Whenever wrappedFn is called, we call fn0 and measure the time it takes from start to finish. If the time is higher than deadlineMs, the next time wrappedFn is called, we always fallback to fn1

So for example, fn0 can be the less-performant function and the fn1 can be the more performant one

Comment (ngxson) [reply tools/server/webui/src/lib/components/app/chat/ChatMessages/ChatMessageUser.svelte]: I've never tested the case where the browser is slow (I'm using firefox which rarely has performance issues compared to chrome). But if you wanna try, you can also spin up a linux vm with less CPU cores (like just 1 or 2 cores)

**Comment by ddh0** [comment]
I've just tested this and it works great, it makes the UI fully functional on mobile for me (whereas I'm unable to re-generate, edit, or copy messages on mobile on `master`.) I'd say ship it!

User agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.0 Mobile/15E148 Safari/604.1`

File: tools/server/webui/src/lib/components/app/chat/ChatMessages/ChatMessageUser.svelte (hunk 1 above)
Comment (allozaur) [reply tools/server/webui/src/lib/components/app/chat/ChatMessages/ChatMessageUser.svelte]: @ngxson I've switched to using `ResizeObserver` which performance-wise is a much better way to handle this ba0ae76c23141c7d4dbd82a550295e35a78666a0

**Review by ggerganov — APPROVED** [review]
