### PR TITLE
main : Fix Ctrl+D/newline handling

### LINKED ISSUE #12949: Misc. bug: Ctrl+D no longer works properly
### Name and Version

$./llama-cli --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon RX 6650 XT, gfx1030 (0x1030), VMM: no, Wave Size: 32
version: 5097 (fe5b78c8)
built with cc (Ubuntu 14.2.0-4ubuntu2) 14.2.0 for x86_64-linux-gnu

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-cli

### Command line

```shell
llama-cli -m ~/gemma-3-4b-it-Q4_K_M.gguf
llama-cli -m ~/gemma-3-4b-it-Q4_K_M.gguf </dev/null
```

### Problem description & steps to reproduce

The multiline feature caused #491 to regress. I expect Ctrl+D to behave exactly like it does in bash. Instead, it's as if it was Enter, and Ctrl+C doesn't work when it is held down by `/dev/null` either.

### First Bad Commit

Perhaps 41654efea879bbdf4fd794e13335929d4cf0eb90

### Relevant log output

```shell
...
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to the AI.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.
 - Not using system message. To change it, set a different value via -sys PROMPT


> Hi
Hi there! How’s your day going so far? Is there anything I can help you with today? 😊 

Do you want to:

*   Chat about something?
*   Get some information?
*   Brainstorm ideas?

> *   Play a game?

> 

> 

> 

> 

> 
llama_perf_sampler_print:    sampling time =       0.16 ms /     1 runs   (    0.16 ms per token,  6172.84 tokens per second)
llama_perf_context_print:        load time =     793.98 ms
llama_perf_context_print: prompt eval time =     185.32 ms /    10 tokens (   18.53 ms per token,    53.96 tokens per second)
llama_perf_context_print:        eval time =    4524.32 ms /    62 runs   (   72.97 ms per token,    13.70 tokens per second)
llama_perf_context_print:       total time =   13648.78 ms /    72 tokens
Interrupted by user
...
== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to the AI.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.
 - Not using system message. To change it, set a different value via -sys PROMPT


> The 2023 NFL Draft is less than two weeks away, and the anticipation^C
>  is building^C
> . Here’^C
> s a breakdown^C
>  of the top^C
>  storylines, key^C
>  players, and^C
>  potential surprises heading into^C
>  the event^C
> :

**^C
> 1.^C
>  The Quarterback^C
>  Carousel:**^C
> 

* **^C
> The Big Three^C
> :** Caleb Williams^C
>  (USC),^\Quit (core dumped)
```

### PR DESCRIPTION
**Pull request by danielzgtg**
This restores the behavior from #491. This does not affect Ctrl+D's ability to terminate --multiline-input lines (#1040).

This also actually implements #587: "If the user wants the text to end in a newline, this should be accomplished by explicitly adding a newline by using \ followed by return, then returning control by pressing return again."

Fixes #12949

### CODE REVIEW

File: examples/main/main.cpp [hunk 1]
```diff
@@ -865,9 +865,20 @@ int main(int argc, char ** argv) {
                 console::set_display(console::reset);
                 display = true;
 
-                // Add tokens to embd only if the input buffer is non-empty
-                // Entering a empty line lets the user pass control back
-                if (buffer.length() > 1) {
+                if (!buffer.length()) { // Ctrl+D on empty line exits
```
Comment (ngxson) [inline examples/main/main.cpp:868]:
```suggestion
                if (buffer.empty()) { // Ctrl+D on empty line exits
```

Does this also work if user hit enter (empty line)?

File: examples/main/main.cpp [hunk 2]
```diff
@@ -865,9 +865,20 @@ int main(int argc, char ** argv) {
...
+                    LOG("EOF by user\n");
+                    break;
+                }
+                if (buffer[buffer.length() - 1] == '\n') {
```
Comment (ngxson) [inline examples/main/main.cpp:872]:
```suggestion
                if (buffer.back() == '\n') {
```

File: examples/main/main.cpp [hunk 3]
```diff
@@ -865,9 +865,20 @@ int main(int argc, char ** argv) {
...
+                    // Implement #587:
+                    // If the user wants the text to end in a newline,
+                    // this should be accomplished by explicitly adding a newline by using \ followed by return,
+                    // then returning control by pressing return again.
+                    buffer.pop_back();
+                }
+                if (!buffer.length()) { // Enter key on empty line lets the user pass control back
```
Comment (ngxson) [inline examples/main/main.cpp:879]:
```suggestion
                if (buffer.empty()) { // Enter key on empty line lets the user pass control back
```

File: examples/main/main.cpp (hunk 2 above)
Comment (ngxson) [inline examples/main/main.cpp:872]:
```suggestion
                }

                if (buffer[buffer.length() - 1] == '\n') {
```

Always add an empty line between 2 blocks of `if {}`

File: examples/main/main.cpp (hunk 1 above)
Comment (danielzgtg) [reply examples/main/main.cpp]: The existing behavior of instead letting "the user pass control back" works. I preserved the behavior from #571 on line 881 below. Enter and Ctrl+D should, and now do, do different things. At this line, they are represented in memory as `buffer == "\n"` and `buffer == ""` respectively.

**Review by ngxson — APPROVED** [review]
