### PR TITLE
Validate special token ids are in range when loading GGUF model

### LINKED ISSUE #3634: Special token ids aren't validated when loading a model
When loading the GGUF model, special token ids aren't validated to be in range, this can lead to index errors later on when they're used to looked up tokens, etc.

Here's an example: https://huggingface.co/Undi95/Mistral-11B-OmniMix/blob/main/config.json

We have 

```json
  "eos_token_id": 32000,
```

However the model's vocab size is 32,000 so that is out of bounds. Currently trying to load that model just crashes.

### PR DESCRIPTION
**Pull request by KerfuffleV2**
This pull adds validation for special token ids that out of range. Invalid ones will be ignored and a warning message is display when loading the model. This model can reproduce the issue: https://huggingface.co/Undi95/Mistral-11B-OmniMix-bf16-GGUF (see issue for HF version with metadata).

I also included a small optimization for `llama_byte_to_token` SPM mode - `snprintf` is kind of overkill there since converting a `uint8_t` to hex is so trivial. Also slightly more friendly behavior if a BPM model is missing newline - assert rather than blindly dereferencing the tokenize result.

Of course, we shouldn't end up in a situation where the GGUF file has invalid token ids. I looked at `convert.py` and the GGUF Python side. The problem is that the special vocab handling stuff doesn't have access to other information like the model's vocab size so it can't validate the token ids.

I updated `SpecialVocab` to take an optional `n_vocab` argument so it can validate that the ids are in range (in-repo conversion scripts also updated to pass this). Refactored to make the logic a bit clearer as well.

Closes #3634

### CODE REVIEW

**Comment by staviq** [comment]
Is the test workflow borked ?

```
main : failed test:    ' ('
main : detokenized to: ' (' instead of ' ('
main : expected tokens:  29871,    313, 
main : got tokens:       29871,    313, 
```

**Comment by KerfuffleV2** [comment]
> Is the test workflow borked ?

@staviq I was thinking that, but it was actually me that's borked. :(

Didn't realize the get macro wouldn't do anything if it didn't find the key, so I was setting all the special ids to -1. They don't get printed out there I guess so the error message is confusing when there's an issue with special tokens.

File: llama.cpp [hunk 1]
```diff
@@ -5986,11 +6003,10 @@ static uint8_t llama_token_to_byte(const llama_vocab& vocab, llama_token id) {
 }
 
 static llama_token llama_byte_to_token(const llama_vocab & vocab, uint8_t ch) {
+    const char * hex = "0123456789ABCDEF";
```
Comment (cebtenzzre) [inline llama.cpp:6006]: It shouldn't really matter, but this can be made `static`.

File: llama.cpp [hunk 2]
```diff
@@ -5986,11 +6003,10 @@ static uint8_t llama_token_to_byte(const llama_vocab& vocab, llama_token id) {
...
     switch (llama_vocab_get_type(vocab)) {
     case LLAMA_VOCAB_TYPE_SPM: {
-        char buf[7];
-        int result = snprintf(buf, sizeof(buf), "<0x%02X>", ch);
-        GGML_ASSERT(0 <= result && result < 7);
+        const char buf[7] = { '<', '0', 'x', hex[ch >> 4], hex[ch & 15], '>', 0 };
```
Comment (cebtenzzre) [inline llama.cpp:6009]: I believe you can just write `buf[]` here since the size is implied by the initializer.

File: llama.cpp [hunk 3]
```diff
@@ -2232,15 +2232,32 @@ static void llm_load_vocab(
     if (vocab.type == LLAMA_VOCAB_TYPE_SPM) {
         vocab.linefeed_id = llama_byte_to_token(vocab, '\n');
     } else {
-        vocab.linefeed_id = llama_tokenize_internal(vocab, "\u010A", false)[0];
+        const std::vector<int> ids = llama_tokenize_internal(vocab, "\u010A", false);
+        GGML_ASSERT(!ids.empty() && "model vocab missing newline token");
```
Comment (cebtenzzre) [inline llama.cpp:2236]: Range checking like this is basically what `.at(0)` is for. But I suppose it doesn't hurt to have an explicit error message.

File: llama.cpp [hunk 4]
```diff
@@ -2232,15 +2232,32 @@ static void llm_load_vocab(
...
     }
 
     // special tokens
-    GGUF_GET_KEY(ctx, vocab.special_bos_id, gguf_get_val_u32, GGUF_TYPE_UINT32, false, kv(LLM_KV_TOKENIZER_BOS_ID));
-    GGUF_GET_KEY(ctx, vocab.special_eos_id, gguf_get_val_u32, GGUF_TYPE_UINT32, false, kv(LLM_KV_TOKENIZER_EOS_ID));
-    GGUF_GET_KEY(ctx, vocab.special_unk_id, gguf_get_val_u32, GGUF_TYPE_UINT32, false, kv(LLM_KV_TOKENIZER_UNK_ID));
-    GGUF_GET_KEY(ctx, vocab.special_sep_id, gguf_get_val_u32, GGUF_TYPE_UINT32, false, kv(LLM_KV_TOKENIZER_SEP_ID));
-    GGUF_GET_KEY(ctx, vocab.special_pad_id, gguf_get_val_u32, GGUF_TYPE_UINT32, false, kv(LLM_KV_TOKENIZER_PAD_ID));
+    {
+        const std::vector<std::tuple<enum llm_kv, int32_t &>> special_token_types = {
```
Comment (cebtenzzre) [inline llama.cpp:2242]: Instead of a two-tuple, why not std::pair?

File: llama.cpp [hunk 5]
```diff
@@ -2232,15 +2232,32 @@ static void llm_load_vocab(
...
+            { LLM_KV_TOKENIZER_BOS_ID, vocab.special_bos_id },
+            { LLM_KV_TOKENIZER_EOS_ID, vocab.special_eos_id },
+            { LLM_KV_TOKENIZER_UNK_ID, vocab.special_unk_id },
+            { LLM_KV_TOKENIZER_SEP_ID, vocab.special_sep_id },
+            { LLM_KV_TOKENIZER_PAD_ID, vocab.special_pad_id },
+        };
+        for (const auto & it : special_token_types ) {
+            const std::string key = kv(std::get<0>(it));
+            int32_t & id = std::get<1>(it), old_id = id;
```
Comment (cebtenzzre) [inline llama.cpp:2251]: std::tie is handy for unpacking tuples and pairs in a clearer way.

File: llama.cpp [hunk 6]
```diff
@@ -2232,15 +2232,32 @@ static void llm_load_vocab(
...
+
+            GGUF_GET_KEY(ctx, id, gguf_get_val_u32, GGUF_TYPE_UINT32, false, key);
+            if (id != -1 && (id < 0 || size_t(id) >= vocab.id_to_token.size())) {
```
Comment (cebtenzzre) [inline llama.cpp:2254]: Would it be clearer to write this as `id < -1 || size_t(id) >= vocab.id_to_token.size()`?

File: llama.cpp (hunk 4 above)
Comment (KerfuffleV2) [reply llama.cpp:2242]: No reason why not, I just didn't know about it. :)

File: llama.cpp (hunk 2 above)
Comment (KerfuffleV2) [reply llama.cpp:6009]: I thought there were some compilers that couldn't handle it, but I might be mistaken. I think leaving the single character here is worth it though just to be more explicit. I.E. if someone messes with that code in the future and accidentally removes the `0`, it should produce a compiler error. Not a likely scenario, but still...

File: llama.cpp (hunk 6 above)
Comment (KerfuffleV2) [reply llama.cpp:2254]: I had that same thought and then I realized it can lead to converting `-1` to `size_t`. The way the boolean short circuiting is set up is to avoid that, even though it's a little more complicated.

File: llama.cpp (hunk 5 above)
Comment (cebtenzzre) [reply llama.cpp:2251]: Unfortunately, you're looking for a structured binding declaration, which was only made available six years ago in C++17.

File: llama.cpp (hunk 6 above)
Comment (cebtenzzre) [reply llama.cpp:2254]: Then `id < -1 || id >= ptrdiff_t(vocab.id_to_token.size())`?

File: llama.cpp (hunk 2 above)
Comment (cebtenzzre) [reply llama.cpp:6009]: It won't produce a compiler error, it will just silently add zero bytes to the end of the array. Array and struct initializers are not required to initialize all elements.

File: llama.cpp (hunk 6 above)
Comment (KerfuffleV2) [reply llama.cpp:2254]: What I meant is if you have `id < -1 || size_t(id) >= x` the `id < -1` doesn't stop the expression from evaluating when `id == -1`. So then you do `size_t(-1) >= x`. Isn't `size_t(-1)` going to be a huge number since `size_t` is unsigned?

File: llama.cpp (hunk 5 above)
Comment (KerfuffleV2) [reply llama.cpp:2251]: Yeah, I actually looked it up and tried to find a better way. Since I'm not allowed to use C++17 here as far as I know, I went with the current version. There are definitely cases where `std::tie` is better though, just not this one.

File: llama.cpp (hunk 6 above)
Comment (cebtenzzre) [reply llama.cpp:2254]: Did you see my comment here? https://github.com/ggerganov/llama.cpp/pull/3635#discussion_r1360781711

Comment (KerfuffleV2) [reply llama.cpp:2254]: > Did you see my comment here?

Sort-of. I was still stuck on what you originally said, also I didn't know the properties of `ptrdiff_t` off the time of my head. It doesn't look like that type is used in the project source at all (except for some 3rd party stuff like a JSON lib).

Personally, I'd say the version with `ptrdiff_t` would be harder for me to understand than the original version just because all the information is there to think through the boolean logic but if you don't know how `ptrdiff_t` works you don't know what's correct.

I was thinking there may be a simpler solution, something like: 

```c++
if (id < -1 || size_t(id + 1) > vocab.id_to_token.size())
```

The first part excludes anything below `-1`, then since we add `1`, the valid values are between 0 and the size of the vector inclusive now. Pretty simple, hopefully not too cute/tricky. What do you think?

Comment (cebtenzzre) [reply llama.cpp:2254]: ptrdiff_t is a standard C++ difference type that is large enough to hold the difference between two pointers, positive or negative - it will be 32 bits on 32-bit platforms, 64 bits on 64-bit platforms. It's used in the C++ standard library where a large signed type is needed. There is also intptr_t, although it's not guaranteed to exist.

Maybe I'm just used to python where you can compare two numbers without extra operations to check if they are in range of the data type being used :)

Comment (KerfuffleV2) [reply llama.cpp:2254]: > ptrdiff_t is a standard C++ difference type that is large enough to hold the difference between two pointers, positive or negative

Right, and I could guess a lot of that from the name, but this is C++ so all the semantics aren't necessarily going to be intuitive. That's what makes it harder for me to deal with than the original version. Also, if I'm going to be okay with it going into a 32bit signed type, I could just use `int32_t` like the other stuff.

What about the alternative I suggested?

> Maybe I'm just used to python where you can compare two numbers without extra operations to check if they are in range of the data type being used

In this case, you don't really _have_ to, so this is mostly just to stop compiler warnings by explicitly saying "Yes, I meant to do that". I get your point though. I'm by no means a C++ person, I actually never touched it until I started contributing to this project. I'd rather be writing all this in Rust!

Comment (cebtenzzre) [reply llama.cpp:2254]: > Also, if I'm going to be okay with it going into a 32bit signed type, I could just use `int32_t` like the other stuff.

I like ptrdiff_t because it's a signed type where `sizeof(ptrdiff_t) == sizeof(size_t)` (on any platform I know of), just like ssize_t, which is used on *nix for syscalls like read that may need to return `-1`.

**Comment by KerfuffleV2** [comment]
I've been looking at the Python side and I actually can't replicate how the special EOS token got set to `32000`. (It is fixed in the HF repo now, but even reverting to the previous version where it was set to `32000` doesn't result in creating a GGUF file with EOS set to `32000`.)

Possibly it was converted using an older version. Also, I can't even get it to convert with the existing `added_tokens.json` which looks like:

```json
{
  "</s>": 2,
  "<s>": 1,
  "<unk>": 0
}
```

I don't know if that's wrong, but the convert script expects added tokens to be... well, added. This is redefining tokens that are already in the main vocab, but convert expects the added tokens to come with ids past the normal vocab.

I think the error in `convert.py` is wrong though, it should be `vocab_size` not `len(added_tokens)` like:

```python
        if expected_ids != actual_ids:
            raise Exception(f"Expected added token IDs to be sequential and start at {vocab_size}; got {actual_ids}")
```

    Exception: Expected added token IDs to be sequential and start at 32000; got [0, 1, 2]

vs

    Exception: Expected added token IDs to be sequential and start at 2; got [0, 1, 2]

(Unfortunately I think I'm responsible for that mistake.)

Anyway, I'm not even sure how that model converter even managed to convert the model to GGUF, maybe they hacked `convert.py` to bypass those checks.

**Comment by TheBloke** [comment]
Yeah that error message confused me at first :)  

I believe the issue with added_tokens < vocab_size is fixed by another PR though, so hopefully no need to look at that?  https://github.com/ggerganov/llama.cpp/pull/3585

I pointed out the issue in the base repo to Undi so he fixed it.  As to how it happened in the first place - he may have had different config files at the time at the time he made his GGUFs, or yes it's entirely possible he hacked convert.py! I talked to him about it the other day and he couldn't remember how he made them or what config files he had at the time. And he never noticed the llama.cpp problem because he tested with SillyTavern, which must not have the same bug.

I did GGUFs for that model at the weekend, with the corrected config files (EOS should be `2`, ie `</s>`, not `32000`), so working files are available now.  Even more confusingly, Undi's GGUFs were using the right EOS, ie `2`, so he definitely didn't make them from the config files that were in the repo at the time I first made the models, which listed 32000 as EOS.

It's always an adventure with Undi models 🤣

**Comment by KerfuffleV2** [comment]
> I believe the issue with added_tokens < vocab_size is fixed by another PR though, so hopefully no need to look at that? 

Ah, thanks.

> I did GGUFs for that model at the weekend, with the corrected config files

The thing that confused me is setting

```json
  "eos_token_id": 32000,
```

in `config.json` actually doesn't result in the GGUF file having 32000 as the EOS token id. I can only replicate it if I edit `tokenizer.json` to look like:

```json
{
  "added_tokens": [
    {
      "id": 32000,
      "content": "</s>",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": false,
      "special": true
    }
```

> It's always an adventure with Undi models 

Haha, at least it's a reallly good model for being so small. Looking at the output, I can actually imagine it's coming from one of the weaker 70Bs which really hasn't been the case in the past even with 30Bs.

**Review by ggerganov — APPROVED** [review]
Needs coordination with #3585 and we can merge

**Comment by KerfuffleV2** [comment]
> Needs coordination with https://github.com/ggerganov/llama.cpp/pull/3585 and we can merge

I don't think there should be a conflict, they're kind of doing different stuff. #3585 only touches `convert.py` while my Python changes are in `gguf-py` mainly (and the part that touches `convert.py` is just for calling `SpecialVocab` really).

Pretty sure it wouldn't even cause a merge conflict.

**Comment by KerfuffleV2** [comment]
Is this actually approved or am I missing something about the #3585 coordination issue?
