### PR TITLE
hparams : add n_embd_inp() to support extended embed

### LINKED ISSUE #16908: Eval bug: Control vectors for Qwen3VL fail due to n_embd size
### Name and Version

version: 6906 (0de0a0157)
built with cc (GCC) 15.2.1 20250813 for x86_64-pc-linux-gnu

### Operating systems

Linux

### GGML backends

HIP

### Hardware

probably not relevant

### Models

Qwen3VL

### Problem description & steps to reproduce

Not sure if this is a bug or I am holding it wrong.

Apparently Qwen3VL uses n_embd strangely in llama.cpp. Computing a control vector as I do for other models produces a result with a size of 5120 per layer, but I cannot load it.

Although the hidden_size is 5120 in transformers, llama.cpp asserts unless the vector is 20480. Padding the remaining values, or commenting out the assert results in a different error, GGML_ASSERT(ggml_can_repeat(b, a)).

Reading the merge CL for Qwen3VL, it sounds like n_embd is extended to handle some recurrent stuff. Is a different approach to calculate control vectors necessary here? How should this work for Qwen3VL?

### First Bad Commit

n/a

### Relevant log output

```shell
apply: control vector n_embd does not match model
srv    load_model: failed to load model, '.../path/to/model.gguf'
srv    operator(): operator(): cleaning up before exit...
main: exiting due to model loading error
```

### PR DESCRIPTION
**Pull request by CISC**
Required for proper handling of `Qwen3-VL` DeepStack embeds.

May change more than currently necessary for future use, f.ex. in `llama-context` (or maybe even not enough), please review carefully!

Fixes #16908

### CODE REVIEW

File: include/llama.h [hunk 1]
```diff
@@ -482,6 +482,7 @@ extern "C" {
 
     LLAMA_API int32_t llama_model_n_ctx_train(const struct llama_model * model);
     LLAMA_API int32_t llama_model_n_embd     (const struct llama_model * model);
+    LLAMA_API int32_t llama_model_n_embd_full(const struct llama_model * model);
```
Comment (ngxson) [inline include/llama.h]: Since it's currently only used by mtmd, maybe `llama_model_n_embd_mtmd` could be less confusing?

**Comment by 65a** [comment]
~~The hidden state size (e.g. for embeddings, control vectors) for Qwen3VL under Transformers is 5120, not 20480. It may be relevant here? I don't fully get what is supposed to happen with DeepStack embeds, but they aren't used during inference for normal embeddings, I think?~~

Tested this. It works correctly with a 1d cvector of the size 5120, and for basic MTMD use cases. Thanks!

File: src/llama-hparams.h [hunk 2]
```diff
@@ -40,6 +40,7 @@ struct llama_hparams {
 
     uint32_t n_ctx_train; // context size the model was trained on
     uint32_t n_embd;
+    uint32_t n_embd_full; // main + auxiliary embeds
```
Comment (ggerganov) [inline src/llama-hparams.h]: It would be better to be a const function: `uint32_t n_embd_full() const;` since it does not introduce any new parameters - it's a function of existing parameters.

**Comment by ngxson** [comment]
Looking again at this change, I'm now wondering if we should instead add the reversed notion of `n_embd_full`. What I'm suggesting is `n_embd_internal`

For example, a model can have `n_embd_internal = 2` while `n_embd = n_embd_internal * 4 = 8`

The reason is because this `n_embd_internal` only used internally in cgraph between layers. The input/output vectors always have size of `n_embd`, thus from the outside world perspective, the model always have `n_embd = 8`. In this case, we don't even need to add a new public API.

This reminds about my works on Gemma 3n, where they also have this kind of internal/external embedding length.

**Comment by ngxson** [comment]
Hmm, please ignore what I said earlier.

Indeed, I think there is currently a misunderstanding here. The `n_embd_full` refer to the length of the **input** embedding, not the output. For example, I can have an input of `n_embd_full = n_embd*4`, but the model will always return `n_embd` as output. Therefore, this naming can be quite confusing.

I would suggest calling it `n_embd_inp` instead. Just need to pay attention to use `n_embd` when dealing with batch output.

File: src/llama-context.cpp [hunk 3]
```diff
@@ -1340,7 +1340,7 @@ uint32_t llama_context::output_reserve(int32_t n_outputs) {
 
 void llama_context::output_reorder() {
     const uint64_t n_vocab = model.vocab.n_tokens();
-    const uint64_t n_embd  = model.hparams.n_embd;
+    const uint64_t n_embd  = model.hparams.n_embd_full;
```
Comment (ngxson) [inline src/llama-context.cpp]: For Qwen3, the output embeddings should be `n_embd`

File: include/llama.h (hunk 1 above)
Comment (CISC) [reply include/llama.h]: Well, it's conceivable that this could be useful for other purposes at some point, locking down that name in the API is perhaps not great?

Also, re. the newer comments, `llama_model_n_embd_inp` would probably be confusing, so we need a better name...

Comment (ngxson) [reply include/llama.h]: I think `llama_model_n_embd_in` should be fine. IIRC gemma 3n also use this kinda of strategy, where input embedding is indeed `n_embd * N` while output is still `n_embd` (they call it "per-layer embeddings", exactly what qwen3vl is using)

Actually while working with TTS models, I also thought about an API like `llama_model_n_embd_in/out` where the embedding length of input/output can be different from the intermediate embeddings. Though not sure if it's a good idea @ggerganov

Comment (ggerganov) [reply include/llama.h]: `llama_model_n_embd_inp` seems good to me. (use `_inp` instead of `_in` suffix because it aligns better with `_out` potentially in the future)

File: src/llama-model.cpp [hunk 4]
```diff
@@ -6681,8 +6668,9 @@ ggml_backend_buffer_type_t llama_model::select_buft(int il) const {
     return ::select_buft(
             *pimpl->dev_layer.at(il).buft_list,
             [&](ggml_context * ctx) {
-                ggml_tensor * cur = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, hparams.n_embd);
-                ggml_tensor * layer_dir = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, hparams.n_embd);
+                const int n_embd_inp = hparams.n_embd_inp();
+                ggml_tensor * cur = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, n_embd_inp);
+                ggml_tensor * layer_dir = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, n_embd_inp);
```
Comment (ngxson) [inline src/llama-model.cpp]: I'm not 100% sure if `n_embd_inp` is correct here.

As far as I can understand, the `cur` is the output of the current layer. That means it should use the internal embedding length `n_embd`. CC @65a in case you know this part.

File: src/llama-context.cpp [hunk 5]
```diff
@@ -620,7 +620,7 @@ float * llama_context::get_embeddings_ith(int32_t i) {
             throw std::runtime_error(format("corrupt output buffer (j=%" PRId64 ", n_outputs=%d)", j, n_outputs));
         }
 
-        return embd + j*model.hparams.n_embd;
+        return embd + j*model.hparams.n_embd_inp();
```
Comment (ngxson) [inline src/llama-context.cpp]: Technically this should be `n_embd_out` (aka currently `n_embd`), right?

Comment (CISC) [reply src/llama-context.cpp]: Could be, I wasn't entirely sure.

File: src/llama-model.cpp [hunk 6]
```diff
@@ -276,8 +276,8 @@ static bool weight_buft_supported(const llama_hparams & hparams, ggml_tensor * w
             } break;
         case GGML_OP_IM2COL:
             {
-                const int n_embd = hparams.n_embd;
-                ggml_tensor * b = ggml_new_tensor_4d(ctx, GGML_TYPE_F32, n_embd, w->ne[1], 1, 1);
+                const int n_embd_inp = hparams.n_embd_inp();
+                ggml_tensor * b = ggml_new_tensor_4d(ctx, GGML_TYPE_F32, n_embd_inp, w->ne[1], 1, 1);
```
Comment (CISC) [inline src/llama-model.cpp:280]: I'm unsure if this is correct as well...

Comment (ngxson) [reply src/llama-model.cpp:280]: I think either `n_embd_inp` or `n_embd` should not be very important. at least for now, models that use this ops will have `n_embd_inp == n_embd`

File: src/llama-model.cpp (hunk 4 above)
Comment (65a) [reply src/llama-model.cpp]: So I just know what I learned from trying to make cvectors for Qwen3VL, so with that in mind:
1. The Transformers hiddenstate (and output embedding, being last_hidden_state) size of that model is 5120 (n_embd) and not 20480 (n_embd_inp). But I didn't use multimodal, and not sure if it changes.
2. I think the deepstack layers are only used for multimodal

This at least is called from llama-adapter.cpp for cvectors, but the check in cvector is hardcoded against n_embd, so it will still pass regardless (was wondering why my cvector worked with this code change). I assume since the cvector is for the language model, it doesn't matter if the other ones are empty so much so long as they are zeroed.

It seems like the answer might be use n_embd here unless there is somewhere multimodal where this is used, or multimodal cvectors are a thing, or this is called from other contexts that need the "rest" of it?

Comment (65a) [reply src/llama-model.cpp]: I can only find references to this variant of `select_buft` in llama_adapter.cpp, for cvectors. Since cvectors do not include the input embedding, I think n_embd is correct here.

**Comment by 65a** [comment]
I tested the latest commit in this series and it works for text and image processing successfully with a cvector applied.

File: src/llama-context.cpp (hunk 5 above)
Comment (ggerganov) [reply src/llama-context.cpp]: My understanding is this should be `n_embd` now and potentially `n_embd_out` if we do the extension.

**Review by ggerganov — APPROVED** [review]

**Comment by CISC** [comment]
> I tested the latest commit in this series and it works for text and image processing successfully with a cvector applied.

I will test again later today, but feel free to do so too before that.

**Comment by 65a** [comment]
> feel free to do so too before that.

Tested again on the latest commit. Seems to work great, MTMD and text work with a cvector applied. cvector is still working as expected.

**Review by ngxson — APPROVED** [review]
