### PR TITLE
clip : bring back GPU support

### LINKED ISSUE #11322: Eval bug: clip.cpp has no GPU support - a lot of work is at risk
### Name and Version

all versions 2025

### Operating systems

Linux

### GGML backends

CUDA, Metal

### Hardware

any

### Models

_No response_

### Problem description & steps to reproduce

In PR #10896  the GPU support of clip.cpp has been removed, it's basically just a few comments around fullly functional code.

Hundreds of hours went into CLIP and having it on GPU support was a major feat for the vision capabilities of llama.cpp, this also caused large SOTA models to be implemented in llama.cpp with people working dedicated on those patches.

I agree that the vision implementation was not great but we've had SOTA support by models like minicpm-v-2.6 and even the new minicpmv-o-2.6 has been implemented in llama.cpp at launch with dedicated people working on it with a current PR waiting for merge.

This change renders those models useless for anyone who is not aware on how to hack the llama.cpp code. It takes minutes instead of milliseconds now.

I strongly recommend to add the GPU support back into clip.cpp while it is still compatible (currently it is) with the core so people can use llama.cpp with vision capabilities again.
To prevent people posting unwelcome issues, add a warning message instead.
Right now we see issues being created that vision support is not working anymore, that GPU support is failing etc. Longterm it will cause developers to stop support llama.cpp as engine for vision.

### First Bad Commit

https://github.com/ggerganov/llama.cpp/pull/10896

### Relevant log output

```shell
-
```

### PR DESCRIPTION
**Pull request by ngxson**
## Motivation

Fix #11322

While waiting for https://github.com/ggml-org/llama.cpp/pull/11292 , I think it will be beneficial to look back at the `clip` and `llava` implementation and improve them a bit, as many downstream projects are depending on this.

Some of my ideas:
1. Format the code to make it looks nicer
2. Use more STL and cpp features to ease the memory management
3. Optimize the speed

So in this PR, I target the point (2) and (3) in my list above.

Please note that this implementation may not be perfect. My knowledge about ggml's `sched` is quite outdated, so the current status of this PR is "just work".

## How to test this

Download the GGUF from https://huggingface.co/openbmb/MiniCPM-V-2_6-gguf (download text model + mmproj)

```sh
cmake --build build -j --target llama-minicpmv-cli

./build/bin/llama-minicpmv-cli -m ../models/minicpmv-Q2_K.gguf --mmproj ../models/minicpmv-mmproj.gguf --image ../models/bliss.png -p "what do you see?"
```

If you see `CLIP using Metal backend`, that means it's good:

```
clip_init: CLIP using Metal backend
...
clip_init:      Metal compute buffer size =   102.80 MiB
clip_init:        CPU compute buffer size =    16.30 MiB
...
encode_image_with_clip: step 1 of 1 encoded in  1120.92 ms
encode_image_with_clip: all 1 segments encoded in  1120.95 ms
encode_image_with_clip: load_image_size 300 241
encode_image_with_clip: image embedding created: 64 tokens
```

To disable GPU, set `-ngl 0`, output will be:

```
clip_init: CLIP using CPU backend
...
clip_init:        CPU compute buffer size =   102.80 MiB
...
encode_image_with_clip: step 1 of 1 encoded in  6653.19 ms
encode_image_with_clip: all 1 segments encoded in  6653.21 ms
encode_image_with_clip: load_image_size 300 241
encode_image_with_clip: image embedding created: 64 tokens
```

Note: this is only tested on Metal

### CODE REVIEW

File: examples/llava/clip.h [hunk 1]
```diff
@@ -39,8 +39,15 @@ struct clip_image_f32_batch {
     size_t size;
 };
 
-CLIP_API struct clip_ctx * clip_model_load    (const char * fname, int verbosity);
-CLIP_API struct clip_ctx * clip_model_load_cpu(const char * fname, int verbosity);
```
Comment (ngxson) [inline examples/llava/clip.h:43]: Please note that `clip_model_load_cpu` has no implementation, so I removed it

**Review by slaren — APPROVED** [review]
Looks good. The GPU backend initialization could be implemented using the backend registry with `new_clip->backend = ggml_backend_init_by_type(GGML_BACKEND_DEVICE_TYPE_GPU, nullptr)`.

**Comment by ngxson** [comment]
@slaren Thanks for the clue, I implemented it in https://github.com/ggml-org/llama.cpp/pull/12322/commits/3e45ea4900d651d9d9116ac9b9083f61116441ed

File: examples/llava/clip.cpp [hunk 2]
```diff
@@ -600,18 +601,62 @@ struct clip_ctx {
...
+        }
+        if (buf) {
+            ggml_backend_buffer_free(buf);
+        }
+        if (backend) {
+            ggml_backend_free(backend);
+        }
+        if (backend_cpu && backend_cpu != backend) {
+            ggml_backend_free(backend_cpu);
+        }
```
Comment (slaren) [inline examples/llava/clip.cpp:658]: All of these functions can be safely called with a null pointer.

File: examples/llava/clip.cpp [hunk 3]
```diff
@@ -4,30 +4,31 @@
...
+#include "ggml-metal.h"
+#endif
+
+#ifdef GGML_USE_CANN
+#include "ggml-cann.h"
+#endif
+
+#ifdef GGML_USE_VULKAN
+#include "ggml-vulkan.h"
+#endif
```
Comment (slaren) [inline examples/llava/clip.cpp:31]: These includes are not necessary when using the backend registry.

File: examples/llava/clip.cpp (hunk 2 above)
Comment (ngxson) [reply examples/llava/clip.cpp]: Fixed in https://github.com/ggml-org/llama.cpp/pull/12322/commits/d95c01ab64289cb09509291f9fb1ac956c577331 , the only check I keep is `backend_cpu != backend` to prevent double-free

**Review by ggerganov — APPROVED** [review]
Tested only on Mac as well.

**Comment by mudler** [comment]
Hey guys great work as always! very happy to see GPU support back to clip. just a friendly bump/ for reference these changes broke some model supports according to my tests:

I've been trying this now and seems it breaks both `moondream2` (https://huggingface.co/moondream/moondream2-gguf/) and bakllava (which is tested by CI in LocalAI https://github.com/mudler/LocalAI/pull/4996 ).

**Comment by ngxson** [comment]
@mudler I think the CI is killed due to timeout, maybe you can try explicit set `use_gpu` to `false` via the newly added `clip_init` call.

Unfortunately I don't have the capability to debug right now. Would be nice if someone can look in depth to see what is the cause problem.

**Comment by mudler** [comment]
> @mudler I think the CI is killed due to timeout, maybe you can try explicit set `use_gpu` to `false` via the newly added `clip_init` call.
> 
> Unfortunately I don't have the capability to debug right now. Would be nice if someone can look in depth to see what is the cause problem.

mmh. that gave me some hint actually, thank you! I've tested on GPU and it works, while on CPU it fails indeed.

Probably related to the fact that 

```
struct clip_ctx * clip_model_load(const char * fname, const int verbosity = 1) {
    return clip_init(fname, clip_context_params{
        /* use_gpu */   true,
        /* verbosity */ verbosity,
    });
}
```

now defaults to using gpu. I'm fine specifying it by passing a context, but I wonder if would be safer to switching back to cpu as default?

**Comment by ngxson** [comment]
Hmm ok so that means it will stuck if there is no GPU at all. I'm not entirely sure why, but will try to compile llama.cpp without GPU to see.

`use_gpu` is supposed to be `true` by default, my idea was:
- If there is a GPU, good, use it
- If there is no GPU, fallback to CPU --> I think this is currently buggy, will have a look a bit later

**Comment by mudler** [comment]
yup can confirm that now works locally: 

I've replaced `            clp_ctx = clip_model_load(params.mmproj.c_str(), /*verbosity=*/ 1);` with:

```
            clp_ctx = clip_init(params.mmproj.c_str(), clip_context_params {
                /* use_gpu */ false,
                /*verbosity=*/ 1,
            });
```

And now successfully runs!

I'm trying to have a look on how can we detect better if device in use is GPUs, for instance among the lines of https://github.com/ggml-org/llama.cpp/blob/e0dbec0bc6cd4b6230cda7a6ed1e9dac08d1600b/src/llama.cpp#L208

**Comment by slaren** [comment]
The risk of enabling a GPU backend is that if does not support the operations, then the weights will still be stored in VRAM and will need to be copied back to CPU during evaluation, which of course is very slow. On a system without GPUs, the value of `use_gpu` shouldn't change anything.

**Comment by ngxson** [comment]
> I see in other spots of this PR reading the number of gpu layers to understand if we should use GPU or not, but afaict that seems something we can probably avoid as other code is probably capable of detecting devices in use (but I'm not sure about it, this is my speculation). llama.cpp so far behind the scenes managed to detect GPU or CPU devices without being explicit about it. For example, I use to specify gpu layers even if running on CPU, and that does not force llama.cpp to offload to gpu.

Please note that the point of having this detection (case of `ngl == 0`) is for convenient, as often user adding `-ngl 0` will expect model to run on CPU.

Even with `ngl != 0` and you run it **without** GPU, it should offload to CPU and runs normally, I think this is currently buggy and need to be fix.

And also remember that we will soon move away from this `clip.cpp` infrastructure, so I just want to keep thing simple here.

**Comment by mudler** [comment]
> > I see in other spots of this PR reading the number of gpu layers to understand if we should use GPU or not, but afaict that seems something we can probably avoid as other code is probably capable of detecting devices in use (but I'm not sure about it, this is my speculation). llama.cpp so far behind the scenes managed to detect GPU or CPU devices without being explicit about it. For example, I use to specify gpu layers even if running on CPU, and that does not force llama.cpp to offload to gpu.
> 
> Please note that the point of having this detection (case of `ngl == 0`) is for convenient, as often user adding `-ngl 0` will expect model to run on CPU.

Right indeed :+1: 
> 
> Even with `ngl != 0` and you run it **without** GPU, it should offload to CPU and runs normally, I think this is currently buggy and need to be fix.

I think that's the case here - ngl is !=0 and have no GPU, `use_gpu` is set to true and it crashes


> 
> And also remember that we will soon move away from this `clip.cpp` infrastructure, so I just want to keep thing simple here.

Thanks for the heads up!

**Comment by Azirine** [comment]
This commit breaks Qwen2-VL on Mac https://github.com/ggml-org/llama.cpp/issues/12405

**Comment by gryffindor-rr** [comment]
clip_image_build_graph_legacy: 490 406
ggml_metal_graph_compute: command buffer 0 failed with status 5
error: Internal Error (0000000e:Internal Error)
clip_image_batch_encode: ggml_backend_sched_graph_compute failed with error -1

error with running Minicpm-v26

cpu mode is good.
