### PR TITLE
Fix phi3 chat template confusion with zephyr

### LINKED ISSUE #7432: [server] phi-3 uses <|endoftext|> instead of <|end|> when applying chat template in /chat/completions
When using phi-3 without the option `--chat-template phi3`, the tokenization is incorrect. 

For example, if I **do** use `--chat-template phi3`, here is the log output when I send the message "hi":
```json
{
    "level": "VERB",
    "function": "update_slots",
    "line": 1954,
    "msg": "prompt tokenized",
    "id_slot": 0,
    "id_task": 1,
    "n_ctx": 8192,
    "n_keep": 0,
    "n_prompt_tokens": 7,
    "prompt_tokens": "<s><|system|><|end|><|user|> hi<|end|><|assistant|>"
}
```

actually the extra space after <|user|> is concerning, it should be a newline, but maybe that's just an artifact of how the log message is formatted.

But here's what happens when the `--chat-template phi3` is omitted:

```json
{
    "level": "VERB",
    "function": "update_slots",
    "line": 1954,
    "msg": "prompt tokenized",
    "id_slot": 0,
    "id_task": 0,
    "n_ctx": 8192,
    "n_keep": 0,
    "n_prompt_tokens": 11,
    "prompt_tokens": "<s><|system|><|endoftext|> \n<|user|> hi<|endoftext|> \n<|assistant|>"
}
```

See how it uses <|endoftext|> (wrong) instead of <|end|> (correct) which causes really bad generation.

I am using the gguf straight from Microsoft, so I guess it is as official as it gets:

https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf

Possibly the problem is in the gguf itself? Even so, it's weird that using the "official" gguf results in incorrect tokenization output from the template applied.

Now, you could just always use `--chat-template phi3`. But my expectation is the `phi3` chat template should automatically be picked up by the detection heuristic, when using the canonical/official Phi-3 models, since they purport to support phi3.

### PR DESCRIPTION
**Pull request by tristandruyen**
Reported in & Resolves #7432

### Problem

Zephyr & Phi3 use similar tokens like `<|assistant|>` &  `<|user|>`, but they use different eos tokens, as the zephyr template appears first in the if else chain, phi3 is misdetected as zephyr, which causes wrong `<|endoftext|>` instead of `<|end|>` tokens to appear in the prompt as reported in the referenced issue.

### Root-Cause

Phi-3's template, seems to have changed sometime after my PR #6857 was merged.
Initially it didn't explicitly include <|user|> but spliced the role into there...

OLD:
```
{{ bos_token }}{% for message in messages %}{{'<|' + message['role'] + '|>' + ' ' + message['content'] + '<|end|> ' }}{% endfor %}{% if add_generation_prompt %}{{ '<|assistant|> ' }}{% else %}{{ eos_token }}{% endif %}
```

NEW:
```
{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') %}{{'<|user|>' + ' ' + message['content'] + '<|end|>' + ' ' + '<|assistant|>' + ' '}}{% elif (message['role'] == 'assistant') %}{{message['content'] + '<|end|>' + ' '}}{% endif %}{% endfor %}
```

This causes this mis-matching as zephyr.

### Solution

It's pretty simple, stop zephyr from applying to every model with <|user|> in the template by ~adding an additional requirement.~ reordering the if else's

### CODE REVIEW

File: llama.cpp [hunk 1]
```diff
@@ -17628,7 +17628,7 @@ static int32_t llama_chat_apply_template_internal(
             }
         }
         // llama2 templates seem to not care about "add_generation_prompt"
-    } else if (tmpl == "zephyr" || tmpl.find("<|user|>") != std::string::npos) {
+    } else if (tmpl == "zephyr" || (tmpl.find("<|user|>") != std::string::npos && tmpl.find("<|end|>") == std::string::npos)) {
```
Comment (tristandruyen) [inline llama.cpp:17631]: I could not easily confirm the chat template for zephyr, a random GGUF of a random finetune had this in the GGUF metadata:
```
{% for message in messages %} {% if message['role'] == 'user' %} {{ '<|user|> ' + message['content'] + eos_token }} {% elif message['role'] == 'system' %} {{ '<|system|> ' + message['content'] + eos_token }} {% elif message['role'] == 'assistant' %} {{ '<|assistant|> ' + message['content'] + eos_token }} {% endif %} {% if loop.last and add_generation_prompt %} {{ '<|assistant|>' }} {% endif %} {% endfor %}
```

So can not match on `<|endoftext|>` As it doesn't appear explicitly. `eos_token` is also not an option is it appears in both the zephyr & old phi3 template. 
Therefore I decided to falsify the zephyr match when <|end|> is in the template, which is the case for both phi3 templates.

Comment (ngxson) [reply llama.cpp:17631]: I'd recommend to move the phi-3 check before the check for zephyr, instead of doing inverse logic like this.

Example:

```
else if (tmpl == "phi3" || (tmpl.find("<|user|>") != std::string::npos && tmpl.find("<|end|>") != std::string::npos)) {
   ...
} else if (tmpl == "zephyr" || tmpl.find("<|user|>") != std::string::npos) {
   ...
} else if ...
```

Also, phi-3 templates seems to have the distinct `+ ' '` condition. Why don't we do: `tmpl.find("<|user|>") != std::string::npos && tmpl.find("+ ' '") != std::string::npos)` ?

Comment (tristandruyen) [reply llama.cpp]: I reordered & removed the inverse check like suggested.
I also replaced the `find("<|end|>")` with `find("+ ' '")`.

`tmpl.find("<|user|>")` wouldn't work for the old phi3 template which uses `'<|' + message['role'] + '|>'` instead of `<|user|>`

Comment (ngxson) [reply llama.cpp]: According to discussion from https://github.com/ggerganov/llama.cpp/pull/6857/files/992fff725f307ce54e02586f82a0303e6b0023b6#diff-b87e1c2fc779778832f03ef373963fcc40603a0500fc13cdc4cc570ee0189e8f , the given template may not be correct. Can you have a link to the original `tokenizer_config.json` file?

Comment (tristandruyen) [reply llama.cpp]: I changed the match to find("<|end|>") again, I'm also fine with find("+ '\n'") if you think that's better...

Comment (ngxson) [reply llama.cpp]: We should `find("+ '\n'")` because this condition appears in almost all templates - not just phi-3.

The reason why I suggested `find("+ ' '")` was because I thought that phi-3 uses space after special token - which turns out to be incorrect.

File: tests/test-chat-template.cpp [hunk 2]
```diff
@@ -50,7 +50,9 @@ int main(void) {
         // Llama-3
         "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ content }}{% endfor %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}",
         // Phi-3
-        "{{ bos_token }}{% for message in messages %}{{'<|' + message['role'] + '|>' + ' ' + message['content'] + '<|end|> ' }}{% endfor %}{% if add_generation_prompt %}{{ '<|assistant|> ' }}{% else %}{{ eos_token }}{% endif %}"
+        "{{ bos_token }}{% for message in messages %}{{'<|' + message['role'] + '|>' + '\n' + message['content'] + '<|end|> ' }}{% endfor %}{% if add_generation_prompt %}{{ '<|assistant|> ' }}{% else %}{{ eos_token }}{% endif %}"
+        // Phi-3 New
+        "{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') %}{{'<|user|>' + '\n' + message['content'] + '<|end|>' + '\n' + '<|assistant|>' + '\n'}}{% elif (message['role'] == 'assistant') %}{{message['content'] + '<|end|>' + '\n'}}{% endif %}{% endfor %}",
```
Comment (ngxson) [inline tests/test-chat-template.cpp:55]: According to my research, there are 4 templates used by phi-3 (all of them output the same thing): https://gist.github.com/ngxson/38d8d89fb5d856187bcc70e78b1cc4f5

Maybe it's worth to add them all.

File: llama.cpp [hunk 3]
```diff
@@ -17628,6 +17628,15 @@ static int32_t llama_chat_apply_template_internal(
             }
         }
         // llama2 templates seem to not care about "add_generation_prompt"
+    } else if (tmpl == "phi3" || (tmpl.find("<|assistant|>") != std::string::npos && tmpl.find("<|end|>") != std::string::npos )) {
```
Comment (ngxson) [inline llama.cpp:17631]:
```suggestion
    } else if (tmpl == "phi3" || (tmpl.find("<|assistant|>") != std::string::npos && tmpl.find("<|end|>") != std::string::npos)) {
```

**Review by ngxson — APPROVED** [review]
LGTM overall. It would be nice to have all 4 templates in the test.

File: tests/test-chat-template.cpp (hunk 2 above)
Comment (tristandruyen) [reply tests/test-chat-template.cpp:53]: Done :)

File: llama.cpp [hunk 4]
```diff
@@ -17628,6 +17628,15 @@ static int32_t llama_chat_apply_template_internal(
             }
         }
         // llama2 templates seem to not care about "add_generation_prompt"
+    } else if (tmpl == "phi3" || (tmpl.find("<|assistant|>") != std::string::npos && tmpl.find("<|end|>") != std::string::npos)) {
+        // Phi 3
+        for (auto message : chat) {
+            std::string role(message->role);
+            ss << "<|" << role << "|>\n" << trim(message->content) << "<|end|>\n";
```
Comment (ngxson) [inline llama.cpp:17635]: One small change: None of the template has `message['content'] | trim`, so we shouldn't trim here

```suggestion
            ss << "<|" << role << "|>\n" << message->content << "<|end|>\n";
```

**Review by ngxson — CHANGES_REQUESTED** [review]

File: llama.cpp (hunk 4 above)
Comment (tristandruyen) [reply llama.cpp]: Tests fail now obviously.
Will fix soon

**Review by ngxson — APPROVED** [review]

**Comment by ngxson** [comment]
OK I'll merge when CI passes

**Comment by tristandruyen** [comment]
The test failures seem unrelated to the changes, should be good to merge.
