### PR TITLE
kv-cache: Fix state restore fragmented cache

### LINKED ISSUE #17527: Eval bug: failed to restore kv cache on gpt-oss:120b with parallel processing
### Name and Version

version: 7157 (583cb8341)
built with clang version 19.1.5 for x86_64-pc-windows-msvc

### Operating systems

Windows

### GGML backends

CUDA

### Hardware

RTX 5060 Ti + 9950x + 96 GB RAM

### Models

`--gpt-oss-120b-default` (see below for extra parameters that might affect it)

### Problem description & steps to reproduce

I am running `llama-server` with

```
      --gpt-oss-120b-default
      --ctx-size 0
      --kv-unified
      --jinja
      --chat-template-kwargs {\"reasoning_effort\":\"high\"}
      -ub 2048 -b 2048
      --cpu-moe --n-gpu-layers 999
      --prio -1
      --parallel 8
```

And two parallel agentic workflows: one via llama.vscode, another via codex.

Both contexts are far from 64K (somewhere in 2xK each). Yet, llama-server falls back to full prompt re-processing "due to lack of cache data".

### First Bad Commit

_No response_

### Relevant log output

```shell
srv  params_from_: Chat format: GPT-OSS
slot get_availabl: id  7 | task -1 | selected slot by LCP similarity, sim_best = 0.901 (> 0.100 thold), f_keep = 0.823
slot launch_slot_: id  7 | task -1 | sampler chain: logits -> logit-bias -> penalties -> dry -> top-n-sigma -> top-k -> typical -> top-p -> min-p -> xtc -> temp-ext -> dist
slot launch_slot_: id  7 | task 60314 | processing task
slot update_slots: id  7 | task 60314 | new prompt, n_ctx_slot = 131072, n_keep = 0, task.n_tokens = 27291
slot update_slots: id  7 | task 60314 | n_past = 24582, slot.prompt.tokens.size() = 29882, seq_id = 7, pos_min = 29755, n_swa = 128
state_read_meta: failed to find available cells in kv cache
state_seq_set_data: error loading state: failed to restore kv cache
slot update_slots: id  7 | task 60314 | failed to restore context checkpoint (pos_min = 21700, pos_max = 24516, size = 99.068 MiB)
slot update_slots: id  7 | task 60314 | forcing full prompt re-processing due to lack of cache data (likely due to SWA or hybrid/recurrent memory, see https://github.com/ggml-org/llama.cpp/pull/13194#issuecomment-2868343055)
```

### PR DESCRIPTION
**Pull request by ssweens**
Fix #17527 

Change find_slot to allow non-contiguous allocation during state restore. Fixes 'failed to find available cells in kv cache' error when restoring state to fragmented cache.

### CODE REVIEW

**Comment by ssweens** [comment]
PS - aimed to implement the direction given by @ggerganov (https://github.com/ggml-org/llama.cpp/issues/17527#issuecomment-3605767335)

**Comment by ggerganov** [comment]
Looking good - will do some testing to confirm 👍

File: src/llama-kv-cache.h [hunk 1]
```diff
@@ -264,8 +278,8 @@ class llama_kv_cache : public llama_memory_i {
     void state_write_meta(llama_io_write_i & io, const cell_ranges_t & cr, llama_seq_id seq_id = -1) const;
     void state_write_data(llama_io_write_i & io, const cell_ranges_t & cr) const;
 
-    bool state_read_meta(llama_io_read_i & io, uint32_t strm, uint32_t cell_count, llama_seq_id dest_seq_id = -1);
-    bool state_read_data(llama_io_read_i & io, uint32_t strm, uint32_t cell_count);
+    bool state_read_meta(llama_io_read_i & io, uint32_t strm, uint32_t cell_count, llama_seq_id dest_seq_id, slot_info & sinfo);
+    bool state_read_data(llama_io_read_i & io, uint32_t strm, uint32_t cell_count, const slot_info & sinfo);
```
Comment (ggerganov) [inline src/llama-kv-cache.h]: Use this signature instead:

```suggestion
    bool state_read_meta(llama_io_read_i & io, uint32_t strm, uint32_t cell_count,       slot_info & sinfo, llama_seq_id dest_seq_id = -1);
    bool state_read_data(llama_io_read_i & io, uint32_t strm, uint32_t cell_count, const slot_info & sinfo);

```

**Comment by ggerganov** [comment]
I updated the test to do a proper verification:

- It requires `kv_unified == true`
- It interleaves the sequences to create large fragmentation
- Uses total context size of 256 tokens and 3 sequences with 70 tokens each

@ssweens  After you address the comments, we can merge.

File: src/llama-kv-cache.h [hunk 2]
```diff
@@ -72,6 +72,20 @@ class llama_kv_cache : public llama_memory_i {
...
+                return true;
+            }
+            const uint32_t h = idxs[0][0];
+            for (size_t i = 0; i < idxs[0].size(); ++i) {
+                if (idxs[0][i] != h + i) {
+                    return false;
+                }
+            }
+            return true;
+        }
```
Comment (ggerganov) [inline src/llama-kv-cache.h:91]: Should return `false` when `idx.size() > 1`

**Comment by ssweens** [comment]
Thanks @ggerganov.  Comments addressed and committed.

**Review by ggerganov — APPROVED** [review]
Thanks for the contribution. This is a good improvement.

**Comment by ssweens** [comment]
Happy to help where/when I can.  Hat tip to you and team on the great project.
