### PR TITLE
llama : fix non-causal mask for gemma 3

### LINKED ISSUE #12433: Eval bug: Gemma3 <unused32> spam
### Name and Version

```
> llama-gemma3-cli.exe --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6, VMM: yes
  Device 1: NVIDIA GeForce RTX 4060 Ti, compute capability 8.9, VMM: yes
version: 4902 (cf2270e4)
built with MSVC 19.29.30158.0 for
```

### Operating systems

Windows

### GGML backends

CUDA

### Hardware

AMD Ryzen 7 5800X 8-Core
NVIDIA GeForce RTX 3090 Ti
NVIDIA GeForce RTX 4060 Ti

### Models

gemma-3-4b-it-GGUF/gemma-3-4b-it-Q4_K_M.gguf + gemma-3-4b-it-GGUF/mmproj-model-f16.gguf

https://huggingface.co/ggml-org/gemma-3-4b-it-GGUF

### Problem description & steps to reproduce

`llama-gemma3-cli` outputs `<unused32>` infinitely in certain situations.

Reproduction:
1. Load the model as such:
```
>  llama-gemma3-cli.exe -m gemma-3-4b-it-GGUF\gemma-3-4b-it-Q4_K_M.gguf --mmproj gemma-3-4b-it-GGUF\mmproj-model-f16.gguf -ngl 99 --temp 0.0 --seed 0 -c 4096
```
2. Have the model first generate a story with prompt `Tell me a long story`, to completion:
```
<snipped>
 Running in chat mode, available commands:
   /image <path>    load an image
   /clear           clear the chat history
   /quit or /exit   exit the program
> Tell me a long story
```
3. Have the model eval the following image: 

Image
```
<snipped>
*   Change the ending?
*   Tell a different story altogether?
> /image dice.jpg
```
4. Ask the model what they are:
```
> /image dice.jpg
Encoding image dice.jpg
Image encoded in 589 ms
Image decoded in 295 ms
> What are these?
```
5. Observe `<unused32>` spam
```
> What are these?
<unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32>...
``` 

### First Bad Commit

_No response_

### Relevant log output

```shell
C:\Users\User>  C:\Users\User\Downloads\llama-b4902-bin-win-cuda-cu11.7-x64\llama-gemma3-cli.exe -m C:\Users\User\.cache\lm-studio\models\ggml-org\gemma-3-4b-it-GGUF\gemma-3-4b-it-Q4_K_M.gguf --mmproj C:\Users\User\.cache\lm-studio\models\ggml-org\gemma-3-4b-it-GGUF\mmproj-model-f16.gguf -ngl 99 --temp 0.0 --seed 0 -c 4096
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090 Ti, compute capability 8.6, VMM: yes
  Device 1: NVIDIA GeForce RTX 4060 Ti, compute capability 8.9, VMM: yes
build: 4902 (cf2270e4) with MSVC 19.29.30158.0 for
llama_model_load_from_file_impl: using device CUDA0 (NVIDIA GeForce RTX 3090 Ti) - 23267 MiB free
llama_model_load_from_file_impl: using device CUDA1 (NVIDIA GeForce RTX 4060 Ti) - 15209 MiB free
llama_model_loader: loaded meta data with 40 key-value pairs and 444 tensors from C:\Users\User\.cache\lm-studio\models\ggml-org\gemma-3-4b-it-GGUF\gemma-3-4b-it-Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gemma3
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Gemma 3 4b It
llama_model_loader: - kv   3:                           general.finetune str              = it
llama_model_loader: - kv   4:                           general.basename str              = gemma-3
llama_model_loader: - kv   5:                         general.size_label str              = 4B
llama_model_loader: - kv   6:                            general.license str              = gemma
llama_model_loader: - kv   7:                   general.base_model.count u32              = 1
llama_model_loader: - kv   8:                  general.base_model.0.name str              = Gemma 3 4b Pt
llama_model_loader: - kv   9:          general.base_model.0.organization str              = Google
llama_model_loader: - kv  10:              general.base_model.0.repo_url str              = https://huggingface.co/google/gemma-3...
llama_model_loader: - kv  11:                               general.tags arr[str,1]       = ["image-text-to-text"]
llama_model_loader: - kv  12:                      gemma3.context_length u32              = 131072
llama_model_loader: - kv  13:                    gemma3.embedding_length u32              = 2560
llama_model_loader: - kv  14:                         gemma3.block_count u32              = 34
llama_model_loader: - kv  15:                 gemma3.feed_forward_length u32              = 10240
llama_model_loader: - kv  16:                gemma3.attention.head_count u32              = 8
llama_model_loader: - kv  17:    gemma3.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  18:                gemma3.attention.key_length u32              = 256
llama_model_loader: - kv  19:              gemma3.attention.value_length u32              = 256
llama_model_loader: - kv  20:                      gemma3.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  21:            gemma3.attention.sliding_window u32              = 1024
llama_model_loader: - kv  22:             gemma3.attention.head_count_kv u32              = 4
llama_model_loader: - kv  23:                   gemma3.rope.scaling.type str              = linear
llama_model_loader: - kv  24:                 gemma3.rope.scaling.factor f32              = 8.000000
llama_model_loader: - kv  25:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  26:                         tokenizer.ggml.pre str              = default
llama_model_loader: - kv  27:                      tokenizer.ggml.tokens arr[str,262144]  = ["<pad>", "<eos>", "<bos>", "<unk>", ...
llama_model_loader: - kv  28:                      tokenizer.ggml.scores arr[f32,262144]  = [-1000.000000, -1000.000000, -1000.00...
llama_model_loader: - kv  29:                  tokenizer.ggml.token_type arr[i32,262144]  = [3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, ...
llama_model_loader: - kv  30:                tokenizer.ggml.bos_token_id u32              = 2
llama_model_loader: - kv  31:                tokenizer.ggml.eos_token_id u32              = 1
llama_model_loader: - kv  32:            tokenizer.ggml.unknown_token_id u32              = 3
llama_model_loader: - kv  33:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  34:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  35:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  36:                    tokenizer.chat_template str              = {{ bos_token }}\n{%- if messages[0]['r...
llama_model_loader: - kv  37:            tokenizer.ggml.add_space_prefix bool             = false
llama_model_loader: - kv  38:               general.quantization_version u32              = 2
llama_model_loader: - kv  39:                          general.file_type u32              = 15
llama_model_loader: - type  f32:  205 tensors
llama_model_loader: - type q4_K:  204 tensors
llama_model_loader: - type q6_K:   35 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 2.31 GiB (5.12 BPW)
load: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
load: special tokens cache size = 6414
load: token to piece cache size = 1.9446 MB
print_info: arch             = gemma3
print_info: vocab_only       = 0
print_info: n_ctx_train      = 131072
print_info: n_embd           = 2560
print_info: n_layer          = 34
print_info: n_head           = 8
print_info: n_head_kv        = 4
print_info: n_rot            = 256
print_info: n_swa            = 1024
print_info: n_swa_pattern    = 6
print_info: n_embd_head_k    = 256
print_info: n_embd_head_v    = 256
print_info: n_gqa            = 2
print_info: n_embd_k_gqa     = 1024
print_info: n_embd_v_gqa     = 1024
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-06
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 6.2e-02
print_info: n_ff             = 10240
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = 0
print_info: rope type        = 2
print_info: rope scaling     = linear
print_info: freq_base_train  = 1000000.0
print_info: freq_scale_train = 0.125
print_info: n_ctx_orig_yarn  = 131072
print_info: rope_finetuned   = unknown
print_info: ssm_d_conv       = 0
print_info: ssm_d_inner      = 0
print_info: ssm_d_state      = 0
print_info: ssm_dt_rank      = 0
print_info: ssm_dt_b_c_rms   = 0
print_info: model type       = 4B
print_info: model params     = 3.88 B
print_info: general.name     = Gemma 3 4b It
print_info: vocab type       = SPM
print_info: n_vocab          = 262144
print_info: n_merges         = 0
print_info: BOS token        = 2 '<bos>'
print_info: EOS token        = 1 '<eos>'
print_info: EOT token        = 106 '<end_of_turn>'
print_info: UNK token        = 3 '<unk>'
print_info: PAD token        = 0 '<pad>'
print_info: LF token         = 248 '<0x0A>'
print_info: EOG token        = 1 '<eos>'
print_info: EOG token        = 106 '<end_of_turn>'
print_info: max token length = 48
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: offloading 34 repeating layers to GPU
load_tensors: offloading output layer to GPU
load_tensors: offloaded 35/35 layers to GPU
load_tensors:        CUDA0 model buffer size =  1185.55 MiB
load_tensors:        CUDA1 model buffer size =  1182.63 MiB
load_tensors:   CPU_Mapped model buffer size =   525.00 MiB
................................................................
llama_context: constructing llama_context
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 4096
llama_context: n_ctx_per_seq = 4096
llama_context: n_batch       = 2048
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = 0
llama_context: freq_base     = 1000000.0
llama_context: freq_scale    = 0.125
llama_context: n_ctx_per_seq (4096) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
llama_context:  CUDA_Host  output buffer size =     1.00 MiB
init: kv_size = 4096, offload = 1, type_k = 'f16', type_v = 'f16', n_layer = 34, can_shift = 1
init:      CUDA0 KV buffer size =   352.00 MiB
init:      CUDA1 KV buffer size =   192.00 MiB
llama_context: KV self size  =  544.00 MiB, K (f16):  272.00 MiB, V (f16):  272.00 MiB
llama_context: pipeline parallelism enabled (n_copies=4)
llama_context:      CUDA0 compute buffer size =   166.01 MiB
llama_context:      CUDA1 compute buffer size =   601.02 MiB
llama_context:  CUDA_Host compute buffer size =    69.02 MiB
llama_context: graph nodes  = 1367
llama_context: graph splits = 3
common_init_from_params: setting dry_penalty_last_n to ctx_size = 4096
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
clip_init: loaded meta data with 16 key-value pairs and 439 tensors from C:\Users\User\.cache\lm-studio\models\ggml-org\gemma-3-4b-it-GGUF\mmproj-model-f16.gguf
clip_init: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
clip_init: - kv   0:                       general.architecture str              = clip
clip_init: - kv   1:                        clip.projector_type str              = gemma3
clip_init: - kv   2:                      clip.has_text_encoder bool             = false
clip_init: - kv   3:                    clip.has_vision_encoder bool             = true
clip_init: - kv   4:                   clip.has_llava_projector bool             = false
clip_init: - kv   5:                     clip.vision.image_size u32              = 896
clip_init: - kv   6:                     clip.vision.patch_size u32              = 14
clip_init: - kv   7:               clip.vision.embedding_length u32              = 1152
clip_init: - kv   8:            clip.vision.feed_forward_length u32              = 4304
clip_init: - kv   9:                 clip.vision.projection_dim u32              = 2560
clip_init: - kv  10:                    clip.vision.block_count u32              = 27
clip_init: - kv  11:           clip.vision.attention.head_count u32              = 16
clip_init: - kv  12:   clip.vision.attention.layer_norm_epsilon f32              = 0.000001
clip_init: - kv  13:                     clip.vision.image_mean arr[f32,3]       = [0.500000, 0.500000, 0.500000]
clip_init: - kv  14:                      clip.vision.image_std arr[f32,3]       = [0.500000, 0.500000, 0.500000]
clip_init: - kv  15:                              clip.use_gelu bool             = true
clip_init: - type  f32:  276 tensors
clip_init: - type  f16:  163 tensors
clip_ctx: CLIP using CUDA0 backend
key clip.use_silu not found in file
clip_init: params backend buffer size =  811.79 MB (439 tensors)
key clip.vision.image_grid_pinpoints not found in file
key clip.vision.feature_layer not found in file
key clip.vision.mm_patch_merge_type not found in file
key clip.vision.image_crop_resolution not found in file
clip_init:      CUDA0 compute buffer size =  1128.81 MiB
clip_init:        CPU compute buffer size =     9.19 MiB
main: C:\Users\User\.cache\lm-studio\models\ggml-org\gemma-3-4b-it-GGUF\gemma-3-4b-it-Q4_K_M.gguf
 Running in chat mode, available commands:
   /image <path>    load an image
   /clear           clear the chat history
   /quit or /exit   exit the program
> Tell me a long story
Okay, settle in. This is a story about a lighthouse keeper named Silas Blackwood, a forgotten melody, and a storm that whispered secrets.
Silas Blackwood wasnΓÇÖt a man of many words. HeΓÇÖd been the keeper of the North Point Lighthouse for thirty-seven years, a solitary existence on the jagged, windswept coast of the Isle of Skye in Scotland. The lighthouse, a towering granite sentinel named ΓÇ£The SerpentΓÇÖs ToothΓÇ¥ by the locals, was his entire world. HeΓÇÖd inherited the post from his father, and his father before him, a lineage of men bound to the rhythm of the sea and the insistent blink of the light.
Silas wasnΓÇÖt a romantic. He didnΓÇÖt read poetry or dream of grand adventures. He simply maintained the light, polished the brass, checked the lenses, and listened. He listened to the wind, the waves, the cries of the gulls, and, most importantly, he listened to the silence.
The silence was broken, occasionally, by the arrival of supply ships ΓÇô gruff men with weathered faces and a cargo of oil and provisions. TheyΓÇÖd exchange a few terse words with Silas, a nod of acknowledgement, and then be gone, swallowed by the mist.  Silas rarely spoke to anyone. HeΓÇÖd found a strange comfort in the isolation, a quiet that allowed him to hear things others couldnΓÇÖt.
One particularly bleak autumn evening, as a low, bruised purple sky threatened a storm, Silas discovered something unusual. He was meticulously cleaning the lens of the lamp when he heard it ΓÇô a faint, almost ethereal melody. It wasnΓÇÖt a song he recognized, not a traditional Scottish tune, not a sea shanty. It wasΓÇªolder.  It seemed to emanate from the very stone of the lighthouse, a delicate, mournful tune played on what sounded like a distant, forgotten flute.
He stopped his work, his hand frozen mid-polish. He listened intently, straining his ears against the rising wind. The melody persisted, weaving itself into the roar of the waves. It was beautiful, heartbreakingly so, and utterly perplexing.
Silas, a man of logic and routine, found himself captivated. He began to investigate, meticulously checking the structure of the lighthouse, searching for any sign of a hidden mechanism, a secret chamber. He found nothing. The melody continued, growing slightly louder as the storm gathered.
As the storm broke, unleashing a furious torrent of rain and wind, the melody intensified. It was accompanied by a strange, unsettling feeling ΓÇô a sense of being watched, of something ancient and powerful stirring within the stone.  He realized, with a chilling certainty, that the melody wasn't just *in* the lighthouse; it was *of* the lighthouse.
He began to research the history of The SerpentΓÇÖs Tooth. He poured over old maps, local legends, and the sparse records kept by his ancestors. He discovered that the lighthouse wasn't built on solid rock. It was constructed on a small, submerged island, a place known as ΓÇ£An CailleachΓÇÖs TearΓÇ¥ ΓÇô the WitchΓÇÖs Tear ΓÇô named after a legendary Celtic sorceress who was said to have drowned on the island centuries ago.
The legends spoke of An CailleachΓÇÖs grief, a sorrow so profound that it had become trapped within the stone, manifesting as the melody.  They said she was searching for her lost love, a fisherman named Eamon, who had vanished during a particularly violent storm.
Silas, driven by a compulsion he couldnΓÇÖt explain, began to spend his nights listening to the melody, trying to decipher its meaning. He realized that the tune wasnΓÇÖt just a lament; it was a *search*. It was a desperate, echoing plea.
Then, one night, as the storm raged with particular ferocity, he noticed something new. The melody shifted, subtly altering its notes. It seemed to be responding to the wind, to the waves, to the very storm itself. And then, he heard a voice, faint and ghostly, interwoven with the music.
It was a manΓÇÖs voice, weathered and weary, repeating a single name: ΓÇ£EamonΓÇªΓÇ¥
Silas, armed with this knowledge, began to act. He started leaving small offerings at the base of the lighthouse ΓÇô polished stones, wildflowers, a hand-carved wooden flute ΓÇô hoping to appease the spirit, to guide her. He spent hours studying the tides, the currents, trying to understand the patterns of the storm.
Finally, after weeks of relentless listening and searching, he realized the key. The melody wasnΓÇÖt just about finding Eamon; it was about *returning* him. The storm, he realized, wasnΓÇÖt just a force of nature; it was a conduit, a pathway through time.
On the night of the next full moon, as the storm reached its peak, Silas climbed to the top of the lighthouse, the wind whipping around him, the rain stinging his face. He closed his eyes, focused on the melody, and began to hum, matching its rhythm, echoing its plea.
Suddenly, the light of the lighthouse pulsed with an unnatural intensity. The air shimmered, and a swirling vortex of mist formed around the base of the tower.  And then, he saw him.
Not a ghost, not a phantom, but a man, drenched and shivering, standing on the small island, his eyes filled with a lifetime of sorrow. It was Eamon, miraculously returned from the depths of time.
Eamon didnΓÇÖt speak. He simply looked at Silas, a profound understanding passing between them. Then, he reached out, took SilasΓÇÖs hand, and with a final, heartbreaking smile, he faded away, dissolving back into the mist.
The melody ceased. The storm began to subside.
Silas Blackwood remained the keeper of The SerpentΓÇÖs Tooth, but he was no longer the same man. He had listened to the secrets of the sea, he had answered a forgotten plea, and he had, in a way, brought peace to a restless spirit.
He continued to polish the lens, check the lights, and listen to the silence. But now, he knew that the silence wasn't empty. It was filled with the echoes of a love lost and found, a testament to the enduring power of music, and a reminder that even the most solitary of lives could be touched by the magic of the past.
And sometimes, on the quietest nights, if you listen very carefully, you can still hear the faintest whisper of a flute, playing a mournful, beautiful tune, carried on the wind.
---
Would you like me to:
*   Expand on a particular part of the story?
*   Change the ending?
*   Tell a different story altogether?
> /image C:\Users\User\Documents\random-images\dice.jpg
Encoding image C:\Users\User\Documents\random-images\dice.jpg
Image encoded in 589 ms
Image decoded in 295 ms
> What are these?
<unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32><unused32>
```

### PR DESCRIPTION
**Pull request by ngxson**
Fix https://github.com/ggml-org/llama.cpp/issues/12433

Related to this comment: https://github.com/ggml-org/llama.cpp/pull/12181#issuecomment-2720808102

---

For example, provided that we have a cache of 10 tokens, 3 tokens already inside the cache and we are about to process 4 more tokens

Causal mask (with `llama_set_causal_attn(true)`):

```
xxxx------
xxxxx-----
xxxxxx----
xxxxxxx---
```

For gemma 3, what we want is (with `llama_set_causal_attn(false)`):

```
xxxxxxx---
xxxxxxx---
xxxxxxx---
xxxxxxx---
```

---

To visualize the mask, insert the code below inside `llm_graph_input_attn_kv_unified::set_input()`:

```cpp
printf("\n\n\n\n");
printf("self_kq_mask.shape %lld, %lld\n", self_kq_mask->ne[0], self_kq_mask->ne[1]);
printf("n_tokens: %lld, n_kv: %lld\n", n_tokens, n_kv);
for (int row = 0; row < n_row; row++) {
    for (int i = 0; i < std::min(max_tok_display, (int)self_kq_mask->ne[0]); i++) {
        printf(data[row*self_kq_mask->ne[0] + i] == 0.0f ? "x" : ".");
    }
    printf("\n");
}
printf("\n\n\n\n"); // GGML_ABORT("test");
```

### CODE REVIEW

File: include/llama.h [hunk 1]
```diff
@@ -208,6 +208,7 @@ extern "C" {
         LLAMA_ATTENTION_TYPE_UNSPECIFIED = -1,
         LLAMA_ATTENTION_TYPE_CAUSAL      = 0,
         LLAMA_ATTENTION_TYPE_NON_CAUSAL  = 1,
+        LLAMA_ATTENTION_TYPE_CAUSAL_FULL = 2, // used by gemma 3, allowing image to attention to past tokens
```
Comment (ggerganov) [inline include/llama.h:211]:
```suggestion
        LLAMA_ATTENTION_TYPE_CAUSAL_FULL = 2, // used by gemma 3, allowing image to attend to past tokens
```

File: include/llama.h [hunk 2]
```diff
@@ -942,8 +943,12 @@ extern "C" {
     // If true, embeddings will be returned but logits will not
     LLAMA_API void llama_set_embeddings(struct llama_context * ctx, bool embeddings);
 
+    // Set the attention type
+    LLAMA_API void llama_set_attn_type(struct llama_context * ctx, enum llama_attention_type type);
+
     // Set whether to use causal attention or not
-    // If set to true, the model will only attend to the past tokens
+    // - true:  the model will only attend to the past tokens, alias of LLAMA_ATTENTION_TYPE_CAUSAL
+    // - false: alias of LLAMA_ATTENTION_TYPE_FULL
```
Comment (ggerganov) [inline include/llama.h:951]:
```suggestion
    // - false: alias of LLAMA_ATTENTION_TYPE_NON_CAUSAL
```

File: src/llama-cparams.h [hunk 3]
```diff
@@ -25,14 +25,19 @@ struct llama_cparams {
...
     bool offload_kqv;
     bool flash_attn;
     bool no_perf;
     bool warmup;
 
+    enum llama_attention_type attn_type;
+
     enum llama_pooling_type pooling_type;
 
+    bool use_past_tokens() const {
```
Comment (ggerganov) [inline src/llama-cparams.h:37]:
```suggestion
    bool attend_past_tokens() const {
```

File: src/llama-graph.cpp [hunk 4]
```diff
@@ -403,12 +403,14 @@ void llm_graph_input_attn_no_cache::set_input(const llama_ubatch * ubatch) {
 void llm_graph_input_attn_kv_unified::set_input(const llama_ubatch * ubatch) {
     if (self_kq_mask || self_kq_mask_swa) {
         // NOTE: hparams.causal_attn indicates the model is capable of generation and uses the kv cache.
-        if (cparams.causal_attn) {
+        if (cparams.use_past_tokens()) {
```
Comment (ggerganov) [inline src/llama-graph.cpp:406]: I think there is an alternative solution, that does not require to introduce a new attention type:

When `causal_attn == false`, all tokens in the current batch attend to each other, and also to everything that is before them in the KV cache.

So this check here has to be removed and the 2 branches can be merged into a single implementation. It would require an extra loop over the batch of tokens when `causal_attn == false`, to find the token with the minimum position.

It might be a bit more complicated, but I think it would be the better option, since it will not involve changing the interface.

Comment (ggerganov) [reply src/llama-graph.cpp:406]: > It would require an extra loop over the batch of tokens when causal_attn == false, to find the token with the minimum position in the batch.

Actually, this is probably not necessary - sorry for the confusion.

The main point is that the second use-case in the OP is not relevant:

```
Non-causal mask:
---xxxx---
---xxxx---
---xxxx---
---xxxx---
```

This is never used. For example, when running embeddings models, the entire sequence has to be passed as a single ubatch, and KV cache is not used.

WDYT?

Comment (ngxson) [reply src/llama-graph.cpp:406]: Yeah you're right @ggerganov on second thought, the case `---xxxx---` is never actually used since we always clear the KV before running non-causal embeddings to be able to use the full KV.

So yeah I agree that the API introduced in this API is redundant, I will extend the non-causal mask to include tokens in the past instead.

Btw, I also realized that my current logic may have produced this wrong mask:

```
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
```

Comment (ggerganov) [reply src/llama-graph.cpp:406]: We currently have 2 main paths:

- `llm_graph_input_attn_no_cache::set_input`
  Used by embeddings models like BERT that don't require KV cache. In this case, we always have `causal_attn == false`. There is also handling of the case for `causal_attn == true`, which technically can allow you to run non-embedding models (e.g llama) with causal attn, but none of the examples uses this, because it is very slow.
Anyway, this path does not require any changes.

- `llm_graph_input_attn_kv_unified::set_input`
  Here we have 2 cases:
  - `causal_attn == true`:  uses the KV cache (does not need any changes)
  - `causal_attn == false`: does not use the KV cache (basically the same as the "no_cache" path above). This case here has to be updated to start using the KV cache. If I am not mistaken, you can simply copy-paste the first case (i.e. `causal_attn == true`) and remove the position checks.

Let me know if you have doubts - I'm also not 100% sure that the above is entirely correct.

Comment (ngxson) [reply src/llama-graph.cpp:406]: > llm_graph_input_attn_kv_unified::set_input

> causal_attn == false: does not use the KV cache (basically the same as the "no_cache" path above). This case here has to be updated to start using the KV cache. If I am not mistaken, you can simply copy-paste the first case (i.e. causal_attn == true) and remove the position checks.

Yes this is what I discovered. I also include the code I used to visualize the mask in this PR's description.

The problem is that in this case, the mask layout seems to be different (i.e. the tensor shape). Using the visualization code above, it prints out this mask for a batch of 3 tokens:

```
self_kq_mask.shape 32, 64
n_tokens: 3
xxxxxxxxx...........
....................
....................
....................
```

So I expect that somewhere in the cgraph, we will reshape this tensor into a 3x3 matrix (though I still haven't found this code yet)

Another possibility is that the current code could be wrong. What I expected to see was:

```
self_kq_mask.shape 32, 64
n_tokens: 3
xxx.................
xxx.................
xxx.................
....................
```

Comment (ggerganov) [reply src/llama-graph.cpp:406]: Yes, on `master` this is broken. The only example that uses this path is currently Gemma vision and nothing else should go there.

File: src/llama-graph.cpp [hunk 5]
```diff
@@ -402,120 +402,86 @@ void llm_graph_input_attn_no_cache::set_input(const llama_ubatch * ubatch) {
...
+        // Example with a cache of 10 tokens, 2 tokens populated in cache and 3 tokens in batch:
+        //   Causal mask:
+        //      xxx-------
+        //      xxxx------
+        //      xxxxx-----
+        //   Non-causal mask:
+        //      xxxxx-----
+        //      xxxxx-----
+        //      xxxxx-----
+        // To visualize the mask, see https://github.com/ggml-org/llama.cpp/pull/12615
```
Comment (ngxson) [inline src/llama-graph.cpp:434]: I'm thinking, will it be a good idea to regroup some debugging tools / functions into a header called `llama-debug.h` (header-only) ? This can be included during development, and will be removed when people want to merge code on `master`

Comment (ggerganov) [reply src/llama-graph.cpp:434]: Yes, sounds good. We can have debugging code remain and guard it with environment variables similar to `GGML_SCHED_DEBUG`.

**Review by ggerganov — APPROVED** [review]
