### PR TITLE
mtmd: fix use_non_causal being reported incorrectly

### LINKED ISSUE #18757: Eval bug: llama-context.cpp:1443: GGML_ASSERT((cparams.causal_attn || cparams.n_ubatch >= n_tokens_all) && "non-causal attention requires n_ubatch >= n_tokens") failed
### Name and Version

llama-cli --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
version: 7700 (707cbafc)
built with GNU 14.2.0 for Linux x86_64

### Operating systems

Linux

### GGML backends

CUDA

### Hardware

CPU: 13th Gen Intel(R) Core(TM) i7-13700T (24) @ 4.90 GHz
GPU: NVIDIA GeForce RTX 3090 [Discrete]

### Models

634904 /usr/local/bin/llama-server --jinja -fa on -c 40960 -ngl 64 -v --log-timestamps --host 192.168.1.68 -m /mnt/nvme0n1/LLM/quantized/Qwen3VL-8B-Instruct-Q8_0.gguf --mmproj /mnt/nvme0n1/LLM/quantized/mmproj-Qwen3VL-8B-Instruct-Q8_0.gguf

### Problem description & steps to reproduce

I was running model without problems. Today I have upgraded with git log, and found this error:

```
srv    operator(): http: streamed chunk: data: {"choices":[{"finish_reason":null,"index":0,"delta":{"role":"assistant","content":null}}],"created":1768132902,"id":"chatcmpl-ZlIXQ830O5S22rStSI5QC5zHBzQO3jcW","model":"Qwen3VL-8B-Instruct-Q8_0.gguf","system_fingerprint":"b7700-707cbafc","object":"chat.completion.chunk","timings":{"cache_n":0,"prompt_n":12,"prompt_ms":0.0,"prompt_per_token_ms":0.0,"prompt_per_second":null,"predicted_n":0,"predicted_ms":0.0,"predicted_per_token_ms":null,"predicted_per_second":null},"prompt_progress":{"total":708,"cache":0,"processed":12,"time_ms":12}}
 
 
encoding image slice...
image slice encoded in 261 ms
set_causal_attn: value = 0
decoding image batch 1/1, n_tokens_batch = 690
/mnt/nvme0n1/LLM/git/llama.cpp/src/llama-context.cpp:1443: GGML_ASSERT((cparams.causal_attn || cparams.n_ubatch >= n_tokens_all) && "non-causal attention requires n_ubatch >= n_tokens") failed
/usr/local/lib/libggml-base.so.0(+0x13d65) [0x7f0a979ead65]
/usr/local/lib/libggml-base.so.0(ggml_print_backtrace+0x1df) [0x7f0a979eb12f]
/usr/local/lib/libggml-base.so.0(ggml_abort+0x11e) [0x7f0a979eb2be]
/usr/local/lib/libllama.so.0(_ZN13llama_context6decodeERK11llama_batch+0x1902) [0x7f0a976ad422]
/usr/local/lib/libllama.so.0(llama_decode+0xb) [0x7f0a976ad6bb]
/usr/local/lib/libmtmd.so.0(mtmd_helper_decode_image_chunk+0xd55) [0x7f0a97b0af25]
/usr/local/lib/libmtmd.so.0(mtmd_helper_eval_chunk_single+0x13f) [0x7f0a97b0c7ef]
/usr/local/bin/llama-server(+0xcd3ff) [0x56032a1963ff]
/usr/local/bin/llama-server(+0x12242d) [0x56032a1eb42d]
/usr/local/bin/llama-server(+0x15dc2f) [0x56032a226c2f]
/usr/local/bin/llama-server(+0x90784) [0x56032a159784]
/lib/x86_64-linux-gnu/libc.so.6(+0x29ca8) [0x7f0a97033ca8]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f0a97033d65]
/usr/local/bin/llama-server(+0x92bc1) [0x56032a15bbc1]
```

### First Bad Commit

_No response_

### Relevant log output

res          send: task id = 0 pushed to result queue
srv  update_slots: run slots completed
que    start_loop: waiting for new tasks
que    start_loop: processing new tasks
que    start_loop: processing task, id = 1
que    start_loop: update slots
srv  update_slots: posting NEXT_RESPONSE
que          post: new task, id = 2, front = 0
srv  update_chat_: Parsing chat message: 
slot update_slots: id  3 | task 0 | n_tokens = 12, memory_seq_rm [12, end)
Parsing input with format Hermes 2 Pro: 
srv  process_chun: processing image...
srv    operator(): http: streamed chunk: data: {"choices":[{"finish_reason":null,"index":0,"delta":{"role":"assistant","content":null}}],"created":1768132902,"id":"chatcmpl-ZlIXQ830O5S22rStSI5QC5zHBzQO3jcW","model":"Qwen3VL-8B-Instruct-Q8_0.gguf","system_fingerprint":"b7700-707cbafc","object":"chat.completion.chunk","timings":{"cache_n":0,"prompt_n":12,"prompt_ms":0.0,"prompt_per_token_ms":0.0,"prompt_per_second":null,"predicted_n":0,"predicted_ms":0.0,"predicted_per_token_ms":null,"predicted_per_second":null},"prompt_progress":{"total":708,"cache":0,"processed":12,"time_ms":12}}
 
 
encoding image slice...
image slice encoded in 261 ms
set_causal_attn: value = 0
decoding image batch 1/1, n_tokens_batch = 690
/mnt/nvme0n1/LLM/git/llama.cpp/src/llama-context.cpp:1443: GGML_ASSERT((cparams.causal_attn || cparams.n_ubatch >= n_tokens_all) && "non-causal attention requires n_ubatch >= n_tokens") failed
/usr/local/lib/libggml-base.so.0(+0x13d65) [0x7f0a979ead65]
/usr/local/lib/libggml-base.so.0(ggml_print_backtrace+0x1df) [0x7f0a979eb12f]
/usr/local/lib/libggml-base.so.0(ggml_abort+0x11e) [0x7f0a979eb2be]
/usr/local/lib/libllama.so.0(_ZN13llama_context6decodeERK11llama_batch+0x1902) [0x7f0a976ad422]
/usr/local/lib/libllama.so.0(llama_decode+0xb) [0x7f0a976ad6bb]
/usr/local/lib/libmtmd.so.0(mtmd_helper_decode_image_chunk+0xd55) [0x7f0a97b0af25]
/usr/local/lib/libmtmd.so.0(mtmd_helper_eval_chunk_single+0x13f) [0x7f0a97b0c7ef]
/usr/local/bin/llama-server(+0xcd3ff) [0x56032a1963ff]
/usr/local/bin/llama-server(+0x12242d) [0x56032a1eb42d]
/usr/local/bin/llama-server(+0x15dc2f) [0x56032a226c2f]
/usr/local/bin/llama-server(+0x90784) [0x56032a159784]
/lib/x86_64-linux-gnu/libc.so.6(+0x29ca8) [0x7f0a97033ca8]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f0a97033d65]
/usr/local/bin/llama-server(+0x92bc1) [0x56032a15bbc1]

### PR DESCRIPTION
**Pull request by ngxson**
Error spotted by LM Studio team

Fix https://github.com/ggml-org/llama.cpp/issues/18757

### CODE REVIEW

File: tools/mtmd/mtmd.cpp [hunk 1]
```diff
@@ -863,18 +860,23 @@ float * mtmd_get_output_embd(mtmd_context * ctx) {
 
 bool mtmd_decode_use_non_causal(mtmd_context * ctx) {
     switch (ctx->proj_type_v()) {
-        case PROJECTOR_TYPE_QWEN2VL:
-        case PROJECTOR_TYPE_QWEN25VL:
-        case PROJECTOR_TYPE_QWEN3VL:
-        case PROJECTOR_TYPE_YOUTUVL:
+        case PROJECTOR_TYPE_GEMMA3:
```
Comment (ngxson) [inline tools/mtmd/mtmd.cpp:863]: note: I verified transformers code and confirmed that gemma3n doesn't use causal mask (i.e. "bidirectional mask")

**Review by ggerganov — APPROVED** [review]

**Review by CISC — APPROVED** [review]
