### PR TITLE
`server`: update deepseek reasoning format (pass reasoning_content as diffs)

### LINKED ISSUE #13867: Misc. bug: Reasoning content is not separated when streaming
### Name and Version

version: 5523 (aa6dff05)
built with cc (GCC) 15.1.1 20250425 for x86_64-pc-linux-gnu

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
llama-server -m models/Qwen3-30B-A3B-IQ4_XS.gguf --jinja
```

### Problem description & steps to reproduce

Thinking content should be separated when streaming too.

@ochafik in #12379 said:
> Note: Ideally, we'd stream the thoughts as a reasoning_content delta (now trivial to implement), but for now we are just aiming for compatibility w/ DeepSeek's API (if --reasoning-format deepseek, which is the default).

I just tested using the official deepseek API and thoughts are separated.

Official deepseek API:
`"choices":[{"index":0,"delta":{"content":null,"reasoning_content":"Okay"},"logprobs":null,"finish_reason":null}]}`
llama.cpp server API:
`"choices":[{"finish_reason":null,"index":0,"delta":{"content":"<think>Okay"}}]`

### PR DESCRIPTION
**Pull request by ochafik**
Fixes https://github.com/ggml-org/llama.cpp/issues/13867

(~~updated / simplified webui accordingly~~ edit: reverted UI changes, will let @ngxson update it as follow up)

### CODE REVIEW

**Review by CISC — APPROVED** [review]

File: tools/server/webui/src/components/ChatMessage.tsx [hunk 1]
```diff
@@ -55,32 +49,6 @@ export default function ChatMessage({
...
-  // TODO: implement this as remark/rehype plugin in the future
-  const { content, thought, isThinking }: SplitMessage = useMemo(() => {
-    if (msg.content === null || msg.role !== 'assistant') {
-      return { content: msg.content };
-    }
-    let actualContent = '';
-    let thought = '';
-    let isThinking = false;
-    let thinkSplit = msg.content.split('<think>', 2);
-    actualContent += thinkSplit[0];
```
Comment (ngxson) [inline tools/server/webui/src/components/ChatMessage.tsx:68]: If user doesn't explicitly enable `deepseek` reasoning format (which is the default behavior), this code is there to make sure the thinking is always parsed.

Unless we can control thinking format per-request, I don't think we can remove this code block

File: tools/server/webui/src/utils/types.ts [hunk 2]
```diff
@@ -112,6 +113,7 @@ export interface ViewingChat {
 
 export type PendingMessage = Omit<Message, 'content'> & {
   content: string | null;
+  reasoningContent: string | null;
```
Comment (ngxson) [inline tools/server/webui/src/utils/types.ts:116]: Tbh I'm not very confident adding this, because it is not future-proof.

If you look at how chatgpt structure their message, the `content` is an array instead of a string, and that is what I wanted to do in near future. It will allow different message parts, like for example a message can contains both reasoning, text response and a tool call

**Review by ngxson — CHANGES_REQUESTED** [review]
I think I will redo the frontend changes in a more structured way, can you maybe revert these changes?

For now, I think it's worth adding a per-request reasoning format control

File: tools/server/webui/src/components/ChatMessage.tsx (hunk 1 above)
Comment (ochafik) [reply tools/server/webui/src/components/ChatMessage.tsx]: reverted UI changes

File: common/arg.cpp [hunk 3]
```diff
@@ -2869,6 +2869,7 @@ common_params_context common_params_parser_init(common_params & params, llama_ex
         "(default: deepseek)",
         [](common_params & params, const std::string & value) {
             /**/ if (value == "deepseek") { params.reasoning_format = COMMON_REASONING_FORMAT_DEEPSEEK; }
+            else if (value == "deepseek-legacy") { params.reasoning_format = COMMON_REASONING_FORMAT_DEEPSEEK_LEGACY; }
```
Comment (ngxson) [inline common/arg.cpp:2872]: should we add a help message to explain this mode?

**Review by ngxson — APPROVED** [review]
