### PR TITLE
vulkan: disable mmvq on Intel Windows driver

### LINKED ISSUE #17628: Misc. bug: Vulkan's performance degradation(TG) on A770 from b7189 and FA problem
### Name and Version

llama-cli -v
load_backend: loaded RPC backend from C:\llm\llama-cpp\VULKAN\b7209\ggml-rpc.dll
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = Intel(R) Arc(TM) A770 Graphics (Intel Corporation) | uma: 0 | fp16: 1 | bf16: 0 | warp size: 32 | shared memory: 32768 | int dot: 1 | matrix cores: none
load_backend: loaded Vulkan backend from C:\llm\llama-cpp\VULKAN\b7209\ggml-vulkan.dll
load_backend: loaded CPU backend from C:\llm\llama-cpp\VULKAN\b7209\ggml-cpu-haswell.dll
build: 7209 (7f8ef50cc) with clang version 19.1.5 for x86_64-pc-windows-msvc

### Operating systems

Windows

### Which llama.cpp modules do you know to be affected?

llama-bench

### Command line

```shell
llama-bench -m T:\models\lmstudio-community\gpt-oss-20b-GGUF\gpt-oss-20b-MXFP4.gguf  -ngl 100 -fa 0,1


llama-bench -m T:\models\TheBloke\Llama-2-7B-GGUF\llama-2-7b.Q4_0.gguf -ngl 100 -fa 0,1


llama-bench -m T:\models\lmstudio-community\Meta-Llama-3.1-8B-Instruct-GGUF\Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf -ngl 100 -fa 0,1
```

### Problem description & steps to reproduce

Hello.

Drop in token generation (TG) performance compared to the B7189 version on the Intel Arc A770.
Between b7189 and b7209.

Driver: 8250
cpu: xeon 2699v3 x2
GPU: 1x A770

Models:
53 -> 42 t/s lmstudio-community\Meta-Llama-3.1-8B-Instruct-GGUF\Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf
60 -> 54 t/s lmstudio-community\gpt-oss-20b-GGUF\gpt-oss-20b-MXFP4.gguf

### B7209
```
| model                          |       size |     params | backend    | ngl | fa |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | --------------: | -------------------: |
| llama 8B Q4_K - Medium         |   4.58 GiB |     8.03 B | Vulkan     | 100 |  0 |           pp512 |        921.00 ± 3.22 |
| llama 8B Q4_K - Medium         |   4.58 GiB |     8.03 B | Vulkan     | 100 |  0 |           tg128 |         42.39 ± 0.07 |
| llama 8B Q4_K - Medium         |   4.58 GiB |     8.03 B | Vulkan     | 100 |  1 |           pp512 |        280.12 ± 0.44 |
| llama 8B Q4_K - Medium         |   4.58 GiB |     8.03 B | Vulkan     | 100 |  1 |           tg128 |         29.39 ± 0.02 |

build: 7f8ef50cc (7209)
```
**sometimes flash attention crashes (with no error, The bench just stops)**
Image

```
| model                          |       size |     params | backend    | ngl | fa |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | --------------: | -------------------: |
| gpt-oss 20B MXFP4 MoE          |  11.27 GiB |    20.91 B | Vulkan     | 100 |  0 |           pp512 |        885.48 ± 5.59 |
| gpt-oss 20B MXFP4 MoE          |  11.27 GiB |    20.91 B | Vulkan     | 100 |  0 |           tg128 |         54.20 ± 0.07 |
```

### B7189

```
| model                          |       size |     params | backend    | ngl | fa |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | --------------: | -------------------: |
| llama 8B Q4_K - Medium         |   4.58 GiB |     8.03 B | Vulkan     | 100 |  0 |           pp512 |        918.06 ± 4.28 |
| llama 8B Q4_K - Medium         |   4.58 GiB |     8.03 B | Vulkan     | 100 |  0 |           tg128 |         53.63 ± 0.10 |
| llama 8B Q4_K - Medium         |   4.58 GiB |     8.03 B | Vulkan     | 100 |  1 |           pp512 |        280.26 ± 0.70 |
| llama 8B Q4_K - Medium         |   4.58 GiB |     8.03 B | Vulkan     | 100 |  1 |           tg128 |         34.50 ± 0.04 |
```

```
| model                          |       size |     params | backend    | ngl | fa |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | -: | --------------: | -------------------: |
| gpt-oss 20B MXFP4 MoE          |  11.27 GiB |    20.91 B | Vulkan     | 100 |  0 |           pp512 |        884.45 ± 5.87 |
| gpt-oss 20B MXFP4 MoE          |  11.27 GiB |    20.91 B | Vulkan     | 100 |  0 |           tg128 |         60.95 ± 0.06 |
```

### First Bad Commit

Between b7189 and b7209

### PR DESCRIPTION
**Pull request by 0cc4m**
Fixes #17628 

@savvadesogle This disables MMVQ entirely on Intel Windows, that should remove the need to use the env var. Please try it.

### CODE REVIEW

**Comment by savvadesogle** [comment]
Hello Ruben!

Thank you very much, and I'm sorry for bothering you with my Intel GPU...

изображение

File: ggml/src/ggml-vulkan/ggml-vulkan.cpp [hunk 1]
```diff
@@ -7629,20 +7629,13 @@ static bool ggml_vk_should_use_mmvq(const vk_device& device, uint32_t m, uint32_
             return true;
         }
     case VK_VENDOR_ID_INTEL:
-        if (k < 2048) {
+        if (device->driver_id == vk::DriverId::eIntelProprietaryWindows) {
+            // Intel Windows proprietary driver does not like MMVQ
```
Comment (jeffbolznv) [inline ggml/src/ggml-vulkan/ggml-vulkan.cpp]: Would be helpful to say whether there are functional issues or if this is just performance tuning.

**Review by jeffbolznv — APPROVED** [review]

File: ggml/src/ggml-vulkan/ggml-vulkan.cpp (hunk 1 above)
Comment (0cc4m) [reply ggml/src/ggml-vulkan/ggml-vulkan.cpp]: Fair, I improved the comment.

**Comment by 0cc4m** [comment]
> Thank you very much, and I'm sorry for bothering you with my Intel GPU...

No worries, it's good to get some performance data from Intel Windows, and to see it working decently well.

**Comment by gustrd** [comment]
Some additional info: disabling MMVQ also helps with stability, avoiding driver errors at Windows (ARC-140V).

**Comment by zero-one-soft** [comment]
I noticed something with this post, My intel b580 does not get nearly as high a score as the A770 
Screenshot 2026-03-18 073100
Screenshot 2026-03-18 072952

Am I doing something wrong or is it just the lack of more processing power ?

**Comment by savvadesogle** [comment]
Hi @zero-one-soft
Try to select the device 
```
set GGML_VK_VISIBLE_DEVICES=0
```
And which driver version do you have?

**Comment by zero-one-soft** [comment]
Hi @savvadesogle 
I am using intel driver 32.0.101.8531 
I did the set GGML_VK_VISIBLE_DEVICES=0 and I now get the following 
image
I am also experiencing random crashes where my pc would just freeze for a couple of seconds then the screen goes dark and the llama.server just stops , or the bench app 
on smaller models it does not happen to often but with the gpt-oss-20b it seems to happen more often 

also noticed that if i use the sycl binaries it is now even worse to run the benchmark on gpt-oss-20b. I get like 4 tokens/s 

smallers models seems to be still ok
image

**Comment by savvadesogle** [comment]
@zero-one-soft 
Try opening an issue and testing earlier builds.

ps
The speed on the smaller model is just great!

**Comment by savvadesogle** [comment]
@zero-one-soft 
It's very strange that you still see two devices after using the GGML_VK_VISIBLE_DEVICES variable. Double-check that you're entering the command correctly.
изображение


изображение

You can try another command in the new CMD
изображение

``` llama-bench -m model -ngl 100 -fa 0,1 -sm none -mg 0 ```

**Comment by 0cc4m** [comment]
The iGPU will not be used automatically, unless no dGPU is available. It is not necessary to hide it.

**Comment by savvadesogle** [comment]
Thanks Ruben, I didn't know that. Sorry for the misinformation. @0cc4m

**Comment by zero-one-soft** [comment]
@savvadesogle 
I did the set command in powershell that is why it did not do anything 
in CMD it works but does nothing for the speed issue 
image

I have had the situation where my Igpu and my CPU would also be processing something so offloading to the GPU is important, I tend to use the -mg 0 in all of my commands  just to make sure 

I will try your advice in terms of using other builds , or I will just use the smaller models , I was just curious why you managed to get such great performance on your A770 and my B580 struggles with that model :)

**Comment by savvadesogle** [comment]
> I was just curious why you managed to get such great performance on your A770 and my B580 struggles with that model :)

@zero-one-soft
Unfortunately, I don't know... We have a cool guy here and his name is Ruben! He's the master of Vulkan 💪.

But I managed to get a little more (https://github.com/ggml-org/llama.cpp/issues/17628#issuecomment-4018920296).
изображение


Come to our OpenArс community discord (https://github.com/SearchSavior/OpenArc), we have guys there who have B580 and B50/60 + if you need to, you can directly ask Jianyu (maintainer SYCL backend) about the SYCL backend

изображение

OpenVINO, llama.cpp, vLLM etc on Intel GPUs.
https://discord.gg/Pq9ZNyd9

**Comment by gustrd** [comment]
> I am also experiencing random crashes where my pc would just freeze for a couple of seconds then the screen goes dark and the llama.server just stops , or the bench app
on smaller models it does not happen to often but with the gpt-oss-20b it seems to happen more often

I think this kind of crash is called *TDR (Timeout Detection and Recovery)*. It also happens with my ARC-140 at Windows. Happens less with MMVQ disabled, but I had some even so. Seems like it stops only if I disable COOPMAT.

For sure it's an issue with the Intel Driver. Not sure if there are other ways to avoid.

**Comment by savvadesogle** [comment]
> I think this kind of crash is called _TDR (Timeout Detection and Recovery)_

@gustrd 
изображение
Does disabling energy saving help (+ASPM)?

**Comment by zero-one-soft** [comment]
It seems to me that my crashes happen with the bigger models more than the smaller 
I did install the newest intel driver today , the version is now 32.0.101.8626 with the vulkan driver being on 1.4.340 
so far i am not getting crashes so holding thumbs . hope it stopped now 

that link state power management is off on my machine , is that correct ?

**Comment by gustrd** [comment]
@savvadesogle , thank you!

I really believe you pinpointed the issue. After changing the power management I spent a whole day of intensive inference without a single TDR.

It should be published somewhere.
