### PR TITLE
webui: auto-refresh /props on inference start to resync model metadata

### LINKED ISSUE #16771: Misc. bug: WebUI incorrectly displays local model names
### Name and Version

version: 6821 (a2e0088d)

### Operating systems

Windows

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
llama-server --offline -m <some-model.gguf>
```

### Problem description & steps to reproduce

Starting from b6821, the webUI no longer correctly shows the model used to generate a response when running a model offline from a local GGUF file. The last release that this worked correctly was b6818.

### Steps to reproduce:

1. Run llama-server using a local GGUF file.
`llama-server --offline -m .\gemma-3-4b-it-Q6_K.gguf`
2. Launch the webUI. In the settings page, ensure that the checkbox for 'Show model information' under the 'General' tab is checked.
3. Start a conversation.
4. Close the server and restart it using a different local GGUF file.
`llama-server --offline -m .\Qwen3-4B-Instruct-2507-Q6_K.gguf`
5. Launch the webUI and either continue the previous conversation, regenerate the most recent response or start a new conversation.

**Expected behavior:**
The webUI should show the first message as generated by `gemma-3-4b-it-Q6_K.gguf` and the second message generated by `Qwen3-4B-Instruct-2507-Q6_K.gguf`.

Image

However, since b6821, all responses are instead shown as being generated by whichever local model is loaded.

Image

### First Bad Commit

Seems to have been introduced by commit [9b9201f](https://github.com/ggml-org/llama.cpp/commit/9b9201f65a22c02cee8e300f58f480a588591227)

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by ServeurpersoCom**
- Add no-cache headers to /props and /slots
- Throttle slot checks to 30s
- Prevent concurrent fetches with promise guard
- Trigger refresh from chat streaming for legacy and ModelSelector
- Show dynamic serverWarning when using cached data

- Updated assistant message bubbles to show each message's stored model when available,
  falling back to the current server model only when the per-message value is missing

- When the model selector is disabled, now fetches /props and prioritizes that model name
  over chunk metadata, then persists it with the streamed message so legacy mode properly
  reflects the backend configuration

Cmdline used on legacy (Raspberry Pi 5) :
```
/root/llama.cpp/build/bin/llama-server \
 -m /root/ia/models/mradermacher/OLMoE-1B-7B-0125-Instruct-i1-GGUF/OLMoE-1B-7B-0125-Instruct.i1-Q6_K.gguf \
 -ctk q8_0 -ctv q8_0 -fa on \
 --jinja --ctx-size 8192 --mlock --port 8081

/root/llama.cpp/build/bin/llama-server \
 -m /root/ia/models/mradermacher/OLMoE-1B-7B-0125-SFT-i1-GGUF/OLMoE-1B-7B-0125-SFT.i1-Q6_K.gguf \
 -ctk q8_0 -ctv q8_0 -fa on \
 --jinja --ctx-size 8192 --mlock --port 8081

/root/llama.cpp/build/bin/llama-server \
 -m /root/ia/models/mradermacher/Qwen3-30B-A3B-Instruct-2507-i1-GGUF/Qwen3-30B-A3B-Instruct-2507.i1-Q4_K_M.gguf \
 --temp 0.7 --top-p 0.8 --top-k 20 --min-p 0 \
 -ctk q8_0 -ctv q8_0 -fa on \
 --jinja --ctx-size 4096 --port 8081
```

Fixes https://github.com/ggml-org/llama.cpp/issues/16771

EDIT : I've recorded a video that specifically targets the original issue.
Testing video, Raspberry Pi 5 + master branch + this PR :

https://github.com/user-attachments/assets/c91e875e-aede-4323-be94-0ee79e6e3d6b

And another one to show there's no regression when the model selector is enabled,
also demonstrating the multimodal function updates:

https://github.com/user-attachments/assets/bcb1bf46-4b7e-4213-999f-6c60b79918a9

### CODE REVIEW

**Comment by ServeurpersoCom** [comment]
The final fix is done, now that the /props refresh is unified, the legacy mode (without the model selector) behaves correctly.
The message history now properly reflects the backend model used.

**Comment by ServeurpersoCom** [comment]
LEGACY MODE (modelSelectorEnabled = false)
  - Do not send "model" in requests
  - Ignore "model" from server responses
  - Read /props.model as the single source of truth
  - Refresh /props periodically or on stream start
  - UI and history reflect the backend model

MODEL SELECTOR MODE (modelSelectorEnabled = true)
  - Always send "model" in requests
  - Use per-message "model" from chunks or user selection
  - /props used only for backend capabilities (context, multimodal, slots)
  - UI reflects the user-selected model

Summary:
  Legacy -> backend decides the model via /props
  ModelSelector -> frontend decides the model via request field

File: tools/server/webui/src/lib/stores/chat.svelte.ts [hunk 1]
```diff
@@ -362,9 +363,87 @@ class ChatStore {
 
 		let resolvedModel: string | null = null;
 		let modelPersisted = false;
+		const PROPS_REFRESH_RETRY_DELAY_MS = 1_000;
```
Comment (allozaur) [inline tools/server/webui/src/lib/stores/chat.svelte.ts]: let's move this to `$lib/constants`

File: tools/server/webui/src/lib/stores/chat.svelte.ts [hunk 2]
```diff
@@ -362,9 +363,87 @@ class ChatStore {
...
+		let serverPropsRefreshRequested = false;
+		let lastPropsRefreshAttempt = 0;
+		const currentConfig = config();
+		const preferServerPropsModel = !currentConfig.modelSelectorEnabled;
+
+		const resetPropsRefreshGate = (options?: { immediate?: boolean }) => {
+			serverPropsRefreshRequested = false;
+			if (options?.immediate) {
```
Comment (allozaur) [inline tools/server/webui/src/lib/stores/chat.svelte.ts]:
```suggestion
			serverPropsRefreshRequested = false;

			if (options?.immediate) {
```

File: tools/server/webui/src/lib/stores/server.svelte.ts [hunk 3]
```diff
@@ -3,6 +3,8 @@ import { SERVER_PROPS_LOCALSTORAGE_KEY } from '$lib/constants/localstorage-keys'
 import { ChatService } from '$lib/services/chat';
 import { config } from '$lib/stores/settings.svelte';
 
+const SLOTS_CHECK_THROTTLE_MS = 30_000;
```
Comment (allozaur) [inline tools/server/webui/src/lib/stores/server.svelte.ts]: Let's move this to `$lib/constants`

**Review by allozaur — APPROVED** [review]
Yes, @ServeurpersoCom, that is much better than the initial idea for this PR 😄

**Comment by ServeurpersoCom** [comment]
> Yes, @ServeurpersoCom, that is much better than the initial idea for this PR 😄

Good thing the merge stashes everything, those intermediate commits were an emotional rollercoaster 😆 Glad we made it out alive 😆

**Comment by allozaur** [comment]
>  those intermediate commits were an emotional rollercoaster 😆

🤣

**Comment by ServeurpersoCom** [comment]
rebased to retry CI

**Comment by ServeurpersoCom** [comment]
Rebased + static build
