### PR TITLE
fix: /metrics endpoint returning JSON-escaped Prometheus format

### LINKED ISSUE #17384: Misc. bug: Metrics for prometheus now incorrectly formatted with 7010
### Name and Version

ggml_metal_device_init: tensor API disabled for pre-M5 and pre-A19 devices
ggml_metal_library_init: using embedded metal library
ggml_metal_library_init: loaded in 6.440 sec
ggml_metal_device_init: GPU name:   Apple M3 Ultra
ggml_metal_device_init: GPU family: MTLGPUFamilyApple9  (1009)
ggml_metal_device_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_device_init: GPU family: MTLGPUFamilyMetal4  (5002)
ggml_metal_device_init: simdgroup reduction   = true
ggml_metal_device_init: simdgroup matrix mul. = true
ggml_metal_device_init: has unified memory    = true
ggml_metal_device_init: has bfloat            = true
ggml_metal_device_init: has tensor            = false
ggml_metal_device_init: use residency sets    = true
ggml_metal_device_init: use shared buffers    = true
ggml_metal_device_init: recommendedMaxWorkingSetSize  = 532575.94 MB
version: 7100 (c49daff5b)
built with Apple clang version 17.0.0 (clang-1700.4.4.1) for arm64-apple-darwin25.1.0

### Operating systems

Mac

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
llama-server -m qwen480.gguf --host 0.0.0.0 --port 1235 -ngl 99 --ctx-size 393216 --parallel 2 --metrics --mlock --no-mmap --jinja -fa on --temp 0.7 --min-p 0.0 --top-p 0.8 --top-k 20 --repeat-penalty 1.05
```

### Problem description & steps to reproduce

Metrics are coming back as a quoted string from /metrics:

"# HELP llamacpp:prompt_tokens_total Number of prompt tokens processed.\n# TYPE llamacpp:prompt_tokens_total counter\nllamacpp:prompt_tokens_total 0\n# HELP llamacpp:prompt_seconds_total Prompt process time\n# TYPE llamacpp:prompt_seconds_total counter\nllamacpp:prompt_seconds_total 0\n# HELP llamacpp:tokens_predicted_total Number of generation tokens processed.\n# TYPE llamacpp:tokens_predicted_total counter\nllamacpp:tokens_predicted_total 0\n# HELP llamacpp:tokens_predicted_seconds_total Predict process time\n# TYPE llamacpp:tokens_predicted_seconds_total counter\nllamacpp:tokens_predicted_seconds_total 0\n# HELP llamacpp:n_decode_total Total number of llama_decode() calls\n# TYPE llamacpp:n_decode_total counter\nllamacpp:n_decode_total 8\n# HELP llamacpp:n_tokens_max Largest observed n_tokens.\n# TYPE llamacpp:n_tokens_max counter\nllamacpp:n_tokens_max 16384\n# HELP llamacpp:n_busy_slots_per_decode Average number of busy slots per llama_decode() call\n# TYPE llamacpp:n_busy_slots_per_decode counter\nllamacpp:n_busy_slots_per_decode 1\n# HELP llamacpp:prompt_tokens_seconds Average prompt throughput in tokens/s.\n# TYPE llamacpp:prompt_tokens_seconds gauge\nllamacpp:prompt_tokens_seconds 0\n# HELP llamacpp:predicted_tokens_seconds Average generation throughput in tokens/s.\n# TYPE llamacpp:predicted_tokens_seconds gauge\nllamacpp:predicted_tokens_seconds 0\n# HELP llamacpp:requests_processing Number of requests processing.\n# TYPE llamacpp:requests_processing gauge\nllamacpp:requests_processing 1\n# HELP llamacpp:requests_deferred Number of requests deferred.\n# TYPE llamacpp:requests_deferred gauge\nllamacpp:requests_deferred 0\n"

### First Bad Commit

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by o7si**
The `/metrics` endpoint returns Prometheus-format text that is incorrectly JSON-escaped, causing the output to be wrapped in double quotes, which prevents Prometheus from parsing it correctly.

Related code snippets:

https://github.com/ggml-org/llama.cpp/blob/2eba631b8127a5a4853ea625a0eac4a7449bc7b8/tools/server/server.cpp#L4567

https://github.com/ggml-org/llama.cpp/blob/2eba631b8127a5a4853ea625a0eac4a7449bc7b8/tools/server/server.cpp#L4441-L4444

I added an `ok()` overload with a `std::string` parameter to fix this issue.

Related issue:
- #17384

Note: I've checked other calls to `ok()` and they all pass JSON types, so this issue won't occur elsewhere.

### CODE REVIEW

File: tools/server/server.cpp [hunk 1]
```diff
@@ -4442,6 +4442,10 @@ struct server_res_generator : server_http_res {
         status = 200;
         data = safe_json_to_str(response_data);
     }
+    void ok(const std::string & response_data) {
+        status = 200;
+        data = response_data;
+    }
```
Comment (ngxson) [inline tools/server/server.cpp]: I don't think it's a safe solution as `std::string` can also be a valid json.

Instead, you can simply set the status and data directly in the `handle_metrics` without using `ok()` macro

**Review by ngxson — CHANGES_REQUESTED** [review]

File: tools/server/server.cpp (hunk 1 above)
Comment (o7si) [reply tools/server/server.cpp]: Hi, @ngxson Thank you for the guidance!

After thinking about it carefully, the situation you described with `I don't think it's a safe solution as std::string can also be a valid json.` does indeed exist.

I noticed that all handlers return by calling either `error` or `ok` to set the HTTP response. To make the code look more consistent, I avoided using this approach in the handler functions:

```cpp
res->status = 200;
res->data = prometheus.str();
```
My original thinking was:

For JSON type return values, call this signature: `ok(const json & response_data)`
For string type return values, call this signature: `ok(const std::string & response_data)`

So I'm wondering which approach would be better - should I simply use:

```cpp
res->status = 200;
res->data = prometheus.str();
```

Or should I define specific methods like:

```cpp
void ok_json(const json & response_data);
void ok_text(const std::string & response_data);  
void ok_html(const std::string & response_data);
```

Or is there another approach you'd recommend? 

I want to maintain consistency with the existing codebase while properly handling different response content types.

**Comment by o7si** [comment]
Hi, I chose the simplest approach:

```cpp
res->status = 200;
res->data = prometheus.str();
```

When requesting via curl command, the output is as follows:

```bash
curl http://127.0.0.1:8080/metrics
```
```
# HELP llamacpp:prompt_tokens_total Number of prompt tokens processed.
# TYPE llamacpp:prompt_tokens_total counter
llamacpp:prompt_tokens_total 30
# HELP llamacpp:prompt_seconds_total Prompt process time
# TYPE llamacpp:prompt_seconds_total counter
llamacpp:prompt_seconds_total 0.152
# HELP llamacpp:tokens_predicted_total Number of generation tokens processed.
# TYPE llamacpp:tokens_predicted_total counter
llamacpp:tokens_predicted_total 10
# HELP llamacpp:tokens_predicted_seconds_total Predict process time
# TYPE llamacpp:tokens_predicted_seconds_total counter
llamacpp:tokens_predicted_seconds_total 0.299
# HELP llamacpp:n_decode_total Total number of llama_decode() calls
# TYPE llamacpp:n_decode_total counter
llamacpp:n_decode_total 10
# HELP llamacpp:n_tokens_max Largest observed n_tokens.
# TYPE llamacpp:n_tokens_max counter
llamacpp:n_tokens_max 39
# HELP llamacpp:n_busy_slots_per_decode Average number of busy slots per llama_decode() call
# TYPE llamacpp:n_busy_slots_per_decode counter
llamacpp:n_busy_slots_per_decode 1
# HELP llamacpp:prompt_tokens_seconds Average prompt throughput in tokens/s.
# TYPE llamacpp:prompt_tokens_seconds gauge
llamacpp:prompt_tokens_seconds 197.368
# HELP llamacpp:predicted_tokens_seconds Average generation throughput in tokens/s.
# TYPE llamacpp:predicted_tokens_seconds gauge
llamacpp:predicted_tokens_seconds 33.4448
# HELP llamacpp:requests_processing Number of requests processing.
# TYPE llamacpp:requests_processing gauge
llamacpp:requests_processing 0
# HELP llamacpp:requests_deferred Number of requests deferred.
# TYPE llamacpp:requests_deferred gauge
llamacpp:requests_deferred 0
```

**Review by ngxson — APPROVED** [review]
sorry I missed the latest commit. merging it now
