### PR TITLE
model : disable SWA for Phi models

### LINKED ISSUE #13665: Eval bug: phi-4 crashes with new versions
### Name and Version

```
llama-cli --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: yes
register_backend: registered backend CUDA (1 devices)
register_device: registered device CUDA0 (NVIDIA GeForce RTX 3060)
register_backend: registered backend BLAS (1 devices)
register_device: registered device BLAS (OpenBLAS)
register_backend: registered backend RPC (0 devices)
register_backend: registered backend CPU (1 devices)
register_device: registered device CPU (AMD Ryzen 7 3800X 8-Core Processor)
version: 5435 (a4090d117)
built with cc (GCC) 15.1.1 20250425 for x86_64-pc-linux-gnu
```

### Operating systems

Linux

### GGML backends

CUDA

### Hardware

Nvidia 3060 12Gb
AMD Ryzen 7 3800X 8-Core

### Models

Original MS build phi-4-Q4_K.gguf

### Problem description & steps to reproduce

Last working version is b5426, after that llama-cli crashes with 'Segmentation fault'

Command: `llama-cli -m /home/ftp/AI/microsoft/phi-4-gguf/phi-4-Q4_K.gguf -st --simple-io --flash-attn --no-display-prompt -ngl 41 --threads 8 --temp 0.25 --top-p 0.95 --ctx-size 2048 -p "$(cat ~/dox/AI/PROMPT.txt)"`

Workaround: downgrade to b5426

### First Bad Commit

b5429 (supposedly)

### Relevant log output

```shell
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: yes
register_backend: registered backend CUDA (1 devices)
register_device: registered device CUDA0 (NVIDIA GeForce RTX 3060)
register_backend: registered backend BLAS (1 devices)
register_device: registered device BLAS (OpenBLAS)
register_backend: registered backend RPC (0 devices)
register_backend: registered backend CPU (1 devices)
register_device: registered device CPU (AMD Ryzen 7 3800X 8-Core Processor)
build: 5435 (a4090d117) with cc (GCC) 15.1.1 20250425 for x86_64-pc-linux-gnu (debug)
main: llama backend init
main: load the model and apply lora adapter, if any
llama_model_load_from_file_impl: using device CUDA0 (NVIDIA GeForce RTX 3060) - 10769 MiB free
llama_model_loader: loaded meta data with 33 key-value pairs and 243 tensors from /home/ftp/AI/microsoft/phi-4-gguf/phi-4-Q4_K.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = phi3
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Phi 4
llama_model_loader: - kv   3:                            general.version str              = 4
llama_model_loader: - kv   4:                       general.organization str              = Microsoft
llama_model_loader: - kv   5:                           general.basename str              = phi
llama_model_loader: - kv   6:                         general.size_label str              = 15B
llama_model_loader: - kv   7:                            general.license str              = mit
llama_model_loader: - kv   8:                       general.license.link str              = https://huggingface.co/microsoft/phi-...
llama_model_loader: - kv   9:                               general.tags arr[str,7]       = ["phi", "nlp", "math", "code", "chat"...
llama_model_loader: - kv  10:                          general.languages arr[str,1]       = ["en"]
llama_model_loader: - kv  11:                        phi3.context_length u32              = 16384
llama_model_loader: - kv  12:  phi3.rope.scaling.original_context_length u32              = 16384
llama_model_loader: - kv  13:                      phi3.embedding_length u32              = 5120
llama_model_loader: - kv  14:                   phi3.feed_forward_length u32              = 17920
llama_model_loader: - kv  15:                           phi3.block_count u32              = 40
llama_model_loader: - kv  16:                  phi3.attention.head_count u32              = 40
llama_model_loader: - kv  17:               phi3.attention.head_count_kv u32              = 10
llama_model_loader: - kv  18:      phi3.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  19:                  phi3.rope.dimension_count u32              = 128
llama_model_loader: - kv  20:                        phi3.rope.freq_base f32              = 250000.000000
llama_model_loader: - kv  21:              phi3.attention.sliding_window u32              = 0
llama_model_loader: - kv  22:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  23:                         tokenizer.ggml.pre str              = dbrx
llama_model_loader: - kv  24:                      tokenizer.ggml.tokens arr[str,100352]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  25:                  tokenizer.ggml.token_type arr[i32,100352]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  26:                      tokenizer.ggml.merges arr[str,100000]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  27:                tokenizer.ggml.bos_token_id u32              = 100257
llama_model_loader: - kv  28:                tokenizer.ggml.eos_token_id u32              = 100265
llama_model_loader: - kv  29:            tokenizer.ggml.padding_token_id u32              = 100349
llama_model_loader: - kv  30:                    tokenizer.chat_template str              = {% for message in messages %}{% if (m...
llama_model_loader: - kv  31:               general.quantization_version u32              = 2
llama_model_loader: - kv  32:                          general.file_type u32              = 15
llama_model_loader: - type  f32:   81 tensors
llama_model_loader: - type q4_K:  101 tensors
llama_model_loader: - type q5_K:   40 tensors
llama_model_loader: - type q6_K:   21 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 8.43 GiB (4.94 BPW) 
load: special tokens cache size = 96
load: token to piece cache size = 0.6151 MB
print_info: arch             = phi3
print_info: vocab_only       = 0
print_info: n_ctx_train      = 16384
print_info: n_embd           = 5120
print_info: n_layer          = 40
print_info: n_head           = 40
print_info: n_head_kv        = 10
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: n_swa_pattern    = 1
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 4
print_info: n_embd_k_gqa     = 1280
print_info: n_embd_v_gqa     = 1280
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-05
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 17920
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = 0
print_info: rope type        = 2
print_info: rope scaling     = linear
print_info: freq_base_train  = 250000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 16384
print_info: rope_finetuned   = unknown
print_info: ssm_d_conv       = 0
print_info: ssm_d_inner      = 0
print_info: ssm_d_state      = 0
print_info: ssm_dt_rank      = 0
print_info: ssm_dt_b_c_rms   = 0
print_info: model type       = 14B
print_info: model params     = 14.66 B
print_info: general.name     = Phi 4
print_info: vocab type       = BPE
print_info: n_vocab          = 100352
print_info: n_merges         = 100000
print_info: BOS token        = 100257 '<|endoftext|>'
print_info: EOS token        = 100265 '<|im_end|>'
print_info: EOT token        = 100265 '<|im_end|>'
print_info: PAD token        = 100349 '<|dummy_85|>'
print_info: LF token         = 198 'Ċ'
print_info: FIM PRE token    = 100258 '<|fim_prefix|>'
print_info: FIM SUF token    = 100260 '<|fim_suffix|>'
print_info: FIM MID token    = 100259 '<|fim_middle|>'
print_info: EOG token        = 100257 '<|endoftext|>'
print_info: EOG token        = 100265 '<|im_end|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: offloading 40 repeating layers to GPU
load_tensors: offloading output layer to GPU
load_tensors: offloaded 41/41 layers to GPU
load_tensors:        CUDA0 model buffer size =  8354.71 MiB
load_tensors:   CPU_Mapped model buffer size =   275.62 MiB
.......................................................................................
llama_context: constructing llama_context
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 2048
llama_context: n_ctx_per_seq = 2048
llama_context: n_batch       = 2048
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = 1
llama_context: freq_base     = 250000.0
llama_context: freq_scale    = 1
llama_context: n_ctx_per_seq (2048) < n_ctx_train (16384) -- the full capacity of the model will not be utilized
llama_context:  CUDA_Host  output buffer size =     0.38 MiB
llama_kv_cache_unified:      CUDA0 KV buffer size =   400.00 MiB
llama_kv_cache_unified: size =  400.00 MiB (  2048 cells,  40 layers), K (f16):  200.00 MiB, V (f16):  200.00 MiB
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by ggerganov**
fix #13665

It seems that there is some confusion with the Phi models configs. It is not clear what is the SWA window and to which layers it is applied.

As an example, if we look at [Phi-3-mini-4k](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/blob/main/config.json) it says that the sliding window is 2047, but there is no field that specifies the SWA layers. Another example is [Phi-3.5-MoE](https://huggingface.co/microsoft/Phi-3.5-MoE-instruct/blob/main/config.json#L172) which has a sliding window equal to the context size - so technically there is no SWA.

So for now I think the simplest solution is to disable SWA for this family of models and to at least avoid breaking the latest Phi-4 that do not rely on SWA.

### CODE REVIEW

**Comment by ngxson** [comment]
FWIW, many configs of phi-3-mini are hard-coded inside python code, so it won't even take the one from `config.json`. I had a hard time finding some of the configs in [modeling_phi3.py](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/blob/main/modeling_phi3.py) before giving up on adding vision support for it.

File: src/llama-model.cpp [hunk 1]
```diff
@@ -853,43 +853,16 @@ void llama_model::load_hparams(llama_model_loader & ml) {
                     default: type = LLM_TYPE_UNKNOWN;
                 }
 
-                // for backward compatibility ; see: https://github.com/ggerganov/llama.cpp/pull/8931
-                if ((hparams.n_layer == 32 || hparams.n_layer == 40) && hparams.n_ctx_train == 4096) {
-                    // default value for Phi-3-mini-4k-instruct and Phi-3-medium-4k-instruct
-                    LLAMA_LOG_WARN("%s: assuming n_swa = 2047 for Phi-3-mini-4k-instruct and Phi-3-medium-4k-instruct\n", __func__);
```
Comment (ngxson) [inline src/llama-model.cpp:859]: Sorry I didn't saw your review request.

Hmm I think these configs still need to be kept. The original issue talked about phi-4 and not phi-3, and these branches of code was to make sure old phi-3 model works correctly.

Probably phi-4 conflicts with this but I'll have a look. In anw, I think `n_swa` should still be set, so that the model can mask out tokens correctly for long sequence.

Comment (ggerganov) [reply src/llama-model.cpp:859]: The problem is that `n_swa` value never does anything when `n_swa_pattern == 1`, which has always been like this. So unless I am missing something, these configs didn't do anything.

**Comment by ngxson** [comment]
Ok so the problem seems to be isolated to phi-4 only. They tricked transformers code to disable SWA by setting SWA to a value higher than n_ctx_orig: https://huggingface.co/microsoft/Phi-4-multimodal-instruct/blob/main/config.json#L214

So I think the fix in llama.cpp is to check if `n_swa >= n_ctx_orig`. If that's the case, we disable `n_swa`. This will make sure phi-3 models with SWA still work correctly

File: src/llama-model.cpp (hunk 1 above)
Comment (ngxson) [reply src/llama-model.cpp:859]: Hmm ok it seems like `n_swa_pattern = 1` meaning all layers use SWA. I had a look at [modeling_phi3.py](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/blob/main/modeling_phi3.py#L459-L463) and seems like `use_sliding_windows` is set to the same value globally.

In anw, I think we can just remove SWA altogether for phi-3/phi-4 if you feel like we spent too much efforts fixing this.

**Review by ngxson — APPROVED** [review]

**Comment by SahibdeepMe** [comment]
idk previousluy it was running but now i use = 
.\llamafile-0.10.5.exe --server --model .\qwen2.5-3b-instruct-q4_k_m.gguf , model not running 

Help!!
Screenshot 2026-08-23 075724
 
image
