### PR TITLE
models : fix qwen3.5 beta/gate shapes

### LINKED ISSUE #19728: Eval bug: src/models/delta-net-base.cpp:316: GGML_ASSERT(g->ne[0] == 1 || g->ne[0] == S_v) failed
### Name and Version

version: 8099 (3bb2fcc85)
built with AppleClang 17.0.0.17000603 for Darwin arm64

### Operating systems

Mac

### GGML backends

Metal

### Hardware

Apple M3 Ultra

### Models

unsloth/Qwen3.5-397B-A17B-GGUF MXFP4_MOE

### Problem description & steps to reproduce

Crashes during model load.

### First Bad Commit

commit 27326bfce1f2cc688c042e4a75522a9619c2c48f
Author: Georgi Gerganov <ggerganov@gmail.com>
Date:   Thu Feb 19 08:17:49 2026 +0200

    models : dedup qwen35 graphs (#19660)
    
    * models : dedup qwen35 graphs
    
    * cont : add missing sigmoid

### Relevant log output

<details>
<summary>Logs</summary>

```console
/opt/hal/llama.cpp/src/models/delta-net-base.cpp:316: GGML_ASSERT(g->ne[0] == 1 || g->ne[0] == S_v) failed
WARNING: Using native backtrace. Set GGML_BACKTRACE_LLDB for more info.
WARNING: GGML_BACKTRACE_LLDB may cause native MacOS Terminal.app to crash.
See: https://github.com/ggml-org/llama.cpp/pull/17869
0   libggml-base.0.9.7.dylib            0x00000001050c13bc ggml_print_backtrace + 276
1   libggml-base.0.9.7.dylib            0x00000001050c15a8 ggml_abort + 156
2   libllama.0.0.8099.dylib             0x0000000104ee9b7c _ZN15llm_build_dots1C2ERK11llama_modelRK16llm_graph_params + 0
3   libllama.0.0.8099.dylib             0x0000000104f0bf04 _ZN19llm_build_qwen35moe23build_layer_attn_linearEP18llm_graph_input_rsP11ggml_tensori + 2072
4   libllama.0.0.8099.dylib             0x0000000104f0b494 _ZN19llm_build_qwen35moeC2ERK11llama_modelRK16llm_graph_params + 320
5   libllama.0.0.8099.dylib             0x0000000104e94f40 _ZNSt3__111make_uniqueB8ne200100I19llm_build_qwen35moeJRK11llama_modelRK16llm_graph_paramsELi0EEENS_10unique_ptrIT_NS_14default_deleteIS9_EEEEDpOT0_ + 52
6   libllama.0.0.8099.dylib             0x0000000104e92564 _ZNK11llama_model11build_graphERK16llm_graph_params + 1216
7   libllama.0.0.8099.dylib             0x0000000104df7670 _ZN13llama_context13graph_reserveEjjjPK22llama_memory_context_ibPm + 668
8   libllama.0.0.8099.dylib             0x0000000104df662c _ZN13llama_context13sched_reserveEv + 552
9   libllama.0.0.8099.dylib             0x0000000104df55d8 _ZN13llama_contextC2ERK11llama_model20llama_context_params + 4300
10  libllama.0.0.8099.dylib             0x0000000104dff324 llama_init_from_model + 544
11  libllama.0.0.8099.dylib             0x0000000104ddefc4 _ZL28llama_get_device_memory_dataPKcPK18llama_model_paramsPK20llama_context_paramsRNSt3__16vectorIP19ggml_backend_deviceNS7_9allocatorISA_EEEERjSF_SF_14ggml_log_level + 240
12  libllama.0.0.8099.dylib             0x0000000104dda8e4 llama_params_fit + 184
13  llama-server                        0x0000000104440918 _ZN18common_init_resultC2ER13common_params + 380
14  llama-server                        0x0000000104441d68 _Z23common_init_from_paramsR13common_params + 60
15  llama-server                        0x000000010436b780 _ZN19server_context_impl10load_modelERK13common_params + 188
16  llama-server                        0x00000001042c5c74 main + 11996
17  dyld                                0x000000019a945d54 start + 7184

```
</details>

### PR DESCRIPTION
**Pull request by ggerganov**
fix #19728
cont #19660 

Forgot to update the `beta` / `gate` shapes after the refactor.

### CODE REVIEW

File: src/models/qwen35.cpp [hunk 1]
```diff
@@ -232,6 +232,9 @@ ggml_tensor * llm_build_qwen35::build_layer_attn_linear(
     ggml_tensor * gate = ggml_mul(ctx0, alpha_softplus, model.layers[il].ssm_a);  // -A_log.exp() * softplus
     cb(gate, "gate", il);
 
+    beta = ggml_reshape_4d(ctx0, beta, 1, num_v_heads, n_seq_tokens, n_seqs);
```
Comment (CISC) [inline src/models/qwen35.cpp]: Can't it just be shaped like this to begin with? Or is that sub-optimal for some backend?

Comment (ggerganov) [reply src/models/qwen35.cpp]: The shape of `beta` seems to be fundamentally driven by the `ssm_alpha` weight tensor (see the matrix multiplication above). I actually didn't look at it in details, but my assumption is it would likely require reshaping the weights in some way? Not sure.

Comment (CISC) [reply src/models/qwen35.cpp]: I'm not sure I follow, `beta` just goes through `sigmoid` before this point?

Comment (ggerganov) [reply src/models/qwen35.cpp]: Do you mean to move the reshape before the sigmoid? What would be the benefit of that?

Comment (CISC) [reply src/models/qwen35.cpp]: Probably nothing, just seemed unnecessary.

Comment (ggerganov) [reply src/models/qwen35.cpp]: I see now - yes, it's better to do it before the sigmoid to avoid an unnecessary reshape.
