### PR TITLE
grammar : support array references in json schema

### LINKED ISSUE #16790: Misc. bug: JSON schema to grammar does not support array references
### Name and Version

```
$ llama-cli --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
version: 6841 (54c618222)
built with MSVC 19.43.34810.0 for x64
```

Original issue by @serjrd https://github.com/ggml-org/llama.cpp/issues/16714#issuecomment-3431179568

### Operating systems

Windows

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell

```

### Problem description & steps to reproduce

The JSON schema to grammar does not support references to items in an array.

```
curl http://localhost:8080/v1/chat/completions -d '{
  "model": "gpt-oss-20b",
  "messages": [
    {
      "role": "user",
      "content": "Build a binary tree that matches (A (B C D) E)"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "build_binary_tree",
        "description": "build a binary tree. The left/right fields may be either a string value or another tree.",
        "parameters": {
          "type": "object",
          "properties": {
            "tree": {
              "type": "object",
              "properties": {
                "left": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "$ref": "#/properties/tree"
                    }
                  ]
                },
                "right": {
                  "anyOf": [
                    {
                      "$ref": "#/properties/tree/properties/left/anyOf/0"
                    },
                    {
                      "$ref": "#/properties/tree"
                    }
                  ]
                }
              },
              "additionalProperties": false
            }
          },
          "required": [
            "tree"
          ],
          "additionalProperties": false,
          "$schema": "http://json-schema.org/draft-07/schema#"
        }
      }
    }
  ],
  "tool_choice": "auto"
}'
```

### First Bad Commit

_No response_

### Relevant log output

```json
{
  "error": {
    "code": 500,
    "message": "JSON schema conversion failed:\nError resolving ref #/properties/tree/properties/left/anyOf/0: 0 not in [{\"type\":\"string\"},{\"$ref\":\"#/properties/tree\"}]",
    "type": "server_error"
  }
}
```

### PR DESCRIPTION
**Pull request by aldehir**
fixes #16790

related:  https://github.com/ggml-org/llama.cpp/issues/16714#issuecomment-3431179568.

The JSON schema to grammar conversion does not support referencing array items. It appears zod or the MCP library may do this to reuse schemas instead of creating a separate definition.

<details>
<summary>Example</summary>

```bash
curl http://localhost:8080/v1/chat/completions -d '{
  "model": "gpt-oss-20b",
  "messages": [
    {
      "role": "user",
      "content": "Build a binary tree that matches (A (B C D) E)"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "build_binary_tree",
        "description": "build a binary tree. The left/right fields may be either a string value or another tree.",
        "parameters": {
          "type": "object",
          "properties": {
            "tree": {
              "type": "object",
              "properties": {
                "left": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "$ref": "#/properties/tree"
                    }
                  ]
                },
                "right": {
                  "anyOf": [
                    {
                      "$ref": "#/properties/tree/properties/left/anyOf/0"
                    },
                    {
                      "$ref": "#/properties/tree"
                    }
                  ]
                }
              },
              "additionalProperties": false
            }
          },
          "required": [
            "tree"
          ],
          "additionalProperties": false,
          "$schema": "http://json-schema.org/draft-07/schema#"
        }
      }
    }
  ],
  "tool_choice": "auto"
}'
```
</details>

The example above will fail with:

```json
{
  "error": {
    "code": 500,
    "message": "JSON schema conversion failed:\nError resolving ref #/properties/tree/properties/left/anyOf/0: 0 not in [{\"type\":\"string\"},{\"$ref\":\"#/properties/tree\"}]",
    "type": "server_error"
  }
}
```

This PR adds support for referencing array items.

Since indexes are less unique than object keys, it also renames the grammar rules derived from references.

Currently, the rules are named after the last component of the reference. E.g. `#/properties/tree => tree`. That doesn't work well with indexes, so instead this PR names them as follows:

1. Extract the content after `#`.
2. Replace non-alphanumeric characters with a dash `-`.
3. Prefix with `ref`

This results in `#/properties/tree => ref-properties-tree` as the grammar rule name.

@ochafik I would like your opinion on the rule naming. I don't know if there is any additional impact I am not seeing.

Here is the same example against this PR:

```json
{
  "model": "unsloth/gpt-oss-20b",
  "choices": [
    {
      "finish_reason": "tool_calls",
      "index": 0,
      "message": {
        "role": "assistant",
        "reasoning_content": "We need to use the function build_binary_tree. The f...",
        "content": null,
        "tool_calls": [
          {
            "type": "function",
            "function": {
              "name": "build_binary_tree",
              "arguments": "{\"tree\":{\"left\":{\"left\":\"C\",\"right\":\"D\"},\"right\":\"E\"}}"
            },
            "id": "NHd0M0zGWTx1XG6DN2NalUqMT0b8GVb3"
          }
        ]
      }
    }
  ]
}
```

And the grammar rules generated:

```
build-binary-tree-args ::= "{" space build-binary-tree-args-tree-kv "}" space
build-binary-tree-args-tree ::= "{" space  (build-binary-tree-args-tree-left-kv build-binary-tree-args-tree-left-rest | build-binary-tree-args-tree-right-kv )? "}" space
build-binary-tree-args-tree-kv ::= "\"tree\"" space ":" space build-binary-tree-args-tree
build-binary-tree-args-tree-left ::= string | build-binary-tree-args-tree-left-1
build-binary-tree-args-tree-left-1 ::= ref-properties-tree
build-binary-tree-args-tree-left-kv ::= "\"left\"" space ":" space build-binary-tree-args-tree-left
build-binary-tree-args-tree-left-rest ::= ( "," space build-binary-tree-args-tree-right-kv )?
build-binary-tree-args-tree-right ::= build-binary-tree-args-tree-right-0 | build-binary-tree-args-tree-right-1
build-binary-tree-args-tree-right-0 ::= string
build-binary-tree-args-tree-right-1 ::= ref-properties-tree
build-binary-tree-args-tree-right-kv ::= "\"right\"" space ":" space build-binary-tree-args-tree-right
build-binary-tree-call ::= "build_binary_tree"channel " <|constrain|>json"? "<|message|>" build-binary-tree-args
build-binary-tree-call0 ::= "build_binary_tree" " <|constrain|>json"? "<|message|>" build-binary-tree-args
channel ::= "<|channel|>" ( "commentary" | "analysis" )
char ::= [^"\\\x7F\x00-\x1F] | [\\] (["\\bfnrt] | "u" [0-9a-fA-F]{4})
recipient-in-channel ::= channel " to=functions." ( build-binary-tree-call0 )
recipient-in-role ::= "<|start|>assistant"? " to=functions." ( build-binary-tree-call )
ref-properties-tree ::= "{" space  (ref-properties-tree-left-kv ref-properties-tree-left-rest | ref-properties-tree-right-kv )? "}" space
ref-properties-tree-left ::= string | ref-properties-tree-left-1
ref-properties-tree-left-1 ::= ref-properties-tree
ref-properties-tree-left-kv ::= "\"left\"" space ":" space ref-properties-tree-left
ref-properties-tree-left-rest ::= ( "," space ref-properties-tree-right-kv )?
ref-properties-tree-right ::= ref-properties-tree-right-0 | ref-properties-tree-right-1
ref-properties-tree-right-0 ::= string
ref-properties-tree-right-1 ::= ref-properties-tree
ref-properties-tree-right-kv ::= "\"right\"" space ":" space ref-properties-tree-right
root ::= recipient-in-role | recipient-in-channel
space ::= | " " | "\n"{1,2} [ \t]{0,20}
string ::= "\"" char* "\"" space
```

### CODE REVIEW

File: common/json-schema-to-grammar.cpp [hunk 1]
```diff
@@ -601,7 +601,11 @@ class SchemaConverter {
     }
 
     std::string _resolve_ref(const std::string & ref) {
-        std::string ref_name = ref.substr(ref.find_last_of('/') + 1);
+        std::string ref_fragment = ref;
+        if (ref.find('#') != std::string::npos) {
+            ref_fragment = ref.substr(ref.find('#') + 1);
+        }
```
Comment (CISC) [inline common/json-schema-to-grammar.cpp]:
```suggestion
        auto it = ref.find('#');
        std::string ref_fragment = it != std::string::npos ? ref.substr(it + 1) : ref;
```

**Review by ggerganov — APPROVED** [review]

**Comment by CISC** [comment]
@aldehir Do you need someone to merge for you and/or are you waiting for @ochafik?

File: common/json-schema-to-grammar.cpp [hunk 2]
```diff
@@ -601,7 +601,9 @@ class SchemaConverter {
     }
 
     std::string _resolve_ref(const std::string & ref) {
-        std::string ref_name = ref.substr(ref.find_last_of('/') + 1);
+        auto it = ref.find('#');
+        std::string ref_fragment = it != std::string::npos ? ref.substr(it + 1) : ref;
+        std::string ref_name = "ref" + std::regex_replace(ref_fragment, std::regex(R"([^a-zA-Z0-9-])"), "-");
```
Comment (ochafik) [inline common/json-schema-to-grammar.cpp]: nit: define `static const std::regex replaceableCharsRx(R"([^a-zA-Z0-9-]+)");`

File: examples/json_schema_to_grammar.py [hunk 3]
```diff
@@ -547,7 +556,8 @@ def join_seq():
 
 
     def _resolve_ref(self, ref):
-        ref_name = ref.split('/')[-1]
+        ref_fragment = ref.split('#')[-1]
+        ref_name = 'ref' + re.sub(r'[^a-zA-Z0-9-]', '-', ref_fragment)
```
Comment (ochafik) [inline examples/json_schema_to_grammar.py]: nit: `[^a-zA-Z0-9-]+` (+)

File: tools/server/public_legacy/json-schema-to-grammar.mjs [hunk 4]
```diff
@@ -594,7 +598,8 @@ export class SchemaConverter {
   }
 
   _resolveRef(ref) {
-    let refName = ref.split('/').pop();
+    let refFragment = ref.split('#').pop();
+    let refName = 'ref' + refFragment.replace(/[^a-zA-Z0-9-]/, '-');
```
Comment (ochafik) [inline tools/server/public_legacy/json-schema-to-grammar.mjs]: Need to add `/g` otherwise this only replaces the first occurrence

`refFragment.replace(/[^a-zA-Z0-9-]+/g, '-')`

**Review by ochafik — COMMENTED** [review]
Thanks @aldehir !

Looks good (small nits), no objections re/ naming (looks neater!)

Could you share an example of zod schema that produces def arrays? The spec seems to say [defs must be an object](https://json-schema.org/draft-07/json-schema-validation#rfc.section.9) (which in json spec doesn't mean array i believe).

**Comment by aldehir** [comment]
@ochafik thank you for pointing that out, and for the feedback. This stemmed from the following (contrived) example in https://github.com/ggml-org/llama.cpp/issues/16714#issuecomment-3431179568:

```javascript
const SomeObject = z.object({ test: z.string() })

const testType = z.lazy(() =>
  z.object({
    and: z.union([SomeObject, testType]),
    or: z.union([SomeObject, testType]),
    not: z.union([SomeObject, testType])
  })
)

server.registerTool('test',
  {
    title: 'Get test record by ID',
    description: 'Get test record by ID',
    inputSchema: {
      test: testType
    }
  },
  ({ testId }) => {
    return {
      content: [{ type: 'text', text: 'You requested test record ID: ' + testId }]
    }
  }
)
```

Which produces:

```json
{
  "type": "object",
  "properties": {
    "test": {
      "type": "object",
      "properties": {
        "and": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "test": {
                  "type": "string"
                }
              },
              "required": [
                "test"
              ],
              "additionalProperties": false
            },
            {
              "$ref": "#/properties/test"
            }
          ]
        },
        "or": {
          "anyOf": [
            {
              "$ref": "#/properties/test/properties/and/anyOf/0"
            },
            {
              "$ref": "#/properties/test"
            }
          ]
        },
        "not": {
          "anyOf": [
            {
              "$ref": "#/properties/test/properties/and/anyOf/0"
            },
            {
              "$ref": "#/properties/test"
            }
          ]
        }
      },
      "required": [
        "and",
        "or",
        "not"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "test"
  ],
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-07/schema#"
}
```

It does not appear specific to Zod's new `toJSONSchema()` function in v4, but rather the MCP typescript library which still uses zod v3.

I used a definitions array only to keep the test case simple. I updated it to reference a schema in `anyOf` instead.

**Comment by aldehir** [comment]
@CISC, barring any objections, it is ready to merge. I do not have the ability to do so.

**Comment by ochafik** [comment]
> It does not appear specific to Zod's new toJSONSchema() function in v4, but rather the MCP typescript library which still uses zod v3.

@aldehir Ah indeed, it's a [zod-to-json-schema](https://www.npmjs.com/package/zod-to-json-schema) thing (`console.log(JSON.stringify(z.toJSONSchema(testType), null, 2))` w/ v4 doesn't use the array defs, while `console.log(JSON.stringify(zodToJsonSchema(testType), null, 2))` w/ v3 does)

Still worth supporting given its (temporary) popularity (until v4 fully takes over).
